### ISSUE TITLE
Clarification Regarding Usage of Java.util

### ISSUE THREAD

**Issue by Vatinius** [nus-cs2103-AY2425S1/forum#10]
Hi! I would like to clarify if we are allowed to use everything under java.util without needing to request for permission, as it is not a third-party library? For example, to import java.util.scanner and java.util.ArrayList for my ip, etc.

Thank you!

**Comment by RezwanAhmed123** [comment]
I think that’s correct, third party libraries would be libraries not created by Oracle such as Junit (for unit testing).

**Comment by damithc** [comment]
> I think that’s correct, third party libraries would be libraries not created by Oracle such as Junit (for unit testing).

@RezwanAhmed123's answer is in the right direction. No need to ask for permission to use anything that comes with the JDK, or even third party libraries we have specifically asked you to use (JUnit falls into the latter category, as we will be asking you to use it in the iP at some point). But _other_ third party libraries need permission.

**Comment by Vatinius** [comment]
Noted! Thank you so much for the clarifications @RezwanAhmed123 @damithc!!
