### ISSUE TITLE
.gitignore not ignoring the files

### ISSUE THREAD

**Issue by Judy1x4** [nus-cs2103-AY2425S1/forum#101]
IntelliJ version: IntelliJ IDEA 2023.3.2 (Community Edition)
Java version: 17.0.10
OS: Windows

My .gitignore file looks as follows: 

```# IDEA files
/.idea/
/out/
/*.iml

# Gradle build files
/.gradle/
/build/
src/main/resources/docs/

# MacOS custom attributes files created by Finder
.DS_Store
*.iml
bin/

/text-ui-test/ACTUAL.TXT
text-ui-test/EXPECTED-UNIX.TXT

# files to be not revision controlled
*.class
*.jar
*.exe
/data/jude.txt
```

However, it seems like in the source tree the data.jude file (for the saving purpose) is still in the unstaged files section.
![image](https://github.com/user-attachments/assets/427db395-6470-44e2-982f-727a8aced578)

**Comment by damithc** [comment]
@Judy1x4 While waiting for peer inputs, one simple thing you can try is to refresh the Sourcetree UI (F5 in Windows) to see if that helps.
Also, you can right-click on the unstaged file (i.e., the one inside the redbox in your screenshot) and choose 'ignore ...' to see if that works

**Comment by Domokunx** [comment]
@Judy1x4 Hi. I suspect what happened is that you committed those 2 files before updating your .gitignore. So those files will continue being tracked despite specifically updating to ignore it afterwards.

What you can do is:
1. first commit all current changes (to be safe)
2. run ```git rm --cached build.gradle data/jude.txt``` 
3. commit 

And hopefully it works!

**Comment by Judy1x4** [comment]
@Domokunx  This has resolved my issue. Thank you!

**Comment by damithc** [comment]
Good catch @Domokunx 💯
