### ISSUE TITLE
Coding standard for switch case

### ISSUE THREAD

**Issue by DKHB0207** [nus-cs2103-AY2425S1/forum#102]
Can I ask for course coding standard, when using switch and case, is it a must to include default as well?

**Comment by sayglenn** [comment]
<img width="829" alt="Screenshot 2024-08-29 at 10 48 19 AM" src="https://github.com/user-attachments/assets/0b17b849-d4d6-4d7a-a24d-718f0dbd2796">

Hi Daryl, it looks like typically the examples given in the Java coding convention have a default case. It should be good practice to have a default case to handle a case not included in the switch statement.

**Comment by itsme-zeix** [comment]
Seems like it wasn't specified, but I don't see any reason not to include it for robustness. No harm with at least logging the default case or throwing an exception so the program doesn't silently fail.

**Comment by rxchell** [comment]
Agreeing with the points above, it would be good practice to include the default case to handle values (e.g by throwing an exception) that are not explicitly handled by the cases. The example in the Java documentation includes the default case as well: https://docs.oracle.com/javase/tutorial/java/nutsandbolts/switch.html

**Comment by damithc** [comment]
To add to this discussion, this aspect is covered in a future topic https://nus-cs2103-ay2425s1.github.io/website/se-book-adapted/chapters/codeQuality.html#use-the-default-branch
However, this is a general code quality guideline, not part of the coding standard.
