### ISSUE TITLE
Git Standard tag

### ISSUE THREAD

**Issue by MinkhantEain** [nus-cs2103-AY2425S1/forum#103]
Hi, I think one of my commits that has already been pushed violated the git standard which result in git standard criteria not being met. So in order to meet the git standard criteria, do i push some random commits or do I just have to leave it for the next ip?

**Comment by damithc** [comment]
@MinkhantEain No need to push random commits. This aspect is checked every time the dashboard is updated, until the end of iP. So, it will turn green eventually if you follow the Git convention from now on. There is no penalty for having it red for a short while.
