### ISSUE TITLE
Question about downloading of JavaFX for AddressBook

### ISSUE THREAD

**Issue by Ma-Xizi** [nus-cs2103-AY2425S1/forum#104]
My OS: MacOS Monterey
Hi! I just found that I could not just run addressbook.jar. The only external library I have in my project is corretto-17 as my java JDK. I have attached my error message below; but I am thinking whether I should download javaFX manually from GLUON and add it somewhere(not sure tho). 

edited: I have discovered that my Terminal is using Java19 instead of corretto-17 in my preference setting and project structure of IDE:( dunno why it did not give rise to an error for my IP, but I have fixed it now) I also try to use a specific javafx, sudo mv ~/Downloads/javafx-sdk-22.0.2 /Users/maxizi/.openjfx/
I used aarch64 JDK one.

edited the second time : I have done debugging by using:  java --module-path /Users/maxizi/.openjfx/javafx-sdk-22.0.2/lib --add-modules javafx.controls,javafx.fxml -jar addressbook.jar

Still I am not sure why it occurred lol.
Thanks for assistance!

**Comment by damithc** [comment]
@Ma-Xizi While waiting for inputs from others, it might be useful to share your OS, and the output for the `java -version` command.

**Comment by Ma-Xizi** [comment]
> @Ma-Xizi While waiting for inputs from others, it might be useful to share your OS, and the output for the `java -version` command.

I have just done debugging myself.:) Is it because my terminal is using a different version of java from java 17 at first? I was forced to download javaFX manually and update the path to JavaFX SDK manually as well.

**Comment by damithc** [comment]
@Ma-Xizi Is the error resolved now? 
Normally, you should be able to run AB3 JAR file without needing to install JavaFX separately.
What' your OS, exactly?

**Comment by oneBoz** [comment]
Hi I've encountered the same issue too! Mac OS M2 Macbook air
[ error ]

<img width="731" alt="Screenshot 2024-08-29 at 5 06 41 PM" src="https://github.com/user-attachments/assets/f5c137eb-fca7-4209-8f1b-c4cb188e02e9">

[ running java --version ]

<img width="566" alt="Screenshot 2024-08-29 at 5 07 49 PM" src="https://github.com/user-attachments/assets/b8f69d3b-dbe5-48d5-a444-301adb7232b7">


[ EDIT ]
hi I've fixed this issue after seeing the edit by @Ma-Xizi.

**Comment by zaidansani** [comment]
> edited: I have discovered that my Terminal is using Java19 instead of corretto-17 in my preference setting and project structure of IDE:( dunno why it did not give rise to an error for my IP. I also try to use a specific javafx, sudo mv ~/Downloads/javafx-sdk-22.0.2 /Users/maxizi/.openjfx/
> I used aarch64 JDK one.

It seems that you have found a workaround - but may I recommend that you check your `$JAVA_HOME` PATH variable? If your terminal is using Java19, there's a chance your current `$JAVA_HOME` points to that particular version of Java instead of the one you have to use, and it might be beneficial to change that for the rest of the module, at the very least.

**Comment by damithc** [comment]
> Hi I've encountered the same issue too! Mac OS M2 Macbook air

@oneBoz As you are a Mac user, do ensure you are using the precise version (not _any_ JDK 17) we have prescribed for Mac users https://nus-cs2103-ay2425s1.github.io/website/admin/programmingLanguages.html

**Comment by Ma-Xizi** [comment]
> @Ma-Xizi Is the error resolved now? Normally, you should be able to run AB3 JAR file without needing to install JavaFX separately. What' your OS, exactly?

Yes I have resolved it on MAC OS Monterey version 12.3. I went through a complicated process as I used a different version from the precise JDK 17 version as recommended. 

Later I switched to the specific Azul JDK 17 in the guide, everything became easy. Thanks a lot!

**Comment by Ma-Xizi** [comment]
> > edited: I have discovered that my Terminal is using Java19 instead of corretto-17 in my preference setting and project structure of IDE:( dunno why it did not give rise to an error for my IP. I also try to use a specific javafx, sudo mv ~/Downloads/javafx-sdk-22.0.2 /Users/maxizi/.openjfx/
> > I used aarch64 JDK one.
> 
> It seems that you have found a workaround - but may I recommend that you check your `$JAVA_HOME` PATH variable? If your terminal is using Java19, there's a chance your current `$JAVA_HOME` points to that particular version of Java instead of the one you have to use, and it might be beneficial to change that for the rest of the module, at the very least.

Yep you are right! I modified ~/.zshrc file to set my $JAVA_HOME variable later. By the way, SDKMAN is quite good at managing the version of Java.
