### ISSUE TITLE
gradle clean build checkstyleMain fail

### ISSUE THREAD

**Issue by itsnotsherm** [nus-cs2103-AY2425S1/forum#105]
```
plugins {
    id 'java'
    id 'application'
    id 'checkstyle'
    id 'com.github.johnrengelman.shadow' version '7.1.2'
}
```

I've added the plugin for checkstyle as shown above and in the tutorial but whenever I run ./gradlew clean build on IntelliJ or CLI I always get a build failure, message shown below.

![image](https://github.com/user-attachments/assets/37e87210-18a9-4401-9073-3dd702e37b4e)

Do advise on how to proceed, thank you!

**Comment by Rachelcoll** [comment]
![image](https://github.com/user-attachments/assets/7a1109be-04ea-474f-a892-2d9b477aec39)
maybe can try to copy checkstyle.xml and suppressions.xml from [AddressBook Level 3 project](https://github.com/se-edu/addressbook-level3/tree/master/config/checkstyle) to your local file
