### ISSUE TITLE
How to use checkstyle of gradle 

### ISSUE THREAD

**Issue by blackpanther9229** [nus-cs2103-AY2425S1/forum#106]
Have anyone try checkstyle of gradle? I followed the instructions and create .config/checkstyle with two file checkstyle.xml and suppression.xml in my directory. But this happened and I can not fix it.
![image](https://github.com/user-attachments/assets/609ab06c-fb35-40bb-9738-8f17c8f156aa)
![image](https://github.com/user-attachments/assets/0e4c3424-ccae-4f43-b5f4-fdb772451470)

**Comment by Rachelcoll** [comment]
Just put your mouse on the red link and the editor will pop out a window to let you include external url

**Comment by blackpanther9229** [comment]
> Just put your mouse on the red link and the editor will pop out a window to let you include external url

Thanks bro. But now when I try run the .\gradlew checkstyleMain, this happened. 
![image](https://github.com/user-attachments/assets/9eed8150-c728-48e9-8532-8d44beea6ea7)

**Comment by damithc** [comment]
@blackpanther9229 See if [this](https://github.com/nus-cs2103-AY2425S1/forum/issues/105#issuecomment-2316738260) helps.

**Comment by blackpanther9229** [comment]
> @blackpanther9229 See if [this](https://github.com/nus-cs2103-AY2425S1/forum/issues/105#issuecomment-2316738260) helps.

Thank you Prof. It seems this is just about setting up the Intellij to recognise this URI https://checkstyle.org/dtds/configuration_1_3.dtd (which is my initial problem).

**Comment by damithc** [comment]
@blackpanther9229 The usual fix for the `unable to create root module` error you are facing now is to add the two missing config files, as [this](https://github.com/nus-cs2103-AY2425S1/forum/issues/105#issuecomment-2316738260) mentions.

**Comment by chenle228** [comment]
```
> Thank you Prof. It seems this is just about setting up the Intellij to recognise this URI https://checkstyle.org/dtds/configuration_1_3.dtd (which is my initial problem).
```

Hi @blackpanther9229 , can I ask how you set up the Intellij to recognise the external URL? I tried adding External DTD URLs in my **IntelliJ File → Settings→ Languages & Frameworks → Schemas and DTDs**, but I was still facing the same error when running`./gradlew checkstyleMain checkstyleTest`


<img width="727" alt="1724984503736" src="https://github.com/user-attachments/assets/06efae8b-873a-42c2-a8ac-99fdde894c04">
<img width="711" alt="1724984528099" src="https://github.com/user-attachments/assets/7be983de-18cb-4cd8-ae63-3d3efde9f240">

**Comment by damithc** [comment]
> but I was still facing the same error when running`./gradlew checkstyleMain checkstyleTest`

@blackpanther9229 When running checkstyle in the terminal like this, it doesn't even use Intellij settings. So, the external dtd is not the issue. 
Have you added the two config files, as suggested previously? They are needed irrespective of the dtd issue, so add them anyway, and try again.

**Comment by chenle228** [comment]
Hi prof @damithc , thank you so much for your swift response and clarifications on Gradle vs Intellij settings, the issues have been resolved after I added the two config files! Appreciate your help:)

**Comment by yadobler** [comment]
> but I was still facing the same error when running`./gradlew checkstyleMain checkstyleTest`

If you want to go through the gradle route of checkstyle, you must update the `build.gradle` file to include `id('checkstyle')`, and add the dependency for checkstyle (using the correct toolset version)

If done right, you can run the above command and you'll get a lot of errors, and a link to a generated html file detailing all the errors.
