### ISSUE TITLE
Problem following JavaFX Tutorial on newer Mac versions

### ISSUE THREAD

**Issue by jinnsuke** [nus-cs2103-AY2425S1/forum#107]
Hi! 

I am currently trying to follow the JavaFX tutorial at [https://se-education.org/guides/tutorials/javaFxPart1.html](url) but when I run ./gradlew run, I keep getting an error and I can't find a solution. 

According to ChatGPT, the error says
"The error you're encountering is related to JavaFX and its native libraries not being compatible with your system architecture. Specifically, it indicates that JavaFX is trying to load native libraries (libprism_es2.dylib and libprism_sw.dylib) that are built for the x86_64 architecture, but your system requires arm64 architecture (which is typical for newer Macs with Apple Silicon)."

Based on the tutorial, we were asked to update our build.gradle using String javaFxVersion = '17.0.7' but it seems like this won't work for new Mac versions. 

Please help! Thank you!

Edit: I am getting a similar error when I try to run addressbook.jar. I think both issues need the same solution.

**Comment by damithc** [comment]
@jinnsuke While waiting for peer inputs, you can share more info to aid the troubleshooting e.g.,
* What's your OS?
* If it is MacOS, have you followed our advisor for Mac users, given [here](https://nus-cs2103-ay2425s1.github.io/website/admin/programmingLanguages.html#programming-language)?
* What's the output for `java -version` command?
* What's the error message?

**Comment by jinnsuke** [comment]
@damithc 
1. I am using MacOS Ventura 13.5
2. Yup, I've followed the advisor
3. The output is 

> java version "17.0.12" 2024-07-16 LTS
> Java(TM) SE Runtime Environment (build 17.0.12+8-LTS-286)
> Java HotSpot(TM) 64-Bit Server VM (build 17.0.12+8-LTS-286, mixed mode, sharing)

4. The error message is 

> java.lang.UnsatisfiedLinkError: /Users/shoujinsugimoto/.openjfx/cache/17.0.7/libprism_es2.dylib: dlopen(/Users/shoujinsugimoto/.openjfx/cache/17.0.7/libprism_es2.dylib, 0x0001): tried: '/Users/shoujinsugimoto/.openjfx/cache/17.0.7/libprism_es2.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/shoujinsugimoto/.openjfx/cache/17.0.7/libprism_es2.dylib' (no such file), '/Users/shoujinsugimoto/.openjfx/cache/17.0.7/libprism_es2.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

**Comment by damithc** [comment]
> 2\. Yup, I've followed the advisor
> 
>     3\. The output is
> 
> 
> > java version "17.0.12" 2024-07-16 LTS
> > Java(TM) SE Runtime Environment (build 17.0.12+8-LTS-286)
> > Java HotSpot(TM) 64-Bit Server VM (build 17.0.12+8-LTS-286, mixed mode, sharing)

🤔 Are you sure? This output doesn't look like it came from the Azul JDK we prescribed for MacOS.

**Comment by jinnsuke** [comment]
@damithc Thanks for pointing that out! Completely overlooked that section. Will follow the instructions :)
