### ISSUE TITLE
Level-9 Find requirements

### ISSUE THREAD

**Issue by lavanyagarg112** [nus-cs2103-AY2425S1/forum#110]
Hello, I just wanted to check regarding the level-9 find requirements, is it enough to just search for the keyword in the task name, or for eg: 

- if the user puts in the date, the tasks containing that date/time must be shown?
- if the user puts in "todo", the tasks which are of type todo must be shown?

Thanks!

**Comment by damithc** [comment]
@lavanyagarg112 Minimally, the the search should search the task description for the given keyword. You and add more sophisticated search abilities if you wish, but it's not a requirement.

**Comment by lavanyagarg112** [comment]
ok thank you prof!
