### ISSUE TITLE
Not sure iP dashboard at the top is my dashboard

### ISSUE THREAD

**Issue by Judy1x4** [nus-cs2103-AY2425S1/forum#112]
On my iP dashboard, I can't clearly identify which table reflects my progress. At first, I assumed the iP progress table at the top was tracking my work, but I noticed the partial student ID listed does not match mine.

![image](https://github.com/user-attachments/assets/3e5e6dd1-8d0d-4b82-8f7d-1425c76e292e)

This is an image of the topmost table — while the progress seems similar to mine, I'm unsure if this is actually my table.

**Comment by Incogdino** [comment]
You can ctrl + F with the last 5 digits of your student id to find your own progress dashboard
