### ISSUE TITLE
Git Convention

### ISSUE THREAD

**Issue by JoanneHing** [nus-cs2103-AY2425S1/forum#115]
I had read the site [](https://se-education.org/guides/conventions/git.html#commit-message-body) about Git Convention for commit message. But I want to ask is it okay for us to follow the Conventional Commit Format(exp feat: Add searching fucntionality) or should we follow the one stated at the CS2103T site?

**Comment by damithc** [comment]
@JoanneHing You need to follow our convention. However, the following clause in our convention opens the door for you to get close to the _Conventional Commits_ Format.

![image](https://github.com/user-attachments/assets/ab9ac837-3ed1-4547-8567-75d25311479f)

**Comment by JoanneHing** [comment]
So I am allow to write something like 
`feature: Add delete task command`
Or is it better to just write
`Add delete task command`

Thank you for the clarification!

**Comment by damithc** [comment]
> So I am allow to write something like
> `feature: Add delete task command`
> Or is it better to just write
> `Add delete task command`

@JoanneHing Both are allowed. So, in the iP, the choice is yours. In the tP, the team can decide which of the two style you want to follow, and the whole team should follow the chosen style.

**Comment by JoanneHing** [comment]
Alright! Thank you prof for clarifying my doubts!
