### ISSUE TITLE
How to write test for Ui.java

### ISSUE THREAD

**Issue by huangjiaxi1111** [nus-cs2103-AY2425S1/forum#116]
Lets say I want to test for 
```java
public void showLoadingError() {
    System.out.println("Error loading tasks.");
}
```
How do I test for such output to the terminal?

**Comment by RezwanAhmed123** [comment]
I wouldn’t necessarily test this method (as with any method that merely prints stuff) as it seems very trivial. I would rather test the method that may cause this method to be called on, which in this case should be something like `loadTasks()`.

In the testing for the `loadTasks()` method, I would add a test putting in a corrupted file or write some gibberish to the file first before calling `loadTasks()` on it to see if the error is handled correctly. This should let you know if it’s working as intended.

**Comment by gohsl99** [comment]
This https://www.baeldung.com/java-testing-system-out-println may help (using JUnit).
