### ISSUE TITLE
Exception Handling in java.nio.file vs java.io.File

### ISSUE THREAD

**Issue by psh12320** [nus-cs2103-AY2425S1/forum#117]
I was trying to understand the differences in exception handling offered by `java.nio.file` vs `java.io.File` and would like to know which package is more recommended.

It seems that the exceptions in `java.nio.file` are more specific than in `java.io.File`. For example, when `duke.txt` is not found, the former would throw a `NoSuchFileException` compared to the latter which would throw an `IOException`.

Is there any recommendation or are we free to experiment and change along the way?

**Comment by Incogdino** [comment]
According to this [online](https://www.geeksforgeeks.org/difference-between-java-io-and-java-nio/) article, nio is an improvement to the current io, hence the name "new io".

The key difference is just how java handles the data. Previously it was handled using streams so data transfer would be synchronous. With nio, data is handled asynchronously and thus more threads are free to do other work. 

Another thing that you mentioned is that it would throw more exceptions and they are also more specific. I guess this is better as you can now catch more errors and exceptions before it gets into production. 

Given a choice, I guess I would just go with nio. (Its newer and more powerfull after all 😆)
