### ISSUE TITLE
How do I move my master up to the other branches

### ISSUE THREAD

**Issue by niclammm** [nus-cs2103-AY2425S1/forum#118]
Due to some mistakes, I had to hard reset my git in order to save my progress. However, doing so moved my master to the current location below my previous tags. How do I go about fixing this 
![Help wanted](https://github.com/user-attachments/assets/3a7590f0-5e03-4ed3-a50d-11884b01f875)

**Comment by Anant1902** [comment]
Hi @niclammm, I am a senior from your previous batch! If you're trying to move master to your latest commit (which I'm assuming is on the blue line branch, you can try running the code below on your local repo:
`git checkout master`
`git reset <branch-name>` where branch-name is the name of the blue line branch

**Comment by NeoHW** [comment]
Hi @niclammm , I am a senior from your previous batch dropping in to help! 
From your image it looks like you want to reset the `master` to the one with `A-moreOOP`. 
I recommend:
1. `git checkout master`
2. `git reset --hard <commit-hash>` (replace commit-hash with the one on the column with "commit")
3. you might want to update your remote branch by force pushing if necessary `git push origin master --force`
A word of advice before force pushing, try to read up on it and understand what is going on before doing it!

**Comment by damithc** [comment]
GUI method:
Right-click on the commit you want the currently selected branch (i.e., `master` branch) to move to, and choose `Reset current branch to this commit`.

**Comment by niclammm** [comment]
Thank you for help!
