### ISSUE TITLE
gradle does not seem to allow me to run main, constantly says the main class not found

### ISSUE THREAD

**Issue by martout2002** [nus-cs2103-AY2425S1/forum#119]
<img width="1511" alt="Screenshot 2024-08-29 at 11 50 36 PM" src="https://github.com/user-attachments/assets/d71dc35e-69bc-49c9-bbe9-9bcd9f739bd6">

Help me please

**Comment by Incogdino** [comment]
According to your repo on github, it seems that your mainClass.set("...") in your build.gradle points to the default location. You need to set it to point to the correct file where main exists in your program

**Comment by Incogdino** [comment]
Not too sure why, but your fork is missing two folder directories, namely `main` and `java` as shown here with an example in y repo

![image](https://github.com/user-attachments/assets/1e102c12-a9ec-4ea0-aff5-dda669d11899)

Adding these two directories should solve your issue

Alternatively, you can refer to this post on stackoverflow if you do not wish to add the directories

https://stackoverflow.com/questions/24924932/gradle-could-not-find-or-load-main-class

**Comment by martout2002** [comment]
Omg it works, i just added the two files, IT WORKS I LOVE YOU SO MUCH
