### ISSUE TITLE
error when downloading java 17 on mac

### ISSUE THREAD

**Issue by jiaaaaen** [nus-cs2103-AY2425S1/forum#12]
was following the java 17 installation guide for macs and downloaded sdkman already, but when i run 

jiaen@jia-ens-MacBook-Pro ~ % sdk install java 17.0.11.fx-zulu

Downloading: java 17.0.11.fx-zulu

In progress...

######################################################################### 100.0%curl: (33) HTTP server doesn't seem to support byte ranges. Cannot resume.

Download has failed, aborting!

Can not install Java 17.0.11.fx-zulu at this time...

^^ this error comes up 

any help will be appreciated thank you!

**Comment by NeoHW** [comment]
Hi @jiaaaaen, I'm from your senior batch. Here are a few suggestions to solve your current problem:

1. Regarding the problem with the curl bug: [this discussion](https://github.com/sdkman/sdkman-cli/issues/1288) might be of use to you!
   - From the discussion, try:
     * Running `sdk flush` or
     * cURL's `--remove-on-errors` option

2. Another solution would be to download and install the Azul build of OpenJDK 17 version found [here](https://www.azul.com/downloads/?version=java-17-lts&os=macos&architecture=arm-64-bit&package=jdk-fx#zulu) (scroll to the bottom of the page).

**Comment by jiaaaaen** [comment]
@NeoHW 

sdk flush works! thankss
