### ISSUE TITLE
Code does not run after deleting .idea file in ip folder

### ISSUE THREAD

**Issue by FlyingDonkeys** [nus-cs2103-AY2425S1/forum#120]
I was trying to get Gradle to work but am currently facing issues after deleting the .idea file. Was tinkering with the commands given in the 2103T website tutorial but cant seem to get it to work. Also accidentally invalidated caches in an attempt to fix the errors but inadvertently deleted my local history so I cannot rollback to a previous local version... Code cannot be compiled anymore and doing git pull on my previous work does not seem to make the code runnable. Any suggestions?

**Comment by damithc** [comment]
@FlyingDonkeys While waiting for others to help, can you post a screenshot of your current project folder contents?
How did you try to run the gradle commands (can you post a screenshot of that too)?

**Comment by yadobler** [comment]
What's the "error" happening? Is it incorrect jdk? Jdk not found? Something like `unable to open cp_proj`? Or unable to find main / entry point? 

Also do tell which os you're using cos for example Linux / nixos has been a pain to resolve.

**Comment by itsme-zeix** [comment]
@FlyingDonkeys Have you tried [reimporting the project](https://www.jetbrains.com/help/idea/import-project-or-module-wizard.html#create-from-sources)? That should help to re-create the `.idea` folder (I think?)

Could you also share what steps you've already tried? It will make it easier to know what has or has not been tried yet.

If nothing else works, you could always clone the repository in a new directory with `git clone` and import it into IntelliJ.

**Comment by FlyingDonkeys** [comment]
![Screenshot 2024-08-30 100116](https://github.com/user-attachments/assets/25653f97-e999-4869-9e1e-9b1f15a3f1a1)

@damithc this is my current folder contents. My chatbot "Bonnie" cannot be run now after I tried getting gradle to work. I have in fact done `git clone` the repo into a new directory and this is what it looks like from my latest workable code. Any advice guys?

**Comment by damithc** [comment]
~~@FlyingDonkeys Did you do step 1?~~
![image](https://github.com/user-attachments/assets/ee3da708-a688-4052-803c-3b56ac8ba628)

EDIT: Never mind.  I realized you are now trying it without Gradle.

**Comment by Incogdino** [comment]
> My chatbot "Bonnie" cannot be run now after I tried getting gradle to work.

I found this answer on stackoverflow regarding this question. 

https://stackoverflow.com/a/56377111/16322247

**Comment by FlyingDonkeys** [comment]
I have resolved the issue after marking `ip` my sources root in Intellij. Thanks a ton @Incogdino!

**Comment by damithc** [comment]
> I have resolved the issue after marking `ip` my sources root in Intellij. Thanks a ton @Incogdino!

@FlyingDonkeys You are strongly recommended to use `src/main/java` as the source root. That's what Gradle expects. `src`,
`main`, and `java` should not be used as packages.
