### ISSUE TITLE
What is this canvas quiz question? 

### ISSUE THREAD

**Issue by yadobler** [nus-cs2103-AY2425S1/forum#122]
![Screenshot_20240830_013000_Canvas Student.jpg](https://github.com/user-attachments/assets/e146a13e-8091-445e-a34f-cd2cb3743cf0)

I do not understand these 3 questions given in canvas week 3 quiz.

I feel like I probably missed some hint given in the videos.

**Comment by Domokunx** [comment]
These questions can be found in the Friday Weekly Briefings. (Link found in the "Home" tab of CS2103T canvas)

**Comment by yadobler** [comment]
Ah I knew it. Thanks
