### ISSUE TITLE
Unable to run gradle run file(got error)

### ISSUE THREAD

**Issue by arnav12344** [nus-cs2103-AY2425S1/forum#123]
I am using InteliJ for running my app. I have changed the gradle.build file to reflect my package.

![image](https://github.com/user-attachments/assets/e5431848-b49a-4b6e-8e0a-348e6c96d39f)

"
application {
    mainClass.set("Kayo")
}

shadowJar {
    archiveBaseName = "duke"
    archiveClassifier = null
}
"
I am getting this error 
"Error: Could not find or load main class Kayo"

Any help is appreciated

**Comment by itsme-zeix** [comment]
Hi @arnav12344,

Try updating your `mainClass` attribute to `mainClass.set("Kayo.Kayo")` in `build.gradle` to correctly reference the class within its package.

On that note, the course convention is to use lower case for package names,  so do update the package name to `kayo`. 
After this change,  the `mainClass` attribute needs to be updated to  `mainClass.set("kayo.Kayo")` in `build.gradle` to reflect the new package name.

The final directory structure should look like this: `.../src/main/java/kayo/Kayo`, with the corresponding mainClass attribute set to `kayo.Kayo`.

**Comment by damithc** [comment]
@arnav12344 
While waiting for inputs from others, note that you can use [fenced code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) to format your post for better readability.

**Comment by arnav12344** [comment]
Thank you, everyone. The issue has been resolved.
