### ISSUE TITLE
Typo in A-JUnit

### ISSUE THREAD

**Issue by ckclion** [nus-cs2103-AY2425S1/forum#124]
![image](https://github.com/user-attachments/assets/9974f65c-a050-4b7e-9e43-043c79d029e8)

Link to site: https://nus-cs2103-ay2425s1.github.io/website/schedule/week3/project.html#a-junit

I think there is a missing "test" in the line "... to at least ..." so it becomes "... to test at least ..."

**Comment by damithc** [comment]
Thanks for the bug report, @ckclion 💯 
Fixed.
