### ISSUE TITLE
JavaDoc minimum requirements

### ISSUE THREAD

**Issue by starchypotatocode** [nus-cs2103-AY2425S1/forum#125]
I assume that
1) A class needs a javadoc at the top (above the class name and below import / package, no blank lines in between) with a brief statement of what its for and nothing else
2) Constructor, and everything but getters/setters and overrided methods inherited from above needs one (at the top, no blank lines in beteen); you can autogenerate those using the relevant guide. The top sentence needs to be a brief summary of what it does, a blank line, and then the rest of the @ notations.

Is that correct? Couldn't quite find examples or a very clear example of requirements anywhere, thanks.

**Comment by damithc** [comment]
@starchypotatocode Yes, seems about right. 👍
