### ISSUE TITLE
How to style switch statements?

### ISSUE THREAD

**Issue by thisisaditya17** [nus-cs2103-AY2425S1/forum#127]
In the website, the coding standard for switch case is given but it only for:
switch (condition) {
case ABC:
    statements;
    break;
default:
    statements;
    break;
}

If i want to style case with braces, it won't follow Egyptian Braces standard i think.

<img width="179" alt="image" src="https://github.com/user-attachments/assets/0c51a841-dd1c-4453-a388-4d73406c3785">

What to do in this case?

**Comment by damithc** [comment]
@thisisaditya17 When something is not covered in the given coding standard, you can decide on a style that you think is reasonably aligned with existing rules, and then, follow it consistently (e.g., in the team project, all members should follow the chosen style). So, I'll let you all discuss here and decide on a style.

Related: #49 

Side note: You can use [fenced code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) to format your post for better readability.
