### ISSUE TITLE
Git branching

### ISSUE THREAD

**Issue by celeschai** [nus-cs2103-AY2425S1/forum#128]
Hi all would appreciate any confirmation on my understanding on why things went wrong and suggestions on how I may attempt to fix this predicament.

I branched out to branch-level-7 at commit A.
But I realised I was still working on branch master, and I committed my changes - commit B on master.

Then I checkout to branch-level-7 and fetch the code from commit B on master, made further changes and commit C on branch-level-7. 

I merged back to master after commit C, I think it is because there is only one extra commit, git automatically did a ff merge for me so now branch-level-7 is technically the same as my master branch (same commits with same hashes, looks linear in GUI). Not sure if this understanding of the problem is accurate.

**Comment by Incogdino** [comment]
Your understanding is right. 

Git does a fast forward commit when the master branch is behind the branch of your current branch, branch level 7 when there is no diverging commits in your master branch and your branch level 7. 

A fast forward commit then takes the pointer of the master branch and moves it to the branch level 7 commit and thus they have the same commit hashes.

Though I do think that the course specifies us to use `--no-ff` or disable fast forward commit in all cases even when possible.
