### ISSUE TITLE
Can we use copilot for java docs generation?

### ISSUE THREAD

**Issue by thisisaditya17** [nus-cs2103-AY2425S1/forum#129]
Can we use github copilot for java docs generation?
Just for this and not the code.

**Comment by RezwanAhmed123** [comment]
I did a few methods’ Javadocs on my own for practice and then used chatgpt to generate the rest of the docs after that. I think it should be fine but do note the Java doc generated isn’t always accurate and you should still do some corrections whenever possible.

**Comment by damithc** [comment]
@thisisaditya17 Yes, you can. Also refer the following section of [our reuse policy](https://nus-cs2103-ay2425s1.github.io/website/admin/appendixB-policies.html#policy-on-reuse). It applies to both code and documentation.

![image](https://github.com/user-attachments/assets/e3bececb-e3d9-4bf2-99fa-3f02619a46f8)
