### ISSUE TITLE
git username

### ISSUE THREAD

**Issue by LemonDrew** [nus-cs2103-AY2425S1/forum#13]
I was doing my IP halfway when I realized that my commits have different author names. My laptop uses my github username while my other desktop uses my full name but both uses the same email addresses. Do I have to change all the commits author's name to the same name now?

**Comment by damithc** [comment]
@LemonDrew No need to change anything. As the iP is done individually, we can map all commits to you irrespective of the author name used. Remember to use the same author name for the the team project later.

**Comment by LemonDrew** [comment]
@damithc Thanks!
