### ISSUE TITLE
Gradle issues

### ISSUE THREAD

**Issue by FlyingDonkeys** [nus-cs2103-AY2425S1/forum#134]
![Uploading Screenshot 2024-08-30 145744.png…]()
Code seems to run and build correctly but the IDE says that I have errors such as `package name does not correspond to the file path`... What is going on?

**Comment by damithc** [comment]
@FlyingDonkeys Your screenshot didn't upload properly ...

**Comment by FlyingDonkeys** [comment]
![Uploading Screenshot 2024-08-30 145744.png…]()

**Comment by FlyingDonkeys** [comment]
![Screenshot 2024-08-30 145744](https://github.com/user-attachments/assets/c2a7f396-65d5-4c7c-89cb-a478d6f95c46)

sorry, i have uploaded the picture. i am not sure why my gradle build runs successfully when the package statement has issues...

**Comment by damithc** [comment]
@FlyingDonkeys See https://github.com/nus-cs2103-AY2425S1/forum/issues/120#issuecomment-2320001474

**Comment by FlyingDonkeys** [comment]
Thanks prof, have fixed it!
