### ISSUE TITLE
Time for uploading briefing recording to Canvas

### ISSUE THREAD

**Issue by Ma-Xizi** [nus-cs2103-AY2425S1/forum#137]
Hi! May I know normally when the briefing recording will be uploaded to Canvas? Since the quizzes contribute to participation marks, it would be helpful to watch the recording before Tuesday to get marks of the bonus questions.

**Comment by damithc** [comment]
@Ma-Xizi Usually, by Friday night (a few hours after the briefing ends). Today's recording is already available on Canvas homepage.

**Comment by Ma-Xizi** [comment]
> @Ma-Xizi Usually, by Friday night (a few hours after the briefing ends). Today's recording is already available on Canvas homepage.

Thank you so much!
