### ISSUE TITLE
gitk command not found

### ISSUE THREAD

**Issue by zi-yii** [nus-cs2103-AY2425S1/forum#14]
I am trying to learn to use both sourcetree and CLI. I am using macOS and when I try to run gitk command on terminal, it seems like gitk command is not found although I have Git downloaded. Any help would be greatly appreciated :)

**Comment by tata32000** [comment]
I installed mine with

```
brew install git
brew install git-gui
```

If it doesn't work, can try follow the steps from this https://stackoverflow.com/questions/17582685/install-gitk-on-mac

**Comment by zi-yii** [comment]
Will this method affect the sourcetree GUI?

**Comment by tata32000** [comment]
Sourcetree GUI seems to be working fine for me, so I think it's not affected.

**Comment by zi-yii** [comment]
Okie thank you!
