### ISSUE TITLE
Don't understand 0..1 association for logic and route in week 4 reding materials

### ISSUE THREAD

**Issue by tayxuenye** [nus-cs2103-AY2425S1/forum#140]
![Screenshot 2024-08-30 205718](https://github.com/user-attachments/assets/8d66213d-a106-4ae2-aec2-e05553fbb3e8)
Hi, I do not understand the 0..1 association on the left. It just looks like Route class can have 0 or 1 Logic class which is wrong.

**Comment by zaidansani** [comment]
According to the video, that relationship refers to the tracking of the longest `Route` by `Logic`. In that sense, it means that `Logic` might not be tracking any `Route`  when there are no routes, meaning that `Logic` is linked to 0 `Route`, and when there is at least one route, it will be associated to 1 `Route`.

Similarly on the other way round, each `Route` can only be the longest for 1 `Logic` or not the longest for any, hence the similar multiplicity.

**Comment by tayxuenye** [comment]
Thank you!
