### ISSUE TITLE
Data not saving for the test

### ISSUE THREAD

**Issue by thisisaditya17** [nus-cs2103-AY2425S1/forum#141]
When I am running my program normally. 
The list of tasks is saving but when I am doing the same with the testcases.
Then why are the tasks from test cases not appearing in the .txt file?

**Comment by AlekKwek18** [comment]
You might want to show snippet of the code where the test cases is saving to the .txt file.

**Comment by matchastack** [comment]
without code snippets it is hard to pinpoint the problem, but a possible reason might be the relative path. one way to start debugging is to specify a different path for your test storage. for example, my Storage uses ./data/tasks.txt but for StorageTest, it uses ./tmp/tasks.txt and then observe where the folders are initialised

**Comment by AbdulrahmanAlRammah** [comment]
I think more detail would help. However, when you run test cases with gradle it will create the environment from scratch and run the program then discard the changes. However, if you are specifically testing storage it should work as while the test runs it will save and write as normal and only delete afterwards. 

So for example if you do write to storage then read from storage and assertequals(string, string) to see that what is written matches you're expectation the result will work. However, after the test is passed or failed there won't be any effect on the actual file.

**Comment by rayray39** [comment]
I agree with the previous comment, maybe try saving it to a different folder instead. And perhaps you could also check if your program is reading the .txt file from the correct location (if there is already an existing list of tasks).

**Comment by yadobler** [comment]
Try using relative path from the **root directory of the project**. Most likely the files are being generated into different `out` folders depending on whether it is main or test. Ideally `src/test/resources/` for jUnit tests
