### ISSUE TITLE
Unsure of UML diagram convention

### ISSUE THREAD

**Issue by tayxuenye** [nus-cs2103-AY2425S1/forum#143]
![Screenshot 2024-08-30 221935](https://github.com/user-attachments/assets/1612d0f6-0241-448f-ac16-1eeb17cdba00)
I am not sure if Class E and class F are correct because we usually don't write "Operations" and "Attributes" in the box. I think Class G is wrong.

**Comment by damithc** [comment]
@tayxuenye In this question, `Operations` is a shorthand used to represent a list of operations (i.e., a list of methods). Similarly, for `Attributes` (i.e., a list of variables).

**Comment by Green-Tea-123** [comment]
Class F is wrong because attributes are supposed to come before operations.

**Comment by tayxuenye** [comment]
Thank you
