### ISSUE TITLE
In video quiz does not load :(

### ISSUE THREAD

**Issue by Feng1231** [nus-cs2103-AY2425S1/forum#144]
Hi prof, 
[The in video quiz for Class Diagrms: Intermediate-Level](https://nus-cs2103-ay2425s1.github.io/website/schedule/week4/topics.html#w4-3-class-diagrams-intermediate-level) at the 13:19 mark does not load. It is showing a blanks screen. :(
![image](https://github.com/user-attachments/assets/3e399d67-6407-432c-856e-9ef9b7ec77bd)

I am unable to proceed beyond the 13:19 mark because of this issue.

**Comment by damithc** [comment]
@Feng1231 Can you proceed after clicking on the 'Close' (top right)?
If cannot, try a different browser or an incognito browser window?

**Comment by Feng1231** [comment]
@damithc Hi prof, it suddenly works now. I have asked my friends a few minutes ago whether the quiz loads on their end and they said no, so I thought there were some issue with the quiz.
