### ISSUE TITLE
W4.3 Class Diagrams Snake exercise

### ISSUE THREAD

**Issue by tayxuenye** [nus-cs2103-AY2425S1/forum#148]
![Screenshot 2024-08-31 095923](https://github.com/user-attachments/assets/946dab0c-96dd-4642-afc9-ede684c62e53)
Hi, this is from W4.3 of course topics. 

I don't understand what the diagram labels "head in" and "tail in" mean. They don't have arrows to show which direction they are referring to. Since they are closer to Snake, I would assume that it means SnakeHeadSquare's head is in Snake. 

I am not sure why the question uses the phrase "Snake head" when there is only "Snake" and "SnakeHeadSquare".

**Comment by damithc** [comment]
@tayxuenye Thanks for raising this issue. This diagram seems to have some notations issues. I've updated the question entirely, including a new version of the diagram. Have a look at it again now.

**Comment by tayxuenye** [comment]
Thanks prof
