### ISSUE TITLE
Windows warning for Scene Builder

### ISSUE THREAD

**Issue by tayxuenye** [nus-cs2103-AY2425S1/forum#149]
![Screenshot 2024-08-31 140905](https://github.com/user-attachments/assets/0c21a376-d778-4274-b616-27d9488e663d)
Did anyone else get a warning from trying to Run Scene Builder from JavaFX tutorial? Is it safe to run it?

**Comment by Justincjr** [comment]
click run anyway

**Comment by damithc** [comment]
> click run anyway

Provided you downloaded the installer from a legit location, it's safe to click `Run anyway`

**Comment by tayxuenye** [comment]
Thank you
