### ISSUE TITLE
Where is the recommended place to put stubs classes in?

### ISSUE THREAD

**Issue by Bonzzz3** [nus-cs2103-AY2425S1/forum#152]
I'm planning to create a TaskStub which extends Task class. Which directory should I put it in? Should it be in my main folder or test folder? Is it advisable to put all my stubs in a single stub folder?

**Comment by damithc** [comment]
Good question @Bonzzz3 
Let's wait to see if others have any thought on this.

**Comment by tohhengxing** [comment]
>Is it advisable to put all my stubs in a single stub folder

It may make sense now, but not in the future. But why optimise so early?

**Comment by damithc** [comment]
> Should it be in my main folder or test folder?

One option is to put stub classes in in the same package as the class being stubbed, but in the `test` folder (similar to how test classes are organized, as per https://se-education.org/guides/tutorials/junit.html#conventions-to-follow).

This way, the stub will not pollute the main code folder but will have high level of access to the stubbed class (because it is in the same package).

**Comment by Bonzzz3** [comment]
> > Is it advisable to put all my stubs in a single stub folder
> 
> It may make sense now, but not in the future. But why optimise so early?

Oh ok. I just had the question in mind and it might be useful in the future for making more jUnit tests.

**Comment by Bonzzz3** [comment]
> > Should it be in my main folder or test folder?
> 
> One option is to put stub classes in in the same package as the class being stubbed, but in the `test` folder (similar to how test classes are organized, as per https://se-education.org/guides/tutorials/junit.html#conventions-to-follow).
> 
> This way, the stub will not pollute the main code folder but will have high level of access to the stubbed class (because it is in the same package).

Ahh I see. Thanks for the suggestion and explanation prof. I will close the issue now.
