### ISSUE TITLE
Enhanced switch case style 

### ISSUE THREAD

**Issue by Feng1231** [nus-cs2103-AY2425S1/forum#153]
Hi. according to this [issue](https://github.com/nus-cs2103-AY2425S1/forum/issues/49), there is a consensus on how to style enhanced switch case, where the cases could be indented

I am currently doing the A-CheckStyle task for week 4. I have followed instructions from [here](https://se-education.org/guides/tutorials/checkstyle.html) and found checkstyle errors pertaining to the enhanced checkstyle.
Specifically, this is what that had been flagged out as 'errors'. 
![image](https://github.com/user-attachments/assets/6ba7db72-2beb-4fc0-8cef-35aa22a919a8)

This is the code that violates the checkstyle 
```java
    public static Command parse(String message) {
        try {
            CommandWord instruction = CommandWord.valueOf(getInstruction(message));
            return switch (instruction) {
                case LIST -> new ListCommand(message);
                case FIND -> new FindCommand(message);
                case MARK -> new MarkCommand(message);
                case UNMARK -> new UnmarkCommand(message);
                case DELETE -> new DeleteCommand(message);
                case TODO -> new ToDoCommand(message);
                case DEADLINE -> new DeadlineCommand(message);
                case EVENT -> new EventCommand(message);
                case ON -> new OnCommand(message);
                case BYE -> new ByeCommand(message);
            };
        } catch (IllegalArgumentException e) {
            return new InvalidCommand("");
        }
    }
```

Seems like the enhanced switch case will still have follow the 'no indentation for cases' rule right?

**Comment by damithc** [comment]
@Feng1231 The AB3 checkstyle rules file is based on the old syntax (AB3 was written using Java 11). You'll need to update the rule, or delete/disable it, if you wish to use this new style.

**Comment by Feng1231** [comment]
> @Feng1231 The AB3 checkstyle rules file is based on the old syntax (AB3 was written using Java 11). You'll need to update the rule, or delete/disable it, if you wish to use this new style.

Ohh so we won't be marked down if we follow the new style for enhanced switch case, as long as we stick to it throughout?

**Comment by damithc** [comment]
> Ohh so we won't be marked down if we follow the new style for enhanced switch case, as long as we stick to it throughout?

@Feng1231 Yes, that's correct.

**Comment by Feng1231** [comment]
Noted prof, thank you😊
