### ISSUE TITLE
Spelling error - JavaFX part1

### ISSUE THREAD

**Issue by Feng1231** [nus-cs2103-AY2425S1/forum#154]
There is a spelling error under [this section](https://se-education.org/guides/tutorials/javaFxPart1.html#writing-your-first-java-fx-program).
![image](https://github.com/user-attachments/assets/d4d1f372-096c-47de-8d27-31f1398dace6)

> Similarly, the ~~warnign~~ **warning** about the different versions can be ignored as well

**Comment by damithc** [comment]
Thanks for the bug report, @Feng1231 💯 
Fixed.
