### ISSUE TITLE
Test functions not working

### ISSUE THREAD

**Issue by jevan13** [nus-cs2103-AY2425S1/forum#155]
![IMG_1168](https://github.com/user-attachments/assets/297d1dd7-8d2c-4d26-897c-550ab98ba51f)
i closed and reopend intellij and my testing tools stopped working. im thinking it might be my junit not working properly? before this i could run the 'test' function on gradle and it worked but right now the testing functions are not even being detected.

**Comment by damithc** [comment]
@jevan13 While waiting for inputs from others, try these 'common remedies' one-at-a-time in this order:
  * Run `./gradlew clean build`
  * Choose `File` -> `Invalidate caches`
  * Close Intellij -> Delete the `.idea` folder -> Re open the project in Intellij
  * Clone the fork to a different location and open the project in Intellij again to get a fresh start without losing changes you did so far.

**Comment by damithc** [comment]
> @jevan13 While waiting for inputs from others, try these 'common remedies' one-at-a-time in this order:
> 
>     * Run `./gradlew clean build`
> 
>     * Choose `File` -> `Invalidate caches`
> 
>     * Close Intellij -> Delete the `.idea` folder -> Re open the project in Intellij
> 
>     * Clone the fork to a different location and open the project in Intellij again to get a fresh start without losing changes you did so far.

@jevan13 update here after trying above remedies.

**Comment by jevan13** [comment]
@damithc Thank you! It works now :)

**Comment by rithiklenin** [comment]
![Screenshot 2024-09-01 at 11 37 48 PM](https://github.com/user-attachments/assets/37ff2cb5-bd2d-4df0-a333-673b997d671d)
Hi I am also facing the same problems now but it fails when I run ./gradlew clean build`. Not sure what to do now.

**Comment by damithc** [comment]
@rithiklenin This issue has been closed already. You can start a new post instead. Also, give the full error message outputted by gradle command.
But first, try the solutions suggested earlier in this thread (apparently, one of them solved the problem @jevan13 faced)
