### ISSUE TITLE
Expected testoutput does not match expected test input

### ISSUE THREAD

**Issue by miuna9890** [nus-cs2103-AY2425S1/forum#156]
org.opentest4j.AssertionFailedError: expected: <    Here are the tasks in your list that match book:
    1.[D][ ] read book (by: Apr 05 2020, 4:00 pm)
    3.[T][ ] read book> but was: <    Here are the tasks in your list that match book:
    1.[D][ ] read book (by: Apr 05 2020, 4:00 pm)
    3.[T][ ] read book
>
Process finished with exit code -1

Although the output seems to match the testcase does not pass

@Test
    public void findCheck() {
        ArrayList<Task> items = new ArrayList<>();
        StoreList storeList = new StoreList(items);

        // Create a new deadline task and add it to the StoreList
        storeList.addItem("read book /by 2020-04-05 16:00", "deadline");

        // Create a new event task and add it to the StoreList
        storeList.addItem("project /from 16:00 /to 18:00 /on 2020-04-05", "event");

        // Create a new ToDo task and add it to the StoreList
        storeList.addItem("read book", "todo");

        // Capture the console output
        ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        PrintStream originalOut = System.out; // Save the original System.out
        System.setOut(new PrintStream(outContent)); // Redirect System.out to outContent

        // Call the method that prints to the console
        storeList.displayItemsWithWord("book");

        assertEquals("    Here are the tasks in your list that match book:\n" +
                "    1.[D][ ] read book (by: Apr 05 2020, 4:00 pm)\n" +
                "    3.[T][ ] read book", outContent.toString());

        // Restore original System.out
        System.setOut(originalOut);
    }

**Comment by damithc** [comment]
@miuna9890 While waiting for inputs from others, it might help to push this exact code to a branch in your fork and share here so that other can try to replicate the problem.

**Comment by sayomaki** [comment]
Hi, it may seem that your output from the print is different compared to the expected output given by you, likely due to a missing newline at the end (remember that println will always end with a newline, however the expected test result is missing a final newline at the very end).

This is also evident from your output given:

>  3.[T][ ] read book> but was: < Here are the tasks in your list that match book:

As you can see the ">" is on the same line as the output (whereas there is a blank line between the actual output and the final line, "Process...")

> 3.[T][ ] read book
> 
> Process finished with exit code -1

Do try this out and see if it works! Hope this helps!

**Comment by miuna9890** [comment]
no it did not:( 
Here's the branch with the code: https://github.com/miuna9890/ip/tree/Level-9-version-2
Test is under src/test/Data/StorelistTest

**Comment by Domokunx** [comment]
Another possibility is due to your console output using CRLF line break instead of just LF

try replacing your \n with \r\n in your test function and see how it goes?

**Comment by Incogdino** [comment]
I believe @Domokunx is right. I tried running your code locally on my machine but replaced `assertEquals` with this

```java
assertEquals("    Here are the tasks in your list that match book:" +
                "    1.[D][ ] read book (by: Apr 05 2020, 4:00 pm)" +
                "    3.[T][ ] read book", outContent.toString().replaceAll("\n", "").replaceAll("\r", ""));
```

It passed the test case you are looking for.

On a side note, I followed this [article](https://stackoverflow.com/a/57692688/16322247) on stackoverflow for the answer. The author of the question also seemed to be from a previous batch facing the same issue 🤣

**Comment by miuna9890** [comment]
yuppp. It workedd!! thanksss:)

**Comment by damithc** [comment]
> On a side note, I followed this [article](https://stackoverflow.com/a/57692688/16322247) on stackoverflow for the answer.

Nice find @Incogdino
