### ISSUE TITLE
Test ignored using gradle test function

### ISSUE THREAD

**Issue by jevan13** [nus-cs2103-AY2425S1/forum#157]
<img width="710" alt="Screenshot 2024-08-31 at 11 28 19 PM" src="https://github.com/user-attachments/assets/b6cad19d-e6dc-42d9-b329-a2c82e9c5f11">
Hi, I get the message "Tests ignored" when I run the test function using gradle, does anyone have any solutions for this :(

**Comment by damithc** [comment]
@jevan13 While waiting for inputs from others, push the code to a branch and share here so that other can try to replicate the problem.

You can also try the the 'common remedies' mentioned in a previous thread.
  * Run `./gradlew clean build`
  * Choose `File` -> `Invalidate caches`
  * Close Intellij -> Delete the `.idea` folder -> Re open the project in Intellij
  * Clone the fork to a different location and open the project in Intellij again to get a fresh start without losing changes you did so far.

**Comment by jevan13** [comment]
@damithc Hi this is the link to my code. Also the common remedies did not work.
https://github.com/jevan13/ip/tree/Forum(A-JUnit)

**Comment by damithc** [comment]
hmm... this is unexpected 🤔 

https://github.com/jevan13/ip/blob/Forum(A-JUnit)/src/test/java/Yapper/ParserTest.java

![image](https://github.com/user-attachments/assets/da5aec72-d720-4308-8aa6-a766c27c89a4)

Although this may not be the cause of your problem.

**Comment by Jasperabez** [comment]
@jevan13  Is this your second time running the tests? If I am right gradle caches the build if you have passed the test successfully once, which would show it as skipped in IntelliJ.

You can use the cli gradlew to force the test, see whether it works:
`./gradlew test --rerun-tasks` 

alternatively modify some bits of your code and rerun the test in IntelliJ

**Comment by jevan13** [comment]
@damithc Hi may i know what is unexpected about that?

**Comment by jevan13** [comment]
<img width="424" alt="Screenshot 2024-09-01 at 12 46 01 AM" src="https://github.com/user-attachments/assets/1ef4bbac-61a9-427e-bcca-c6fc98b619d2">
@Jasperabez This is what I got from running ./gradlew test --rerun-tasks

When I modied some bits of my code, I either get the same "Test ignored" or "Test events were not received"

**Comment by damithc** [comment]
> @damithc Hi may i know what is unexpected about that?

The entire code is shown as one line :-p

**Comment by jevan13** [comment]
@damithc Oh i see...hahaha

**Comment by Incogdino** [comment]
I do believe the reason for this is because you are calling `Yapper.main`. I am not 100% sure about why, but I think the reason is it launches another program and thus intercepts with the test that is ran by gradle. 

Try removing it and it should run your tests normally. Hopefully this helps :)

**Comment by Jasperabez** [comment]
@jevan13 This is what I got after running `./gradlew test --rerun-tasks` on your code (after uncommenting `testLogging` in your `build.gradle` - on branch **Forum(A-JUnit)** )
![Screenshot_20240901_013043](https://github.com/user-attachments/assets/bf1c40c3-6f68-4c8a-a125-699768cf7ee3)

The test is ran but somehow is skipped, the weirdest part is when I copied your test code and run it on my own ip it's somehow working?
```
package nixy.parse;

import nixy.Nixy;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;

import java.io.IOException;
import java.io.PrintStream;


public class ParserTest {

    @Test
    public void invalidInput() throws IOException {
        String userInput = String.format("blah%bye", System.lineSeparator());
        ByteArrayInputStream bais = new ByteArrayInputStream(userInput.getBytes());
        System.setIn(bais);

        String expected
 = "Yapper don't know this command :(";
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        PrintStream printStream = new PrintStream(baos);
        System.setOut(printStream);


        Nixy.main(null);
        String[] lines = baos.toString().split(System.lineSeparator());
        String actual = lines[lines.length - 1];

        assertEquals(expected, actual);

    }
}
```

![Screenshot_20240901_022634](https://github.com/user-attachments/assets/128bf10a-d7ea-4e87-b0da-adffcb3047bd)

**Comment by yadobler** [comment]
@jevan13 I checked your `build.gradle`.

Try to uncomment this:
![image](https://github.com/user-attachments/assets/56ff7be4-7291-4e8c-b579-2a38715db0b5)

I am not sure why is it commented out, and if it affects the reason why your tests aren't running any tests

**Comment by jevan13** [comment]
@yadobler Hi, uncommenting that part seems to work! Thank you! I uncommenting it because the website said to add the following:

 test {
    useJUnitPlatform()
}

so i thought that part was unnecessary haha.
