### ISSUE TITLE
Missed submission for tP: AB3 Initial Experience

### ISSUE THREAD

**Issue by hyxnnii** [nus-cs2103-AY2425S1/forum#159]
I accidentally missed the submission deadline for the canvas survey tP: AB3 Initial Experience, and I am aware that the submission will be shared with my team members later for the team project, but I can no longer submit anything as the quiz is now locked :-( Would there be a way for a late submission to go through so that my suggestions can still be shared?

**Comment by damithc** [comment]
@hyxnnii You can share it with your team yourself. You can simply reply-all to the email (the one containing the submitted responses) that we sent out just now.
