### ISSUE TITLE
When branching, do we execute the compare and pull request on github to merge branches

### ISSUE THREAD

**Issue by obrona** [nus-cs2103-AY2425S1/forum#16]
When we create a branch, and push to it, github will ask us to Compare and pull request, do we do it or not to merge the branch with master?

**Comment by Incogdino** [comment]
You can choose to not do it and merge it later on after further commits to the same branch/ when the branch/feature is ready for production.

I think the reason for this is that the feature of the branch may not be ready for deployment so you don't merge it first to prevent adding unfinished code to the main branch

**Comment by damithc** [comment]
@obrona For now, ignore that 'helpful suggestion' from GitHub. We are going to learn how to do branching with Git alone, without involving GitHub features.

**Comment by obrona** [comment]
The website says "Only merged branches are detected by the script" if I do not do "Compare and pull request" then merge the branches in the pull request, will the script detect that I merge the branches using Git CLI on my local computer?

So the steps are
1. push your branch to github branch
2. merge branch to master on your computer
3. push the merge commit on master to github master
4. Leave the branch alone, don't delete it

Is this the correct process ?

**Comment by damithc** [comment]
> 1. push your branch to github branch
> 2. merge branch to master on your computer
> 3. push the merge commit on master to github master
> 4. Leave the branch alone, don't delete it
> 
> Is this the correct process ?

@obrona Week 2 iP tasks do not involve any branching. But if you are doing week 3 tasks, yes, that's the correct process but you need to push the branch again after merging (or else, the mering of the branch is not reflected in the remote repo, even if you pushed the merge commit already).

Side note: Do not move more than one week ahead of schedule.

**Comment by obrona** [comment]
![Screenshot 2024-08-21 103354](https://github.com/user-attachments/assets/23b6c97b-7c19-41b7-aed2-91997abff48f)
Is this the correct outcome ?

**Comment by damithc** [comment]
@obrona this is how it looks on SourceTree
![image](https://github.com/user-attachments/assets/c5b916f8-c66e-46b2-9331-82b109148b39)

`branch-Level-8` seems to be as expected.

**Comment by obrona** [comment]
So I realised I needed to do --no-ff so that the merge commits will be reflected in github.
Right now this is my SourceTree graph
![Screenshot 2024-08-21 134131](https://github.com/user-attachments/assets/c4184c1c-0e59-49dc-bec0-0db0296751d2)

Is this correct ? I had to force push to github because I needed to redo the commits for Level-7 too, I forgot to add --no-ff when merging branch-Level-7

**Comment by damithc** [comment]
> Right now this is my SourceTree graph ![Screenshot 2024-08-21 134131](https://private-user-images.githubusercontent.com/114121900/359761337-c4184c1c-0e59-49dc-bec0-0db0296751d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMTk1NDMsIm5iZiI6MTcyNDIxOTI0MywicGF0aCI6Ii8xMTQxMjE5MDAvMzU5NzYxMzM3LWM0MTg0YzFjLTBlNTktNDlkYy1iZWMwLTBkYjAyOTY3NTFkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMVQwNTQ3MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZjEzYzBmODY3MjQ5MTU0OTZkY2Q3NmU1NWZjNjMyODRiYmFiZWIzMDM3MzBmYWU1M2ZiODZmMjMwZTNmM2RkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rTvUsXRmbUzAtm8wObTqtq2GRbGEDZeFExFMC2ySYkY)
> 
> Is this correct ?

Almost. Looks like you started branch-Level-8 to branch off from branch-Level-7 (instead of going back to the master branch and starting the new branch from there)?

**Comment by obrona** [comment]
Okay Prof I messed up my branching big time, I forgot I was in branch-Level-7 when creating branch-Level-8 as I use Git from the CLI, so I am not actively shown which branch I am in, and now changing the commit history to ensure it fits the correct branching is too difficult for me already. 

Will I be penalised, and can I keep my current code, if not I have to reset to Level-6 and restart branch-Level-7 and branch-Level-8 again? 

Will the scripts detect the branches and merges correctly, i.e "Only merged branches are detected by the script" will this statement be satisfied

**Comment by damithc** [comment]
> Okay Prof I messed up my branching big time, I forgot I was in branch-Level-7 when creating branch-Level-8, and now changing the commit history to ensure it fits the correct branching is too difficult for me already. Will I be penalised, and can I keep my current code, if not I have to reset to Level-6 and restart branch-Level-7 and branch-Level-8 again

@obrona Not to worry. This kind of branching mistakes are common and you'll learn to avoid/correct them with more practice. In fact, your attempts to fix the problem so far already show that you know more Git than a typical Git newbie.
You are welcome to keep trying to fix it but it's also OK if you don't, as our grading forgives occasional mistakes.

**Comment by obrona** [comment]
I have managed to correct the commit history

This is the Source Tree graph
![Screenshot 2024-08-21 180140](https://github.com/user-attachments/assets/aa1b25b3-a6a6-4d68-b2cf-6e3c48f3c1de)

Is this what you mean when you say "merging of the branches is reflected in the repo"? Otherwise, how should we know if the merging is reflected in the repo, and the scripts will be able to detect the merge branches
![Screenshot 2024-08-21 180237](https://github.com/user-attachments/assets/d25f9713-9780-4cca-af04-25b332c896be)

**Comment by damithc** [comment]
> This is the Source Tree graph
> ![Screenshot 2024-08-21 180140](https://private-user-images.githubusercontent.com/114121900/359850776-aa1b25b3-a6a6-4d68-b2cf-6e3c48f3c1de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNDMzMzEsIm5iZiI6MTcyNDI0MzAzMSwicGF0aCI6Ii8xMTQxMjE5MDAvMzU5ODUwNzc2LWFhMWIyNWIzLWE2YTYtNGQ2OC1iMmNmLTZlM2M0OGYzYzFkZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMVQxMjIzNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YjQxYjc1N2M1MWE5NjdkODFjNTAxNWU0YTEwYjg5NDdmY2MwZDViZTYwNTk0OTZmZTkxODQ2YWVmMGJlZWRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gxbVEtj_b1-lFwu2uktl1brAww5gXfP2jyRSrZ2vYy4)

@obrona hmm... where are the branch labels? Did you delete the branches after merging?

**Comment by obrona** [comment]
You got be to be kidding me Prof, I thought when the website said not to delete the branches, I thought it meant not to delete the branches on github. I think the website can be more clear on what to do. Can I clarify what is the expected process for Level-7 and Level-8?

**Comment by damithc** [comment]
> You got be to be kidding me Prof, I thought when the website said not to delete the branches, I thought it meant not to delete the branches on github.

Technically, that's enough (as the script can see only what's on GitHub, not your local repo). Nevertheless, it may be better to keep your local branch as for, for your easier reference.
We'll start checking week 3 stuff from this Saturday -- at that time you can verify from the [iP dashboard](https://nus-cs2103-ay2425s1.github.io/dashboards/contents/ip-progress.html).
There is an explanation of what is expected from branches in the iP dashboard as well.
![image](https://github.com/user-attachments/assets/c9572d46-baa7-463d-805f-786cf74e51d5)
