### ISSUE TITLE
Retagging commits

### ISSUE THREAD

**Issue by yadobler** [nus-cs2103-AY2425S1/forum#160]
I realised that some commits I have tagged wrongly:

Expected: (tag master **after** merge)
```
                        (commit 2103)
                      merge; tag:A-smth 
main ---------*-------+---------->
              |       | 
branch-A-smth |-------|
```

What I did (tag branch **before** merge)
```
                      (commit 696969) merge   
main ---------*-------+---------->
              |       | 
branch-A-smth |-----|-|
                    (commit 2425S1) tag:A-smth
```

~~Is it ok if I do~~ (edit: I already did it) *Is it ok that I did* the following:
```bash
# find the correct merge commits
git log

# local tag removal
git tag -d A-smth

# add tag to merge commit on master
git tag A-smth 696969

# delete remote tag
# use tag path to prevent accidentally removing branch-A-smth when autocompleting
git push origin :refs/tags/A-smth 

# push new tags
git push --tags
```

I feel like the timestamps might mess up, but I feel like wrong time ("overdue") is better than incorrect tagging.

**Comment by damithc** [comment]
@yadobler Should be fine. You can check the dashboards later today, after they have updated again.

**Comment by yadobler** [comment]
@damithc thank you.

Maybe I'll share this as a tip for others in case they made the same mistake.
