### ISSUE TITLE
Unable to match strings in runtest.bat for text art

### ISSUE THREAD

**Issue by flyingsalsa** [nus-cs2103-AY2425S1/forum#164]
![image_2024-09-01_171825364](https://github.com/user-attachments/assets/00277abc-6363-49f6-bc58-030f4b221b4f)
Why does the FC command in the bat file highlight my text art as differing in the expected and actual file? I copied it from my output and put in the expected text. 

it would appear there are some missing spaces in some lines of the expected.txt which are in the Actual.txt but if I copy them over to the expected text they disappear after I run the runtest.bat.
Any ideas on how to fix this would be appreciated!

**Comment by RezwanAhmed123** [comment]
I realised in the expected text file, they seem to trim the trailing spaces when u save the file. One way to fix this would be to format the code for ur printing method and remove any spaces before the line break

```java
public void formatPrint(String string) {
    System.out.println(string + “\n”);
}
```

Instead of 

```java
public void formatPrint(String string) {
    System.out.println(string + “ \n”);
}
```

**Comment by damithc** [comment]
@flyingsalsa let us know if @RezwanAhmed123's suggestion worked or if the issue still persists.

**Comment by flyingsalsa** [comment]
Ah I just tried it out and it worked! 
closing now ty

**Comment by damithc** [comment]
> Ah I just tried it out and it worked!

🎯 Bulls eye, @RezwanAhmed123 Nice!
