### ISSUE TITLE
Default Multiplicity for Class Diagrams

### ISSUE THREAD

**Issue by lithops-zty** [nus-cs2103-AY2425S1/forum#165]
Looks like it is not mentioned what type of multiplicity we should assume for class diagrams like the one below:
![image](https://github.com/user-attachments/assets/1d0391e1-07ea-4c7e-a35c-70badbbfd5ec)

Is there a rule on this? Thanks!

**Comment by damithc** [comment]
@lithops-zty Good question. The answer is similar to what the following say about visibility.
![image](https://github.com/user-attachments/assets/469d11a1-e588-4a7c-9e8f-d588927f2945)

**Comment by lithops-zty** [comment]
Thank you prof!
