### ISSUE TITLE
Unable to initiate pull-request for week3 ip tasks

### ISSUE THREAD

**Issue by somethingfishyfishy** [nus-cs2103-AY2425S1/forum#166]
These are the steps I took to try to create a pull request. Not sure why I cannot initiate a pull request, I don't have one existing currently.

The button for "create pull request" is not highlighted

![image](https://github.com/user-attachments/assets/21491f7a-f6d4-4d60-b01f-2074df82db23)
![image](https://github.com/user-attachments/assets/c391f509-33ae-4db0-ba41-f0a6f9872f21)

Please send help

**Comment by xqtann** [comment]
you can try creating the new pull request from your fork (your_username/ip) instead of creating the pull request from the original upstream repo. i believe that should allow you to successfully create the new pull request.

![image](https://github.com/user-attachments/assets/d079d14c-8b48-4655-8efb-d2fec2770d64)

**Comment by somethingfishyfishy** [comment]
Yes finally, was really struggling with this. Thanks for your help!

> you can try creating the new pull request from your fork (your_username/ip) instead of creating the pull request from the original upstream repo. i believe that should allow you to successfully create the new pull request.
> 
> ![image](https://private-user-images.githubusercontent.com/80834308/363495927-d079d14c-8b48-4655-8efb-d2fec2770d64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyMDAzMDUsIm5iZiI6MTcyNTIwMDAwNSwicGF0aCI6Ii84MDgzNDMwOC8zNjM0OTU5MjctZDA3OWQxNGMtOGI0OC00NjU1LThlZmItZDJmZWMyNzcwZDY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDE0MTMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4MGVmMGQ0MGZiZmM0ZTQ4YWE5NzJlYWM4OTZiNDUxMWMzMzAxODg1NTBjZTUzZGIwMTJiMWE5ZWU3YWE2NDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JXz_YU-h4JoxE4zoY-DUFagWgnovY6PhUwlsFXzt94U)
