### ISSUE TITLE
Checkstyle config issues

### ISSUE THREAD

**Issue by OrangeCatLoves** [nus-cs2103-AY2425S1/forum#167]
For some reason after copy-pasting the checkstyle.xml and suppressions.xml from AB3, i'm met with some error
saying

"URI is not registered (Settings | Languages & Frameworks | Schemas and DTDs)"
for both checkstyle.xml and suppressions.xml
mm what's the issue here. I've already updated the build.gradle file

![Screenshot 2024-09-01 221323](https://github.com/user-attachments/assets/eb61d9c4-eff2-405b-bf27-a6ed5d10a8a1)
![Screenshot 2024-09-01 221431](https://github.com/user-attachments/assets/e017c8af-4217-49e6-9c6e-89f10821dc11)
![Screenshot 2024-09-01 221636](https://github.com/user-attachments/assets/fbe9068f-49de-4533-8c3a-eba046994f94)

When i run gradlew checkstyleMain checkstyleTest, i get this error 
![Screenshot 2024-09-01 223719](https://github.com/user-attachments/assets/ed332973-f3df-48bc-ade3-dec74cf548b5)

**Comment by damithc** [comment]
@OrangeCatLoves The two things (the error indicator in the file view, and the error you got when running the gradle command) are not related.

For the second one, try running the gradle command in a regular cmd terminal, instead of a powershell terminal to see if that makes a difference.

**Comment by OrangeCatLoves** [comment]
I ran it in a regular cmd terminal and I guess it worked?
![Screenshot 2024-09-02 015636](https://github.com/user-attachments/assets/fd478d95-1c82-4fd8-b9f7-f0da5924f385)
 
![Screenshot 2024-09-02 020150](https://github.com/user-attachments/assets/f0cac7a0-172c-495c-93ad-1c05cafe3ddb)

**Comment by blackpanther9229** [comment]
> I ran it in a regular cmd terminal and I guess it worked? ![Screenshot 2024-09-02 015636](https://private-user-images.githubusercontent.com/156922023/363509942-fd478d95-1c82-4fd8-b9f7-f0da5924f385.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyMzYzMDUsIm5iZiI6MTcyNTIzNjAwNSwicGF0aCI6Ii8xNTY5MjIwMjMvMzYzNTA5OTQyLWZkNDc4ZDk1LTFjODItNGZkOC1iOWY3LWYwZGE1OTI0ZjM4NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMlQwMDEzMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hM2NiZDU4ZDBjYjNhMzE1MjM3MDE5NTY5NjM1ODJlNzg5YmNmYjZhZDU5ZTcyZWM4MjZjNGQ1ZWEwZTU5YWViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jwOvTG_My_sGEOsd_HeYyeBvRVrYcbVCTnP1l7LqVPM)
> 
> ![Screenshot 2024-09-02 020150](https://private-user-images.githubusercontent.com/156922023/363510175-f0cac7a0-172c-495c-93ad-1c05cafe3ddb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyMzYzMDUsIm5iZiI6MTcyNTIzNjAwNSwicGF0aCI6Ii8xNTY5MjIwMjMvMzYzNTEwMTc1LWYwY2FjN2EwLTE3MmMtNDk1Yy05M2FkLTFjMDVjYWZlM2RkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMlQwMDEzMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZWZmOTVmNjY1OThmMWQ4YjkwOTY1MjE4ZWU0N2U0ZmEwMGRlMWNiMTNhY2NlMGVjYTMyZGI1ZWFkZTcwOTU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bvh4BvQReZJbjW3XanAB6w--34TNVoSWVh--wh2ZyEw)

That’s right

**Comment by aldentantan** [comment]
Have you tried running `.\gradlew` instead of just `gradlew`?
