### ISSUE TITLE
What does association without navigability look like?

### ISSUE THREAD

**Issue by lithops-zty** [nus-cs2103-AY2425S1/forum#168]
Under Section W4.2b → OOP  Associations → Navigability, it states
> When two classes are linked by an association, it does not necessarily mean the two objects taking part in an instance of the association knows about (i.e., has a reference to) each other. **The concept of which object in the association knows about the other object is called navigability.**

]I’m struggling to think of a scenario where two classes are associated but not navigable. In what situations does an association not require a reference within the classes? Can someone provide a concrete example? Thanks!

**Comment by damithc** [comment]
> I’m struggling to think of a scenario where two classes are associated but not navigable.

@lithops-zty Can you also elaborate your chain of thinking that led from the textbook statement you cited to this question? That can help others give more focused inputs.

**Comment by lithops-zty** [comment]
When I was reading the quoted statement I was quite confused as why two classes with no references to each other can still be associated. It seems to me that such an 'association' is meaningless, as the code wouldn't change whether the association exists or not (since no attributes are added).

I was more perplexed when I read an earlier statement:

> An association can be shown as an attribute instead of a line.

This suggests that an association should result in new attributes being created, which makes it navigable.

This leads me to the question: do associations without navigability actually exist, and if so, what are some real-life examples where such associations are necessary and meaningful?

**Comment by damithc** [comment]
> This leads me to the question: do associations without navigability actually exist, and if so, what are some real-life examples where such associations are necessary and meaningful?

@lithops-zty What the text says is, an association doesn't necessarily mean _each_ class has a reference to the other. That is, every association is not navigable in _both_ directions. That's why we need a notation to indicate which direction an association is navigable. The statement is not supposed to imply that associations can exist without navigability in either direction. That said, it is still possible to have an an association in a UML diagram that doesn't _show_ navigability in either direction (i.e., the direction of the navigability is unknown.

**Comment by lithops-zty** [comment]
@damithc Got it! I now realize that I misunderstood the text. A more accurate interpretation is that associations imply navigability, and vice versa, though navigability can be either unidirectional or bidirectional (or simply not shown). 
Please correct me if my understanding is still wrong/inaccurate.

**Comment by damithc** [comment]
> @damithc Got it! I now realize that I misunderstood the text. A more accurate interpretation is that associations imply navigability, and vice versa, though navigability can be either unidirectional or bidirectional (or simply not shown).
> Please correct me if my understanding is still wrong/inaccurate.

Yes, in world where associations are implemented using instance variables (which is the typical case), this is correct. Not so clear-cut when other implementation mechanism are used (e.g., a separate look-up table). But you need not worry about those complications in the context of this course.

**Comment by lithops-zty** [comment]
@damithc Thank you prof!
