### ISSUE TITLE
Is the exercises under each chapter of the JavaFX tutorial compulsory?

### ISSUE THREAD

**Issue by Feng1231** [nus-cs2103-AY2425S1/forum#169]
There are exercises for us to try at the end of each JavaFX tutorial parts. 
Are these compulsory and must be implemented in our IP? For example, these 2 exercises:
![image](https://github.com/user-attachments/assets/0f5b4995-215f-4107-9198-b833d7e94e1e)

**Comment by damithc** [comment]
@Feng1231 No, they are optional. You can skip them for now.

**Comment by Feng1231** [comment]
Thank you prof!
