### ISSUE TITLE
Gradle version incompatible with Java 17.0.11

### ISSUE THREAD

**Issue by vicelyav** [nus-cs2103-AY2425S1/forum#170]
Hi, I am in the process of setting-up gradle. However, I got an error message while loading it:

Your build is currently configured to use incompatible Java 17.0.11 and Gradle 6.2. Cannot sync the project.

We recommend upgrading to Gradle version 8.8.

The minimum compatible Gradle version is 7.2.

The maximum compatible Gradle JVM version is 13.

Possible solutions:
 - Upgrade to Gradle 8.8 and re-sync
 - Upgrade to Gradle 7.2 and re-sync
 - Use Java 13 as Gradle JVM: Open Gradle settings

For context, I used my project directory "/Users/vicelyavisakha/Documents/CS2103/INDIVIDUAL PROJECT" as my gradle user home. The java version for my computer is Azul zulu 17.10.11. 
Any help would be appreciated. Thank you.

*Edit: I tested using another directory /Users/vicelyavisakha/.gradle as well and face the same issue

**Comment by damithc** [comment]
Hmm... did anybody else face this?
@vicelyav Are you able to ignore this and proceed, for the time being?

**Comment by vicelyav** [comment]
@damithc i cannot proceed with the A-Graddle for now and potentially other graddle-related increments. I will try to do other increments first.

**Comment by damithc** [comment]
@vicelyav Can you share a screenshot of the error? When exactly did it appear?

**Comment by vicelyav** [comment]
<img width="1710" alt="Screenshot 2024-09-02 at 1 03 13 AM" src="https://github.com/user-attachments/assets/60d02d26-26e2-4109-a0f3-bb9827a55f27">
This is the error message
The setting window in IntelliJ looks like this:
<img width="1710" alt="Screenshot 2024-09-02 at 1 27 52 AM" src="https://github.com/user-attachments/assets/8d9c44c5-82d0-4fb2-aa5d-7043a66b4cf4">

**Comment by vicelyav** [comment]
This is the error message:
<img width="1710" alt="Screenshot 2024-09-02 at 1 26 34 AM" src="https://github.com/user-attachments/assets/c44ecce6-f859-4f02-82c1-a16a1eb883fa">
This is the settings window in IntelliJ:
<img width="1710" alt="Screenshot 2024-09-02 at 1 27 52 AM" src="https://github.com/user-attachments/assets/d8d63457-ea43-462c-acdf-4091ea9f5afd">


I merged my master branch with the "add-gradle-support" branch, and then go to the settings to confirm my java sdk version. The error automatically happens after I exited the settings screen.

**Comment by Incogdino** [comment]
I believe you are using the wrong gradle version as suggested by the error message and the version [here](https://docs.gradle.org/7.6.2/userguide/compatibility.html).

I have cloned your repo and changed the gradle version to version 7.6.2 and it is able to run `gradle build` with no issues. 

The file changed is gradle-wrapper.properties in the wrapper directory within the gradle folder 
```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-7.6.2-bin.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
```

Hopefully this solves your issue 😄

**Comment by vicelyav** [comment]
Ah I see, it really worked. Thank you so much!

It's interesting though, since I merged it from the forked branch. I am pretty sure my jdk version is correct as well. What's the likely cause of this discrepancy?

**Comment by Incogdino** [comment]
![image](https://github.com/user-attachments/assets/e983f3ef-f430-4cce-a9b2-deaab102e6bd)


Hmm 🤔 Looking at sourcetree, could it be the case that you merged the commit instead of the branch? That could be the reason why the updated gradle version commit were not added when you merged them.

**Comment by vicelyav** [comment]
Ok thank you. I will figure it out.

**Comment by yadobler** [comment]
Just wanna add in, do try to put the error message in fenced codeblock. Makes things easier (and other forums might not be very nice about not doing it)
