### ISSUE TITLE
Test not identified; Unable to do Unit

### ISSUE THREAD

**Issue by rithiklenin** [nus-cs2103-AY2425S1/forum#171]
![Screenshot 2024-09-01 at 11 37 48 PM](https://github.com/user-attachments/assets/d9c12b7e-0f20-47e5-a168-86a6c92a57bb)
Hi I am unable to do the JUnit. I have tried some other steps in the other forum which jevan reported on. I am still facing the same issue. 

Error message: 
(base) rithik@Rithiks-MacBook-Air ip % ./gradlew clean build
> Task :compileTestJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileTestJava'.
> Could not resolve all files for configuration ':testCompileClasspath'.
   > Could not find org.junitm.jupiter:junit-jupiter-api:5.10.0.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/junitm/jupiter/junit-jupiter-api/5.10.0/junit-jupiter-api-5.10.0.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
11 actionable tasks: 11 executed

**Comment by zaidansani** [comment]
Hmm, seems like an issue with your `build.gradle`. Mind sending how that looks like?

**Comment by rithiklenin** [comment]
![Screenshot 2024-09-02 at 1 13 41 AM](https://github.com/user-attachments/assets/f8c77870-d891-4706-91fc-2848ddc2a881)
![Screenshot 2024-09-02 at 1 13 47 AM](https://github.com/user-attachments/assets/1050b24b-25bf-436f-ac19-53b287fdb7b0)
Here's my build.gradle

**Comment by rollingpencil** [comment]
Could it be that gradle has not import the JUnit library? Your Project Structure > Libraries should look like this: ![Screenshot 2024-09-02 at 1 16 06 AM](https://github.com/user-attachments/assets/1b7a8b41-63c3-414d-bb8c-ee7ca755329e)

**Comment by zaidansani** [comment]
Found the error. 

In your dependencies, you have it misspelled: ```testImplementation group: 'org.junitm.jupiter'```.
```testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.10.0'``` is the right name.

Thus, your Gradle is unable to fetch the dependency from the repository. This should work.

**Comment by damithc** [comment]
> In your dependencies, you have it misspelled: `testImplementation group: 'org.junitm.jupiter'`.

Good sleuthing, @zaidansani 💯

**Comment by rithiklenin** [comment]
> Found the error.
> 
> In your dependencies, you have it misspelled: `testImplementation group: 'org.junitm.jupiter'`. `testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.10.0'` is the right name.
> 
> Thus, your Gradle is unable to fetch the dependency from the repository. This should work.

Thank you. Managed to fix it.
