### ISSUE TITLE
Association Classes vs Dependencies

### ISSUE THREAD

**Issue by jagdeepsh** [nus-cs2103-AY2425S1/forum#173]
Hi just wanted to clarify what the main difference is between Association Classes and Dependencies:

From my understanding, Dependencies are classes that does not store a reference to any other classes but relies on other classes to perform certain tasks and association is referred to classes that does in fact store references to other classes.

The following is a quote from the lecture notes on the course website that I have pasted for reference:
> Dependencies vs associations:
> 
> An association is a relationship resulting from one object keeping a reference to another object (i.e., storing an object in an instance variable). While such a relationship forms a dependency, we need not show that as a dependency arrow in the class diagram if the association is already indicated in the diagram. That is, showing a dependency arrow does not add any value to the diagram.
>
> Similarly, an inheritance results in a dependency from the child class to the parent class but we don't show it as a dependency arrow either, for the same reason as above.
>
> Use a dependency arrow to indicate a dependency only if that dependency is not already captured by the diagram in another way (for instance, as an association or an inheritance) e.g., class Foo accessing a constant in Bar but there is no association/inheritance from Foo to Bar.

My question is, in the photo pasted below for reference, doesn't the association class act like a dependency class as well? It does not store any references of other classes as shown in the example, rather just a utility base Class to store just a `startDate` and `returnDate` in example.

Dependencies:
![IMG_0047](https://github.com/user-attachments/assets/1a00ca0a-2952-4b5a-a621-05f6f00e8b08)

Association Classes:
![IMG_0048](https://github.com/user-attachments/assets/5992fb40-baee-409d-995d-fc4ad33f816a)

**Comment by damithc** [comment]
@JagdeepSinghNUS While waiting for inputs from others, I want to point out that the comparison you are trying to do is not strictly apples to apples. Dependency is a directional link between classes (a weaker type of association), not a class. There is no such thing as a _dependency class_. So, you can "there is a dependency from `ReviewGenerator` to `Chapter`" but you can't say "`ReviewGenerator` is a dependency class".

**Comment by jagdeepsh** [comment]
Ahh I see, so dependencies are just relationships rather than looked at as a class itself. I thought a Dependency Class was an actual thing, similar to an Association Class.

With that being said the Association Class itself has a dependency relationship to the other classes they are linked to, just that they represent the association itself. So based on the examples shown above, `Loan` represents the association between `Student` borrowing `Book` where as `PreviewGenerator` does not represent any association, but is mainly there just to perform certain operations making it dependent on other classes, the key point here would be that in that example, `PreviewGenerator` does not represent any association relationship but is dependent on `Chapter`, whereas `Loan` represents the association relationship between `Student` and `Book` and thus also making it dependent to both of those classes as well?

Would this be correct?

**Comment by damithc** [comment]
> Ahh I see, so dependencies are just relationships rather than looked at as a class itself. I thought a Dependency Class was an actual thing, similar to an Association Class.
> 
> With that being said the Association Class itself has a dependency relationship to the other classes they are linked to, just that they represent the association itself. So based on the examples shown above, `Loan` represents the association between `Student` borrowing `Book` where as `PreviewGenerator` does not represent any association, but is mainly there just to perform certain operations making it dependent on other classes, the key point here would be that in that example, `PreviewGenerator` does not represent any association relationship but is dependent on `Chapter`, whereas `Loan` represents the association relationship between `Student` and `Book` and thus also making it dependent to both of those classes as well?
> 
> Would this be correct?

Yes @JagdeepSinghNUS, that is the general idea.

**Comment by jagdeepsh** [comment]
I see, thanks prof for the clarification :)
