### ISSUE TITLE
Realised error in code after pushing commit (with tag)

### ISSUE THREAD

**Issue by muhdbhz** [nus-cs2103-AY2425S1/forum#175]
Hi, I am about to proceed with Week 4 IP and I realised that while testing my program, I forgot to catch an IndexOutOfBoundsException and thus it terminated my program early. However, I have already pushed that particular commit with the tag and now I'm not sure if I will be marked down for that particular tag.  

(context) My task list had 3 tasks so I inputted delete 4 and it terminated my program. 

Would like to seek advice on this matter: Should I just push a new commit with no tags to rectify the issue?  Or should I do something else? Thank you very much :)

Sorry if this thread already exists. May have missed it out while browsing through.

**Comment by Gra7ityIC3** [comment]
Quoting from the FAQ [here](https://nus-cs2103-ay2425s1.github.io/website/schedule/week2/project.html#faq-about-ip-increments):
> Go ahead and fix it in a subsequent commit. There is no need to update the previous commit or move the corresponding tag to the new commit. As we do not test your code at every tag, earlier bugs will not affect your grade as long as they are fixed eventually. Similarly, feel free to improve the code of previous increments later.

**Comment by muhdbhz** [comment]
Ahhh I missed that part. Thank you very much!
