### ISSUE TITLE
Gradle not catching exceptions but IntelliJ does

### ISSUE THREAD

**Issue by muhdbhz** [nus-cs2103-AY2425S1/forum#176]
Hi, I'm using Java 17 (corretto-17) as my SDK and my gradle JVM is also the project SDK (corretto-17)

When I run my program with IntelliJ and purposely write **any** command that throws an exception, the exception is caught and my program doesn't terminate. However, when I run the program with gradle and do the same thing, the exception is not caught and my program terminates as a result. I checked with my friends and they do not have this issue.

IntelliJ (exception caught and handled)
![Screenshot 2024-09-02 131655](https://github.com/user-attachments/assets/1634ecbe-8a03-4a82-82ad-ed931e786948)

Gradle (exception not caught, program terminates)
![Screenshot 2024-09-02 131728](https://github.com/user-attachments/assets/65b9b4df-68cb-41d2-b1a0-0a51fd9afecb)

I believe this has something to do with my gradle settings but I am not sure. I have checked my code to handle said errors. Would like to seek advice please.

If any code needs to be provided, please let me know!

**Comment by Incogdino** [comment]
I believe gradle is doing what it needs to as intended, which is to report the exceptions thrown as specified in the build.gradle file. 

To continue inputting commands you can click on the first tab here.
![image](https://github.com/user-attachments/assets/9d3bc60d-a480-4b79-80d4-6a867449932c)

**Comment by muhdbhz** [comment]
Oh wow it works hahaha. What a trivial fix. Thanks a lot friend!!!
