### ISSUE TITLE
Mistyping in JavaFX Tutorial Part 1 on SE-EDU

### ISSUE THREAD

**Issue by DennieDan** [nus-cs2103-AY2425S1/forum#177]
I noticed this minor typo in the ``Main.java`` code snippet or 
Isn't the comment for the line of code ``stage.setScene(scene)`` supposed to be ``// Setting the stage to show our *scene*`` instead of ``screen``?
![Screenshot 2024-09-02 150554](https://github.com/user-attachments/assets/df8278f1-4548-4dfa-8e23-9373c5a9a536)

**Comment by damithc** [comment]
@DennieDan Good catch, @DennieDan 
Fixed.
