### ISSUE TITLE
Question about week 1 quiz Lists

### ISSUE THREAD

**Issue by RezwanAhmed123** [nus-cs2103-AY2425S1/forum#18]
Hi I am confused about this question:

![image](https://github.com/user-attachments/assets/ac44bd2b-37c2-4b04-ad67-8261e273da24)

While it is true that a list can be created using this method, I wrote false as the type of element of the list was not specified.

**Comment by Incogdino** [comment]
This is inferred as a rawtype so the statement technically works. What are you confused about?

https://docs.oracle.com/javase/tutorial/java/generics/rawTypes.html

**Comment by RezwanAhmed123** [comment]
Ah ok thanks, I just realised that it was inferred to be rawtype. Thanks!
