### ISSUE TITLE
UML Diagrams: Bidirectional vs opposite unidirectional associations

### ISSUE THREAD

**Issue by vinceg4** [nus-cs2103-AY2425S1/forum#181]
From the textbook, it seems that two opposite two unidirectional associations between two classes does not always result in a bidirectional association. This was illustrated by the example:
```
class Person {
    Cat pet;
    //...
}

class Cat{
    Person breeder;
    //...
}
```
I interpreted this as a class diagram like this:
<img width="344" alt="image" src="https://github.com/user-attachments/assets/c2a84b20-a80a-475c-9c80-c4a2b82f4b2c">

Then, another example showcasing bidirectional association was given by this example:
```
class Dog {
    Man man;
    // ...
}

class Man {
    Dog dog;
    // ...
}
```

So with these two examples we see that simply having a class `B` attribute in class `A` and a class `A` attribute in class `B` might not always result in bidirectional association. In the first example, we say that the breeder might not be the owner of the pet so we separate the associations. Yet, in example 2, it does not seem quite apparent to me that the "`man`" and "`dog`" are referring to the same association. The `man ` in `Dog` could refer to the owner/breeder, etc.

I am not sure if it is correct but my take on this is that the attributes should be named in a way that provides the context so that a clear association can be established. If i renamed the `breeder` to `person` in the first example, how would I know if the association is bidirectional or two separate associations?

**Comment by damithc** [comment]
> I am not sure if it is correct but my take on this is that the attributes should be named in a way that provides the context so that a clear association can be established. If i renamed the `breeder` to `person` in the first example, how would I know if the association is bidirectional or two separate associations?

@vinceg4 Good question. In this case, you need to find out more about the context e.g., referring to documentation, talking to the developer who wrote the code, based on what you know about the application domain etc.
A related point is that it is usually not possible to draw UML diagrams simply based on the code -- that's why we can't rely on automated generation of diagram from the code alone.
