### ISSUE TITLE
Change Commit

### ISSUE THREAD

**Issue by tyxiangs** [nus-cs2103-AY2425S1/forum#182]
I'm currently in the last stage of my progress but I just found out I have make a mistake at previous level. How can I solve it ? If I make changes, commit and retag the commit, I will have all the tag starting from that level up to my current level on a single commit and the file for each tag will be the latest product of my bot. Is it fine to do so ?

**Comment by damithc** [comment]
@tyxiangs Just fix it in a new commit. No other changes need. More info in this iP FAQ https://nus-cs2103-ay2425s1.github.io/website/admin/appendixC-faq.html#faqs-on-ip

**Comment by tyxiangs** [comment]
I didn't include the loading task from hard disk when opening the bot operation which is task in level 7. I am currently at the progress after level 8. So I just add loading operation in my project, commit and push it to fix them ?

**Comment by Feng1231** [comment]
> I didn't include the loading task from hard disk when opening the bot operation which is task in level 7. I am currently at the progress after level 8. So I just add loading operation in my project, commit and push it to fix them ?

Yes! Its stated in the faq. You do not have to retag.
