### ISSUE TITLE
My ip progress isn't showing

### ISSUE THREAD

**Issue by thisisaditya17** [nus-cs2103-AY2425S1/forum#185]
It was working perfectly till yesterday. But suddenly its all red now!!
I didn't change my github username or anything.
What should i do??

<img width="993" alt="image" src="https://github.com/user-attachments/assets/3782761b-df01-428c-a1aa-ada2385e737b">

**Comment by damithc** [comment]
@thisisaditya17 Could be a temporary issue  of the dashboard script not being able to access your repo. You can check again later. In the meantime, your repo seems to have quite a few 'unexpected' folders, perhaps results of a botched Gradle integration.
![image](https://github.com/user-attachments/assets/97405d68-a9e5-4ad8-b5d2-5ebecc79468a)
You might want to clean that up too.
