### ISSUE TITLE
Am I allowed to add the Exception class later if I forgot to implement it?

### ISSUE THREAD

**Issue by Elinengu** [nus-cs2103-AY2425S1/forum#190]
Hello, I forgot to implement an Exception class for my iP. Am I allowed to implement it later? If yes, then when is the due date for it? Also, do I need to delete the original tag for my A-More OOP and tag this new commit as A-More OOP, or should I just make it a new commit on master?

**Comment by damithc** [comment]
@Elinengu Just fix it in a new commit and move on. More info in this FAQ https://nus-cs2103-ay2425s1.github.io/website/admin/appendixC-faq.html#faqs-on-ip

**Comment by JoanneHing** [comment]
Can also refer to #182 , updates can be made after you commit, you do not have to modify the tags or commit made : D
