### ISSUE TITLE
gradle Unsupported class file major version 65

### ISSUE THREAD

**Issue by jan-kai1** [nus-cs2103-AY2425S1/forum#193]
When running gradle commands, I get the following error
`FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'ip'.
> Could not open cp_proj generic class cache for build file 'D:\School\y2s1\CS2103T\individual\ip\build.gradle' (C:\Users\andro\.gradle\caches\7.6.2\scripts\1xrtyde626ulr1v849j1u6gea).
   > BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 65
`

The error seems to be caused by mismatching java versions but gradle is configured to use the same version as the project
It usually resolves by restarting intellij and running ./gradlew wrapper but is there a configuration issue that is causing this error?

**Comment by damithc** [comment]
@jan-kai1 While waiting for inputs from others, you can share some additional info:
* How are you running Gradle commands? via Intellij UI or via a separate terminal?
* Is this in the iP or when doing the JavaFX tutorial?
* Was it working before? When did it started happening?

**Comment by jan-kai1** [comment]
I am running gradle commands from the terminal using ./gradlew
This occurs in the iP
The issue occurs intermittently, unsure of when it first started

**Comment by damithc** [comment]
@jan-kai1 Three more questions:
* Did you add Gradle support by merging the `add-gradle-support` branch we provided, or some other way?
* What's the output for the `java -version`command?
* Does the problem still happens if you clone the fork to another location continue in that location?

**Comment by jan-kai1** [comment]
* Yes I added it by forking the add-gradle-support branch
 ```
$ java -version
java version "21.0.1" 2023-10-17 LTS
Java(TM) SE Runtime Environment (build 21.0.1+12-LTS-29)
Java HotSpot(TM) 64-Bit Server VM (build 21.0.1+12-LTS-29, mixed mode, sharing)
```
* The terminal uses java 21, is that what causes conflicting issues?
* Unsure, will test it out

**Comment by damithc** [comment]
@jan-kai1 Use Java 17. That's a course requirement.

**Comment by jan-kai1** [comment]
Changing the terminal java version worked

**Comment by yadobler** [comment]
I want to add on, if anyone is facing this issue and have correctly set the java path to point to java17, but face this issue, check if the IDE is using the **correct gradle file**. 

_File > Settings > Build, Execution, Deployment > Build Tools > Gradle_

Choose `Local Installation` for _Distribution_, choose the gradle folder that you should have merged into your local repo. Also ensure the _Gradle JVM_ is `17`. 

---

Whenever I switch branches, my IDE for some reason resets this.
