### ISSUE TITLE
No feedback to give!

### ISSUE THREAD

**Issue by maahir-garg** [nus-cs2103-AY2425S1/forum#194]
The code I have been asked to review looks great, as such there is no feedback to give, what are the 5 comments to do?

**Comment by damithc** [comment]
> The code I have been asked to review looks great, as such there is no feedback to give, what are the 5 comments to do?

@maahir-garg Code reviews don't always have to be negative comments or suggestions for improvements; you can also comment on positive aspects e.g., `good job applying the xyz coding standard rule here`, `I like how you applied technique Z here to make this code shorter`. 
Also, you can mention alternative ways of implementing the same thing, for the author's consideration. e.g., `I did this using technique X but I see you applied technique Y -- I think yours is a better choice, although one downside is ...`

**Comment by FYL2003** [comment]
In my opinion, you can implement A-checkstyle and put the PR into that to see whether there is any violations.
