### ISSUE TITLE
Code all in one line

### ISSUE THREAD

**Issue by jevan13** [nus-cs2103-AY2425S1/forum#196]
![Screenshot 2024-09-04 at 6 42 17 PM](https://github.com/user-attachments/assets/a783aaac-d751-4d62-9aba-14f8c547af75)
Does anyone know why all my code in is one line? When I open my file in Intellij everything is fine, but one Github it looks like this.

**Comment by yisiox** [comment]
Hi @jevan13 , I'm dropping by from your senior batch. This sounds like a line separator issue - can you try changing the line separator setting in IntelliJ? See [IntelliJ's page on this](https://www.jetbrains.com/help/idea/configuring-line-endings-and-line-separators.html). Otherwise, are you able to provide any more details like your OS / when did this start happening?

**Comment by zhonghan721** [comment]
Hi @jevan13 , I am a senior from your previous batch. As @yisiox have mentioned, there seems to be a line separator issue. Perhaps you might also want to check if there is any editor config file that might be overriding the line separator setting in IntelliJ as mentioned [here](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000554939-Intellij-adding-M-newline-characters)?

**Comment by zaidansani** [comment]
In addition to what the above have said, there's also these `^M` characters in your code - which I don't think SHOULD appear - they're the carriage return (for new lines). See this forum [here](https://stackoverflow.com/questions/1822849/what-are-these-ms-that-keep-showing-up-in-my-files-in-emacs).

Do you happen to be coding on two computers (Windows & Mac)?

**Comment by AdityaB4** [comment]
Hi @jevan13, I am one of your seniors from last semester. Alongside what other's have mentioned, if I were trying to resolve this issue independently, things like opening the file in other text editors or IDEs would help you possibly isolate the issue to either the file contents themselves or IntelliJ (your IDE). It would also help to look out for things that seem unusual like the `^M` that was pointed out previously.

While this doesn't directly resolve the issue, I hope this helps develop your thought process for how you could attempt to resolve such issues.

**Comment by ThatGirlJam** [comment]
Hi @jevan13, I'm a senior from the previous batch. In addition to the suggestions above, perhaps you may like to check for issues related to commenting and uncommenting code, as well as the IntelliJ settings for that. It could also be an issue stemming from copying over code manually from a different text editor or application. 

Since it seems that the issue is only related to the GitHub version, you could try pushing your code to see if it updates correctly.

Hope you manage to resolve the issue 👍🏻

**Comment by woke02** [comment]
Hey @jevan13, it could also be worth checking your Git settings for line ending conversions, like core.autocrlf. Sometimes Git modifies line endings based on your OS, which might explain why it looks fine in IntelliJ but not on GitHub.

**Comment by jevan13** [comment]
@yisiox @zhonghan721 
Hi, I tried changing the settings to Windows(\r\n) and Unix and OS X(\n), both did not work.
I was previously using Classic Mac (\r)

**Comment by zaidansani** [comment]
You probably need to reformat your code. Right click on your `src` folder and reformat the code for the line separators to update!

**Comment by jevan13** [comment]
@zaidansani @woke02 
Hi, I tried using the command git config --global core.autocrlf true, but it still does not work.

**Comment by jevan13** [comment]
@zaidansani Do I have to commit or push anything to Github? Because I tried reformatting my code and it doesn't seem to change on Github.

**Comment by zaidansani** [comment]
> @zaidansani Do I have to commit or push anything to Github? Because I tried reformatting my code and it doesn't seem to change on Github.

After reformatting the code, is there changes detected (aka, is there anything to commit?) If so, commit and push them.

**Comment by jevan13** [comment]
@zaidansani Hi, there was something to commit, but after committing and pushing the new version was the same as the old. Nothing was changed, it is still in one line.

**Comment by zaidansani** [comment]
Interesting. I downloaded one of your files, and it still only shows the Carriage Return (/r), and not the (/n) as expected.

**Comment by zaidansani** [comment]
Interesting. I downloaded one of your files, and it still only shows the Carriage Return (/r), and not the (/n) as expected.

![image](https://github.com/user-attachments/assets/97be3790-9c9d-41a3-860d-ca55c0ce5956)

When you reformatted, did you tick YES on the `do not keep line breaks`? If you didn't, please try that? [IntelliJ's documentation on reformatting code](https://www.jetbrains.com/help/idea/reformat-and-rearrange-code.html#reformat_file)

**Comment by jevan13** [comment]
@zaidansani 
Sorry where is the "do not keep line breaks" button?
![Screenshot 2024-09-06 at 12 20 30 AM](https://github.com/user-attachments/assets/9c0091fd-a443-4caf-8dc0-dda6540e410f)

**Comment by jevan13** [comment]
@zaidansani 
Sorry where do you get the "do not keep line breaks" button? I checked the website but theirs seem to be different from mine.

Attached below is my version of reformatting a directory/file
![Screenshot 2024-09-06 at 12 20 30 AM](https://github.com/user-attachments/assets/d1a70351-947c-4a69-93e6-a06e1742b041)
![Screenshot 2024-09-06 at 12 23 23 AM](https://github.com/user-attachments/assets/869fc936-f2eb-45b8-b2d4-66237d736492)

**Comment by yisiox** [comment]
Hi @jevan13 , this is from the IntelliJ page on line separators, looks like it should allow you to change all the `\r`.

![image](https://github.com/user-attachments/assets/2e71ae2e-4a04-4751-b247-d1c84df53e69)

**Comment by zaidansani** [comment]
> Sorry where do you get the "do not keep line breaks" button? I checked the website but theirs seem to be different from mine.

Hmm, apparently that dialog is only for reformatting code.

However, I've found something else:

In your settings, under Editor > Code Style > Java > Wrapping and Braces,
turn off reformatting at line breaks (the first checkbox in the image below)

<img width="370" alt="image" src="https://github.com/user-attachments/assets/5ac99392-5489-404a-b759-44eae94f879a">.

This probably was preventing the line breaks from being reformatted.

**Comment by zaidansani** [comment]
> Hi @jevan13 , this is from the IntelliJ page on line separators, looks like it should allow you to change all the `\r`.
> 
> ![image](https://private-user-images.githubusercontent.com/107540644/364870684-2e71ae2e-4a04-4751-b247-d1c84df53e69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1NjE2NzksIm5iZiI6MTcyNTU2MTM3OSwicGF0aCI6Ii8xMDc1NDA2NDQvMzY0ODcwNjg0LTJlNzFhZTJlLTRhMDQtNDc1MS1iMjQ3LWQxYzg0ZGY1M2U2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNVQxODM2MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYzhiMDI1ZWQ1MzVjMTA1YjBlM2NkYWEzZmZkNmI4MzBlMjVhMWI0NjU1ZDRkNTNkOTUzMTU5NWZlOWY0Yzk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Y9T5HSe4MTQ6buCB44c0u-l5whZslmV-sZmW_Uhs2rI)

I think this changes the setting going forward, but not necessarily the files before (unless an explicit reformat is done).

**Comment by jevan13** [comment]
@zaidansani 
Hi, I turned off the line break settings and tried with both Windows (\r\n) and Unix and MacOS (\n).
Again, nothing changed on Github.
<img width="658" alt="Screenshot 2024-09-06 at 2 06 42 PM" src="https://github.com/user-attachments/assets/a9bac709-3654-451f-aa4e-92aeeaed92fc">

Also I cant access the image you sent.

**Comment by zaidansani** [comment]
Unfortunately, it seems like there's no way to change existing files in IntelliJ (at least from my research so far - if someone has a solution).

You probably have to find some way of converting all the CRs to CRLF or LF - obviously there are manual solutions - but perhaps this might be the best.

Assuming you're on Mac, open your terminal and use `mac2unix` to convert the files.

The command is `mac2unix FILE` - try it on one file, commit and see if it works on Github, then if it does, you can do it for the rest of the files!

<img width="1432" alt="image" src="https://github.com/user-attachments/assets/452b7e20-cfe8-4fb9-8065-1217b442e10f">

(if you are doing this, for consistency, set your line separator settings to /n (Linux and Unix) so that your new files follow this setting!).

**Comment by jevan13** [comment]
@zaidansani 
Thank you so much! Changing my settings to \n on IntelliJ, reformatting src, followed by using mac2unix for every file worked!
