### ISSUE TITLE
Peer review file format with ^M symbol

### ISSUE THREAD

**Issue by Bonzzz3** [nus-cs2103-AY2425S1/forum#197]
<img width="569" alt="Screenshot 2024-09-04 at 6 40 57 PM" src="https://github.com/user-attachments/assets/f913caa2-4cc2-4235-836d-87f9ce3d1b50">

I am trying to review the backup PR's code but most of the classes are in this format with a weird ^M symbol. I'm not sure if it's my settings problem. How do I fix this?

**Comment by damithc** [comment]
@Bonzzz3 You can post a comment asking the PR author to fix this problem. If the PR author doesn't fix it fast enough, you can review the backup PR instead.

**Comment by zaidansani** [comment]
Pretty sure in this case, the PR author has the issue in #196 with the line separators.

**Comment by Bonzzz3** [comment]
> @Bonzzz3 You can post a comment asking the PR author to fix this problem. If the PR author doesn't fix it fast enough, you can review the backup PR instead.

Unfortunately I couldn't find the primary PR so I moved to backup PR but his PR code is all in one line as appear in the screenshot above. Is it ok if I randomly comment on someone else's code as long as they are not in my CS2103T group?

**Comment by damithc** [comment]
> Unfortunately I couldn't find the primary PR so I moved to backup PR but his PR code is all in one line as appear in the screenshot above. Is it ok if I randomly comment on someone else's code as long as they are not in my CS2103T group?

@Bonzzz3 Yes, that's fine.
