### ISSUE TITLE
Question on working across multiple workstations?

### ISSUE THREAD

**Issue by winstonlimjy** [nus-cs2103-AY2425S1/forum#198]
Am I required to install Sourcetree on all workstations if all files are saved on a central cloud drive? Will there be conflicts in editing the same file saved on the same cloud drive across workstations without committing..? Thanks~

**Comment by RezwanAhmed123** [comment]
I've tried this before but i notice onedrive sometimes will revert/cancel changes by itself sometimes if it notices many files were changed. I recommend doing a 

`git fetch`

or

`git pull`

Every time you start work on a different workstation just to be safe.

**Comment by damithc** [comment]
> I've tried this before but i notice onedrive sometimes will revert/cancel changes by itself sometimes if it notices many files were changed.

Yup, some past students also reported that OneDrive sometimes messes up Git repos. Other cloud drive services might have similar issues. So, best not to put Git repos under other file sync services.

**Comment by winstonlimjy** [comment]
> I've tried this before but i notice onedrive sometimes will revert/cancel changes by itself sometimes if it notices many files were changed. I recommend doing a
> 
> `git fetch`
> 
> or
> 
> `git pull`
> 
> Every time you start work on a different workstation just to be safe.

which would mean.. i need to finalise a working copy and push on 1 workstation before moving on the another workstation (pulling)?

**Comment by zaidansani** [comment]
> which would mean.. i need to finalise a working copy and push on 1 workstation before moving on the another workstation (pulling)?

Yep, hence why it is generally just better to have a local copy on both machines and push everytime you want to move to the other machine. The convenience of syncing ala-GDrive/OneDrive may be lost, but you're a lot more likely to not run into unexpected behaviour. (for example, editing on one side, then editing on the other PC and the syncing causing some conflict within the changed file).

Git also has some behaviour that isn't seen sometimes when you do push which is helpful for maintaining code across different OSes - `core.autocrlf` for example is a Git setting that helps manage line separators (that differ in Mac and Windows)

**Comment by winstonlimjy** [comment]
Thanks!

**Comment by damithc** [comment]
@winstonlimjy If you do each increment in a separate branch and merge it to `master` only when the increment is done, it is somewhat acceptable for you to push half-complete code to that branch. So, when you switch computers, you can just commit whatever you have in the working folder and push to that branch without needing to 'finalize' the code.
