### ISSUE TITLE
Proper way of exiting JavaFx Application on "bye" command

### ISSUE THREAD

**Issue by NgZiXin** [nus-cs2103-AY2425S1/forum#199]
Hello! Based on my understanding, to exit from JavaFx GUI application, you can call the following function:
```java
import javafx.application.Platform;

Platform.exit();
```

My question is where do you call it? In _MainWindow#handleUserInput_, or do you have a `public void handleExit() { Platform.exit(); }` method in the _Main_ class which is passed into the _MainWindow_ class and called as a callback function?

Or is there a cleaner way to exit the application which I am missing? Please share your ways! Thank you! 😀

**Comment by MAOXIONGKAI** [comment]
I think at this point of time you can leave it as it is, but putting it inside a `handleExit()` method may help in the future if your program actually needs to invoke multiple clean up methods before the program actually exit, in that case having a method to handle exit logics and stuff all the clean up methods inside can make the code a lot cleaner. Hope this idea helps

**Comment by RezwanAhmed123** [comment]
I just removed it entirely, since there is a x button to just close the window, no need to recreate another exit point in my opinion.

**Comment by tckeong** [comment]
I still keep the "bye" command, so when the user input this command, my chatbot will like "sleep", it will not process the input from the user anymore.

**Comment by SeanFoongjt** [comment]
Not exactly sure if this is good, but what I essentially did was inject the stage into the `MainWindow` like how the Duke equivalent was injected into it with *MainWindow#setDuke*, then had *MainWindow#handleUserInput* detect when the user input was "bye" ( or when Duke / your equivalent responded with the bye message) and invoke the *Stage::close* function of the injected stage. 

This seemed to work as typing "bye" would close the window. The handleExit method sounds neater though!

**Comment by jagdeepsh** [comment]
For me personally the way I did it was adding on an if statement in their `handleUserInput()` method as referenced in their tutorial notes by checking if the `String response` that you get from your `getResponse()` method from your `Duke` instance contains the word `Bye`, I just added something like the following:

```java
// Stop the JavaFX application from running after bye command
if (response.contains("Bye")) {
    Platform.exit();
}
```

**Comment by emmannyyy** [comment]
I did something very similar to @JagdeepSinghNUS but i noticed that just typing Platform.exit() would immediate close the window, without allowing the user to read my goodbye message. 

To handle this, I added a time-delay to allow the user to read the final message (i.e: confirming that his log has been saved successfully, and the program would exit in 3 seconds) 

I did put this under the "handle input" method in MainWindow.java

Here is how I did it: 
```java
    @FXML
    private void handleUserInput() {
       //earlier irrelevant part of method body not shown
        if (response.equalsIgnoreCase(monique.getUi().showGoodbye())) {
            PauseTransition pause = new PauseTransition(Duration.seconds(3));
            pause.setOnFinished(event -> stage.close());
            pause.play();
        }
    }
```
