### ISSUE TITLE
Unable to run code as JavaFX runtime components are missing, and are required to run this application

### ISSUE THREAD

**Issue by niclammm** [nus-cs2103-AY2425S1/forum#200]
I am unable to run my code due to this error: JavaFX runtime components are missing, and are required to run this application. I have checked my dependencies shown in the tutorial but still can't figure out why I am experiencing this. Since I use gradle to run the application, I am unsure about how to approach the problem. Any help would be appreciated :-) 
Also, I forked the repo in the tutorial and tried the tutorial code and it works 

![Errorplease help](https://github.com/user-attachments/assets/42c0f75e-15e6-4a41-a2e3-b3cc0f2dc9bd)

**Comment by damithc** [comment]
While waiting for inputs from others, here are some things you can try:
* Push the code to a branch and share here so that other can try to replicate the problem.
* Try these 'common remedies' one-at-a-time in this order:
  * Run `./gradlew clean build run`
  * Choose `File` -> `Invalidate caches`
  * Close Intellij -> Delete the `.idea` folder -> Re open the project in Intellij
  * Clone the fork to a different location and open the project in Intellij again to get a fresh start without losing changes you did so far.

**Comment by niclammm** [comment]
Thank you for the help, actually I found a fix but I'm not sure why it works. I placed my main class in one of my classes that i implemented. However, after moving my main class to the Launcher class as shown in tutorial, it runs. Why is this so ahah?

**Comment by zaidansani** [comment]
> Thank you for the help, actually I found a fix but I'm not sure why it works. I placed my main class in one of my classes that i implemented. However, after moving my main class to the Launcher class as shown in tutorial, it runs. Why is this so ahah?

What do you mean by this exactly - do you mean the `mainClass.set` in your build.gradle?

**Comment by niclammm** [comment]
![image](https://github.com/user-attachments/assets/84686058-9a5b-4d51-8a08-2d26e73090de)
![image](https://github.com/user-attachments/assets/adad4ec0-e461-4a91-895b-82549bbac83e)
In this first Image, I had my main class in one of my chatbot classes. I thought I could initialise my chatbot that way but it resulted in the error shown above. 
In the second Image, I created the launcher class as show in tutorial 1 and my code could run. 
In the first part of the tutorial it is stated that the launcher class is used to work around a classpath issue but they didnt go into detail as to why. Could be something else though im not too sure myself

**Comment by zaidansani** [comment]
Did some Googling, pretty sure it's the classpath issue as mentioned in the tutorial. Won't pretend I understand the technicalities of it all, but if you're curious: [the docs multiple forum answers refer to](https://mail.openjdk.org/pipermail/openjfx-dev/2018-June/021977.html).

Perhaps someone with more Java experience can decipher it, unfortunately I am clueless.
