### ISSUE TITLE
Building is very slow after adding javaFX

### ISSUE THREAD

**Issue by Rachelcoll** [nus-cs2103-AY2425S1/forum#203]
After adding javaFX to my code, building becomes very slow and I'm not sure if it will eventually output the result. My configuration is basically the same as the setup in the tutorial. It works fine with the javaFX tutorial, but basically it just stucks here in my project.
![image](https://github.com/user-attachments/assets/4a3fc799-1882-45ea-8b5e-a1e09dbf1493)

**Comment by damithc** [comment]
@Rachelcoll If you don't see the GUI after a few seconds, it's unlikely to show up later. So, something is wrong (e.g., the GUI is invisible and waiting for user input).

**Comment by anselmlong** [comment]
Is it normal for runs to take over 30 seconds each time? Mine's also slow, but eventually shows up.

**Comment by Rachelcoll** [comment]
> @Rachelcoll If you don't see the GUI after a few seconds, it's unlikely to show up later. So, something is wrong (e.g., the GUI is invisible and waiting for user input).

I feel like it's not the problem of my chatbot, because i just tested on tutorial and it also doesn't work now, not sure why is it

**Comment by JoanneHing** [comment]
Are you using Mac? 
I read some forum, seems like Mac will often run with problem if you are using Java 8.
I followed the guide line here, and my Mac so far run well with the JavaFx.
Hope this helps!

<img width="821" alt="Screenshot 2024-09-05 at 9 57 42 AM" src="https://github.com/user-attachments/assets/19786344-5b7f-4fc4-aef1-a7629c0772b8">

**Comment by Rachelcoll** [comment]
I found that it keeps loading because that I forgot to put `stage.show()` in Main class, thanks for all of your help!
