### ISSUE TITLE
Git Branch Merging

### ISSUE THREAD

**Issue by JoanneHing** [nus-cs2103-AY2425S1/forum#204]
Previously my JavaDoc branch was floating out of the master branch after commit.
And I think this may cause my branch not detected by the bot as this the only branch that is marked red in the iP progress.
<img width="519" alt="Screenshot 2024-09-05 at 9 39 36 AM" src="https://github.com/user-attachments/assets/706e63ff-22af-472d-b0a0-39cd5407fc08">

I spent some time solving it, and tried to turn off the fast-forwarding in Source Tree after reading this forum #131 
After some tries, now there is no more floating branches, but there is quite a lot of parallel branch created.
<img width="816" alt="Screenshot 2024-09-05 at 10 10 09 AM" src="https://github.com/user-attachments/assets/a541e06b-5d2a-42c0-9a3a-79a7fa3f7e67">

May I ask
1. Is the fast forwarding the reason causing the JavaDoc branch to be floating without merging back? Or is it cause by other problem (Not merging branch correctly, etc)
2. How to correctly merge branch to avoid creating a lot of parallel branch like the second screenshot?

Hope my question is clear :D

**Comment by damithc** [comment]
@JoanneHing While waiting for peer inputs, couple of things I noticed from the screenshots:
* Your branches don't seem to have the expected branch name e.g.,  should be `branch-A-Javadoc`
* There is still at least one branch that hasn't been merged to `master` yet (but you have merged `master` to that branch)

**Comment by JoanneHing** [comment]
Thank you prof for the reply!
Sorry for the careless mistake, I missed out the branch name :o
And I found out the branch that is not been merged! It looks more correct now. Did not realize that I accidentally did the reversed merge!

<img width="541" alt="Screenshot 2024-09-05 at 11 36 01 AM" src="https://github.com/user-attachments/assets/e0378725-5d6d-4f25-bf97-4ae5066a5402">
