### ISSUE TITLE
Errors when runningradlew.run

### ISSUE THREAD

**Issue by chengzihao123** [nus-cs2103-AY2425S1/forum#205]
I have just implemented the GUI for my chatbot and when I refactored my code and updated my build.gradle file. I met with this error when running gradlew.run

![image](https://github.com/user-attachments/assets/13387b4b-3af1-483e-8681-126c7b353238)

Does the error come from my build.gradle?
```
plugins {
    id 'java'
    id 'application'
    id 'com.github.johnrengelman.shadow' version '7.1.2'
    id 'checkstyle'
}

repositories {
    mavenCentral()
}

dependencies {
    String javaFxVersion = '17.0.7'

    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'linux'
    testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.10.0'
    testRuntimeOnly group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.10.0'
}

checkstyle {
    toolVersion = '10.2'
}

test {
    useJUnitPlatform()

    testLogging {
        events "passed", "skipped", "failed"

        showExceptions true
        exceptionFormat "full"
        showCauses true
        showStackTraces true
        showStandardStreams = false
    }
}

application {
    mainClass.set("main.Main")
}

shadowJar {
    archiveBaseName = "chattyBuddy"
    archiveClassifier = null
}

run {
    standardInput = System.in
    jvmArgs = [
            "--module-path",
            "C:/Program Files/Java/jdk-17/lib",
            "--add-modules", "javafx.controls,javafx.fxml"
    ]
}
```
I have tried to modify the run property but it doesn't seem to work.

**Comment by damithc** [comment]
@chengzihao123 While waiting for peer inputs, it might help others diagnose the problem if you share the following:

* What's your OS?
* What's the output for the `java -version` command?
* What happens if you run `./gradlew clean build run` from the terminal, in the project root folder.

**Comment by chengzihao123** [comment]
I am using Windows, currently using Java 17.0.7 and when i run `./gradlew clean build run` i see this:

![image](https://github.com/user-attachments/assets/141761fd-5800-4a0e-8667-640ced356484)

**Comment by suhayl13** [comment]
Hi! Maybe you can try running the command using `./gradlew run --debug` on your terminal. You will likely be met with a very verbose output. Search for sections named [ERROR] and it would point to exact location of error and we can try and find out the solution to the problem from there. There might be better ways to debug this but this is what I did when I encountered errors. Hope it helps!

**Comment by Anant1902** [comment]
Hi @chengzihao123, I'm a senior from your previous batch. You mention that you're using Java 17.0.7. That might be the potential issue... try changing your sdk to java 11 and see if it resolves this!

**Comment by yisiox** [comment]
Hi @chengzihao123 , I'm dropping by from your senior batch. I think it may be caused by having two instances of `public static void main(String[] args)`; in your `Launcher` and `Main` classes.

Hopefully its one of those odd cases of the error message not really being reflective of the issue.

**Comment by chengzihao123** [comment]
> Hi! Maybe you can try running the command using `./gradlew run --debug` on your terminal. You will likely be met with a very verbose output. Search for sections named [ERROR] and it would point to exact location of error and we can try and find out the solution to the problem from there. There might be better ways to debug this but this is what I did when I encountered errors. Hope it helps!

Hi this is what is shown for the error sections:
`2024-09-06T01:08:42.323+0800 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] `

**Comment by chengzihao123** [comment]
> Hi @chengzihao123, I'm a senior from your previous batch. You mention that you're using Java 17.0.7. That might be the potential issue... try changing your sdk to java 11 and see if it resolves this!

HI! I have tried to switching to java 11 but I still faced the same error.

**Comment by chengzihao123** [comment]
Hi everyone so much for your help! The issue is that I didn't download the JavaFX SDK. After downloading and putting it under JavaFX folder the run command works perfectly fine!
