### ISSUE TITLE
Issues running gradlew run

### ISSUE THREAD

**Issue by amitha2210** [nus-cs2103-AY2425S1/forum#207]
For the JavaFx tutorial, I tried running ./gradlew run on IntelliJ but I am getting an error about incompatible architecture. It says " (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')". 

I am using macOS and the java zulu JDK for both gradle and the IntelliJ project, anyone have suggestions on how to handle?

**Comment by damithc** [comment]
While waiting for peer inputs, it might help others diagnose the problem if you share the following:

* What's your Macbook model? e.g., M series?
* How did you install the zulu JDK?
* What's the output for the `java -version` command?
* What happens if you run `./gradlew clean build run` from the terminal, in the project root folder.

**Comment by amitha2210** [comment]
- Model is Macbook Air M2
- I installed the zulu JDK with the instructions in this guide: https://se-education.org/guides/tutorials/javaInstallationMac.html
- This is the output for the `java -version `command: 
openjdk version "17.0.12" 2024-07-16
OpenJDK Runtime Environment Homebrew (build 17.0.12+0)
OpenJDK 64-Bit Server VM Homebrew (build 17.0.12+0, mixed mode, sharing)
- It returns the same thing as` ./gradlew run` returns (`Task :run FAILED` followed by "`Loading library prism_es2 from resource failed: java.lang.UnsatisfiedLinkError:` ", file names and the error about incompatible architecture

**Comment by amitha2210** [comment]
I tried using new dependencies, suitable for ARM64 architecture, fixed the problem

**Comment by damithc** [comment]
> I tried using new dependencies, suitable for ARM64 architecture, fixed the problem

@amitha2210 Did you mean by changing build.gradle? If yes, that's not the right solution (this fix will affect the compatibility of your app on non-ARM Macs).

Based on your `java -version` output, your terminal is not using the Zulu SDK we prescribed. It's possible that you installed it but didn't set it as the default.
