### ISSUE TITLE
Are magic numbers coding standard violations?

### ISSUE THREAD

**Issue by matthewyip1511** [nus-cs2103-AY2425S1/forum#208]
While reviewing the PR for this week's iP task, it came to mind that magic numbers were taught as bad coding practices in lower level courses but is not explicitly stated as a coding standard violation the the course material in CS2103. May I therefore check what the stance on magic numbers is? Thank you!

**Comment by RezwanAhmed123** [comment]
Hi just a disclaimer, I have no official info, but going according to what I have seen in the lecture notes and examples so far, I think magic numbers should be fine as long as it’s within a very small scope say a short method. For a bigger method, I still don’t think it’s a code violation but I would still name it cause I forget what I’m doing with that number quite often 😂.

**Comment by SeanFoongjt** [comment]
Building on what RezwanAhmed123 said, going off what is available in the course materials magic numbers should be fine if it is clear what the magic number represents. At the same time, I'll wager its probably best not to use it as far as possible given that the naming convention at the [Week 4 topics page](https://nus-cs2103-ay2425s1.github.io/website/schedule/week4/topics.html#w4-6-code-quality-naming) specify that names like label1 label2 are already frowned upon.

**Comment by damithc** [comment]
Thanks for raising this, @matthewyip1511 

There are two questions here:
1. Are magic numbers a coding standard violation, as per the course's coding standard?
2. Are magic numbers bad for code quality? (and follow up questions such as, why they are bad, when is it acceptable to use them, when are they not acceptable to use etc.)

First one: we should be able decide now, as the coding standard is already in force now.
Second one: good to discuss for the time being (the topic of magic numbers is scheduled for a later week).

**Comment by matthewyip1511** [comment]
Got it, thanks prof! I'll keep these in mind and look out for when magic numbers are covered :)
