### ISSUE TITLE
iP progress not reflected under Admin Tasks 

### ISSUE THREAD

**Issue by potaotototo** [nus-cs2103-AY2425S1/forum#209]
Under my individual iP progress, iP increments is updated to A-Packages, but somehow the admin tasks show that from branch-Level-7 it was already all overdue. Is there anything I can do regarding this inconsistency?

**Comment by potaotototo** [comment]
![Uploading Screenshot 2024-09-05 at 5.03.51 PM.png…]()

**Comment by potaotototo** [comment]
<img width="879" alt="Screenshot 2024-09-05 at 5 03 51 PM" src="https://github.com/user-attachments/assets/4f30107a-b73a-4dac-bbee-8d90c56ac4a3">

**Comment by rahula1008** [comment]
You could check out this similar issue: #185 

Could I ask for some more details regarding this?

1. Firstly, did you submit everything on time? If so, this is likely a bug, but can you send a screenshot of your source tree branch merge details. This is to make sure you have merged everything correctly. 
2. Secondly, are you sure you pushed your local branches to the remote repository. If you didn't, you may have just pushed the tag and commit, and thus it won't identify your branches.

**Comment by damithc** [comment]
@potaotototo 
At the top of the [iP progress dashboard](https://nus-cs2103-ay2425s1.github.io/dashboards/contents/ip-progress.html), there are a couple of tips about troubleshooting when an increment related to a tag or a branch is not green as expected. See if those help you locate the problem.
