### ISSUE TITLE
Where to put my Level-XX tag?

### ISSUE THREAD

**Issue by Jianwen0451** [nus-cs2103-AY2425S1/forum#21]
I have a question about putting my tags Level-XX. At first, I completed Level 4 and tag it. Then I discovered a few formatting errors and fixed them. Where should I put my Level-4 tag? At the first or after formatting changes?

**Comment by damithc** [comment]
@Jianwen0451 You are welcome to move the tag to the new commit (that way, you can learn how to move tags), but this is not required. 
More info in the FAQ [here ](https://nus-cs2103-ay2425s1.github.io/website/schedule/week2/project.html#faq-about-ip-increments)
