### ISSUE TITLE
Common Multiplicities 

### ISSUE THREAD

**Issue by ITZXITZX** [nus-cs2103-AY2425S1/forum#212]
Hi Prof, 

I was wondering if you could update the notes, section "UML Class Diagrams -> Associations -> Multiplicity", under "Commonly used multiplicities", with the multiplicity "**1..*** 1 or more" as written in your slides but is not currently written in the notes explicitly?

Thank you.

![image](https://github.com/user-attachments/assets/4f915d40-e3ca-45e1-bd4f-4982087b97cc)

![image](https://github.com/user-attachments/assets/43a49502-d137-478a-bf6e-a51aec3a777e)

**Comment by shotnothing** [comment]
This doesn't seem like a bug, more of an improvement? It is covered under the `n..m` point, but I think it would be better explicitly stated, yeah

**Comment by ITZXITZX** [comment]
Understand, thanks Prof

**Comment by damithc** [comment]
> Understand, thanks Prof

That answer wasn't from me :-p

Anyway, I've added a few examples to the `n..m` explanation in the textbook, to cover `1..*` case as well.
