### ISSUE TITLE
Is the space intended in the Java Conventions site?

### ISSUE THREAD

**Issue by yadobler** [nus-cs2103-AY2425S1/forum#213]
I refer to the [Java coding standard (basic + intermediate)](https://se-education.org/guides/conventions/java/intermediate.html), specifically under _Layout > Place line break to improve readability_ 

![image](https://github.com/user-attachments/assets/b38bdc4c-db18-46d0-b0f5-df843faa1f3e)

Is there supposed to be 2 spaces before `.method2()`?

```
method(param1,
        object.method()
                .method2(),  <<< Must this be aligned or indented?
        param3);
```

**Comment by jayjay19630** [comment]
From my understanding, it seems that the above is intentional due to the 8 spaces required for wrapped lines: 

> Indentation for wrapped lines should be 8 spaces (i.e. twice the normal indentation of 4 spaces) more than the parent line.

However, I do agree that in the case of method chaining, it does look cleaner if the methods were aligned. I don't know if we're allowed to make suggestions to the coding style, though.

**Comment by damithc** [comment]
@yadobler For consistency, follow the 8-space rule. Trying to align the dot will cause inconsistency, as the indentation will then depend on the length of the method name (which can vary widely).
