### ISSUE TITLE
Should JUnit tests for text-based UI be removed or changed after GUI is implemented?

### ISSUE THREAD

**Issue by psh12320** [nus-cs2103-AY2425S1/forum#215]
Hello. I would like to check if the JUnit tests can be deleted or changed after GUI has been implemented. 

In my case, I had to change some other methods to adapt to a GUI and as such, the JUnit tests have compilation errors and will need to be changed as well.

When the iP is graded, do the markers check the JUnit tests before Level-10 or the tests at the end?

**Comment by damithc** [comment]
@psh12320 JUnit tests need to adapt as the code changes. We'll be grading the code at the end.
