### ISSUE TITLE
Unable to resolve javafx in fxml file

### ISSUE THREAD

**Issue by gabriellegtw** [nus-cs2103-AY2425S1/forum#216]
# Context
Hi! I'm currently on the last step of the JavaFX tutorial. However, for some reason my fxml files have multiple errors as my javafx and related classes are unable to be resolved. (I'm using Intellij on Windows btw)

More specifically, the below import statements are unable to be resolved:

```fxml
<?import javafx.scene.layout.AnchorPane?>
<?import javafx.scene.control.TextField?>
<?import javafx.scene.control.Button?>
<?import javafx.scene.control.ScrollPane?>
<?import javafx.scene.layout.VBox?>
```

This is a screengrab of the error messages:
<img width="252" alt="image" src="https://github.com/user-attachments/assets/f9b40fb7-1458-4903-a40f-a2f42e845b7e">

# Steps taken (that did not work)

I have followed the other parts of the tutorial exactly up to this point. I have searched how to resolve this on the web and done the below to try to resolve it (but it still showed the same issues):

- Ensuring that I am using the correct JDK/SDK
- Clearing Intellij cache
- Ensuring that my file directory structures are correctly set up
- Ensuring that my files are marked correctly (eg. marking resources folder as a resources folder)
<img width="217" alt="image" src="https://github.com/user-attachments/assets/e99a8733-c4da-4fc3-ace6-4788b29c1d8d">

- Ensuring that `fx:controller` correctly points to duke.MainWindow (as I placed it in a package)
- Ensuring that javafx plugin is enabled in Intellij

I have also tried editing the build.gradle file, but to no avail:

Initially, this was my build.gradle file:

```java
plugins {
    id 'java'
    id 'application'
    id 'com.github.johnrengelman.shadow' version '7.1.2'
}

repositories {
    mavenCentral()
}

dependencies {
    String javaFxVersion = '17.0.7'

    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'linux'
}

application {
    mainClass.set("Launcher")
}

shadowJar {
    archiveBaseName = "javafx-tutorial-duke"
    archiveClassifier = null
}
```

I also tried changing it to this after looking at the forum:

```java
plugins {
    id 'java'
    id 'application'
    id 'com.github.johnrengelman.shadow' version '7.1.2'
    id 'org.openjfx.javafxplugin' version '0.0.12'
}

repositories {
    mavenCentral()
}

dependencies {
    String javaFxVersion = '17.0.7'

    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'linux'
}

application {
    mainClass.set("Launcher")
}

shadowJar {
    archiveBaseName = "javafx-tutorial-duke"
    archiveClassifier = null
}

javafx {
    version = "17.0.7"
    modules = [ 'javafx.controls', 'javafx.fxml' ]
}
```

Thank you!

**Comment by damithc** [comment]
@gabriellegtw Can you push your code to a  fork of the tutorial starter repo and share the link here?

**Comment by gabriellegtw** [comment]
Hi @damithc , here's the link: https://github.com/gabriellegtw/javafx-tutorial

Thank you!

**Comment by k-hian** [comment]
Hi @gabriellegtw, not sure if this is directly related to your error, but your `application` in build.gradle is pointing to `Launcher` without the package. (I'm using terminal to run gradle so I'm unable to replicate the exact error)

You can try change to the following and see if the error still persist:
```java
application {
    mainClass.set("duke.Launcher")
}
```

Hope this helps.

**Comment by QinHaichen12** [comment]
Are the error messages in the screenshot all of the errors that occurred in the file?

**Comment by gabriellegtw** [comment]
Hi @k-hian ,

Thanks for that! I changed it and unfortunately the error still persists :/ Either ways, I am able to launch the GUI (because I was able to follow the tutorial up to step 3)

<img width="303" alt="image" src="https://github.com/user-attachments/assets/901abe4d-db47-47b0-a02e-afd011238a01">

**Comment by gabriellegtw** [comment]
Hi @QinHaichen12 

Thanks for commenting! No, those are not all the errors. Here is the full list:

_NOTE: Ignore the fact that the last error says "MainWindow" instead of "duke.MainWindow", I've shifted around some files on my local repo since the time I've posted this (It previously said "duke.MainWindow" when I posted this query because everything was packaged within duke). 

Previously, changing "duke.MainWindow" to anything else (eg. "MainWindow") leads to more errors. So I suspect the problem lies with javafx and not so much the file structure, but I may be wrong._

<img width="277" alt="image" src="https://github.com/user-attachments/assets/5c6dc8da-3688-43d5-bccc-e5922a80472c">

**Comment by gabriellegtw** [comment]
Okay I have resolved the issue and I'm putting it here in case anyone needs it. 

1. Ensure that the "resources" file is marked as a source file and not a resource file. You can do this by checking that the file icon next to the word resources looks like this:
<img width="92" alt="image" src="https://github.com/user-attachments/assets/e1081bdf-ddaf-4bab-a9d4-d234daee488c">

(Initially mine had a yellow logo instead)

2. Not sure if this affects anything, but I also ensured that the Main, MainWindow, DialogBox and Launcher classes were outside my `duke` package

3. If you're using Intellij, right click on the import statements and select "Show Context Actions". There should be a list of actions that appears (mainly adding different modules and dependencies). I just clicked on each one until the error messages all went away.

Thanks @damithc , @k-hian and @QinHaichen12 for help on this!
