### ISSUE TITLE
A-CheckStyles Error

### ISSUE THREAD

**Issue by tyxiangs** [nus-cs2103-AY2425S1/forum#217]
Hi, I have followed the steps given but I get URL is  not registered error. How to resolve this ?
![Screenshot 2024-09-06 110933](https://github.com/user-attachments/assets/57a5a4ab-e048-4b8d-82f1-67f291faf371)
![Screenshot 2024-09-06 111048](https://github.com/user-attachments/assets/6163b124-d8b7-4569-8a31-832d440a75d9)

**Comment by itsnotsherm** [comment]
Hi, have you tried highlighting the error (hovering cursor over the line) and fetching external resource? Do update if this works ! :)

**Comment by itsnotsherm** [comment]
Hi, have you tried highlighting the error (hovering cursor over the line) and fetching external resource? If not, try Build > Clean Project, do update if this works ! :)

**Comment by damithc** [comment]
![image](https://github.com/user-attachments/assets/99f4df52-14d4-4489-af73-6e1aaea2e318)

An `h` missing here?

Another thing you can try:
![image](https://github.com/user-attachments/assets/0c96634c-ee8c-4dff-883f-ee3b5dc458de)

**Comment by chengzihao123** [comment]
Hi I also faced the same issue. The warning says that the URL is not registered. What you need to do is to go to `Settings` -> `Languages & Frameworks` -> `Schemas and DTDs`. Under the `Ignored schemas and DTDs` section click on `+` and then you copy and paste the URL inside. After that the warning would go off.

**Comment by ChinSekYi** [comment]
I agree with both solutions mentioned above. Tried it and both works.
