### ISSUE TITLE
A-CheckStyles Error

### ISSUE THREAD

**Issue by tyxiangs** [nus-cs2103-AY2425S1/forum#218]
Hi, I have followed steps given but I get URL is not registered error.
![Screenshot 2024-09-06 110933](https://github.com/user-attachments/assets/351f7a25-8fcc-4be8-bce6-36129b3ef975)
![Screenshot 2024-09-06 111048](https://github.com/user-attachments/assets/2b83db4a-7d34-4c06-bf50-9f3d87701a5f)

**Comment by Andrew22Teoh** [comment]
Hi, I also have this error on my IntelliJ but the checkstyle runs just fine! 

<img width="619" alt="image" src="https://github.com/user-attachments/assets/03ca3959-ecbb-4fe4-97d3-de6befaa5508">
<img width="594" alt="image" src="https://github.com/user-attachments/assets/a61cdd94-733e-45c0-abf1-1f9935291694">
<img width="569" alt="image" src="https://github.com/user-attachments/assets/b57a4e8a-61d2-4e02-a94b-364bba1c0998">

Could you try running `./gradlew checkstyleMain checkstyleTest` and see if it works, or if you get an error message?

**Comment by Andrew22Teoh** [comment]
Btw, just a side note: if you right click the red text in IntelliJ and click `Show Context Actions`, you can click on `Fetch External Resource` and that removes the error!

**Comment by tyxiangs** [comment]
I get this error after I fetch external resources
![Uploading Screenshot 2024-09-06 113410.png…]()

**Comment by psh12320** [comment]
Here are the steps I took to resolve this error:

1. Copy-paste the links on the internet. 

2. Once done, the files `configuration_1_3.dtd` and `suppressions_1_2.dtd` will be downloaded. 

3. You can paste those files within the same `config/checkstyle` folder as `checkstyle.xml` and `suppressions.xml`.

4. After doing the above, you can write the following code instead:

``` xml
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "configuration_1_3.dtd">

```

The same can be done for `suppressions.xml`.

There will be no longer be any URI not registered error.
