### ISSUE TITLE
Extend MainWindow to have a Stage as a root Node

### ISSUE THREAD

**Issue by Judy1x4** [nus-cs2103-AY2425S1/forum#219]
In JavaFX tutorial part 4 – Using FXML Exercise section, I am confused by the phrase:

>  Extend MainWindow to have a Stage as a root Node.

I am not sure how to make a Stage as a root node of MainWindow and don't know what concept I should be applying.

**Comment by damithc** [comment]
@Judy1x4 You can ignore those exercises. We revamped the tutorial contents recently but didn't have time to look at the exercises yet.

**Comment by damithc** [comment]
In case anyone else is reading this thread later, I've removed the exercises section from the JavaFX tutorial, for now.
