### ISSUE TITLE
Edit checkstyle.xml file for import statements

### ISSUE THREAD

**Issue by matchastack** [nus-cs2103-AY2425S1/forum#220]
Hi, I am currently using the `checkstyle.xml` from AB3.

In order to pass the check style, I will have to arrange my import statements like this
```java
import java.io.IOException;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;
import zbot.ui.MainWindow;
```

However, I think that the following will be more suitable
```java
import java.io.IOException;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;

import zbot.ui.MainWindow;
```

Does anyone know how I can edit the `checkstyle.xml` file in order to achieve this? Thank you!

**Comment by MAOXIONGKAI** [comment]
Hi, I have tried played around with the `checkstyle.xml` file and this approach may help with your issue.
1. First locate the following block of code in your `checkstyle.xml`
```
<!--
    IMPORT CHECKS
    -->

    <!-- Checks the ordering of import statements follow the rules that the default Eclipse formatter uses.
    The order rule "STATIC###STANDARD_JAVA_PACKAGE###SPECIAL_IMPORTS###THIRD_PARTY_PACKAGE" consists of:
      1. STATIC: static imports
      2. STANDARD_JAVA_PACKAGE: standard java/javax imports
      3. SPECIAL_IMPORTS: defined as org imports
      4. THIRD_PARTY_PACKAGE: defined as com imports
    -->
    <module name="CustomImportOrder">
        <property name="customImportOrderRules"
            value="STATIC###STANDARD_JAVA_PACKAGE###SPECIAL_IMPORTS###THIRD_PARTY_PACKAGE"/>
        <property name="specialImportsRegExp" value="^org\."/>
        <property name="thirdPartyPackageRegExp" value="^com\."/>
        <property name="sortImportsInGroupAlphabetically" value="true"/>
    </module>
```
2. Change `<property name="specialImportsRegExp" value="^org\."/>` to `<property name="specialImportsRegExp" value="^javafx\."/>`
3. Change `<property name="thirdPartyPackageRegExp" value="^com\."/>` to `<property name="thirdPartyPackageRegExp" value="^zbot\."/>`

Now you should see the warning fading away when you use your own way to import packages. I have tried this approach in my own code and it works pretty well:

<img src="https://github.com/user-attachments/assets/70723399-7124-44d8-9719-91a3bec539fa" width="50%" />

However, just to say that I don't fully understand the initial values used by these two properties so there may be some repercussions when you change the file in the above way. But the general idea should be group the imports in separate groups and specify their order in the `CustomImportOrder` property, then `checkstyle.xml` should automatically reinforce line separations between the desired groups.

**Comment by matchastack** [comment]
Thanks for the help!
