### ISSUE TITLE
Can we resolve conversation after addressing the issues pointed out by the PR reviewers?

### ISSUE THREAD

**Issue by MAOXIONGKAI** [nus-cs2103-AY2425S1/forum#221]
Hi prof, just as the title suggests, my code has some minor issues which have been pointed out by one of the reviewers and I have already addressed those issues in the latest version of my code. 

One example is as follows which is a simple fix on a typo, and GitHub has already marked this review as outdated:
![image](https://github.com/user-attachments/assets/06f78bf0-0608-453e-8986-a29390ef5885)

So I am just wondering whether is it ok for me to resolve such conversations or I should just leave everything as it is for grading purpose? Thank you!

**Comment by damithc** [comment]
@MAOXIONGKAI You can mark them as resolved.

**Comment by MAOXIONGKAI** [comment]
> @MAOXIONGKAI You can mark them as resolved.

Thank you prof!
