### ISSUE TITLE
mislabelled branch-Level-10

### ISSUE THREAD

**Issue by maahir-garg** [nus-cs2103-AY2425S1/forum#223]
I did not realise that the branch was supposed to be named specifically as branch-Level-10 so I simply named It as GUI what are the next steps to be taken?

**Comment by suhayl13** [comment]
Hi Maahir! You can simply rename the branch. The method is laid out [here](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch)

If you have not pushed the branch to your repo, then the following command would suffice `git branch -m <oldname> <newname>`

**Comment by JoanneHing** [comment]
Or else you can actually just rename the branch using SourceTree as shown in below
<img width="455" alt="Screenshot 2024-09-07 at 1 51 35 PM" src="https://github.com/user-attachments/assets/4dc2cdee-a279-4e79-8936-7944af30d28f">
And push your changes to Github and the branch name should be renamed! :D
