### ISSUE TITLE
Style for Class/Method annotations such as @Override 

### ISSUE THREAD

**Issue by SeeYangZhi** [nus-cs2103-AY2425S1/forum#227]
Could the style follow the first format as shown below, or must it be wrapped.
```java
@Override public String toString() {
    // Code ...
}
```

```java
@Override 
public String toString() {
    // Code ...
}
```

**Comment by AbdulrahmanAlRammah** [comment]
I believe the coding guidelines don't specify that the override statement should be its own line. However, conventionally override is placed above the method like in the 2nd example. I think either method is valid as far as standards for the course, but override being a separate line is better for readability.

**Comment by damithc** [comment]
> I believe the coding guidelines don't specify that the override statement should be its own line. However, conventionally override is placed above the method like in the 2nd example. I think either method is valid as far as standards for the course, but override being a separate line is better for readability.

Yes, let's stick with the more common usage of having `@Override` in a separate line.
