### ISSUE TITLE
Saving program data into a json file using json-simple library

### ISSUE THREAD

**Issue by DennieDan** [nus-cs2103-AY2425S1/forum#229]
## Library
[json-simple](https://code.google.com/archive/p/json-simple/)

## Purpose
The library provides methods for reading and writing JSON data in Java. Therefore, it can be used to parse the application's data to JSON objects for saving purposes and vice versa.

## License
The ``json-simple`` is released under the [**Apache License 2.0**](https://www.apache.org/licenses/LICENSE-2.0) .

**Comment by damithc** [comment]
@DennieDan Approved.
