### ISSUE TITLE
Text UI Testing Not Running

### ISSUE THREAD

**Issue by PeterHW963** [nus-cs2103-AY2425S1/forum#23]
I am doing the Text UI Testing right now on a Windows computer. After setting up the runtest.bat, input.txt and EXPECTED.TXT, what should I do? 

I have tried running the runtest.bat file and it returns
********** BUILD FAILURE **********
'javac' is not recognized as an internal or external command,
operable program or batch file.

The same error message appears when I use cmd (inside and outside IntelliJ) to run the runtest.bat file. I have also tried troubleshooting online by adding the JDK bin folder into my system path variable and it still does not work. 

Thanks for the help!

**Comment by damithc** [comment]
@PeterHW963 In case it matters, changes to Windows PATH are not seen by applications that are already running at the time you did the change. For example, if you were running the runtest.batch in Intellij terminal or in a powershell window or in a DOS terminal window, you need to restart that app to after you change the PATH variable.

**Comment by PeterHW963** [comment]
Thank you prof, it works now! I don't know why I didn't try doing that before asking here :(
