### ISSUE TITLE
Merge Conflict Issue

### ISSUE THREAD

**Issue by SherChew27** [nus-cs2103-AY2425S1/forum#231]
While I was trying to merge a branch into my master branch, there were some merge conflicts and I managed to deconflict them. However, now I have some random files that are not commited yet, as per the screenshot. 
<img width="593" alt="Screenshot 2024-09-07 at 3 50 45 AM" src="https://github.com/user-attachments/assets/964a3c94-7f79-4bf3-a68a-0970b195e681">

I have checked my remote repo and the Ui class is correct in the master branch. However, in my local repo, it still contains 2 copies of the Ui class. Do I just delete the excess files and the old Ui class?

Alternatively, since the remote repo is correct, is it safe for me to just re-clone the remote repo again and delete these files?

**Comment by KennethTeo2002** [comment]
These files are auto-generated by Git when it encounters a merge conflict. So after you resolve the conflicts and complete the merge, it is safe to remove these files.
