### ISSUE TITLE
Normal to fail gradle runs?

### ISSUE THREAD

**Issue by verakohh** [nus-cs2103-AY2425S1/forum#233]
<img width="887" alt="image" src="https://github.com/user-attachments/assets/71d904b1-f0c3-4e77-81b4-f25d2b072dff">
<img width="887" alt="image" src="https://github.com/user-attachments/assets/c11020d7-8e1f-4d6b-8eed-68415bb70979">

Hi! Can I ask if it's normal to fail the gradle runs even if my gradle build is successful? When i run `./gradlew run` my application works correctly as well. Thank you!

**Comment by Incogdino** [comment]
There is probably a version mismatch between your local gradle version and the one specified by the project. `gradlew` uses the gradle wrapper and ensures it builds or runs with the version that was specified in your project. 

Check out the answer [here](https://stackoverflow.com/a/39627421/16322247) for more

**Comment by verakohh** [comment]
@Incogdino Thank you so much!

**Comment by damithc** [comment]
@verakohh See if cloning your fork to a new location and opening it in Intellij resolves this problem (thereby shedding any 'other' Gradle installations that you did in the current project set up).

**Comment by verakohh** [comment]
@damithc Hi Prof Damith! I just tried this and it could build and run successfully on the clone. I then realised my language level under project structure was different from the SDK, so that was probably the problem. Thank you so much for your help!
