### ISSUE TITLE
jar file JavaFX runtime components are missing,

### ISSUE THREAD

**Issue by NorbertLoh** [nus-cs2103-AY2425S1/forum#234]
I am able to run the program as usual and have no issues generating a JAR file. However, when I try to run the jar file, I get this error.
![image](https://github.com/user-attachments/assets/5b666397-7107-462f-b83c-fffb8f9957f2)

I have tried following the jar file tutorial and added

```
repositories {
    mavenCentral()
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
}
```

thank you!

**Comment by damithc** [comment]
@NorbertLoh While waiting for inputs from others, perhaps you can share the OS you are using, and the output for the `java -version` command? Also, what's the size of the jar file?

**Comment by NorbertLoh** [comment]
My current Java version is "17.0.12" I have tried javaFxSdk as well. The OS I am using is Windows.
The size of the jar file is 10,474 kb (10.474 mb).

**Comment by damithc** [comment]
> My current Java version is "17.0.12" I have tried javaFxSdk as well. The OS I am using is Windows.
> The size of the jar file is 10,474 kb (10.474 mb).

@NorbertLoh post here the _full_ output of the `java -version` command followed by your command to run the jar file in the same terminal. It's easier to spot the issue when one can see the full picture.

**Comment by NorbertLoh** [comment]
C:\Users\\ip\build\libs>java -version
java version "17.0.12" 2024-07-16 LTS
Java(TM) SE Runtime Environment (build 17.0.12+8-LTS-286)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.12+8-LTS-286, mixed mode, sharing)

C:\Users\\ip\build\libs>java -jar cow.jar
Error: JavaFX runtime components are missing, and are required to run this application

**Comment by yadobler** [comment]
[This](https://stackoverflow.com/questions/51478675/error-javafx-runtime-components-are-missing-and-are-required-to-run-this-appli) might help.

Your javafx install part should be `C:\Program Files\JavaFX\javafx-sdk-<VERSION_NUMBER>`

**Comment by Javiery3889** [comment]
Hi @NorbertLoh, I am from your senior batch. I came across a similar issue in previous CS2103 iterations, https://github.com/nus-cs2103-AY2324S1/forum/issues/118 and https://github.com/nus-cs2103-AY2021S1/forum/issues/128.

Perhaps you can modify your `build.gradle` file to point to the `Launcher` class as such:
```
application {
    mainClass.set("cow.Launcher")
}
```

**Comment by damithc** [comment]
> Perhaps you can modify your `build.gradle` file to point to the `Launcher` class as such:
> 
> ```
> application {
>     mainClass.set("cow.Launcher")
> }
> ```

To add, ensure `./gradlew run` works. If that doesn't work, the jar file wont work either.

**Comment by itstrueitstrueitsrealitsreal** [comment]
Hi @NorbertLoh, another senior from a previous batch weighing in here, [this step](https://se-education.org/guides/tutorials/javaFxPart1.html#writing-your-first-java-fx-program) in the guide is pretty informative and might help you out. 
The reason why you might need to set the main class to `cow.Launcher` instead of `Launcher` or `cow.Main` is because the main class is now located in the `Launcher` class of the `cow` package, after carrying out the steps in part 1 of the javaFX guide.
Don't hesitate to ask more questions if you have any doubts!

**Comment by NorbertLoh** [comment]
> Hi @NorbertLoh, I am from your senior batch. I came across a similar issue in previous CS2103 iterations, [nus-cs2103-AY2324S1/forum#118](https://github.com/nus-cs2103-AY2324S1/forum/issues/118) and [nus-cs2103-AY2021S1/forum#128](https://github.com/nus-cs2103-AY2021S1/forum/issues/128).
> 
> Perhaps you can modify your `build.gradle` file to point to the `Launcher` class as such:
> 
> ```
> application {
>     mainClass.set("cow.Launcher")
> }
> ```

That solved my problem. Thanks all!
