### ISSUE TITLE
Do we need to maintain the "bye" feature after implementing the gui?

### ISSUE THREAD

**Issue by matthewyip1511** [nus-cs2103-AY2425S1/forum#236]
Now that we have implemented in the GUI in week 4's tasks, I am curious if we still need to maintain the `bye` feature since the user is able to achieve this by simply closing the tab. Thanks!

**Comment by damithc** [comment]
@matthewyip1511 Yes, the 'bye' command is meant to be preserved (although we won't insist on it), as it allows the user to end the program the same way s/he was interacting with it for other things. 
Note how AB3 supports an `exit` command too.

**Comment by matthewyip1511** [comment]
I see, thanks Prof! I was having issue with implementing the "bye" command, but I'll take a look at how AB3 does it as well to get a better of idea of how it can be done 🙂
