### ISSUE TITLE
Unable to push A-CheckStyle

### ISSUE THREAD

**Issue by QuekBingHeng** [nus-cs2103-AY2425S1/forum#237]
After following the instructions, I am unable to push to my main branch with this error:

![Screenshot 2024-09-08 164103](https://github.com/user-attachments/assets/845a778e-2de7-4951-a402-981546806844)

Please send help. Thanks!

**Comment by QuekBingHeng** [comment]
I figured it out! I edited the README remote repo by accident and I used a pull request to update my local repo and I was able to push.

**Comment by damithc** [comment]
> I used a pull request to update my local repo

@QuekBingHeng Caution: Be careful when using terms _pull request_ and _pull_. The first is a GitHub feature while the latter is a Git feature.
