### ISSUE TITLE
Error with GUI; Unable to launch GUI

### ISSUE THREAD

**Issue by rithiklenin** [nus-cs2103-AY2425S1/forum#238]
Hi when I try to start my launcher, I get this error

```
/Users/rithik/Desktop/ip/src/main/java/optimus/DialogBox.java:6: error: cannot access javafx.collections.FXCollections
import javafx.collections.FXCollections;
                         ^
  bad class file: /Users/rithik/.gradle/caches/modules-2/files-2.1/org.openjfx/javafx-base/17.0.7/2b79238d65ff33212eafb04acc6acbb7cd0a3300/javafx-base-17.0.7-win.jar(javafx/collections/FXCollections.class)
    class file has wrong version 55.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
```
I am not sure how to proceed with this. I just copied over my files from the tutorial to the iP file.

**Comment by damithc** [comment]
@rithiklenin It might help if you also shared what happens when you run `java -version` followed by `.\gradlew run` in your terminal.

**Comment by rithiklenin** [comment]
<img width="759" alt="Screenshot 2024-09-08 at 5 07 07 PM" src="https://github.com/user-attachments/assets/9a7d9fbe-d4f7-4037-a236-f0cc1648e902">
This is my result for java -version

<img width="90" alt="Screenshot 2024-09-08 at 5 08 44 PM" src="https://github.com/user-attachments/assets/a618c058-404a-4b09-8f72-7721deffddc9">
and I get this when I run ./gradlew run

**Comment by rithiklenin** [comment]
This is my build.gradle for reference too


```
plugins {
    id 'java'
    id 'application'
    id 'com.github.johnrengelman.shadow' version '7.1.2'
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.10.0'
    testRuntimeOnly group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.10.0'

    String javaFxVersion = '17.0.7'

    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'linux'
}

test {
    useJUnitPlatform()

    testLogging {
        events "passed", "skipped", "failed"

        showExceptions true
        exceptionFormat "full"
        showCauses true
        showStackTraces true
        showStandardStreams = false
    }
}

application {
    mainClass.set("optimus.Launcher")
}

shadowJar {
    archiveBaseName = "Optimus"
    archiveClassifier = null
    mainClassName = 'optimus.Optimus'
    archiveFileName = 'Optimus.jar'

}

run{
    standardInput = System.in
}


```

**Comment by suhayl13** [comment]
Hi! 
The error message you are seeing indicates that there is a mismatch between the versions of the Java runtime you are using and the version of the JavaFX library in the project. It seems like you are using Java 8. To double check run `java --version` or you can go to `File -> Project Structure` in IntelliJ and check that the SDK you are using is **Java 17**. If not, switch the SDK to Java 17. But if you are using Mac then specific **Azul JDK 17** distribution must be used, just having Java 17 would not suffice. You may follow [this guide](https://se-education.org/guides/tutorials/javaInstallationMac.html) to install the specific SDK. Once installed, you can go back to project structure and select `zulu-17` as your SDK instead.

Hope this helps!

**Comment by rithiklenin** [comment]
Hi, I have already done all those you have mentioned above before seeking help. Could there be another reason why I am still experiencing such errors?

**Comment by damithc** [comment]
@rithiklenin Also ensure the Gradle JVM is set to project SDK, as mentioned in https://se-education.org/guides/tutorials/intellijImportGradleProject.html

![intellijSetGradleJvm](https://github.com/user-attachments/assets/e9b342b9-69aa-4bbf-9575-46e45c6762f2)

**Comment by rithiklenin** [comment]
Thank you. I found out that one of my paths were wrong in MainWindow in the fxml file causing the error.
