### ISSUE TITLE
CS2103T Week 5 Peer Evaluation

### ISSUE THREAD

**Issue by Reallyeasy1** [nus-cs2103-AY2425S1/forum#239]
Hi all,

Recently I have received an email, where one of the points stated that we need to submit the teammates prelim peer evaluation for this week. I would like to ask where we can get the link for the peer evaluation. 

![image](https://github.com/user-attachments/assets/30285a79-ea19-4f12-9a41-558c4dc193d1)

**Comment by uniqly** [comment]
I think it's mentioned in the link provided in the email and a reply to #230 by Prof @damithc to go to this link for [submission link session recovery](https://teammatesv4.appspot.com/web/front/help/session-links-recovery) to retrieve the link to peer evaluation form if you lost the original link or did not receive it yet.

But it seems that the _link was not sent to some people_ (or not sent out to begin with) as using the **recovery link does not show the peer evaluation form** (including me).

**Comment by damithc** [comment]
@uniqly @Reallyeasy1 
Thanks for the heads up. I set up the session just now. You should receive the submission link within the next hour.
