### ISSUE TITLE
Topic 5.3 Quiz Question Glitched

### ISSUE THREAD

**Issue by AbdulrahmanAlRammah** [nus-cs2103-AY2425S1/forum#240]
For topic 5.3 the question at 2:23 doesn't come up, so it is impossible to answer and continue the video. I tried viewing the video yesterday night and refreshing and it didn't work. I also tried today and I still have the same issue. 

![Screenshot (303)](https://github.com/user-attachments/assets/b21a93fd-fbb4-4f05-be98-f57a4966f63c)

Update: After refreshing again today the question finally came up. I am not sure what the issue was.

**Comment by rahula1008** [comment]
Hi @AbdulrahmanAlRammah 

I have had similar issues not just with this video, but a few different videos, sometimes it helps me to reload the page, then go back to that point, or restart the browser. It's frustrating, but I'm not sure whether there's a common fix for it.

**Comment by damithc** [comment]
@AbdulrahmanAlRammah As @rahula1008 mentioned, this usually goes away after refresh/restart of the Browser, or by using an anonymous Browser, trying a different Browsers etc. You can also try clicking the 'Close' on top right of your screenshot. 
It's likely a caching issue with Panopto (the 3rd party video delivery platform NUS uses), so not much we can do on our end.
