### ISSUE TITLE
Can't find level 10 branch and tag on github

### ISSUE THREAD

**Issue by verakohh** [nus-cs2103-AY2425S1/forum#242]
<img width="1202" alt="image" src="https://github.com/user-attachments/assets/018686c1-c522-41ea-84ef-1fe4f3844bbc">

<img width="781" alt="image" src="https://github.com/user-attachments/assets/783ba430-482b-4925-bf95-9c183203619a">

<img width="1065" alt="image" src="https://github.com/user-attachments/assets/7a0ba82a-a0f0-4c3c-9c25-28a2ecc62e6f">

Hi, I've completed my level 10 branch and merged it in to the master branch on source tree but i can't seem to find them on github.

**Comment by Incogdino** [comment]
Did you make sure to push the tag on sourcetree?

**Comment by Incogdino** [comment]
You also need to select the branch to push on sourcetree if you have not done it.

![image](https://github.com/user-attachments/assets/2255bd61-6f52-4e6d-9956-a0850124a844)

**Comment by verakohh** [comment]
@Incogdino Okay I've resolved it thank you so much!
