### ISSUE TITLE
Week 5 tp instructions typo

### ISSUE THREAD

**Issue by AbdulrahmanAlRammah** [nus-cs2103-AY2425S1/forum#243]
PS1 should include the word not.
current: We should have a clear overall direction.This ensures we always head in the right direction, even if the final product is defined precisely yet.

correct:  We should have a clear overall direction. This ensures we always head in the right direction, even if the final product is **not** defined precisely yet.

![Screenshot (304)](https://github.com/user-attachments/assets/b116f35a-20e3-4424-bd6f-a728d30f321d)

**Comment by damithc** [comment]
Good catch, @AbdulrahmanAlRammah 💯 
Fixed.
