### ISSUE TITLE
CheckStyle not working

### ISSUE THREAD

**Issue by verakohh** [nus-cs2103-AY2425S1/forum#245]
<img width="863" alt="image" src="https://github.com/user-attachments/assets/0889cb55-dce5-4c7b-a445-ed67fd3217b8">

Hi, I've already completed my week 4 code, including the A-CheckStyle Branch, and it worked two days ago. However, when I tried to run the checkstyle on my "Duke.java" file today, it said that the scan was skipped.
<img width="452" alt="image" src="https://github.com/user-attachments/assets/34bde9f7-0bf2-4ff0-8bd9-733e2491c29a">
<img width="981" alt="image" src="https://github.com/user-attachments/assets/1da148e4-61cb-42c7-8d75-613508922465">

Is there any way i could solve this?

**Comment by yadobler** [comment]
1. Can you post your `build.gradle` since the `./gradlew checkstyleMain' is based off that, instead of the plugin.
2. When you violate checkstyle in your code (like incorrect tabs) does it give the squiggly yellow checkstyle lines? (because mine does even though the panel below says "skipped" like your first image)

**Comment by verakohh** [comment]
`plugins {
    id 'java'
    id 'application'
    id 'checkstyle'
    id 'com.github.johnrengelman.shadow' version '7.1.2'
}

checkstyle {
    toolVersion = '10.2'
    configFile = file('config/checkstyle/checkstyle.xml')
}

repositories {
    mavenCentral()
}

ext {
    javaFxVersion = '17.0.7'
}

dependencies {
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'linux'

    testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.10.0'
    testRuntimeOnly group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.10.0'
}

application {
    mainClass.set("cleo.Main")
}

shadowJar {
    archiveBaseName = "Cleo"
    archiveClassifier = null
    archiveFileName = "Cleo.jar"
}

`

Here's my build.gradle code!
When i violated checkstyle in my code it used to show the squiggly lines back when i was done with the branch, but now it doesn't show any squiggly lines at all
@yadobler

**Comment by yadobler** [comment]
1. lmao you might wanna use three `\``s for code fencing if it's multilines
2. hm

ok Your gradle file and your checkstyle is working on my system:
![image](https://github.com/user-attachments/assets/bf4647d0-8d5f-40b9-bc14-17116a54ca70)

Intellij plugin also works for me:
![image](https://github.com/user-attachments/assets/6175cdf4-5cd2-4b68-92f6-05acc324706c)


---

You can try to:
1.go to `.idea` folder and 
2. delete `idea-checkstyle.xml`, `modules` folder, and `gradle.xml`
3. Then close and reopen Intellij
4. Rebuild gradle by pressing the tiny little elephant icon on the right
5. Reconfig the Checkstyle plugin (File->Settings, search checkstyle, then add the local file and name it and then add on the next window that pops up) then try again

If all else fails, try to File->Invalidate cache and try again

---

<details> <summary> Also </summary>

- I will delete your clone on my dist so no worries
- the bunny very cute

</details>

**Comment by verakohh** [comment]
oops mb i forgot about the ``s!!
but THANK YOU so much it works!!

<details>
<summary> </summary>
thank you  as well :))
