### ISSUE TITLE
Will GitHub Actions / CI be covered further down the course?

### ISSUE THREAD

**Issue by yadobler** [nus-cs2103-AY2425S1/forum#246]
I have an itch to set up Github actions to automate the `./gradlew shadowjar` and create the `.jar` file for each merge to master. 

But if that is going to be covered in future iterations, I will not waste my time tinkering with it now. 

Thanks

**Comment by damithc** [comment]
@yadobler We are not going to ask (or teach) you to automate the iP JAR creation. So, you are free to experiment with it now if you want.
