### ISSUE TITLE
Can we use AssertionError instead of assert

### ISSUE THREAD

**Issue by Soumyadip-cmd** [nus-cs2103-AY2425S1/forum#247]
![image](https://github.com/user-attachments/assets/bef591dc-fe42-4093-ba9c-6fe3320e3d5f)

As shown in the image, I was wondering if I can use AssertionError instead of assert

**Comment by yadobler** [comment]
I believe both does the work, but if you're pushing to production, compiling **without** the -ea flag will silent all `assert` statements, even if triggered. Throwing AssertionError means in production release your product might throw an error to the very very confused user (if it is not caught or handled). Might save you some embarrassment or tech support voes.

very evil but I don't trust the user to handle AssertionErrors, even though the programme will now be in an undefined state. I guess that's up for discussion 

also note that unless you `catch (Error e)` or `catch (Throwable e)`, it won't be caught. Usually we catch `Exception`s but never catch `Error`s (unless threading i think).

**Comment by Soumyadip-cmd** [comment]
Ok thank you
