### ISSUE TITLE
e.printStackTrace() shows warning in IDE

### ISSUE THREAD

**Issue by tata32000** [nus-cs2103-AY2425S1/forum#248]
![image](https://github.com/user-attachments/assets/59981278-9e01-4135-bde5-27d866cfb8c2)

Should we replace printStackTrace with a better logging method?

**Comment by damithc** [comment]
> Should we replace printStackTrace with a better logging method?

@tata32000 Yes, you may look for better ways to handle it. We haven't officially covered the topic of logging yet (it will be covered in a later week) -- so, the use of logging is not _required_ yet.

**Comment by tata32000** [comment]
Alright, thank you prof!
