### ISSUE TITLE
Class exception error for FXML, Level-10.

### ISSUE THREAD

**Issue by QuekBingHeng** [nus-cs2103-AY2425S1/forum#249]
Hi all, while following the JavaFX tutorial step by step for Level-10, I encountered an error when implementing FXML. 
![image](https://github.com/user-attachments/assets/922511ac-7b86-4874-8bdc-1df43c62cd1b)

This is the FXML file (MainWindow changed to GUIWindow):
![image](https://github.com/user-attachments/assets/a3bdaba5-1ce5-47af-b4d4-96436cc66c9c)

**Comment by tata32000** [comment]
I think your ```fx:controller="GUIWindow"``` part needs to reference to the package. 
For example, if you class is in duke package then it's ```fx:controller=duke.GUIWindow"```
