### ISSUE TITLE
Use of assert statements

### ISSUE THREAD

**Issue by OrangeCatLoves** [nus-cs2103-AY2425S1/forum#252]
Hi since assert statements are meant for testing important assumptions that should already hold (potential errors should already be handled such that the assumptions should hold) should we catch it if it's actually thrown. Or should our program function 100% correctly such that at all times it shouldn't be thrown at all because all assumptions should already hold, and that assert statements are simply just there for the last protective measure ?

**Comment by OrangeCatLoves** [comment]
or are assert statements mainly to serve as a form of documentation that clearly states the assumptions or constraints of the code at a specific point for easier debugging in future maybe, or for others to understand ur code better.
Since if perhaps errors/exceptions are potentially alr accounted for/handled, what's the use of assert statements

**Comment by Zenkoh1** [comment]
> Hi since assert statements are meant for testing important assumptions that should already hold (potential errors should already be handled such that the assumptions should hold) should we catch it if it's actually thrown. 

I don't think assertions should be "caught". You want to find out whether or not assertions are actually true asap, you don't want to try stopping the assertions from telling you something is wrong with your code.

From the course website:

> This is because an assertion failure indicates a possible bug and the sooner the execution stops, the safer it is.

**Comment by Zenkoh1** [comment]
> Since if perhaps errors/exceptions are potentially alr accounted for/handled, what's the use of assert statements

Raising errors/exceptions and assertions deal with different things.

From the course website:

> The raising of an exception indicates an unusual condition created by the user (e.g. user inputs an unacceptable input) or the environment (e.g., a file needed for the program is missing).
An assertion failure indicates the programmer made a mistake in the code (e.g., a null value is returned from a method that is not supposed to return null under any circumstances).

**Comment by RezwanAhmed123** [comment]
I think assert is used as a safeguard in future development. If the code logic for other methods above the code are changed and the assumption is broken, you will immediately know and change the code accordingly if you had not accounted for it previously.

In terms of error vs assert, in this case the code could still work but the assumption could have become invalid.

An example could be like your delete function. It could assume the add method has already checked if the task is valid or not. However later if you add a second adding method without the check for other purposes (loading a task from file) this could be invalid in SOME cases and not all. So the code could still work but the assumption will be invalid so you would then need to account for it.
