### ISSUE TITLE
Another account on commits?

### ISSUE THREAD

**Issue by rayray39** [nus-cs2103-AY2425S1/forum#254]
I just realised recently through week 5's activities (all the pull request and stuff) that another account of my full name is doing the commits, instead of my own github account name (rayray39). I have check using git config commands in my terminal that the account is my current account, rayray39. Why is it showing another account, the one with my full name (raynerlimfangyuh), instead of rayray39? And will this be an issue for grading?

![github question 2](https://github.com/user-attachments/assets/04abfeb9-9fd9-46ad-bdfa-97412f872312)
![github question](https://github.com/user-attachments/assets/1671475e-2b6f-4995-a39c-3bb835f164b3)

**Comment by damithc** [comment]
@rayray39 We don't use GitHub data when determining the author of a commit. So, that part should be fine -- any commit in your iP fork is considered as coming from you. However, we can track only one GitHub user for other GitHub actions, such as creating PRs. So, be careful to use only one GitHub account for iP and tP work.

**Comment by rayray39** [comment]
@damithc Hi prof, is there any way to fix this? I dont wish for this to be a problem in the future. Something that I thought might cause this issue is that my nus email is linked to raynerlimfangyuh account and my own gmail is linked to my current rayray39 account.
However, in git, using `git config --global user.email` the email is my nus email while the name is rayray39. Could this be the cause? And will it be solved if i change the git email to my own gmail account?

**Comment by damithc** [comment]
> However, in git, using `git config --global user.email` the email is my nus email while the name is rayray39. Could this be the cause? And will it be solved if i change the git email to my own gmail account?

@rayray39 You can try that and see if it works.

**Comment by rayray39** [comment]
Just an update: I have changed the email and pushed a commit, and it now shows the correct account as the author of the commit. I have yet to try it on a pull request etc. but I will close this for now and reopen if i face the issue again.
