### ISSUE TITLE
Error when pushing github workflows CI

### ISSUE THREAD

**Issue by winstonlimjy** [nus-cs2103-AY2425S1/forum#258]
There's an error when pushing the gradle.yml file to my repo. I'm not too sure what's this error about but I have previously connected sourceTree to github via option 1 (ss below). Does anyone have the same issue?

```
 ! [remote rejected] master -> master (refusing to allow an OAuth App to create or update workflow `.github/workflows/gradle.yml` without `workflow` scope)
 ! [remote rejected] A-CI -> A-CI (refusing to allow an OAuth App to create or update workflow `.github/workflows/gradle.yml` without `workflow` scope)
error: failed to push some refs to 'https://github.com/winstonlimjy/ip.git'
```

![image](https://github.com/user-attachments/assets/e3d4fd17-5a10-4ab6-9006-795f18de0934)

**Comment by winstonlimjy** [comment]
I managed to resolve this issue by generating a temporary personal access token and changing it in windows credentials manager! as shown in this [https://jessehouwing.net/cannot-push-to-github-without-workflow-scope/](https://jessehouwing.net/cannot-push-to-github-without-workflow-scope/)

**Comment by yadobler** [comment]
Just to add on, if anyone wants to `A-CI`and automatically deploy release Jar, you'll need to do this and add the token to the repository's `secrets` in the repo settings (do not paste secrets into tracked files! GH will never **forgive** you when you push those commits)

**Comment by damithc** [comment]
> There's an error when pushing the gradle.yml file to my repo. I'm not too sure what's this error about but I have previously connected sourceTree to github via option 1 (ss below). Does anyone have the same issue?

@winstonlimjy  You are right. I believe this method will create the authentication permission level to 'repo', which doesn't allow your pushes to make changes to workflows within the repo (it requires 'workflow' permission as well).
