### ISSUE TITLE
Text UI Testing showing failed even though the expected and actual are the same

### ISSUE THREAD

**Issue by aditig0305** [nus-cs2103-AY2425S1/forum#26]
line 27: dos2unix: command not found

I have tried using dos2unix as suggested by the troubleshooting section but it said command not found. Then I tried to follow steps to download it but I could not find clear or reliable restrictions. I'm not too sure how to resolve this.

**Comment by FYL2003** [comment]
Have you tried **brew install dos2unix**?

**Comment by FYL2003** [comment]
I followed the instructions given on ChatGPT and it works. Here is the thread url: https://chatgpt.com/share/0f8294bb-c191-483f-b9d7-8e93ac8d2770

**Comment by FYL2003** [comment]
@damithc prof I’m planning to write a troubleshooting issue to this for Mac, is it ok to show the GPT generated advice in this case?

**Comment by tohhengxing** [comment]
Your shell is unable to find the path of the `dos2unix` binary to execute the program.

**Comment by damithc** [comment]
> @damithc prof I’m planning to write a troubleshooting issue to this for Mac, is it ok to show the GPT generated advice in this case?

@FYL2003 Nice. Yes, provided you mention it somewhere.

**Comment by aditig0305** [comment]
> brew install dos2unix

I did this and followed the instructions. I think it works now. Thanks!
