### ISSUE TITLE
Made an error in ordering of PR/merging/commits

### ISSUE THREAD

**Issue by adipanda2002** [nus-cs2103-AY2425S1/forum#261]
![Screenshot 2024-09-11 at 2 13 02 PM](https://github.com/user-attachments/assets/e1b57e7e-bb71-44bd-8728-227f1559cb23)

For Week 5 tasks, I made an error by forgetting to merge changes made to master (from my first PR) into my second branch after merging my first PR. In other words, I merged my first PR, and then immediately merged my second PR without pulling the changes  made to master.

I think I have corrected the code, by then pulling the changes into the second branch and then merging the branch back to master using the regular merge method (without PR creation). Hence the git graph looks different to the instruction page. Is this okay? By okay I want to verify two things:

- will all the code updates be reflected correctly (on my own review it seems fine)
- will the grading scripts still detect my work correctly? @damithc

**Comment by damithc** [comment]
@adipanda2002 It's fine. It will not affect marks. The main thing is you understood how it should be and knows how to make it so.

**Comment by adipanda2002** [comment]
> @adipanda2002 It's fine. It will not affect marks. The main thing is you understood how it should be and knows how to make it so.

From my understanding, I missed step 3.4 in the instructions. After merging master (with changes pulled from the first PR) into my second branch, I did not push the updated branch to the remote. Is this correct? Or did I miss something else?

**Comment by damithc** [comment]
> From my understanding, I missed step 3.4 in the instructions. After merging master (with changes pulled from the first PR) into my second branch, I did not push the updated branch to the remote. Is this correct? Or did I miss something else?

@adipanda2002 Rather than trying to decipher what happened last time, you'll benefit more if can give it another try i.e., do two more changes (can be any changes you wish to do in the code) as two parallel PRs, and follow the steps correctly this time.
