### ISSUE TITLE
Assertions problem

### ISSUE THREAD

**Issue by verakohh** [nus-cs2103-AY2425S1/forum#263]
Hi! How do i know if my assertions are working after setting them up? 
<img width="832" alt="image" src="https://github.com/user-attachments/assets/91183bf0-db5f-4a09-b750-0d4146fb14a1">

I've added the -ea VM option for my ip[run]  but when i run the code below and make a new task, there are no errors shown. I'm not sure if it's not set up properly or if i'm not applying the assertions correctly.
```
 public Task(String description) {
        this.description = description;
        this.isDone = false;
        assert isDone == true : "Task should not be marked done yet.";
    }
```

**Comment by winstonlimjy** [comment]
Maybe you could set an ``` assert false; ``` to the start of the run method to see if the program crashes at the start of the program?

**Comment by verakohh** [comment]
<img width="531" alt="image" src="https://github.com/user-attachments/assets/2b3b97c2-df8d-476a-8d4d-1c886fe966a1">

```
    public String run() {
        assert false : "assert works";
        String greeting = ui.displayWelcomeMessage();
        return greeting;
    }
```

i get the above error when i insert it into my file.
<img width="826" alt="image" src="https://github.com/user-attachments/assets/ceec3885-15a0-429c-a26f-264cd4ca6db7">

**Comment by winstonlimjy** [comment]
Are you running with gradle? Did you add this 
```
run {
    enableAssertions = true
}
```
to your build.gradle file

**Comment by verakohh** [comment]
<img width="1709" alt="image" src="https://github.com/user-attachments/assets/3f086b7e-5b52-4fcf-a380-f6b3d34b102f">


Oh i didnt add that but after i did and ran with gradle, i did get an assertion error as one of the errors.

Thank you so much!! @winstonlimjy
