### ISSUE TITLE
💡A-CI Error: Unable to push workflow

### ISSUE THREAD

**Issue by ghos7ie** [nus-cs2103-AY2425S1/forum#264]
Hi, just wanted to share for those facing this issue when attempting A-CI increment.

![image](https://github.com/user-attachments/assets/50241632-a906-4df3-881e-630df4457a6c)

I solved this issue by following this [StackOverflow post](https://stackoverflow.com/questions/64059610/how-to-resolve-refusing-to-allow-an-oauth-app-to-create-or-update-workflow-on).

TLDR:
1. Creating a Personal Access Token in my Github account.
> Must store the PAT string somewhere as it will not be shown again once you leave the page.
2. Enable both repo and workflows in the PAT.
3. Removing all Github credentials (follow steps below the answer).
4. Login to SourceTree with PAT.
5. Push commit again.

Additionally, if you receive errors in your CI pipeline, you can check what went wrong under the `Actions` tab of your repo.

I had issues with CheckStyle and my JUnit tests, which caused my CI to fail.

**Comment by blackpanther9229** [comment]
By the way, this is more detail of how to do it with SourceTree:
1. Create (if you haven't had one) Personal Access Token that allows `workflow` in github.
2. Navigate to Repository -> Repository Settings and change the URL of `origin` from 
`https://github.com/<your_git_hubname>/ip.git`
to `https://<The_Personal_Access_Token_key>@github.com/<your_github_name>/ip.git`
You can see The_Personal_Access_Token_key after create the token.

**Comment by nuagetsu** [comment]
To add on for those not using SourceTree, I solved it on Windows 11 / IntelliJ by:

1. Creating a PAT that allows workflow in github
2. Going to IntelliJ > Settings > Version Control > Github > Sign in by token and adding the PAT
3. Going to Start > Settings > Windows Credentials manager and deleting my old git credentials
