### ISSUE TITLE
Is there any way to disable checkstyle in gradle check in CI file?

### ISSUE THREAD

**Issue by Rachelcoll** [nus-cs2103-AY2425S1/forum#265]
Currently my CI test always fail due to the failure of checkstyle, because I feel some checkstyle are unnecessary to follow. How can I disable it in `gradle.yml`? Currently I tried `
      - name: Build and check with Gradle
        run: ./gradlew check -x checkstyle
`
but is seems not working
![image](https://github.com/user-attachments/assets/c632f781-4892-4640-a560-1b9db8fe2029)

**Comment by stanleytangzh** [comment]
Hi, if you want to disable Checkstyle checks, you can use build and exclude the Checkstyle tasks. Thus, you can try ```- name: Build with Gradle with Gradle run: ./gradlew build -x checkstyleMain -x checkstyleTest ``` -x checkstyleMain and -x checkstyleTest are used to exclude the Checkstyle tasks. These tasks might be named differently depending on your configuration, but checkstyleMain and checkstyleTest are the standard names for Checkstyle tasks in many setups. To verify task names, you can also run the following command locally to list all available tasks and their names: ```./gradlew tasks --all```
