### ISSUE TITLE
Extension already supported in iP project

### ISSUE THREAD

**Issue by maahir-garg** [nus-cs2103-AY2425S1/forum#266]
For our extension, if my project already supports and extension like C-BetterSearch(All more flexibility in search e.g., find items even if the keyword matches the item only partially.) Do I need to pick something new to add or can I just tag this as done and move on?

**Comment by damithc** [comment]
@maahir-garg you can just add the tag if the feature is implemented already.

**Comment by maahir-garg** [comment]
Thanks a lot!

**Comment by MAOXIONGKAI** [comment]
@damithc Hi prof, would just like to clarify, under such situation am I allowed to pick another extension to work on? Thank you!

**Comment by damithc** [comment]
> @damithc Hi prof, would just like to clarify, under such situation am I allowed to pick another extension to work on? Thank you!

@MAOXIONGKAI Certainly. You can do other or more B/C/D extensions.
