### ISSUE TITLE
TestUI giving exception althought test cases pass

### ISSUE THREAD

**Issue by miuna9890** [nus-cs2103-AY2425S1/forum#27]
$ ./runtest.sh
Exception in thread "main" java.util.NoSuchElementException: No line found
        at java.base/java.util.Scanner.nextLine(Scanner.java:1651)
        at Flash.main(Flash.java:46)
dos2unix: converting file ACTUAL.TXT to Unix format...
dos2unix: converting file EXPECTED-UNIX.TXT to Unix format...
Test result: PASSED
Not sure why i keep getting an exception before testcases pass?

**Comment by Ponharish** [comment]
@miuna9890 Have you modified the file input.txt to contain all your inputs to your program before running the test?

**Comment by miuna9890** [comment]
yes it has all the inputs

**Comment by Ponharish** [comment]
Oh. Do you have the command "bye" or a similar one at the end of input.txt file? 
If this command is not present, the program must have not terminated and tried to read the next line which does not exist, hence throwing an exception

**Comment by Feng1231** [comment]
it could be because you did not check whether your scanner has next line. 
Have you tried invoking
hasNextLine() method before obtaining the next line?

**Comment by miuna9890** [comment]
i modified to add in bye and it worked. Thankss!
