### ISSUE TITLE
CodeCov not configuring

### ISSUE THREAD

**Issue by Judy1x4** [nus-cs2103-AY2425S1/forum#271]
I have followed the instructions for setting up CodeCov up to step 5, which involves checking the coverage status. However, what is displayed differs from what is supposed to be shown in the instructions.

the instruction:
![image](https://github.com/user-attachments/assets/f0bfc8ab-bee7-460e-941a-c9d9b2cbddc1)

my CodeCov tp repo page that is not being updated as above:
![image](https://github.com/user-attachments/assets/0e46fb61-a7e2-462c-bc73-3158fb4d55d2)

**Comment by damithc** [comment]
@Judy1x4 Coverage data will appear in that page _after the next time CI runs in your fork_ (e.g., after you push a commit to that repo).

**Comment by Judy1x4** [comment]
I solved it by making a change in the README text that has no effect as a commit.
