### ISSUE TITLE
Generating new jar with javafx now is causing problems for me

### ISSUE THREAD

**Issue by PresleyChew** [nus-cs2103-AY2425S1/forum#272]
![image_2024-09-12_231411547](https://github.com/user-attachments/assets/05e221e8-f0c5-47cb-a954-550771314e43)

I am able to run directly on intellij via launcher class however when it comes to running jar this pops up. Did not have this issue when creating jar without javafx. After implementing GUI and use of javafx, creating jar led to this.

**Comment by thisisaditya17** [comment]
I faced some issue with JavaFX as well. I don't know if this is the same but can check.

I changed my loader to this and it worked.
 FXMLLoader fxmlLoader = new FXMLLoader(Main.class.getResource("/view/MainWindow.fxml"));

**Comment by PresleyChew** [comment]
> I faced some issue with JavaFX as well. I don't know if this is the same but can check.
> 
> I changed my loader to this and it worked. FXMLLoader fxmlLoader = new FXMLLoader(Main.class.getResource("/view/MainWindow.fxml"));

Thanks for the reply! Just tried this and got the same outcome. Just to clarify the loader to be changed is located in Main class that extends from Application right?

**Comment by thisisaditya17** [comment]
Yeah

**Comment by yadobler** [comment]
Your function is catching an file not found exception but it's not the savefile but the image file:
![image](https://github.com/user-attachments/assets/7e184028-c368-4298-a6b3-2d65bcec22ea)

I believe there's a typo [here](https://github.com/PresleyChew/ip/blob/71746148d2c0de81f5d10629b21c974f99426236/src/main/java/gutti/MainWindow.java#L33):
```java
guttiImage = new Image(getClass().getResourceAsStream("/Image/Dagutti.png"));
//                                                              ^
```

**Comment by PresleyChew** [comment]
> Your function is catching an file not found exception but it's not the savefile but the image file: ![image](https://private-user-images.githubusercontent.com/49450747/367149863-7e184028-c368-4298-a6b3-2d65bcec22ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMDI2NDcsIm5iZiI6MTcyNjIwMjM0NywicGF0aCI6Ii80OTQ1MDc0Ny8zNjcxNDk4NjMtN2UxODQwMjgtYzM2OC00Mjk4LWE2YjMtMmQ2NWJjZWMyMmVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDA0MzkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyNTliMmE1NWI3YTMwNmViMGI4NDg1OTBiZWU0MDgyODZhMTk4NTA3MGUxMTI1ZmYwODczNDM1OGZlYWQ1MmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dp37qLnvuLoQMfJBHn3Ncp0RHLc6sSUcqAl4uv9vXQs)
> 
> I believe there's a typo [here](https://github.com/PresleyChew/ip/blob/71746148d2c0de81f5d10629b21c974f99426236/src/main/java/gutti/MainWindow.java#L33):
> 
> ```java
> guttiImage = new Image(getClass().getResourceAsStream("/Image/Dagutti.png"));
> //                                                              ^
> ```

Thanks! Fixed!
