### ISSUE TITLE
Could not load the briefing videos

### ISSUE THREAD

**Issue by thisisaditya17** [nus-cs2103-AY2425S1/forum#273]
<img width="819" alt="image" src="https://github.com/user-attachments/assets/831f0b4f-e911-40e7-82eb-ea2b4aa731c7">
I don't know why I am facing this issue. I have changed two browsers now. 
Even allowed third party cookies but still face this
<img width="678" alt="image" src="https://github.com/user-attachments/assets/f674cc8b-a187-4d4d-b7a4-b3de6dc785b5">

**Comment by damithc** [comment]
@thisisaditya17 Try a different browser?

**Comment by thisisaditya17** [comment]
@damithc I did prof. I was using brave before. Then I switched to Arc. It was working before but i started facing same issue from this week. Currently I have opened the course website in Chrome. It works but still i am confused about this issue.

**Comment by weiseng18** [comment]
I'm on macOS and I have this problem on Chrome as well. Safari works for me

**Comment by itsme-zeix** [comment]
I've had this issue on pretty much every Chromium browser - it randomly works on and off in Arc even after changing the cookie settings. Safari works great though.

**Comment by zzzlou** [comment]
Do you have any plugins like AdBlock installed? Try disabling it might help?
