### ISSUE TITLE
Variable scope in `switch`

### ISSUE THREAD

**Issue by weiseng18** [nus-cs2103-AY2425S1/forum#274]
I've noticed that variables declared in the `case` block of a `switch` share the same scope.

For example,

```Java
switch (command) {

case MarkCommand.COMMAND_WORD:
    int id = Integer.parseInt(rest) - 1;
    return new MarkCommand(taskList, id);

case UnmarkCommand.COMMAND_WORD:
    int id = Integer.parseInt(rest) - 1;
    return new UnmarkCommand(taskList, id);

}
```

if you try to compile and run this, there will be an error `Duplicate local variable id`.

![image](https://github.com/user-attachments/assets/7f4c37b7-c99a-4784-971e-0a51a6178450)

Currently, my workaround this issue is to introduce a closure by adding `{}` around the `case` block, like in the code snippet below. This is quite readable in my opinion as it does not really disrupt the original flow of code. I believe it is also compliant with checkstyle since `./gradlew checkstyleMain` does not give me any errors.

```Java
switch (command) {

case MarkCommand.COMMAND_WORD: {
    int id = Integer.parseInt(rest) - 1;
    return new MarkCommand(taskList, id);
}

case UnmarkCommand.COMMAND_WORD: {
    int id = Integer.parseInt(rest) - 1;
    return new UnmarkCommand(taskList, id);
}

}
```

Are there other ways to handle this issue? Is this method reasonable?

**Comment by zaidansani** [comment]
I think you can just reassign the variable? Either declare it outside the switch case, or declare it in the first case with the variable and then reassign it.

**Comment by weiseng18** [comment]
yep that works too, wondering if there are any conventions/common practices

**Comment by yadobler** [comment]
IIRC usually you declare the variable before the switch, but don't assign it. Then in each case statement you can assign the Id.

I see "Type x = y" as actually 2 different operations, a definition and assignment. So you can break it into 2 statements and then the common statement (ie the definition) will be brought out to before the switch. 

Personally I try to extract as much common statements out as possible, and make each case statement only what's specific to the case. 

```java
int id;

switch (command) {
case MarkCommand.COMMAND_WORD:
    id = Integer.parseInt(rest) - 1;
    return new MarkCommand(taskList, id);

case UnmarkCommand.COMMAND_WORD: 
    id = Integer.parseInt(rest) - 1;
    return new UnmarkCommand(taskList, id);
} 
```
(I'm assuming `id` will have different assignment in other cases? If not you can also just straight away assign it before the switch) 

But I like the brackets too, they help define the local scope. Reminds me of rust `match` blocks.

**Comment by emmannyyy** [comment]
I agree with @yadobler, I think it's best if you abstract out the variable `int id` before each `case`. 

However, if not all of the cases have an `int id`, then perhaps you current implementation where you add a closure may be better.
