### ISSUE TITLE
Cannot run code after merging gradle

### ISSUE THREAD

**Issue by ishan-agarwal-05** [nus-cs2103-AY2425S1/forum#278]
<img width="1512" alt="Screenshot 2024-09-13 at 6 14 26 PM" src="https://github.com/user-attachments/assets/f711b957-921e-472a-ab50-8a79b8c4e5c4">
when i run from gradle or rather anywhere, i get the message 

Error: Could not find or load main class seedu.duke.Duke

Caused by: java.lang.ClassNotFoundException: seedu.duke.Duke

Execution failed for task ':run'.
> Process 'command '/Users/ishan/.sdkman/candidates/java/17.0.11.fx-zulu/zulu-17.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

i think it is because 

application {
    mainClass.set("seedu.duke.Duke")
}

in build.gradle

but now i can't get it to work no matter what i do.

i am also unable to undo the commit

**Comment by ghos7ie** [comment]
Doesn't seem like your classes are put into a package so maybe try ```mainClass.set("JohnCena")``` in your build.gradle instead.

For my own bot, since my code are all in a ```lbot``` package, it is ```mainClass.set("lbot.Launcher")```.

**Comment by ishan-agarwal-05** [comment]
Yeah that worked 
Thanks
