### ISSUE TITLE
Gradle run suddenly throwing java.lang.IllegalArgumentException exception

### ISSUE THREAD

**Issue by nuagetsu** [nus-cs2103-AY2425S1/forum#279]
`./gradlew run ` suddenly stopped working, and doesn't work even when i revert to an older version of my code that worked in the past.
When I run `./gradlew run `, I get the following error:

```
> Task :run
Sep 14, 2024 12:00:40 AM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @3b8b3a05'
Exception in Application constructor
Exception in thread "main" java.lang.IllegalArgumentException: 0 > -4
        at java.base/java.util.Arrays.copyOfRange(Arrays.java:3782)
        at java.base/java.util.Arrays.copyOfRange(Arrays.java:3742)
        at jdk.compiler/com.sun.tools.javac.launcher.Main.execute(Main.java:431)
        at jdk.compiler/com.sun.tools.javac.launcher.Main.run(Main.java:192)
        at jdk.compiler/com.sun.tools.javac.launcher.Main.main(Main.java:132)

> Task :run FAILED

FAILURE: Build failed with an exception.
```

This is my output upon running java -version:

```
java version "17.0.12" 2024-07-16 LTS
Java(TM) SE Runtime Environment (build 17.0.12+8-LTS-286)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.12+8-LTS-286, mixed mode, sharing)
```

I have tried
- killing previously stopped/running Daemons
- Making sure my JDK versions are all 17
- Invalidating my cache and restarting
- making a clean build in gradle

but nothing has changed. Anyone ran into this issue and has a fix?

**Comment by damithc** [comment]
@EdaYeo You can also try cloning the fork to a new location and running it from there.

**Comment by nuagetsu** [comment]
It works after cloning the fork to a new location as you said. Thank you!
