### ISSUE TITLE
Does it SLAP to use monads to abstract programming constructs?

### ISSUE THREAD

**Issue by Virusrwj223** [nus-cs2103-AY2425S1/forum#282]
Hi everybody, we had learnt to abstract lines of code into a logical sequence of methods to achieve SLAP. I had noticed that my own code uses a lot of `if ( ) { } ... else { }` or `try { } catch ( ) { }` or the various loops. Will abstracting these constructs, say changing the conditional construct to `Conditional.of().ifBlock(<condition>, <method to execute>).elseBlock(<method to execute>)` be following SLAP? Also, is doing this good practice?

**Comment by Feng1231** [comment]
The briefing mentioned that the main reason for SLAP is to enhance readability and help maintainence of codebase easier, for you and for future developers.

I personally don't think changing the if else to conditional.of.ifblock.elseblock enhance readability. You might want to consult your teammates as well! Considering that you might write all your if else blocks in this format in your TP. 

Also, this is not abstraction right? You are still exposing the check conditions and the steps to execute in the params of the conditional

**Comment by yadobler** [comment]
Changing the if-else blocks to streams might not help if it's gonna be the same _multiple levels of abstraction_ for each conditions. 

Also i agree with @Feng1231, rewriting if-blocks to `Conditional.of()` is not abstraction. I'd argue you're making it even more messy. You're actually introducing **another** level of abstraction, by introducing a new `Conditional` class and running your existing code in them.
 
You might want to see i you can throw the inner blocks into separate methods, and call them in each `else` block. 

Try using switch if possible when there's too much `if`s.
