### ISSUE TITLE
Progress Tracker not being updated

### ISSUE THREAD

**Issue by nihalramesh** [nus-cs2103-AY2425S1/forum#283]
<img width="782" alt="Screenshot 2024-09-14 at 12 51 03 PM" src="https://github.com/user-attachments/assets/b5a4d1a8-3b68-43b7-b9e3-7af7cef6e48d">
<img width="1440" alt="Screenshot 2024-09-14 at 12 50 30 PM" src="https://github.com/user-attachments/assets/59088c29-efdb-454d-936d-749cd71d7b0e">

The Tags are present in my repo, so I'm not very sure on why some of the tags are not being detected.

**Comment by damithc** [comment]
@nihalramesh12629 At the top of the [iP progress dashboard](https://nus-cs2103-ay2425s1.github.io/dashboards/contents/ip-progress.html), there are a couple of tips about troubleshooting when an increment related to a tag or a branch is not green as expected. See if those help you locate the problem.

If the problem remains unresolved even after trying the above, let us know by replying here.
