### ISSUE TITLE
Completed `A-Assertions` and `A-CodeQuality` with wrong branch name

### ISSUE THREAD

**Issue by weiseng18** [nus-cs2103-AY2425S1/forum#284]
I've completed the features `A-Assertions` and `A-CodeQuality`, but unfortunately I have labelled their branches `A-Assertions` and `A-CodeQuality` instead of the required `branch-A-Assertions` and `branch-A-CodeQuality`. As such they correctly show up as red in my progress tracker.

![image](https://github.com/user-attachments/assets/97b11b9f-c89d-443d-83d2-e83ee3e82843)

Is there a recommended way to fix this issue? Should I unmerge the branches, rename, then merge them back?

**Comment by Domokunx** [comment]
![image](https://github.com/user-attachments/assets/45fbd4bb-aabe-462f-9715-4d5ad7923b5a)
If you click on "Branches" in your ip fork on GitHub, there should be an option to rename your branches

Though later you will have to set your local branch to track the new name I believe

**Comment by RezwanAhmed123** [comment]
There is a way to rename the branches without manually unmerging. Simply rename old assertions branch to something else first, rename the old code quality branch to assertions then the old assertions branch into code quality. You can explore it in [this](https://www.theserverside.com/blog/Coffee-Talk-Java-News-Stories-and-Opinions/rename-Git-branch-local-remote-GitHub-GitLab-BitBucket) page.

Make sure to follow from 

`Git branch rename command`

Onwards.

**Comment by weiseng18** [comment]
@Domokunx i'll give that a shot, will rename one branch first and wait for the next dashboard update

**Comment by weiseng18** [comment]
ok so that doesn't seem to fix my issue

hi prof @damithc, I can fix the issue by creating the two branches and merging them with small changes. Is that appropriate? Or will someone be reading through my iP code so that they will notice that I implemented the necessary features for these two branches?

**Comment by damithc** [comment]
> hi prof @damithc, I can fix the issue by creating the two branches and merging them with small changes. Is that appropriate? 

@weiseng18 Yes, that's fine too.

**Comment by weiseng18** [comment]
alright, thanks prof!
