### ISSUE TITLE
Will reusing a extension feature implemented in iP be given equal credit in tP?

### ISSUE THREAD

**Issue by yizhong187** [nus-cs2103-AY2425S1/forum#287]
For instance, I implement the C-BetterSearch extension in my iP, and then proceed to copy the code used in my iP for a component in tP, will the implementation in tP be given credit?

**Comment by damithc** [comment]
@yizhong187 Yes, it's fine if it is your own iP code. If it is someone else's iP code, you need to give credit to the original author.
