### ISSUE TITLE
Not sure how reverse commit works on Source Tree

### ISSUE THREAD

**Issue by jinnsuke** [nus-cs2103-AY2425S1/forum#29]
Hi! So basically I made a commit, right clicked on the commit and accidentally clicked "reverse commit". I expected the files that I committed to reappear back in staging but unfortunately they aren't there. I am a bit confused about what to do from here but essentially I just want to get back to my original state right before I clicked the reverse commit button. Appreciate any advice thanks!

![Screenshot 2024-08-22 at 4 39 15 PM](https://github.com/user-attachments/assets/3b0a9add-2e00-417c-8687-c46936bb961e)

**Comment by hanscau** [comment]
Hello, I'm pretty sure you can revert your revert. Just right click on the Revert commit and revert it again.

**Comment by yanhwee** [comment]
Right click on the the previous commit (the commit that you want to "rollback to") and click "Reset master to this commit", and then in the option select the SOFT option.

**Comment by rxchell** [comment]
1. You can right click the commit you reverted (with the commit details Revert "A-TextUiTesting & Removed Indentations") 
2. **Click on the same option "Reverse commit..."**. 
3. You will be able to get back to the original state right before you clicked the reverse commit button. 
4. The commit details should show: Revert "Revert "A-TextUiTesting & Removed Indentations""

Hope it helps!

**Comment by jinnsuke** [comment]
Thank you so much for your help everyone!

**Comment by damithc** [comment]
To summarize:
* 'Reverting the revert' is on option. This results in two extra commits though.
* Another way is to delete the revert commit (i.e., 'undo' the previous revert), by resetting the branch to the commit just before the 'revert' commit.
