### ISSUE TITLE
Failed tests while trying to merge pull request

### ISSUE THREAD

**Issue by rayray39** [nus-cs2103-AY2425S1/forum#290]
I am trying to merge my branch (branch-A-MoreErrorHandling) to the master branch by creating a pull request. For some reason the CI checks keep failing and this is because some of the JUnit tests failed. On intellij, I ran the same JUnit tests using gradle and they all passed. Is it a still good idea to create the pull request and merge it?

![fail CI checks](https://github.com/user-attachments/assets/64c91220-cf2d-418d-b382-5dad3ad4ba35)

**Comment by RezwanAhmed123** [comment]
I think this case is similar to issue #277 .

Your locale is probably not set up correctly leading to failures in checks.

Do also ensure that your checks properly set up and are cleaned up after each test as well (sometimes they leave fragments in your storage text files.

**Comment by RezwanAhmed123** [comment]
i just checked your repo and github actions, it seems its due to the locale of the date time not being set to a default value in your java test files

**Comment by rayray39** [comment]
@RezwanAhmed123 is it the same as issue #277 ? Because I have just made the changes but its still failing

**Comment by rayray39** [comment]
I managed to solve the issue by following issue #277, in addition i perfomed a `gradlew clean` and pushed a commit using `git commit --allow-empty -m "peform gradle clean"`. Thanks @RezwanAhmed123 for helping me out!
