### ISSUE TITLE
Sequence diagrams: Asynchronous call vs Parallel

### ISSUE THREAD

**Issue by vinceg4** [nus-cs2103-AY2425S1/forum#292]
This question might be out of the syllabus scope but I just want to know more about the difference between lined arrowheads vs par frames. 

In the textbook, it is stated that lined arrowheads are used for asynchronous calls. It is also stated under the advanced section that we can use par frames to describe parallel paths. May I know if there is a difference in using lined arrowheads vs par frames? Or to put in another way, are there scenarios where one would be more suitable than another? To me, both seems to be indicating some sort of parallelism in the program.

**Comment by damithc** [comment]
@vinceg4 Good area to dig into. You are wondering when to use threads and when to use async calls, right? In that case the question is not related to UML but about two implementation choices.

**Comment by damithc** [comment]
@vinceg4 Any updates? i.e., is the question about UML or about implementation choices?

**Comment by vinceg4** [comment]
@damithc sorry for the late update! it slipped my mind. I believe back when I was asking this question, I was confused about why there was different notations  parallel frames and asynchronous calls because to me parallelism = async calls (which does not seem to be the case?)

**Comment by damithc** [comment]
@vinceg4 They are not the same, although they are related. While they are not in the scope of this course, it is fine to discuss here. You can dig around a bit to find the difference between 'parallel execution vs asynchronous calls' and raise here if you have further questions.

**Comment by vinceg4** [comment]
@damithc Okay, thank you!
