### ISSUE TITLE
Where to submit the UI.png?

### ISSUE THREAD

**Issue by Brendan8899** [nus-cs2103-AY2425S1/forum#293]
The website states to submit to docs folder.

I would like to seek some clarification, where is that docs folder.

**Comment by Feng1231** [comment]
There is a docs folder in your ip repository.
![image](https://github.com/user-attachments/assets/684b7d4c-b78c-4e4a-bf01-8dd071d9a545)


It currently contains only a `README.md`, if you have not touched it yet.
Just:
- paste your `Ui.png` into that folder
- update the `docs/README.md`, and follow the instructions of `A-UserGuide`.
