### ISSUE TITLE
GFMD Tag in IP Dashboard not reflecting properly

### ISSUE THREAD

**Issue by Brendan8899** [nus-cs2103-AY2425S1/forum#294]
Dear Professor,

Sorry to disturb. I need your help to check why my GFMD Tag in IP Dashboard is red even though I added it 3 weeks ago.

![image](https://github.com/user-attachments/assets/802f0f62-a07c-4d4e-a92d-fba48801213c)

Thank you so much!

**Comment by Feng1231** [comment]
Seems like you are missing:
- fenced code block (with syntax highlighting) 
- inline code 
- block quote

which are requirements stated [here](https://nus-cs2103-ay2425s1.github.io/website/schedule/week4/project.html#1-use-gfmd-in-the-pr-description)

**Comment by damithc** [comment]
@Brendan8899 As mentioned by @Feng1231, some expected GFMD syntax are missing in your PR description.
