### ISSUE TITLE
Tagging lastest commit for features implemented in previous commits

### ISSUE THREAD

**Issue by NorbertLoh** [nus-cs2103-AY2425S1/forum#296]
Hi prof I saw another question asking about tagging old commits where streams were implemented. Is it ok to tag my latest commit with A-Streams if I implemented streams in a previous commit?
Thank you!

**Comment by damithc** [comment]
@NorbertLoh You can tag the latest commit or the commit that actually implemented the increment (the latter is preferred, but the dashboard accepts both). Remember to push the tag to the fork in both cases.

**Comment by NorbertLoh** [comment]
Ok thanks prof!
