### ISSUE TITLE
Clarification on iP final product requirement

### ISSUE THREAD

**Issue by FYL2003** [nus-cs2103-AY2425S1/forum#297]
Does anyone know what does "Ensure the correct product name appears everywhere in the UI" mean?

Is it like we need to change the fxml file to show it somewhere?

**Comment by damithc** [comment]
> Does anyone know what does "Ensure the correct product name appears everywhere in the UI" mean?

@FYL2003 Ensure that your GUI reflects the correct product name. A common oversight is to show `Duke` in the title bar of the GUI

![image](https://github.com/user-attachments/assets/83e68999-80f4-4d4f-8fe3-27415acfe41f)

**Comment by FYL2003** [comment]
<img width="400" alt="Screenshot 2024-09-16 at 9 00 22 PM" src="https://github.com/user-attachments/assets/5a7bf770-12d5-49f8-bf18-83243f379507">
I am not sure if this is the common issue for Mac users, but mine do not have the name stated at that place. I also checked for some available iP showcases and found out those who are using Mac do not have the label either.

**Comment by Jianwen0451** [comment]
To get the title bar do the following in your main class (the one include the build of stage and scene)

```java 
stage.setTitle("BotName");
```
This should add the bot name to the title bar.

**Comment by damithc** [comment]
> I am not sure if this is the common issue for Mac users  but mine do not have the name stated at that place. 

@FYL2003 probably it appears in the main menu bar (near the Apple logo at the top left corner of the screen)? It's due to differences in how Mac OS and Windows show application Windows. Mac has only one menu bar which is at the top of the screen and is assigned to the active window, while Windows gives each application its own menu bar.

**Comment by damithc** [comment]
@FYL2003 Looks like this one managed to show the product name in the window title bar while running on a Mac https://github.com/nus-cs2103-AY2425S1/forum/issues/301#issuecomment-2353488680

**Comment by FYL2003** [comment]
I tried the above method and it works.
