### ISSUE TITLE
iP tag and commit enquiries

### ISSUE THREAD

**Issue by ITLimJiaWei** [nus-cs2103-AY2425S1/forum#3]
It's stated "git tag the commit with the exact increment ID e.g., Level-2, A-TextUiTesting" in the CS2103/T site but I have 2 questions about this. 

1.) Is omitting the spaces alright as it seems Sourcetree doesn't allow for spaces in tag name? 
2.) When I try to assign 2 commits to a tag of similar name, Sourcetree seems to not permit this (prompts me to transfer the tag to the other commit). What if I have several commits which relate to the same incrementID/stage? E.g. Level-0.Rename,Greet,Exit -> Would Level-**0.1**.Rename,Greet,Exit suffice if there was a 2nd commit working on this same stage?

Thank you in advance for the help

**Comment by damithc** [comment]
> 1.) Is omitting the spaces alright as it seems Sourcetree doesn't allow for spaces in tag name?

@ITLimJiaWei `Level-2, A-TextUiTesting` is not one tag, but two examples for increment IDs. Each tag should be exactly one increment ID. e.g., `Level-2` or  `A-TextUiTesting`

> 2.) When I try to assign 2 commits to a tag of similar name, Sourcetree seems to not permit this (prompts me to transfer the tag to the other commit). What if I have several commits which relate to the same incrementID/stage? E.g. Level-0.Rename,Greet,Exit -> Would Level-**0.1**.Rename,Greet,Exit suffice if there was a 2nd commit working on this same stage?

The increment tag should be added to the commit that _completed_ the increment, not to _every_ commit that is related to that increment. So, there is no need to add the same tag to multiple tags. And you are right, it is not allowed by Git.

**Comment by ITLimJiaWei** [comment]
I see, thank you!

**Comment by damithc** [comment]
@ITLimJiaWei Thanks for raising this question. I've updated https://nus-cs2103-ay2425s1.github.io/website/schedule/week2/project.html to make this point clearer.
