### ISSUE TITLE
Does inline identation matter for Output in the chatbot?

### ISSUE THREAD

**Issue by Brendan8899** [nus-cs2103-AY2425S1/forum#30]
Hey Prof and Coursemates,

This is my interaction with my own code:

todo borrow book
____________________________________________________________ 
Got it. I've added this task: 
[T][ ] borrow book
Now you have 1 tasks in the list.
____________________________________________________________ 

This is the interaction stated in the CS2103 Website:
todo borrow book
    ____________________________________________________________
     Got it. I've added this task:
       [T][ ] borrow book
     Now you have 5 tasks in the list.
    ____________________________________________________________

Looking at the expected output, I see that each line has some indentation. However, in Level-1 it states:
The indentations are optional. 

Can I seek your clarification?

**Comment by damithc** [comment]
@Brendan8899 Indentations are optional, even in later increments.
Side note: You can use [fenced code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) to format your post for better readability.

**Comment by Brendan8899** [comment]
Thank you Prof
