### ISSUE TITLE
Looking for helpful friends to help to test my .jar file

### ISSUE THREAD

**Issue by Chronoxy** [nus-cs2103-AY2425S1/forum#301]
Hi friends,

I'm looking for anyone who is available and would like to help me test my .jar file.
If possible, both Windows and Mac machines.

Follow the steps below:
1. Download `patrick.jar` [here](https://github.com/Chronoxy/ip/releases/download/A-Release/patrick.jar)
2. Locate the file on your operating system and double-click to open it.
3. A Java program will run, welcoming you to use the application
4. Use commands like:
    `list`: Lists all added tasks
    `todo work`: Adds a new todo task with the description "work"

For all other features, refer to my [user guide](https://chronoxy.github.io/ip/).
I would appreciate if you could leave a comment to let me know how it goes

Thank you so much in advance friends 😄

**Comment by zyng233** [comment]
It looks good in my OS(window), but just that the program does not handle non-positive value like if I type 
`mark 0`, it caused a java.lang.IndexOutOfBoundsException in the terminal but it was not reflected in the chatbot.

![Screenshot 2024-09-17 003711](https://github.com/user-attachments/assets/628eaf4e-8c3f-41a0-9177-f7c980b2390b)

**Comment by Chronoxy** [comment]
> It looks good in my OS(window), but just that the program does not handle non-positive value like if I type `mark 0`, it caused a java.lang.IndexOutOfBoundsException in the terminal but it was not reflected in the chatbot.
> 
> ![Screenshot 2024-09-17 003711](https://private-user-images.githubusercontent.com/122551083/367844462-628eaf4e-8c3f-41a0-9177-f7c980b2390b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1MDU4OTQsIm5iZiI6MTcyNjUwNTU5NCwicGF0aCI6Ii8xMjI1NTEwODMvMzY3ODQ0NDYyLTYyOGVhZjRlLThjM2YtNDFhMC05MTc3LWY3Yzk4MGIyMzkwYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNlQxNjUzMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYTlmMzFjOGYzMzA5NDMyY2RlMjVjZGU0NGUyNDRjNTI0NzE4NzlkOGVlYzA1ZWQ4OGQxYzM0MGU5MzZmMTlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GyaRB67pAN0tErMMMxV13qm_tQ5vJtNOitU40yPYorw)

Hi @zyng233, thank you so much for your help. I'll perform a fix immediately 🙇‍♂️ 🙏 

Edit: fixed

**Comment by yizhong187** [comment]
![tg_image_3241759836](https://github.com/user-attachments/assets/97583d4f-5002-4fe4-8838-09cef552982c)
![tg_image_1741435248](https://github.com/user-attachments/assets/48f5c5a0-8a56-4471-a83a-603777cf7162)

Unfortunate, on MacOS, it's not possible to run the .jar file by just click on it :(

For anyone trying to run it, navigate to the folder where you downloaded the .jar file and run the application using the following command:

```bash
java -jar patrick.jar
```

**Comment by yizhong187** [comment]
<img width="429" alt="image" src="https://github.com/user-attachments/assets/8378d68f-5ebc-47dd-9490-03409851a944">

I tried running some of the example codes in your user guide, but _Patrick The Star_ kept telling me the format is wrong :(

**Comment by linette-g** [comment]
Looks good on my OS (macOS), just that the chatbot doesn't handle cases where the task description is empty for deadline or event tasks. Example input: `deadline /by Sep 20 2024 2359`

<img width="839" alt="Screenshot 2024-09-17 at 9 40 43 AM" src="https://github.com/user-attachments/assets/624182aa-b9fd-40a0-ad7a-c31695d57ea6">

**Comment by weiliann** [comment]
UI looks nice but the app crashes when I rerun it after adding a todo.

Steps to reproduce:
1. add a new todo with `todo ip`
2. exit the app with `bye`
3. reboot the app

edit:
OS: windows

Error:
![image](https://github.com/user-attachments/assets/629fe98e-3c14-4530-875a-49966d6eb226)

**Comment by jasmiinee** [comment]
![Screenshot 2024-09-17 142501](https://github.com/user-attachments/assets/30a91235-e15c-4de5-b857-ecb59229a123)
Everything looks good to me! (Windows user) Only issue I found was being able to add an event where the start time is after the end time.

**Comment by Chronoxy** [comment]
> <img alt="image" width="429" src="https://private-user-images.githubusercontent.com/109573190/367856928-8378d68f-5ebc-47dd-9490-03409851a944.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NTQ4MjYsIm5iZiI6MTcyNjU1NDUyNiwicGF0aCI6Ii8xMDk1NzMxOTAvMzY3ODU2OTI4LTgzNzhkNjhmLTVlYmMtNDdkZC05NDkwLTAzNDA5ODUxYTk0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxN1QwNjI4NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMWQ3NzVhMWYyNGYyYmQ0ZTM5YmVhYTU3YzFiNmI1OWJhN2MyMjdmYzg2MWY3YjVmYTgwOTM3ZDNlZjNlMDkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.A4VoS82L-nSps_O8ynw9GzPI6XX34NZgDtHjcd8_S9o">
> I tried running some of the example codes in your user guide, but _Patrick The Star_ kept telling me the format is wrong :(

hi @yizhong187,

Thanks for your help on testing my product. However, I tried on my end it seems to work as intended. Could I trouble any other mac users to test on this issue? Thanks
![Patrick The Star](https://github.com/user-attachments/assets/5e8c28b9-f6d6-4cec-a370-a71211bb1e68)

**Comment by Chronoxy** [comment]
> Looks good on my OS (macOS), just that the chatbot doesn't handle cases where the task description is empty for deadline or event tasks. Example input: `deadline /by Sep 20 2024 2359`
> 
> <img alt="Screenshot 2024-09-17 at 9 40 43 AM" width="839" src="https://private-user-images.githubusercontent.com/156193856/367976975-624182aa-b9fd-40a0-ad7a-c31695d57ea6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NTQ4MjYsIm5iZiI6MTcyNjU1NDUyNiwicGF0aCI6Ii8xNTYxOTM4NTYvMzY3OTc2OTc1LTYyNDE4MmFhLWI5ZmQtNDBhMC1hZDdhLWMzMTY5NWQ1N2VhNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxN1QwNjI4NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MThiZTE4YWI2M2E1N2JkYjhiM2ZhMTc2NjYyMDgxZTRlY2FjMDE1NGE4NDQ1YzMyMmM0NzZiN2MxYmE4ZDI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YSejfCnbI7g6rNsTh7q796HhbM885cqLW0GGNu0uQyU">

Hi @linette-g, thanks for helping to test my product. I have thus fixed the issue in the latest release. 🙏

**Comment by Chronoxy** [comment]
> UI looks nice but the app crashes when I rerun it after adding a todo.
> 
> Steps to reproduce:
> 
> 1. add a new todo with `todo ip`
> 2. exit the app with `bye`
> 3. reboot the app
> 
> edit: OS: windows
> 
> Error: ![image](https://private-user-images.githubusercontent.com/137792973/367985254-629fe98e-3c14-4530-875a-49966d6eb226.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NTQ4MjYsIm5iZiI6MTcyNjU1NDUyNiwicGF0aCI6Ii8xMzc3OTI5NzMvMzY3OTg1MjU0LTYyOWZlOThlLTNjMTQtNDUzMC04NzVhLTQ5OTY2ZDZlYjIyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxN1QwNjI4NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MGFkYzc0ZTM0ODE0ZWE5OWVjNTc4ZDUyNTkzOWFkOTE2OTgwMTc1MDAzMTFhMGFlOGUwMzI1ZDE5MzhkYTQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CUeKei4pp6Hbr7X9OBVEf2FmQ51HsWuoo6ec6Uat6TQ)

Hi @weiliann, thank you for testing my product. I have therefore fixed the issue in my latest release. 🙏 🙇‍♂️
