### ISSUE TITLE
How to create stubs for testing

### ISSUE THREAD

**Issue by NgZiXin** [nus-cs2103-AY2425S1/forum#303]
According to the notes, a stub have is supposed to implement the interface of the class which it is replacing.

<img width="565" alt="image" src="https://github.com/user-attachments/assets/ae404c06-ebf1-42b1-80ad-182a4a6bf8b7">

I have a function in my `Command` class that has the following function prototype `Response execute(TaskList tasks, Ui ui, Storage storage)` which I want to perform J-Unit test on to ensure it returns the right Response.

My understanding is that I am supposed to create a stub for `TaskList`, `Ui`, and `Storage`. However, none of these classes implements any interface. Nonetheless, within these classes, it still needs to have all the public methods found in their class right (regardless if it will be used or not). These methods will be a simple implementation such as returning null. 

May I check if my understanding for the J-Unit testing with stubs correct? Else, how would you test the function as stated above? Thank you!

**Comment by yadobler** [comment]
You can `extend` them and override all the functions to not do anything / do any side effects except what you need. 

Make the stub class inside the jUnit class as an inner class.
