### ISSUE TITLE
Looking for helpful classmates to help test my .jar file

### ISSUE THREAD

**Issue by emmannyyy** [nus-cs2103-AY2425S1/forum#306]
Hi everyone,
I'm looking for anyone who can help me test my jar file, especially on Mac. 

Please follow these steps:
1. Download Monique.jar from [here](https://github.com/emmannyyy/ip/releases/download/v0.2/Monique.jar)
2. Locate the file in your OS and double click it to open. If double clicking does not work, open a command terminal and navigate to where the .jar file is located and type ```java -jar Monique.jar```
3.  Test commands. You can find more details about the commands [here in my user guide.](https://emmannyyy.github.io/ip/)

For a series of dummy test commands, I've included them below:
<details>
    <summary> expand test cases </summary>

deadline submit project /by 25/12/2024 1400

deadline finish essay /by tomorrow 3:00pm

deadline buy groceries /by monday 10:30am

deadline prepare presentation /by 01-01-2025

deadline send email /by 12-12-2024 5:00pm

deadline finalize proposal /by 31/12/2024

deadline clean house /by fri 11:59pm

deadline book flight /by 15/11/2024 1230

deadline submit assignment /by sun 4pm

deadline pay bills /by 20-11-2024 1800

event conference /from 12/12/2024 0900 /to 15/12/2024 1700

event dinner with friends /from tomorrow 7:00pm /to tomorrow 10:00pm

event yoga class /from monday 6:30am /to monday 8:00am

event wedding /from 01/01/2025 1400 /to 01/01/2025 1800

event coding workshop /from fri 9am /to fri 5pm

event vacation /from 05/01/2025 1200 /to 10/01/2025 2200

event company meeting /from 12-12-2024 10:00am /to 12-12-2024 11:30am

event gaming session /from saturday 3pm /to saturday 6pm

event road trip /from tomorrow 5:00am /to tomorrow 9:00pm

event music concert /from 20/12/2024 1800 /to 20/12/2024 2300

todo buy groceries

todo read a book

todo clean the house

todo finish homework

todo write report

todo walk the dog

todo exercise

todo call mom

todo attend meeting

todo schedule appointment

find homework

find meeting

find project proposal

find groceries

find yoga class

mark 0

mark 2

mark 3

unmark 0

unmark 4

unmark 3

delete 4

delete 5

delete 6

delete 10000
</details>

Please let me know how it works, and if you find any bugs! 
Thank you in advance :)

**Comment by damithc** [comment]
@emmannyyy Others can help with a _smoke test_ (i.e., just to check if the application runs on their computer and basic functions work) but extensive testing needs to be done by the iP owner.

**Comment by emmannyyy** [comment]
oh ok, thanks Prof @damithc , I've already tested it locally, just hoping all features work for other users too. Shall I remove the sample test cases?

**Comment by damithc** [comment]
> Shall I remove the sample test cases?

@emmannyyy It's fine to keep them. Testers can use them if they want.

**Comment by OttoTan** [comment]
@emmannyyy Looks good on my environment (Windows)  👍

However, I found a minor bug. When unmarking a task, it is still displayed as marked in the reply. The command probably stores the task before unmarking it rather than after.

![image](https://github.com/user-attachments/assets/2daac161-2c7a-4a92-b6e5-6a221f319d6b)

**Comment by emmannyyy** [comment]
oh wow! Thanks @OttoTan I'll go fix it right away!

**Comment by tata32000** [comment]
@emmannyyy Looks good on my environment (MacOS)

<img width="529" alt="Screenshot 2024-09-17 at 13 41 19" src="https://github.com/user-attachments/assets/37b9137b-8468-4908-a2f2-8309d6930875">
