### ISSUE TITLE
Codecov integration problem: No Test Data for coverage despite successful report uploading

### ISSUE THREAD

**Issue by starchypotatocode** [nus-cs2103-AY2425S1/forum#308]
After following all the steps in the given tutorials (including adding the correct secret into the repository), and making minor edits and committing, there still isn't any data after more than 24h since committing.

I saw some part of the code mentioned something about Linux, so could incorrect OS be the issue there, or is it something else?

So this is the current status of the codecov: Has the integration been done properly? Thanks.
![image](https://github.com/user-attachments/assets/48c791aa-6421-4356-bf87-1bc845fb1e0b)

**Comment by damithc** [comment]
> Has the integration been done properly?

@starchypotatocode Based on the screenshot, looks like it's working fine.
