### ISSUE TITLE
Clarification for "major bugs" in ip requirement

### ISSUE THREAD

**Issue by FYL2003** [nus-cs2103-AY2425S1/forum#309]
Hi, I just followed the minimal requirement for exception handling(the two kind of error stated in level5). May I know if some other input is not considered and cause exception, will it be treated as major bugs? Thanks!

**Comment by damithc** [comment]
@FYL2003 Any common errors need to be handled, either using exceptions or some other means. For example, the application should not crash if the user command has a typo.

**Comment by FYL2003** [comment]
For example if key in `mark 1abcd` as input and send to the bot, exception is not handled but the bot will not crash either, will it be considered as major bug?(If I remove abcd and the back and resend `mark 1`, the bot will run as normal.)

**Comment by damithc** [comment]
> For example if key in `mark 1abcd` as input and send to the bot, exception is not handled but the bot will not crash either, will it be considered as major bug?(If I remove abcd and the back and resend `mark 1`, the bot will run as normal.)

I see. I recommend informing the user of the problem rather than do nothing.

**Comment by FYL2003** [comment]
Does it mean that I have to state it in the user guide?

**Comment by damithc** [comment]
> Does it mean that I have to state it in the user guide?

I meant, the application should give some feedback to the user if an operation failed, rather than fail silently.

**Comment by FYL2003** [comment]
Noted!
