### ISSUE TITLE
Error reading filename

### ISSUE THREAD

**Issue by keithxun** [nus-cs2103-AY2425S1/forum#31]
PS C:\CS2103T> cmd /c "c:\CS2103T\ip\text-ui-test\runtest.bat"
error: Invalid filename: ..\src\main\java\*.java
Usage: javac <options> <source files>
use --help for a list of possible options
********** BUILD FAILURE **********

Hi all, I am getting an error in the runtest.bat test file. It is unmodified but I am unable to get it to run.

Appreciate any debugging tips

**Comment by Incogdino** [comment]
I think you forgot a \

Could you try this: ..\src\main\java\*.java

**Comment by TY1Fan** [comment]
Hi, have you changed the file name Duke to your new file name in runtest.bat?

Specifically this line:
java -classpath ../bin Duke < input.txt > ACTUAL.TXT
to
java -classpath ../bin "Bot-name" < input.txt > ACTUAL.TXT

**Comment by keithxun** [comment]
> Hi, have you changed the file name Duke to your new file name in runtest.bat?
> 
> Specifically this line: java -classpath ../bin Duke < input.txt > ACTUAL.TXT to java -classpath ../bin "Bot-name" < input.txt > ACTUAL.TXT

Yep, did this already

**Comment by keithxun** [comment]
> I think you forgot a \
> 
> Could you edit runtest.bat to this: ..\src\main\java*.java

I tried this and does not seem to work. Also, I am not sure how does removing the backslash help though

**Comment by keithxun** [comment]
Resolved: CD to test directory before running
