### ISSUE TITLE
GitHub CI/CD failing but tests work locally

### ISSUE THREAD

**Issue by wrjgold** [nus-cs2103-AY2425S1/forum#310]
![image](https://github.com/user-attachments/assets/72c3d474-fd50-43fd-92da-72ff07ca86b9)
![image](https://github.com/user-attachments/assets/c089cde4-9beb-45c5-81c0-053d31b99107)

My github actions seem to be failing after adding a new JUnit test. However running the same `./gradlew check` and `./gradlew checkstyleMain checkstyleTest` locally gives no errors. Does anyone have any ideea how to resolve this?

The github action log: https://github.com/wrjgold/ip/actions/runs/10903838088

**Comment by Incogdino** [comment]
For the first screenshot I think your tests are failing that is why the build is not working. Try running `./gradlew build` locally first or `./gradlew clean test` to see if the test cases pass

**Comment by damithc** [comment]
@wrjgold You can provide a link to the CI page (the one with the error message) so that others can go there and have a look around.

**Comment by wrjgold** [comment]
> For the first screenshot I think your tests are failing that is why the build is not working. Try running `./gradlew build` locally first or `./gradlew clean test` to see if the test cases pass

Thank you for your suggestion, however I tried running both commands and all my tests still pass locally. I have included my github action log in the post if it helps to provide a clearer picture.

**Comment by Incogdino** [comment]
Is the current master branch your latest code? I tried cloning it and running `gradlew clean build` which resulted in failing test cases.

![image](https://github.com/user-attachments/assets/c90edc97-3203-4197-bbce-c2b279ddd886)

**Comment by Incogdino** [comment]
After further testing, the reason why the test case failed on Github Actions is due to the filePath specified in your test method.

```java
    public void executeDelete_correctInput() {
        TaskList taskList = new TaskList(new ToDo("test"));
        DeleteCommand deleteCommand = new DeleteCommand(0);
        try {
            deleteCommand.execute(taskList, new Ui(), new Storage("data/test.txt"));
        } catch (TickException e) {
            fail("Exception thrown when it should not have been thrown.");
        }
        assertEquals(0, taskList.getSize());
    }
}
```
The build failing previously occurred when I have yet to run the application before calling `gradlew clean build`. After calling `gradlew run`, the file in directory `data/test.txt` gets created and `gradlew build` works properly, passing the test cases.

I reckon Github Action runs a similar procedure internally when building your application. Since the file path `data/test.txt` does not exist on building, the test case is bound to fail and thus the build.

**Comment by wrjgold** [comment]
> After further testing, the reason why the test case failed on Github Actions is due to the filePath specified in your test method.
> 
> ```java
>     public void executeDelete_correctInput() {
>         TaskList taskList = new TaskList(new ToDo("test"));
>         DeleteCommand deleteCommand = new DeleteCommand(0);
>         try {
>             deleteCommand.execute(taskList, new Ui(), new Storage("data/test.txt"));
>         } catch (TickException e) {
>             fail("Exception thrown when it should not have been thrown.");
>         }
>         assertEquals(0, taskList.getSize());
>     }
> }
> ```
> 
> The build failing previously occurred when I have yet to run the application before calling `gradlew clean build`. After calling `gradlew run`, the file in directory `data/test.txt` gets created and `gradlew build` works properly, passing the test cases.
> 
> I reckon Github Action runs a similar procedure internally when building your application. Since the file path `data/test.txt` does not exist on building, the test case is bound to fail and thus the build.

I see thank you for your help, I'll make the necessary ammendmants to my test case then
