### ISSUE TITLE
Requesting help for JAR testing

### ISSUE THREAD

**Issue by rayray39** [nus-cs2103-AY2425S1/forum#313]
Hi, you may find the jar file to my chatbot [here](https://github.com/rayray39/ip/releases/download/A-Release/janet.jar) and the user guide [here](https://rayray39.github.io/ip/). I am personally using a windows, and havent tried on macos before.

Thanks to those, on windows and macs, helping me to test my chatbot! If anybody needs help I would love to help too!

**Comment by tata32000** [comment]
Hi @rayray39, I have tested and it looks good on MacOS.

![Screenshot 2024-09-17 at 23 29 35](https://github.com/user-attachments/assets/ce936526-75b5-46a4-9344-8968a5bca070)

**Comment by rayray39** [comment]
cheers! @tata32000

**Comment by damithc** [comment]
![image](https://github.com/user-attachments/assets/7e92a8f0-28e8-4663-b7cf-9ff4b5dfd777)

Hmm... so if the deadline is over the app refuses to record it? Isn't this the type of thing (i.e., overdue tasks) the user might desperately want to keep track of?

**Comment by ZShunRen** [comment]
Hi @rayray39, just had a few suggestions, but take note that this is just my opinion.
1.  It works great on windows, but perhaps you might want to create a subfolder named `data`and then place the `janet.txt` inside it. i.e. `data/janet.txt` is the path of the saved tasks file.
2.  Perhaps you can add the functionality of the chatbot exiting if the user types in the `bye` command.  You can try this by adding an exit animation. This is an excerpt from my code that tries to do it (although it can be cleaner) :
```java
    private void exitApplicationWithDelay(double seconds) {
        PauseTransition delayAnimation = new PauseTransition(Duration.seconds(seconds));
        delayAnimation.setOnFinished(event -> Platform.exit());
        delayAnimation.play();
    }
    private void handleUserInput() {
    ...
      if (response.equals("EXIT MESSAGE")) {
              dialogContainer.getChildren().addAll(
                      encloseUserInput(input),
                      encloseNedInput(ned.getByeMessage(), false));
              exitApplicationWithDelay(2);
              return;
          }
   }
```

Overall, good job!

**Comment by rayray39** [comment]
> ![image](https://private-user-images.githubusercontent.com/1673303/368233907-7e92a8f0-28e8-4663-b7cf-9ff4b5dfd777.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NDA0MzMsIm5iZiI6MTcyNjY0MDEzMywicGF0aCI6Ii8xNjczMzAzLzM2ODIzMzkwNy03ZTkyYThmMC0yOGU4LTQ2NjMtYjdjZi05ZmY0YjVkZmQ3NzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MThUMDYxNTMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTIwMWI0ZGUxZTZiZDJhZDMwMmY2NWY0NWM4Y2Q1NDhkYTllMzk0NDc5NWJiYTEwMTQ4NDk5ODI4OTgyOTJjNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BHyWRUT_nDxjAZmcSAh1hqqw5OdrENN1orXK8Ewfz-o)
> 
> Hmm... so if the deadline is over the app refuses to record it? Isn't this the type of thing (i.e., overdue tasks) the user might desperately want to keep track of?

Hi prof @damithc , thanks for the feedback. But why would the user want to keep track of things that is already over? Wouldnt it make more sense for the user to only keep track of deadlines that are in the future? (eg. upcoming assignments, approaching meetings etc.)? I would love to have more opinions on this before i start to edit some of my code :)

**Comment by damithc** [comment]
> Hi prof @damithc , thanks for the feedback. But why would the user want to keep track of things that is already over? Wouldnt it make more sense for the user to only keep track of deadlines that are in the future? (eg. upcoming assignments, approaching meetings etc.)? I would love to have more opinions on this before i start to edit some of my code :)

@rayray39 Take any calendar software e.g., Google Calendar. They allow scheduling an event in the past. Why? Because people might still want to keep track of things they've done already but didn't have time to record yet. Similarly, for past deadlines. For example, if I was away from work due to illness and come back after a while, I still want to keep track of all the deadlines I missed so that I can catch up.

**Comment by YINZE66** [comment]
Hi @rayray39, I'm using mac and it works fine!
<img width="410" alt="image" src="https://github.com/user-attachments/assets/d525cc5f-a60e-4c6d-b503-978da00374c7">

**Comment by FYL2003** [comment]
Hi, I have test your bot and most of the features works well!
However, I find out that the following things that may be an issue:

1. event tst /abc /from 2025-12-21 18:12 /to 2026-12-12 12:12 /dto 2027-11-04 05:14

This one ignore "/dto ....." which should not be a big issue

2. The bot never terminate after enters bye command

This one is a major issue to me as the program have no way to terminate by it self(Or this is the design of the chatbot?)
