### ISSUE TITLE
Requesting for smoke test on JAR file

### ISSUE THREAD

**Issue by FYL2003** [nus-cs2103-AY2425S1/forum#314]
Hi guys, my release is [here](https://github.com/FYL2003/ip/releases/tag/v0.2), and my user guide is [here](https://github.com/FYL2003/ip/tree/master/docs). I am using MacOS and have not run my program on Windows before.

I will appreciate it if you can test my chatbot and report the bugs. I will also try to help test yours too!

**Comment by josh1248** [comment]
Tested on mac.

2 main bugs:
Commands that start with a trailing space arent handled as errors (Currently, error message only works if first character is a letter)

I think the text storage mechanism to make storage persistent may not be working as well.

Please do come and try my release [here](https://github.com/josh1248/ip/releases/tag/BCD-Extension]) . It has default commands (no user guide yet 😅)

**Comment by yongqqqq** [comment]
Hello, i did some simple testing and here are my comments!

Overall, the features all seem to work fine without any issues! However, here are some things that you may want to look into further! I have attached screenshots so that you may reproduce the steps I have taken. Hope this helps!

Pressing the send button creates empty chatboxes. May not be intended?

For event:
Keying in the wrong event format command produces the error "You are manipulating position out of bounds" which may not be an accurate error statement to display to users.

![event](https://github.com/user-attachments/assets/f8f40de5-26e3-49e3-af8d-5ba1ac57a99b)

For deadline:
Similar to invalid event format command, the same error message is produced which may not be intended.

![deadline bot](https://github.com/user-attachments/assets/531b6536-aaeb-4a17-ba17-31f6b2b83b04)

Your user guide might have an slight typo: `deadlind `instead of `deadline`

![deadline](https://github.com/user-attachments/assets/4b88831e-b1f7-4701-9c15-038e1e536c8e)

Data storage:
Modifying the .txt file leads to the application not launching. Can possibly look into that if you have the time. (i.e. skip lines or produce error) See entry number 7, where the description is removed.

![data](https://github.com/user-attachments/assets/1aa45b5e-f8d9-4c80-8a1a-77d6bc4eddba)

**Comment by FYL2003** [comment]
> Tested on mac.
> 
> 2 main bugs: Commands that start with a trailing space arent handled as errors (Currently, error message only works if first character is a letter)
> 
> I think the text storage mechanism to make storage persistent may not be working as well.
> 
> Please do come and try my release [here](https://github.com/josh1248/ip/releases/tag/BCD-Extension%5D) . It has default commands (no user guide yet 😅)

Thanks for your reply! I will try to check your release tomorrow and get back to you.

**Comment by FYL2003** [comment]
> Hello, i did some simple testing and here are my comments!
> 
> Overall, the features all seem to work fine without any issues! However, here are some things that you may want to look into further! I have attached screenshots so that you may reproduce the steps I have taken. Hope this helps!
> 
> Pressing the send button creates empty chatboxes. May not be intended?
> 
> For event: Keying in the wrong event format command produces the error "You are manipulating position out of bounds" which may not be an accurate error statement to display to users.
> 
> ![event](https://private-user-images.githubusercontent.com/57471791/368263487-f8f40de5-26e3-49e3-af8d-5ba1ac57a99b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1OTM4MTksIm5iZiI6MTcyNjU5MzUxOSwicGF0aCI6Ii81NzQ3MTc5MS8zNjgyNjM0ODctZjhmNDBkZTUtMjZlMy00OWUzLWFmOGQtNWJhMWFjNTdhOTliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDE3MTgzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjNThlZDU5MjVjMGM5ZTg1NTZjOTVlY2M3NzlmMjExYzI5MGQ0NmFkNDA5OWYxNjViMDQxMTQxZTVjN2Q0NTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dgMQJSyrPSMXVe1TIve-3KvlvsWjMH4MSZbxxil8rEg)
> 
> For deadline: Similar to invalid event format command, the same error message is produced which may not be intended.
> 
> ![deadline bot](https://private-user-images.githubusercontent.com/57471791/368263933-531b6536-aaeb-4a17-ba17-31f6b2b83b04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1OTM4MTksIm5iZiI6MTcyNjU5MzUxOSwicGF0aCI6Ii81NzQ3MTc5MS8zNjgyNjM5MzMtNTMxYjY1MzYtYWFlYi00YTE3LWJhMTctMzFmNmIyYjgzYjA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDE3MTgzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjNDQzNzA3YmZjZTkwYmEyZDAxM2VlNDZhNzU3MDJiZGFmNTA5NzI5YjgyMGNiZTVmM2Q1OGUyODQ3OGJmY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T_34qNvcyDg0JtMDYyrrCK5Vms21jmcpBrgx9RxmrbY)
> 
> Your user guide might have an slight typo: `deadlind `instead of `deadline`
> 
> ![deadline](https://private-user-images.githubusercontent.com/57471791/368264184-4b88831e-b1f7-4701-9c15-038e1e536c8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1OTM4MTksIm5iZiI6MTcyNjU5MzUxOSwicGF0aCI6Ii81NzQ3MTc5MS8zNjgyNjQxODQtNGI4ODgzMWUtYjFmNy00NzAxLTljMTUtMDM4ZTFlNTM2YzhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDE3MTgzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhZTE2YjdhNzllMjA4NjdlYTRiNDhkMDcxNzMwNTY2MDRlYmEzNWNlOThmMzJjZGVjYzgyMjA0OWUwM2MxOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MwvDdZgF-cKUCehz6dFjiPDO03DZgt6GRwjwlPaBXdU)
> 
> Data storage: Modifying the .txt file leads to the application not launching. Can possibly look into that if you have the time. (i.e. skip lines or produce error) See entry number 7, where the description is removed.
> 
> ![data](https://private-user-images.githubusercontent.com/57471791/368264498-1aa45b5e-f8d9-4c80-8a1a-77d6bc4eddba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1OTM4MTksIm5iZiI6MTcyNjU5MzUxOSwicGF0aCI6Ii81NzQ3MTc5MS8zNjgyNjQ0OTgtMWFhNDViNWUtZjhkOS00YzgwLThhMWEtNzdkNmJjNGVkZGJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDE3MTgzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkMzg4ZDU3Mzg4NjcwMjc0MDQxMzE3OWIzOWI0ZmViMWFjYThiMjJhMmVlNjJjN2Y4ZmZkOTFiOTM1ZDRlOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VB6vJsC6zsYImlC8-EfFB6Olu159pfVhgzkVtzhjPV8)

For the empty chatbox, I purposely return an empty chatbot for that situation. I am not sure if this is considered as an implementation flaw or I can leave it as it is? And for the data storage, I did not implement the stretched goal for checking corrupted database.
For the array out of bounds error message, I am pretty sure it is because of the argument length problem.(No check for argument length)

Thanks for checking!!

**Comment by FYL2003** [comment]
> Tested on mac.
> 
> 2 main bugs: Commands that start with a trailing space arent handled as errors (Currently, error message only works if first character is a letter)
> 
> I think the text storage mechanism to make storage persistent may not be working as well.
> 
> Please do come and try my release [here](https://github.com/josh1248/ip/releases/tag/BCD-Extension%5D) . It has default commands (no user guide yet 😅)

Hi, just to confirm, for the storage issue, do you mean by storage corruption?

**Comment by josh1248** [comment]
Yep, i cant make my storage persist between sessions, always have to start from scratch

**Comment by FYL2003** [comment]
> Yep, i cant make my storage persist between sessions, always have to start from scratch

For this issue, this is because I followed the minimal requirement. But thanks for clarification!!!

**Comment by FYL2003** [comment]
@josh1248 I tried to download your W5 release from your forked ip repo, but it seems that there are some issue and the screen shot look like this:
<img width="436" alt="Screenshot 2024-09-18 at 9 13 05 PM" src="https://github.com/user-attachments/assets/86321820-c61d-4aa4-a437-db7ff2fd4e6a">

**Comment by wes-w-z-h** [comment]
lgtm 👍 
I didn't face any of the issues mentioned above, looks like it's been fixed and the storage works as expected!
One tip is to include any fixes above so that later testers can tell what has been fixed.

**Comment by FYL2003** [comment]
Update: storage will save after each change, the exception will provide the user with more information about what is wrong with their input.
