### ISSUE TITLE
Emojis for output

### ISSUE THREAD

**Issue by TechRaj** [nus-cs2103-AY2425S1/forum#315]
Hi, I decided to use emojis for my bot output to add some user friendliness and ease of reading. It looked fine on my Mac. However, when my windows friend tried my jar file, some of the emojis were not supported. Is there a way to work around this issue? Or will it matter in the scope of the IP grading?

Just need some clarity/guidance. Thanks!

**Comment by damithc** [comment]
@TechRaj Can you share some screenshots too?

**Comment by Incogdino** [comment]
I don't think there is a way to maintain consistent emoji outputs across different OS or browsers.

You can instead try having a set of svg images/ image emojis instead to maintain consistency.

**Comment by TechRaj** [comment]
<img width="422" alt="ui" src="https://github.com/user-attachments/assets/c7ebf4ce-9412-4987-a7d9-1388c6fea00e">
![photo_2024-09-18 20 07 31](https://github.com/user-attachments/assets/8f9d88ff-5d8b-4618-9ba7-1b67fe204534)

How it looks on Mac vs how it looks on windows

**Comment by TechRaj** [comment]
![UI on Mac](https://github.com/user-attachments/assets/e8327acf-ad9f-45c5-ad24-c7f212c09601)
![UI on Windows](https://github.com/user-attachments/assets/45683ee3-9fed-4477-947f-3dfee8239886)


How it looks on Mac vs how it looks on Windows

**Comment by TechRaj** [comment]
@damithc prof I decided to add an if else, stating that if the os is Mac, use emojis. else, use text based. Is that ok?

**Comment by damithc** [comment]
> @damithc prof I decided to add an if else, stating that if the os is Mac, use emojis. else, use text based. Is that ok?

@TechRaj It is fine to have OS-specific enhancements, provided the app still works in other OS'es. Have you tried this in different Windows versions (i.e., are you sure if this works as expected in other Windows versions)?

**Comment by TechRaj** [comment]
It works on my friend's windows 11 system. I will try finding ppl with other windows versions. Thanks prof!
