### ISSUE TITLE
Looking for classmates to help smoke test a JAR file

### ISSUE THREAD

**Issue by tata32000** [nus-cs2103-AY2425S1/forum#316]
Hi everyone, 

I've released my chatbot [here](https://github.com/tata32000/ip/releases/tag/A-Release), and the user guide is available [here](https://tata32000.github.io/ip/). I’m using macOS and haven't tested the program on Windows yet.

I’d really appreciate it if you could test it out and report any bugs. I'll be happy to help test yours as well! 

Thanks!

**Comment by JoanneHing** [comment]
Hi I just downloaded your chatbot. I am using Mac aIso and I briefly tested the program and it runs well!
Good to see you have design your own GUI, you also added different color to the dialog box when command like `delete`, `mark`, `unmark` is entered. A red dialog box is also shown when there is error in the command entered bu the user, well done! Seen you also implemented a `help` command that guide the user how to use the chatbot in the app, this is a good guide for new users! Overall I haven't test out an error on the chatbot. Good job!

Here is some screenshot from my testing:
<img width="412" alt="Screenshot 2024-09-18 at 2 23 54 AM" src="https://github.com/user-attachments/assets/802dadfa-8b14-4e85-a410-4c1ce16f7fca">

<img width="408" alt="Screenshot 2024-09-18 at 2 22 11 AM" src="https://github.com/user-attachments/assets/c579f069-da82-409f-825d-2361c4dbc52b">

**Comment by RezwanAhmed123** [comment]
Hi, I'm not sure if this is a bug. I am on windows and I was smoke testing your app.

I opened it from the windows home view in file explorer and i could not send any commands using either "enter" key or the "send" button at the start. However, when I opened it from the downloads folder it was working fine.

I was curious about this so decided to test on my own app. I noticed if I opened it from home view in windows file explorer, I am able to send stuff but I get a "file cannot be created" feedback. So, maybe its just how errors were coded in the different apps.

Other than this issue, it was working fine.

Here is a video of what I am talking about:

https://github.com/user-attachments/assets/c893eaeb-eb75-4415-9a58-364a6fc7cad8

**Comment by emmannyyy** [comment]
Looks great to me! I performed my checks on Windows Subsystems for Linux.


![image](https://github.com/user-attachments/assets/177d8693-3dee-44b8-8f61-4df9a0a92f3f)
Regarding the "find" variable, does it only work with 1 keyword as intended? 
I tried to search using multiple searchkeys but then it didn't work. 

Apart from that, it looks good!

**Comment by damithc** [comment]
@RezwanAhmed123 if you run multiple jars in the same folder (e.g., the Downloads folder), testing may not be 'clean'. For example, one jar might not handle the `data` folder missing case correctly but it will go unnoticed if a `data` folder is already there from previous testing i.e., a folder created by the other jar file. Or the jar might try to read a `tasks.txt` file created by another jar file, and fail.
So, it is best to put the jar file in an empty folder before testing it.

**Comment by tata32000** [comment]
Thank you for testing! @JoanneHing

**Comment by tata32000** [comment]
@RezwanAhmed123 Thanks for pointing that out! Do you think that it could be an issue with folder permission to create file/folder?

**Comment by tata32000** [comment]
@emmannyyy Thanks for testing! My `find` command does not support multiple search keys as I want it to be able to search a sequence of words like `find read book` should match `read book` and `read book for fun`.

**Comment by RezwanAhmed123** [comment]
@damithc Hi prof, actually the bug persists when i add to a clean environment (new empty folder by itself). I think its more of a file permission thing (as pointed out by @tata32000) as it will only create the necessary files when i access it thru its actual file location rather than a shortcut such as in recents of the windows explorer.

heres the new test:

https://github.com/user-attachments/assets/876a2717-6ef1-4ce7-8ccb-12861678a92e

**Comment by damithc** [comment]
> it will only create the necessary files when i access it thru its actual file location rather than a shortcut such as in recents of the windows explorer.

@RezwanAhmed123 Yes, this is likely the case because the data files are created relative to the location it is run from. When running the jar using a shortcut, it is likely the app is run from a system location which is likely write-protected (e.g., `Windows/system32`).
So yes, not only the jar file needs to be in an empty folder, it needs to be run by navigating to that folder using a terminal and running the `java -jar` command.

**Comment by RezwanAhmed123** [comment]
@damithc understood prof. thank you!

**Comment by ChenLeiyu** [comment]
Hi, I tested it briefly on windows and all the basic features work fine.

Data saving and loading works and creating tasks works.
Only minor bug I encountered is using 'bye' command does not seem to do anything. You can interact with the chatbot perfectly fine after giving the 'bye' command.

**Comment by tata32000** [comment]
@ChenLeiyu Thank you for your feedback! For the `bye` command, I did not add the function to close the app after the command for the GUI application.

**Comment by DennieDan** [comment]
> Looks great to me! I performed my checks on Windows Subsystems for Linux.
> 
> ![image](https://private-user-images.githubusercontent.com/122295421/368384963-177d8693-3dee-44b8-8f61-4df9a0a92f3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NDAyODMsIm5iZiI6MTcyNjYzOTk4MywicGF0aCI6Ii8xMjIyOTU0MjEvMzY4Mzg0OTYzLTE3N2Q4NjkzLTNkZWUtNDRiOC04ZjYxLTRkZjlhMGE5MmYzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQwNjEzMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZDI3MDEzOTMwN2RkOTgxM2YxNTVmMTRhMGIxZDdiZmJiNGM0ZDVhZDc5M2UzZGJlYmU5ZWRhNmYyYmE1ODE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Dr9K6ipgRwmwnCfEz-MS1hB96Ike_h5v9A8mgVEcbfs) Regarding the "find" variable, does it only work with 1 keyword as intended? I tried to search using multiple searchkeys but then it didn't work.
> 
> Apart from that, it looks good!

I guess this app is programmed to return tasks that match all the words. So it takes the keyword as "conference submit" not "conference" and "submit" on their own.

**Comment by DennieDan** [comment]
Your app handles all the errors beautifully. It looks nice on my side also! I like how you tailor your app with a logo and a full-screen interface.

The C-Help extension is elegant and easy to understand. However, can try putting a link to the User Guide or providing more details on the `date` format. It is unclear at first, user can only know how to if they make at least 1 mistake.

In case you want to improve the error handling, you can consider unable the "Enter" and "Pressing Send button" actions when the TextField is empty!

**Comment by DennieDan** [comment]
Another thing, I don't know if it can be considered a bug based on the project requirement.

When I added a task, for example, a `todo` task by adding a few *spaces* after the command word `todo`, the current version still accepted it and did not consider it the wrong format. Same thing happened to `deadline` and `event` also.

This is my screenshot
![image](https://github.com/user-attachments/assets/cecc3259-de43-426f-876a-42d216dc4989)

**Comment by tata32000** [comment]
@DennieDan Thank you for pointing that out! Seems like my input validation needs some work 😅

**Comment by ckclion** [comment]
Hi I have just downloaded your chatbot and testing on a windows system.

All the basic features work great! :smile: 
I like that I am able to resize the application size

Here is a screenshot of me using the application
![image](https://github.com/user-attachments/assets/b7af20aa-e07e-4d5c-9e1a-0cd6f4efda91)

**Comment by O-Darren** [comment]
Hey, downloaded your chatbot on a windows system. Functions work great!

You can make the bye command exit the program after a duration by importing some javaFX libraries. It currently only plays the bye message.

Screenshot of me using the application
![image](https://github.com/user-attachments/assets/12a55986-0037-42d1-a566-aea0b9f077f7)

**Comment by wes-w-z-h** [comment]
lgtm 👍

**Comment by tata32000** [comment]
@ckclion Thanks for testing!

**Comment by tata32000** [comment]
@O-Darren Thanks for the feedback! I'll look into that 🫡
