### ISSUE TITLE
Running Jar File : Could not find or load main class Launcher

### ISSUE THREAD

**Issue by jevan13** [nus-cs2103-AY2425S1/forum#317]
I have this issue where it says "Could not find or load main class Launcher" when I enter java -jar Yapper.jar
![Screenshot 2024-09-18 at 2 22 22 AM](https://github.com/user-attachments/assets/d895b245-9bd0-453f-aaf6-3a5c3826db26)

![Screenshot 2024-09-18 at 2 10 10 AM](https://github.com/user-attachments/assets/6ba129ac-634a-4e88-87f5-3029237898ae)

**Comment by Domokunx** [comment]
![image](https://github.com/user-attachments/assets/f3c5cddb-19ce-41c4-ab9b-580a550263d9)
Looking through your ip folders, changing "Launcher" here to "yapper.gui.Launcher" in your build.gradle file should fix this.

**Comment by jevan13** [comment]
@Domokunx thank you
