### ISSUE TITLE
JAR file unable to save a local file

### ISSUE THREAD

**Issue by daronoh** [nus-cs2103-AY2425S1/forum#318]
I noticed that when i run my jar file by simply double clicking on the icon, I am unable to save my data locally. However, running java -jar bot.jar will allow me to save data locally etc. May I know if not being able to save data when the program is ran by double clicking considered to be a bug/error?

**Comment by yadobler** [comment]
Kindly provide:

1. OS
2. How is it revealed that the save does not work (ie does your program throw an exception? Does it not but the file is missing?)

Thanks

**Comment by damithc** [comment]
> May I know if not being able to save data when the program is ran by double clicking considered to be a bug/error?

For iP purposes, we expect the jar file to be run using `java -jar` command.
