### ISSUE TITLE
Typo in Appendix D

### ISSUE THREAD

**Issue by flyingsalsa** [nus-cs2103-AY2425S1/forum#32]
https://nus-cs2103-ay2425s1.github.io/website/admin/appendixB-policies.html#policy-on-tech-help
in appendix D under the **isolate the problem** there appears to be a missing "to" in the phrase

> the bare minimum that is enough reproduce the error.
![image_2024-08-22_174831993](https://github.com/user-attachments/assets/bd580b37-0650-4cb5-ac2f-8d1775f736d1)

**Comment by damithc** [comment]
Thanks for reporting this, @flyingsalsa 💯 
Fixed.
