### ISSUE TITLE
Clarification on Level-8 : Is it sufficient to use LocalDate instead of LocalDateTime?

### ISSUE THREAD

**Issue by rahula1008** [nus-cs2103-AY2425S1/forum#320]
So the website states the minimal requirement for Level 8, is to use a LocalDate(or LocalDateTime) object for deadline objects. My question is, is there a minimal requirement specified for the Event object? I decided to use LocalDate objects for events, but I wanted to ask, was it implied that LocalDateTime is more suitable / required for Event objects? 

i.e 
is `event team meeting /from 10-10-2024 /to 10-10-2024` sufficient?
or would `event team meeting /from 10-10-2024 1800 /to 10-10-2024 1900` be required to hit the minimal requirement?

Kind Regards, Rahul.

**Comment by damithc** [comment]
@rahula1008 This is up to you. In terms of meeting the minimum requirement, just the date is enough. So, it is a matter of how you expect the app to be used i.e., just to keep track of which day the events are, or to keep track of times as well. You can also inform users that if they want to track the time, they can state the time as part of the description
e.g., `event team meeting 4pm /on 10-10-2024`

**Comment by rahula1008** [comment]
Thanks for the clarification Prof @damithc, I understand the requirement now! For reference, I initially assumed events to be like conferences, i.e Media Conference from 10th sep to 13th sep, but later realised they might be as small as a meeting that lasts 2 hours.
