### ISSUE TITLE
Query regarding iP Project Management

### ISSUE THREAD

**Issue by nihalramesh** [nus-cs2103-AY2425S1/forum#321]
To qualify for full marks, our last 5 iP commits only need to follow the convention for the commit message subject right. Is it still required to have the full body of the commit message?

**Comment by damithc** [comment]
@nihalramesh12629 Having a body for the commit message is optional (except when you do the [`A-FullCommitMessage` increment](https://nus-cs2103-ay2425s1.github.io/website/admin/ip-w5.html#2-write-some-full-commit-messages)), but if you do add a body, you should follow the Git conventions for the body.

More info https://nus-cs2103-ay2425s1.github.io/website/admin/standardsAndConventions.html
