### ISSUE TITLE
Feature List Clarification

### ISSUE THREAD

**Issue by VedJoshi** [nus-cs2103-AY2425S1/forum#322]
For the MVP feature specification, do we also include the features already implemented in the AB3 like adding a contact? or do we only include features that we plan to add/change from the existing product?

**Comment by damithc** [comment]
@VedJoshi Good question. Yes, you should include all features, including existing AB3 features that you don't even plan to change in the MVP. But you can omit AB3 features that are not must-have and need not be in the MVP.
