### ISSUE TITLE
Codecov test failing

### ISSUE THREAD

**Issue by wang-h-z** [nus-cs2103-AY2425S1/forum#325]
<img width="1464" alt="Screenshot 2024-09-18 at 3 24 43 PM" src="https://github.com/user-attachments/assets/e1bfd1ed-3539-4c33-8877-bfacab1b957f">

Message given by Codecov check:
0.00% of diff hit (target 75.26%)

Anybody has any idea why Codecov is constantly failing?

**Comment by damithc** [comment]
@wang-h-z In some cases the code you edit is not covered by existing tests, which means codecov will report it as not adhering to the current coverage target of 75%. 
It is fine to ignore those warnings, or reduce the target coverage level codecov checks against. The third alternative is to add tests to increase the coverage of the lines in concern (probably too early to take that route, as you are still not familiar with the codebase).

Codecov is there to help you manage code coverage -- it is not graded.

Also see below:
![image](https://github.com/user-attachments/assets/1a682274-13c4-4ef7-8c4e-91861a7f0f6a)
