### ISSUE TITLE
Authentication Failed

### ISSUE THREAD

**Issue by LemonDrew** [nus-cs2103-AY2425S1/forum#326]
I closed a similar issue as I thought that I solved it, but it turns out that I am still unable to push in Sourcetree without having to provide an access key for my account. But if Im not wrong, the access token can only be accessed once.

Do I have to create another personal access token and use its password, or is there any other way to solve this issue?

<img width="431" alt="image" src="https://github.com/user-attachments/assets/70471d60-a3ed-4e84-acdc-79faaea7acad">

**Comment by sam-theman88** [comment]
I think the problem might be due to you connecting to your GitHub repo via the **HTTPS url** instead of the **SSH url**.
If the remote of your local repo is named **origin**, you can use the following command in your CLI to change the url of your remote to a new one. e.g the new url is **new.link/here**

`git remote set-url origin new.link/here`

**Comment by LemonDrew** [comment]
I used the following settings

1. OAuth
2. HTTPs

When prompted with the Access key, turns out its the password for my macbook account (which is weird). Now I can push and pull from github in sourcetree without any issues.

**Comment by damithc** [comment]
> When prompted with the Access key, turns out its the password for my macbook account (which is weird).

@LemonDrew My guess (I'm not a Mac user myself) is that your Mac has already stored the GitHub password in its Keychain app. When Sourcetree asks for that password from Keychain, Keychain is in turn asking you if it is OK to give that password to Sourcetree. To authorize this, you need to use your Mac password. So, the Keychain app is doing its job -- i.e., you only need to remember the Mac password (it keeps track of all other passwords for you -- but to access those passwords, you need to provide the Mac password).

**Comment by LemonDrew** [comment]
Got it! But it was pretty weird that sourcetree suddenly gave a bad credentials error out of nowhere (it was working fine for the past few days). Could it be due to the github authentication changes that they made recently?

**Comment by damithc** [comment]
> Could it be due to the github authentication changes that they made recently?

Possibly 🤔
