### ISSUE TITLE
Empty description problem

### ISSUE THREAD

**Issue by FYL2003** [nus-cs2103-AY2425S1/forum#327]
If an empty description can be added to the task, would it be considered as a major bug? (Does the description of a task **MUST** be non-empty?)

**Comment by Wxy2003-xy** [comment]
I believe this can be a feature, it makes sense to allow users to add tasks which have self-explaining name, or just to be too lazy to put down descriptions.

**Comment by FYL2003** [comment]
So as long as the program will not crash due to this, this can be considered as a normal behaviour.

**Comment by damithc** [comment]
> I believe this can be a feature, it makes sense to allow users to add tasks which have self-explaining name, or just to be too lazy to put down descriptions.

@Wxy2003-xy this is assuming a task has both a name field and description field, right? In the iP we didn't specifically require tasks to have both (although you are free to do so).
