### ISSUE TITLE
Github markdown (alerts)

### ISSUE THREAD

**Issue by zi-yii** [nus-cs2103-AY2425S1/forum#330]
On my github pages link, the alerts in my user guide are not shown properly but when it is viewed on my readme file, the alerts are showing correctly. Is it meant to be this way?

Screenshot from github page:

<img width="628" alt="Screenshot 2024-09-18 at 5 17 31 PM" src="https://github.com/user-attachments/assets/7837fb0e-2312-4d20-9657-9d7e86313d40">

Screenshot from readme file:

<img width="597" alt="Screenshot 2024-09-18 at 5 20 09 PM" src="https://github.com/user-attachments/assets/141ae72e-33e2-44b1-856c-f81db440a669">

**Comment by Incogdino** [comment]
This seem to be an ongoing issue as discussed here: https://github.com/orgs/community/discussions/77077

There are some solutions in that link but the easiest solution is to just change `[!NOTE]` to `**NOTE**`.

**Comment by zi-yii** [comment]
Okie thank you for the help!
