### ISSUE TITLE
GitHub Java CI

### ISSUE THREAD

**Issue by WinstonJin** [nus-cs2103-AY2425S1/forum#331]
I keep on getting an email every 15 mins on this

<img width="526" alt="Screenshot 2024-09-18 at 17 38 31" src="https://github.com/user-attachments/assets/ff8a0a1b-8001-4945-9dde-08ef80dfc3e4">

Then when I click it it brings me to this page 

<img width="1036" alt="Screenshot 2024-09-18 at 17 40 35" src="https://github.com/user-attachments/assets/742706d3-c72c-4c60-8b8e-afdecc6304a9">

```
Run ./runtest.sh
error: file not found: /Users/winston/Desktop/Code/CS2103/ip/src/main/java/windebot/Winde.java
Usage: javac <options> <source files>
use --help for a list of possible options
********** BUILD FAILURE **********
Error: Process completed with exit code 1.
```

This is the relevant part in my runtest.sh file. I also can confirm that the directory is correct, being in a package windebot/Winde.java

```
# compile the code into the bin folder, terminates if error occurred
if ! javac -cp /Users/winston/Desktop/Code/CS2103/ip/src/main/java -Xlint:none -d ../bin /Users/winston/Desktop/Code/CS2103/ip/src/main/java/windebot/Winde.java
then
    echo "********** BUILD FAILURE **********"
    exit 1
fi
```

I only had this error recently when I changed my GitHub personal token and had to sign into my GitHub account on IntelliJ again. I am on a MacBook. Anyone have any idea how to solve this? Thank you!

**Comment by yadobler** [comment]
>error: file not found: /Users/winston/Desktop/Code/CS2103/ip/src/main/java/windebot/Winde.java

 the java path in your runtest.sh seems to be hard coded. 

GH actions run the workflow in a virtual machine in the cloud where it clones your repo into work directory and then runs the jobs from the **repo root directory **

Try using relative path in the sh file

**Comment by WinstonJin** [comment]
How do you input the relative path?

Is it something like this: 

```
javac  -cp ..\src\main\java -Xlint:none -d ..\bin ..\src\main\java\*.java
```

Edit: I still get the same error though

**Comment by Anant1902** [comment]
> How do you input the relative path?
> 
> Is it something like this:
> 
> ```
> javac  -cp ..\src\main\java -Xlint:none -d ..\bin ..\src\main\java\*.java
> ```
> 
> Edit: I still get the same error though

Hi @WinstonJin, I am a senior from the previous batch. You can try replace your absolute path with this, and check if it works! It seems, on first look, that the absolute hardcoded path is the issue!
 ```
if ! javac -cp ./src/main/java -Xlint:none -d ./bin ./src/main/java/windebot/Winde.java
then
    echo "********** BUILD FAILURE **********"
    exit 1
fi 
```

**Comment by ThatGirlJam** [comment]
Hi @WinstonJin, I am a senior from the previous batch. It seems from your repo that you've tried replacing the absolute path in the runtest.sh file with `if ! javac -cp ./src/main/java -Xlint:none -d ./bin ./src/main/java/windebot/Winde.java`

However since you have made the bin in `../bin`, you may like to try 
`if ! javac -cp ../src/main/java -Xlint:none -d ../bin ../src/main/java/windebot/Winde.java`. Take note of the two dots. While one dot refers to the current directory, two dots refer to the parent directory. 

Hope this helps!

**Comment by gerteck** [comment]
Hi, I'm dropping by to hopefully give some input you will find useful as well.

```
# create bin directory if it doesn't exist
if [ ! -d "../bin" ]
then
    mkdir ../bin
fi
...
# compile the code into the bin folder, terminates if error occurred
if ! javac -cp ./src/main/java -Xlint:none -d ./bin ./src/main/java/windebot/Winde.java
then
    echo "********** BUILD FAILURE **********"
    exit 1
fi
```

1. These lines of code seem to be referencing different bin directories ('./bin' and '../bin).

https://superuser.com/questions/153165/what-does-represent-while-giving-path

2. Notice that in your github workflows file, 

```
working-directory:  ${{ github.workspace }}/text-ui-test
```

the cwd when you are running your test has implications on how you may compile your java file. 

You could also consult how Duke implements this as well: https://github.com/se-edu/duke/blob/full-template/text-ui-test/runtest.sh

Hope this helps enough for you to understand, and solve the issue on your own!

**Comment by WinstonJin** [comment]
Thank you for all your inputs! 

@Anant1902, this was my error code:
```
Run ./runtest.sh
error: file not found: ./src/main/java/windebot/Winde.java
Usage: javac <options> <source files>
use --help for a list of possible options
********** BUILD FAILURE **********
Error: Process completed with exit code 1.
```

@ThatGirlJam 
```
Run ./runtest.sh
Error: Could not find or load main class Winde
Caused by: java.lang.ClassNotFoundException: Winde
diff: EXPECTED-UNIX.TXT: No such file or directory
Test result: FAILED
Error: Process completed with exit code 1.
```

@gerteck 
```
Run ./runtest.sh
error: file not found: ./src/main/java/windebot/Winde.java
Usage: javac <options> <source files>
use --help for a list of possible options
********** BUILD FAILURE **********
Error: Process completed with exit code 1.
```

Thank you all for your help once again but after thinking a bit, it may be due to the runtest.sh being a feature for the previous weeks without the GUI requirement. Hence my main class now is the Launcher class instead of the Winde class. Maybe this is the issue? Or maybe when I changed my GitHub personal token and had to sign into my GitHub account on IntelliJ again it detected that I had this error whenever I push new commits. 


Anyways this issue doesn't really affect my end product of my iP (jar file) and so I think I will just close this issue. It is just annoying that everytime I push a commit I get this email saying my JAVA CI workflow has an issue.

**Comment by damithc** [comment]
@WinstonJin There is no need to keep runtest.sh in the repo after adding the GUI.
![image](https://github.com/user-attachments/assets/beb711f3-49fe-48c7-abca-3b637bc1091e)
