### ISSUE TITLE
Must stubs be implemented in a <SomeTest>.java files as a inner static class?

### ISSUE THREAD

**Issue by Feng1231** [nus-cs2103-AY2425S1/forum#332]
I was looking at some other issues and realised people declared the stubs inside the test classes where they would need to use it.
However, I did it this way:

![image](https://github.com/user-attachments/assets/e5c9e57a-c061-47d0-bde4-bba74a42e0ee)

Is this okay or not allowed?

**Comment by damithc** [comment]
> Is this okay or not allowed?

@Feng1231 We don't have any rule on this. Both _allowed_.

**Comment by Feng1231** [comment]
Thank you prof for the speedy response 🙂.
