### ISSUE TITLE
Did not make branch for certain tasks.

### ISSUE THREAD

**Issue by reidenong** [nus-cs2103-AY2425S1/forum#333]
I accidentally missed out on creating branches for A-Assertions, A-CodeQuality, and made changes in the master branch directly. As such, I do not have the tags for branch-A-CodeQuality, branch-A-Assertions.

What are the recommended actions for this, should i undo the changes and redo as a branch?

**Comment by damithc** [comment]
@reidenong You can add tags to past commits any time. As long as the tag is in the repo and reachable from the master branch, the dashboard will accept it.
Regarding missed branches, see below:

![image](https://github.com/user-attachments/assets/40c6ed75-a06d-4d88-9abd-7256a151ae9d)
