### ISSUE TITLE
Getting warning when running the jar file in Windows Powershell

### ISSUE THREAD

**Issue by jian7490** [nus-cs2103-AY2425S1/forum#334]
Sep 18, 2024 7:09:39 PM com.sun.javafx.application.PlatformImpl startup
Warning: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @1d3b6895'

I keep getting this warning when java -jar my jar file.
Anyone faced similar thing and solved it?
Thanks.

**Comment by weiliann** [comment]
It's a known issue as mentioned [here](https://se-education.org/guides/tutorials/javaFxPart1.html#:~:text=WARNING%3A%20Unsupported%20JavaFX%20configuration%3A%20classes%20were%20loaded%20from%20%27unnamed%20module%20%40...) but still curious if anyone fixed it.
