### ISSUE TITLE
Problem: not able to fulfill the ip tag -Use GFMD

### ISSUE THREAD

**Issue by dominic2412** [nus-cs2103-AY2425S1/forum#336]
Hi all!

May i consult if anyone has idea on the requirement to light up the GFMD requirement, which is a week 4 task.
I've tried editing and was sure that I have met most if not all of the tasks as listed on the cs2103 website.

![download](https://github.com/user-attachments/assets/f4f326b0-f3d6-4dcf-8185-3b8e18a9f4c5)

I have attached the IP task progress and the pull request comment page for reference

thanks!
![download (2)](https://github.com/user-attachments/assets/6e92708e-4dd7-4bd5-9ca9-dff515445cd1)
![download (1)](https://github.com/user-attachments/assets/cd410eaf-3bf0-4536-af69-b5a41874cc47)

**Comment by Incogdino** [comment]
Is the code block right? There seem to be excess ` being outputted. Make sure you use 

\```<language_name>
code
\```

**Comment by Incogdino** [comment]
Also, it looks like you are missing a header, inline code and some text formatting

**Comment by flyingsalsa** [comment]
Ya you are missing in some text formatting such as:
~~Slow~~ *Lightning* fast

inline code such as:
make use of ```java -jar Duke.jar```  to run.


And I think Headers
# Duke

**Comment by flyingsalsa** [comment]
If you quote reply you should be able to see what the formatting is for the examples in markdown, hope that helps!
