### ISSUE TITLE
Require help for testing

### ISSUE THREAD

**Issue by Feng1231** [nus-cs2103-AY2425S1/forum#338]
Hi, I have release my application! 
I have been running my application on windows and have not done a lot of testings on mac.
Would appreciate if someone could do some basic testing for me 🙂
You can download it [here](https://github.com/Feng1231/ip/releases/download/A-Release/duck-0.2-all.jar).
The documentation is [here](https://feng1231.github.io/ip/)

Thanks for the help in advance :-)

**Comment by tata32000** [comment]
@Feng1231 I have tested your app in MacOS and it's working very well! Also, I wonder how you manage to save the tasks without creating a new text file.

![Screenshot 2024-09-18 at 23 03 29](https://github.com/user-attachments/assets/a0654a67-6703-464e-9ccd-638cb8ee281e)

**Comment by Feng1231** [comment]
> @Feng1231 I have tested your app in MacOS and it's working very well! Also, I wonder how you manage to save the tasks without creating a new text file.
> 
> ![Screenshot 2024-09-18 at 23 03 29](https://private-user-images.githubusercontent.com/86035967/368626678-a0654a67-6703-464e-9ccd-638cb8ee281e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NzI0MzYsIm5iZiI6MTcyNjY3MjEzNiwicGF0aCI6Ii84NjAzNTk2Ny8zNjg2MjY2NzgtYTA2NTRhNjctNjcwMy00NjRlLTljY2QtNjM4Y2I4ZWUyODFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDE1MDg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyY2E5ODNmMWVhMmRmZTIwYzIyM2FmNWQwNDk2ODg2OTZjOGQ0MjI5OThlMjUyOTlkNjI5YmJmN2UwZGM4NTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BL_4UNMjE6jLa5j-KKMy6HkOi3eSG__uHBuSEEQZEmw)

Thank you so much!

Actually I did created a text file. 
The data file is located under the home directory of the user.
You can refer to the last part of my documentation [here](https://feng1231.github.io/ip/#editing-the-data-file).

Also, did no message pop up the first time you run the application? It should show a message like this, telling you the file path:
![image](https://github.com/user-attachments/assets/18b328dd-dd59-424e-a1de-6fc78935716b)

**Comment by tata32000** [comment]
@Feng1231 I see, seems like I missed that part 😅
