### ISSUE TITLE
Issue with making the jar file run the code

### ISSUE THREAD

**Issue by WinstonJin** [nus-cs2103-AY2425S1/forum#339]
Hi I'm also getting this issue. I'm using a Macbook and it seems that this problem only occurs when trying to run from the jar file. If I do the ```./gradlew run``` on the IntelliJ terminal, it works fine and I can read the previous safe file. But if I do ```./gradlew clean shadowJar``` and go to the directory and run the following, I get the error message:

My input in the terminal
``` 
java -jar Winde.jar
```

The error message I get

```
Error in creating fileNo such file or directory
Error Loading Tasks to File: ../src/main/java/windebot/WindeTasks.txt (No such file or directory)
```

So I tried changing the file path to ```WindeTasks.txt```  instead of the ```../src/main/java/windebot/WindeTasks.txt``` and I get a long error message:

```
Caused by: java.lang.NullPointerException: Cannot invoke "java.io.File.mkdirs()" because the return value of "java.io.File.getParentFile()" is null
	at windebot.History.load(History.java:60)
	at windebot.Winde.<init>(Winde.java:40)
	at gui.Main.<init>(Main.java:17)
	... 11 more
```

This is the line 60 code in History:

```
            if (!file.exists()) {
                file.createNewFile();
                file.getParentFile().mkdirs(); // line 60
                file.createNewFile();
                // file.exists();
```

**Comment by Incogdino** [comment]
It looks like when the jar file is ran, there is no parent directory and thus the filename returns `null`.

Try removing line 60 and test the jar file. So then the txt file will just be created at the same level as your jar file.

Update: Did not realize in line 59, you had already created a new file. 

In that case, since the file you created `WindeTasks.txt` does not have a path, you need to define the path by calling

```java
file.getAbsoluteFile().getParentFile().mkdirs(); // line 60
```

**Comment by WinstonJin** [comment]
Thank you so much! I managed to solve it. 

What I did was I deleted the line 60 but also realised that the error code 

```
Error in creating fileNo such file or directory
Error Loading Tasks to File: ../src/main/java/windebot/WindeTasks.txt (No such file or directory)
```

was referring to my save method, not my load method as mentioned above. Because I forgot to change the file directory of my save method. Now it works! Thank you!
