### ISSUE TITLE
Typos in Week 3-Project

### ISSUE THREAD

**Issue by SQ77** [nus-cs2103-AY2425S1/forum#34]
In Duke Level-7: Save

Your code must handle the case where the data file doesn't exist at the start. Reason: when someone else takes your chatbot and runs it for the first time, the required file will not exist in their computer. Similarly, if you expect the data file to be in **as** specific folder (e.g., ./data/), you must also handle the folder-does-not-exist-yet case.

Typo 1 (When hovering over the word "handle"): i.e., if the file is missing, your code must **creat** it
Typo 2: "as" should be "a" instead

**Comment by damithc** [comment]
Thanks for reporting this, @SQ77 💯 
Fixed.
