### ISSUE TITLE
Test on MacOS failed

### ISSUE THREAD

**Issue by jian7490** [nus-cs2103-AY2425S1/forum#341]
### Issue Description
I'm using a Mac with M1 chip to test my ip which is built on Windows. It can work on my Windows device. 
I'm facing this issue about architecture right now. 
<img width="1440" alt="8b208726eb268fe61e7d477b7f56edc" src="https://github.com/user-attachments/assets/ae7d84c8-f71a-4678-9305-f3c5cb845f13">

Here is my build.gradle code. I suspect it is about loading JavaFX dependencies. The current version is reused from a past student who fixes the similar issues of testing on different os. 

```groovy
plugins {
    id 'java'
    id 'application'
    id 'com.github.johnrengelman.shadow' version '7.1.2'
    id 'org.openjfx.javafxplugin' version '0.0.13'
}

repositories {
    mavenCentral()
}

dependencies {
    //@@author woojiahao-reused
    //Reused from https://github.com/woojiahao/ip/blob/master/build.gradle
    testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.10.0'
    testRuntimeOnly group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.10.0'
    implementation group: 'com.google.code.gson', name: 'gson', version: '2.10.1'
    testImplementation 'org.testng:testng:7.1.0'

    def platforms = ["win", "linux", "mac"]
    def javafxDependency = ["javafx-graphics", "javafx-controls", "javafx-fxml"]

    for (plt in platforms) {
        for (dep in javafxDependency) {
            runtimeOnly "org.openjfx:$dep:$javafx.version:$plt"
        }
    }
    //@author woojiahao
}

test {
    useJUnitPlatform()

    testLogging {
        events "passed", "skipped", "failed"

        showExceptions true
        exceptionFormat "full"
        showCauses true
        showStackTraces true
        showStandardStreams = false
    }
}

application {
    mainClass.set("chatbaby.Launcher")
}

allprojects {
    tasks.withType(JavaCompile) {
        options.encoding = 'UTF-8'
    }
}

tasks.withType(JavaExec) {
    jvmArgs = ['-Dfile.encoding=UTF-8']
}

shadowJar {
    archiveBaseName = "ChatBaby"
    archiveFileName = 'ChatBaby.jar'
    archiveClassifier = null
}

javafx {
    version = '17.0.7'
    modules = ['javafx.base', 'javafx.controls', 'javafx.fxml', 'javafx.graphics']
}

run{
    standardInput = System.in
}

```

**Comment by rahula1008** [comment]
Hi @jian7490, would you be able to copy the code and put it in a code block next time?

There definitely is a recurring error message saying : "have x86_64, need arm...", but before looking into those, do try the following:

1. Do the following command: `java -version` and make sure you have the correct java version as referenced by this [guide](https://se-education.org/guides/tutorials/javaInstallationMac.html). You need to have this exact version, and as they say in the guide, 

> This version is resilient to compatibility issues between Mac ARM and Mac Intel computers when creating/running Java GUI applications built using JavaFX.
> 

Do let me know whether this works, and if it doesn't, there are a few other possible fixes we can look into.

Edit: Typos

**Comment by raageth** [comment]
I think the issue is with the java version. Ensure your java version is correct by doing `java -version` as referenced by this [guide](https://se-education.org/guides/tutorials/javaInstallationMac.html). If you installed java with sdkman, the issue is with the java source path.

Try running this command: `source "$HOME/.sdkman/bin/sdkman-init.sh"`. If it works, append this line to your config by doing `echo source "$HOME/.sdkman/bin/sdkman-init.sh" >> ~/.zshrc` (it looks like you are using zsh shell)

**Comment by jian7490** [comment]
Hey guys thanks for your help and I think you are right. The Mac device I used didn't install java 17 as shwon in the guide, although it is also java 17. I tested it on another device and it is fine now. Thank you for your help.
