### ISSUE TITLE
Project Management Component Scoring

### ISSUE THREAD

**Issue by Puakii** [nus-cs2103-AY2425S1/forum#343]
Hi Prof @damithc, I noticed that the project management component has a requirement of submitting deliverables in at least 4 out of 5 iP weeks. However I only submitted in 3 of those weeks. Does this mean my score is limited to half of the iP score?

**Comment by damithc** [comment]
@Puakii Should be fine, if almost all the deliverables are green, and the commits are reasonably spread out. 

In general, if any lapse is causing a student to earn less than full marks, we'll inform the student and give a way (and time) to make up for it and earn full marks. So, no need to worry.

**Comment by Puakii** [comment]
thanks prof!
