### ISSUE TITLE
Requesting help to smoke test my jar file

### ISSUE THREAD

**Issue by SwaminathanViswa** [nus-cs2103-AY2425S1/forum#345]
Hello everyone! I am a Windows user.
Please do help me smoke test my jar file!

[Jar file](https://github.com/SwaminathanViswa/ip/releases/tag/A-UserGuide)
[User guide](https://swaminathanviswa.github.io/ip/)

 Thank you so much for your help!

**Comment by lavanyagarg112** [comment]
I am a mac user and all features work well on my side!

Just wondering if the date/time validation doesn't work only on my system, or is it an intended feature.

Otherwise everything else looks great

**Comment by skyl3-r** [comment]
Hi, good job on your IP! I'm a windows user but I thought I'll still help test things out. Mostly everything looks good to me, except when I use the unmark command, the formatting of the response appears to be slightly off. Also, when adding a task with dates, it appears that I can set the date to be anything, even strings like "tomorrow" or empty strings. It might be good to fix this before the final submission. All the best!

**Comment by arnav-goel05** [comment]
Hi, everything looks great on my end on Windows. Maybe you could introduce a bit of personalization and their were a couple of minor errors such as for the command 'list -1', the bot would still print out the list. In the case for 'delete -1', I was unable to send the message.

**Comment by SwaminathanViswa** [comment]
@lavanyagarg112 @skyl3-r @Arnaxx54 thank you so much for your inputs! I will definitely take a look at them and update them accordingly!

**Comment by SKarthikeyan28** [comment]
Hi, I am a mac user and the bitbot.jar file runs properly on my mac! Good job on your iP, maybe you could pass you instructions message as a separate text instead of stating everything at in your introduction text. You could also see if you can add a condition in your list printing method to print that there's no tasks in the list when 0 tasks as now it prints an empty list. 
![Uploading Screenshot 2024-09-20 at 11.43.15 AM.png…]()

**Comment by SuhailLoya** [comment]
Just tested on my mac, as @lavanyagarg112 mentioned there seems to be no date time validation. But apart from that everything else seems to be working!

<img width="412" alt="Screenshot 2024-09-20 at 5 01 09 PM" src="https://github.com/user-attachments/assets/1a743780-f95d-4361-90f8-eaf137a5f9ca">
