### ISSUE TITLE
iP dashboard failed to detect branch.

### ISSUE THREAD

**Issue by ItsMeNengYi** [nus-cs2103-AY2425S1/forum#348]
@damithc
Dear professor,
I have a problem with my branches not being detected by the iP dashboard.
The branches have been pushed to my iP repo, but iP dashboard has not updated.
<img width="965" alt="image" src="https://github.com/user-attachments/assets/a5581893-8e10-497a-982b-2210808b3ca4">
<img width="1414" alt="image" src="https://github.com/user-attachments/assets/50950163-7453-4df0-a937-d575d2c2a31d">

**Comment by damithc** [comment]
@ItsMeNengYi Not to worry. We should be able to figure this out and rectify in due course.

At the top of the [iP progress dashboard](https://nus-cs2103-ay2425s1.github.io/dashboards/contents/ip-progress.html), there are a couple of tips about troubleshooting when an increment related to a tag or a branch is not green as expected. See if those help you locate the problem.

**Comment by ItsMeNengYi** [comment]
Alright thanks prof.
