### ISSUE TITLE
error: Invalid filename

### ISSUE THREAD

**Issue by Soumyadip-cmd** [nus-cs2103-AY2425S1/forum#35]
```java
@ECHO OFF

REM create bin directory if it doesn't exist
if not exist ..\bin mkdir ..\bin

REM delete output from previous run
if exist ACTUAL.TXT del ACTUAL.TXT

REM compile the code into the bin folder
javac  -cp ..\src\main\java -Xlint:none -d ..\bin "..\src\main\java\*.java"
IF ERRORLEVEL 1 (
    echo ********** BUILD FAILURE **********
    exit /b 1
)
REM no error here, errorlevel == 0

REM run the program, feed commands from input.txt file and redirect the output to the ACTUAL.TXT
java -classpath ..\bin Assitinator < input.txt > ACTUAL.TXT

REM compare the output to the expected output
FC ACTUAL.TXT EXPECTED.TXT
```
C:\Users\soumy\OneDrive - National University of Singapore\ip\text-ui-test>.\runtest.bat
error: Invalid filename: ..\src\main\java\*.java
Usage: javac <options> <source files>
use --help for a list of possible options
********** BUILD FAILURE **********

Hi all, I am getting an error running the runtest.bat file. I have attached the code and the stack trace. I have also CD into the test directory as mentioned in a previous issue but error still persists. Any help would be appreciated.

**Comment by Incogdino** [comment]
Please refer to https://github.com/nus-cs2103-AY2425S1/forum/issues/11#issue-2472852762 and https://github.com/nus-cs2103-AY2425S1/forum/issues/31#issue-2480257311

What I think went wrong was that you did not navigate to the folder directory before running the script

Edit: Could you also try running the full file path of the runtest.bat file from within the directory

**Comment by Soumyadip-cmd** [comment]
PS C:\Users\soumy\OneDrive - National University of Singapore\ip\text-ui-test> cmd /c "C:\Users\soumy\OneDrive - National University of Singapore\ip\text-ui-test\runtest.bat"
error: Invalid filename: ..\src\main\java\*.java
Usage: javac <options> <source files>
use --help for a list of possible options
********** BUILD FAILURE **********
I tried running the entire path but still get the same error

**Comment by Incogdino** [comment]
`javac  -cp ..\src\main\java -Xlint:none -d ..\bin ..\src\main\java\*.java
`
oh could you try the above instead? I removed the quotation marks

**Comment by Soumyadip-cmd** [comment]
Oh now it works. Thank you very much for the help.

**Comment by damithc** [comment]
> `javac -cp ..\src\main\java -Xlint:none -d ..\bin ..\src\main\java\*.java `
> oh could you try the above instead? I removed the quotation marks

Nice catch, @Incogdino 👍
