### ISSUE TITLE
Requesting help to smoke test my jar file

### ISSUE THREAD

**Issue by reginateh** [nus-cs2103-AY2425S1/forum#350]
Hello everyone! I am a Windows user.
Please do help me smoke test my jar file!

[Jar file](https://github.com/reginateh/ip/releases/tag/v0.2)
[User guide](https://reginateh.github.io/ip/)

Thank you so much for your help!

**Comment by weiliann** [comment]
App crashes when invalid date is provided.

For e.g. `deadline d /by 2222-22-22` will crash the app.

**Comment by LynetteLeeSiYing** [comment]
yes! it works on my device. Mine is MacOS.

**Comment by jinnsuke** [comment]
Works well on my MacOS. Good work :)

**Comment by reginateh** [comment]
@weiliann @LynetteLeeSiYing @jinnsuke Thank you so much!!

**Comment by jagdeepsh** [comment]
Works well on my MacOS, all seem to be fine.

**Comment by SKarthikeyan28** [comment]
Hi! Works well on my mac and the chatbot works well! 
If there's time, you could think of adding a help command option which can show an example of the right command the user should give!

**Comment by wes-w-z-h** [comment]
Can consider adding conditions to catch such cases:

<img width="397" alt="image" src="https://github.com/user-attachments/assets/c0b714e6-d964-4c7c-90bd-530a051c2159">

**Comment by reginateh** [comment]
@JagdeepSinghNUS @SKarthikeyan28 @wes-w-z-h Thanks for the suggestions!
