### ISSUE TITLE
Does bye need to be a required command?

### ISSUE THREAD

**Issue by lavanyagarg112** [nus-cs2103-AY2425S1/forum#351]
I just wanted to check if `bye` is a required command? Since I switched to GUI, I decided not to make bye a command, since the user can easily exit by clicking on the cross on the GUI. Is that ok, or must I make my application exit on `bye`?

**Comment by Felipe-Rafael-Rosa** [comment]
install this
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw

you may need to install the c compiler

**Comment by damithc** [comment]
@lavanyagarg112 It was intended to be kept, as it's nicer if the user can exit by typing a command too. Still, it is not a strict requirement. You can still meet the bar for the iP features even without it, provided you have the other features.

**Comment by lavanyagarg112** [comment]
Oh ok thank you prof! In that case I will still keep it
