### ISSUE TITLE
Github Actions build and check with gradle failing

### ISSUE THREAD

**Issue by Raghava-Chittidi** [nus-cs2103-AY2425S1/forum#353]
Helloo, all the tests are passing when I run them on Intellij IDE. However, when I push to github, the github actions step build and check with gradle is failing for some reason due to failed tests. The expected and actual output it is displaying also looks the same to me so I am not very sure what could be a possible issue.

<img width="1446" alt="Screenshot 2024-09-19 at 7 45 20 PM" src="https://github.com/user-attachments/assets/cf237b45-cab6-4a0d-82e2-61dc2aa6f2be">

**Comment by damithc** [comment]
@Raghava-Chittidi Which OS are you using locally? Certain behaviors can vary based on the OS e.g., the line endings differ between Windows and Mac/Linux.

**Comment by suhayl13** [comment]
It seems like there is a mismatch in the case sensitivity. It was expecting a lowercase “pm” but received an uppercase “PM”.

**Comment by Raghava-Chittidi** [comment]
I am using macOS Sonoma 14.2. Ohh I am not too sure why the uppercase is there because when I run the tests locally they were all lowercase and they passed all the tests

**Comment by suhayl13** [comment]
I think the date and time is being formatted differently on GitHub actions. I searched this up so maybe can try adding the following code into the yaml file:
```
- name: Set locale
  run: sudo update-locale LANG=en_US.UTF-8
```

**Comment by emmannyyy** [comment]
I think this is similar to the issues I faced in #277 and #307. 

You can probably set the time locality for the whole run of the application in your Main() method, as #307 suggests

**Comment by Raghava-Chittidi** [comment]
Thank you everyone!
