### ISSUE TITLE
Crediting se-education for JavaFX

### ISSUE THREAD

**Issue by ckclion** [nus-cs2103-AY2425S1/forum#354]
May I ask what is the proper way to credit se-education if I have reused code from their JavaFX tutorial?

**Comment by damithc** [comment]
@ckclion It's mentioned in https://nus-cs2103-ay2425s1.github.io/website/admin/appendixB-policies.html#policy-on-reuse (search in the page for `se-edu`)

**Comment by ckclion** [comment]
@damithc Oh I must have missed it thank you!
