### ISSUE TITLE
Creating a PR for TP

### ISSUE THREAD

**Issue by winstonlimjy** [nus-cs2103-AY2425S1/forum#355]
Hi guys, do yall know if we should edit the master branch of the immediate fork of AB3, in order to create a PR request to the upstream cs2103t repo? How do i create a PR request if there are zero changes and the code is identical?

**Comment by damithc** [comment]
@winstonlimjy You can do a small change in the README file, or delay creating the PR until there are changes in the repo.

**Comment by damithc** [comment]
To add, when you set up the website of your team repo, you will need to change some files anyway. Yes, you can commit those changes to the `master` branch.

**Comment by winstonlimjy** [comment]
> To add, when you set up the website of your team repo, you will need to change some files anyway. Yes, you can commit those changes to the `master` branch.

Thank you!
