### ISSUE TITLE
checkstyle import statements

### ISSUE THREAD

**Issue by verakohh** [nus-cs2103-AY2425S1/forum#357]
<img width="1277" alt="image" src="https://github.com/user-attachments/assets/24f331ad-626c-46d9-a69a-6082b2c62954">

```
package cleo;

import javafx.util.Pair;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;

public class ParserTest {
```

hi! i have no idea how else im suppose to write my import statements, i cant remove the static from the imports as well if not my code wont work:(

**Comment by Incogdino** [comment]
Change the order of the import statements to 

```java
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;

import org.junit.jupiter.api.Test;

import javafx.util.Pair;
```

Edit: Got the order wrong oops. The updated one should work.

**Comment by zaidansani** [comment]
In addition to this, peep the tip found here in #150.
Do the relevant changes and use IntelliJ's inbuilt reformat code (or any equivalent tools) to fix all the other code in your files!

**Comment by verakohh** [comment]
@Incogdino thank you so much! 
for some reason that still gives me an error but this

```
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;

import org.junit.jupiter.api.Test;

import javafx.util.Pair;
```
solves it!
