### ISSUE TITLE
Question on Grading of the IP

### ISSUE THREAD

**Issue by Ma-Xizi** [nus-cs2103-AY2425S1/forum#358]
Hi Prof! May I know how we can evaluate our **code quality** and **junit testing** for the two methods? Or is there any way to track our progress? I have been diligently refactoring my code, but I find it challenging to gauge when the process is complete.

**Comment by damithc** [comment]
@Ma-Xizi evaluating your own code quality (and the level of testing) is among things we hope you'll learn in this course. We did give you some automated feedback on code quality to get you started but from then on you'll need to manage it yourself. So, you can make a judgement call on how much is enough. Later on, during the iP evaluation (which has a peer evaluation), you'll also get to evaluate the code quality and testing level of other iPs. This should serve as more practice. 
That said, we'll still give you some further code quality feedback later, after the iP is over. That will help you identify the things you missed yourself, and do an even better job in the tP.

**Comment by Ma-Xizi** [comment]
> @Ma-Xizi evaluating your own code quality (and the level of testing) is among things we hope you'll learn in this course. We did give you some automated feedback on code quality to get you started but from then on you'll need to manage it yourself. So, you can make a judgement call on how much is enough. Later on, during the iP evaluation (which has a peer evaluation), you'll also get to evaluate the code quality and testing level of other iPs. This should serve as more practice. That said, we'll still give you some further code quality feedback later, after the iP is over. That will help you identify the things you missed yourself, and do an even better job in the tP.

Okay! Thank you Prof!
