### ISSUE TITLE
Advice on Committing Multiple Files (IP Week 2 Level-3)

### ISSUE THREAD

**Issue by vicelyav** [nus-cs2103-AY2425S1/forum#36]
Hi, can I ask, is it possible/recommended that we commit 2 files at once? I recently created a separate file to store my Task class to tackle the level-3 of Week 2 ip task. How do we go around with tagging these files?

**Comment by blanklogic** [comment]
> Hi, can I ask, is it possible/recommended that we commit 2 files at once? I recently created a separate file to store my Task class to tackle the level-3 of Week 2 ip task. How do we go around with tagging these files?

Hi, I assume when you mean committing 2 files at once, you mean adding 2 files to a commit.

I'm not sure what's the guidelines or recommendations are for this course, so hope someone could fill me in on this as well. Personally, I would complete all my work for each Level before adding/staging them all into one commit with a general description of what I have done for the commit (like a major revision/change). After staging them, I would add the tag for the level and push them all to my forked repo. Would probably be easier for you to view the key changes you have made for each level increment in a single commit and leaving minor bug fixes as extra commits thereafter.

**Comment by tohhengxing** [comment]
My opinion is that it is very difficult to read git history when every commit only consist if one change.

**Comment by Wxy2003-xy** [comment]
IMO it is appropriate to commit changes made for the same purpose e.g. multiple new files created to implement a new function, together; On the other hand it would be beneficial to commit changes made in the same file but for different purposes separately, so it's easy to identify where problem may come from when issues arise.

**Comment by damithc** [comment]
Thanks for raising this relevant discussion point @vicelyav and for the inputs so far @blanklogic @tohhengxing 

The course does not impose a specific requirement on this (i.e., what to include in a commit). It is one of those aspects for which we want you to discuss/research best practices and decide on a set of reasonable practices to follow for yourself. I look forward to seeing what you share here on this topic.

On a related note, we _do_ prescribe [a format for the commit message](https://nus-cs2103-ay2425s1.github.io/website/admin/standardsAndConventions.html). It will be added to iP requirements at a later point i.e., it is not applicable to Week 2 iP work.

**Comment by vicelyav** [comment]
Thank you so much everyone!
