### ISSUE TITLE
Use GFMD progress not updating in dashboard

### ISSUE THREAD

**Issue by sannie-beep** [nus-cs2103-AY2425S1/forum#360]
I was wondering why my Use GFMD is tagged as not done. I had actually edited it twice, once on Wednesday morning and once this morning. The dashboard was last updated at 21:16, but I had already updated my GFMD and made a commit way before that. 

Here is a screenshot of the dashboard page:
![Screenshot 2024-09-19 233338](https://github.com/user-attachments/assets/dced1dd9-8136-4741-948c-3d5ad54c1f44)

Here is a screenshot of my GFMD. I have followed all the requirements entailed in the instructions for the task. 
![Screenshot 2024-09-19 234058](https://github.com/user-attachments/assets/c90075e6-a16a-4a2a-8c5a-0e2d26946384)
![Screenshot 2024-09-20 001800](https://github.com/user-attachments/assets/82488c33-ebc7-44b9-af32-41fee50f92d1)

Would you be able to advise on why the task has not been recorded as complete?

**Comment by damithc** [comment]
> I had already updated my GFMD and made a commit way before that.

hmmm... this one shouldn't need any commits 🤔 😁

**Comment by MAOXIONGKAI** [comment]
Sorry but someone please correct me if I am wrong, I don't think this is how you should include emoji in your GFMD, you should use markdown language to specify the emoji as well instead of just copy pasting them like this, for more detail can refer to this [GFMD emoji cheat sheet](https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://github.com/ikatyang/emoji-cheat-sheet/blob/master/README.md&ved=2ahUKEwjHrKieuc-IAxWaTGwGHbe9F1UQjjh6BAgXEAE&usg=AOvVaw1ZAGUCBD1x16WQz339KJ7L).

Hope this helps.

**Comment by sannie-beep** [comment]
Firstly, thanks for the replies! 

@MAOXIONGKAI  Hm, but I was following this from the Github docs on GFMD 
>Typing : will bring up a list of suggested emoji. The list will filter as you type, so once you find the emoji you're looking for, press Tab or Enter to complete the highlighted result.
I didn't copy and paste and instead it just auto-filled it, so I'm unsure why it still didn't record. 

@damithc I see, but I am still unsure as to why it didn't record in the dashboard since the updated Readme shows on my iP too, despite my commits. Becayse I seem to be meeting all the requirements listed (unless it has something to do with the emoji format). Could it perhaps be something to do with the progress tracker?😕

**Comment by damithc** [comment]
> @damithc I see, but I am still unsure as to why it didn't record in the dashboard since the updated Readme shows on my iP too, despite my commits. Becayse I seem to be meeting all the requirements listed (unless it has something to do with the emoji format). Could it perhaps be something to do with the progress tracker?😕

@sannie-beep This requirement doesn't ask you to put GFMD in the README file (hence, no commit is needed). Instead, GFMD is expected in the PR description.

**Comment by sannie-beep** [comment]
@damithc Ohh, I see! I misinterpreted the task as having to edit the README, since I thought that was what the description was referring to 😅. Thanks for your patience and replies! I have now edited the description. 👍
