### ISSUE TITLE
Unable to push my commits

### ISSUE THREAD

**Issue by nws321** [nus-cs2103-AY2425S1/forum#361]
I am faced with an error now that I am unsure how to solve and it is preventing my commits from being pushed. If anyone know where the issue lies and how to fix it please assist me thank you!
<img width="581" alt="Screenshot 2024-09-19 at 11 44 33 PM" src="https://github.com/user-attachments/assets/ea9b353d-3edb-4046-8193-62eee42fb961">

**Comment by yadobler** [comment]
Could you show what are the pending commits that have not been pushed? (those with the `master` tag and no `origin/master` tags)

I'm gonna guess it might be an image you're pushing that is too large for the default postBuffer size ([see this](https://stackoverflow.com/a/78260070))

If you don't mind getting your hands dirty with CLI then you can go to the project root directory and run that command and then try `git push`ing

**Comment by nws321** [comment]
I followed the steps mentioned in the link you attached in your message and was able to push my commits. Thank you so much, really appreciate the help!
