### ISSUE TITLE
Issues with JUnit test for CI

### ISSUE THREAD

**Issue by xGladiate** [nus-cs2103-AY2425S1/forum#362]
I have issues with JUnit testing as locally, gradlew runs JUnit without any issues but using Java CI in github, there is the error of incorrect formatting of time for the method `testCorrectDateTimeOutput()`.

![image](https://github.com/user-attachments/assets/d05e2017-d3c5-41cb-a0c8-fa6e2eb41de2)
![image](https://github.com/user-attachments/assets/37ecd90e-b214-42ee-9f97-70e3efe91833)

**Comment by yadobler** [comment]
Might be related to #353

**Comment by xGladiate** [comment]
@yadobler Yep I have resolved it, thank you for the help! 
I have followed the solution from #277 to add the set time locale in the test class and it works.
