### ISSUE TITLE
Requesting help from Mac/Linux users to smoke test my jar file

### ISSUE THREAD

**Issue by JYL27** [nus-cs2103-AY2425S1/forum#364]
Hello, Windows user here looking for people to help smoke test my jar file on Mac/Linux platforms.

The jar file can be downloaded [here](https://github.com/JYL27/ip/releases/download/v0.2/colress.jar)
The user guide can be found [here](https://jyl27.github.io/ip/)

Thanks for your help!

**Comment by wes-w-z-h** [comment]
lgtm 👍

**Comment by JYL27** [comment]
@wes-w-z-h Thank you!

**Comment by arjun2598** [comment]
<img width="699" alt="image" src="https://github.com/user-attachments/assets/05f9cebb-d082-4dec-904d-44aa838e16e6">

I am using M1 MacBook Air. Chatbot is working smoothly, GUI looks nice 👍
