### ISSUE TITLE
Requesting help from Mac/Linux users to smoke test my jar file 

### ISSUE THREAD

**Issue by miuna9890** [nus-cs2103-AY2425S1/forum#365]
to download jar file [EmoteX.zip](https://github.com/user-attachments/files/17069752/EmoteX.zip)

i am only able to attach it as a zip file

user guide : https://miuna9890.github.io/ip/

Hi! pls help smoke test my file on mac/linux platformss
thank youu:)

**Comment by damithc** [comment]
@miuna9890 The UG link is incorrect.

**Comment by miuna9890** [comment]
my bad, it should work now

**Comment by wes-w-z-h** [comment]
Some issues on my end

Missing image and hello message (not sure if its intended):
<img width="420" alt="image" src="https://github.com/user-attachments/assets/a28e9071-c03c-4dd8-94bb-da61b800e81c">
`WARNING: Error loading image: jar:file:/Users/microgz/Downloads/EmoteX.jar!/images/Background.jpg`

**Comment by SKarthikeyan28** [comment]
Hi! I am a mac user and the jar file runs well on my mac, I can use the chatbot well! However i am running into the same issue of error loading background 
The GUI looks well designed too! All the best!

**Comment by miuna9890** [comment]
hii, hello message is only shown once 'hi' is entered. otherwise it will just be empty. I edited the file and there should not be any errors loading the background image now. Thankss @SKarthikeyan28 & @wes-w-z-h :))

**Comment by arjun2598** [comment]
<img width="398" alt="image" src="https://github.com/user-attachments/assets/32e8ca32-ab45-4a03-aa97-fbcc90a78593">

I am on M1 MacBook Air, no errors for me! GUI is very innovative and fun to use 😄
