### ISSUE TITLE
Where should we store the hard disk for Storage, and how to create a filePath for it. 

### ISSUE THREAD

**Issue by blackpanther9229** [nus-cs2103-AY2425S1/forum#367]
This is how I store the hard disk. I can run on Intelij, but when create a .jar folder and run it, there is some error with the filePath.

![image](https://github.com/user-attachments/assets/8339ff6d-12a2-4c30-af4d-93c2d56d39d2)

How should I fix it

**Comment by Incogdino** [comment]
I believe the resources folder within the jar file is immutable and read-only after the jar file is created. Thus trying to update it itself is already an error.

I would recommend just renaming `hardDisk` to

```java
private static final String hardDisk = "./Nah.txt";
```

This creates a text file relative to your jar file at the root folder.
