### ISSUE TITLE
Requesting smoke test on Windows

### ISSUE THREAD

**Issue by LynetteLeeSiYing** [nus-cs2103-AY2425S1/forum#370]
Requesting for smoke test on **Windows** environment

My jar file: 
[socchat.jar.zip](https://github.com/user-attachments/files/17069930/socchat.jar.zip)

User guide: https://lynetteleesiying.github.io/ip/

Thanks!!

**Comment by Incogdino** [comment]
Hi, I am on the window OS and your application works as expected!

**Comment by gohsl99** [comment]
You may want to indicate there is nothing in the list instead of current implementation when you run "list" on empty text file / first time running the program. The rest works fine.

**Comment by LynetteLeeSiYing** [comment]
@Incogdino , @gohsl99 Thank you!!
