### ISSUE TITLE
My jar file does not run

### ISSUE THREAD

**Issue by martout2002** [nus-cs2103-AY2425S1/forum#371]
I keep running into the same load and illegal state exception, but it seems like I have added the correct filepath, I even debugged it with a print statement to check if /view/MainWindow.fxml can be found in my main file (it can be found). Help me please, i'm at my wits end and chatgpt is not telling me how to fix this

<img width="1392" alt="Screenshot 2024-09-20 at 12 58 07 PM" src="https://github.com/user-attachments/assets/fe7267d2-19da-4839-a896-41221d9c8e71">

```java
FXMLLoader fxmlLoader = new FXMLLoader(getClass().getResource("/view/MainWindow.fxml"));
            // Initialize BrainRot instance


            String filePath = System.getProperty("user.home") + "/ip/data/brainRot.txt";
            brainRot = new BrainRot(filePath);
            AnchorPane root = fxmlLoader.load();
```

Below is my java tf build/libs/BrainRot.jar

<img width="774" alt="Screenshot 2024-09-20 at 1 00 10 PM" src="https://github.com/user-attachments/assets/db5c328d-c663-4b77-8a6a-ffd1af265628">

below is my build.gradle file
```java
plugins {
    id 'java'
    id 'application'
    id 'com.github.johnrengelman.shadow' version '7.1.2'
    id 'checkstyle'
}

checkstyle {
    toolVersion = '10.2'
}

repositories {
    mavenCentral()
}

dependencies {
    String javaFxVersion = '17.0.7'

    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'linux'

    testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.10.0'
    testRuntimeOnly group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.10.0'
}

test {
    useJUnitPlatform()

    testLogging {
        events "passed", "skipped", "failed"

        showExceptions true
        exceptionFormat "full"
        showCauses true
        showStackTraces true
        showStandardStreams = false
    }
}

application {
    // This should match the package and class name
    mainClass.set("brainrot.Main")
    sourceSets.main.resources.srcDirs = ['src/main/resources']
}

shadowJar {
    archiveBaseName = "BrainRot"
    archiveClassifier = null
    mergeServiceFiles()
}

run {
    standardInput = System.in
}

```

**Comment by damithc** [comment]
@martout2002 Does the code work when you run it in the IDE?

**Comment by myrilla12** [comment]
Hi, I had a similar issue whereby my application was running in the IDE but the jar was not. It turned out that there was a capital letter causing in my path name causing it to be incorrect. So maybe just make sure all your file paths are exactly word for word correct. If I'm not wrong the ...20 more at the end of the error message in the terminal might help you out and tell you exactly where the error is. So you could try directing the error message into a text file and see if it gives you more details.

**Comment by BunnyHoppp** [comment]
Hmm, in this case under application {} in build.gradle, does brainrot.Main initialise the GUI? Or do you have a launcher class?

**Comment by gerteck** [comment]
Hi, dropping in from your senior batch!

Do remember to follow the [tutorial](https://se-education.org/guides/tutorials/javaFxPart1.html) to be able to run the jar file first, before making your own edits! As @BunnyHoppp mentioned, you don't seem to have a launcher class. A quick fix referencing the tutorial should get your GUI working! 

![image](https://github.com/user-attachments/assets/d788ba8e-5eb5-46f5-8f57-1a9b22f59da7)

**Comment by martout2002** [comment]
Update:
I can run the code on my IDE, however, I seem to run into a problem whereby it is unable to load up the DaDuke.png and DaUser.png images. The problem is isolated to these lines. 


<img width="963" alt="Screenshot 2024-09-22 at 6 50 46 PM" src="https://github.com/user-attachments/assets/56bea459-2548-4524-bbec-13630ce25864">

It seems that it can load the images as long as I dont create a dialog box out of it, when I created a print statement and ran to debug, it showed that DaUser is successfully loaded

**Comment by martout2002** [comment]
I found the issue, it was my DialogBox.fxml file, it was named Dialogbox.fxml originally so the file could not be found. Thank you everyone for your help, my search is over after 2 days
