### ISSUE TITLE
Request for help with Smoke Test on Mac/Linux

### ISSUE THREAD

**Issue by Kitty-001** [nus-cs2103-AY2425S1/forum#372]
Need your help with smoke test! Thank you so much!

Download `jar` file from [here](https://github.com/Kitty-001/ip/releases/tag/A-UserGuide).

User Guide is [here](https://kitty-001.github.io/ip/)

**Comment by clarud** [comment]
I'm not using a Mac or Linux. But, everything seems to work well on Windows. I have tested all the commands and some possible error cases as well and have not caught any issues.

**Comment by foothaddeus** [comment]
Looks good! Just some minor formatting issues which I'm not sure if you want to address. Unfortunately I'm using Windows, as I don't use a Mac/Linux:

For the find function, there are no line breaks between the tasks being found, so everything appears in a single line:
![Screenshot 2024-09-20 142223](https://github.com/user-attachments/assets/4a06a53c-ee33-495c-b4ca-8ecfd31349c9)

Also, the month in your expected output for the "delete" function on your user guide seems to be appearing a bit strangely. Again, a minor issue:
![Screenshot 2024-09-20 142835](https://github.com/user-attachments/assets/f574d6df-f355-4869-b902-2721037c1eb1)

Lastly, just a suggestion but maybe you could add a link to your releases page in the "Quick Start" section in your user guide?

Other than that, everything seems to be working well!

**Comment by Kitty-001** [comment]
Thank you all.
