### ISSUE TITLE
Seeking clarification for tP's MVP

### ISSUE THREAD

**Issue by Elinengu** [nus-cs2103-AY2425S1/forum#374]
Good days Prof, for the MVP, are we supposed to set the MVP for our tP to be able to distinguished from others (ie. the minimum upgrade from AB3) or the minimum for it to work even it's just a normal address book, however if it's the latter our team thinks that it has been implemented by AB3 already.

**Comment by damithc** [comment]
@Elinengu Define your MVP irrespective of whether the feature are implemented in AB3. When we come to the stage of implementing the MVP, you can finish it up fast (if features don't need changing, probably just change the product name?) and continue to add other high priority features for the remaining time of that iteration.

**Comment by IanCheah** [comment]
Hi @damithc just to double confirm, for the command that we are supposed to put under each feature, are we expected to come up with something entirely new? Or we can reuse the commands from the original ab3? Say for example the add contact feature.

**Comment by damithc** [comment]
> Hi @damithc just to double confirm, for the command that we are supposed to put under each feature, are we expected to come up with something entirely new? Or we can reuse the commands from the original ab3? Say for example the add contact feature.

@IanCheah You may follow AB3. See below:

![image](https://github.com/user-attachments/assets/3a0b2aba-18a2-4842-bbe6-7bd4a033235e)
