### ISSUE TITLE
Unable to find text file for storage

### ISSUE THREAD

**Issue by TerenceWongsExtravaganza** [nus-cs2103-AY2425S1/forum#375]
Windows 11, Java 17

I am having issues when running JAR application of my iP as the storage functionality doesn't work.
The following code is my code for getting my storage file but it doesn't seem to recognize the file.
`
private String path = "/data/tasks.txt";
`

Giving the error
`\data\tasks.txt (The system cannot find the path specified)`

The following code is my code for getting an image but it works as intended
`
stage.getIcons().add(new Image("/images/DaDuke.png"));
`

I can't seem to tell how the bottom relative directory works but the one on top does not? Thanks for the help!

**Comment by winstonlimjy** [comment]
I think this might be the same as your problem: [here](https://github.com/nus-cs2103-AY2425S1/forum/issues/255#issuecomment-2342036264)

**Comment by damithc** [comment]
@TerenceWongsExtravaganza 
`new Image("/images/DaDuke.png")` is a special case in which the path needs to start  with `/`. Normally, if you want to specify 'relative to current folder', you can use either `./data/tasks.txt` or `data/tasks.txt`

**Comment by TerenceWongsExtravaganza** [comment]
> @TerenceWongsExtravaganza 
> `new Image("/images/DaDuke.png")` is a special case in which the path needs to start  with `/`. Normally, if you want to specify 'relative to current folder', you can use either `./data/tasks.txt` or `data/tasks.txt`

Hi prof thanks for the quick reply.
I apologise but i forgot to mention that i tried `./data/tasks.txt` and `data/tasks.txt` as well and it doesnt work 😭

**Comment by ritvi12** [comment]
@TerenceWongsExtravaganza maybe try to mention the sub folder under which it is in? like main/data/tasks.txt.

**Comment by damithc** [comment]
@TerenceWongsExtravaganza Also ensure that your code creates the required folders and the file if they are not found, as stated in `Level-7` requirements.

https://nus-cs2103-ay2425s1.github.io/website/se-book-adapted/projectDuke/index.html#level-7-save
