### ISSUE TITLE
Clarification regarding change of tP UI

### ISSUE THREAD

**Issue by BuffWuff1712** [nus-cs2103-AY2425S1/forum#377]
For the MVP that we have created, we are not planning to change the UI as of now. We would like to clarify if this is allowed for the upcoming MVP submission?

**Comment by damithc** [comment]
@BuffWuff1712 Yes, it is fine to not change the UI for the MVP, or even for the final version. UI changes are not compulsory.

**Comment by BuffWuff1712** [comment]
Noted, thanks prof!
