### ISSUE TITLE
Failing ip[run]

### ISSUE THREAD

**Issue by ruiming97** [nus-cs2103-AY2425S1/forum#378]
I'm getting this message when I try to use the built-in `ip[run]` on IntelliJ to run my GUI.
<img width="1239" alt="Screenshot 2024-09-20 at 3 48 43 PM" src="https://github.com/user-attachments/assets/d1771271-61b8-488f-91c0-f409788fa284">
However, my GUI can be run when I do `./gradlew run` in the terminal.
Below is the configuration of my `ip[run]`
<img width="820" alt="Screenshot 2024-09-20 at 3 55 13 PM" src="https://github.com/user-attachments/assets/2b195f32-1b8b-4e25-980b-a63cd8051888">

**Comment by SuhailLoya** [comment]
Hi, can I check if your Java JDK version and Gradle JVM Version are correctly set to Azul Zulu 17

Java JDK version is under File -> Project structure
Gradle JVM version is under Settings -> Build, Execution, Deployment -> Build Tools -> Gradle

**Comment by ruiming97** [comment]
> Hi, can I check if your Java JDK version and Gradle JVM Version are correctly set to Azul Zulu 17
> 
> 
> 
> Java JDK version is under File -> Project structure
> 
> Gradle JVM version is under Settings -> Build, Execution, Deployment -> Build Tools -> Gradle

Hi! sflr, this actually helps solve the problem! Thank you so much
