### ISSUE TITLE
Clarification about iP grading

### ISSUE THREAD

**Issue by MiloTruck** [nus-cs2103-AY2425S1/forum#379]
For my iP, I performed a hard reset to a previous commit and re-pushed my commits to fix issues with branches for certain levels. Since the dates in [my commit history](https://github.com/MiloTruck/ip/commits/master/) are now more recent, the [iP progress dashboard](https://nus-cs2103-ay2425s1.github.io/dashboards/contents/ip-progress.html) now shows red for weeks 4 and 5:

![body_language](https://github.com/user-attachments/assets/119ea6a6-013b-426a-a07d-014c051b8ee9)

Will this affect the grading for my iP? You can see that the tasks were completed in time for week 4 and 5 in [this commit history](https://github.com/MiloTruck/ip/commits/f05ab5af0229d40a457ad9875c8caefeaacbc2a6/), which was erased by the hard reset.

**Comment by damithc** [comment]
@MiloTruck It's fine. Don't worry about it.

**Comment by MiloTruck** [comment]
Thanks, closing this issue.
