### ISSUE TITLE
can't push to github from sourcetree

### ISSUE THREAD

**Issue by yikyak02** [nus-cs2103-AY2425S1/forum#38]
Hi! Everytime I try pushing my tags to github i get the following:
"git-credential sourcetree wants to use your confidential information stored in github.com Access key for {username} in your keychain"
i have attached an image which shows this.
does anyone know how to solve this issue? any help would be greatly appreciated!
![Screenshot 2024-08-23 at 2 01 34 AM](https://github.com/user-attachments/assets/778407b3-a2b1-4c5a-8838-e584cb00cc81)

**Comment by tata32000** [comment]
I had the same issue, what I did was to key in my MacBook password and click Always allow. 

Sometimes it will pop up twice, just key in the password again and it works for me.

**Comment by JoanneHing** [comment]
Same here, just key in your password for your macbook and you should be able to push your commit to github. You may also enable "Always allow" or otherwise you had to key in your password everytime you try to push :D

**Comment by damithc** [comment]
@yikyak02 Did you manage to solve the problem?
