### ISSUE TITLE
Where is the members directory

### ISSUE THREAD

**Issue by Feng1231** [nus-cs2103-AY2425S1/forum#380]
My team is doing the add-member-info task

The instruction says to add a MD file to the `members` directory. I only see a `team` directory.
Where is it? Or is the instructions not updated yet 😢

![image](https://github.com/user-attachments/assets/48240718-ec20-452b-a74a-a2522c32833c)

**Comment by damithc** [comment]
@Feng1231 This exercise is meant to be done using the repo https://github.com/se-edu/samplerepo-workflow-practice 
(i.e., not your tP repo). It's a stand-alone exercise, independent of the tP

**Comment by Feng1231** [comment]
I have overlooked that part. Sincere apologies. Thank you prof for clarifying!
