### ISSUE TITLE
Requesting for smoke tests for MacOS / Windows

### ISSUE THREAD

**Issue by winstonlimjy** [nus-cs2103-AY2425S1/forum#382]
Hi! Are there any kind souls, using MacOS or Windows, able to help test out my .jar file? 
[final-tanjiro.zip](https://github.com/user-attachments/files/17075889/final-tanjiro.zip) *NEWLY UPDATED 2131H*

The user guide is [here](https://winstonlimjy.github.io/ip/)

Much appreciated! <3

**Comment by gohsl99** [comment]
Any kind soul can help check [mine](https://github.com/gohsl99/ip/releases/download/A-Release/Blitz.jar) also, not sure if it can run on MacOS, my user guide is [here](https://gohsl99.github.io/ip/).
Thanks!

**Comment by damithc** [comment]
> Any kind soul can help check [mine](https://github.com/gohsl99/ip/releases/download/A-Release/Blitz.jar) also, not sure if it can run on MacOS, my user guide is [here](https://gohsl99.github.io/ip/).
> Thanks!

@gohsl99 Post your request as a separate issue.

**Comment by SamsonChew** [comment]
Hi, I am a Mac user. It works for me to enter the GUI interface, however it shows errror when I try to type some commands. Attached with the error.
<img width="689" alt="Screenshot 2024-09-20 at 9 01 45 PM" src="https://github.com/user-attachments/assets/9cd5b971-8ade-4a03-ad99-9e7dd689ac33">

**Comment by winstonlimjy** [comment]
> Hi, I am a Mac user. It works for me to enter the GUI interface, however it shows errror when I try to type some commands. Attached with the error. <img alt="Screenshot 2024-09-20 at 9 01 45 PM" width="689" src="https://private-user-images.githubusercontent.com/86278562/369413770-9cd5b971-8ade-4a03-ad99-9e7dd689ac33.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4Mzc2ODcsIm5iZiI6MTcyNjgzNzM4NywicGF0aCI6Ii84NjI3ODU2Mi8zNjk0MTM3NzAtOWNkNWI5NzEtOGFkZS00YTAzLWFkOTktOWU3ZGQ2ODlhYzMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDEzMDMwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5ZDJjMzAwOGQwNzMyYzRhYTgwYTZhZjFlMTFhZDQ0MGQxMTI5YjE5ZWU3ODdhNjI3MzRlYzI5YjE5ZjgxNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QcB2Q11zgjep3RQ18iWJR3oMvcP5NG8MdKOaIA4Vupk">

Thanks for the help! I have updated some stuff. If you have the time, could I trouble you to try again? Thanks!!

**Comment by BunnyHoppp** [comment]
Hi, I am a Windows user. Seems to work on Windows

![image](https://github.com/user-attachments/assets/15d26df7-0539-43e8-adda-2a1dca1f5523)


Seems to have some warnings, possibly wrong version of JavaFX, should be 17.0.7 instead of 22
![image](https://github.com/user-attachments/assets/f3d1f2ef-0026-47b5-8e2e-a7a0ac4eaa5d)

**Comment by meatyturtle** [comment]
windows user here, it works well with good error handling but i also get the same warning messages as BunnyHoppp above

**Comment by yimjianbing** [comment]
![image](https://github.com/user-attachments/assets/13f9b435-bd76-4926-9f17-58827d3d2202)
![image](https://github.com/user-attachments/assets/996b9234-2a34-410d-a344-d4d248d0e723)

Hey! I am a windows user, everything seems great on my end, I tried using an invalid date: 2019-99-99 and even though the bot didn't respond, it could still function afterwards so really good error handling!

All the commands work well and the GUI is pretty dope, only problem I faced was with this error, I am guessing you used scene builder to customise the GUI, and didn't change the JavaFX version back as scenebuilder will auto modify the JavaFX version in your .fxml files to use Java version 22 by default

Great job!

**Comment by winstonlimjy** [comment]
> ![image](https://private-user-images.githubusercontent.com/134612680/369459567-13f9b435-bd76-4926-9f17-58827d3d2202.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4NDY1NzcsIm5iZiI6MTcyNjg0NjI3NywicGF0aCI6Ii8xMzQ2MTI2ODAvMzY5NDU5NTY3LTEzZjliNDM1LWJkNzYtNDkyNi05ZjE3LTU4ODI3ZDNkMjIwMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMFQxNTMxMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZDNmZjgxNWQwMTI5NWRkNDYwOGZiYmNlNTllZDljYWZmYzVkOTE2OWQ4MjViNTQ3ZjBhZjc1YTFhZjE1NjZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.bHqZZBHtPf1hwHkACHBPTH3kQ-n5IxPyASiuAOe5sJc) ![image](https://private-user-images.githubusercontent.com/134612680/369459642-996b9234-2a34-410d-a344-d4d248d0e723.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4NDY1NzcsIm5iZiI6MTcyNjg0NjI3NywicGF0aCI6Ii8xMzQ2MTI2ODAvMzY5NDU5NjQyLTk5NmI5MjM0LTJhMzQtNDEwZC1hMzQ0LWQ0ZDI0OGQwZTcyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMFQxNTMxMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOWEzNDhjNGRiOGMzMTcwYzFhMGUxMGVmMzExNjVhNmQ4YTgwMTBlODYzODI3Nzc2YzcyOTdkNmY0NjI0YzZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.IUt-NjIpVQRnrvfA-h5jZ29-wRPSU04QFVdGkY50Eg0)
> 
> Hey! I am a windows user, everything seems great on my end, I tried using an invalid date: 2019-99-99 and even though the bot didn't respond, it could still function afterwards so really good error handling!
> 
> All the commands work well and the GUI is pretty dope, only problem I faced was with this error, I am guessing you used scene builder to customise the GUI, and didn't change the JavaFX version back as scenebuilder will auto modify the JavaFX version in your .fxml files to use Java version 22 by default
> 
> Great job!

Thanks for the help man. I tried to replicate the problem on my side, but i cant replicate it. Some magic is happening here.

![image](https://github.com/user-attachments/assets/982e18f4-f111-408e-aa07-c3f0f3e43b33)

**Comment by SamsonChew** [comment]
> > Hi, I am a Mac user. It works for me to enter the GUI interface, however it shows errror when I try to type some commands. Attached with the error. <img alt="Screenshot 2024-09-20 at 9 01 45 PM" width="689" src="https://private-user-images.githubusercontent.com/86278562/369413770-9cd5b971-8ade-4a03-ad99-9e7dd689ac33.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4Mzc2ODcsIm5iZiI6MTcyNjgzNzM4NywicGF0aCI6Ii84NjI3ODU2Mi8zNjk0MTM3NzAtOWNkNWI5NzEtOGFkZS00YTAzLWFkOTktOWU3ZGQ2ODlhYzMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDEzMDMwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5ZDJjMzAwOGQwNzMyYzRhYTgwYTZhZjFlMTFhZDQ0MGQxMTI5YjE5ZWU3ODdhNjI3MzRlYzI5YjE5ZjgxNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QcB2Q11zgjep3RQ18iWJR3oMvcP5NG8MdKOaIA4Vupk">
> 
> Thanks for the help! I have updated some stuff. If you have the time, could I trouble you to try again? Thanks!!

The chatbot works well from my side now!!! Well done

**Comment by winstonlimjy** [comment]
> > > Hi, I am a Mac user. It works for me to enter the GUI interface, however it shows errror when I try to type some commands. Attached with the error. <img alt="Screenshot 2024-09-20 at 9 01 45 PM" width="689" src="https://private-user-images.githubusercontent.com/86278562/369413770-9cd5b971-8ade-4a03-ad99-9e7dd689ac33.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4Mzc2ODcsIm5iZiI6MTcyNjgzNzM4NywicGF0aCI6Ii84NjI3ODU2Mi8zNjk0MTM3NzAtOWNkNWI5NzEtOGFkZS00YTAzLWFkOTktOWU3ZGQ2ODlhYzMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDEzMDMwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5ZDJjMzAwOGQwNzMyYzRhYTgwYTZhZjFlMTFhZDQ0MGQxMTI5YjE5ZWU3ODdhNjI3MzRlYzI5YjE5ZjgxNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QcB2Q11zgjep3RQ18iWJR3oMvcP5NG8MdKOaIA4Vupk">
> > 
> > 
> > Thanks for the help! I have updated some stuff. If you have the time, could I trouble you to try again? Thanks!!
> 
> The chatbot works well from my side now!!! Well done

Thanks brother
