### ISSUE TITLE
Requesting for smoke tests for MacOS / Linux

### ISSUE THREAD

**Issue by xGladiate** [nus-cs2103-AY2425S1/forum#383]
Could anyone help me to smoke test my application?

Here is the zip containing the jar file: [xbot.zip](https://github.com/user-attachments/files/17082855/xbot.zip)

Here is the link to the user guide [user guide](https://xgladiate.github.io/ip/)!

Thank you!!

**Comment by VedJoshi** [comment]
LGTM! I am a windows user, I couldn't find any obvious bugs, the UI is very refined and the window resizes without issue. No errors in the terminal also.

![image](https://github.com/user-attachments/assets/a3034b20-c5a6-4c98-bfc4-4a92eeab2aa3)

![image](https://github.com/user-attachments/assets/069eadfc-182c-4a46-8c06-d49af6b738f7)

**Comment by myrilla12** [comment]
I am using M2 Apple Silicon Macbook air. It runs well on my OS! GUI is very cute too :)

**Comment by arjun2598** [comment]
<img width="398" alt="image" src="https://github.com/user-attachments/assets/ac4ba8bd-635e-45ef-b948-ec3f89446125">

I am on M1 MacBook Air. The GUI looks very nice! Everything seems to be running smoothly, no issues for me 👍

**Comment by Quasant** [comment]
<img width="606" alt="image" src="https://github.com/user-attachments/assets/c6ff4db6-089a-4765-99b1-42fc46188037">

Looks very nice! Very small nits but deadline and event tasks can have an empty descriptor.

**Comment by annabellekk** [comment]
I'm using Mac book air with Intel chip, lgtm. No major issues found, works smoothly and the UI is cute!
