### ISSUE TITLE
Requesting smoke test (any platform)

### ISSUE THREAD

**Issue by gohsl99** [nus-cs2103-AY2425S1/forum#384]
Anyone free can help to test if this [jar file](https://github.com/gohsl99/ip/releases/download/A-Release/Blitz.jar) able to run on your system and run any commands as you wish ([here](https://gohsl99.github.io/ip/) is the user guide).
Thanks.

**Comment by travisim** [comment]
it works, tested on M2 pro macos Sequoia 15.2
<img width="551" alt="image" src="https://github.com/user-attachments/assets/07ad562e-bf32-4470-8c39-20bfa4e0ac0f">

**Comment by gohsl99** [comment]
> it works, tested on M2 pro macos Sequoia 15.2 <img alt="image" width="551" src="https://private-user-images.githubusercontent.com/64481469/369441065-07ad562e-bf32-4470-8c39-20bfa4e0ac0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4NDMyMDMsIm5iZiI6MTcyNjg0MjkwMywicGF0aCI6Ii82NDQ4MTQ2OS8zNjk0NDEwNjUtMDdhZDU2MmUtYmYzMi00NDcwLThjMzktMjBiZmE0ZTBhYzBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDE0MzUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyYWE1NmM1M2FkOTkxMjZlYTJjZDM1NjEzNjQ3ZTlmZWYxZTg0Zjc1ZWQ5NDRhMTViMDhiMGU5OWFkZmVhYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.foXQU7dfjGNySmxqsMVxUTCAv5jVH0mp7YsCBE_1GDg">

Nice, thanks for the help!

**Comment by BunnyHoppp** [comment]
Seems to work on windows too!
![image](https://github.com/user-attachments/assets/fb9ce8a0-2ec4-48f8-a85b-6e175c1079a9)

**Comment by gohsl99** [comment]
> Seems to work on windows too! ![image](https://private-user-images.githubusercontent.com/145633434/369450359-fb9ce8a0-2ec4-48f8-a85b-6e175c1079a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4NDUwNTMsIm5iZiI6MTcyNjg0NDc1MywicGF0aCI6Ii8xNDU2MzM0MzQvMzY5NDUwMzU5LWZiOWNlOGEwLTJlYzQtNDhmOC1hODViLTZlMTc1YzEwNzlhOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMFQxNTA1NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MjFlYjJjODhiNTEyYzdlZDc2M2QwMzk1NWYwNmE2MGJmYTNiNTM3ZWVjZjNjZDk2N2UxNGVmYmU5NjVkN2RhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.sslmn_tYG_tamFki6R2gHgvTiDNtJjhxN50oI8kHg_c)

Okay nice, thank you!

**Comment by nws321** [comment]
Works on m1 Mac Sonoma 14.6.1
<img width="548" alt="Screenshot 2024-09-21 at 1 15 26 AM" src="https://github.com/user-attachments/assets/85609d43-ae00-4527-b62e-6de58cd05192">
