### ISSUE TITLE
Requesting help for smoke test

### ISSUE THREAD

**Issue by Jalenleeruixian** [nus-cs2103-AY2425S1/forum#386]
Hi can I check that for Mac users the correct java version is Azulu 17?  Can anyone help me run a test on my jar file? Thank you.
You can find it here https://github.com/Jalenleeruixian/ip/releases/tag/A-Release. Any help is much appreciated.

**Comment by travisim** [comment]
yes, i used that
<img width="395" alt="Screenshot 2024-09-20 at 10 14 42 PM" src="https://github.com/user-attachments/assets/12f21446-f5a8-492c-bcad-e2d0bd430fe4">

**Comment by travisim** [comment]
it works, tested on M2 pro macos Seqouia 15.2
<img width="399" alt="image" src="https://github.com/user-attachments/assets/aaa84b75-fbe0-49b7-983a-975069d44c28">

**Comment by BunnyHoppp** [comment]
It works on mine, windows

![image](https://github.com/user-attachments/assets/c55d3409-ac5f-43cd-99be-b17ec264c8c2)

**Comment by Jalenleeruixian** [comment]
Thank you guys so much!
