### ISSUE TITLE
Issue with running my .jar file on windows

### ISSUE THREAD

**Issue by WinstonJin** [nus-cs2103-AY2425S1/forum#388]
Hi I am a Mac user and all my Mac friends can run my Winde.jar on their macbooks no issue but my Windows friends have an issue.

Here are the several error messages from them
![photo_2024-09-20 22 21 00](https://github.com/user-attachments/assets/97bab7bb-28e2-4bfe-84be-e8e15095bdd1)

![photo_2024-09-20 22 21 08](https://github.com/user-attachments/assets/95e701ed-28b6-4c37-85b6-803e75801888)

My .jar file can be found in my release on my github page (https://github.com/WinstonJin/WindeBot)

Thank you!

**Comment by Incogdino** [comment]
My wild guess after looking at your `build.gradle` file is that the dependencies for javaFX for windows (and linux) were not included. 

```java
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'linux'
```

Try adding these, to your dependencies inside `build.gradle` to support windows and linux.

**Comment by WinstonJin** [comment]
Oh yea thats the issue thanks!
