### ISSUE TITLE
Markdown Formating Issue on github.io

### ISSUE THREAD

**Issue by amoschee** [nus-cs2103-AY2425S1/forum#389]
Hi I encountered a weird issue where my markdown is not being formatted correctly in my github.io/ip/ page even though the formatting works correct on my README.md. Below are the screenshots of README and github.io page, my guess is the numbering might have messed up the markdown but I'm not too sure:

[README](https://github.com/amoschee/ip/blob/master/docs/README.md#listing-tasks)
![image](https://github.com/user-attachments/assets/f9e0a23b-aa78-434f-9134-3e8a0919b861)

[github.io page](https://amoschee.github.io/ip/#listing-tasks)
![image](https://github.com/user-attachments/assets/98035fbf-72b6-49c9-9dcd-c27da606916e)

Thank you!

**Comment by damithc** [comment]
Try this indentation (i.e., indent the code block by 2 spaces, not 4 spaces):
``````
- **Output**:
  ```
  Got it. I've added this task:
    [T][ ] Read a book
  Now you have 1 task in the list.
  ```
``````

**Comment by amoschee** [comment]
works now, thanks prof!
