### ISSUE TITLE
Which commit to tag when performing different commits on a same feature/IP Level task

### ISSUE THREAD

**Issue by vicelyav** [nus-cs2103-AY2425S1/forum#39]
Hi everyone, I made some revisions on my code for a particular level feature (e.g. automated UI testing or other levels). I have tagged the earliest commit of that level feature. After I made a newer commit, do I simply add the same tag to the latest commit or do I need to remove the tag from the older commits? Any help appreciated

If this question is not appropriate for this topic, do let me know.

**Comment by JoanneHing** [comment]
In the website they mentioned like this
"Adding a git tag in the iP is a self-declaration that you think you are done with the iP increment. We take your word for it. We don't check the code to see if you have actually done the said increment. Therefore, it is just a mechanism for you to self-declare progress and for us to monitor those progress declarations."

So I think it doesn't not affect much if your initial tag is at the commit that meet the requirement stated in the website for the particular level. I think there is no harm by moving the tag to your latest update, but it could better to remove the previous one so you won't end up with several tag if you have multiple updates/revisions. Or maybe could go with Level-1.1, Level-1.2 tags. This just from my understanding of the usage of tags from the 2103 website and other resources, hopefully my opinion is helpful :)

**Comment by matchastack** [comment]
Hi, you may refer to issue  #21. I think it is not necessary to move the tag.

However, if you do wish to do so, you may do
``` 
git tag -d [tag]
git tag [tag]
```

you will need to delete the original tag since it is not permitted to have the same tag on multiple commits.

**Comment by vicelyav** [comment]
I see that it has been addressed in the previous issue, thank you for alerting me. I will now close this issue!

**Comment by damithc** [comment]
Answers from @liauzhanyi and @JoanneHing are on the right track. Thanks both 💯
