### ISSUE TITLE
Requesting Help for Smoke Test

### ISSUE THREAD

**Issue by JoanneHing** [nus-cs2103-AY2425S1/forum#390]
I am using a M2 Mac device, would appreciate a lot if any window or linux user could help me test the project on their OS!

Here is my [project](https://github.com/JoanneHing/ip/releases/tag/A-Release) and my [User Guide](https://github.com/JoanneHing/ip/blob/master/docs/README.md)

**Comment by BunnyHoppp** [comment]
Seems good on Windows. I really like your bot's personality, good job :)
![image](https://github.com/user-attachments/assets/79fc6bdd-c41a-41c5-b52f-fb5baca9675d)

Although there are some warnings, it seems that your javafx version is 22 instead of 17.0.7
![image](https://github.com/user-attachments/assets/9ccb66b1-e02b-41c2-bd3b-1bf28a978931)

**Comment by MAOXIONGKAI** [comment]
![image](https://github.com/user-attachments/assets/795db1fe-75ff-4a2a-bc17-7b28ea025efe)
Can open on windows, but I am having issue retrieving my save tasks. Every time I created something, close the application and open again, the list task command only tells me that there's no quest at all...
I am not sure what is going on but there's no folder/files created in the folder where I put the jar file....

**Comment by arjun2598** [comment]
<img width="398" alt="Screenshot 2024-09-21 at 12 25 14 AM" src="https://github.com/user-attachments/assets/8314f63a-90d4-46a1-a99a-e9d671716009">

I'm on M1 Mac, the commands seem to be working fine and the GUI looks great! 
However, I also face an issue with saving and loading of tasks. The tasks added from my previous run can't seem to be loaded in the subsequent run. There doesn't seem to be a save file created by the program, maybe this is the issue?

**Comment by SlothyCat** [comment]
![image](https://github.com/user-attachments/assets/52fb7457-991d-4b7e-9a40-ae310fa2d8f2)

Hi I am a Windows User, the GUI is cute!! However, I think there is some minor issue in your deadline task creation, it does not seem to accept both the date time formats that I have provided. Could it be a wrong prompt from me, I believe it follows the dd/MM/yyyy HHmm format though.

**Comment by JoanneHing** [comment]
> Seems good on Windows. I really like your bot's personality, good job :)
> Although there are some warnings, it seems that your javafx version is 22 instead of 17.0.7 ![image](https://private-user-images.githubusercontent.com/145633434/369476289-9ccb66b1-e02b-41c2-bd3b-1bf28a978931.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MDU2ODQsIm5iZiI6MTcyNjkwNTM4NCwicGF0aCI6Ii8xNDU2MzM0MzQvMzY5NDc2Mjg5LTljY2I2NmIxLWUwMmItNDFjMi1iZDNiLTFiZjI4YTk3ODkzMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMVQwNzU2MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNjA3MDNiODkwOGViN2ZkNWE2N2MxMzYzMWQxMWViMzM5MWI0YWEyYjc5MmFmMGM1Yzg1OTVkOTliOTdjZTY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.IF_lrIOLKGVppQ7FNJHaqogsy9RPqviFla1v5WX-jxs)

Hi, thanks for helping of testing out my iP! For the error I think can be ignored as this had been mentioned in the textbook before
<img width="946" alt="Screenshot 2024-09-21 at 3 56 13 PM" src="https://github.com/user-attachments/assets/65488519-fbd6-44ba-bb6c-2421de0de521">
But still thanks for mentioning it!

**Comment by JoanneHing** [comment]
@MAOXIONGKAI @arjun2598 Thank you for letting me know there is a bug on saving the task to the hard disk! I had updated a new jar file, hopefully it fix the error now!

**Comment by JoanneHing** [comment]
@SlothyCat Thanks for helping to test out! But the error is actually indicating that the deadline was invalid because the date is earlier than today's date, I set that as an invalid date! So if you change it to date later than today it should work! :D
