### ISSUE TITLE
Git Standard label shows up red

### ISSUE THREAD

**Issue by Anvita2110** [nus-cs2103-AY2425S1/forum#391]
![image](https://github.com/user-attachments/assets/1953fb13-29ad-4baa-9102-d477d46da35d)

What am I supposed to do here so that the Git Standard is completed(green)? 
I have already put full commit messages, so was I supposed to create a branch for it and do that?

**Comment by arjun2598** [comment]
I think this is referring to the requirement for the subject of the latest 5 commits of your ip to follow the standard given in the textbook, which are 1) Use imperative mood, 2) Capitalise first letter, 3) Don't end subject line with a period. If your recent commits don't follow these guidelines, maybe you could add minor edits and commit them with appropriate commit messages. I also don't think you need the full commit messages for this git standard label to turn green.

**Comment by damithc** [comment]
@Anvita2110 You can click on the `details` link (shown in your screenshot) to find more details of each item.


> I think this is referring to the requirement for the subject of the latest 5 commits of your ip to follow the standard given in the textbook, which are 1) Use imperative mood, 2) Capitalise first letter, 3) Don't end subject line with a period. If your recent commits don't follow these guidelines, maybe you could add minor edits and commit them with appropriate commit messages. I also don't think you need the full commit messages for this git standard label to turn green.

That's correct. Thanks @arjun2598

**Comment by Anvita2110** [comment]
Thank you both, @damithc and @arjun2598, for your input. 

However, I need clarification on how to edit an older commit. It seems like this might involve rebasing, but I'm a bit uncertain about the process and concerned about the potential impact on my entire project. 

Could you please provide detailed steps for rebasing? Alternatively, would it be better to leave the commit messages as it is?

**Comment by JoanneHing** [comment]
@Anvita2110 Hi you may refer to this issue #276 for editing commit message! Or you can make small changes and update your latest 5 commit to follow the git standard referring to this #312

**Comment by damithc** [comment]
> Or you can make small changes and update your latest 5 commit to follow the git standard referring to this #312

Yup, no need to edit past commits.

**Comment by Anvita2110** [comment]
Ok Thankyou so much @JoanneHing @damithc @arjun2598 for your inputs.

I have edited my commits using `git commit --amend -c <commitID>`.
The only downside to it is that our branch gets diverged then we have to do:
* git pull origin master
* git push (Introducing 2 more commits including the updated commit message).
