### ISSUE TITLE
Wanting to update my release after deadline

### ISSUE THREAD

**Issue by rahula1008** [nus-cs2103-AY2425S1/forum#393]
So I note that the email from the admin bot said that we can update our release/make a new release by next week, for instance, if we notice a bug. 

1. If we update our release, does that mean just change the jar file? If I do so, the jar will file be my latest version, but I can't change the source code.
2. If we make a whole new release, do we need to delete the tag from the old release, and move it to the new release?

**Comment by damithc** [comment]
@rahula1008 You can change anything, and do any number of releases. 
No need to move the tag. We take the latest release irrespective of the tag.

**Comment by rahula1008** [comment]
Understood, thank you prof!
