### ISSUE TITLE
Do I need to update a new version of release after I fix the bugs?

### ISSUE THREAD

**Issue by JoanneHing** [nus-cs2103-AY2425S1/forum#395]
As mention in the title, I make some updates for the iP after receiving feedback from the peer about some bugs, do I need to create a new release or I just need to push the commit to the master branch?

**Comment by damithc** [comment]
@JoanneHing You need to create a new release or update the current release with the new jar file. Update the master branch as well.

**Comment by JoanneHing** [comment]
> @JoanneHing You need to create a new release or update the current release with the new jar file. Update the master branch as well.

Thank you prof for clarifying, the naming for the new release can be anything? like `v0.3` or should i replace the `v0.2` release and retag it?

**Comment by damithc** [comment]
@JoanneHing You can use any name for the release. We take the latest release irrespective of the name.

**Comment by JoanneHing** [comment]
Alright thank you prof for the clarification!
