### ISSUE TITLE
💎 Runtime component missing when running on Windows 

### ISSUE THREAD

**Issue by Wxy2003-xy** [nus-cs2103-AY2425S1/forum#396]
https://stackoverflow.com/questions/56894627/how-to-fix-error-javafx-runtime-components-are-missing-and-are-required-to-ru

I kept getting 
```
Error: JavaFX runtime components are missing, and are required to run this application
```
when launching my app developed on macOS on windows, despite having followed the build.gradle settings exaclty. Upon further inspection it appeared although i have javafx.controls included in the dependency list, it's not included in the fatjar when running clean shadowjar, for some unknown reason. 

The solution (or hack) to bypass this problem as mentioned in the article is to have an extra starter class to avoid starting from the original main class that extends Application. 

Not sure if why this would work nor how did i encounter such issue in the first place, but here it is. Hope it helps.

**Comment by Gra7ityIC3** [comment]
> Not sure if why this would work nor how did i encounter such issue in the first place, but here it is. Hope it helps.

The reason for the missing components was mentioned in [AB3](https://github.com/se-edu/addressbook-level3/blob/4eb130f32ef1a3b492ce25c741fb06defd26fad4/src/main/java/seedu/address/Main.java#L8-L23):

```java
/**
 * The main entry point to the application.
 *
 * This is a workaround for the following error when MainApp is made the
 * entry point of the application:
 *
 *     Error: JavaFX runtime components are missing, and are required to run this application
 *
 * The reason is that MainApp extends Application. In that case, the
 * LauncherHelper will check for the javafx.graphics module to be present
 * as a named module. We don't use JavaFX via the module system so it can't
 * find the javafx.graphics module, and so the launch is aborted.
 *
 * By having a separate main class (Main) that doesn't extend Application
 * to be the entry point of the application, we avoid this issue.
 */
```

You can view more details of this fix in this [commit](https://github.com/se-edu/addressbook-level3/commit/12bb91903e71ea1109e04f7369c2169f1c7be39a).
