### ISSUE TITLE
Java version 21 to 17

### ISSUE THREAD

**Issue by tyxiangs** [nus-cs2103-AY2425S1/forum#397]
I have made a lot of configuration, changing my java version from 21 to 17. It ended up when I type command java -version, it still shows my java ver was 17. How to solve it
![Screenshot 2024-09-21 211729](https://github.com/user-attachments/assets/80202fdc-0c10-4fe2-ab4a-21e088ad0bd8)
![Screenshot 2024-09-21 211645](https://github.com/user-attachments/assets/95fda023-aee1-4d17-bf2e-99d0097b5b33)
![Screenshot 2024-09-21 211655](https://github.com/user-attachments/assets/e7cd11c9-b5e3-459d-a917-39b005aec50c)
![Screenshot 2024-09-21 212434](https://github.com/user-attachments/assets/d05556eb-4e54-45ff-88e9-577a52582f4a)

**Comment by Incogdino** [comment]
`java -version` refers to the one that is set in your environment variables, not IntelliJ.

You need to change your environment variables to switch to a different java version. Please refer to [this](https://www.java.com/en/download/help/path.html) faq to see how you can change  your java version.

**Comment by damithc** [comment]
Another guide we recently added on this aspect https://se-education.org/guides/tutorials/javaInstallationWindows.html#switching-between-java-versions
