### ISSUE TITLE
Requesting help for smoke test

### ISSUE THREAD

**Issue by vicelyav** [nus-cs2103-AY2425S1/forum#398]
Hi everyone, I would like to ask for your kind help to smoke-test my jar file:
https://github.com/vicelyav/ip/releases/tag/A-Release

The user guide is here:
https://vicelyav.github.io/ip/

If you encounter any issues, please help screenshot and send it here if you can . Thank you!

**Comment by lithops-zty** [comment]
Windows user here. The GUI opens up fine on my laptop and all the features work as intended! I noted some edge cases that could be handled more elegently:
- A more user-friendly message can be displayed for wrong date format;
- Currently having slashes in the description will lead to an exception message being displayed. Maybe you can display 'please remove slashes in your task description' instead?

By the way, there's a misplaced slash in the deadline command format section of the user guide.

That said, overall it's an excellent product!

**Comment by vicelyav** [comment]
@lithops-zty Thank you for testing!  By task description with slashes is it something like: todo /borrow book?

**Comment by lithops-zty** [comment]
@vicelyav Yes, I think you can explicitly disallow it if your parser was not designed to handle this.
