### ISSUE TITLE
Are we supposed to fork the original tp repo, or the newly created team tp repo?

### ISSUE THREAD

**Issue by zzzlou** [nus-cs2103-AY2425S1/forum#399]
Hi, I am a bit confused here.
The tp task for week 6 says that:
```
Fork the tp repo to your personal GitHub account.
```

I forked the **team tp repo** but the dashboard failed to detect it. So I am wondering if there is a misunderstanding here. Is it actually referring to the **original tp repo**  or **team tp repo**? Thanks!

**Comment by Incogdino** [comment]
Your tp repo seemed like it was forked from the original tp project repo though. 

I think you should fork the tp repo from your **team organization** instead.
