### ISSUE TITLE
Bug: Linked Article on course site is dead

### ISSUE THREAD

**Issue by pradyuprasad** [nus-cs2103-AY2425S1/forum#40]
## Issue
In the [course notes for week 3](https://nus-cs2103-ay2425s1.github.io/website/schedule/week3/topics.html#W3-1) there is a broken link to the [external site](https://initialcommit.com/blog/what-is-git-head) mentioned. Specifically in this section

> To learn a bit more about how labels such as master and HEAD work, you can refer to [this article](https://initialcommit.com/blog/what-is-git-head).

I have tried this site on 2 browsers (chrome and safari), and am unable to access it. Additionally, a curl command to it also gives a 500 HTTP status code
```zsh
pradyu@Pradyumnas-MacBook-Air ~> curl https://initialcommit.com/blog/what-is-git-head
{"timestamp":"2024-08-23T08:30:03.668+00:00","status":500,"error":"Internal Server Error","path":"/blog/what-is-git-head"}⏎                                                                                     pradyu@Pradyumnas-MacBook-Air ~> 
```
## Proposed fix
We should rather link to an archived version of it using [this link](https://web.archive.org/web/20231002150108/https://initialcommit.com/blog/what-is-git-head) or use an alternative resource like [this one](https://jvns.ca/blog/2024/03/08/how-head-works-in-git/)

**Comment by damithc** [comment]
Thanks for the bug report, and taking time to suggest a fix @pradyuprasad 💯 
For the time being, I've pointed it to https://blog.git-init.com/what-is-head-in-git/
