### ISSUE TITLE
Issue in making Project Website

### ISSUE THREAD

**Issue by Anvita2110** [nus-cs2103-AY2425S1/forum#400]
### * just merge our master branch to upstream master branch
![image](https://github.com/user-attachments/assets/3086d698-cdc0-42ce-8d27-af16ccd9085f)

**Comment by JoanneHing** [comment]
Are you mentioning about product website for the iP? Suppose you can follow this guide and you should be able to view your product README.md at the link `https://{your user name}.github.io/{repo name}`. Hope I understand your question correctly.

<img width="733" alt="Screenshot 2024-09-21 at 10 47 56 PM" src="https://github.com/user-attachments/assets/40a09a9b-1ad4-46bf-bac5-f55bf6607b55">

**Comment by weijianwong** [comment]
There should already be a switch-docs-to-markbind branch in the repo so you just have to fetch it and merge it into master. Pushing the master branch up should run codecov assuming you have set it up correctly. Hope this helps!

**Comment by damithc** [comment]
> There should already be a switch-docs-to-markbind branch in the repo so you just have to fetch it and merge it into master. Pushing the master branch up should run codecov assuming you have set it up correctly. Hope this helps!

@Anvita2110 you can follow @weijianwong's suggestion, if your team wants to use MarkBind. We have provided guides for both Jekyll and MarkBind.

**Comment by Anvita2110** [comment]
@weijianwong @damithc Thankyou for your inputs, it is solved now as codecov was not correctly set up.
