### ISSUE TITLE
Enquiry about submission of feature specification

### ISSUE THREAD

**Issue by Elinengu** [nus-cs2103-AY2425S1/forum#401]
Good days Prof, may I know if we are supposed to have 1 person to submit the pdf file for feature specification for the whole team or everyone needs to submit the same pdf file?

**Comment by Incogdino** [comment]
![image](https://github.com/user-attachments/assets/0d235249-d33c-4235-9460-aecc2d003b40)

It is one person for the whole team according to this [image](https://nus-cs2103-ay2425s1.github.io/website/schedule/week6/project.html) from the project tab
