### ISSUE TITLE
Please Help Smoke Test IP

### ISSUE THREAD

**Issue by AbdulrahmanAlRammah** [nus-cs2103-AY2425S1/forum#402]
Please help smoke test my ip. I used windows would appreciate linux and MAC users. Feel free to also give feedback on user guide format and if description is enough. 

User guide: https://abdulrahmanalrammah.github.io/ip/ 
Jar file: https://github.com/AbdulrahmanAlRammah/ip/releases/tag/A-Release

Thanks.

**Comment by SlothyCat** [comment]
<img width="401" alt="Screenshot 2024-09-22 at 1 05 32 PM" src="https://github.com/user-attachments/assets/6ae767cf-26a6-4ae3-84ac-4c88032bdedb">

Hi there, I used a Mac to test out your JAR file. Your README is informative and you went through the various functions. Just a little format issue for the tagging. As seen in the screenshot, I was able to tag without the # and it looked like i just added onto the previous tag. Not sure if this is something you may want to refine but overall I think the bot is working and nice!!

**Comment by weijianwong** [comment]
<img width="401" alt="Screenshot 2024-09-22 at 1 15 02 PM" src="https://github.com/user-attachments/assets/5e1b5c71-b71c-47bd-85d7-b509e0d84bb8">
Hi there, there seems to be a bug when i enter events with /to first before /from. Like in screenshot above. But other than that, it looks very good!

**Comment by AbdulrahmanAlRammah** [comment]
@damithc regarding the point by @weijianwong above are we supposed to allow /to before /from in creating the event task. My bot is meant to only account for the case where before precedes to. Do I have to go back and change this?

Thank you @weijianwong for testing and bringing up this point.

**Comment by AbdulrahmanAlRammah** [comment]
@SlothyCat thank you for smoke testing. Yeah for the tag I don't throw an error when # isn't included. In my mind some tags could be something like 'FYI: Important' or 'note:' so it is up to the user discretion to include the #. I think this should be fine, but I can see how there can be confusion.

**Comment by damithc** [comment]
> @damithc regarding the point by @weijianwong above are we supposed to allow /to before /from in creating the event task. My bot is meant to only account for the case where before precedes to. Do I have to go back and change this?

It is up to you. You can make the app as user-friendly error-resistant as you want but there is no specific requirement from our side.
