### ISSUE TITLE
Pages build and deployment problem

### ISSUE THREAD

**Issue by SherChew27** [nus-cs2103-AY2425S1/forum#403]
I recently received an email from github that some jobs were not successful. Upon clicking the link, this is what I saw.
<img width="1800" alt="Screenshot 2024-09-22 at 2 23 47 AM" src="https://github.com/user-attachments/assets/7a54d157-4fe6-4b02-b657-406926bf8780">
<img width="1799" alt="Screenshot 2024-09-22 at 2 23 37 AM" src="https://github.com/user-attachments/assets/b8a0883e-fbe7-4e0c-805d-91e20337f6df">

I was initially able to see my image on the page but now it is no longer displayed

<img width="1002" alt="Screenshot 2024-09-22 at 2 24 30 AM" src="https://github.com/user-attachments/assets/88cc563f-bb8f-4418-8e29-067d9a381c07">

Is anyone able to advise me on what i should do to rectify this problem?

**Comment by SherChew27** [comment]
I tried to push another commit and the latest workflow completes, but the problematic one is still there. I have double checked that the image path is correct, but it does not display on the page

**Comment by Gra7ityIC3** [comment]
> I have double checked that the image path is correct, but it does not display on the page

Your image path is wrong. It should be just `Ui.png` instead of `/docs/Ui.png`:
```markdown
![Example of bellroy in use](Ui.png)
```

**Comment by SherChew27** [comment]
Thanks! I've edited it and the image shows on the page now. However, regarding the queued workflow that is not running, can I just ignore that?

**Comment by yadobler** [comment]
> However, regarding the queued workflow that is not running, can I just ignore that?

Yes, it's an old run that got queued but didn't manage to run or get automatically  cancelled even though subsequent jobs have already been successfully completed. You can click the top right corner button and _Cancel Workflow_.
