### ISSUE TITLE
Requesting help from Mac/Linux users to smoke test my jar file

### ISSUE THREAD

**Issue by leroytan** [nus-cs2103-AY2425S1/forum#404]
Please help smoke test my ip!
Would appreciate linux and MAC users as I use windows.
Feel free to give any other feedback (e.g. user guide/user interface)

User guide: [User Guide](https://leroytan.github.io/ip/)
Jar file: [Jar file](https://github.com/leroytan/ip/releases/tag/A-Release2.0)

Thanks!

**Comment by curtischang2510** [comment]
Hello!! Just tested on MacOS. Seems to work fine, like the death note theme 👍

**Comment by leroytan** [comment]
> Hello!! Just tested on MacOS. Seems to work fine, like the death note theme 👍

Thanks for your help!

**Comment by kimberlytmq** [comment]
Hi! Tested on MacOS and it's working fine! really like the vignette effect!

**Comment by flyingsalsa** [comment]
Tested on Linux 
![image](https://github.com/user-attachments/assets/306ceb29-5b67-4740-a6da-3cf7660de3a0)
Might need to work anchoring some the send button during window rescaling
Commands seem fine doe
the error handling also appears to be complete in the command line output but within the UI it only states invalid without specifying whats wrong, not sure if this is intended.

**Comment by flyingsalsa** [comment]
Otherwise i rly like the extra visuals!

**Comment by yastsc** [comment]
Hi, I tested it on Mac and it seems to have the same issue as the above Linux user in terms of resizing, but the avatars are really cool :)
<img width="1469" alt="Screenshot 2024-09-22 at 11 37 42 PM" src="https://github.com/user-attachments/assets/feab0ff7-5607-4f8a-b294-66e6fed71538">

**Comment by leroytan** [comment]
thx for all your help! @yastsc @kimberlytmq @flyingsalsa @curtischang2510
