### ISSUE TITLE
Week 7 Task: Updating README

### ISSUE THREAD

**Issue by beginner-web-developer** [nus-cs2103-AY2425S1/forum#405]
Hi, I have a question regarding the Week 7 task of updating the README page. It seems that the README.md file is not in the `[project-root]/docs` folder, so when i run `npm run serve` to preview (my team is using MarkBind), the README page doesn't appear on the website. Is this the intended behaviour? Or are we supposed to move the README.md file to `[project-root]/docs`?

**Comment by damithc** [comment]
@beginner-web-developer That is intended. That file is not part of the published project website. It is for the eyes of those who visit the GitHub project directly.

**Comment by beginner-web-developer** [comment]
ok thanks prof
