### ISSUE TITLE
Requesting help from Mac/Linus to smoke tes my jar file

### ISSUE THREAD

**Issue by blackpanther9229** [nus-cs2103-AY2425S1/forum#406]
Please help smoke test my ip!
Would appreciate linux and MAC users as I use windows.
Feel free to give any other feedback (e.g. user guide/user interface)

User guide: [User Guide](https://blackpanther9229.github.io/ip/)
Jar file: [Jar file](https://github.com/blackpanther9229/ip/releases/tag/A-Release)

Thanks!

**Comment by tzuennn** [comment]
<img width="793" alt="Screenshot 2024-09-22 at 3 15 57 PM" src="https://github.com/user-attachments/assets/e0f25450-e5ed-4c63-8e81-95499e84536a">
Hi!
Your program is working fine.

**Comment by blackpanther9229** [comment]
> <img alt="Screenshot 2024-09-22 at 3 15 57 PM" width="793" src="https://private-user-images.githubusercontent.com/156199068/369670806-e0f25450-e5ed-4c63-8e81-95499e84536a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5OTI0NzAsIm5iZiI6MTcyNjk5MjE3MCwicGF0aCI6Ii8xNTYxOTkwNjgvMzY5NjcwODA2LWUwZjI1NDUwLWU1ZWQtNGM2My04ZTgxLTk1NDk5ZTg0NTM2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMlQwODAyNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZGRiYmFlNTkxZWJhNGRmNmVhMTBmYmI3YTM4NjNlOTg1NjlkOTMzZGY5NzUwY2I3OWNiZWI0ZDJmOGY2NmE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.K5gUqo-e163F9jGF_yKxc1CQquYmuEpurPAlmSTZM10"> Hi! Your program is working fine.

![image](https://github.com/user-attachments/assets/120d6b81-e355-4a5a-b7b4-2831d2347292)

you too

**Comment by thisisaditya17** [comment]
<img width="399" alt="image" src="https://github.com/user-attachments/assets/5a55cd57-6737-4510-9a35-45c1751d8310">
I am unable to add task using todo
Am i doing something wrong ?
I tried todo dance
Todo dance
todo 'dance'

**Comment by ishan-agarwal-05** [comment]
> Please help smoke test my ip! Would appreciate linux and MAC users as I use windows. Feel free to give any other feedback (e.g. user guide/user interface)
> 
> User guide: [User Guide](https://blackpanther9229.github.io/ip/) Jar file: [Jar file](https://github.com/blackpanther9229/ip/releases/tag/A-Release)
> 
> Thanks!

your program is working fine
<img width="954" alt="image" src="https://github.com/user-attachments/assets/d5570479-fbfd-4572-86df-3be4fdfab0c9">

**Comment by blackpanther9229** [comment]
> <img alt="image" width="399" src="https://private-user-images.githubusercontent.com/131612114/369673462-5a55cd57-6737-4510-9a35-45c1751d8310.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5OTI4NzUsIm5iZiI6MTcyNjk5MjU3NSwicGF0aCI6Ii8xMzE2MTIxMTQvMzY5NjczNDYyLTVhNTVjZDU3LTY3MzctNDUxMC05YTM1LTQ1YzE3NTFkODMxMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMlQwODA5MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNTc0OTljZjU5NjM1Y2Q5ZTllOTczZDA4ZjFhMDBlY2ZjNjFhNWQ3ZjJmMmQwOTZlMjk0ZmEwOGFlYjVjMGQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wCDpvFayXcj1b1gmbx8px2dEIj0J0YrWb_SAaa2lVNU"> I am unable to add task using todo Am i doing something wrong ? I tried todo dance Todo dance todo 'dance'

Ahh that is the help window, not the chat bot. But thank you, I think I should also manage this.

**Comment by thisisaditya17** [comment]
Ah okay, I mean it wasn't quite clear. 
Maybe just point out that you are in help window. Close it to try out commands

**Comment by blackpanther9229** [comment]
> Ah okay, I mean it wasn't quite clear. Maybe just point out that you are in help window. Close it to try out commands

Yes sure

**Comment by flyingsalsa** [comment]
Hi, tested on linux
![image_2024-09-22_191326890](https://github.com/user-attachments/assets/1ffb2d09-ab3e-443b-be3e-fc32fc040e89)
Appears ur UI isnt anchored properly and doesnt move with window rescaling.
There are also some extra white spaces at the start of some lines while other lines (usually those that wrap around) do not have them.
However most of the other features seem fine!

**Comment by flyingsalsa** [comment]
I liked the customised window and cursors very cool

**Comment by blackpanther9229** [comment]
> Hi, tested on linux ![image_2024-09-22_191326890](https://private-user-images.githubusercontent.com/107453007/369683059-1ffb2d09-ab3e-443b-be3e-fc32fc040e89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwMDQxNTYsIm5iZiI6MTcyNzAwMzg1NiwicGF0aCI6Ii8xMDc0NTMwMDcvMzY5NjgzMDU5LTFmZmIyZDA5LWFiM2UtNDQzYi1iZTNlLWZjMzJmYzA0MGU4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMlQxMTE3MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YmQ3MjIxZTYyMDFkY2U2ZWIzNjVhMWI5OTNlYmEzZmZmY2JiMjQwZGY2Njg1NWJhM2M0MzczODg4ZmEzODc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tWuUyhNcUgYjVG0a-80PCLgbMFAEt2J4qgyrhDQTq2o) Appears ur UI isnt anchored properly and doesnt move with window rescaling. There are also some extra white spaces at the start of some lines while other lines (usually those that wrap around) do not have them. However most of the other features seem fine!

Thanks. Definitely need some modification.

**Comment by blackpanther9229** [comment]
> Hi, tested on linux ![image_2024-09-22_191326890](https://private-user-images.githubusercontent.com/107453007/369683059-1ffb2d09-ab3e-443b-be3e-fc32fc040e89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwMTQzNTAsIm5iZiI6MTcyNzAxNDA1MCwicGF0aCI6Ii8xMDc0NTMwMDcvMzY5NjgzMDU5LTFmZmIyZDA5LWFiM2UtNDQzYi1iZTNlLWZjMzJmYzA0MGU4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMlQxNDA3MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lODlkNzE0OTA1M2RiMjUyZjExYjc3Mjc5ZjcwZWRjMjE0N2M5OWQ3MmMyNjVlNjIxYzQwNDFkNTJiZDgzZTkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MrTYNlAZJ2jWEgGvq63fZ1NknlJIcC3CD1PYvBrp7ps) Appears ur UI isnt anchored properly and doesnt move with window rescaling. There are also some extra white spaces at the start of some lines while other lines (usually those that wrap around) do not have them. However most of the other features seem fine!

I did some modification, can you quick recheck. Thanks.

**Comment by flyingsalsa** [comment]
yep the screen resizing isnt bugged anymore 
although sasuke looks slightly too close to the edge of the window compared to naruto
![image](https://github.com/user-attachments/assets/f53bf457-efcf-4d66-9f2a-8f39f3905332)

**Comment by flyingsalsa** [comment]
PS you misspelt automatically in the release
![image](https://github.com/user-attachments/assets/4ecacfa6-7132-482a-a1af-c5ce3fb6aff2)

**Comment by flyingsalsa** [comment]
Hope the feedback helps!

**Comment by blackpanther9229** [comment]
> Hope the feedback helps!

Really appreciate your effort!
