### ISSUE TITLE
Clarification for tp UI Mock-ups

### ISSUE THREAD

**Issue by Droas590** [nus-cs2103-AY2425S1/forum#407]
Hi prof, for our team features, we will only have different command, output and error message compare to AB3 (different text), UI will be similar to AB3. Do we need to create UI mock-up in this case?

**Comment by damithc** [comment]
@Droas590 If the UI will be exactly the same as AB3, there is no need. You can use an AB3 screenshot instead.

**Comment by Droas590** [comment]
Thank you prof for the response! Do you mean we should screenshot AB3 and edit our text response on top? and do we need the screenshot for each feature?

**Comment by damithc** [comment]
> Do you mean we should screenshot AB3 and edit our text response on top? 

@Droas590 If the UI is going to be the same, no need to edit, right?

>and do we need the screenshot for each feature?

No need, if the UI remains the same and only the text changes. You can give one representative mockup/screenshot and mention the behavior of each feature in text.

**Comment by Droas590** [comment]
Alright thank you for the fast response!
