### ISSUE TITLE
Help to smoke test my IP

### ISSUE THREAD

**Issue by thisisaditya17** [nus-cs2103-AY2425S1/forum#408]
I would appreciate if you will try out my chatbot and list out if faced any issues or bugs. Thanks all.

[https://github.com/thisisaditya17/ip/releases/tag/A-Release](url)

**Comment by natlv** [comment]
Hi there, I used a Mac OS to test your jar file. I like that your README is informative and the UI design of your chatbot is creative. Overall, I think the bot is working and nice!

**Comment by hazzle23** [comment]
![Screenshot 2024-09-22 164248](https://github.com/user-attachments/assets/5f757792-9179-4f03-aba1-7f8408acdc8d)

Hello~~ Windows user here! I faced this error when trying to run your .jar file. 
This issue looks quite similar to #388

**Comment by hansneddyanto** [comment]
Hi, tried on my windows laptop and there was an error from my side. Same error as @hazzle23

**Comment by thisisaditya17** [comment]
oh yeah okay 
i had removed the dependencies for windows and linux from build.gradle because  i thought I won't be using it.
Wait i'll fix this.

**Comment by thisisaditya17** [comment]
@hansneddyanto @hazzle23 Hi guys, I added dependencies for Windows. 
Can you try again?
Thank you

**Comment by lancehaha** [comment]
hello I have tested your ip, to me only 2 commands came in trouble, which are the "load" and "archive" commands in need  of more instruction, as a user at first I didn't realize that I have to open the folder and check the file name. I was quite lost and wondering what do you mean by "archive file name with extension", at the time when I was trying to use this command. Probably give my function on archive command so that user can choose their own filename instead of checking them by themselves. Or add some new command to check what archives do they have right now.

**Comment by Wnayar** [comment]
Hi, just tried out your chatbot v1.1. No issues on windows end. (Also, it looks awesome). I tested also reopening it to see if the data is persistent and it is.   

I would say the only small issue I had is that when I type a command in an incorrect format it says Danger, invalid command format but it does not tell me the format I should use.

**Comment by hansneddyanto** [comment]
Hi! I just tested your chatbot v1.1, and it works on my laptop. Just a small note, I'm not sure if this is intended or not, but if I mark a task that is already marked, it becomes unmarked. Similarly, if I unmark a task that is already unmarked, it becomes marked.

**Comment by flyingsalsa** [comment]
I've tested it as well and unmark and mark do the same thing which is just flip the completion state of the numbered task, seems like unintended behaviour to have both functions do the same thing?

**Comment by flyingsalsa** [comment]
Also error catching by just stating "Danger! invalid command format" seems slightly vague on the user side. maybe some checks could be put in place to catch what kind of error in the command there is?

**Comment by iamdiluxedbutcooler** [comment]
Hi! I've test your v1.2 released yesterday, Here's what I found

Some minor text format problem (somehow \n isn't making the text to move to next line ._.)
<img width="384" alt="Screenshot 2567-09-23 at 22 40 25" src="https://github.com/user-attachments/assets/fc1afc0c-fda5-4829-ba86-979e3ab5ce9b">

**Comment by iamdiluxedbutcooler** [comment]
Event task is labelled with "D" which is for deadline
<img width="394" alt="Screenshot 2567-09-23 at 22 41 41" src="https://github.com/user-attachments/assets/8a7fed3b-e1d2-482b-a42e-774b5b398bac">

**Comment by iamdiluxedbutcooler** [comment]
As I understand from your user guide, 'archive' command will only archive completed task (which I interpret as "marked" task), however when I type archive, all tasks are gone regardless of their marking status

Would you mind to explain a little bit more about this function? Maybe I understand it wrong HAHAHA.

**Comment by thisisaditya17** [comment]
> As I understand from your user guide, 'archive' command will only archive completed task (which I interpret as "marked" task), however when I type archive, all tasks are gone regardless of their marking status
> 
> Would you mind to explain a little bit more about this function? Maybe I understand it wrong HAHAHA.

This was given in the BCD extensions page
Archiving items

Provide a way to archive items so that the user can remove items from the app but still keep a record of them somewhere e.g., archive all tasks in the list into a file so that the user can start over with a clean slate.

So it stores all the tasks and preserve their respective states. Then it removes them from the current class list.
