### ISSUE TITLE
Tutorial 2 from Week 6 tP tasks

### ISSUE THREAD

**Issue by adipanda2002** [nus-cs2103-AY2425S1/forum#409]
After completing the functionality for the remark command on the tutorial-add-command branch, do I make the PR from the tutorial-add-command branch to my team's repo or do I merge the branch to the master branch of my fork and then create the PR to the team fork? I am a bit confused by the instructions on the course website.

**Comment by damithc** [comment]
@adipanda2002 create a PR from your fork's `tutorial-adding-command` (not `...-add-...`) branch to your team repo's `master` branch

**Comment by adipanda2002** [comment]
Alright thanks prof
