### ISSUE TITLE
IP Dashboard does not reflect some of my commits

### ISSUE THREAD

**Issue by ITZXITZX** [nus-cs2103-AY2425S1/forum#41]
Hi,

Might anyone know what I could have done wrongly when I commit and push to my remote repo? 

On the dashboard it displayed that I have only completed Level-4, when I had also completed those beforehand.

I used source tree, and pushed to both the master branch and origin branch of my remote server for Level-4. I checked and ensured that the tags are named correctly. I think I only pushed to master for the previous levels. On my github repo, master is my main branch.

![image](https://github.com/user-attachments/assets/5b8de50a-20a9-4864-8c38-5c5b8995c329)
![todelete2](https://github.com/user-attachments/assets/15df662f-b4ae-463f-8429-2ec624dd9ed8)
![to delete 1](https://github.com/user-attachments/assets/238c21cd-1476-4dad-a8e6-c65c511bf8e7)

**Comment by Domokunx** [comment]
One possibility I can think of is that you could have forgotten to push the tags specifically for your previous commits maybe?
