### ISSUE TITLE
Not able to run jar file on other devices but locally can due to JavaFX runtime components missing

### ISSUE THREAD

**Issue by rynlwhh** [nus-cs2103-AY2425S1/forum#411]
Hi, I keep getting this error 
RyanIPTest % java -jar Naega.jar
Error: JavaFX runtime components are missing, and are required to run this application

I tried debugging already, I made sure that the correct java version is downloaded on the other device and I have tried changing my build.gradle file but I still keep getting the same error. Can someone kindly advice, below is my build.gradle file.

```java
plugins {
    id 'java'
    id 'application'
    id 'checkstyle'
    id 'com.github.johnrengelman.shadow' version '7.1.2'
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.10.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.10.0'

    // JavaFX version
    String javaFxVersion = '17.0.7'

    // Dynamically include JavaFX dependencies based on the platform (Windows, macOS, Linux)
    String osName = System.getProperty("os.name").toLowerCase()
    String javafxPlatform

    if (osName.contains("win")) {
        javafxPlatform = "win"
    } else if (osName.contains("mac")) {
        javafxPlatform = "mac"
    } else if (osName.contains("linux")) {
        javafxPlatform = "linux"
    } else {
        throw new GradleException("Unsupported OS: " + osName)
    }

    // Include the JavaFX modules for the detected platform
    implementation "org.openjfx:javafx-base:${javaFxVersion}:${javafxPlatform}"
    implementation "org.openjfx:javafx-controls:${javaFxVersion}:${javafxPlatform}"
    implementation "org.openjfx:javafx-fxml:${javaFxVersion}:${javafxPlatform}"
    implementation "org.openjfx:javafx-graphics:${javaFxVersion}:${javafxPlatform}"
}

checkstyle {
    toolVersion = '10.2'
    configFile = file('config/checkstyle/checkstyle.xml')
}

test {
    useJUnitPlatform()

    testLogging {
        events "passed", "skipped", "failed"
        showExceptions true
        exceptionFormat "full"
        showCauses true
        showStackTraces true
        showStandardStreams = false
    }
}

application {
    mainClass.set("Naega.Gui.Main")  // Set your main class here
}

shadowJar {
    archiveFileName = 'Naega.jar'

    // Merge services and exclude module-info.class to prevent Java module system issues
    mergeServiceFiles()
    exclude 'module-info.class'
}

run {
    standardInput = System.in
    jvmArgs = [
            '--module-path', configurations.runtimeClasspath.asPath,
            '--add-modules', 'javafx.controls,javafx.fxml'
    ]
}
```

**Comment by damithc** [comment]
@rynlwhh While waiting for others to chime in, I suggest you try with the JavaFX configuration we have specified in our own JavaFX tutorial in https://se-education.org/guides/tutorials/javaFxPart1.html

**Comment by taggyhan** [comment]
try 
shadowJar {
    archiveBaseName = "Naega"
    mainClassName = 'naega.Naega' (deps where u saved?)
    archiveClassifier = null
}

instead? ( this is as specified by the javaFx tut)

**Comment by Wxy2003-xy** [comment]
I posted an issue yesterday mentioning one probable cause of this problem(and I'm getting tagged for this issue what an amazing algorithm behind this), that if your entry point extends Application you might run into this error. The solution is to have a separate entry class that doesn't extend Application. This was mentioned in AB3 as pointed by someone else so I closed the issue. Hope it helps.

**Comment by damithc** [comment]
@rynlwhh Recommended to configure build.gradle as given by our JavaFX tutorials (in general, trust the resources given by the course because if there is something wrong with them, someone else would have noticed and reported it already). The build.gradle you created yourself is not doing the correct thing -- it is selecting JavaFX dependencies only for the current OS whereas what we want is to include dependencies for all three OS'es.

**Comment by rynlwhh** [comment]
Thank you so much @damithc @taggyhan @Wxy2003-xy @LimKaiWei @natlv I have managed to fix my build.gradle file. The main issue was the Launcher class including the Application class.
