### ISSUE TITLE
Request help for smoke test on Windows/Linux

### ISSUE THREAD

**Issue by travisim** [nus-cs2103-AY2425S1/forum#415]
I use a m2 pro macbook on macos Sequoia 15.1.
I deeply appreciate a windows or linux user's help to test my jar files
[user guide](https://travisim.github.io/ip/) and [.jar file](https://github.com/travisim/ip/releases/tag/v0.7)

**Comment by LimKaiWei** [comment]
Hi there. I have roughly tested your program on my system (Linux) and it works just fine. 
I might be nitpicking abit but I wish I can see all my 11 tasks i have when using the `list` command.
![image](https://github.com/user-attachments/assets/08626ef7-e57b-4557-8a38-0ff2c9e8f79a)
Other than that, I would like to praise you _duplicate task detection_, good work!

**Comment by riccoljy** [comment]
Looks good; working perfectly fine on Windows 11! But seems like `deadline` uses exact date formatting whereas `event` does not. Also similar to above, seems like I'm stuck to listing 4 tasks :( 

Ultimately, working perfectly fine!

**Comment by yugan01** [comment]
Great job in designing the GUI, with circular pictures of the faces. For duplicate detection, I would like to ask if its the intended feature to detect duplicates across tasks (for example, a todo and event with the same description is considered a duplicate). I thought the duplicate detection applied for duplicates within the same category of tasks (e.g. 2 todos with the same description is not allowed but a todo and an event with the same description is allowed as its under different categories)
