### ISSUE TITLE
Git-Standard

### ISSUE THREAD

**Issue by JellyPenguinnn** [nus-cs2103-AY2425S1/forum#416]
Anyone know how to meet the Git-Standard requirement for iP?

**Comment by Feng1231** [comment]
Hi, as long as you followed the rules stated [here](https://se-education.org/guides/conventions/git.html#commit-message-subject), then everything should be good.
I think you have exceeded 72 characters for this commit:
![image](https://github.com/user-attachments/assets/241bd221-e2c3-41e5-ab8f-5066a98d139c)

**Comment by JellyPenguinnn** [comment]
Hello. Thanks for the information. It will only track for the last 5 commits, is it?

**Comment by damithc** [comment]
> Hello. Thanks for the information. It will only track for the last 5 commits, is it?

@JellyPenguinnn Yes.

**Comment by JellyPenguinnn** [comment]
Noted. Thank you prof!!
