### ISSUE TITLE
tP: Is following the tp Constraints considered as the NFRs for the tP?

### ISSUE THREAD

**Issue by DennieDan** [nus-cs2103-AY2425S1/forum#417]
I am thinking about adapting the [tp: Constraints](https://nus-cs2103-ay2425s1.github.io/website/admin/tp-constraints.html#tp-constraints) to the NFRs in the tP Developer Guide.
Am I allowed to do that beside adding some more NFRs as my own idea?

**Comment by damithc** [comment]
> I am thinking about adapting the [tp: Constraints](https://nus-cs2103-ay2425s1.github.io/website/admin/tp-constraints.html#tp-constraints) to the NFRs in the tP Developer Guide.
> Am I allowed to do that beside adding some more NFRs as my own idea?

@DennieDan Yes you may. Alternatively, you can point to the [tp: Constraints](https://nus-cs2103-ay2425s1.github.io/website/admin/tp-constraints.html#tp-constraints) page. Either way is fine.

**Comment by DennieDan** [comment]
Thank you so much, Prof.
