### ISSUE TITLE
Error in course website

### ISSUE THREAD

**Issue by Feng1231** [nus-cs2103-AY2425S1/forum#418]
Under this [section](https://nus-cs2103-ay2425s1.github.io/website/schedule/week7/project.html#2-update-the-project-website): 

 > Can the AB3 screenshot **used for this**? Only in the unlikely case that your final product UI is expected to look exactly the same as AB3.

Should it be `Can the AB3 screenshot **be used for this**` ?

**Comment by damithc** [comment]
Fixed. Thanks for the bug report @Feng1231 💯
