### ISSUE TITLE
Questions about command format in level 8

### ISSUE THREAD

**Issue by Ma-Xizi** [nus-cs2103-AY2425S1/forum#42]
Hi I am bit confused by level 8 requirements. In level 8, command lines with date e.g. "deadline return book /by 2/12/2019 1800" should be accepted and processed correctly.

Prior to level 8, the deadline format is "deadline return book /by Sunday". Will this format still be accepted in level 8, using the LocalDate.now() way? It seems that I have to adjust my testing script as well.

Since I was using regex for command, there was definitely a big change for me.

**Comment by damithc** [comment]
> Prior to level 8, the deadline format is "deadline return book /by Sunday". Will this format still be accepted in level 8, using the LocalDate.now() way? It seems that I have to adjust my testing script as well.

@Ma-Xizi supporting the previous command format is not required, but you are free to do so too.

**Comment by MinkhantEain** [comment]
Hi, will the time always be after the date? Also, iss the date always in 2/12/2019 format or are we also supposed to account for the cases where date is given as 2019-12-02?

**Comment by Ma-Xizi** [comment]
> > Prior to level 8, the deadline format is "deadline return book /by Sunday". Will this format still be accepted in level 8, using the LocalDate.now() way? It seems that I have to adjust my testing script as well.
> 
> @Ma-Xizi supporting the previous command format is not required, but you are free to do so too.

Thank you!
