### ISSUE TITLE
Wrong hyperlink in AB3 Tutorial: Removing Fields

### ISSUE THREAD

**Issue by ghos7ie** [nus-cs2103-AY2425S1/forum#420]
The hyperlink linking back to the Add Command tutorial is wrong as shown below!

![image](https://github.com/user-attachments/assets/b6cf2a87-54e6-4091-b216-92fbe385177e)

Should change from https://se-education.org/guides/tutorials/AddRemark.html to https://se-education.org/guides/tutorials/ab3AddRemark.html

**Comment by damithc** [comment]
Thanks for the bug report, @ghos7ie 💯 
Fixed.
