### ISSUE TITLE
Checkstyle for constants

### ISSUE THREAD

**Issue by kimxw** [nus-cs2103-AY2425S1/forum#422]
![image](https://github.com/user-attachments/assets/eea8a4f4-db75-4cab-9647-6244d6bb2e59)

![image](https://github.com/user-attachments/assets/4bee23bd-3f3c-4e49-b1fc-bfa83d390ad1)

Any suggestions as to what could be trigerring the checkstyle this way?

**Comment by Feng1231** [comment]
Probably because its not a static final variable.

I found this online:
![image](https://github.com/user-attachments/assets/d24b267b-292b-436d-ad61-6181a3c795df)

**Comment by yadobler** [comment]
I talked about it [here](https://github.com/nus-cs2103-AY2425S1/forum/issues/255#issuecomment-2342348083)

Final variables only mean they are immutanle _for each object instance_ but making it static final means they are _globally immutable_. 

JVM will store _static final_ separately in the program `DATA` section, but finals without static will still be allocated on heap with each instance of the class initialised. 

---

Now, some standards agree that finals should also be ALL_CAPS. Some don't. For this course, we reserve this to only the static finals.

There's an option in the `checkstyle.xml` if you wanna disable it, for future uses

**Comment by kimxw** [comment]
Ah got it. Thank you so much~ @Feng1231  and @yadobler
