### ISSUE TITLE
Error occurred when trying to run jar on a x86_64 architecture

### ISSUE THREAD

**Issue by rynlwhh** [nus-cs2103-AY2425S1/forum#423]
When smoke testing on another Mac with x86_64 processor, I get the following error
limkahleong@Mac RyanIPTest % java -jar Naega.jar
Sep 23, 2024 5:05:40 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @3f2a5da7'
Loading library prism_es2 from resource failed: java.lang.UnsatisfiedLinkError: /Users/limkahleong/.openjfx/cache/17.0.7/libprism_es2.dylib: dlopen(/Users/limkahleong/.openjfx/cache/17.0.7/libprism_es2.dylib, 0x0001): tried: '/Users/limkahleong/.openjfx/cache/17.0.7/libprism_es2.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/limkahleong/.openjfx/cache/17.0.7/libprism_es2.dylib' (no such file), '/Users/limkahleong/.openjfx/cache/17.0.7/libprism_es2.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')) ...

Trying to debug with chatGPT and it says this 

![2024-09-23 17 21 54](https://github.com/user-attachments/assets/d0d48c28-7145-4633-a89d-61432f25f15f)

My question is do we have to ensure that it works for x86_64 architectures? Because I have tested other friends' released JARs and they all do not work on a x86_64 architecture. If we do, is there any suggestion on how to fix this error? Appreciate any help!

**Comment by damithc** [comment]
@rynlwhh While waiting for others to chime in, also share the following:

1. In the terminal you saw the error, what's the output for the `java -version` command?
2. What's your build.gradle file? You can push to your fork and share the link here.

**Comment by rynlwhh** [comment]
@damithc the output is as follows 
limkahleong@Mac RyanIPTest % java -version
openjdk version "17.0.12" 2024-07-16
OpenJDK Runtime Environment Homebrew (build 17.0.12+0)
OpenJDK 64-Bit Server VM Homebrew (build 17.0.12+0, mixed mode, sharing)


The following is my build.gradle file,
``` java

plugins {
    id 'java'
    id 'application'
    id 'com.github.johnrengelman.shadow' version '7.1.2'
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.10.0'
    testRuntimeOnly group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.10.0'

    String javaFxVersion = '17.0.7'

    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'linux'
}

test {
    useJUnitPlatform()

    testLogging {
        events "passed", "skipped", "failed"

        showExceptions true
        exceptionFormat "full"
        showCauses true
        showStackTraces true
        showStandardStreams = false
    }
}

application {
    mainClass.set('Naega.Gui.Launcher')
}

shadowJar {
    archiveFileName = 'Naega.jar'
    archiveBaseName = 'Naega'
    archiveClassifier = null
}

run {
    standardInput = System.in
}

```

**Comment by TechRaj** [comment]
Try adding this to your run task


run {
    standardInput = System.in
    jvmArgs = [
            '--module-path', '/path/to/javafx-sdk-17/lib',
            '--add-modules', 'javafx.controls,javafx.fxml,javafx.graphics'
    ]
}

**Comment by damithc** [comment]
> Try adding this to your run task
> 
> run { standardInput = System.in jvmArgs = [ '--module-path', '/path/to/javafx-sdk-17/lib', '--add-modules', 'javafx.controls,javafx.fxml,javafx.graphics' ] }

@TechRaj This is unlikely to help, as the problem happens when running the jar file normally, not when when running the app using Gradle.

**Comment by damithc** [comment]
> limkahleong@Mac RyanIPTest % java -version
> openjdk version "17.0.12" 2024-07-16
> OpenJDK Runtime Environment Homebrew (build 17.0.12+0)
> OpenJDK 64-Bit Server VM Homebrew (build 17.0.12+0, mixed mode, sharing)

@rynlwhh As per this output, the computer is not using the SDK we have prescribed for Macs in [here](https://nus-cs2103-ay2425s1.github.io/website/admin/programmingLanguages.html#programming-language). If the prescribed version is not used, jars created in ARM versions will not work in Intel Macs, and vice versa.

**Comment by rynlwhh** [comment]
Thank you @damithc ! I understand the issue now.
