### ISSUE TITLE
Requesting Smoke test for Mac OS

### ISSUE THREAD

**Issue by Judy1x4** [nus-cs2103-AY2425S1/forum#424]
This is my release page: https://github.com/Judy1x4/ip/releases/tag/v0.2

And this is my user guide: https://judy1x4.github.io/ip/

**Comment by MadLamprey** [comment]
Hello @Judy1x4! I am from a previous batch. I have tested your application on my system:
`macOS Sequoia 15.0`
All basic functionalities as defined in the user guide seem to be running smoothly. It also loads data upon restarting, as intended. 
<img width="401" alt="Screenshot 2024-09-25 at 12 36 02 PM" src="https://github.com/user-attachments/assets/47f1d0d4-cb19-4167-8a68-0bc04bbf5a80">
One minor consideration is, currently the window is resizable without associated responsiveness. Simplest workaround could be fixing window dimensions.
<img width="1470" alt="Screenshot 2024-09-25 at 12 36 27 PM" src="https://github.com/user-attachments/assets/05b07d2f-b0b4-483d-a845-7cea1e655c79">

**Comment by yu-sutong** [comment]
I'm able to run, load data and save data on MacOS without any issues.
<img width="397" alt="Screenshot 2024-09-25 at 1 31 57 PM" src="https://github.com/user-attachments/assets/e99e998a-9ca6-4f65-ad2c-3389f1e319ca">
