### ISSUE TITLE
Request for smoke testing for MacOS

### ISSUE THREAD

**Issue by Elinengu** [nus-cs2103-AY2425S1/forum#425]
This is my release page: https://github.com/Elinengu/ip/releases/tag/A-Release
And this is my user guide: https://elinengu.github.io/ip/

**Comment by RobotWizzard** [comment]
Hi, I'm not using MacOS, but it seems to be working fine on my Windows laptop. 
Though I would like to suggest allowing event start times to be in the past as users may want to track an event that has already started, for example a new season in a video game.

**Comment by Airiinnn** [comment]
Able to run, save and load data on MacOS without issue.
![elysia](https://github.com/user-attachments/assets/9510280b-61ce-4b04-b3f0-0f376c0969de)

**Comment by sandyk0105** [comment]
<img width="529" alt="Screenshot 2024-09-25 at 08 03 06" src="https://github.com/user-attachments/assets/52486e90-831a-4b5e-941c-3a7a068d97b9">

Works without any issue! Tested on MacOS Ventura.
