### ISSUE TITLE
Requesting smoke test on windows or linux

### ISSUE THREAD

**Issue by weijianwong** [nus-cs2103-AY2425S1/forum#427]
This is my release page: https://github.com/weijianwong/ip/releases/tag/A-Release2
This is my user guide: https://weijianwong.github.io/ip/

Thank you guys!

**Comment by darkmoongreatsword** [comment]
Windows user here. Looks good! Runs smoothly on my machine.

![image](https://github.com/user-attachments/assets/212e6419-9060-485c-bd64-c915ef673bcd)
![image](https://github.com/user-attachments/assets/b0187d02-7c5c-4adc-905c-ff23915456f8)

**Comment by Xczheng0105** [comment]
![image](https://github.com/user-attachments/assets/4ee6395d-340b-4d26-9985-0536f612d0ba)

![image](https://github.com/user-attachments/assets/8303bda2-52a6-495a-8e45-4428ee5eb0f0)

Windows user here. Tested some functionalities, LGTM!

**Comment by kienvumrpm** [comment]
![image](https://github.com/user-attachments/assets/f7f8f997-6c08-451f-ab90-b175b5f1eea6)
LGTM

**Comment by zhiyi12345** [comment]
Works on MacOs.

I am able to call list with random string attached after `list`. Perhaps you can check for additional user input after `list`.
<img width="512" alt="Screenshot 2024-09-24 at 6 26 22 PM" src="https://github.com/user-attachments/assets/e293747d-6da3-4604-b128-95d9b6915504">

I am also able to create an event where its from date is after the to date. Perhaps you can add a conditional check on the from and to dates to ensure that the timing of the event is valid.
<img width="512" alt="Screenshot 2024-09-24 at 6 23 39 PM" src="https://github.com/user-attachments/assets/602bb640-0f5d-40e5-b973-a4fb63e04da2">

**Comment by mrnobody0505** [comment]
Testing on Mac, lgtm
![image](https://github.com/user-attachments/assets/3e995670-9c39-4135-a713-7d893225230e)
