### ISSUE TITLE
Convention for Field Annotations

### ISSUE THREAD

**Issue by yadobler** [nus-cs2103-AY2425S1/forum#428]
I have seen #227, but I believe this is only for class / method annotations.

In the [Google Java style guide](https://google.github.io/styleguide/javaguide.html#s4.8.5-annotations) for Annotations, field annotations (4.8.5.4) are instructed to be inline:

> 4.8.5.4 Field annotations
> Annotations applying to a field also appear immediately after the documentation block, but in this case, multiple annotations (possibly parameterized) may be listed on the same line; for example:
> 
> ```java
> @Partial @Mock DataLoader loader;
> ```

However, in the JavaFX tutorial, I noticed that the `@FXML` annotations are on a separate line:
([Example from here](https://se-education.org/guides/tutorials/javaFxPart4.html))
```java
    @FXML
    private ScrollPane scrollPane;
    @FXML
    private VBox dialogContainer;
    @FXML
    private TextField userInput;
    @FXML
    private Button sendButton;
```

Personally I prefer the google way:
```java
    private @FXML Label dialog;
    private @FXML ImageView displayPicture;
    private @FXML VBox labelsVbox;
```

What do we use?

**Comment by damithc** [comment]
@yadobler As a goal of the coding standard is consistency, we should aim to preserve/increase consistency. Therefore, it makes sense to follow the style used by the tutorial.

**Comment by yadobler** [comment]
@damithc i see, that does make sense.

Thank you!
