### ISSUE TITLE
Is there a way to allow the automated test files to access the folders other than java inside main?

### ISSUE THREAD

**Issue by RezwanAhmed123** [nus-cs2103-AY2425S1/forum#43]
Right now I have the following structure:
![image](https://github.com/user-attachments/assets/8ccc17b1-d5e9-4b9d-8d1d-822b1b9f3ead)

I would like to make the runtest.bat or runtest.sh to be able to access the text-files folder as well. Right now, the code works as intended however, since during the testing the code doesnt have access to the text-files folder, it is throwing errors.

I know the code itself is fine because when i manually test it with the terminal with same inputs it works.

**Comment by damithc** [comment]
@RezwanAhmed123 iP expectations that may be relevant to your question.
1. In code, specify the data file location relative to the location at which the program is run (e.g., `.\data\tasks.txt`, not  `C:\projects\data\tasks.txt`). You also need to do this in an OS-independent way, as file path syntax vary based on the OS.
2. The above means the data file used when you do manual testing will be different from the data file used by the automated test, as the two are run from two different locations.

**Comment by RezwanAhmed123** [comment]
I have managed to fix the issue. I realised that the program I had, only supported checks to see if a file "listStorage.txt" exists or not, not the entire directory that it belongs in. Once I implemented a check to see if the "text-files" and its parent directory exists and create if it does not, both runtest.sh and runtest.bat files were able to run smoothly with no errors.

this was the block of code I added into my load function which helped to solve the issue:

```
File f = new File(storageListFilePath);

// Check if the file/folder already exists and create if it is not,
// send a warning if unable to create either and the file still does not exist
if ((!f.getParentFile().mkdirs() || !f.createNewFile()) && !f.exists()) {
    FormattedPrinting.fileCorrupted();
}
```

**Comment by damithc** [comment]
Good work @RezwanAhmed123 
Thanks for sharing the solution too.
Tip: You can enable syntax highlighting using the following syntax ([more info on fenced code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)).

e.g.,
```java
File f = new File(storageListFilePath);

// Check if the file/folder already exists and create if it is not,
// send a warning if unable to create either and the file still does not exist
if ((!f.getParentFile().mkdirs() || !f.createNewFile()) && !f.exists()) {
    FormattedPrinting.fileCorrupted();
}
```

**Comment by RezwanAhmed123** [comment]
Ahh thanks prof, I was trying to enable that unfortunately was unable to find the correct info. Thank you!
