### ISSUE TITLE
ALT+7 hotkey not working as intended when finding all usages

### ISSUE THREAD

**Issue by ITZXITZX** [nus-cs2103-AY2425S1/forum#431]
Hi, does anyone know how to fix the issue of the ALT+7 hotkey not working as intended when finding all usages? 

I am using IntelliJ.

When I use ALT+7, it instead shows me the class structure on the left panel.

![image](https://github.com/user-attachments/assets/5c5d8b47-812a-4ebe-a744-decc933bbb39)

**Comment by jinnsuke** [comment]
Hi! I think it should be Option + F7? It doesn't work for me too but simply selecting the keyword, right clicking and clicking "Find Usages" works for me so I'm using that method instead!

**Comment by ITZXITZX** [comment]
Is Option + F7 for mac?

**Comment by ITZXITZX** [comment]
Thanks!
