### ISSUE TITLE
editPersonDesciptor naming spelling error

### ISSUE THREAD

**Issue by ITZXITZX** [nus-cs2103-AY2425S1/forum#432]
Hi Prof,

I think there is a minor spelling error of the method editPersonDescriptor in the AB3 tutorial 1, under point 14 of tracing execution path.

![image](https://github.com/user-attachments/assets/08d78d4a-47e1-4743-8e10-c9b2d9088168)

**Comment by damithc** [comment]
Good catch, @ITZXITZX 
Fixed.
