### ISSUE TITLE
Trouble with Ui.png and README.md uploads

### ISSUE THREAD

**Issue by kimxw** [nus-cs2103-AY2425S1/forum#433]
I was notified via email my Ui.png and User Guide was not accessible via https://kimxw.github.io/ip/Ui.png and  https://kimxw.github.io/ip respectively. (gives 404)

However, I already followed the instructions to the best of my knowledge. I have the requisite files in docs/Ui.ong and docs/README.md
I genuinely dont know what else to try. Am I making a mistake?

My files seem to be located in the correct place as shown below. (thank you in advance~)

![image](https://github.com/user-attachments/assets/5ba5d25b-005b-48f7-86b6-65c8693999a5)

**Comment by Gra7ityIC3** [comment]
Did you enable the [GitHub pages feature](https://nus-cs2103-ay2425s1.github.io/website/se-book-adapted/projectDuke/index.html#a-userguide) for your fork?

**Comment by kimxw** [comment]
That was it. thank you so much!
