### ISSUE TITLE
Link to tP briefing video in Project page of Week 7 not working

### ISSUE THREAD

**Issue by SeanFoongjt** [nus-cs2103-AY2425S1/forum#434]
Hello profs,

I believe that there is a bug with the <span style="color:blue">__This week's tP briefing video__ link</span> on the Projects page of Week 7 as it is currently redirecting to a 404.
![image](https://github.com/user-attachments/assets/8d2b0efd-d59d-4940-8e61-6cc2faaac867)

**Comment by damithc** [comment]
Thanks for the bug report, @SeanFoongjt 
Fixed.
