### ISSUE TITLE
Tests in setting up AB3 developer environment

### ISSUE THREAD

**Issue by jktang14** [nus-cs2103-AY2425S1/forum#437]
I was setting up the developer environment. At step 3 where I am required to run tests,  Method 1 of using IntelliJ JUnit test runner runs fine and passes all tests.

However using method 2, when i type `./gradlew clean test`, I encounter the below error.
<img width="665" alt="Screenshot 2024-09-25 001009" src="https://github.com/user-attachments/assets/df6021bf-842d-4100-b42b-9bd7bee14998">

I have checked that i am using JDK17 and my gradle JVM is set to project SDK as well. What could the issue be?

**Comment by damithc** [comment]
@jktang14 Try running `java -version` before the `./gradlew clean test` to double-confirm you are using the correct Java version in that terminal.

**Comment by jktang14** [comment]
Hi Prof. I ran `java -version` as requested and it shows i am using the same version as my SDK as well
<img width="494" alt="Screenshot 2024-09-25 002307" src="https://github.com/user-attachments/assets/d5cd0a02-025c-434b-bc24-b5fdf02d30e0">

**Comment by damithc** [comment]
@jktang14 just to be sure, can you run the `java -version` command followed by `./gradew clean test` in the same terminal and give full output here? 
If it still doesn't work, you can also try cloning https://github.com/nus-cs2103-AY2425S1/tp to a new location in your computer and running the two commands against that.

**Comment by jktang14** [comment]
<img width="557" alt="Screenshot 2024-09-25 004144" src="https://github.com/user-attachments/assets/1e4a46a7-7695-468d-9baf-d5857224d528">

I have tried cloning to a different location and running both commands, I get the exact same outputs as the above picture as well.

**Comment by damithc** [comment]
While waiting for inputs from others, you can try remedies suggested in https://stackoverflow.com/questions/69696321/intellij-invalid-source-release-17, especially the ones related to `JAVA_HOME` environment variable.

**Comment by jktang14** [comment]
> While waiting for inputs from others, you can try remedies suggested in https://stackoverflow.com/questions/69696321/intellij-invalid-source-release-17, especially the ones related to `JAVA_HOME` environment variable.

This worked. My environment variable was indeed set to another JDK version. Thanks for the help Prof!
