### ISSUE TITLE
Requesting for help to smoke test jar file

### ISSUE THREAD

**Issue by btbrandon** [nus-cs2103-AY2425S1/forum#438]
i am a MacBook Air M2 user running on Sonoma 14.5

any help from windows/linux users to smoke test my jar file is greatly appreciated

here is the [user guide](https://btbrandon.github.io/ip/) and the [jar file](https://github.com/btbrandon/ip/releases/tag/A-Release)

**Comment by yashma-sonara** [comment]
Hi, dropping in from your senior batch!
I tried out your app in my windows machine. Seems to work well with the commands on your UG. 
Used both cmd command and directly running the file.

**Comment by ghost** [comment]
Hi I'm a senior from a previous batch, I've tested this on the following environments from the terminal
```
java -jar beebot.jar
```

### Windows 11 (My PC)

java 17.0.10 2024-01-16 LTS
Java(TM) SE Runtime Environment (build 17.0.10+11-LTS-240)

#### Terminal Output:
```
Sept 25, 2024 11:34:05 AM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @5a862460'
[]
________________________
Got it. I've added this task:
[T][ ] 1
Now you have 1 task in the list.
________________________
```

#### Commands Executed
asdf

> Please enter a valid command for worker bee to follow:
> 1\. todo <task name>
> 2\. deadline <task name> /by <due date>
> 3\. event <task-name> /from <start date> Ito <end date>
> 4\. mark
> 5\. unmark <index>
> 6\. list
> 7\. find <part of task name>
> 8\. update <task numbery /to <new name>
> 9\. delete <task number>
> 9\. bye

todo 1

> Growl... Honeyboo added '1' to the list!

list

> 1.[T][] 1

mark 1

> [bee]-utiful! Honeyboo marked this task as done:

#### Folders/Files Generated
```
-- beebot.jar
-- data
    `-- BeeBot.txt
```

#### Screenshot
![image](https://github.com/user-attachments/assets/5543aa9d-a043-429a-814e-a9d85ed36c94)

### Ubuntu 22.04 (VMWare Workstation 17 Player)

openjdk version "17.0.12" 2024-07-16
OpenJDK Runtime Environment OpenLogic-OpenJDK (build 17.0.12+7-adhoc.root.jdk17u)

#### Terminal Output
```
[]
________________________
Got it. I've added this task:
[T][ ] 1
Now you have 1 task in the list.
________________________
```

#### Commands Executed
asdf

> Please enter a valid command for worker bee to follow:
> 1\. todo <task name>
> 2\. deadline <task name> /by <due date>
> 3\. event <task-name> /from <start date> Ito <end date>
> 4\. mark
> 5\. unmark <index>
> 6\. list
> 7\. find <part of task name>
> 8\. update <task numbery /to <new name>
> 9\. delete <task number>
> 9\. bye

todo 1

> Growl... Honeyboo added '1' to the list!

list

> 1.[T][] 1

#### Folders/Files Generated
```
-- beebot.jar
-- data
    `-- BeeBot.txt
```

#### Screenshot
![image](https://github.com/user-attachments/assets/d6935f75-8709-43a8-95c8-7dfd2a3694e5)
