### ISSUE TITLE
Does modifying earlier commit messages require new release

### ISSUE THREAD

**Issue by Anvita2110** [nus-cs2103-AY2425S1/forum#439]
Am I supposed to release a new version if all I did was edit my earlier commit messages after the final release which was done on Sep 20, Friday (last day of final submission of IP)?

**Comment by damithc** [comment]
@Anvita2110 No need to do a new release if there are no changes to the code.

**Comment by Anvita2110** [comment]
@damithc  Ok noted, Thank you for reverting sir!
