### ISSUE TITLE
Facing warning in tp project while running it

### ISSUE THREAD

**Issue by Anvita2110** [nus-cs2103-AY2425S1/forum#441]
# What am I supposed to do about this warning with JavaFx version?

### Can someone suggest me the ways to rectify it or should I leave it like this since its a warning and not an error? 

> Sorry for night light filter on the image, I hope its clear enough

![image](https://github.com/user-attachments/assets/cf4818e4-ab56-4e3e-b781-b208210b4295)

**Comment by Incogdino** [comment]
I believe we can ignore it, else you can  try the suggestion in #211

**Comment by Anvita2110** [comment]
@Incogdino, Thankyou for your input, guess I will just ignore it since it does not make any improvement after downloading jar file.
