### ISSUE TITLE
AB3 Tutorial: Is the reference here updated?

### ISSUE THREAD

**Issue by ITZXITZX** [nus-cs2103-AY2425S1/forum#442]
AB3 Tutorial: Adding a Command

Hi, 

I was going through the "**AB3 Tutorial: Adding a Command**", under section "**Enhancing `RemarkCommand`**", and I clicked the [link](https://github.com/se-edu/addressbook-level3/commit/dc6d5139d08f6403da0ec624ea32bd79a2ae0cbf#diff-a8e35af8f9c251525063fae36c9852922a7e7195763018eacec60f3a4d87c594) at the bottom of the section. 

![image](https://github.com/user-attachments/assets/77838e56-2b27-4945-95f0-20b03fa0afdb)

Clicking the link brought me to this page, showing the changed that needed to be made for the section.

![image](https://github.com/user-attachments/assets/6c7c77b3-0893-4b7b-8acc-bed445d0fee7)

In the import statements above, I noticed this line:

```
import static seedu.address.commons.core.Messages.MESSAGE_INVALID_COMMAND_FORMAT;
```

This line caused an error because Messages was not found in the logic package.
When I checked the AB3 code, there doesn't seem to have the Messages class either.
Instead, following the intellij suggestion, I replaced the above line with this line:

```
import static seedu.address.logic.Messages.MESSAGE_INVALID_COMMAND_FORMAT;
```

It seems to work when I run the code, at least up till my current section.

May I check if anyone encountered this issue before and if it is ok to make such a replacement?

**Comment by Feng1231** [comment]
I've encountered this too.

Doesn't matter, just carry on with what intellij suggested.

That commit was probably done long time ago. Most likely AB3 had been refactored and constants were moved around after that commit.

**Comment by ITZXITZX** [comment]
ok, thanks!

**Comment by damithc** [comment]
> I've encountered this too.
> 
> Doesn't matter, just carry on with what intellij suggested.
> 
> That commit was probably done long time ago. Most likely AB3 had been refactored and constants were moved around after that commit.

Yup, thanks @Feng1231 for the quick response.
