### ISSUE TITLE
TP Tutorial 1 Week 6 help

### ISSUE THREAD

**Issue by WinstonJin** [nus-cs2103-AY2425S1/forum#443]
Hi guys, Mac user here, I keep on getting this error when following the steps for the team project tutorial 1 of week 6. So when pressing the debug button on the top right of the Main file, MainApp file etc, I get the error: 

```
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
```

or 

```
JavaFX runtime components are missing, and are required to run this application
```

<img width="1466" alt="Screenshot 2024-09-26 at 16 21 49" src="https://github.com/user-attachments/assets/b2231dcb-c6b3-49d8-9503-2ea560f36bfa">

Im not sure how to settle this issue and I cant seem to debug the code either way

Also, the second problem I am having is that the src/test/java/seedu.address/commons/util/AppUtilTest keeps on getting an error when I run the ```gradle build``` command. This is the specific line of code I get the error from

```
public class AppUtilTest {
    @Test
    public void getImage_exitingImage() {
        assertNotNull(AppUtil.getImage("/images/address_book_32.png"));
    }
```

and this is the error given to me

```
java.lang.RuntimeException: No toolkit found
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:278)
	at javafx.scene.image.Image.loadImage(Image.java:1080)
	at javafx.scene.image.Image.initialize(Image.java:815)
	at javafx.scene.image.Image.<init>(Image.java:705)
...
```

I have not changed any of the files since cloning the repo onto my intellij

**Comment by damithc** [comment]
@WinstonJin I added some extra steps to verify the AB3 set up, in https://se-education.org/guides/tutorials/ab3TracingCode.html
See if they help to resolve your issue.

![image](https://github.com/user-attachments/assets/679c0391-f367-490d-8214-d05fcd5e22d0)

**Comment by WinstonJin** [comment]
[celebrate]     Jin Zhong Tang Winston reacted to your message:
________________________________

**Comment by WinstonJin** [comment]
Thanks so much prof!

Also gonna leave this here for anyone else also having trouble for the Second part of the tp tutorial of Week 6

I still got some error when doing the ```./gradlew check``` so this is what I did to rectify this issue:

Change the toStringMethod() of test/java/seedu/address/model/person/PersonTest.java to be the following. It should be on line 93.

```
    @Test
    public void toStringMethod() {
        String expected = Person.class.getCanonicalName() + "{name=" + ALICE.getName() + ", phone=" + ALICE.getPhone()
                + ", email=" + ALICE.getEmail() + ", address=" + ALICE.getAddress() + ", remark=" + ALICE.getRemark()
                + ", tags=" + ALICE.getTags() + "}";
        assertEquals(expected, ALICE.toString());
    }
```

Second thing is to comment out the entire last method of test/java/seedu/address/storage/JsonAdaptedPersonTest.java. The method is toModelType_invalidTags_throwsIllegalValueException()

Only then do I get no errors for doing ```./gradlew check```

Maybe there's a better way to do it @damithc ?

**Comment by damithc** [comment]
> Also gonna leave this here for anyone else also having trouble for the Second part of the tp tutorial of Week 6
> 
> I still got some error when doing the `./gradlew check` so this is what I did to rectify this issue:
> 
> Change the toStringMethod() of test/java/seedu/address/model/person/PersonTest.java to be the following. It should be on line 93.
> 
> ```
>     @Test
>     public void toStringMethod() {
>         String expected = Person.class.getCanonicalName() + "{name=" + ALICE.getName() + ", phone=" + ALICE.getPhone()
>                 + ", email=" + ALICE.getEmail() + ", address=" + ALICE.getAddress() + ", remark=" + ALICE.getRemark()
>                 + ", tags=" + ALICE.getTags() + "}";
>         assertEquals(expected, ALICE.toString());
>     }
> ```

Thanks for sharing this @WinstonJin 
`./gradlew check` should pass without needing any changes, if you are using the tp code base we have provided. As you can see in https://github.com/nus-cs2103-AY2425S1/tp, the CI passed at the last commit, which means the `check` task passes.
In any case, I removed the mention of `./gradlew check` from Tutorial 1 because it is not strictly necessary for tracing the code.

**Comment by WinstonJin** [comment]
Thanks Prof!
