### ISSUE TITLE
Inability to set up user guide docs

### ISSUE THREAD

**Issue by starchypotatocode** [nus-cs2103-AY2425S1/forum#444]
Although by following instructions we can get https://ay2425s1-cs2103t-w14-3.github.io/tp/ to work, but the actual page checked for in the dashboard (https://ay2425s1-cs2103t-w14-3.github.io/tp/UserGuide.html) isn't working.
Swapping out the website links to the correct ones in the docs and site.json files doesn't seem to help much either.

We have decided to use MarkBind if that is relevant, and have set the Github Pages to key off the gh-pages branch. Thanks!

Not sure what other information to include here, so instead may I ask what could the typical possible causes of such problems be?

**Comment by damithc** [comment]
@starchypotatocode 

https://ay2425s1-cs2103t-w14-3.github.io/tp/  is currently showing `[root]/README.md` instead of `[root]/docs/README.md`
When you set up GitHub pages, you probably pointed it to the root folder rather than the docs folder.

The following instruction previously used `/[root]`, assuming the reader will change it to match the project folder structure. I've changed it to `/docs` now, to avoid readers mistakenly setting it to `/[root]`.
![image](https://github.com/user-attachments/assets/cbcf5845-4b9a-4ee7-bb42-f5ab9e4c5fb4)

**Comment by starchypotatocode** [comment]
Yep, it's resolved now: That took way too long to debug to no success on my own, thanks!

**Comment by damithc** [comment]
> The following instruction previously used `/[root]`, assuming the reader will change it to match the project folder structure. I've changed it to `/docs` now, to avoid readers mistakenly setting it to `/[root]`.
> ![image](https://private-user-images.githubusercontent.com/1673303/371148273-cbcf5845-4b9a-4ee7-bb42-f5ab9e4c5fb4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2MTg2MzcsIm5iZiI6MTcyNzYxODMzNywicGF0aCI6Ii8xNjczMzAzLzM3MTE0ODI3My1jYmNmNTg0NS00YjlhLTRlZTctYmI0Mi1mNWFiOWU0YzVmYjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjlUMTM1ODU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWMyMDkzODhhNjc4ZWYwYzljZDQwYzBmY2FlNjVkMDc0OTkyZjk0Mjc3NDk5MWU1MjA3NWI0ZTVhYzMzNjljMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.wV0PQh-ztUrErQ7xTHYjv9QM6C5w4a-cKJScsBT06Ao)

For anyone referring this issue, my fix given above is incorrect. It should be `/root`, as pointed out by #451

**Comment by starchypotatocode** [comment]
Looks like my reading comprehension wasn't quite up to par, at least it's fixed now?
(Previously the website was incorrect even though it loaded just fine)
