### ISSUE TITLE
AB3 tutorial 2 - Adding a new command 

### ISSUE THREAD

**Issue by Shruthiiii03** [nus-cs2103-AY2425S1/forum#445]
I have completed the code for adding the remark command for the tp on my side, and made sure that all the test cases can be passed. However, I keep encountering build errors (the ones for macOS and windows) and I am not sure what I am supposed to do. I double checked to make sure I am using the Zulu java 17 version. 

My development environment is IntelliJ and im using a Mac. I have figured out the build(ubuntu) but not the other two. 

<img width="1710" alt="Screenshot 2024-09-26 at 10 28 35 PM" src="https://github.com/user-attachments/assets/0dcef23b-db2d-4cbd-9009-827f788eb4a4">
<img width="1710" alt="Screenshot 2024-09-26 at 10 30 37 PM" src="https://github.com/user-attachments/assets/80f331ee-ebf8-4235-939c-2dab2deb2c44">

Does anyone have any tips on what I could do or where the error might be?

**Comment by starchypotatocode** [comment]
Did you make sure both checkStyles pass?

**Comment by yadobler** [comment]
If your ubuntu run is failing, then github actions will cancel all other tests in the same workflow.

The ubuntu-windows-macos are 3 threads in a single workflow

**Comment by damithc** [comment]
> If your ubuntu run is failing, then github actions will cancel all other tests in the same workflow.

Yup, the other two are cancelled because the build failed on one OS already.

**Comment by Shruthiiii03** [comment]
Thank you for your help @starchypotatocode @yadobler @damithc, the error was indeed my code not passing the Checkstyle tests. I have resolved the issue now and all three tests pass. Thank you!
