### ISSUE TITLE
Typo in Week 8 tP requirements

### ISSUE THREAD

**Issue by MAOXIONGKAI** [nus-cs2103-AY2425S1/forum#447]
Hi prof, I was taking a brief look at week 8's tP task(just to get rough idea of what to expect for future weeks, not attempting to do it now), I realized that there are some typos in the task description:
1. Under `Admin  tP: Practical Exam (PE) → Guidelines for bug triaging (extract 1)`
    1. In `Functionality bugs`, there is one part that says `be not than 8 digits`, which should be `be not more than 8 digits`.
    2. In `Feature flaws`, there is one part that says `instead, it shows the even in a ligher color`, which should be `instead, it shows the event in a lighter color`

**Comment by damithc** [comment]
Thanks for the bug report, @MAOXIONGKAI 
Fixed.
