### ISSUE TITLE
Not able to properly step into code during code tracing

### ISSUE THREAD

**Issue by minhao23** [nus-cs2103-AY2425S1/forum#449]
![image](https://github.com/user-attachments/assets/572bcdc6-9e27-4bac-a2c1-a03b9a87f739)
![image](https://github.com/user-attachments/assets/bd1395fb-631a-4082-aab1-94433d00cb87)

Hi, I keep encountering this "frames not available" error. I have tried adjusting the breakpoint to multiple places, but nothing seems to be working at the moment.
Does anyone else here have the same issue?

**Comment by damithc** [comment]
@minhao23 While waiting for input from others, things you can try:

* Try again after restarting Intellij
* Put the break point at a different location e.g., a normal statement rather than `try`
* Ensure you can run the application normally (not in debug mode) using the green play button

**Comment by damithc** [comment]
> @minhao23 While waiting for input from others, things you can try:
> 
>     * Try again after restarting Intellij
> 
>     * Put the break point at a different location e.g., a normal statement rather than `try`
> 
>     * Ensure you can run the application normally (not in debug mode) using the green play button

@minhao23 Any updates?

**Comment by starchypotatocode** [comment]
Looking at the top half of the screenshot, have you checked if
1) You removed all the other debugging breakpoints and
2) You were clicking the green bug icon not the green play button during testing?
