### ISSUE TITLE
Difference between working directory and local repo

### ISSUE THREAD

**Issue by rayray39** [nus-cs2103-AY2425S1/forum#45]
From what I have googled, the working directory and local repo are 2 different things but I am still confused as to what the both of them really mean. Is it that whenever I commit a change, git is actually tracking/updating the difference between the files inside my working directory and the local repo?

**Comment by ghos7ie** [comment]
Hi @rayray39, I googled around and I think this [stackoverflow answer](https://stackoverflow.com/a/61038693) helps a lot. There's a youtube video linked in it as well for a visual explanation :)

> TLDR: 
> Working Directory -> your project folder 
> Local Repo -> inside .git folder within your working directory. This is where Git handles your commits etc

Feel free to correct me if I'm wrong, I didn't know there's a difference either.

**Comment by Incogdino** [comment]
To answer this,
"Is it that whenever I commit a change, git is actually tracking/updating the difference between the files inside my working directory and the local repo?"

Git saves the staged files as a new commit in the local repo (.git directory). So yes, I guess it does in a sense "tracks/updates" the differences
