### ISSUE TITLE
critical path on a PERT chart

### ISSUE THREAD

**Issue by verakohh** [nus-cs2103-AY2425S1/forum#450]
<img width="621" alt="image" src="https://github.com/user-attachments/assets/75908d2d-f606-4c2a-ad8b-aad7b4687851">

hi! the description for a [critical path](https://arc.net/l/quote/nbyhzenm) states that 'In the example above, the shortest possible path is also the critical path.', but I don't see how the middle path is considered the shortest path if the path below it(persistency support design paths) is shorter. are all critical paths the shortest paths? or just paths which can't be delayed? thank you!

**Comment by damithc** [comment]
@verakohh Good question. The statement in question should be corrected as follows:

> ... In the example above, the ~~shortest possible~~ _shaded_ path is also the ...

I've updated it.

**Comment by verakohh** [comment]
@damithc Hi Prof, just to clarify, the shortest path would then be the persistency support path instead of the shaded path?

**Comment by damithc** [comment]
> @damithc Hi Prof, just to clarify, the shortest path would be then persistency support path instead of the shaded path?

@verakohh The shortest path doesn't matter. What matters is the critical path i.e., shortest path that still allows the projects to be completed, which is the shaded path.

**Comment by verakohh** [comment]
@damithc okay understood, thank you so much Prof Damith :)
