### ISSUE TITLE
MarkBind guide should indicate deployment from /[root] instead of /docs

### ISSUE THREAD

**Issue by IzN432** [nus-cs2103-AY2425S1/forum#451]
[![image](https://github.com/user-attachments/assets/dc5e7bec-be4b-48a7-b3f2-a43c995b7b99)](https://se-education.org/guides/tutorials/markbind-forked-sites.html#:~:text=latest%20%2D%2Dsave%2Ddev-,Updating%20documents,-MarkBind%20is%20a)
https://se-education.org/guides/tutorials/markbind-forked-sites.html#:~:text=latest%20%2D%2Dsave%2Ddev-,Updating%20documents,-MarkBind%20is%20a

In #444, @damithc mentioned making this change to /docs. The problem is that the team that opened issue #444 was deploying from master branch, while the image above is deploying from gh-pages branch, which by default does not have a /docs folder. This should be changed back to /[root] to avoid confusion (we were stuck on this for quite a bit haha)

**Comment by damithc** [comment]
@IzN432 Ops... the original `/root` was correct. Thanks for the heads up. A fix is being deployed right now.

> we were stuck on this for quite a bit haha

Sorry about that.
