### ISSUE TITLE
Error: tp build failed (Cause: zip END header not found)

### ISSUE THREAD

**Issue by sannie-beep** [nus-cs2103-AY2425S1/forum#452]
Hi, I am trying to clone the repo into my computer, but the console is giving this error and gradle does not seem to be working: 

![Screenshot 2024-09-30 145744](https://github.com/user-attachments/assets/f6520ddd-ee83-41c5-8cfb-6518db8c6d26)
This is the error message. I have followed all the steps required and tried multiple times, but neither me nor my teammates know why it is not working. 

1. I made the fork properly
2. I followed the correct steps to clone the repository
3. I updated the project settings and structure as follows: 
![Screenshot 2024-09-30 145756](https://github.com/user-attachments/assets/d0c4db22-1d65-46f1-9409-f16a5c145635)
![Screenshot 2024-09-30 145821](https://github.com/user-attachments/assets/67ba7a1d-8745-4c77-95b7-e066af183a31)

My Sourcetree remote seems to have some error, but I am not sure what exactly it is:
![Screenshot 2024-09-30 145730](https://github.com/user-attachments/assets/1ebcd4ba-1434-4fb1-b33d-4b1ca8f44bd3)

**Comment by damithc** [comment]
@sannie-beep Are you able to run the project using `.\gradlew run` from the terminal (outside of Intellij)?

**Comment by yadobler** [comment]
Try deleting `C:\Users\YOUR_USERNAME\.gradle` and running gradle again

Running gradle should give a clue as to which file in the dependency cache is corrupted but you can just clear all the gradlew cache files and try again

(on Linux/mac: `~/.gradle`)

**Comment by sannie-beep** [comment]
@yadobler 
Hi, thank you! Deleting the gradle folder worked! Semmed one or more files had gotten corrupted but when I deleted and reran, it seemed to work fine! :)

**Comment by damithc** [comment]
Good troubleshooting, @yadobler 💯
