### ISSUE TITLE
Java CI is not running for TP

### ISSUE THREAD

**Issue by Jianwen0451** [nus-cs2103-AY2425S1/forum#454]
<img width="1297" alt="Screenshot 2024-10-01 at 11 52 48 AM" src="https://github.com/user-attachments/assets/16cba605-b5fd-4b4b-95e3-d7a5bcb87641">
<img width="922" alt="Screenshot 2024-10-01 at 11 53 10 AM" src="https://github.com/user-attachments/assets/13921957-5763-4d93-b169-d381eceb5a64">

The picture above shows that the Java CI is not running for our TP.  Our .yml file is about the same as other groups whose Java CI is running correctly. Can I get an idea about what could go wrong with our TP setting?

**Comment by damithc** [comment]
hmm... strange. Can you share screenshots of the Actions settings (they are not visible to others)?

![image](https://github.com/user-attachments/assets/27004c10-e343-478a-a953-766843ce82b2)

**Comment by Jianwen0451** [comment]
These are the screen shot for runners and general
<img width="785" alt="Screenshot 2024-10-01 at 11 17 05 PM" src="https://github.com/user-attachments/assets/6f8697e8-3236-4dd6-a0b2-95b2986d6d78">
<img width="844" alt="Screenshot 2024-10-01 at 11 17 47 PM" src="https://github.com/user-attachments/assets/c9537706-4850-44dc-83e3-4978c65e154a">

**Comment by gerteck** [comment]
Hi, dropping by from previous semesters' batch.

Did you enable codecov (only one team member has to do it) last week?
* https://nus-cs2103-ay2425s1.github.io/website/schedule/week6/project.html
* https://nus-cs2103-ay2425s1.github.io/website/admin/appendixE-gitHub.html#tp-team-repo-setup
* https://nus-cs2103-ay2425s1.github.io/tp/DevOps.html

The Java CI includes uploading coverage reports to codecov, so not enabling it could cause some issues with CI not running. 

Cheers!

**Comment by damithc** [comment]
Another thing you can try is to create another org and set up the tp repo again in that org, to see if that one works as expected. Ideally, this should be done by someone other than the one who set up the first one, in case that person unconsciously missed a step or deviated from instructions in some other way.

**Comment by isaactodo** [comment]
Hey y'all, I'm from the same team as @Jianwen0451 and we managed to fix the issue. We are pretty sure that we have set up the team repo correctly (codecov, tokens, repo settings and all that) but the Java CI just wasn't running.

Here's how we fixed it: 
1. Create a new workflow in GitHub Actions
2. Choose Java with Gradle
3. Rename the file to something else other than gradle.yml (gradletest.yml for example)
4. Copy and paste the content of gradle.yml into gradletest.yml
5. Commit to repo

After we did these steps, we had two Java CI's and they both started running. Now, we can disable the new Java CI workflow and the old one should now be functioning correctly. So basically, adding a new workflow kickstarted the Java CI.

As for what caused this issue in the first place, we have no clue.

**Comment by damithc** [comment]
@isaactodo Thanks for sharing this. Good to here it got resolved. 
My guess is some intermittent error or GitHub side 'clogged' the CI pipeline the first time you set it up, but the second one 'unclogged' it. 
You can close this issue now.
