### ISSUE TITLE
Using Git CLI

### ISSUE THREAD

**Issue by AbdulrahmanAlRammah** [nus-cs2103-AY2425S1/forum#455]
In this week's project we were recommended to use git CLI. I would really rather avoid it and continue using source tree. Is git CLI tested in the final exam explicitly? Are there questions asking us to know how to use git CLI commands?

<img width="599" alt="image" src="https://github.com/user-attachments/assets/d8d05b96-445c-4efc-943a-114901d9c005">

**Comment by damithc** [comment]
@AbdulrahmanAlRammah Yes, basic Git commands are within the scope of the exam, although I wouldn't call it a 'heavily-tested'.
