### ISSUE TITLE
The given EditCommandTest is failing 

### ISSUE THREAD

**Issue by PrishaVP** [nus-cs2103-AY2425S1/forum#456]
Hi, I'm trying to submit my remark command tutorial pull request but for some reason one of the given tests in EditCommandTest is failing even though I dont recall changing the original code for this test. It seems like the expected model is different from the actual model. Is it the code accidentally got changed somehow or does anyone know what's causing this?

<img width="1108" alt="Screenshot 2024-10-02 at 2 40 50 AM" src="https://github.com/user-attachments/assets/3b01b7bf-9823-4f85-b92c-edc46fccf917">

**Comment by damithc** [comment]
@PrishaVP You can submit the PR and give the link here so that others can know exactly what you changed.
