### ISSUE TITLE
CI banner automated dashboard test failure

### ISSUE THREAD

**Issue by starchypotatocode** [nus-cs2103-AY2425S1/forum#457]
Looking at the dashboard, we have this problem noted: [README.md] CI banners not pointing to own project,
but on our end we have already changed things to `[![CI Status](https://github.com/ay2425s1-cs2103t-w14-3/tp/workflows/Java%20CI/badge.svg)](https://github.com/ay2425s1-cs2103t-w14-3/tp/actions)`
which should be pointing to our own project already?

**Comment by damithc** [comment]
@starchypotatocode You can try comparing the relevant line of your README.md with that of another team which got that item to turn green, to see if there is a difference in the text.

**Comment by damithc** [comment]
To add, it was because your badge URL had `ay2425s1-cs2103t-w14-3` instead of `AY2425S1-CS2103T-W14-3`
I've updated the dashboard code to ignore the case. Should be green now.
