### ISSUE TITLE
Updating index.md vs README.md

### ISSUE THREAD

**Issue by tingxuanp** [nus-cs2103-AY2425S1/forum#458]
Hi, for the updating of the product website for this week's tp tasks point 2, I accidentally updated the `index.md` file as well, since it was what appeared on the home page of the product website. May I check if I need to change it back to the original, or will we have to update it in the future so I can just leave it as is? Thank you.

**Comment by damithc** [comment]
@tingxuanp You can leave it as is.

**Comment by tingxuanp** [comment]
Thank you prof
