### ISSUE TITLE
Week 7 TP readme level of detail

### ISSUE THREAD

**Issue by vicelyav** [nus-cs2103-AY2425S1/forum#459]
Hi everyone, may I ask how detailed the readme for Week 7's TP task should be? Aside from adding the UI and modifying the CI, are we supposed to edit it to the level of detail of the User Guide of our IP based on our current feature lists? Thank you in advance :D.

**Comment by damithc** [comment]
@vicelyav You can follow the level of details in the current README. So, just update the current details; no need to add more details. In particular, it's not meant to be as detailed as a user guide, because there is a separate UG.

**Comment by vicelyav** [comment]
Alright, thank you
