### ISSUE TITLE
Should tags accumulate over time?

### ISSUE THREAD

**Issue by josh1248** [nus-cs2103-AY2425S1/forum#46]
Hey alls,

I have noticed that in my process of tagging, my older commits are getting many, many tags:

![image](https://github.com/user-attachments/assets/1c861b80-3f12-4118-a227-b799138117f2)
Most recent commit

![image](https://github.com/user-attachments/assets/7a7d7bc5-dd12-45ae-be93-c2b4c58e8c36)
Level 3 commit - but the subsequent tags are also present =O

I am asking around if anyone has also noticed this in their ip. In case it is relevant, I am using the GUI provided by IntelliJ and adding my tags from there. If so, do you think this is a desirable or expected use of tags?

**Comment by damithc** [comment]
@josh1248 Good point to look into. Thanks for raising it. While we wait for peer inputs, this is somewhat related:
![image](https://github.com/user-attachments/assets/d18c6704-a943-43aa-a0cb-72c1c8168edf)

**Comment by RezwanAhmed123** [comment]
Currently I am using Sourcetree to do the tagging and once I tag a commit, the commit tag does not move about unless I intentionally move them. New tags added also do not get added to my older commits. I would recommend using Sourcetree as mentioned in the course as I feel that it is closer to the command line (in that you can control things more specifically).

As you can see from this image the tags are stationary and do not change:
![image](https://github.com/user-attachments/assets/fd76667f-5afa-4e31-9735-2a9b2106d053)

i suspect it has to do with the way the git GUI on intellij shows the tags on each branch (maybe all the tags found on a future commit of a particular branch will be shown for all older commits).

You can double check using sourcetree accordingly.

**Comment by blanklogic** [comment]
> Hey alls,
> 
> I have noticed that in my process of tagging, my older commits are getting many, many tags:
> 
> ![image](https://private-user-images.githubusercontent.com/110712708/361114581-1c861b80-3f12-4118-a227-b799138117f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0ODcwMzEsIm5iZiI6MTcyNDQ4NjczMSwicGF0aCI6Ii8xMTA3MTI3MDgvMzYxMTE0NTgxLTFjODYxYjgwLTNmMTItNDExOC1hMjI3LWI3OTkxMzgxMTdmMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNFQwODA1MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNDFlMjUyZGQ1OGU3NWM5NjQ3NDI0ZjNhY2ZhNjAwZmJhMjE0MGYyMDVkMmY2YzM0MzEwOTZkYjIwNmYzZGExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WMoFSbXo9Lz-vSoF2esXxwWrwy_ZIBY3YfsJWcVXhLs) Most recent commit
> 
> ![image](https://private-user-images.githubusercontent.com/110712708/361114610-7a7d7bc5-dd12-45ae-be93-c2b4c58e8c36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0ODcwMzEsIm5iZiI6MTcyNDQ4NjczMSwicGF0aCI6Ii8xMTA3MTI3MDgvMzYxMTE0NjEwLTdhN2Q3YmM1LWRkMTItNDVhZS1iZTkzLWMyYjRjNThlOGMzNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNFQwODA1MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MjhlNWM3MmQzNWJhNzgwNzA0YzIzNDFjYWRlYmYxNzQ4MTc2Y2VjZDRjMjFiNmM2ODg3NjkwZmQwYjFjY2UxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BP5BpEarbK9FAofoCYjjqCf2mn79ko0aR_vJvVteTFA) Level 3 commit - but the subsequent tags are also present =O
> 
> I am asking around if anyone has also noticed this in their ip. In case it is relevant, I am using the GUI provided by IntelliJ and adding my tags from there. If so, do you think this is a desirable or expected use of tags?

Hi. I did not use any IDEs for git, utilised terminal to commit and tag my commits manually with `git tag Level-6` and so on, I see similar tags on my older commits on Github as well. My interpretation is that Github shows the tag on the current commit as well as subsequent/child tags as I have checked using `gitk` that I'm not tagging on multiple commits. I have also verified using `git show` and `git checkout` to check out different tags and showing the commit info. This is what I got:

```diff
j@MacBook-Air ip % git show
commit f454bb3f27c19c7ebaabd27cb016f7272137ce94 (HEAD -> master, tag: Level-6, origin/master, origin/HEAD)
Author: blanklogic <redacted@mail.com>
Date:   Thu Aug 22 15:34:04 2024 +0800

    Level 6. Implemented Delete functionality with appropriate error handling, included in list of commands

diff --git a/src/main/java/Friday.java b/src/main/java/Friday.java
index 244b909..0659c18 100644
--- a/src/main/java/Friday.java
+++ b/src/main/java/Friday.java
@@ -1,8 +1,9 @@
 import java.util.Objects;
 import java.util.Scanner;
+import java.util.ArrayList;
 
 public class Friday {
-    private final Task[] items = new Task[100];
j@MacBook-Air ip % git checkout Level-3
Note: switching to 'Level-3'.

HEAD is now at 9169c6d Level 3. Mark as Done. Implemented Task class and refactored code to utilize OOP concepts and modularized code for improved readability
j@MacBook-Air ip % git show
commit 9169c6d00b18cd65f34d047c95d98bc181dab39f (HEAD, tag: Level-3)
Author: blanklogic <redacted@mail.com>
Date:   Sun Aug 18 23:05:14 2024 +0800

    Level 3. Mark as Done. Implemented Task class and refactored code to utilize OOP concepts and modularized code for improved readability

diff --git a/src/main/java/Friday.java b/src/main/java/Friday.java
index cebfaf7..25025d3 100644
--- a/src/main/java/Friday.java
+++ b/src/main/java/Friday.java
@@ -2,35 +2,63 @@ import java.util.Objects;
 import java.util.Scanner;
 
 public class Friday {
-    public static void main(String[] args) {
-
-        String horizontalLine = "\t____________________________________________________________"; // For better readability
```

**Comment by josh1248** [comment]
Hi Prof and all, thanks for your inputs! I have switched over and tried the tagging using just the CLI - the same thing occurs. I have verified that my tags are stationary as they should be.

It seems that this is some quirk of GitHub, which displays all tags that are downstream from that release. Here are other people in the wild facing this quirk as well:
https://stackoverflow.com/questions/50542908/git-tag-tags-all-the-previous-commits-as-well
https://stackoverflow.com/questions/59308676/multiple-git-tags-appear-in-software-release-on-github

But I wonder why this is something that github has?

**Comment by damithc** [comment]
> It seems that this is some quirk of GitHub, which displays all tags that are downstream from that release.

Yup, it's a GitHub quirk. Thanks everyone for pitching in to reach this conclusion.

> But I wonder why this is something that github has?

No Idea. Doesn't seem to be useful (in fact the opposite of useful) in our context.
