### ISSUE TITLE
Should we include acknowledge of AB-3 in our developer guide as well?

### ISSUE THREAD

**Issue by MAOXIONGKAI** [nus-cs2103-AY2425S1/forum#461]
Hi prof, when doing this week's tP task I realized that apart from instruction of including acknowledgement of AB-3 in README, there's another section in developer guide called acknowledgement also but there seems to be no instruction on updating this part, may I check if we should acknowledge AB-3 in our developer guide as well? Thank you!

**Comment by damithc** [comment]
@MAOXIONGKAI You just need to update the README for now. You can update DG at a later time.
Acknowledging AB3 in the DG is optional.
