### ISSUE TITLE
Java CI failing 

### ISSUE THREAD

**Issue by Darren-Tung** [nus-cs2103-AY2425S1/forum#462]
![image](https://github.com/user-attachments/assets/3fb05f54-4c36-40a6-8947-5360324ae665)
Dear all, this is my team's dashboard and the CI is failing. We are requesting help to look into this. We also looked into a similar issue under https://github.com/nus-cs2103-AY2425S1/forum/issues/454 , but we could not solve the problem. 

We followed the codecov instructions under https://se-education.org/guides/tutorials/codecov.html
The only task we could not execute is step 5 as we cannot see the coverage status.
![image](https://github.com/user-attachments/assets/5209e293-378f-45a0-a5fd-2c0ea7f82b20)

Below are the extra details:

Team's repo actions (general)
![image](https://github.com/user-attachments/assets/26baa7e3-03ea-4891-9f53-1fa3e522ba9f)

Team's repo runner
![image](https://github.com/user-attachments/assets/d5a72881-fbc4-4d14-a5b8-f5d8762452a4)

Thanks All

**Comment by Darren-Tung** [comment]
@damithc may I request for your help

**Comment by damithc** [comment]
@Darren-Tung according to https://github.com/AY2425S1-CS2103T-T09-2/tp/actions/runs/11155458111/job/31006415610#step:5:6 one of your code files have trailing whitespaces Check to see if any of your edits left a whitespace at the end of a line

**Comment by damithc** [comment]
On a related noted, refer to https://se-education.org/guides/tutorials/intellijCodeStyle.html#tweak-auto-remove-trailing-spaces to find out how to configure Intellij to auto-remove trailing spaces.

**Comment by Darren-Tung** [comment]
Thank you Prof @damithc. Our team fixed everything.
