### ISSUE TITLE
npm ci creating vulnerabilities

### ISSUE THREAD

**Issue by ITZXITZX** [nus-cs2103-AY2425S1/forum#463]
Hi, has anyone encountered this situation when running the command `npm ci` on windows, under the [project root]/docs folder?

![image](https://github.com/user-attachments/assets/2fe6b585-a36f-423a-aa33-1ae800966d35)

**Comment by damithc** [comment]
@ITZXITZX This is likely caused by an outdated library used in MarkBind. You can ignore it.

**Comment by ITZXITZX** [comment]
Thanks!
