### ISSUE TITLE
Enquiry of submission for TP

### ISSUE THREAD

**Issue by winstonlimjy** [nus-cs2103-AY2425S1/forum#464]
hi, can i ask when's the dateline for this week's TP tasks except the 'workflow practice' session dated 3rd Oct 2359, but for 'Update the project website' as well as 'Update the DG: user stories, glossary, NFRs, use cases'?

In addition, when do we need to close the milestone 1.1? Thank you!

**Comment by damithc** [comment]
@winstonlimjy Steps 2 and 3 were intended to be part of v1.1 as well, but as it was not clearly specified in the instructions, you may push some of that work to v1.2.

![image](https://github.com/user-attachments/assets/4920949f-a5e7-4e96-8cd2-033bfddfb12c)


> when do we need to close the milestone 1.1?

The following applies.

![image](https://github.com/user-attachments/assets/67b1f98c-4942-4ecc-b9d4-cb0191d3fd13)

**Comment by winstonlimjy** [comment]
Thank you!
