### ISSUE TITLE
"Get Familiar with codebase" task deadline due when?

### ISSUE THREAD

**Issue by saajidshaik02** [nus-cs2103-AY2425S1/forum#465]
![image](https://github.com/user-attachments/assets/e95c6a98-2856-4313-8dc0-0ef3b24e0085)

Hello! When they mean, due by week 7, is it due by friday(tomorrow) or by this weekend, Sunday 2359?

Thank you!

**Comment by damithc** [comment]
> Hello! When they mean, due by week 7, is it due by friday(tomorrow) or by this weekend, Sunday 2359?

@saajidshaik02 

Deadline for weekly tasks: Friday 16:00
Deadline for tP iterations v1.1, v1.2 etc. : Thursday 23:59
