### ISSUE TITLE
What is AB3-Tutorial? Is everyone expected to do it?

### ISSUE THREAD

**Issue by samuelthen** [nus-cs2103-AY2425S1/forum#466]

**Comment by Feng1231** [comment]
It's probably the [week 6 TP task](https://nus-cs2103-ay2425s1.github.io/website/schedule/week6/project.html#4-get-familiar-with-the-codebase).

> Is everyone expected to do it?

I believe tutorial 2 is compulsory.

**Comment by AbdulrahmanAlRammah** [comment]
@damithc For the tutorial-adding-command. Do we have to follow the steps and obtain the final code or is it acceptable to read through but not apply everything? Since the code is already there, I prioritized just reading and seeing the workflow to save time.

**Comment by damithc** [comment]
> @damithc For the tutorial-adding-command. Do we have to follow the steps and obtain the final code or is it acceptable to read through but not apply everything? Since the code is already there, I prioritized just reading and seeing the workflow to save time.

@AbdulrahmanAlRammah Recommended to actually do it. In fact you'll need to do some minor tweaks to the given code to get it to work. There is a big difference between just reading a tutorial and actually doing it. The extra time spent here will pay dividends later by helping you to move faster in other coding work in the tP.
