### ISSUE TITLE
Members photo in `AboutUs.md` not detected as completed in the tracker task `website adapted`

### ISSUE THREAD

**Issue by gohyongjing** [nus-cs2103-AY2425S1/forum#467]
[Asking on behalf of Team CS2103-F13-1]

The team has uploaded the photos to `AboutUs.md`, but it marked as not complete
<img width="643" alt="Screenshot 2024-10-04 at 9 52 40 PM" src="https://github.com/user-attachments/assets/1e40ff15-6459-4e11-8ac8-173807494f79">

![image](https://github.com/user-attachments/assets/9e243578-d04d-4be5-9e67-4781e4628762)

Could it be that the tracker is looking for `src="images/github_username_in_lower_case.png"` directly from the `AboutUs.md`? Because their `AboutUs.md` is refactored to utilise Jekyll's include tag but the respective members.md has the correct `images/github_username_in_lower_case.png`?

**Comment by shotnothing** [comment]
it needs to be your github handle

**Comment by shotnothing** [comment]
i almost made this mistake too till my teammates told me haha

**Comment by damithc** [comment]
> Could it be that the tracker is looking for `src="images/github_username_in_lower_case.png"` directly from the `AboutUs.md`? Because their `AboutUs.md` is refactored to utilise Jekyll's include tag but the respective members.md has the correct `images/github_username_in_lower_case.png`?

Yup. Our grading scripts will not follow `{% include ...` links. So, avoid using them in tP documentation. Instead, put all relevant content in the parent `.md` file itself.

**Comment by gohyongjing** [comment]
Thanks all for the help!
