### ISSUE TITLE
Clarifying Week 8 tp Task: Add the first functionality increment

### ISSUE THREAD

**Issue by JoanneHing** [nus-cs2103-AY2425S1/forum#469]
<img width="868" alt="Screenshot 2024-10-05 at 5 52 32 PM" src="https://github.com/user-attachments/assets/cee234fa-9434-4c04-9144-96767ea6c08c">

Hi prof, our team is a bit unsure about how much we need to complete to satisfy the requirement of adding first functionality increment. As each of us is assigned 1 or 2 MVP feature to work on, for this week is it we just need to do some part of the feature increment?

For example: We have new fields for adding new data
So the task we need to do is to
1. add the field
2. do valid check of the field format
3. store and read the field from json format
4. ....

For this week is it that we can pick to do adding the fields as part of the increment and continue to work on it on the upcoming week or we need to do more than that?

Hope my question is clear. Thank you!

**Comment by damithc** [comment]
@JoanneHing The minimum requirement for v1.1 is, each person merges at least one PR that changes functional code. The more you do in v1.1, the less you'll need to do in v1.2 and later. So, proceed in small steps (i.e., small PRs), but do as much as you can afford to, based on the time you have.

**Comment by JoanneHing** [comment]
Thank you prof for the clarification! May I ask does missing a bit on this deadline affect the team progress? As some of the team mates may still having quite some midterm in Week 8.

**Comment by damithc** [comment]
> Thank you prof for the clarification! May I ask does missing a bit on this deadline affect the team progress? As some of the team mates may still having quite some midterm in Week 8.

@JoanneHing I added the follow FAQ just now, to answer this question:

![image](https://github.com/user-attachments/assets/12999df4-cdeb-42ba-b315-191a5e5baf32)

**Comment by JoanneHing** [comment]
Thank you prof for the clarification!
