### ISSUE TITLE
Issues With Tags and Dashboard Tracking

### ISSUE THREAD

**Issue by jan-kai1** [nus-cs2103-AY2425S1/forum#47]
Hi, I am having issues with getting my tags tracked on the dashboard. Currently I have added tags up till Level-6 but only up till Level-3 was tracked
![image](https://github.com/user-attachments/assets/2046a73b-fdd9-4070-880d-ca0f878b31af)
![image](https://github.com/user-attachments/assets/2b0319d1-2688-453f-bac4-b41d46c4bcb0)

I followed the troubleshooting guide, verified the commits were in the master branch and did not see the does not belong to any branch warning 
![image](https://github.com/user-attachments/assets/6d9d6ec9-5e21-48ae-b869-5d2e7997b645)

I am unsure about the remedy stated in the troubleshooting guide as I only have the master branch on my local machine
Remedy: Wait till the branch that has the tag is merged to the master branch, push the master branch to the fork.
![image](https://github.com/user-attachments/assets/34319fe3-eeb6-4634-90ee-18a3228cb114)

Am I misunderstanding the guide? Not sure how only my first 3 level tags were tracked

**Comment by damithc** [comment]
@jan-kai1 If  you pushed a tag only _after_ the last time the dashboard was updated, it will not appear in the  dashboard, even if the tag was created earlier.
![image](https://github.com/user-attachments/assets/90df211d-bf73-4403-97e3-482c946988b7)

You can wait till the next dashboard update and check again.

**Comment by jan-kai1** [comment]
The commits that were pushed from before the last update (Text ui testing, Level 4 and 5) aren't shown to be updated as well, will wait till next dashboard update and see if they are tracked

**Comment by damithc** [comment]
> The commits that were pushed from before the last update (Text ui testing, Level 4 and 5) aren't shown to be updated as well, will wait till next dashboard update and see if they are tracked

@jan-kai1 As pushing commits doesn't automatically push the corresponding tags, it is still possible the tag was pushed at a later time.

**Comment by jan-kai1** [comment]
update: tracking works, was probably due to not pushing tags along with corresponding commits
