### ISSUE TITLE
Accidentally clicked on redo iP peer evaluation, do I redo and submit?

### ISSUE THREAD

**Issue by Quasant** [nus-cs2103-AY2425S1/forum#472]
As mentioned in the title, I'm not sure if my initial submission has already been recorded somehow, and I'm worried if re-submission results in some wonky behaviors in the cs2103 system.

**Comment by damithc** [comment]
@Quasant You can let it be, for now. If there is any issue, we'll contact you in due course.

**Comment by Quasant** [comment]
Got it, thanks! I will close this issue for now.
