### ISSUE TITLE
Changing Feature Specification

### ISSUE THREAD

**Issue by S-K-Y-Light** [nus-cs2103-AY2425S1/forum#473]
Hi @damithc , is it possible for our Team Project to change one our feature specification for the MVP? One of our MVP Features "Update" currently updates students by taking the Student's Name. However, we think it might be better to update Students by their index, and that would require changes in the command format & parameters of the update function.

**Comment by damithc** [comment]
@S-K-Y-Light you can change your features any time. The feature spec submission was simply a starting point only. You can evolve it as you wish, provided you don't violate any project constraints.

**Comment by S-K-Y-Light** [comment]
Alright thank you @damithc. May I clarify if our team needs to resubmit the "MVP Feature Specification"?

**Comment by damithc** [comment]
> Alright thank you @damithc. May I clarify if our team needs to resubmit the "MVP Feature Specification"?

@S-K-Y-Light No need.

**Comment by S-K-Y-Light** [comment]
Alright, thank you!
