### ISSUE TITLE
Adding tests for UI components

### ISSUE THREAD

**Issue by Green-Tea-123** [nus-cs2103-AY2425S1/forum#474]
I was working on the next iteration of the tp and sent a PR only for it to fail Codecov's test coverage. After looking at the areas where coverage is supposed to be missing, I found that majority of the missing coverage was in the UI components I have added to the project. I presumed that UI components were not required to be tested as the tp's original code had no tests for the UI components, but I might have to to pass Codecov's check. Is there any way to write tests for these components?

**Comment by MAOXIONGKAI** [comment]
I think can refer to this past issue [Codecov test failing](https://github.com/nus-cs2103-AY2425S1/forum/issues/325) if the UI components are hard to test. From week 8's topics it seems like we aren't really expected to learn how to carry out those automated GUI testing, and test coverage itself is not really part of the assessing criteria

**Comment by damithc** [comment]
> I think can refer to this past issue [Codecov test failing](https://github.com/nus-cs2103-AY2425S1/forum/issues/325) if the UI components are hard to test.

Yup. Thanks @MAOXIONGKAI 

@Green-Tea-123 I added the following FAQ to the website just now.

![image](https://github.com/user-attachments/assets/566fd3ff-0674-4a62-97b4-8411f2a439c8)

**Comment by Green-Tea-123** [comment]
Thank you all for answering, I will discuss this with my team and close the issue.
