### ISSUE TITLE
Will we be penalised in the PE if an invalid address is keyed in as an address field?

### ISSUE THREAD

**Issue by ITZXITZX** [nus-cs2103-AY2425S1/forum#476]
Example of invalid address "asdadasdasd" or "Clementi block 2103, #50-50", which is not an actual address either.

**Comment by damithc** [comment]
@ITZXITZX The 'official' guidelines are cited in https://nus-cs2103-ay2425s1.github.io/website/schedule/week8/project.html

![image](https://github.com/user-attachments/assets/40f2e203-371a-495c-b474-36244f03272b)

It depends on the following two questions:
1. Is there a 'better' behavior, compared to current behavior? 
2. Is implementing that better behavior more important than the work done already (or could it have been done without needing any extra effort)?

If the answer is 'no' to either question, there is no penalty for the dev team.
The answers depend on the app itself -- so, it needs to be case-by-case.

**Comment by ITZXITZX** [comment]
Thanks Prof!
