### ISSUE TITLE
Creating PR without a fork

### ISSUE THREAD

**Issue by jowhee3011** [nus-cs2103-AY2425S1/forum#477]
For the AB3 tutorial, I've cloned the repo into my local without forking. Hence, I don't have a repo in my github and am unable to create a PR on my team's repo.

Can I ask how can I go about this?

**Comment by AbdulrahmanAlRammah** [comment]
I think you can correct this by forking your team's repo now and then cloning your fork. 

To do a PR push changes to your fork. When you go to your fork on github website it will suggest creating a PR. You can click on that, if it doesn't suggest can read back material on how to create a PR. 

Even if you do not fork the repo you should still be able to create a PR but the PR will be from a branch to main branch in the main repo. This is called the feature workflow whereby all team members push to branches in the main repo while working and then create a PR from that branch to main. However, until tp V1.3 we are meant to follow the forking workflow so for now just fork and flow the forking workflow.

**Comment by damithc** [comment]
> I think you can correct this by forking your team's repo now and then cloning your fork.

@jowhee3011 Alternatively, you can fork the team repo, and configure the remote name `origin` of your existing clone to point to your fork (currently it must be pointing to your team repo). After that, you can push any new commits/branches (if any) to your fork. Ask here if you can't figure out how to perform any of those steps.

**Comment by jowhee3011** [comment]
Thank you! I have managed to create a PR now.
