### ISSUE TITLE
Quiz 1, question 11: Options C and D seem to be duplicates

### ISSUE THREAD

**Issue by emmannyyy** [nus-cs2103-AY2425S1/forum#480]
![image](https://github.com/user-attachments/assets/11e7424c-ed9b-4420-9110-5732aeffd57b)

Regarding this question, is there any difference between options C and D?

**Comment by tata32000** [comment]
I think it’s supposed to be a trick question. Option C has number above the line but option D is below.

**Comment by damithc** [comment]
> I think it’s supposed to be a trick question. Option C has number above the line but option D is below.

@emmannyyy Your question is on the right track (that's what you were _expected_ to ask after reading this quest :-). 
@tata32000 is correct. No real difference. The question aims to show that the position of the multiplicity (i.e.., above or below the line) doesn't matter.

**Comment by emmannyyy** [comment]
ah I see! Thanks prof @damithc , and thank you @tata32000 

My apologies, I realised I immediately got the quiz results upon submission. Will close this thread now. 

Thank you!
