### ISSUE TITLE
tP: Unsure of How to Publish Docs

### ISSUE THREAD

**Issue by yu7ong** [nus-cs2103-AY2425S1/forum#482]
Although my team's documentation is accessible via this link: https://ay2425s1-cs2103t-t17-3.github.io/tp/UserGuide.html, the tP dashboard shows that our docs have not been published.
We’ve configured the site using MarkBind. 

Is there something we're missing? Any advice would be appreciated!

**Comment by damithc** [comment]
@yu7ong This is a week 6 deliverable. We stopped checking for it a week after week 6 ended.
I've triggered the check manually. It should turn green at the next dashboard update.
In future, remember to rectify any red items within few days (max: 1 week) after the weekly deadline is over (Friday 4pm).

**Comment by yu7ong** [comment]
Noted with thanks. We did do the tasks for the respective week but we knew later that it didn't turn green and it was quite late by then. We will take note next time.
