### ISSUE TITLE
Issue with CodeCov in CI

### ISSUE THREAD

**Issue by keithxun** [nus-cs2103-AY2425S1/forum#483]
![image](https://github.com/user-attachments/assets/6ca3bac8-ac77-4ed2-8ec7-94ccd58585e5)

Hi, I am currently facing an issue with Codecov where it does not cover new files that I have created, named as session and sessionName. Did anyone else get this issue or am I doing something incorrectly?

**Comment by keithxun** [comment]
Nvm, it seem that I have mistaken how Codecov works. I have to write test cases for the new code that I have written. will be closing the issue now.

**Comment by damithc** [comment]
@keithxun The following FAQ may be useful as well.

![image](https://github.com/user-attachments/assets/d7f122f2-ed3d-46b1-8b0d-b7a52621fd54)
