### ISSUE TITLE
PR failing CodeCov

### ISSUE THREAD

**Issue by JoanneHing** [nus-cs2103-AY2425S1/forum#484]
<img width="880" alt="Screenshot 2024-10-09 at 11 47 36 AM" src="https://github.com/user-attachments/assets/91841d01-6970-4034-898a-5d2b6a720cfe">

Hi prof, our team is working on adding some new field and methods, the CI is passing but codecov is failing because insufficient testcase is provided. We want to ask is it necessary for us to add in the test cases for the current increment? Are we allowed to merge in our PR with the failing CodeCov or we must fix it? As the course mention we must pass the JavaCI but the CodeCov part is a bit unclear.

**Comment by damithc** [comment]
@JoanneHing There are several options, covered in [one of the this FAQs in this week](https://nus-cs2103-ay2425s1.github.io/website/schedule/week8/project.html#:~:text=PR%20CI%20fails%20because%20Codecov%20reports%20a%20drop%20in%20code%20coverage.%20What%20to%20do%3F).

**Comment by JoanneHing** [comment]
Alright thank you prof for the clarification!
