### ISSUE TITLE
Run with no error but no JavaFX window popping out

### ISSUE THREAD

**Issue by tansanchian** [nus-cs2103-AY2425S1/forum#485]
My code runs without any error when i click build, and I even tried to check out the master branch with the orginal AddressBook code in it, but the problem still persists. Basically, when I run build, there is an icon shown up in the task bar 
![{382545BA-B242-4DE6-AF88-6EBCA7F22C11}](https://github.com/user-attachments/assets/02009137-3278-4b3e-9744-decd6d4b758c)
But it looks like this 
![{DC979BFF-3C16-4606-9354-2214041DEAC8}](https://github.com/user-attachments/assets/e1232d93-3719-45c7-b060-84f667df90f1)
and when i click the icon nothing happen. I have no idea what is going on. Below is the log of my file. 

Oct 09, 2024 4:14:55 PM seedu.address.Main main
WARNING: The warning about Unsupported JavaFX configuration below (if any) can be ignored.
Oct 09, 2024 4:14:55 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @6402f9e3'
Oct 09, 2024 4:14:56 PM seedu.address.MainApp init
INFO: =============================[ Initializing AddressBook ]===========================
Oct 09, 2024 4:14:56 PM seedu.address.MainApp initConfig
INFO: Using config file : config.json
Oct 09, 2024 4:14:56 PM seedu.address.commons.util.JsonUtil readJsonFile
INFO: JSON file config.json found.
Oct 09, 2024 4:14:56 PM seedu.address.commons.core.LogsCenter init
INFO: Log level will be set as: INFO
Oct 09, 2024 4:14:56 PM seedu.address.MainApp initPrefs
INFO: Using preference file : preferences.json
Oct 09, 2024 4:14:56 PM seedu.address.commons.util.JsonUtil readJsonFile
INFO: JSON file preferences.json found.
Oct 09, 2024 4:14:56 PM seedu.address.MainApp initModelManager
INFO: Using data file : data\addressbook.json
Oct 09, 2024 4:14:56 PM seedu.address.MainApp initModelManager
INFO: Creating a new data file data\addressbook.json populated with a sample AddressBook.
Oct 09, 2024 4:14:56 PM seedu.address.MainApp start
INFO: Starting AddressBook V0.2.2ea
Oct 09, 2024 4:14:56 PM seedu.address.ui.UiManager start
INFO: Starting UI...

This is my project structure:
![{497ADDB1-6A5F-4D61-908A-ADAEB90A7224}](https://github.com/user-attachments/assets/9c8d9ba2-7829-401f-9d52-37e506292dc7)

**Comment by shotnothing** [comment]
maybe try restarting your computer?

**Comment by Feng1231** [comment]
Are you coding on two different computers and the files is stored on one drive? Mine had the same issue as well, not sure if it's the case for you too

**Comment by tansanchian** [comment]
I have tried restarting my computer. I am saving the local repo in my C drive storage and I just code on my own computer.

**Comment by damithc** [comment]
@tansanchian to establish a baseline, you can do the following:

* Clone https://github.com/nus-cs2103-AY2425S1/tp to your computer
* Open a terminal, and navigate to the clone location
* Run `java -version` to confirm you are using Java 17
* Run `./gradlew run` to see if the AB3 GUI appears as expected

**Comment by tansanchian** [comment]
ya, it works fine! But i didnt change any dependencies and configuration of my repo though.

**Comment by tansanchian** [comment]
Ah, I realized what happened.
![{114CAC37-B7A0-4A0E-999A-9D709173A30E}](https://github.com/user-attachments/assets/b4a452e9-ac65-4f13-9d3e-7f505d2ddfd8)
It just stuck at 75% and wont move further. But what causes this?

**Comment by damithc** [comment]
> Ah, I realized what happened.
> ![{114CAC37-B7A0-4A0E-999A-9D709173A30E}](https://private-user-images.githubusercontent.com/142957529/374909638-b4a452e9-ac65-4f13-9d3e-7f505d2ddfd8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NjkwNTksIm5iZiI6MTcyODQ2ODc1OSwicGF0aCI6Ii8xNDI5NTc1MjkvMzc0OTA5NjM4LWI0YTQ1MmU5LWFjNjUtNGYxMy05ZDNlLTdmNTA1ZDJkZGZkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOVQxMDEyMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NDVjOWJmYTkwOTVjYTJmMjBkYjYzZmRkNjczM2I0OTE4N2FhZDFmNzdmMTdiOGNlNzhiNWQwNGRlYWQwNDcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nGf0hD0AHgFnBPOMcYuQT9lkmU9fKfFJ4mRxrIAqy7Q)
> It just stuck at 75% and wont move further. But what causes this?

@tansanchian Gradle is waiting for you to close the GUI.

**Comment by tansanchian** [comment]
wait then so what is the issue?

**Comment by tansanchian** [comment]
What I can do to reset the dependencies/cache? I have no idea what to do now

**Comment by damithc** [comment]
@tansanchian 

A) We established that AB3 can work in your computer, which means your computer has the required software.
B) Previously you reported that your team repo's master branch doesn't work, apparently, in your Intellij. 

So, now we can move from A to B in small steps, to see where the problem happens.

For example, you can now try to open AB3 (that you cloned in A) in Intellij and try to run it from there, to see if it is a problem with your Intellij set up.
Is that works too, next you can clone your team repo to a fresh location and try running it via Gradle, to see if the problem is in your team repo's master branch.
Then try the running it using Intellij.

**Comment by tansanchian** [comment]
Thanks a lot for the help! It works now and I didn't change a single thing, I think its just some random bug.
