### ISSUE TITLE
Unable to email cs2103@comp.nus.edu.sg

### ISSUE THREAD

**Issue by yihuididi** [nus-cs2103-AY2425S1/forum#486]
![Screenshot 2024-10-09 at 4 35 05 PM](https://github.com/user-attachments/assets/ec7ae183-65b8-4ac9-b2e4-493763102ebf)

I wanted to email `cs2103@comp.nus.edu.sg` regarding TP but my mail was not delivered. Instead, I received this reply from microsoft as shown in the screen shot. I used my nus email to send this email (E....@nus.ed.sg).

Did anyone encounter this issue before and how do I resolve this? Thanks!

**Comment by damithc** [comment]
@yihuididi `.sg` not `.eg` 😁
