### ISSUE TITLE
What to do about path coverage if it is not 100%?

### ISSUE THREAD

**Issue by Anvita2110** [nus-cs2103-AY2425S1/forum#487]
## How do I rectify this? Or is it even an error to be rectified?

------------------------------------------------------------------------------------------------------------------------------------------------------

![image](https://github.com/user-attachments/assets/79f8c7cd-a9bd-4723-a9b1-98afdbf63128)

**Comment by damithc** [comment]
@Anvita2110 See if the following FAQ answers your question:

![image](https://github.com/user-attachments/assets/d982fb83-6661-4ca0-9ed0-ec7d015e62b2)
