### ISSUE TITLE
Sequence Diagram in Week 8 Quiz

### ISSUE THREAD

**Issue by yockcheng** [nus-cs2103-AY2425S1/forum#489]
<img width="929" alt="Screenshot 2024-10-10 at 10 43 10 AM" src="https://github.com/user-attachments/assets/c9d079fd-4773-4d31-aad1-ab09169f4f3c">

Can I check if there should be a supposed left-to-right sequence for the objects because it seems from this question that the dog object can appear on the left of the man object despite being created later. Thanks!

**Comment by damithc** [comment]
@yockcheng there is no specific meaning on horizontal ordering (i.e., left-to-right). But vertical ordering has a meaning (i.e., time goes from top-to-bottom).

**Comment by yockcheng** [comment]
Okay thank you!
