### ISSUE TITLE
Milestone v1.2 not detected

### ISSUE THREAD

**Issue by JoanneHing** [nus-cs2103-AY2425S1/forum#490]
<img width="1234" alt="Screenshot 2024-10-10 at 12 23 11 PM" src="https://github.com/user-attachments/assets/76dad396-0649-466e-82fd-5a16e210ec8c">
As shown from the image above, our team had set up milestone v1.2 before but it is not detected by the tP progress, do Prof has any idea why is it not detected?
<img width="697" alt="Screenshot 2024-10-10 at 12 23 42 PM" src="https://github.com/user-attachments/assets/27ba337c-5571-406f-87cf-a34ac5457777">

**Comment by damithc** [comment]
@JoanneHing CS2103T-W11-3? Seems to be green?
![image](https://github.com/user-attachments/assets/3bd04290-a86b-4ecc-b81c-d1e64a4a4720)

**Comment by JoanneHing** [comment]
Oh! Maybe it wasn't updated on my side just now! I just checked and it is green now, thank you prof!
