### ISSUE TITLE
Ui code not passing the tests

### ISSUE THREAD

**Issue by celeschai** [nus-cs2103-AY2425S1/forum#492]
<img width="1341" alt="image" src="https://github.com/user-attachments/assets/822519c7-dcc5-4583-a105-faa2de49fff7">
Hi may I know if anyone else faces the same issue and whether this needs to be resolved?

**Comment by damithc** [comment]
@celeschai While waiting for inputs from others, you can share some more information:

* Which 'original code' are you running? The `master` branch of your team repo? 
* What happens if you run clone that repo to a fresh location and run the `.\gradlew test` command?

**Comment by celeschai** [comment]
[Test results - Class Gradle Test Executor 3.pdf](https://github.com/user-attachments/files/17330174/Test.results.-.Class.Gradle.Test.Executor.3.pdf)
This is the error message I recevied.

**Comment by damithc** [comment]
@celeschai That's not exactly what I had in mind. Here are more detailed steps.

1. Clone your team repo into an empty folder again
2. Open a terminal, and `cd` into that folder
3. Run the `java -version` command to confirm you are using Java 17
4. Run the `.\gradlew test` command.
5. Post the output of the above two commands here.

**Comment by celeschai** [comment]
Hi prof, thank you for the instructions, the test now passed, although I am not exactly sure why.

```
Starting Gradle Daemon...
Gradle Daemon started in 352 ms

> Task :compileJava
> Task :processResources
> Task :classes
> Task :compileTestJava
> Task :processTestResources
> Task :testClasses
> Task :test
Oct 12, 2024 2:05:17 PM seedu.address.AppParameters parse
WARNING: Invalid config path a. Using default config path.
Oct 12, 2024 2:05:18 PM seedu.address.commons.util.JsonUtil readJsonFile
INFO: JSON file src/test/data/ConfigUtilTest/EmptyConfig.json found.
Oct 12, 2024 2:05:18 PM seedu.address.commons.util.JsonUtil readJsonFile
INFO: JSON file src/test/data/ConfigUtilTest/TypicalConfig.json found.
Oct 12, 2024 2:05:18 PM seedu.address.commons.util.JsonUtil readJsonFile
INFO: JSON file /var/folders/l5/zgn14k2x33v8hpzph3zxgpfr0000gn/T/junit3084446448538816174/TempConfig.json found.
Oct 12, 2024 2:05:18 PM seedu.address.commons.util.JsonUtil readJsonFile
INFO: JSON file /var/folders/l5/zgn14k2x33v8hpzph3zxgpfr0000gn/T/junit3084446448538816174/TempConfig.json found.
Oct 12, 2024 2:05:18 PM seedu.address.commons.util.JsonUtil readJsonFile
INFO: JSON file src/test/data/ConfigUtilTest/ExtraValuesConfig.json found.
Oct 12, 2024 2:05:18 PM seedu.address.commons.util.JsonUtil readJsonFile
INFO: JSON file src/test/data/ConfigUtilTest/NotJsonFormatConfig.json found.
Oct 12, 2024 2:05:18 PM seedu.address.commons.util.JsonUtil readJsonFile
WARNING: Error reading from jsonFile file src/test/data/ConfigUtilTest/NotJsonFormatConfig.json: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'this': was expecting 'null', 'true', 'false' or NaN
 at [Source: this file is not in json format!
; line: 1, column: 5]
Oct 12, 2024 2:05:18 PM seedu.address.logic.LogicManager execute
INFO: ----------------[USER COMMAND][uicfhmowqewca]
Oct 12, 2024 2:05:18 PM seedu.address.logic.LogicManager execute
INFO: ----------------[USER COMMAND][add n/Amy Bee p/11111111 e/amy@example.com a/Block 312, Amy Street 1]
Oct 12, 2024 2:05:18 PM seedu.address.logic.LogicManager execute
INFO: ----------------[USER COMMAND][list]
Oct 12, 2024 2:05:18 PM seedu.address.logic.LogicManager execute
INFO: ----------------[USER COMMAND][add n/Amy Bee p/11111111 e/amy@example.com a/Block 312, Amy Street 1]
Oct 12, 2024 2:05:18 PM seedu.address.logic.LogicManager execute
INFO: ----------------[USER COMMAND][delete 9]
Oct 12, 2024 2:05:18 PM seedu.address.commons.util.JsonUtil readJsonFile
INFO: JSON file src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json found.
Oct 12, 2024 2:05:18 PM seedu.address.storage.JsonAddressBookStorage readAddressBook
INFO: Illegal values found in src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json: Names should only contain alphanumeric characters and spaces, and it should not be blank
Oct 12, 2024 2:05:18 PM seedu.address.commons.util.JsonUtil readJsonFile
INFO: JSON file src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json found.
Oct 12, 2024 2:05:18 PM seedu.address.storage.JsonAddressBookStorage readAddressBook
INFO: Illegal values found in src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json: Phone numbers should only contain numbers, and it should be at least 3 digits long
Oct 12, 2024 2:05:18 PM seedu.address.commons.util.JsonUtil readJsonFile
INFO: JSON file /var/folders/l5/zgn14k2x33v8hpzph3zxgpfr0000gn/T/junit358006438962909149/TempAddressBook.json found.
Oct 12, 2024 2:05:18 PM seedu.address.commons.util.JsonUtil readJsonFile
INFO: JSON file /var/folders/l5/zgn14k2x33v8hpzph3zxgpfr0000gn/T/junit358006438962909149/TempAddressBook.json found.
Oct 12, 2024 2:05:18 PM seedu.address.commons.util.JsonUtil readJsonFile
INFO: JSON file /var/folders/l5/zgn14k2x33v8hpzph3zxgpfr0000gn/T/junit358006438962909149/TempAddressBook.json found.
Oct 12, 2024 2:05:18 PM seedu.address.commons.util.JsonUtil readJsonFile
INFO: JSON file src/test/data/JsonAddressBookStorageTest/notJsonFormatAddressBook.json found.
Oct 12, 2024 2:05:18 PM seedu.address.commons.util.JsonUtil readJsonFile
WARNING: Error reading from jsonFile file src/test/data/JsonAddressBookStorageTest/notJsonFormatAddressBook.json: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'not': was expecting 'null', 'true', 'false' or NaN
 at [Source: not json format!
; line: 1, column: 4]
Oct 12, 2024 2:05:18 PM seedu.address.commons.util.JsonUtil readJsonFile
INFO: JSON file src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json found.
Oct 12, 2024 2:05:18 PM seedu.address.commons.util.JsonUtil readJsonFile
INFO: JSON file src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json found.
Oct 12, 2024 2:05:18 PM seedu.address.commons.util.JsonUtil readJsonFile
INFO: JSON file src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json found.
Oct 12, 2024 2:05:18 PM seedu.address.commons.util.JsonUtil readJsonFile
INFO: JSON file src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json found.
Oct 12, 2024 2:05:18 PM seedu.address.commons.util.JsonUtil readJsonFile
INFO: JSON file src/test/data/JsonUserPrefsStorageTest/NotJsonFormatUserPrefs.json found.
Oct 12, 2024 2:05:18 PM seedu.address.commons.util.JsonUtil readJsonFile
WARNING: Error reading from jsonFile file src/test/data/JsonUserPrefsStorageTest/NotJsonFormatUserPrefs.json: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'Not': was expecting 'null', 'true', 'false' or NaN
 at [Source: Not a json file!
; line: 1, column: 4]
Oct 12, 2024 2:05:18 PM seedu.address.commons.util.JsonUtil readJsonFile
INFO: JSON file src/test/data/JsonUserPrefsStorageTest/EmptyUserPrefs.json found.
Oct 12, 2024 2:05:18 PM seedu.address.commons.util.JsonUtil readJsonFile
INFO: JSON file /var/folders/l5/zgn14k2x33v8hpzph3zxgpfr0000gn/T/junit10416805285195614567/TempPrefs.json found.
Oct 12, 2024 2:05:18 PM seedu.address.commons.util.JsonUtil readJsonFile
INFO: JSON file /var/folders/l5/zgn14k2x33v8hpzph3zxgpfr0000gn/T/junit10416805285195614567/TempPrefs.json found.
Oct 12, 2024 2:05:18 PM seedu.address.commons.util.JsonUtil readJsonFile
INFO: JSON file src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json found.
Oct 12, 2024 2:05:18 PM seedu.address.commons.util.JsonUtil readJsonFile
INFO: JSON file /var/folders/l5/zgn14k2x33v8hpzph3zxgpfr0000gn/T/junit11922635546401532867/ab found.
Oct 12, 2024 2:05:18 PM seedu.address.commons.util.JsonUtil readJsonFile
INFO: JSON file /var/folders/l5/zgn14k2x33v8hpzph3zxgpfr0000gn/T/junit8611116013241585950/prefs found.
> Task :jacocoTestReport
BUILD SUCCESSFUL in 4s
6 actionable tasks: 6 executed
14:05:18: Execution finished 'test'.
```

**Comment by damithc** [comment]
@celeschai Looks like the tests are passing on this fresh clone. So, we have a baseline that works. Now you can try to move from here to the one that doesn't work, in small steps, to see where things go wrong.
For example, you can open this fresh clone in intellij and run tests from inside there. If tests fail the same way as you original case, then the problem could be in your Intellij settings.
If it still works, you can push your branch to your fork, and pull it to this fresh clone, and see if it still works. If yes, the problem is not related to your branch either. Then, it could be something specific to your other project location e.g., settings got corrupted in that project. Either you can investigate further to find the problem (e.g., compare the two project folders/settings to see what's different), or just continue the project from this fresh clone (as it seems to be working fine).

Side note: I have a good hunch what the problem is, based on your screenshot, but it is better if you follow the above steps to learn how to deal with this kind of problems in future.

**Comment by celeschai** [comment]
Hi Prof, somehow my previous repo with the errors no longer throw errors after I pulled from main... So I am not exactly sure how I can move forward with the troubleshooting. Can you let me know your guesses so I can see if I somehow fixed them unintentionally?

**Comment by yadobler** [comment]
Why is your repo's src package name CareConnect but the screenshot / tests showing seedu?

**Comment by damithc** [comment]
> Can you let me know your guesses so I can see if I somehow fixed them unintentionally?

@celeschai I was suspicious of the `seedu2` folder you have in the screenshot. Perhaps you took a temporary copy of the source code folder and Intellij got confused why there are two copies of the same class?

**Comment by celeschai** [comment]
> Why is your repo's src package name CareConnect but the screenshot / tests showing seedu?

My team updated it over the weekend.

**Comment by celeschai** [comment]
> > Can you let me know your guesses so I can see if I somehow fixed them unintentionally?
> 
> @celeschai I was suspicious of the `seedu2` folder you have in the screenshot. Perhaps you took a temporary copy of the source code folder and Intellij got confused why there are two copies of the same class?

Oh I see, thank you prof! I actually discovered the same issue in another commit of mine and fixed them together, without thinking that it is the source of the error.

**Comment by celeschai** [comment]
> > Can you let me know your guesses so I can see if I somehow fixed them unintentionally?
> 
> @celeschai I was suspicious of the `seedu2` folder you have in the screenshot. Perhaps you took a temporary copy of the source code folder and Intellij got confused why there are two copies of the same class?

Oh I see, thank you prof! I actually discovered the same issue in another commit of mine and fixed them together, without thinking that it is the source of the error.
