### ISSUE TITLE
Delete or keep branches after PR has been merged?

### ISSUE THREAD

**Issue by michaelyql** [nus-cs2103-AY2425S1/forum#493]
Do we need to keep the branches after they have been merged or can we safely delete the branches? 

(In order for the scripts to detect our contributions)

**Comment by damithc** [comment]
@michaelyql Keep :-) Do NOT delete the branch after merging a PR, as our grading scripts will look for the branches.

**Comment by michaelyql** [comment]
@damithc 

Thank you Prof! 👍🏻

On a related note, do the grading scripts only detect PRs merged into `master`? If we make PRs to features that are still in development on a separate branch from master, will they still count towards the weekly requirement?

---

EDIT: Apologies, this discussion has already been addressed in #470

**Comment by Ma-Xizi** [comment]
> @michaelyql Keep :-) Do NOT delete the branch after merging a PR, as our grading scripts will look for the branches.

Good evening Professor, could you please confirm if this means that the master branch of our forked repository will be updated to match the latest code in our team repository, while each feature branch will remain unchanged, staying as it was in the pull request?

**Comment by damithc** [comment]
> Good evening Professor, could you please confirm if this means that the master branch of our forked repository will be updated to match the latest code in our team repository, while each feature branch will remain unchanged, staying as it was in the pull request?

@Ma-Xizi 
1. To answer your question, if done correctly, the team repo and forks will be identical, with or without feature branches. That is, you need to synchronize them by pulling from the team repo, and pushing to your fork. An illustration of this is given in the tP briefing video in https://nus-cs2103-ay2425s1.github.io/website/schedule/week7/index.html
2. Reminder: it is better for you to stick with the workflow you practiced in v1.1. You might think feature branches will make things easier but they create additional complexities. As many of you are new to all this, it's best not to complicate things more than they already are.

**Comment by Ma-Xizi** [comment]
> > Good evening Professor, could you please confirm if this means that the master branch of our forked repository will be updated to match the latest code in our team repository, while each feature branch will remain unchanged, staying as it was in the pull request?
> 
> @Ma-Xizi
> 
> 1. To answer your question, if done correctly, the team repo and forks will be identical, with or without feature branches. That is, you need to synchronize them by pulling from the team repo, and pushing to your fork. An illustration of this is given in the tP briefing video in https://nus-cs2103-ay2425s1.github.io/website/schedule/week7/index.html
> 2. Reminder: it is better for you to stick with the workflow you practiced in v1.1. You might think feature branches will make things easier but they create additional complexities. As many of you are new to all this, it's best not to complicate things more than they already are.

Thank you Prof!
