### ISSUE TITLE
Alpha Testing

### ISSUE THREAD

**Issue by lithops-zty** [nus-cs2103-AY2425S1/forum#495]
The textbook says 
> Alpha testing is performed by the users, under controlled conditions set by the software development team.

Can I clarify on _the users_ here? Does it really mean any users, or users within the organization only? If it is any users from the general public, how can we ensure the product is used under controlled conditions?

I have also seen alternative definitions of alpha/beta testing as internal and open testing respectively. Is this correct?

**Comment by damithc** [comment]
Good question @lithops-zty 
Alpha testing tend to be done by 'internal' users (e.g., other people in the same organization) whereas beta testers are usually a subset of actual target users (i.e., 'external').

**Comment by lithops-zty** [comment]
@damithc Thank you prof!
