### ISSUE TITLE
Difference between the expected and actual error message because of use of emoji

### ISSUE THREAD

**Issue by annabellekk** [nus-cs2103-AY2425S1/forum#496]
Hi, for the IP peer review, there was a question asking what the output was after you type foo 2. For my own chat bot, my message is actually this - "`I don't undestand what you mean.. (˚ ˃̣̣̥⌓˂̣̣̥ )`". I included an 'emoji' without knowing that we would need to be marked based on this. I don't think the reviewer will be able to copy this emoji when they fill out the review form for me. Since you can't select and copy on the chatbot interface itself. As such, would I be penalised because my error message is different if my peer reviewer is unable to input the emoji part of the message, which result in a difference between the expected output and the actual output?
![Screenshot 2024-10-11 at 11 21 52 AM](https://github.com/user-attachments/assets/71c67314-6e6d-4b63-b212-4c40b09f6ed5)

**Comment by damithc** [comment]
@annabellekk It should be fine. We do a manual inspection for cases of mismatching reviews.

**Comment by shotnothing** [comment]
I went into the code to copy the string since the `exactly` was emphasized so much, I'd imagine your reviewers would too

**Comment by damithc** [comment]
> I went into the code to copy the string since the `exactly` was emphasized so much, I'd imagine your reviewers would too

@shotnothing I wish everyone is as diligent as you are :-)
