### ISSUE TITLE
Question 15 in Quiz 9-Part 1

### ISSUE THREAD

**Issue by Ma-Xizi** [nus-cs2103-AY2425S1/forum#498]
Hi, the answer options for Question 15 in Quiz 9-Part 1 aren’t loading correctly on my side. Does anyone have the full, correct version of the question? Thank you so much for your help!
<img width="682" alt="Screenshot 2024-10-11 at 9 39 14 PM" src="https://github.com/user-attachments/assets/edd97820-331f-4414-9dea-97902c29ff7a">

**Comment by damithc** [comment]
@Ma-Xizi It's a bug (feature?) in Canvas: the updated question is not showing up for those who started the quiz before the question was updated. Why was it broken in the first place? That's another Canvas bug: it somehow lost the answers when the quiz was copied over from previous semester.

It should look like the following:
![image](https://github.com/user-attachments/assets/fce37946-20d2-4557-9109-36ca89de6523)

**Comment by Ma-Xizi** [comment]
> @Ma-Xizi It's a bug (feature?) in Canvas: the updated question is not showing up for those who started the quiz before the question was updated. Why was it broken in the first place? That's another Canvas bug: it somehow lost the answers when the quiz was copied over from previous semester.
> 
> It should look like the following: ![image](https://private-user-images.githubusercontent.com/1673303/375781911-fce37946-20d2-4557-9109-36ca89de6523.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2OTg2MjQsIm5iZiI6MTcyODY5ODMyNCwicGF0aCI6Ii8xNjczMzAzLzM3NTc4MTkxMS1mY2UzNzk0Ni0yMGQyLTQ1NTctOTEwOS0zNmNhODlkZTY1MjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTJUMDE1ODQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGUzOTE5ZjY5ZmJiMDk1ZTBmY2M2YjU5OTU4MGY0MTdkMTVlZTdhYzM5NjExODBhZTEwOTUzZDRlNGMwN2NlOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.-7tb0BIZzGz-toxOiVNWb-0QEnG0qinEDy7ai1UZSMs)

Thank you Prof!
