### ISSUE TITLE
Using branches in iP?

### ISSUE THREAD

**Issue by matthewyip1511** [nus-cs2103-AY2425S1/forum#5]
Hi all! May I check if it is allowed for us to branch from the main branch by using `git checkout` while working on each level for the iP (and later open PRs to merge them to `master`) ? This would allow one to work on the code without having to commit directly to `master` :)

**Comment by damithc** [comment]
@matthewyip1511 Good question. Branching and PRs are added gradually to the iP workflow later (but pretty soon). In the meantime, it is fine to commit directly to the `master` branch. This way, we learn simple approaches first before moving to more sophisticated ones later.

**Comment by matthewyip1511** [comment]
Got it, thank you very much prof :)

**Comment by matthewyip1511** [comment]
Question answered by prof
