### ISSUE TITLE
Clarification on giving my bot a non-English name

### ISSUE THREAD

**Issue by Jianwen0451** [nus-cs2103-AY2425S1/forum#50]
I am planning to give my bot a non-English name. The name is Kotori (Bird in Romanization of Japanese).  Can I ask if this is a complaint with the standard or do I have to rename the bot to an English name?

**Comment by WeiHanWong** [comment]
You can name whatever you want.

**Comment by damithc** [comment]
@Jianwen0451 Yes you can give your chat bot any name, provided it is spelled using English characters.
