### ISSUE TITLE
Bug in topic w9-7

### ISSUE THREAD

**Issue by Feng1231** [nus-cs2103-AY2425S1/forum#500]
Exercise [Agile processes, Pair programming, Test-driven development](https://nus-cs2103-ay2425s1.github.io/website/schedule/week9/topics.html#w9-7-sdlc-process-models-continued)
![image](https://github.com/user-attachments/assets/66a3c445-0a64-4f3c-9434-977ce712798a)

I think there is a bug in formatting here. The last sentence seems like a pointer for the last argument against TDD

**Comment by shotnothing** [comment]
I think so too, but interestingly, it was first put in 7 years ago and modified 3 years ago, but nobody brought this up

https://github.com/se-edu/se-book/commit/f92f9d6b738e42def751a711521730304ef16e73

**Comment by damithc** [comment]
Good catch @Feng1231 
As @shotnothing mentioned, the file was updated once but the bug went unnoticed.
I've fixed it now.
