### ISSUE TITLE
Minor grammar error in Topics section [W9.2a]

### ISSUE THREAD

**Issue by bigismols** [nus-cs2103-AY2425S1/forum#501]
Minor grammar error regarding Acceptable Simplifications in [W9.2a](https://nus-cs2103-ay2425s1.github.io/website/schedule/week9/topics.html#w9-2-activity-diagrams)
According to screenshot below, the second point should be "Multiple arrows can start..." or "Starting multiple arrows from same.."
![image](https://github.com/user-attachments/assets/d9e31ec0-b34a-47ad-b43d-1eae7ac24f7d)
Content still understood perfectly tho 👍

**Comment by damithc** [comment]
Good catch, @bigismols 👍 
Fixed.
