### ISSUE TITLE
Checkstyle reports Trailing spaces unreasonably

### ISSUE THREAD

**Issue by DennieDan** [nus-cs2103-AY2425S1/forum#502]
I am using IntelliJ 2024.1.4 on Windows with Vim mode.

My **checkstyleMain** and **checkstyleTest** tasks keep reporting ```trailing spaces``` whenever the new methods that I add got an empty line before, while other old methods are still okay. 
This is my screenshot for your reference
![image](https://github.com/user-attachments/assets/4869e7d3-6dcb-4266-a8fb-724c136659dc)
![image](https://github.com/user-attachments/assets/10ccdd2e-af63-4f44-ba42-a3c16caf5a86)

This is my gradle set up for checkstyle
```java
plugins {
    id 'java'
    id 'checkstyle'
    id 'com.github.johnrengelman.shadow' version '7.1.2'
    id 'application'
    id 'jacoco'
}
checkstyle {
    toolVersion = '10.2'
}
```

**Comment by flyingsalsa** [comment]
new lines are only a rule for end of file where it says "no newline at EOF"

**Comment by flyingsalsa** [comment]
i'm pretty sure u just have actual whitespaces there, try highlighting the line and see if there's any whitespaces to delete

**Comment by DennieDan** [comment]
> i'm pretty sure u just have actually whitespaces there, try highlighting the line and see if there's any whitespaces to delete

Oh thank you so much, I think I got it!
As I hit `Enter` the next line the auto indented with 4 spaces and they are considered as white spaces

**Comment by damithc** [comment]
@DennieDan you can configure Intellij to show white space characters. That way, you can see that those blank lines actually have some spaces.

![image](https://github.com/user-attachments/assets/9d0f0187-a41d-4507-b5ff-fc78c4dd9c79)

You can also configure Intellij to auto-delete those white spaces.
https://se-education.org/guides/tutorials/intellijCodeStyle.html#tweak-auto-remove-trailing-spaces

**Comment by DennieDan** [comment]
@damithc I see, I will configure my IntelliJ. Thank you Prof!
