### ISSUE TITLE
OpenCSV for tp storage

### ISSUE THREAD

**Issue by stephaneleong** [nus-cs2103-AY2425S1/forum#503]
## Library

[OpenCSV](https://mvnrepository.com/artifact/com.opencsv/opencsv)

## Purpose

For the project, my team would like to store additional data in csv files for easier readability and scalability. OpenCSV would be used to read and write the java objects into these csv files. 

## License

[Apache License 2.0](https://www.apache.org/licenses/LICENSE-2.0)

**Comment by damithc** [comment]
@stephaneleong Approved.
