### ISSUE TITLE
Canvas quiz 9 part 1

### ISSUE THREAD

**Issue by FYL2003** [nus-cs2103-AY2425S1/forum#504]
Hi, may I know if this question is set intentionally like this or it is an error?
<img width="907" alt="Screenshot 2024-10-12 at 10 01 08 PM" src="https://github.com/user-attachments/assets/271b18f8-6d99-4cf7-8459-e14d3d85ba80">

**Comment by damithc** [comment]
@FYL2003 see https://github.com/nus-cs2103-AY2425S1/forum/issues/498

**Comment by FYL2003** [comment]
Thanks prof!

**Comment by FYL2003** [comment]
I will keep this issue open for other people's reference purposes.
