### ISSUE TITLE
Unsure why import statement has style check error

### ISSUE THREAD

**Issue by tayxuenye** [nus-cs2103-AY2425S1/forum#505]
![Screenshot 2024-10-14 003245](https://github.com/user-attachments/assets/f4fc129b-0f85-41ba-8cdf-bed4a10089a2)
![Screenshot 2024-10-14 003257](https://github.com/user-attachments/assets/46a3bcf4-f2b5-4fdc-8adc-e63027f0dc32)

`./gradlew checkstyleMain

> Task :checkstyleMain
[ant:checkstyle] [ERROR] C:\Users\optim\OneDrive - National University of Singapore\Desktop\NUS modules\CS2103T\tp\src\main\java\seedu\address\logic\parser\FindTagCommandParser.java:7:1: Import statement for 'seedu.address.logic.Messages.MESSAGE_INVALID_COMMAND_FORMAT' is in the wrong order. Should be in the 'STATIC' group, expecting not assigned imports on this line. [CustomImportOrder]

> Task :checkstyleMain FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':checkstyleMain'.
> Checkstyle rule violations were found. See the report at: file:///C:/Users/optim/OneDrive%20-%20National%20University%20of%20Singapore/Desktop/NUS%20modules/CS2103T/tp/build/reports/checkstyle/main.html
  Checkstyle files with violations: 1
  Checkstyle violations by severity: [error:1]

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
3 actionable tasks: 1 executed, 2 up-to-date
`

I am not sure why I am getting a style check error for my import statements in FindTagCommandParserTest.java even though it is the same order as FindCommandParserTest.java which is from the original AB3 code.

**Comment by yadobler** [comment]
I cloned your repo and tested checkstyle on my machine. It works without issue.

![image](https://github.com/user-attachments/assets/55710d72-5b05-4dc8-a156-2e05627b7b16)

maybe your local checkstyle got corrupted or something?

(Or you did not push the commit that introduces the error - do push it so that we can test)

**Comment by damithc** [comment]
@tayxuenye Have you pushed the problematic code to your fork?

**Comment by tayxuenye** [comment]
I have just resolved the issue. Thank you!

**Comment by yadobler** [comment]
> I have just resolved the issue. Thank you!

Is it possible to share what you did? Might help others if this happens again

**Comment by tayxuenye** [comment]
> > I have just resolved the issue. Thank you!
> 
> Is it possible to share what you did? Might help others if this happens again

Haha I was just editing the wrong file... Was editing the test file instead of the actual class. I shifted the static import statement to the top of the non-static ones.

**Comment by yadobler** [comment]
Ah makes sense! Yes I initially kept doing that mistake because the tabs with changes vs currently open tabs vs the file being tested are different.

Definitely would have saved myself lots of time if I knew this earlier!
