### ISSUE TITLE
Must immutability be preserved in tP?

### ISSUE THREAD

**Issue by yadobler** [nus-cs2103-AY2425S1/forum#506]
I understand from #15 that immutability is nor a strict requirement. As we add functionality and create tests, it seems like the immutability aspect of AB3 (specifically the `Person` class) is incurring more trouble than worth. _Especially with the edit command and the editdescriptors and the deep copying for tests_

Are we allowed to modify the immutability aspect, or will that enter into "reworking AB3 instead of adding on" territory? Especially since this project is more OOP based, things like getters and setters can control access and prevent side-effects by returning values instead of direct references to fields.

**Comment by damithc** [comment]
@yadobler You may change immutability as you wish. However, IIRC, this immutability is required for the GUI to reflect changes to person details in real time. You can experiment to find if that is indeed the case.

**Comment by yadobler** [comment]
@damithc oooh OK. Thanks so much, we'll discuss on how we will go about it!
