### ISSUE TITLE
Video bug in Week 9.1 topic when quiz loads

### ISSUE THREAD

**Issue by tayxuenye** [nus-cs2103-AY2425S1/forum#508]
![image](https://github.com/user-attachments/assets/b33fc5cd-1708-4d4c-9ad1-33cca29ee4b1)
When the in-video quiz for week 9.1 lecture loads, all I se is this empty screen. There is no way to skip the quiz. I tried refreshing the webpage but to no avail. Not sure if I am the only one facing this issue.

**Comment by damithc** [comment]
@tayxuenye It's an intermittent issue only some students face, possibly due to caching. What you can try:
* Click the `Close` on top right and retry
* Use an incognito browser window.
* Try different browsers/devices/networks.

**Comment by tayxuenye** [comment]
Thanks prof. I cleared my browser cache and it worked.
