### ISSUE TITLE
Use of absolute path in Level 7

### ISSUE THREAD

**Issue by Jianwen0451** [nus-cs2103-AY2425S1/forum#51]
In the instruction of Level 7, it is recommended to use a relative path for the txt file. However, as I try, although it works fine on my Kotori.java, the Test-Ui-Testing keeps reporting that the file can not be found. This issue is resolved after I change to an absolute path of the txt file. Can I ask is there a possible way to resolve this issue without using the absolute path?

**Comment by WeiHanWong** [comment]
If I remember correctly, your code should handle missing file, which is to detect when file does not exist, and creates the file automatically. Ur relative path does not work because Test-ui-testing compile the java code to /bin

**Comment by Jianwen0451** [comment]
Thank you! It works now! At first, I thought I should print a Message if the file did not exist. Now I change to making the directory and file if they do not exist and the problem is solved. The Text-Ui-testing is now giving me the correct result!
