### ISSUE TITLE
IP Grading 

### ISSUE THREAD

**Issue by Justin-Aw46** [nus-cs2103-AY2425S1/forum#513]
I was hoping someone could clarify whether based on these comments I received for my IP, would I be likely to fail the grading for the IP. The feedback stated (Copied Below) that I was at risk of failing criteria for [tests, exceptions] however looking through the comments they don't exactly seem to be saying anything about this. I appreciate the feedback but unsure if it is relevant if considering only the criteria set by the 2103 team. 

GUI -- Unable to view full list; only able to see first task, and adding an event cuts off the response text. Window unable to expand as well (wanted to view the cut-off text and tried expanding but could not). "Bye" command also does nothing. Chat can be continued after issuing that command.

Abstraction -- Files like Parser.java have long methods that include processes that can be done by a helper function. For example, in parseFile, after reading individual files, the processing (parseFileTodo, parseFileDeadline, parseFileEvent) could be done in another method like processLine. Likewise, the parseFileTodo, parseFileDeadline, parseFileEvent have multiple repeated code, within each function and between the 3 functions as well. For example, in parseFileTodo

if (isDone) {
    ToDos newToDo = new ToDos(input[2]);
    newToDo.markAsDone();
    taskList.addTask(newToDo);
} else {
    ToDos newToDo = new ToDos(input[2]);
    taskList.addTask(newToDo);
}

everything but markAsDone is repeated. In the other two methods, retrieving the date is repeated.

Tests -- The tests written are all stored in one file (PapaguTest.java) even though it tests listing (which should be UiTest.java) and adding an event (which should be EventTest.java). Furthermore, the tests seem to rely on the save file being of a certain state already when you list it as the test method seems to import the save file (Papagu papagu = new Papagu("src/main/java/Data/tasks.txt");)and then listing it without adding any tasks to the list.  

Neatness -- Lots of unnecessary whitespacing (multiple 1 line whitespaces between chunks of code that does not seem to require whitespacing separation, like in Parser.java).

Comments -- JavaDoc seems extremely minimal, with some not explaining what the param(s) and return value are. E.g. Parser::parseFileTodo: 

/**
 * Parses the file for ToDos
 * @param input
 * @param isDone
 * @param taskList
 */

I was unsure what input and taskList were until I found the method calling this method and had to read each line code.

Overall, working product (GUI) looks to attain the minimal expectations while lacking in certain minimal UI features like the task list being cut off when requested. Codebase looks hastily done, though.

**Comment by damithc** [comment]
@Justin-Aw46 If the email indicated that your iP is weak on `tests, exceptions`, ensure your iP meets the minimum bar for `A-JUnit` and `A-Exceptions`, given below for easy reference:
![image](https://github.com/user-attachments/assets/b396b5a7-d324-4d5d-8081-aff2837e1c71)
![image](https://github.com/user-attachments/assets/36ce6a28-a4ee-4250-8944-9ab12c81bdee)

In addition, ensure your iP `Meets expectation` for all graded aspects mentioned in the iP peer evaluation form, to the best of your judgement. Here they are, for easy reference:
![image](https://github.com/user-attachments/assets/6cdcd66a-7841-4595-a235-cfd4c9edbf8c)

The comments you received from peers can be useful for the above, but in addition, you need to apply your own judgement as well. 
Note that _evaluative judgement_ (i.e., the ability evaluate own and others' work) is one of the things we try to develop in this course, as software engineers need to use that skill all the time. 

That said, if your iP is still not meeting the bar for full marks, we'll give you another chance to rectify and get full marks, at a later stage. So, there is a safety net even if your own judgement was off the mark (developing that skill takes lot of practice and experience; so we don't expect everyone to get it right the first time).

**Comment by Justin-Aw46** [comment]
Thanks so much for the clarification prof!
