### ISSUE TITLE
TP PersonTest functionality

### ISSUE THREAD

**Issue by jktang14** [nus-cs2103-AY2425S1/forum#514]
Currently in the PersonTest class, there is a function that checks if two things are the same Person, and a name with a trailing whitespace Eg. `John ` is classed as a different person from someone with the same name `John`. 

Can we change the functionality such that they are treated as the same person instead?

**Comment by damithc** [comment]
> Can we change the functionality such that they are treated as the same person instead?

@jktang14 Definitely. AB3 behavior may be flawed or may not fit your own product. Change as necessary by all means. In fact, they will be considered bugs if you don't -- although the behavior came from AB3, now it is in your product, and hence, under your responsibility.

**Comment by jktang14** [comment]
Thanks Prof.
