### ISSUE TITLE
ip code quality feedback

### ISSUE THREAD

**Issue by IanCheah** [nus-cs2103-AY2425S1/forum#515]
![image](https://github.com/user-attachments/assets/e197ae24-3253-409f-b69d-c6c70f770fe3)

Hi all, the ip code quality checker flagged out 1 of my recent git commits, indicating that it did not follow the convention. However, the ip code progress shows that my git standard is in green. Hence, I would like to ask if this is a cause for concern.

**Comment by damithc** [comment]
@IanCheah If the `Git Standard` item is green in the dashboard, it should be fine.

**Comment by IanCheah** [comment]
okay, thank you! @damithc
