### ISSUE TITLE
Java CI Ubuntu issues

### ISSUE THREAD

**Issue by wang-h-z** [nus-cs2103-AY2425S1/forum#516]
Hi, 

I am encountering an issue with Java CI/Github Actions where my macOs and windows Java CI tests are passing but the ubuntu-latest is forever pending. 
Additionally, my gradle tests are all passing when running gradle test. 

Anybody ran into these issues? Thanks.

**Comment by damithc** [comment]
@wang-h-z It might help to share the link to the CI page relevant to this issue

**Comment by wang-h-z** [comment]
Hi, this is a late update but to whomever that is still interested in this issue, I realised the problem causing the CI page to hang was the usage of automated JavaFX testing in my JUnit tests. 
If I am not mistaken, there are restrictions to running some JavaFX tests in the ubuntu/Linux environments and the CI process hangs as the tests are not being ran/testing environment not set up properly.

**Comment by damithc** [comment]
> Hi, this is a late update but to whomever that is still interested in this issue, I realised the problem causing the CI page to hang was the usage of automated JavaFX testing in my JUnit tests.
> If I am not mistaken, there are restrictions to running some JavaFX tests in the ubuntu/Linux environments and the CI process hangs as the tests are not being ran/testing environment not set up properly.

@wang-h-z Good to hear you managed to figure it out. Thanks for sharing, as this could be useful to others who are attempting to use TestFX (I know there are a few others).
