### ISSUE TITLE
Accidentally updated UML diagrams in milestone 1.3

### ISSUE THREAD

**Issue by sheenkerr** [nus-cs2103-AY2425S1/forum#517]
I noticed that the UML diagram updates are scheduled for version 1.4. Should I uncommit my changes and create a new PR for 1.4, or is it okay to merge my UML diagrams in 1.3?

Also, will there be a checker in place for the UML diagrams in 1.4?

Thanks for your help!

**Comment by damithc** [comment]
@sheenkerr It's fine. You can update them further in later iterations (designs tend to change as we evolve the product). Yes, the script will be checking for changes to diagram files when it is one of iteration deliverables.

**Comment by sheenkerr** [comment]
Alright, then I'll put my UML diagrams in another PR for 1.4.

Thank you for the prompt response prof!
