### ISSUE TITLE
Code Coverage and Test Cases

### ISSUE THREAD

**Issue by JoanneHing** [nus-cs2103-AY2425S1/forum#518]
Hi prof, our team would like to clarify is the code coverage and test cases graded in this milestone? Can we improve on it on the upcoming iterations?

**Comment by damithc** [comment]
@JoanneHing It is not graded at milestones. The following applies.

![image](https://github.com/user-attachments/assets/8fa8202a-16c3-4357-99e3-9a9a84555179)

**Comment by JoanneHing** [comment]
Thank you prof for clarification!
