### ISSUE TITLE
Can the address book have hyperlinks that can open the browser?

### ISSUE THREAD

**Issue by SwaminathanViswa** [nus-cs2103-AY2425S1/forum#519]
We are planning to use the `java.awt `package for our addressbook and we would like feedback if it is possible to be used in the tP.

**Comment by damithc** [comment]
@SwaminathanViswa From course admin perspective, you may use any class that comes with the JDK. You only need to ask for permission when using third-party libraries.

**Comment by SwaminathanViswa** [comment]
Okay thank you prof!
