### ISSUE TITLE
Issue with questions in Week 3 Quiz

### ISSUE THREAD

**Issue by natlv** [nus-cs2103-AY2425S1/forum#52]
<img width="759" alt="Screenshot 2024-08-24 at 8 58 49 PM" src="https://github.com/user-attachments/assets/b45d69f2-dc75-4971-bace-8a17f2bf2b73">

The first 5 or so questions in the Canva quiz for Week 3 don't seem to be complete. May I check if the questions are displayed as intended? Thank you!

**Comment by TY1Fan** [comment]
Hi, the questions are intended to be incomplete. The answers for the in-briefing (bonus) questions were gone through during week 2 -> 3 briefing on friday. U can watch the recording to find the answers.

**Comment by damithc** [comment]
> Hi, the questions are intended to be incomplete. The answers for the in-briefing (bonus) questions were gone through during week 2 -> 3 briefing on friday. U can watch the recording to find the answers.

Yup, that's correct. Thanks @TY1Fan for the quick answer.
