### ISSUE TITLE
JFXPanel fails test on Ubuntu

### ISSUE THREAD

**Issue by btbrandon** [nus-cs2103-AY2425S1/forum#520]
In the help page, I created a hyperlink to allow people to click on the link directly rather than having to copy the url and paste it in their web server. To test this, I need to set up a JFXPanel. The tests works fine on Windows and MacOS but fails the github test on Ubuntu with the java.lang.UnsupportedOperationException at the line of the JFXPanel initialisation. 

Dependencies wise, I have imported the same libraries for all 3 OS

Anyone have any idea on what might be the issue?

https://github.com/btbrandon/tp/actions/runs/11360720368

**Comment by damithc** [comment]
@btbrandon It might be easier for others to help if you point to the CI page showing the error message.

**Comment by mongj** [comment]
Hi! I know this doesn't directly address your question but here's an alternative for opening up a link in the browser, which has worked well for me so far.

```java
import java.awt.Desktop;

URI link = new URI("https://www.google.com");
Desktop.getDesktop().browse(link);
```
