### ISSUE TITLE
TestFx FxToolKit fails on github

### ISSUE THREAD

**Issue by teamotitan** [nus-cs2103-AY2425S1/forum#521]
Good afternoon all. I was using testfx to test for javafx, and when I ran it on my machine it works. However, when I put in up on Github, it failed the gradle test. I am not sure how to fix it. Can anyone help me?

![image](https://github.com/user-attachments/assets/40c04763-67e1-4014-8152-a4762195b7b7)

(here is line 26)
![image](https://github.com/user-attachments/assets/4cd6328f-b5b3-4495-b631-0d11c8c7ac9b)

Did I not import the correct package?

![image](https://github.com/user-attachments/assets/0988c7da-2196-4f67-8828-3852f1782436)

Thanks a lot!

**Comment by damithc** [comment]
@teamotitan It's good that you are trying to automate GUI tests. I've added a FAQ with some relevant points [here](https://nus-cs2103-ay2425s1.github.io/website/schedule/week9/project.html#:~:text=Should%20we%20try%20to%20automate%20GUI%20testing%20as%20well%3F).

**Comment by damithc** [comment]
@teamotitan If your team is no longer attempting to automate GUI testing, you can close this issue as well.

**Comment by teamotitan** [comment]
Okay thank you prof
