### ISSUE TITLE
Why can't I find myself on tP comments dashboard?

### ISSUE THREAD

**Issue by annabellekk** [nus-cs2103-AY2425S1/forum#522]
Hello, I tried searching my github username and my name as well on the tP comments dashboard on the 2103t website but I can't find an entry, could this mean my PR review comments are not recorded?

**Comment by damithc** [comment]
@annabellekk Cross-check against the `last updated` date of that dashboard. Were your comments added before or after that date?

**Comment by yadobler** [comment]
> Cross-check against the `last updated` date of that dashboard. Were your comments added before or after that date?

I'd assume the dashboard will still list the name but as _"0 comments"_. But there are only [380 usernames](https://nus-cs2103-ay2425s1.github.io/dashboards/contents/tp-comments.html) (instead of 588 like [ip comments](https://nus-cs2103-ay2425s1.github.io/dashboards/contents/ip-comments.html))

**Comment by damithc** [comment]
> I'd assume the dashboard will still list the name but as _"0 comments"_. But there are only [380 usernames](https://nus-cs2103-ay2425s1.github.io/dashboards/contents/tp-comments.html) (instead of 588 like [ip comments](https://nus-cs2103-ay2425s1.github.io/dashboards/contents/ip-comments.html))

@yadobler Those are students who gave comments but those comments were on their own PR or were very short (like `LGTM`). It doesn't list those who didn't give any comments at all.

**Comment by yadobler** [comment]
> > I'd assume the dashboard will still list the name but as _"0 comments"_. But there are only [380 usernames](https://nus-cs2103-ay2425s1.github.io/dashboards/contents/tp-comments.html) (instead of 588 like [ip comments](https://nus-cs2103-ay2425s1.github.io/dashboards/contents/ip-comments.html))
> 
> @yadobler Those are students who gave comments but those comments were on their own PR or were very short (like `LGTM`). It doesn't list those who didn't give any comments at all.

Ah makes sense

**Comment by annabellekk** [comment]
Hi prof @damithc, I have given comments when merging others' PRs as well throughout the past two iterations. Albeit some very short, like just LGTM, which should still show my name as 0 comments right? Or does it only count those comments that are given within the code instead of those that are given at the end when you review the changes?

**Comment by damithc** [comment]
@annabellekk Only review comments are counted (both overall reviews and in-line comments done as part of a 'PR review'). See https://nus-cs2103-ay2425s1.github.io/website/book/gitAndGithub/reviewPRs/ for more info on how to add a review to a PR.

Regular comments added to a PR thread are not counted.

**Comment by annabellekk** [comment]
@damithc I see, in that case, I did do a few review comments (where I went to the files changed and do an overall review comment then approve the pr) previously. But just to be sure, I have made another review as well where I added in line comments to see if my comments will be detected by the system. I will check again when the dashboard next updates.

**Comment by damithc** [comment]
> @damithc I see, in that case, I did do a few review comments (where I went to the files changed and do an overall review comment then approve the pr) previously. But just to be sure, I have made another review as well where I added in line comments to see if my comments will be detected by the system. I will check again when the dashboard next updates.

@annabellekk Noted. If you want me to check the previous case, you can send me (or post here) the link to that PR.

**Comment by annabellekk** [comment]
@damithc Thank you prof. For instance, the comment on this PR [https://github.com/AY2425S1-CS2103T-W11-3/tp/pull/81](url) was done yesterday morning before the dashboard last updated. Are these overall review comments not included in the tp comments dashboard?

**Comment by damithc** [comment]
@annabellekk I updated the comments dashboard again. Your name now appears there.

**Comment by annabellekk** [comment]
Noted, thank you prof @damithc
