### ISSUE TITLE
Add link to Week 9 topic

### ISSUE THREAD

**Issue by Incogdino** [nus-cs2103-AY2425S1/forum#524]
![image](https://github.com/user-attachments/assets/7c378c30-00ca-426d-89dd-a52c1d26f0c5)

I'm not sure if this was intended but maybe "extremeprogramming.org" can be set as a hyperlink instead. The website do seem suspicious though, prompting a warning when I try accessing it.

Link: https://nus-cs2103-ay2425s1.github.io/website/schedule/week9/topics.html#project-management-sdlc-process-models-xp

**Comment by damithc** [comment]
Thanks for the suggestion @Incogdino 
Yes, we'll that. And yes, that's the correct website.
