### ISSUE TITLE
LoC for test cases

### ISSUE THREAD

**Issue by teamotitan** [nus-cs2103-AY2425S1/forum#525]
Good evening all! Can I check for test methods do we need to follow the less than 30 LoC rule?

**Comment by damithc** [comment]
@teamotitan There is no such 'rule', even for functional code. It's just a guideline only :-) 
You need to decide if each method is 'too long', case by case. 

Yes, test methods tend to be long, and that's fine if shortening them doesn't improve readability (which is the real end goal).
Tip: You can divide the method body into meaningful blocks to improve readability.
e.g.,
```java
void testFoo(){

    // test param x
    test case x1;
    test case x2;
    test case x3;

    // test param y
    test case y1;
    test case y2;
    test case y3;

    // test for empty file
    test case f1;
    test case f2;
    test case f3;

    // ...
}

**Comment by teamotitan** [comment]
Thanks a lot prof!
