### ISSUE TITLE
Tutorial 9 Question 2

### ISSUE THREAD

**Issue by DKHB0207** [nus-cs2103-AY2425S1/forum#529]
Would like to ask if functionally are there any differences in the first and second picture? And how should we interpret the diagram that uses the association class? for example for one attempt can it be linked to 2 different associations between Student and Task. For eg. StudentA and Task1 linked to Attempt and StudentB and Task2 linked to the same object Attempt.
<img width="979" alt="Screenshot 2024-10-17 at 12 17 15 PM" src="https://github.com/user-attachments/assets/c9f75c71-5783-4454-8382-dbf5db92fba5">
<img width="942" alt="Screenshot 2024-10-17 at 12 18 33 PM" src="https://github.com/user-attachments/assets/117b63f2-7dd9-45c9-8e91-aee680e46856">

**Comment by shotnothing** [comment]
why would the two different tasks be linked to the same attempt? i think CCDs are not meant to be strict, comprehensive and complete representations of what is and is not possible, but a higher-level conceptual modelling of how the different entities are related

**Comment by damithc** [comment]
@DKHB0207 Sorry for not answering before. I wanted to wait till all the tutorial are over before answering this question.


> Would like to ask if functionally are there any differences in the first and second picture?

@DKHB0207 Association classes have some additional constraints but they are not in the scope of this course. So, in the scope of this course, they can be considered as alternative notations.

> And how should we interpret the diagram that uses the association class? for example for one attempt can it be linked to 2 different associations between Student and Task. For eg. StudentA and Task1 linked to Attempt and StudentB and Task2 linked to the same object Attempt.

An attempt is for a single task. So, one `Attempt` object cannot be linked to multiple `Task` objects.
