### ISSUE TITLE
Difference between actual instructions and notes

### ISSUE THREAD

**Issue by FYL2003** [nus-cs2103-AY2425S1/forum#53]
The pull request button seems to be replaced by contribute button.
Will it be helpful to post it as a tip?

**Comment by damithc** [comment]
@FYL2003 Can you share a screenshot of the new button?

**Comment by FYL2003** [comment]
<img width="925" alt="Screenshot 2024-08-24 at 11 41 32 PM" src="https://github.com/user-attachments/assets/8dc4565b-5ea0-43c0-ab03-61cbb5bce32b">
It's the contribute button

**Comment by damithc** [comment]
@FYL2003 Did you click on the 'Pull requests' tab first?

![image](https://github.com/user-attachments/assets/68d2505c-ed3e-42c2-b0ac-91a08d548f3c)

**Comment by FYL2003** [comment]
Nope, there is no such button

**Comment by FYL2003** [comment]
<img width="922" alt="Screenshot 2024-08-25 at 12 00 19 AM" src="https://github.com/user-attachments/assets/c1ba7ef8-77e2-43f2-9ab5-f80b24f86a9e">
But I can do pull request after I click contribution button

**Comment by Incogdino** [comment]
![image](https://github.com/user-attachments/assets/6fa02bdb-bdad-4ddc-a0ef-273bc5ed5d3d)

Does your github not have this tab at the top?

**Comment by FYL2003** [comment]
Oh wait, now I see the button. But both ways seems to be working

**Comment by damithc** [comment]
> Oh wait, now I see the button. But both ways seems to be working

I see. Yes @FYL2003, you can share it as an alternative way to create a PR.
