### ISSUE TITLE
What should my VERSION variable be?

### ISSUE THREAD

**Issue by Feng1231** [nus-cs2103-AY2425S1/forum#530]
According to how to create a new release, we need to change the version in `MainApp.java`
![image](https://github.com/user-attachments/assets/e01b0cdc-7e69-44af-96ce-4c667241ce29)

Since the version for this week is v1.3, which is not the normal convention for a release according to the [semantic versioning](http://semver.org/)
In this case, what should I change the version to?
```
public class MainApp extends Application {
    public static final Version VERSION = new Version(0, 2, 2, true);
    ...
```

**Comment by damithc** [comment]
@Feng1231 Use the specified version (i.e., v1.3). The tP doesn't follow the semantic versioning convention.

**Comment by Feng1231** [comment]
> @Feng1231 Use the specified version (i.e., v1.3). The tP doesn't follow the semantic versioning convention.

Thanks prof. In this case, what should my VERSION be?
is this correct?
`public static final Version VERSION = new Version(1, 3, 0, true);`

**Comment by damithc** [comment]
> Thanks prof. In this case, what should my VERSION be?
> is this correct?
> `public static final Version VERSION = new Version(1, 3, 0, true);`

Yes, `v1.3.0`  is fine.

**Comment by Feng1231** [comment]
Thank you prof!
