### ISSUE TITLE
Law of Demeter

### ISSUE THREAD

**Issue by annabellekk** [nus-cs2103-AY2425S1/forum#532]
Hi, from the textbook, it gives the following rules for LoD
<img width="644" alt="Screenshot 2024-10-17 at 10 08 27 PM" src="https://github.com/user-attachments/assets/98d617e8-d2be-47f1-8f56-9dc3e06b588e">
Then in the example below, it says the code fragment violates LoD. But I don't understand why g would be violating LoD since g is created inside foo indirectly so aren't we allowed to call g.doSomething()? Or am I misunderstanding what created indirectly means? 
<img width="609" alt="Screenshot 2024-10-17 at 10 09 06 PM" src="https://github.com/user-attachments/assets/6ad3ae80-8886-4d74-b256-27a0a68aabeb">

**Comment by Feng1231** [comment]
The created or instantiated means that that object did not exist prior to executing this function.

If we follow your logic, 
```
Z z = a.getB().getC().getD().getE()...getZ().doSomething()
can be broken down into
B b = a.getB()
C c = b.getC()
...
Z z = y.getZ()
z.doSomething()
```

will not violate LoD too. 
But does that make sense?

**Comment by shotnothing** [comment]
the object assigned to variable `g` is not created inside `foo`, it is created in `b` and then assigned to the variable `g` in `foo`

**Comment by damithc** [comment]
> the object assigned to variable `g` is not created inside `foo`, it is created in `b` and then assigned to the variable `g` in `foo`

Yup, there is an implicit assumption that `getGoo()` is a typical 'getter' method that simply retrieves an existing object, not create a new object.
