### ISSUE TITLE
Merge PR that passed CI before merging, but fails CI after merging

### ISSUE THREAD

**Issue by seah-minlong** [nus-cs2103-AY2425S1/forum#533]
Hi prof,

Our group has run into this issue. We are able to fix it with the next commit.

![image](https://github.com/user-attachments/assets/3c547a19-76ec-49c3-85af-38d4919cc705)

 However, at the same time, we are wary about the alert below:

![image](https://github.com/user-attachments/assets/e9aa96a2-7baa-4aa7-b4da-94ef40f17610)

Would there be penalties if we do not revert the change and fixed it via another commit instead?

**Comment by damithc** [comment]
@seah-minlong No penalty if you get back to CI-passing state in a timely manner. That is, do not continue to ignore CI and keep merging code that fail CI, as that prevents us from verifying that you have learned how to use CI properly in a project.

**Comment by seah-minlong** [comment]
Ok, duly noted. Thanks prof!
