### ISSUE TITLE
Lack of Q+ logo for video

### ISSUE THREAD

**Issue by Incogdino** [nus-cs2103-AY2425S1/forum#534]
![image](https://github.com/user-attachments/assets/fe62a0ce-837a-4e34-8a75-381e19ba0bfd)

This video has a quiz portion to it but the label lacks a Q+ logo.

Link: https://nus-cs2103-ay2425s1.github.io/website/schedule/week10/topics.html#quality-assurance-test-case-design-equivalence-partitions-what

**Comment by damithc** [comment]
@Incogdino Thanks for raising this. This one does have questions but we didn't put the Q+ icon there because we don't count this one for in-video quiz participation (as we have four Q+ videos for this week already).

**Comment by Incogdino** [comment]
> @Incogdino Thanks for raising this. This one does have questions but we didn't put the Q+ icon there because we don't count this one for in-video quiz participation (as we have four Q+ videos for this week already). 

Ahh okay I see. Thanks for the clarification prof
