### ISSUE TITLE
Unsure of Help Command Implementation

### ISSUE THREAD

**Issue by yuanchengg** [nus-cs2103-AY2425S1/forum#535]
Our team is implementing a HelpCommand and we our implementation now follows the old AB3 and opens a new help window. However, we have to move the mouse to click close for the help window to close. Does this violate the requirement for our product to be CLI-based?

**Comment by shotnothing** [comment]
i think that's the difference between CLI-based and CLI-only? to me, it doesn't make sense to disallow that since the results and everything are fetched in a GUI anyway, and the app window itself needs click-to-close

**Comment by damithc** [comment]
@yuanchengg We do not require everything to be CLI only.

Also see https://nus-cs2103-ay2425s1.github.io/website/admin/tp-constraints.html#recommendation-cli-first

**Comment by yuanchengg** [comment]
@shotnothing 

Thank you so much for your help!!! That makes sense.

**Comment by yuanchengg** [comment]
@damithc 

Thank you for the clarification Prof, appreciate it. 😄
