### ISSUE TITLE
v1.4 released on the TP dashboard

### ISSUE THREAD

**Issue by IanCheah** [nus-cs2103-AY2425S1/forum#536]
Hi teaching team, 
![image](https://github.com/user-attachments/assets/a8cedef3-adb7-4b9f-a4f3-57c1c67d405c)
Our group F08-4 noticed that our "v1.4 released" is lighted up even though we only did the release for v1.3. Is there something that we are doing wrongly?

**Comment by damithc** [comment]
@IanCheah You can ignore that. The jar release is detected based on the the time it is released, not the version number. So, you can get a false-positive green if you release/update v1.3 jar during v1.4 period.

**Comment by IanCheah** [comment]
Okay thanks! @damithc
