### ISSUE TITLE
Requesting permission to use CalendarFX

### ISSUE THREAD

**Issue by Gra7ityIC3** [nus-cs2103-AY2425S1/forum#537]
## Library

[CalendarFX](https://github.com/dlsc-software-consulting-gmbh/CalendarFX)

## Purpose

We want to implement a calendar view of appointments so users can better manage and view their appointments.

## License

[Apache License 2.0](https://opensource.org/licenses/Apache-2.0)

**Comment by damithc** [comment]
Approved, @Gra7ityIC3
