### ISSUE TITLE
Git commit message violation

### ISSUE THREAD

**Issue by JoanneHing** [nus-cs2103-AY2425S1/forum#538]
Hi prof! Wanted to ask do I need to fix the previous commit message if it violates the git naming convention? As it stated in the textbook that editing might affect the progress tracking. I realize that it is because I did not use capital letter for the first letter in the commit and I commit quite some amount of commit for the past three milestone. Does that affect the gradings?

**Comment by damithc** [comment]
@JoanneHing 

1. If the commit is already merged into master, best not to change, as it will make repos of your team members go out of sync as well.
2. If not merged yet, you can change commit message and force-push the branch to your fork, but note that the commit timestamp will change accordingly. If all your commits of a past week change the timestamp to the current week, that week will be recorded as 'no commits'. But having 'no commits' in an occasional  week will not affect your tP marks, if you have commits in at least 4 weeks (see below):
![image](https://github.com/user-attachments/assets/88248508-6830-4991-bd8a-b3d53c0fc351)

**Comment by JoanneHing** [comment]
<img width="712" alt="Screenshot 2024-10-20 at 4 09 38 PM" src="https://github.com/user-attachments/assets/d2106ec1-0a3f-411a-b827-43e9707760ce">


All the commits already been merged to master already, so is it best that I do not change the commit messages? But would it affect my marks? Or is it okay if I follow the git convention afterwards, as stated in the email sent today. I just counted that I pushed around 30 commit for the past weeks.... 😭

**Comment by damithc** [comment]
@JoanneHing Yes, leave them be, and don't worry about it. If you follow the convention from now on and if you are fairly active in the project, it should not affect your marks. Reason: Minor infractions in early tP commits will be ignored if most commits done later are proper, as it shows the student eventually learned to follow the convention.

**Comment by JoanneHing** [comment]
Alright!Thank you prof for the clarification!
