### ISSUE TITLE
Suggestion to be multiple choice question?

### ISSUE THREAD

**Issue by JoanneHing** [nus-cs2103-AY2425S1/forum#539]
<img width="586" alt="Screenshot 2024-10-20 at 4 35 22 PM" src="https://github.com/user-attachments/assets/80341b5f-da10-4839-8605-b12a97cbf597">
 This is the question at the section Quality Assurance → Test Case Design → Equivalence Partitions → Basic
Is this question more suitable if it is to choose the two that are belong to the same EP? Just a small suggestion

**Comment by damithc** [comment]
@JoanneHing Only one answer (i.e., the test case to leave out) needs to be chosen. The answer can be b or c, but not both. So, no need for checkbox-style, right?

**Comment by JoanneHing** [comment]
I see prof point on this! Thank you!
