### ISSUE TITLE
Clarification on Level 8

### ISSUE THREAD

**Issue by Jianwen0451** [nus-cs2103-AY2425S1/forum#54]
For level 8, can we assume that all the inputs about date/time are valid? That is to say, do we need to consider the situation like this "Event doSomething /from somegabage /to someothergarbage". If we need, do we still treat these garbage inputs as String or need to do error handling and not create a new task for this?

**Comment by damithc** [comment]
@Jianwen0451 It's up to you. But minimally, such garbage entries should not crash the program entirely.
