### ISSUE TITLE
UML Diagrams: which is better between these two?

### ISSUE THREAD

**Issue by Meowloid** [nus-cs2103-AY2425S1/forum#540]
Hello friends.

Here's two dummy diagrams I made which represents my problem in a high-level format:
![image](https://github.com/user-attachments/assets/7f69e8bd-e3f9-472b-976d-99f3fe56bace)
![image](https://github.com/user-attachments/assets/4bb4653a-0ac1-4694-8601-e79cde22425f)

I have two questions: both diagrams seem 'correct' (read: nothing wrong with them) to me, but I want to know if any of you have two cents to give regarding whether two or one merge nodes in this scenario is better. It should be noted that I can't seem to have only one merge node to make it look better.

Secondly, for the diagram with two branch nodes, is the second branch node acceptable? Instead of using `[else]`, is using `[!booleanCheck]` valid? I think that as booleanCheck is a boolean here, it is alright as it's a binary question: there's no ambiguity, similar to the examples given in the CS2103T website with `[x => 5]` and `[x < 5]` as guard clauses.

Thanks in advance.

**Comment by damithc** [comment]
Good question @Meowloid 
Let's first look at this from 'what's better in a real world project?' (rather than 'what is expected in tP/exam?' -- this I will answer at a later time)
Let's give some time for others to pitch in with their views.

**Comment by JoanneHing** [comment]
From my opinion, I feel like the first diagram is more concise and easier to read, as the both of the conditions has to be true to execute the intended behavior. while if one of it is false, it will skip the execution of the behavior. It seems a bit redundant to include another branch node as it doesn't result in a different branch/behaviour if valid argument is true and boolean check is false. Hence, I think there is not necessary to have another branch node to indicate the second condition check. But  actually diagram 2 might also create a bit of ambiguity in the second diagram, which will be explain below

For the second question, I am concerning that is there ambiguous for reader as now it is in a separated branch, reader might be confused as they not sure what is the expected value for `booleanChecked` now, as it can be understand as
1. `booleanChecked` supposed to `true` to process the intended behavior, then `!booleanChecked` which is `false` will be branched out (As what is shown in diagram 1)
2. `booleanChecked` supposed to be `false` to process the intended behavior, then `!booleanChecked` will be `true` and branch out (This is different from what the diagram 1 is representing now)

Hence, maybe `booleanChecked == true` will be more clear? But not sure is writing `[booleanChecked]` a more concise representation for it.

Not sure is my understanding on the right track, correct me if I am wrong : D

**Comment by emmannyyy** [comment]
I think that the first diagram will likely be better. Ultimately, checking for valid arguments and the boolean seems like the objective is just input validation. Furthermore, from the diagram, it does seem they both reach the same destination (probably an exception thrown). 

In my opinion, it may be worth splitting them if they both had different outcomes/destinations. Otherwise, it seems verbose to add it.

**Comment by Meowloid** [comment]
> From my opinion, I feel like the first diagram is more concise and easier to read, as the both of the conditions has to be true to execute the intended behavior. while if one of it is false, it will skip the execution of the behavior. It seems a bit redundant to include another branch node as it doesn't result in a different branch/behaviour if valid argument is true and boolean check is false. Hence, I think there is not necessary to have another branch node to indicate the second condition check. But actually diagram 2 might also create a bit of ambiguity in the second diagram, which will be explain below
> 
> For the second question, I am concerning that is there ambiguous for reader as now it is in a separated branch, reader might be confused as they not sure what is the expected value for `booleanChecked` now, as it can be understand as
> 
>     1. `booleanChecked` supposed to `true` to process the intended behavior, then `!booleanChecked` which is `false` will be branched out (As what is shown in diagram 1)
> 
>     2. `booleanChecked` supposed to be `false` to process the intended behavior, then `!booleanChecked` will be `true` and branch out (This is different from what the diagram 1 is representing now)
> 
> 
> Hence, maybe `booleanChecked == true` will be more clear? But not sure is writing `[booleanChecked]` a more concise representation for it.
> 
> Not sure is my understanding on the right track, correct me if I am wrong : D

Hmm, I was of the idea that in the spirit of concise code, a boolean in a guard clause can be expressed without using `== true`
For example,
`if (isPresent == true) { ... }`
and 
`if (isPresent) { ... }`
are equivalent. I feel that if it's clear to the developer/user that what is being checked is a boolean, in this example `isPresent`, it should be fine to leave it as so. Thanks again for your inputs.

**Comment by zaidansani** [comment]
I think the first one is just way more readable. If the specified path can only occur together given the two conditions, it is much simpler to just state them as such.

A real world analogy for me would be - if you want to only give someone money if they have done two surveys, would you check for one survey at a time, or would you just check both surveys in one shot? 

The only reason to provide an alternative path would be if there's an action happening somewhere.
