### ISSUE TITLE
Clarifications on feature freeze

### ISSUE THREAD

**Issue by IanCheah** [nus-cs2103-AY2425S1/forum#542]
Hi, our group would like to clarify about the feature freeze. The website mentions that the feature freeze occurs after the release of the JAR file used in the PE-D, which is v1.5. However, last Friday's briefing states that no features can be added after v1.4. May we know when the feature freeze will occur?

Thank you!

**Comment by damithc** [comment]
@IanCheah The feature freeze is after v1.5.
It was incorrectly cited at v1.4 in the briefing (it used to be called v1.4 in previous semesters -- we changed version numbers this semester). Sorry about that.
