### ISSUE TITLE
Requesting permission to use FuzzyWuzzy

### ISSUE THREAD

**Issue by ghos7ie** [nus-cs2103-AY2425S1/forum#543]
## Library

[FuzzyWuzzy](https://github.com/xdrop/fuzzywuzzy)

## Purpose

We would like to use this library to enhance our Find feature so that users are still able to find what they are looking for even with typoes or not knowing the full search term.

## License

[GPL-2.0](https://github.com/xdrop/fuzzywuzzy?tab=GPL-2.0-1-ov-file#GPL-2.0-1-ov-file)

**Comment by damithc** [comment]
Approved, @ghos7ie
