### ISSUE TITLE
AB3 edit and delete command inconsistency

### ISSUE THREAD

**Issue by thortol** [nus-cs2103-AY2425S1/forum#544]
Noticed an inconsistency with edit and delete command on AB3. Edit command resets the list upon completion while delete keeps the list the same.

Steps to recreate:
1. `find charlotte`
![image](https://github.com/user-attachments/assets/0ca43a3e-c38c-48be-a317-b056dff710c5)
2. `edit 1 p/123`
![image](https://github.com/user-attachments/assets/46f9ef41-608f-4324-bff4-a7cb5daef53e)

The list is reset after executing the edit command

1. `find charlotte`
![image](https://github.com/user-attachments/assets/0ca43a3e-c38c-48be-a317-b056dff710c5)
2. `delete 1`
![image](https://github.com/user-attachments/assets/8091cad1-8b2d-47db-8770-2405a4c56c9a)

The list is not reset after executing the delete command

Is this intended?

**Comment by damithc** [comment]
@thortol I'm not sure if it was intentional. However, you may change the behaviour as you see fit. 

Others feel free to chime in on which behaviour option is better for this case
