### ISSUE TITLE
TP tracker 

### ISSUE THREAD

**Issue by saajidshaik02** [nus-cs2103-AY2425S1/forum#545]
![image](https://github.com/user-attachments/assets/c0f51e2b-7690-4d0b-948c-ef73bbc8e12c)

Hi, one of my issues for V1.3 had the milestone accidentally deleted. Hence, it was not tracked even tho issue closed + PR done. Is there anyway to rectify this or do I live with this mistake :(((((

**Comment by damithc** [comment]
@saajidshaik02 You can add the milestone again, and the dashboard will detect it at the next update.
