### ISSUE TITLE
MarkBind different view from markdown

### ISSUE THREAD

**Issue by NorbertLoh** [nus-cs2103-AY2425S1/forum#547]
Has anyone using MarkBind faced the issue where the markdown looks correct in IntelliJ and GitHub whereas the GitHub pages shows the markdown as raw text?
Markdown
![image](https://github.com/user-attachments/assets/2f285695-1269-473e-a125-e50268e5fd38)

MarkBind
![image](https://github.com/user-attachments/assets/9b61f101-6f74-4e8e-a629-9b60836d4514)

Was wondering if anyone faced something similar and found out what is the cause of it?

**Comment by damithc** [comment]
@NorbertLoh Markdown syntax expects a blank line to separate a list from the text above it. 

```xml

## Some title

1. item A
1. item B
```
Some tools forgive the lack of this blank line (e.g., GitHub Preview) but some don't (Jekyll, MarkBind).

**Comment by NorbertLoh** [comment]
@damithc Interesting. It seems to be happening with other parts in the DG that came with AB3
Our current DG
![image](https://github.com/user-attachments/assets/e98c6efd-1e25-4b95-af2d-299d72135cf7)

MarkBind
![image](https://github.com/user-attachments/assets/8bca90be-4820-415c-9776-e28f5ae02173)

AB3
![image](https://github.com/user-attachments/assets/a7cd5715-6290-4fab-a68e-811a7a127190)

Could this issue possibly arise from the use of the autoformatter?

**Comment by damithc** [comment]
@NorbertLoh Where is this happening? Is it on GitHub so that others can have a closer look?

**Comment by NorbertLoh** [comment]
@damithc Yes it can be found [here](https://github.com/AY2425S1-CS2103-F11-2/tp/blob/master/docs/DeveloperGuide.md?plain=1). Starting from the info box above "How the `Logic` component works:".

**Comment by damithc** [comment]
@NorbertLoh When things get messed up after a certain point, usually the culprit can be found just above that point.
In this case, the line break in the `alt` attribute value is the likely culprit. If this was added by the auto-formatter, then your initial hypothesis is correct about the auto-formatter being the cause.

```
<puml src="diagrams/DeleteSequenceDiagram.puml" alt="Interactions Inside the Logic Component for the `contact delete 1`
Command" />
```

**Comment by NorbertLoh** [comment]
That seems to be the issue! However, any line break causes it to break. So how do we approach this if the line exceeds the recommended word limit per line?

**Comment by damithc** [comment]
> That seems to be the issue! However, any line break causes it to break. So how do we approach this if the line exceeds the recommended word limit per line?

@NorbertLoh It causes problems if the line break is inside an attribute value, not in other places.

There is no max line length for Markdown. In fact our Markdown style guide advices against doing so. https://se-education.org/guides/conventions/markdown.html

**Comment by NorbertLoh** [comment]
Ok got it. Thanks prof!
