### ISSUE TITLE
Deleted merged branch causing tP task progress to not be tracked

### ISSUE THREAD

**Issue by Justin-Yeo** [nus-cs2103-AY2425S1/forum#548]
![Screenshot 2024-10-22 at 1 00 05 AM](https://github.com/user-attachments/assets/fab42a8a-cc21-49d0-8eb7-9bef77830bfe)
I have done the necessary work for the milestone but had deleted the branches used for the milestone. Is there anyway to rectify this or would marks be deducted due to this? Thank you!

**Comment by damithc** [comment]
@Justin-Yeo The first item doesn't have anything to do with branches.
For the second one, which branches did you delete at what point?
