### ISSUE TITLE
What to do if i want to add some more testing in the IP

### ISSUE THREAD

**Issue by ishan-agarwal-05** [nus-cs2103-AY2425S1/forum#549]
Should i just commit and push to master or do i need to change the release and jar file?

**Comment by damithc** [comment]
@ishan-agarwal-05 You definitely need to push the code to the repo. If there is _any_ change to the functional code, do a new release as well.

**Comment by ishan-agarwal-05** [comment]
If I don't want to add any functionality and only changes in function files will be made, should I still update the jar file. Basically I realised that I had commented out my entire test file in the jar (I was fixing some tests but forgot to uncomment out the tests - I didn't know about disable tests at that time 😅). Today morning I was just looking at the code when I realised I basically don't have tests. So for getting the marks of testing section of ip I need to update just the tests. Is it possible to still get marks for that.
Thanks for answering so promptly

**Comment by damithc** [comment]
@ishan-agarwal-05 

If there is no change to functional code, no need to do a new release or update the jar file.

**Comment by ishan-agarwal-05** [comment]
thanks a lot

**Comment by ishan-agarwal-05** [comment]
If I were to update the code now will it still be considered for marking or is it too late?

**Comment by damithc** [comment]
> If I were to update the code now will it still be considered for marking or is it too late?

We can grade the new code if you update it now.
