### ISSUE TITLE
 Update `jackson-databind` and `jackson-datatype-jsr310` Dependencies to Address Security Vulnerabilities

### ISSUE THREAD

**Issue by SeeYangZhi** [nus-cs2103-AY2425S1/forum#551]
Understand that this isn't critical in the context of CS2103 tP, but would just like to ask if we were to update the dependencies, will this be affecting the tP?

See details of related issue:
https://github.com/AY2425S1-CS2103-F13-1/tp/issues/154

**Comment by damithc** [comment]
@SeeYangZhi Feel free to update dependencies versions as you see fit.
