### ISSUE TITLE
UML diagrams on PlantUML rendering differently on Markbind as compared to on the preview

### ISSUE THREAD

**Issue by zaidansani** [nus-cs2103-AY2425S1/forum#552]
In the inbuilt view in IntelliJ, my PlantUML diagram looks like this:
<img width="702" alt="image" src="https://github.com/user-attachments/assets/242f7990-a0bf-40f6-81d0-3535a3db8400">

However, when published to Markbind, the lines seem to have an issue (look at top right of the diagram, between `UniqueAppointmentList` and `AppointmentBook`.

<img width="711" alt="image" src="https://github.com/user-attachments/assets/f92df3f2-2e91-4889-b642-b7d0a4a664a7">

Anyone with any idea why this might be happening?

**Comment by damithc** [comment]
@zaidansani Did your team update this diagram or is this the original diagram?
The differences can be due to different versions of PlantUML used by Intellij and MarkBind (sometimes it even varies based on the OS), but both versions should appear correctly with only cosmetic differences between them. I haven't seen this kind of discrepancies before.

**Comment by damithc** [comment]
> @zaidansani Did your team update this diagram or is this the original diagram?

Of course you did. I didn't check the diagram carefully before writing that 🤦 

Perhaps try installing MarkBind locally and preview the diagram through that? If it is messed up, you can try tweaking the PlantUML code (e.g., reorder elements) to see if you can arrive at a version that renders correctly.

**Comment by zaidansani** [comment]
> Perhaps try installing MarkBind locally and preview the diagram through that?

Yeap, this was where this screenshot was.

Seems like the only fix is to change the direction of the lines:
<img width="876" alt="image" src="https://github.com/user-attachments/assets/b039f548-d04f-4c40-adeb-1cda6960aff7">

**Comment by zaidansani** [comment]
Will keep this open for a bit, to see if anyone has any idea if this issue is caused by anything else, but for all intents and purposes I'd consider this solved for now.
