### ISSUE TITLE
Can we use an open source external JavaFX component in our TP

### ISSUE THREAD

**Issue by kimxw** [nus-cs2103-AY2425S1/forum#553]
Hello,

My team is currently developing an app for small-scale private tutors to manage students and lessons. We’re considering integrating a calendar feature and are exploring the use of the open-source JavaFX component, CalendarFX.

May we clarify if we’re allowed to use CalendarFX for our project? Additionally, if we are permitted to use it, would relying on an external library like this raise any concerns regarding code quality or adherence to coding conventions in the context of CS2103T? Since the component’s source code won’t be written by us, we want to ensure we won’t face any issues.

Thanks in advance!

![image](https://github.com/user-attachments/assets/30aa8a46-8a94-4335-87ad-54ef4ff315d4)

**Comment by damithc** [comment]
The use of CalendarFX has been approved already (see https://github.com/nus-cs2103-AY2425S1/forum/issues/537).

[Our policy on reuse](https://nus-cs2103-ay2425s1.github.io/website/admin/appendixB-policies.html#policy-on-reuse) also covers the use of 3rd party libraries
