### ISSUE TITLE
Anyone else getting weird issues with the CI/CD processes in github?

### ISSUE THREAD

**Issue by jereeemyyyy** [nus-cs2103-AY2425S1/forum#555]
I am trying to create a pull request from my fork branch to my team's master branch. However, when creating the PR, I keep getting hit with this error that I am failing one of the test cases from `ViewCommandTest`. 
Attached below is a screenshot of the error message:
<img width="1369" alt="Screenshot 2024-10-22 at 10 21 51 PM" src="https://github.com/user-attachments/assets/57a032b6-ebe1-465b-b8b6-2f463a382d3c">

However, when I run the test cases locally, everything passes. As shown below:
<img width="333" alt="Screenshot 2024-10-22 at 10 24 50 PM" src="https://github.com/user-attachments/assets/15cb71a4-bffc-4a70-a4bb-abd3f319cd1a">

I am not too sure what is going on and I have been trying to look for a solution for the past hour! Please help if you have ever experienced this issue before 😄. Thank you!

**Comment by yadobler** [comment]
![image](https://github.com/user-attachments/assets/aa18cd04-38be-4141-b79a-96ee1c1a0220)

can confirm you test cases work on my system after I cloned your repo and switched to your `branch-A-viewCommand` branch

maybe try to make a non-consequential edit and commit and push again?

**Comment by damithc** [comment]
@jereeemyyyy See if the following FAQ (from last week) is applicable

![image](https://github.com/user-attachments/assets/94290dea-ebd2-4594-808f-a4f772c639e4)

**Comment by jereeemyyyy** [comment]
Thank you @damithc and @yadobler. I realised that the `master` branch indeed progressed after I started on the PR branch which may have affected the test cases as mentioned by the FAQ. I have managed to solve this issue by merging my PR branch with the new and updated master branch and then updating the testcases. Thanks once again! 😄
