### ISSUE TITLE
How to use logging for week 10

### ISSUE THREAD

**Issue by Feng1231** [nus-cs2103-AY2425S1/forum#557]
Our team has used logging in our methods for week 10.
An example of logger usage is:

`logger.finer("Name keywords are empty or contain an empty string: " + names);`

However, our logging tag in the `individual progress` tab in the course website remains unlit.
![image](https://github.com/user-attachments/assets/05607ce4-7877-4795-8755-fe8dd8e4d052)

May I check how do we actually light it up?

**Comment by damithc** [comment]
@Feng1231 This is an individual item. So, we check the lines of code in the [tP code dashboard](https://nus-cs2103-ay2425s1.github.io/tp-dashboard/?search=&sort=groupTitle&sortWithin=title&timeframe=commit&mergegroup=&groupSelect=groupByRepos&breakdown=true&checkedFileTypes=docs~functional-code~test-code~other) to see if you have used logging in your code.

BTW, yours seems to be 'done' now.

**Comment by Feng1231** [comment]
It is indeed done now. My group members and I merged the PRs two nights before, and it wasn't reflected the next morning, even though the dashboard says last updated @ around 7am that morning. Hence the confusion. Sorry and thank you prof!

**Comment by damithc** [comment]
@Feng1231 Items related to individual code can take a bit longer to get reflected in the tP progress dashboard, as they first need to get detected in the tP code dashboard. So, in some case, it can take two update cycles.
