### ISSUE TITLE
Updating UML diagrams for week 10

### ISSUE THREAD

**Issue by beginner-web-developer** [nus-cs2103-AY2425S1/forum#558]
Hi prof, can i check if for the week 10 task of updating UML diagrams, are we only supposed to be updating the existing diagrams, or can we create new diagrams to reflect the new things we added to AB3? Because I have added new diagrams, but the tp individual progress dashboard doesn't capture this.

**Comment by damithc** [comment]
@beginner-web-developer You can update existing diagrams or add new ones. Yours seems to be green now. It takes a bit longer for this item to get detected, as it needs to get picked up by the tP code dashboard first (updated daily), and then by the progress dashboard will pick it from there at the next update.

**Comment by beginner-web-developer** [comment]
oh ok thanks prof
