### ISSUE TITLE
[External Software Permission Request] Mockito

### ISSUE THREAD

**Issue by SeeYangZhi** [nus-cs2103-AY2425S1/forum#559]
Mockito seems to be an approved library, referencing the past few year's CS2103 forum: https://github.com/nus-cs2103-AY2021S1/forum/issues/337

## Library
[Mockito](https://github.com/mockito/mockito)

## Purpose
Allow dependency-free unit testing using mocks. Reduce the time needed to write stubs.

## License
Licensed under the [MIT License](https://github.com/mockito/mockito/blob/main/LICENSE).

**Comment by damithc** [comment]
Approved, @SeeYangZhi
