### ISSUE TITLE
Is launching the GitHub web application allowed?

### ISSUE THREAD

**Issue by Incogdino** [nus-cs2103-AY2425S1/forum#561]
![image](https://github.com/user-attachments/assets/a70ed5d9-9331-467b-b75f-58c1bb2e4818)

Does launching the GitHub web application from Address Book violate this restriction? Also, will this affect testability in the PE since it brings users to GitHub?

**Comment by damithc** [comment]
@Incogdino 
1. What feature will it be used for, in what way?
2. During the PE, we allow students to access the GitHub project of the product they are testing, if it is needed for the purpose of testing.

**Comment by Incogdino** [comment]
> @Incogdino
> 
> 1. What feature will it be used for, in what way?
> 2. During the PE, we allow students to access the GitHub project of the product they are testing, if it is needed for the purpose of testing.

Our application is focused for SOC TA so the command will launch the GitHub repository of the contact in the address book. The user will just call `github n/NAME` to launch the repository of the user

**Comment by damithc** [comment]
> Our application is focused for SOC TA so the command will launch the GitHub repository of the contact in the address book. The user will just call `github n/NAME` to launch the repository of the user

@Incogdino This should be fine.

**Comment by Incogdino** [comment]
> > Our application is focused for SOC TA so the command will launch the GitHub repository of the contact in the address book. The user will just call `github n/NAME` to launch the repository of the user
> 
> 
> 
> @Incogdino This should be fine.

Okay thank you prof!
