### ISSUE TITLE
SourceTree no longer displaying column guide

### ISSUE THREAD

**Issue by O-Darren** [nus-cs2103-AY2425S1/forum#562]
Sourcetree is suddenly no longer displaying the column guide for my commits. When I navigate to the section in options, the ability to enable the column guide is now grayed out. 

May I know how to reenable the column guide?
 
![image](https://github.com/user-attachments/assets/5f6bcff3-2110-4c48-8da8-8162d4d5d803)

**Comment by emmannyyy** [comment]
I believe you need to select "Use fixed-width font for commit messages", in order to be able to select "Display a column guide..." 

[Source](https://se-education.org/guides/conventions/git.html):
![image](https://github.com/user-attachments/assets/4f60c346-beba-476b-bfe6-264b02876ce4)

**Comment by damithc** [comment]
@emmannyyy is correct. If the text is not using fixed-width font (i.e., different characters have different widths, which is the usual case), it is not possible to draw such a line, as the width of the line depends on which characters are in the line.
