### ISSUE TITLE
Bug when using PlantUML

### ISSUE THREAD

**Issue by Ma-Xizi** [nus-cs2103-AY2425S1/forum#563]
Hi, I have been experiencing this bug about PlantUML that it does not render some of diagrams out, but works normally for sequence diagrams.

The issue appears even when I do not change the original diagrams, so it is not about editing the diagrams.

<img width="699" alt="Screenshot 2024-10-23 at 5 56 04 PM" src="https://github.com/user-attachments/assets/765a058d-0dbf-4c4c-8eac-4e7183042d2c">

**Comment by damithc** [comment]
@Ma-Xizi Which OS are you on? You might need to install the Graphviz engine.
If on Mac and using home-brew, you can try `brew install graphviz`

**Comment by WinstonJin** [comment]
Hi prof, I would like to add a bit more details to this as I am also having the same issue (alongside other mac users in my group)

The only diagrams that show up are the following:
UndoSequenceDiagram.puml
DeleteSequenceDiagram.puml
CommitActivityDiagram.puml
ArchitectureSequenceDiagram.puml
UndoSequenceDiagram-Logic and Model

The rest look like the screenshot shown above.

BUT I have tried your brew install and it works! Thanks so much prof!

**Comment by Ma-Xizi** [comment]
> brew install graphviz

Thank you, solved! I will leave this post open until the end of this week, to see if there is anyone facing the same issue.
