### ISSUE TITLE
Clarification regarding notation for sequence diagrams 

### ISSUE THREAD

**Issue by kngys** [nus-cs2103-AY2425S1/forum#565]
Hi, when referring to the textbook it was mentioned that if method parameters don't matter to the purpose of the sequence diagram, we can omit them using ... e.g., use foo(...) instead of foo(int size, double weight). I would like to clarify to specify only some parameters or only a partial parameter, is such notation accepted? e.g. for foo (int x, String y, int z) use foo(..., 1) to show only one parameter z and for goo(String s) use goo("a ...") to represent a partial parameter instead of the full String input. Thank you!

**Comment by damithc** [comment]
@kngys Yes, such simplifications can be used, provided it doesn't mislead the reader or cause ambiguities.

**Comment by kngys** [comment]
ok thank you!
