### ISSUE TITLE
Incorrect tracking of iP progress dashboard

### ISSUE THREAD

**Issue by blanklogic** [nus-cs2103-AY2425S1/forum#566]
![Screenshot 2024-10-23 at 10 42 46 PM](https://github.com/user-attachments/assets/442ab471-1bd2-4021-99e0-0c0efe91905b)

# Bug: Lost Progression
It seems like something might have broke in the most recent update for the iP Progress Dashboard as all the progress for some students like myself have lost all tracked progress that we had on our iP. Unsure if this may affect us in any way but making this issue to clarify.

## Steps to reproduce
1. Go to https://nus-cs2103-ay2425s1.github.io/dashboards/contents/ip-progress.html
2. View a number of profiles with similar 0 commits, tag-less, and lost progression similar to the screenshot above

**Comment by damithc** [comment]
@blanklogic Some network/GitHub error must have caused this. I've updated the dashboard just now. Seems OK now?

**Comment by blanklogic** [comment]
Thanks Prof. Issue is fixed, closing issue.
