### ISSUE TITLE
Clarification on LSP and Role-Specific Field Editing Behavior

### ISSUE THREAD

**Issue by zzzlou** [nus-cs2103-AY2425S1/forum#567]
**Description:**

Our team is working on a feature where users can manage contacts with different roles: `Volunteer` (subclass of `Person`), `Donor` (subclass of `Person`), `Partner` (subclass of `Person`), and `Person` (default). Each role has specific fields, such as `hours` for Volunteers and `donatedAmount` for Donors.

**Our concern:**

Allowing users to edit role-specific fields for the wrong role (e.g., editing `hours` for a non-Volunteer) could cause bugs. However, if we throw an error in these cases, would that be seen as violating the Liskov Substitution Principle (LSP)?

Since the `edit` function should ideally work across all instances of `Person` and its subclasses, would enforcing role-specific validation (i.e., throwing an error when users attempt to edit a field not applicable to the instance) violate LSP?

Any insights on this would be greatly appreciated!

**Comment by damithc** [comment]
@zzzlou Glad to know you are thinking of issues like this one while implementing features. 
Let's wait to see what others think about this.

**Comment by somethingfishyfishy** [comment]
> However, if we throw an error in these cases, would that be seen as violating the Liskov Substitution Principle (LSP)?

I dont fully understand your questions.
Let me interpret your question. Assume this is your code
```
class Person {
    ... //attributes
    public String editHours(int hoursForVolunteers) { // can be renamed to just "edit"
        return "Error: this person has no hours to edit";
    }
    
    public String editDonationAmount(double amount) { // can be renamed to just "edit" also
        return "Error: this person has no amount to edit";
    }
}
```

```
class Volunteer extends Person {
    private int hours;
    
    public String editHours(int hours) {
        // do stuff
        return "success";
     }
}
```

```
class Donors extends Person {
    private double amount;
    
    public String editDonationAmount(double amount) {
        // do stuff
        return "success";
     }
}
```

> LSP: Objects of a superclass should be able to be replaced with objects of a subclass without affecting the program.

For this there is application of substitutability. You could substitute `Person p = new Volunteer()` and do `p.editHours(1)`. The code is just not applying polymorphism, ie you need to know the subtype and apply the method. In terms of whether throwing errors, I presume you dont mean exceptions hence the String messages only. It will look a bit complicated if the methods throw errors, but nonetheless it isn't violating substitutability

Now if your code looks like

```
class Person {
    public String edit(int i) throws Exception {
        throw new Exception();
    }
    // edit(double d)
}
```

```
class Volunteer extends Person {
    public String edit(int i) throws Exception {
        // do stuff and do not throw exception
    }
}
```

This also does not violate LSP. But in the above example, polymorphism can be applied.

On your 2nd question:
> would enforcing role-specific validation (i.e., throwing an error when users attempt to edit a field not applicable to the instance) violate LSP?

I do not understand how your implementation is so I cant advise you. But if you see the 2nd example I gave, it is not necessary for validating (or type-checking / type-verifying) the types. I would think that, if the typechecking methods are in the subtypes but not supertype then yes it would violate LSP (eg. `boolean isVolunteer()` only appearing in Volunteer and not Person)

Hope my understanding of your question helps to answer
