### ISSUE TITLE
Must a ConfirmationWindow class be linked to UI class?

### ISSUE THREAD

**Issue by Bonzzz3** [nus-cs2103-AY2425S1/forum#569]
Currently, I have a ConfirmationWindow class (for delete and clear) that works fine on its own. However, intuitively it is part of the Ui, and it would be hard/confusing to draw UML diagrams if it is not linked. But in order to link it to Ui, I would have to set a public constructor in UI with no parameter and does nothing, then ConfirmationWindow extend UiPart. Should I just leave it or link it to UI?

**Comment by damithc** [comment]
@Bonzzz3 Good to discuss design decisions (such as this one) here.

From the teaching team side, some general thoughts: Consistency is good, as it makes things easier to understand. But do consider costs as well.

**Comment by Bonzzz3** [comment]
Thanks prof!
