### ISSUE TITLE
[External Software Permission Request] Ikonli Icon Packs for JavaFX (Fontawesome5 Pack)

### ISSUE THREAD

**Issue by colinhia** [nus-cs2103-AY2425S1/forum#570]
## Library

[Ikonli package, Fontawesome5 Icon Pack]
https://kordamp.org/ikonli/ 
https://github.com/kordamp/ikonli?tab=readme-ov-file
https://fontawesome.com/

## Purpose

We intend to use the Icons available in the Icon pack in the UI. This would allow for us to more easily find Icons that are visually consistent; without the need for importing many different SVG files.

## License
https://fontawesome.com/license/free
https://github.com/kordamp/ikonli?tab=Apache-2.0-1-ov-file
The Fontawesome pack is released under the MIT license, and is free and open source. 
The Ikonli package is released under the Apache-2.0 license

**Comment by damithc** [comment]
Approved, @colinhia
