### ISSUE TITLE
Requesting permission to use ez-vcard third-party library

### ISSUE THREAD

**Issue by joeltio** [nus-cs2103-AY2425S1/forum#572]
## Library

[ez-vcard](https://github.com/mangstadt/ez-vcard)

## Purpose

We would like our address book to allow the user to export to VCards so that the user can add contacts to their phone or other devices more easily.

## License

https://github.com/mangstadt/ez-vcard?tab=License-1-ov-file#readme

The type of license is not explicitly specified but it looks like [BSD-2-Clause](https://opensource.org/license/BSD-2-clause)

**Comment by damithc** [comment]
@joeltio Approved
