### ISSUE TITLE
CodeCov issues

### ISSUE THREAD

**Issue by saajidshaik02** [nus-cs2103-AY2425S1/forum#573]
![image](https://github.com/user-attachments/assets/d0473b4f-daba-4392-9a5b-fc77b87c9ef1)

Scenario:
After some online checking, I learnt its difficult for me to test this certain UI related class (CommandBox) unless I learn how use mockito, it seems. Probably, I can still test some underlying logic but I won't hit the 77% required by codecov.

And I'm pretty sure I'm unable to finish implementing this Test Class by v1.4 deadline (or that I know how to make test cases :( in this case) because unlike AddCommandTest classes, there is almost no reference or guidance on how to create test cases for this class...
_______________________________________________________________________________________________________________________________________
[Screenshot 2024-10-24 185921](https://github.com/user-attachments/assets/6c1bcac3-229e-41eb-9791-084a3621c735)
^UI subfolder under SRC

[Screenshot 2024-10-24 185927](https://github.com/user-attachments/assets/e8509b07-a028-4733-80c9-9b137246041a)
^UI subfolder under Test (notice missing test cases for UI clasess, also not too sure how to use TestFXMLObject to test CommandBox?)
_______________________________________________________________________________________________________________________________________

Can I bypass codecov test coverage and merge the PR first? Will I be deducted marks if so? (or if I don't ever address the lack of code coverage in this class at all in the upcoming versions)

**Comment by flyingsalsa** [comment]
you can check [here](https://nus-cs2103-ay2425s1.github.io/website/schedule/week9/project.html#:~:text=drop%20in%20code%20coverage) i think it mostly answers your questions(?)

**Comment by flyingsalsa** [comment]
Ctrl+f for code coverage if the link doesnt work
![image](https://github.com/user-attachments/assets/a1de0c55-762a-4894-afbe-5c1a7b7b008b)

**Comment by damithc** [comment]
@flyingsalsa Thanks for pointing to the relevant FAQ. 
@saajidshaik02 Let me know if you have any follow up questions.
