### ISSUE TITLE
Deadline for updating UML in Week 10

### ISSUE THREAD

**Issue by ghos7ie** [nus-cs2103-AY2425S1/forum#574]
Hi Prof, 

Currently on the course website there is no deadline stated for adding a UML diagram in `v1.4` as it is a recommendation.
![image](https://github.com/user-attachments/assets/f33acb13-0059-4cb9-832d-825d7e6c880c)

But it seems that the tP tracker is tracking that we are required(?) to do at least 3 lines of changes to any `*.puml` file.
![image](https://github.com/user-attachments/assets/06d61d58-ceab-45da-9fca-379f2b64ce2f)

Can I check if we are graded on adding a UML diagram for Week 10? It seems that only 20% of the cohort has done it so far as well so there might be some confusion.

**Comment by flyingsalsa** [comment]
you can check [here ](https://nus-cs2103-ay2425s1.github.io/website/schedule/week9/project.html#:~:text=drop%20in%20code%20coverage) i think 
it has some answers your question

**Comment by damithc** [comment]
@ghos7ie Any project task given in week N is subjected to the weekly deadline (i.e., Friday 4pm), unless a different deadline is given. However, updating UML diagrams is not part of v1.4 requirements. So no need to finish by Thursday 23:59. So, give priority to releasing v1.4, and get started on updating UML diagrams after that. It will turn green if it is done within a few days of the weekly deadline.

**Comment by ghos7ie** [comment]
thanks @damithc :)
