### ISSUE TITLE
Release note for v1.4

### ISSUE THREAD

**Issue by Feng1231** [nus-cs2103-AY2425S1/forum#575]
May I clarify, should the release note for v1.4 include all the changes from AB3, or only the changes from v1.3?

**Comment by damithc** [comment]
@Feng1231 It should include all changes since your last detailed release note. That is, anything new that you haven't reported already in a previous release.

**Comment by Feng1231** [comment]
@damithc Hi prof, are we able to edit the release note now? Or would that make the checks for v1.4 on the course website turn red since it's already pass the deadline

**Comment by damithc** [comment]
@Feng1231 You can edit it now. It will not cause any item to turn red in the dashboard.
