### ISSUE TITLE
How to change tag name of release

### ISSUE THREAD

**Issue by travisim** [nus-cs2103-AY2425S1/forum#576]
I released the release for milestone 1.3 under the release tag of v1.1 on time and now i can't change the name of release tag v1.1 to v1.3 else it will create a new tag of v1.3 with the current time which makes release 1.3 not on time from the dashboard's perspective.

**Comment by damithc** [comment]
@travisim The dashboard checks the created/updated time of the release. It doesn't check the tag. So, as long as you do a release within the iteration period, it will be recognised by the dashboard.

**Comment by travisim** [comment]
Thanks prof, you saved my teams v1.4 release.
