### ISSUE TITLE
Assertions not reflected in tp individual dashboard

### ISSUE THREAD

**Issue by sannie-beep** [nus-cs2103-AY2425S1/forum#577]
Hello, I was wondering why the autograder has found no assertions in my added code. The dashboard shows that 0 assertions were detected when I had in fact added a few. 

Here is the dashboard display:
![image](https://github.com/user-attachments/assets/c17a3070-2642-4480-b110-706bd9343c82)

I have used these assertions in my merged PR:
![image](https://github.com/user-attachments/assets/edd77f94-4682-4c6a-a444-d120cd794a6f)

Is it because they are JUnit assertions and not regular ones?

**Comment by damithc** [comment]
@sannie-beep Yes, this deliverable is about Java `assert`s (covered among [week 5 topics](https://nus-cs2103-ay2425s1.github.io/website/schedule/week5/topics.html#w5-6-assertions)), not JUnit `assert___` methods.
