### ISSUE TITLE
Question about auto-gnerated merge messages

### ISSUE THREAD

**Issue by Ma-Xizi** [nus-cs2103-AY2425S1/forum#578]
Hi Prof! I realized that when I pulled from the team repo and created a new commit from source tree, the git message is generated automatically and not changeable. Sometimes, the messages will be too long. Are they counted as git violations?
<img width="604" alt="Screenshot 2024-10-25 at 12 07 02 PM" src="https://github.com/user-attachments/assets/1f6ea8c8-5ba0-4ed5-a61f-a823c0de3f50">
<img width="461" alt="Screenshot 2024-10-25 at 12 08 20 PM" src="https://github.com/user-attachments/assets/822024af-53af-4aa8-a1bb-c1be78746221">

**Comment by damithc** [comment]
@Ma-Xizi We don't check commit messages of auto-generated commits

If you are following the forking workflow, such auto-generated commits can get created in the team repo (i.e., when merging a PR) but pulling from the team repo should not create new commits (that don't exist in the team repo) in the master branch of your repo. After pulling the master branch of your repo should be identical to the team repo master branch.

**Comment by Ma-Xizi** [comment]
> @Ma-Xizi We don't check commit messages of auto-generated commits
> 
> If you are following the forking workflow, such auto-generated commits can get created in the team repo (i.e., when merging a PR) but pulling from the team repo should not create new commits (that don't exist in the team repo) in the master branch of your repo. After pulling the master branch of your repo should be identical to the team repo master branch.

Thank you Prof!
