### ISSUE TITLE
Clarification on changing file names

### ISSUE THREAD

**Issue by TY1Fan** [nus-cs2103-AY2425S1/forum#580]
Hi can I clarify if we have to change our file name to match our product name, or will we be marked down for not changing the file name?

e.g. Addressbook.java to UGTeach.java

**Comment by damithc** [comment]
@TY1Fan Yes, you can change names of java files.

**Comment by TY1Fan** [comment]
@damithc but will marks be deducted if we choose **NOT** to change our filename to match product name?

**Comment by damithc** [comment]
@TY1Fan Sorry, misread the question. No, it is fine to keep the original names of internal files, given your tP is also a type of an address book. But you should  use the new product name in places visible to the user.

**Comment by TY1Fan** [comment]
Thank you for the clarification Prof @damithc !
