### ISSUE TITLE
TP effort requirement

### ISSUE THREAD

**Issue by AbdulrahmanAlRammah** [nus-cs2103-AY2425S1/forum#581]
From the tp grading guidelines, a team is expected to place 50% of AB3 implementation effort. We are also told that a student should put 50% of the effort it takes to do an IP. So if you have 5 students you would expect 2.5 IP effort. However, 2.5 IP effort doesn't seem to be anywhere near 50% AB3 effort. 50% AB3 effort feels more like 5 IPs. Since these metrics feel so different which should we follow?

<img width="578" alt="image" src="https://github.com/user-attachments/assets/68184c53-b847-43fb-870f-5c8c6ce64825">

**Comment by damithc** [comment]
@AbdulrahmanAlRammah The lower one.
Caution: This kind of estimates are pegged to a 'typical' case. So, don't estimate based on a iP that did the bare minimum.
