### ISSUE TITLE
Markbind deployment website not reflecting the css styling

### ISSUE THREAD

**Issue by Reallyeasy1** [nus-cs2103-AY2425S1/forum#582]
Hi all, 

We are setting up our github website until we encountered a problem.
Our github website doesn't reflect the styling that we have done on our website, specificially the css styling. We tried running markbind locally and the website works on our local machine, but it doesnt work on the deployment site.

Photo of our deployment site:
![photo_6116188250646366474_w](https://github.com/user-attachments/assets/b5e46392-5bf5-4f6e-82f6-01b94bf8d972)

Photo of our local machine:
![photo_6116188250646366473_w](https://github.com/user-attachments/assets/0afe1fc0-c6cb-40eb-aab1-91de6279e677)

Link to our github website:
https://ay2425s1-cs2103t-w08-1.github.io/tp/

Link to our github repo, docs section:
https://github.com/AY2425S1-CS2103T-W08-1/tp/tree/master/docs

Thanks for helping.

**Comment by damithc** [comment]
@Reallyeasy1 Can you point to the commit or the PR that caused this problem?

**Comment by Reallyeasy1** [comment]
Hi, this problem has been surfacing since we started on this project

Attached is the link to the first markbind setup:
https://github.com/AY2425S1-CS2103T-W08-1/tp/commit/651d3e9c844d947c6d07597ab050a06e4158b4cd

Thanks for helping

**Comment by damithc** [comment]
@Reallyeasy1 In which commit/PR did you do css changes that you think is causing these issues? Unless changes are done methodically in small commits/PRs, it is hard to locate where a problem is introduced to the code. 
When did it first surface? How did you fix it? Or did it go away by itself?

**Comment by Reallyeasy1** [comment]
Hi, thanks for helping me to solve the issue, the issue has already been solved. Thanks

**Comment by waihongteh** [comment]
Solution found: Turns out that the github pages is deployed from master branch, /docs instead of gh-pages branch, /root, which is the reason why the css files are not loaded properly.
