### ISSUE TITLE
Question on sd and ref frames

### ISSUE THREAD

**Issue by Feng1231** [nus-cs2103-AY2425S1/forum#583]
As shown in the image, I am trying to use reference frame to make my UML diagram clearer.
On the left diagram, I included the `ParserUtil` class, and the ref frame encapsulates the life line of both `AddCommandParser` and `ParserUtil`. Is there a need to though? Can I omit it?

![image](https://github.com/user-attachments/assets/c36a6de4-c63c-480f-bf61-904c1cee6d3e)

**Comment by damithc** [comment]
@Feng1231 Which part exactly are you thinking  of omitting?

**Comment by Feng1231** [comment]
> @Feng1231 Which part exactly are you thinking  of omitting?

Hi prof, sorry for late reply
I am thinking if it is okay to remove the circled ParserUtil class. Because while this class is not involved in this sequence diagram, it is involved in the sd frame 
![image](https://github.com/user-attachments/assets/da39331b-b1b5-44b4-95ee-17c0009dfc86)

**Comment by damithc** [comment]
@Feng1231 Got it. I think it is fine to omit it, as it is not involved in any interactions that is visible in that specific diagram.
