### ISSUE TITLE
Clarification for deadline of v1.5

### ISSUE THREAD

**Issue by SeeYangZhi** [nus-cs2103-AY2425S1/forum#584]
The deadline for the v1.5 release is next week, Nov 7th.
![telegram-cloud-photo-size-5-6125342621250469400-y](https://github.com/user-attachments/assets/fc02aeab-d4a4-4ec8-b737-71aac9fec039)

However, the dashboard deadline is week 11, which is this week. 
![telegram-cloud-photo-size-5-6123152239469117690-y](https://github.com/user-attachments/assets/6ffd3ac4-632b-428e-89bc-1e0c2974e92f)

May I check if we still must close v1.5 by this week's Thursday (31/10/2024), 23:59?

**Comment by damithc** [comment]
@SeeYangZhi You have an extra week for v1.5 due to university holidays clashing with our lecture slot. So, the deadline is Nov 7th 23.59
