### ISSUE TITLE
Showing throwing of exception in sequence diagram

### ISSUE THREAD

**Issue by Soumyadip-cmd** [nus-cs2103-AY2425S1/forum#585]
I wanted to ask if a method can throw an exception, do we need to show the throwing of the exception when drawing the activation bar for the method in a sequence diagram. If so, I would like to know how to show that the method can throw an exception.

**Comment by baskargopinath** [comment]
im from previous batch, and if i remember correctly, we didnt need to show throwing of exceptions in the activation bar

**Comment by damithc** [comment]
@Soumyadip-cmd There is no need to show such intricate details such as exception handling and lambdas in the sequence diagram. They are outside of the scope of the notation covered in the course anyway.

**Comment by Soumyadip-cmd** [comment]
I see. Thank you for your response @damithc and @baskargopinath
