### ISSUE TITLE
tP DG Question - Implemenation part

### ISSUE THREAD

**Issue by The0nlyJuan** [nus-cs2103-AY2425S1/forum#586]
<img width="1018" alt="image" src="https://github.com/user-attachments/assets/298f6ffe-f10e-4b9b-91e9-f8fb815d8c0d">
For this implementation part in the DG, are we required to update this based on our current features or just for proposed features like in the original AB3. 

<img width="784" alt="image" src="https://github.com/user-attachments/assets/595fd6ee-9065-450c-964d-3a4b9daaaf70">
It does not clearly state in the course website about this implementation part so would it be up to our teams decision?

**Comment by damithc** [comment]
@The0nlyJuan You may remove proposed features from the DG, but you are welcome to keep them too. But if you keep them, the content should match the current product.
