### ISSUE TITLE
Question on command parsing for tp

### ISSUE THREAD

**Issue by kevin-pek** [nus-cs2103-AY2425S1/forum#587]
In my team's TP project, some of the commands include a description field (d/) that accepts free text. This allows users to enter any text within the description, including text resembling the prefixes of other commands (e.g., "t/10am" or "p/123" within d/description), provided there is no conflict with prefixes used by the current command.

Is this behaviour considered a functionality bug, and is additional handling recommended to avoid potential confusion for users? Or can it be considered as intended functionality? Thanks!

**Comment by damithc** [comment]
@kevin-pek This needs to be decided from the user's point of view, and go with the choice you think you can justify. Once the intended behavior is chosen, you can also looks for way to ensure users are well-informed (and not confused) about how it works. This can mitigate any 'flawed feature design' type bug reports against this feature.
If you give the specific design choices here, others can weigh in with what they think is the best choice.
