### ISSUE TITLE
Alpha bug reporting

### ISSUE THREAD

**Issue by annabellekk** [nus-cs2103-AY2425S1/forum#588]
Hello, when I report a bug on github for this iteration's alpha testing, do I just need to attach the alpha-bug tag to the issue? Should I assign the issue to someone? If so, do I assign myself to the bug I reported or assign it to the author of the function? Thank you.

**Comment by damithc** [comment]
@annabellekk 

> when I report a bug on github for this iteration's alpha testing, do I just need to attach the alpha-bug tag to the issue?

Yes. More info [here](https://nus-cs2103-ay2425s1.github.io/website/schedule/week11/project.html#1-alpha-test-the-product)

> Should I assign the issue to someone? If so, do I assign myself to the bug I reported or assign it to the author of the function?

Up to you. The normal practice is to assign a bug report to the person who should act on it, at the point such a person is identified.

As per [this](https://nus-cs2103-ay2425s1.github.io/website/admin/appendixE-gitHub.html#b-using-issue-assignees-to-track-task-allocation):

![image](https://github.com/user-attachments/assets/971e0105-7b32-48fd-b000-d7f7b30e0776)

**Comment by annabellekk** [comment]
Ok thank you prof!
