### ISSUE TITLE
Are multiple screens allowed for the PE?

### ISSUE THREAD

**Issue by matthewyip1511** [nus-cs2103-AY2425S1/forum#589]
Looking ahead, I saw that we have the option to do the PE in week 13 via zoom-proctoring (which we can declare next week). However, may I check if multiple screens (eg. one laptop with an external monitor) will be allowed in the PE?

Thank you!

**Comment by damithc** [comment]
@matthewyip1511 Strictly one screen per person. Remote monitoring becomes harder if we allow multiple monitors. 
More details https://nus-cs2103-ay2425s1.github.io/website/admin/tp-pe.html

**Comment by matthewyip1511** [comment]
Got it, thanks prof!

**Comment by matthewyip1511** [comment]
Query addressed
