### ISSUE TITLE
Corrupting the database file

### ISSUE THREAD

**Issue by Virusrwj223** [nus-cs2103-AY2425S1/forum#591]
Hi, can I check if during the practical exam, do our testers only interact with the app through the app or are they able corrupt the data files directly. For example, are they able to change the JSON key and values to some other name by directly opening them etc.

**Comment by ghos7ie** [comment]
i asked the prof this a few weeks back

what I recall being told is that we can assume the user editing the json file is aware of what they are doing and will carry out actions that won't break the app

**Comment by damithc** [comment]
@Virusrwj223 as mentioned above (thanks @ghos7ie), the following applies.

![image](https://github.com/user-attachments/assets/587266ea-af7b-422c-bfcf-41b6ce3b2ea5)
