### ISSUE TITLE
Is LOC Graded for tP?

### ISSUE THREAD

**Issue by shotnothing** [nus-cs2103-AY2425S1/forum#592]
Hi, are we graded on our LOC count? From the guidelines, there is an effort component that uses human feedback to score, and nothing on LOC. Just wanted to check if LOC matters for grading!

**Comment by damithc** [comment]
@shotnothing LoC is not graded but if there is a significant mismatch between the LoC numbers and the 'effort' rating a student received, we take a closer look at the case to find out the reason for the mismatch, and revise marks if necessary.
