### ISSUE TITLE
JavaFx library incompatible, cannot open jar file

### ISSUE THREAD

**Issue by amitha2210** [nus-cs2103-AY2425S1/forum#595]
I'm using MacOS, and my Java version says "openjdk version "17.0.12" 2024-07-16". When I am trying to open the jar file of my teams' product, I am getting the errors as shown below.
Does anyone know how to fix this? Thank you!

<img width="1470" alt="Screenshot 2024-10-31 at 5 25 38 PM" src="https://github.com/user-attachments/assets/fa153948-60f7-4020-8a17-3e5563b1c119">

**Comment by tata32000** [comment]
What is the version of your Java runtime?

This should be the output when you run `java —version`:
```
openjdk 17.0.11 2024-04-16 LTS
OpenJDK Runtime Environment Zulu17.50+19-CA (build 17.0.11+9-LTS)
OpenJDK 64-Bit Server VM Zulu17.50+19-CA (build 17.0.11+9-LTS, mixed mode, sharing)
```

**Comment by yadobler** [comment]
duplicate of #145, #111, 
see also: #146, #189, #430

**Comment by amitha2210** [comment]
It works! Thank you so much!
