### ISSUE TITLE
Typo in the tP dashboard?

### ISSUE THREAD

**Issue by matthewyip1511** [nus-cs2103-AY2425S1/forum#596]
<img width="699" alt="image" src="https://github.com/user-attachments/assets/558afec6-d4b7-4bdb-9242-130e238bd704">

Hi Prof, may I check if this is a typo since the jar file only needs to be released in week 12 at the end of v1.5 😅 Thanks!

**Comment by damithc** [comment]
@matthewyip1511 officially, the work is scheduled for week 11. Week 12 is just an extra week we had to add due to holidays. We will keep the dashboard in week 11 for an extra week, so that week 11 items don't turn red even through week 12.

**Comment by matthewyip1511** [comment]
Got it, thank you Prof!
