### ISSUE TITLE
Changing Sourcetree display

### ISSUE THREAD

**Issue by SherChew27** [nus-cs2103-AY2425S1/forum#597]
when I am staging my commits, the files that were edited used to be displayed in a list similar to the following screenshot.[
<img width="425" alt="Screenshot 2024-11-01 at 11 39 27 PM" src="https://github.com/user-attachments/assets/a03f8834-9537-43a5-9fdc-8adbc789e82f">
](url)

however, i accidentally dragged the edited code view all the way to the left, and now i have lost the list of edited files and the page looks like this, where i need to manually stage each file.

<img width="1293" alt="Screenshot 2024-11-01 at 11 39 41 PM" src="https://github.com/user-attachments/assets/b708ea81-bbdd-4201-9cdd-81b9d4b3997f">

how do i revert back to the previous view where i have a list of my edited files?

**Comment by zhonghan721** [comment]
Hi @SherChew27, dropping in from your senior batch! I came across this [forum](https://community.atlassian.com/t5/Sourcetree-questions/Can-t-see-quot-Staged-files-quot-list-for-my-commit/qaq-p/2747354) and this [forum](https://community.atlassian.com/t5/Sourcetree-questions/File-status-menu-doesn-t-show-up-list-of-files/qaq-p/2711411) with the same problem that you faced.  You might want to give it a try. It seems like it is a bug on Sourcetree interface.

**Comment by damithc** [comment]
@SherChew27 Any updates?

**Comment by SherChew27** [comment]
Thank you so much for the help! What ended up working for me was to restart my SourceTree. However, I realised that the changes are no longer automatically staged as they were before. Nonetheless, this is just a minor inconvenience and thus I will just close the issue. Thank you!
