### ISSUE TITLE
Pseudocode function call for Sequence Diagram

### ISSUE THREAD

**Issue by Raghava-Chittidi** [nus-cs2103-AY2425S1/forum#599]
Hi, I was wondering if we can just use pseudocode such as "delete ia from list" and maybe have some annotation somewhere explaining what ia stands for. Our team is unsure because diving deep into the function calls would make this diagram complicated but also this pseudo function call is not an actual function call that happends

<img width="900" alt="Screenshot 2024-11-03 at 12 00 40 AM" src="https://github.com/user-attachments/assets/81419707-4ef2-4dcc-bb1a-b31c772b7ccb">

**Comment by damithc** [comment]
@Raghava-Chittidi Yes, you can use pseudocode when it helps.

![image](https://github.com/user-attachments/assets/a25545f8-8a03-4960-a616-8aee6cc381fb)

**Comment by Raghava-Chittidi** [comment]
Thank you prof!
