### ISSUE TITLE
Execution of program fails with ClassNotFound error

### ISSUE THREAD

**Issue by Ponharish** [nus-cs2103-AY2425S1/forum#6]
After cloning the project and configuring IntelliJ, I tried to execute the code in src/main/java but the execution returned ClassNotFound error. After some research, I added the line, 

`package main.java;`

and this seems to have resolved the issue. 
May I confirm if this is the correct approach to solve this problem?
Also, should the class files be saved under the directory bin?

Thank You

**Comment by damithc** [comment]
@Ponharish hmm... 🤔 that doesn't look right. Let's wait to see if any of your classmates can pitch in with any suggestions on how to fix this. In the meantime, you can continue to code iP increments. This issue doesn't need to be fixed immediately.

**Comment by Ponharish** [comment]
Thank you Prof for the info.

I will keep the issue open to see if anyone else encountered this problem.

**Comment by LordSaumya** [comment]
@Ponharish This may likely be a problem with your IntelliJ configuration, since it does not seem to be recognising your package structure. You may need to mark the correct directory as the root.

**Comment by Javiery3889** [comment]
Hi @Ponharish. I'm from your senior batch, perhaps you can try setting `src/main/java` as your Source Folder in IntelliJ. This can be done be by navigating to Project Setting (Ctrl+Shift+Alt+S) → Modules → Sources tab.

See these links for more info:
https://stackoverflow.com/questions/17300318/error-classnotfoundexception-in-intellij-idea
https://stackoverflow.com/questions/17408769/how-do-i-resolve-classnotfoundexception

Cheers,
Javier

**Comment by MadLamprey** [comment]
Hello @Ponharish. I am from your senior batch. Regarding your second question, upon execution, all `.class` files get saved under the `out` directory, upon execution. This can be verified/configured under `Project Settings > Project > Compiler Output`. There is no explicit need for manually saving `.class` files under a specific directory.

**Comment by Ponharish** [comment]
@LordSaumya @Javiery3889 @MadLamprey Thank you for your replies. I have resolved this issue completely by restarting the entire project (from cloning the repo) and reconfiguring IntelliJ as mentioned in the link provided by @Javiery3889. After reconfiguring, i found that the outputs are now saved in the folder mentioned by @MadLamprey without any issue.

Once again Thank you for helping out.
