### ISSUE TITLE
Quiz 3

### ISSUE THREAD

**Issue by AlphaPyke** [nus-cs2103-AY2425S1/forum#60]
Does anyone know what the "..." in the quiz questions 1-5 mean? I have no idea what the question is asking for.
<img width="842" alt="image" src="https://github.com/user-attachments/assets/43fb3ff8-e189-479b-b4ec-2b844998c77b">

**Comment by blanklogic** [comment]
You can view the questions from the lecture on Friday that has been recorded and uploaded on canvas. They are bonus questions that were went through by Prof Damith during the Friday lecture time slot.

**Comment by AlphaPyke** [comment]
ah ok thanks!
