### ISSUE TITLE
Request to use com.openCSV and org.json Third-party libraries

### ISSUE THREAD

**Issue by Hoodini231** [nus-cs2103-AY2425S1/forum#601]
## Library
[com.opencsv.CSVReader](https://opencsv.sourceforge.net/jacoco/com.opencsv/index.source.html)
[org.json](https://mvnrepository.com/artifact/org.json/json)

## Purpose
Used these libraries to read json and CSV objects into AB3 for import and export of contact data.

## License
opencsv has a Apache 2.0 license (https://mvnrepository.com/artifact/com.opencsv/opencsv)
org.json has a public license (https://mvnrepository.com/artifact/org.json/json)

**Comment by damithc** [comment]
@Hoodini231 

org.json: Approved.

OpenCSV: approved in #503
