### ISSUE TITLE
PRs Authored in Milestone v1.4 but not Reflected in tP Progress Dashboard

### ISSUE THREAD

**Issue by kahsuann** [nus-cs2103-AY2425S1/forum#603]
My teammates @Jasperabez @hanscau and @C5hives had created (and merged) PRs during the v1.4 milestone, but the PRs appear to have gone undetected.
As such, their progress dashboards mark v1.4 PRs as incomplete.

![image](https://github.com/user-attachments/assets/38dde34b-29d0-4dc4-b9d7-960519673b57)

Is this an error with the grading scripts, or did we miss something that caused the PRs to be considered invalid? Thanks for the assistance!

**Comment by damithc** [comment]
@kahsuann Thanks for reporting this. Looks like PRs that were not sent from a fork were not counted (but they should be counted in v1.4, as we also allow the feature branch workflow in v1.4). I've updated the dashboard to count them as well. This item should be green for those team members now.

**Comment by C5hives** [comment]
The dashboard is reflecting the v1.4 progress correctly now. Thanks prof!
