### ISSUE TITLE
Question about UML Sequence diagram loops

### ISSUE THREAD

**Issue by nuagetsu** [nus-cs2103-AY2425S1/forum#604]
If I need to reference the index number in a for loop within my UML sequence diagram, how should I go about it? I searched the course website but couldn't seem to find information about that.

For example, if I have a for loop 

```
for (int i = 0; i < 10; i++ ) {
    EgClass.egFunc(i)
}
```
how do I represent the index i within my sequence diagram? Or is it simply unnecessary and I can write the function as `egFunc()` without the parameter? Any advice would be appreciated. Thank you!

**Comment by damithc** [comment]
@EdaYeo for the condition of the `loop` frame, you can use something like `[for i=0..10]` to indicate the iteration counter variable.
