### ISSUE TITLE
MarkBind website not working

### ISSUE THREAD

**Issue by verakohh** [nus-cs2103-AY2425S1/forum#605]
Hi, I'm facing a bug where the layout for my markbind website for my User Guide isn't showing up properly( missing sidebars, navigation bar, and wrong fonts) as seen in the [first picture](https://ay2425s1-cs2103t-t17-1.github.io/tp/UserGuide.html) below. I've tried running the website on an incognito webpage instead but still got the same result (so I doubt is a caching problem). 
Is there anything that I could try?

<img width="1424" alt="image" src="https://github.com/user-attachments/assets/eb38ff7d-f75e-4763-85be-5962c42ffc31">

<img width="497" alt="image" src="https://github.com/user-attachments/assets/8a6331b6-eece-44a1-a67b-d75020d30d07">

my site.json file
```
{
  "baseUrl": "/tp",
  "titlePrefix": "UniVerse",
  "titleSuffix": "UniVerse",
  "faviconPath": "images/SeEduLogo.png",
  "style": {
    "codeTheme": "light"
  },
  "ignore": [
    "_markbind/layouts/*",
    "_markbind/logs/*",
    "_site/*",
    "site.json",
    "*.md",
    "*.njk",
    ".git/*",
    "node_modules/*"
  ],
  "pagesExclude": ["node_modules/*"],
  "pages": [
    {
      "glob": ["**/index.md", "**/*.md"]
    }
  ],
  "deploy": {
    "message": "Site Update."
  },
  "timeZone": "Asia/Singapore"
}
```

**Comment by ghos7ie** [comment]
hi @verakohh, have you tried removing `"baseUrl":"/tp"` to see if the site works?

i double checked against my own group's and our baseUrl is empty.


Would be helpful if you pointed out which PR caused this issue to occur too

**Comment by verakohh** [comment]
hi @ghos7ie! im gonna try that out now but when i was updating the user guide and tested it locally, the website had all the normal layouts. also regarding the PR, it has been like that since the website was set up i think

**Comment by damithc** [comment]
@verakohh When debugging issues like this, it helps to go back to the last point it worked, and see what changed since then.
You can also check the CI output of the last time the website was built, to see if something went wrong in that particular build.

**Comment by verakohh** [comment]
hi prof @damithc , okay i'll try to do that. is there a reason why the website could look ok locally but does not work once its deployed?

<img width="1544" alt="image" src="https://github.com/user-attachments/assets/512496cf-1807-4522-99a0-8e5b89be49cc">
this is how it looks like locally

**Comment by damithc** [comment]
@verakohh If the problem is in the deployed site, you might want to cross-check your settings against this guide https://se-education.org/guides/tutorials/markbind-forked-sites.html

**Comment by verakohh** [comment]
Okay it works now thank you prof! @damithc
