### ISSUE TITLE
DG diagrams

### ISSUE THREAD

**Issue by aditig0305** [nus-cs2103-AY2425S1/forum#606]
This is ComponentManagers.puml
![telegram-cloud-photo-size-5-6129597692595258374-y](https://github.com/user-attachments/assets/c1a29379-efd9-4a97-9841-a88872fdfef6)

How do we solve this problem where one of the DG diagrams doesn't show a preview? We traced the file history and it does not seem like any of our team members made any changes. How can we fix this?

**Comment by tanwartushar** [comment]
Hi @aditig0305 

I faced a similar issue with the previews.
Installing `Graphviz` fixed it for me. Found the fix on this [forum](https://stackoverflow.com/questions/54413962/cant-render-component-diagram-with-plantuml-in-intellij)

**Comment by josh1248** [comment]
Yep, had the same issue and solution as @tanwartushar. If you are using a mac, do rmb to install a package manager first - a good one is Homebrew at https://brew.sh/ , then afterwards can run `brew install graphviz`. (My solution for Macbook M2)

**Comment by aditig0305** [comment]
Thank you!
