### ISSUE TITLE
Issues with PDF Header and Duplicate Heading in User Guide

### ISSUE THREAD

**Issue by ruiming97** [nus-cs2103-AY2425S1/forum#607]
I have encountered a couple of issues while working on our User Guide that I need some help resolving:

1. PDF Header Displays Incorrect Name
When attempting to print the user guide as a PDF, the header still shows "UniNet," which is our previous product name, instead of "AdmiNUS." We have already updated the title in the config.yml file to "AdmiNUS", and updated it to Prof Damith, but the change doesn’t seem to be reflected in the PDF output. Could you provide some guidance on what might be causing this discrepancy and how I can correct it?

2. Duplicate Heading on the Website
I am also facing an issue with duplicate headings appearing on the AdmiNUS website. In the markdown file, I have only defined a single instance of the heading, but it appears twice on the generated webpage. When I tried removing the heading from the markdown file, both instances of the heading disappeared from the website. I have attached screenshots to illustrate this issue:

<img width="1286" alt="image" src="https://github.com/user-attachments/assets/8281e753-6573-4421-83bd-c6da82b821fd">
Below is what I have in my `UserGuide.md` 
<img width="1198" alt="image" src="https://github.com/user-attachments/assets/38fe82f9-8c8b-4c4d-91c4-86868c839815">

To add on: We have already change the title field in `_config.yml` to our latest product name.

**Comment by ruiming97** [comment]
Hi just to update, I've already fixed the first issue, but still haven't found the solution for the second issue (duplicate heading) Appreciate any advice!

**Comment by damithc** [comment]
A general suggestion is to compare the current (broken) code with an earlier version that didn't have this problem, and examine the differences. For example, the original AB3 UG doesn't have this problem. So, you can compare AB3 UG with your UG code to see what's different.

**Comment by ruiming97** [comment]
> A general suggestion is to compare the current (broken) code with an earlier version that didn't have this problem, and examine the differences. For example, the original AB3 UG doesn't have this problem. So, you can compare AB3 UG with your UG code to see what's different.

Thank you prof for the advice! I've solved it already
