### ISSUE TITLE
Request to use Material Icons and Fonts

### ISSUE THREAD

**Issue by InfinityTwo** [nus-cs2103-AY2425S1/forum#609]
## Library

All of [Google's Material Icons and Fonts](https://fonts.google.com)

## Purpose

User Guide (and the rest of the tP website) styling

## License

Fonts: [SIL Open Font License](https://developers.google.com/fonts/faq#can_i_use_any_font_in_a_commercial_product) Also accessible via the FAQ button on the left navigation bar at [fonts.google.com](https://fonts.google.com)
Icons: [Apache License 2.0](https://fonts.google.com/icons) Stated on one of the components below the searchbar

**Comment by damithc** [comment]
@InfinityTwo Approved.
