### ISSUE TITLE
PE-D and PE: Are we allowed to bring notes in/write notes during the PE?

### ISSUE THREAD

**Issue by ghos7ie** [nus-cs2103-AY2425S1/forum#610]
For both PEs, are we allowed to use notes (e.g. checklists, common testing scenarios etc.) while testing?

Additionally, are we allowed to use paper to perhaps keep track of what we have tested?

**Comment by damithc** [comment]
@ghos7ie Yes to both.

**Comment by ghos7ie** [comment]
thanks! @damithc 

I will keep the issue open until post PE-D in case anyone is curious

**Comment by PrishaVP** [comment]
can we only refer to hardcopy materials? or can we refer to anything we want?

**Comment by ghos7ie** [comment]
@PrishaVP im assuming softcopy is allowed

**Comment by damithc** [comment]
@PrishaVP Soft copies allowed.
