### ISSUE TITLE
Meaning of case-sensitive keywords 

### ISSUE THREAD

**Issue by kngys** [nus-cs2103-AY2425S1/forum#611]
Under feature flaws, it is stated that making keywords case-sensitive when there is no need for it is considered a feature flaw. 
Could I clarify what does keyword here refer to? Taking the add command for example, does it mean that the `add` command word should not be case-sensitive, or that even its prefixes (e.g. `n/`, `p/` , `e/` etc.) should not be case-sensitive as well? (i.e. `ADD N/NAME p/PHONE...` should be accepted as valid input for add command).  Thank you!

**Comment by ghos7ie** [comment]
Hi @kngys, my group interpreted keywords as  command words and also the parameters your product has.

i.e. `add` and `ADD` or even `Add` should be recognised as the same command word

regarding parameters, an example could be like names such as `John Doe` and `john doe` should be recognised the as the same name


ultimately, i think it is up to your group's discretion as long as you guys can justify it!

**Comment by kngys** [comment]
Thanks for your input! Did your group also interpret prefixes to be keywords?

i.e. `add n/NAME p/PHONE e/EMAIL ...` and `add N/NAME P/PHONE E/EMAIL...` should both be accepted where `n/`, `p/` and `e/` are the prefixes and are `N/` , `P/` and `E/` when capitalized.

**Comment by yadobler** [comment]
> Thanks for your input! Did your group also interpret prefixes to be keywords?
> 
> i.e. `add n/NAME p/PHONE e/EMAIL ...` and `add N/NAME P/PHONE E/EMAIL...` should both be accepted where `n/`, `p/` and `e/` are the prefixes and are `N/` , `P/` and `E/` when capitalized.

I think this is up to your intepretation

`Keyword` in parsing would refer to any "words with special meanings"[^1]. Basically **constant** tokens. hm hm hm.

The correct question you might wanna ask is "is there a need hmhmhmhmhmhmhmh".

[^1]: [Microsoft definition of C compiler keyword](https://learn.microsoft.com/en-us/cpp/c-language/c-keywords?view=msvc-170)

**Comment by damithc** [comment]
> Under feature flaws, it is stated that making keywords case-sensitive when there is no need for it is considered a feature flaw.


![image](https://github.com/user-attachments/assets/929a6621-6388-4d05-934d-8228113c2f78)

@kngys In there we are referring to search keywords i.e., when you are searching for contacts, the words you are searching for. But the point about case-sensitivity applies to other places too. And as @ghos7ie mentioned, it is up to your discretion -- i.e., you should be able to justify the case sensitivity (or insensitivity) of each feature from the user's point of view. In some cases it can be debatable with both alternatives having strong justifications e.g., Windows chose filenames to be case-insensitive but Unix chose them to be case sensitive.
