### ISSUE TITLE
Unable to display Documentation on Github pages

### ISSUE THREAD

**Issue by Timenikhil** [nus-cs2103-AY2425S1/forum#613]
The Documentation, index.md, UserGuide etc, are rendered properly on localhost, but markbind doesn't render on github pages

* localhost works on windows and mac, Java 17
* No errors
* https://github.com/AY2425S1-CS2103T-W09-2/tp/blob/master/.github/workflows/docs.yml

**Comment by damithc** [comment]
@Timenikhil Can you give more detail/screenshots?

**Comment by damithc** [comment]
Also, it helps if you try to locate the last point at which things worked fine, and examine what changes you did since then.

**Comment by Timenikhil** [comment]
> @Timenikhil Can you give more detail/screenshots?

This is the deployed version
<img width="1701" alt="image" src="https://github.com/user-attachments/assets/11fc1f88-1668-496a-92ec-029ebe97104e">

Same page local version:
<img width="1715" alt="image" src="https://github.com/user-attachments/assets/5110c33a-630a-4b30-9e4f-c6c76f9be6be">

> Also, it helps if you try to locate the last point at which things worked fine, and examine what changes you did since then.

The page broke when me migrated to markbind from jekyll, a few weeks ago.
During the markbind commit, I only copied over the changes from switch-to-markbind, we couldn't merge because we had edited the docs

For github pages settings I have tried 

* Deploy from actions
* Deploy from master/root
* Deploy from master/docs

None of them work

**Comment by damithc** [comment]
@Timenikhil Also share a screenshot of the gh-pages setting of your repo.

**Comment by damithc** [comment]
@Timenikhil Also, compare against our guide [here](https://se-education.org/guides/tutorials/markbind-forked-sites.html) to confirm you did not deviate at any step.

**Comment by Timenikhil** [comment]
> @Timenikhil Also share a screenshot of the gh-pages setting of your repo.
<img width="707" alt="image" src="https://github.com/user-attachments/assets/69e167a5-547a-4c09-b12a-2268556131b3">

**Comment by damithc** [comment]
@Timenikhil As per the screenshot, your settings don't match the ones we have prescribed in the guide.

**Comment by Timenikhil** [comment]
> @Timenikhil Also, compare against our guide [here](https://se-education.org/guides/tutorials/markbind-forked-sites.html) to confirm you did not deviate at any step.

Step 1 :
<img width="1094" alt="image" src="https://github.com/user-attachments/assets/ed796cc0-962a-49b1-9dde-3f6cc4a5151c">
Step 2 :
docs.yml
<img width="725" alt="image" src="https://github.com/user-attachments/assets/9a0ad558-ee17-4c1a-973e-d8f3e6930c12">
default.md
<img width="1354" alt="image" src="https://github.com/user-attachments/assets/8997262f-13aa-41d8-ae12-4063c724ad46">
site.json
<img width="648" alt="image" src="https://github.com/user-attachments/assets/7565a8e5-7fc3-4865-88c2-13d02c209371">

Step 4 : 
shown above, with master/root it displayed readme.md instead of index.md so had to switch to docs

**Comment by Timenikhil** [comment]
> @Timenikhil As per the screenshot, your settings don't match the ones we have prescribed in the guide.

I tried setting it to root/ as well, it displays README.md, also without markbind rendering

**Comment by Timenikhil** [comment]
<img width="1711" alt="image" src="https://github.com/user-attachments/assets/dd21eb72-9b80-4adc-b9d0-6f0c5306fd92">

**Comment by Timenikhil** [comment]
on navigating to /tp/docs manually the markbind render is still missing
<img width="1725" alt="image" src="https://github.com/user-attachments/assets/854b0bf0-49eb-4d3b-b09c-74d2373020ba">

**Comment by damithc** [comment]
Try this:
1. Change settings to the ones given in the guide. Branch should be `gh-pages` and folder should be `root`.
2. Rerun CI (or push a dummy commit) to rebuild the site. Give it a few minutes. Check the site. Ensure you are looking at the latest version and not a cached copy (you can force refresh the browser, and check the timestamp shown in the footer of the page)
3. If still not working, post a screenshot of the new settings so that we can confirm they are as expected.

For reference:
![image](https://github.com/user-attachments/assets/4315874e-8a81-4668-80d2-ed4c5972fc6a)

**Comment by Timenikhil** [comment]
Thank you prof it works now, 
the problem was not with the root, the problem was with the branch, I was deploying from master branch, as I presumed gh pages was the name of the working branch for the tutorial/guide (like the switch-to-markbind branch), before being merged into the master branch, 

As Jekyll and all other github pages deployments run from master branch/docs; I believed that would be the corresponding setting in our repo as well.

Turns out gh-pages is a separate branch maintained by the Github Actions, not us; so for Markbind that needs to be active irrespective of other tp settings.

Thank you once again for your help.

**Comment by damithc** [comment]
> Thank you prof it works now

Great to hear that @Timenikhil 

> Turns out gh-pages is a separate branch maintained by the Github Actions, not us; so for Markbind that needs to be active irrespective of other tp settings.

Yup. I just added a small note to the guide to explain this point, in case future students face a similar problem.

**Comment by XinghuaJulia** [comment]
Greetings! I faced a similar issue, turns out, I did not deploy the site on githube pages correctly... Make sure on the settings of your team's forked repo, under pages, it says "gh-pages" "root" and not "master" "docs"... Once I updated it, wait for a few minutes and it worked!

Not sure if this will help, but yeah :DDDD
