### ISSUE TITLE
Committing from future

### ISSUE THREAD

**Issue by IanCheah** [nus-cs2103-AY2425S1/forum#614]
![image](https://github.com/user-attachments/assets/1db80139-5635-4001-a43d-b7469f683b4a)

I was trying to test what happens to the reminders field when the date of the event has past today's date. So i went to change the date and time of my laptop. However, after testing, I forgot to change the date and time back to current. Hence, I did a few commits from the future, I wonder if this will spoil any of the grading scripts? What should I do?

**Comment by damithc** [comment]
@IanCheah If the branch is not merged yet, it is possible to update the timestamp to the current date/time without too much extra work or risk, especially if the branch is in your fork and not in the team repo.

**Comment by IanCheah** [comment]
Hi @damithc the pr was merged into the team's repo before me realising this issue, will it create problems for the grading scripts?

**Comment by damithc** [comment]
@IanCheah It should not be an issue if you have other commits (with the correct time stamp) in that week.

**Comment by IanCheah** [comment]
okay thanks!
