### ISSUE TITLE
tP admin tasks in https://nus-cs2103-ay2425s1.github.io/dashboards/contents/tp-progress.html Seems to be BUGGED

### ISSUE THREAD

**Issue by SeeYangZhi** [nus-cs2103-AY2425S1/forum#615]
Some tags appear red even though it was definitely green over the past few weeks. Specifically v1.3 PR in my case

**Comment by damithc** [comment]
@SeeYangZhi we only count PRs that come from a branch other than the `master` branch, as that is a requirement for both the workflows we accept (i.e., forking workflow, and feature branch workflow). It's possible that this constraint was not correctly applied earlier, hence some PRs coming from the `master` branch could have been counted when they should not have been counted.
It should be fine (i.e., no effect on marks) provided you remember to use a different branch for future PRs, and you have at least 5 such PRs in total (tracked by the `Branch PRs` item in the dashboard).

**Comment by SeeYangZhi** [comment]
@damithc Okay thanks prof, I understand what you have just mentioned. I think the dashboard was green previously but only recently it is reflecting differently, therefore I thought it is a bug. 

https://github.com/AY2425S1-CS2103-F13-1/tp/issues/130 this issue with the linked PR tagged to milestone 1.3 satisfies what you have just described - "PRs that come from a branch other than the `master` branch", so the tag should by right be green as it once was.

**Comment by damithc** [comment]
@SeeYangZhi 

> [AY2425S1-CS2103-F13-1/tp#130](https://github.com/AY2425S1-CS2103-F13-1/tp/issues/130) this issue with the linked PR tagged to milestone 1.3 satisfies what you have just described - "PRs that come from a branch other than the `master` branch", so the tag should by right be green as it once was.

That PR is in v1.3 but is following the feature branch workflow, which wasn't allowed till v1.4. In v1.3, only PRs following the forking workflow were counted (i.e., the PR should come from a fork).

**Comment by SeeYangZhi** [comment]
> It should be fine (i.e., no effect on marks) provided you remember to use a different branch for future PRs, and you have at least 5 such PRs in total (tracked by the `Branch PRs` item in the dashboard).

Okay thanks prof, we were 1 week ahead and went with the feature branch in v1.3. Since this has no effect on marks and is not a bug on the dashboard, I will close this issue.
