### ISSUE TITLE
Feature Freeze For UI

### ISSUE THREAD

**Issue by S-K-Y-Light** [nus-cs2103-AY2425S1/forum#617]
If there's a Bug in the UI discovered after the feature freeze, are we allowed to change the UI to fix the bug? The feature Freeze stated on the website that UI changes aren't allowed

**Comment by damithc** [comment]
@S-K-Y-Light Bug fixing is allowed, provided it meets our strict criteria of a bug. See Q1 below:

![image](https://github.com/user-attachments/assets/7dca2a77-35c0-4cb9-a346-061b4431f202)
