### ISSUE TITLE
Remove utility for features not completed

### ISSUE THREAD

**Issue by Wxy2003-xy** [nus-cs2103-AY2425S1/forum#618]
Hi may i know if we need to remove the utility classes and methods for features we initially planned but unable to complete by the final deadline? Or may we keep them for (unlikely) future development? These utilities are properly tested but not used in exisitng features accessible to users.

**Comment by damithc** [comment]
@Wxy2003-xy It's up to you. If you keep it, it will be will be graded (can increase of decrease tP marks, depending on the quality of the said code).

**Comment by shotnothing** [comment]
Would this be penalized as keeping dead code?
wrt https://nus-cs2103-ay2425s1.github.io/website/se-book-adapted/chapters/codeQuality.html#delete-dead-code

**Comment by damithc** [comment]
@shotnothing commented out code will be penalised, but we do not penalise unused code.

**Comment by Wxy2003-xy** [comment]
> @Wxy2003-xy It's up to you. If you keep it, it will be will be graded (can increase of decrease tP marks, depending on the quality of the said code).

Ok thank you!
