### ISSUE TITLE
Clarification on Level-7 and Level-8

### ISSUE THREAD

**Issue by Jianwen0451** [nus-cs2103-AY2425S1/forum#62]
Since we have done Level-7 and Level-8 in a separate branch. Do we need to merge them back to master after we are done?

**Comment by hooyushing** [comment]
Yup! Do merge them back as mentioned here
<img width="832" alt="Screenshot 2024-08-25 at 11 18 49 PM" src="https://github.com/user-attachments/assets/648c4400-30ae-4332-bf1a-f159785328eb">

**Comment by Jianwen0451** [comment]
Ok noted, thank you!
