### ISSUE TITLE
Updating the release

### ISSUE THREAD

**Issue by JoanneHing** [nus-cs2103-AY2425S1/forum#625]
Hi prof! Our team released v1.5 with the UG pdf file but we missed out the DG pdf file. Should we edit the current release or make a new release with the DG? As we worry editing the current release may affect the timeline.

**Comment by damithc** [comment]
@JoanneHing Yes, you may add the DG now. It will not affect marks. You can do another release too, provided you do it before 10am Friday.

**Comment by JoanneHing** [comment]
Alright thank you prof!
