### ISSUE TITLE
Chrome's PDF engine unable to render Heading 4 with correct sizing

### ISSUE THREAD

**Issue by ghos7ie** [nus-cs2103-AY2425S1/forum#626]
Just wanted to check if anyone one else is facing the same issue, I've checked that the issue is not caused by using `backticks` in the heading

From my group's PDF

![image](https://github.com/user-attachments/assets/08924e49-1b0b-400e-aa87-2cc364f90b7b)

From my group's website

![image](https://github.com/user-attachments/assets/2d281109-c7b7-40cc-8744-e28b91ecfc3a)

**Comment by yadobler** [comment]
![image](https://github.com/user-attachments/assets/ef1fbf9d-af7f-4a99-88f5-7f1ee64e6bd8)

looking at this, it's h6, and confirmed here:

![image](https://github.com/user-attachments/assets/54112baa-2427-46ae-b360-24fe6236700a)

In your [stylesheet](https://github.com/AY2425S1-CS2103-F12-2/tp/blob/master/docs/stylesheets/main.css), there is no formatting setting for `h6` but there is for `h1` to `h5`

![image](https://github.com/user-attachments/assets/94c2aa71-d5f7-468d-8ee3-f4f629027cb7)

I suspect in the browser, it just happens to render nicely, but printing, the "default" for `h6` is larger than the `0.7rem` size of `h5`.

try adding a custom font size for `h6`.

**Comment by ghos7ie** [comment]
ahh, nice catch @yadobler 

thanks so much :) i'll add it in to the stylesheet!
