### ISSUE TITLE
DG not in scope for PE-D

### ISSUE THREAD

**Issue by Feng1231** [nus-cs2103-AY2425S1/forum#628]
Is DG in the scope for PE-D? 
![image](https://github.com/user-attachments/assets/878019af-c9e0-47ff-918d-f8a0541c9ac3)

Only for the actual PE, i see the instructions to test using UG and DG.
![image](https://github.com/user-attachments/assets/6dba04ac-5d12-458f-9067-8b0dcc6486bf)

However, it is stated that we can submit DG bugs in PE-D
![image](https://github.com/user-attachments/assets/b79c61fe-c70c-4fbb-b27d-8fec5373dc12)

**Comment by damithc** [comment]
@Feng1231 Both DG and UG are in the scope of PE-D. I've updated instructions just now.

**Comment by Feng1231** [comment]
@damithc 
Noted prof, may I check which email do I contact the profs with in teams?

**Comment by damithc** [comment]
> Noted prof, may I check which email do I contact the profs with in teams?

Me. Search for `Damith`

**Comment by Feng1231** [comment]
Thank you prof
