### ISSUE TITLE
Clarification on UI text getting truncated

### ISSUE THREAD

**Issue by oneBoz** [nus-cs2103-AY2425S1/forum#629]
<img width="752" alt="Screenshot 2024-11-08 at 9 19 22 PM" src="https://github.com/user-attachments/assets/7e45ed31-2b48-4ed9-850b-f684d8823c66">

<img width="963" alt="Screenshot 2024-11-08 at 9 30 45 PM" src="https://github.com/user-attachments/assets/7f550a97-2b02-427b-b5d5-ed4666f6991e">

Hello, may I check if forcing the Ui text to overflow in this manner is considered as a bug since it is not "normal" to have an extremely long address

**Comment by damithc** [comment]
@oneBoz If you are asking if this can be fixed in v1.6, the answer is, 'only if there is no other way for the user to see the truncated part'.

**Comment by oneBoz** [comment]
Would it be possible if we add a command for the user to view all the details via a pop up window since there is a limit to how much resizing can be done

**Comment by damithc** [comment]
> Would it be possible if we add a command for the user to view all the details via a pop up window since there is a limit to how much resizing can be done

@oneBoz You are not allowed to add commands/features at this point. You can list such an enhancement under the 'Planned Enhancements' section though.

**Comment by Zenkoh1** [comment]
> @oneBoz You are not allowed to add commands/features at this point. You can list such an enhancement under the 'Planned Enhancements' section though.

Just to clarify, are we allowed to add new commands under the `Planned Enhancements` section (e.g. Given that I currently only have a command to add a field, can I add an enhancement for adding a delete command for that field)? 

Given that the website says this in the `Planned Enhancements` section

>Each enhancement should be a tweak to an existing feature, and should not be a new feature altogether.

**Comment by damithc** [comment]
> Just to clarify, are we allowed to add new commands under the `Planned Enhancements` section (e.g. Given that I currently only have a command to add a field, can I add an enhancement for adding a delete command for that field)?
> 
> Given that the website says this in the `Planned Enhancements` section
> 
> > Each enhancement should be a tweak to an existing feature, and should not be a new feature altogether.

@Zenkoh1 Hmm... 🤔 I guess this can be allowed, given it is a counterpart to an existing feature. The alternative is to remove the feature altogether (and list it as a 'coming soon' feature), given it is not 'complete'. Testers can argue that this feature shouldn't have been released in the first place.
