### ISSUE TITLE
Typo in JAR notes

### ISSUE THREAD

**Issue by Incogdino** [nus-cs2103-AY2425S1/forum#63]
![image](https://github.com/user-attachments/assets/50ba3949-d973-443f-8b47-e425b8210558)

Link to site: https://se-education.org/guides/tutorials/jar.html

In line 1, it says "If you app has ..."

I think it should be "If your app has..."

**Comment by damithc** [comment]
Thanks for the bug report, @Incogdino 
Fixed.

**Comment by Incogdino** [comment]
![image](https://github.com/user-attachments/assets/e6843510-0b7a-4977-9180-1c5b9fe9307f)
Reopening this thread again but for the same set of notes, "create" is missing an "e" for the last line.

**Comment by damithc** [comment]
> Reopening this thread again but for the same set of notes, "create" is missing an "e" for the last line.

Thanks again @Incogdino 
Fixed.
