### ISSUE TITLE
Possibly putting Mass Identity Check section in a wrong place

### ISSUE THREAD

**Issue by DennieDan** [nus-cs2103-AY2425S1/forum#630]
In the [**PE Phase 1 - Part I**](https://nus-cs2103-ay2425s1.github.io/website/admin/tp-pe.html#pe-phase-1-part-i-product-testing-60-minutes) section of our course website, the **Mass Identity Check** section seems to be put in a wrong position (it is put as a bullet point of Tips on assigning the severity tag). Instead, shouldn't it be placed before that?
![image](https://github.com/user-attachments/assets/3ebc8d56-84c5-4c57-9df3-6eacc46212fe)

**Comment by damithc** [comment]
Thanks for the heads up, @DennieDan 
Fixed.
