### ISSUE TITLE
V1.6 set up

### ISSUE THREAD

**Issue by JoanneHing** [nus-cs2103-AY2425S1/forum#631]
<img width="574" alt="Screenshot 2024-11-08 at 11 16 03 PM" src="https://github.com/user-attachments/assets/bd17eb40-24ec-4c12-b6a2-53281ba35c15">

Hi prof is this v1.6 set up deadline marked wrongly? Because if I remember correctly it is not there before today.

**Comment by damithc** [comment]
Good catch @JoanneHing Yes, this should not be red yet. Will fix at the next update.

**Comment by JoanneHing** [comment]
Thank you prof!
