### ISSUE TITLE
CATCHer does not embed .mov file with github issues

### ISSUE THREAD

**Issue by kikokidayo** [nus-cs2103-AY2425S1/forum#633]
Hello, for the issues I reported and demonstrated with a video, the video does not appear embedded in the github issues although it is clearly refelcted in the CATcher issue reporter, so I am worried that this might affect the clarity of my bug report and that it will be construed as less effective by the team. May I edit the github issue directly to include the video? Thanks!

![Screenshot 2024-11-09 at 12 43 01 AM](https://github.com/user-attachments/assets/20ebc328-5af6-43cd-84ae-e687e084a823)

![Screenshot 2024-11-09 at 12 43 49 AM](https://github.com/user-attachments/assets/22fd9679-798a-4bc8-8e05-7521d57466f7)

**Comment by damithc** [comment]
@kikokidayo Which issue number?

**Comment by kikokidayo** [comment]
@damithc [Issue #6](https://github.com/kikokidayo/ped/issues/6), thanks!

**Comment by damithc** [comment]
@kikokidayo 
1. The bug has been transferred to the team. You can go to your corresponding GitHub issue in your ped/issues, navigate to the transferred issue in the team's repo, and post your video there.
2. We need to figure out why the video did not appear in the GitHub issue in the first place. When I added a video through CATcher, it appears in GitHub (see below). Perhaps you can create another dummy issue in CATcher and add a video to see if you can replicate the problem?

![image](https://github.com/user-attachments/assets/13b78a97-aa53-4c39-8ab9-2993b6c907f2)

**Comment by kikokidayo** [comment]
@damithc 

Ah my bad, I think it's because I removed the video link text from the issue since I only wanted the video itself to be shown without the video:..... text. I have responded to the team's issue with the video and it previews fine. I don't think it's an issue anymore. Thanks for your time and speedy responses Prof!
