### ISSUE TITLE
Can this be considered a bug?

### ISSUE THREAD

**Issue by cweijin** [nus-cs2103-AY2425S1/forum#635]
Hi, our app allows special characters (`'`, `-`, `/`) in names when using the add command. However, we encountered a bug with the find command, which rejects inputs containing these valid special characters due to outdated validation regex. 

For example, "M'Lynn" is accepted by add but triggers an "invalid name" error in `find M'Lynn`. Would this be classified as a "Rejecting valid input" bug that can be fixed in v1.6?

<img width="507" alt="image" src="https://github.com/user-attachments/assets/17708234-2eef-4140-81ee-a8a1dea164ac">
<img width="507" alt="image" src="https://github.com/user-attachments/assets/a5709675-dba6-43e1-a8d8-a46bc658ca97">

Additionally, the find command's UI text currently displays incorrect information. Can we consider this a bug and address it together with the above-mentioned issue?

<img width="524" alt="image" src="https://github.com/user-attachments/assets/b1536df3-ea66-4f9c-93cf-e2e857642bc5">

**Comment by damithc** [comment]
> For example, "M'Lynn" is accepted by add but triggers an "invalid name" error in `find M'Lynn`. Would this be classified as a "Rejecting valid input" bug that can be fixed in v1.6?

@cweijin Yes.

> Additionally, the find command's UI text currently displays incorrect information. Can we consider this a bug and address it together with the above-mentioned issue?

Can you elaborate what's 'incorrect'?

**Comment by cweijin** [comment]
Hi Prof, thanks for the reply.

> Can you elaborate what's 'incorrect'?

By updating the validation regex for the find command to accept valid inputs, it will allow special characters (`'`, `-`, `/`) and up to 255 characters (since our app accepts names of up to 255 characters). However, the current invalid input message states "Please make sure the name is between 1-100 characters and only contains alphabets and spaces." This information is incorrect because we actually allow certain special characters and up to 255 characters.

![image](https://github.com/user-attachments/assets/b851d578-e40f-433d-9f9b-da5a176edb96)

Hence we would like to update the message to: "Please make sure the name is between 1-255 characters and only contains alphabets, spaces, and these special characters (excluding the parentheses): (- / ')."

Would this be permissible?

**Comment by damithc** [comment]
> Hence we would like to update the message to: "Please make sure the name is between 1-255 characters and only contains alphabets, spaces, and these special characters (excluding the parentheses): (- / ')."

@cweijin Yes, the current error message can be considered incorrect and the update can be allowed.

**Comment by cweijin** [comment]
Thank you for the clarification Prof!
