### ISSUE TITLE
Request for compiled MCQ questions from the weekly quizzes

### ISSUE THREAD

**Issue by Virusrwj223** [nus-cs2103-AY2425S1/forum#637]
Hi teaching team, I am wondering if it is possible to provide us with a compiled list of all the questions that we had from the weekly quizzes? I am not sure if retaking the quizzes on canvas for practice will mark the quiz as a late submission. If it will be, I think it will really help us to prepare for the theory exam without having the correct answer marked immediately after.

**Comment by damithc** [comment]
@Virusrwj223 All quizzes are reopened after the deadline is over, and you will be able to see the answer immediately when resubmitting them. Trying them will not affect participation.
