### ISSUE TITLE
Indentation after wrapping text for block tags in JavaDoc

### ISSUE THREAD

**Issue by Feng1231** [nus-cs2103-AY2425S1/forum#64]
I am writing the javadocs for the java files and sometimes the description for the '@' is too long to be fitted into one line.

I can't seem to find any rules to follow in our coding standard, under the section **Comments**

This is according to google's coding standard:
[7.1.3 Block tags](https://google.github.io/styleguide/javaguide.html#s7.1.3-javadoc-block-tags)
Any of the standard "block tags" that are used appear in the order @param, @return, @throws, @deprecated, and these four types never appear with an empty description. When a block tag doesn't fit on a single line, continuation lines are indented four (or more) spaces from the position of the @.

This is the indentation rule under 'Layout'
![image](https://github.com/user-attachments/assets/f7673469-3a08-4761-acdc-28d8abc31f4d)

Which one should I follow?

**Comment by damithc** [comment]
@Feng1231 You can follow either one, but follow it consistently.

My take:
In Java code, we use 8-space indentation for line wrapping, to differentiate it from regular 4-space indentation used for nesting.
In javadoc comments, there is no such regular nesting. So, using 4-spaces for line wrapping seems reasonable.

**Comment by Feng1231** [comment]
Thanks prof😎
