### ISSUE TITLE
Improving code quality after feature freeze

### ISSUE THREAD

**Issue by NorbertLoh** [nus-cs2103-AY2425S1/forum#642]
Hi prof I read that improving code quality is still allowed in v1.6. Can confirm that I can still improve SLAP, LOD, extract methods, use loggings and asserts (not creating or handling new exceptions) and standardise my javadocs? Thank you!

**Comment by damithc** [comment]
@NorbertLoh Yes.

**Comment by NorbertLoh** [comment]
> @NorbertLoh Yes.

Ok thank you!
