### ISSUE TITLE
Broken hyperlink seems to be a problem with the 'Preview' software

### ISSUE THREAD

**Issue by rahula1008** [nus-cs2103-AY2425S1/forum#643]
Dear all,

We received a bug report stating that our hyperlink in our user guide pdf was broken, but when we investigated, we found that it is only on certain softwares like 'Preview' where this occurred, whereas softwares like Adobe were able to handle it fine. Is there anything we can do to fix this or is this out of scope?

Thanks

**Comment by damithc** [comment]
@rahula1008 Not a direct answer but related: it is a document update, which means there is no restriction w.r.t. the feature freeze.
