### ISSUE TITLE
How to deal with unrealistic inputs?

### ISSUE THREAD

**Issue by jktang14** [nus-cs2103-AY2425S1/forum#646]
How do we handle supposed feature flaws that are caused by unrealistic inputs?

For example, my group received multiple bug reports for the following cases.

1. Tester inputted an excessively long address that is unrealistic in the real world, which led to the UI needing to be scrolled to the right to view the address
![image](https://github.com/user-attachments/assets/6f5e6ebd-8d6f-4514-b801-3fc398acd9dd)
2. Tester inputted an excessively long phone number that is unrealistic in the real world
![image](https://github.com/user-attachments/assets/1d608f1b-9385-4139-9430-45dbaccc2592)
3. Tester inputted an excessively large index which resulted in a faulty error message.
![image](https://github.com/user-attachments/assets/6f45787b-a506-4dff-8c92-af36f05db195)

Would unrealistic inputs even be accepted as bugs in the PE? Because if so then we would need to add them under planned enhancements. Thanks!

**Comment by damithc** [comment]
@jktang14 To find how these are dealt with in the PE, you can refer to https://nus-cs2103-ay2425s1.github.io/website/admin/tp-pe.html#pe-phase-2-developer-response

Search for `Problems caused by extreme user behaviors`

**Comment by jktang14** [comment]
Thanks Prof!
