### ISSUE TITLE
Can these be considered as  bugs?

### ISSUE THREAD

**Issue by Kitty-001** [nus-cs2103-AY2425S1/forum#647]
1. Users cannot see the content of the buttons cuz of the theme setting (background and font color is the same, can only see when hover over the buttons). More details are [here](https://github.com/AY2425S1-CS2103T-T12-4/tp/issues/258).
--------
2. For daily time preference input, overnight range is not functioning. More details are [here](https://github.com/AY2425S1-CS2103T-T12-4/tp/issues/288).

![image](https://github.com/user-attachments/assets/5cfc197a-fec6-47e6-a52e-12bac2cb71e5)
![image](https://github.com/user-attachments/assets/6fcc7ae5-e435-435a-a0cd-f8857834995f)

-------

3. Similar to point 2. More details are [here](https://github.com/AY2425S1-CS2103T-T12-4/tp/issues/272)

![image](https://github.com/user-attachments/assets/3a198f73-95dd-42c1-ae8a-760eb43b609d)
![image](https://github.com/user-attachments/assets/4ec8fbaf-3e00-4458-8d99-dfd87fed4544)

**Not sure if it is safe to fix as it touches the displaying**

Thank you!

**Comment by damithc** [comment]
> 1. Users cannot see the content of the buttons cuz of the theme setting (background and font color is the same, can only see when hover over the buttons). More details are [here](https://github.com/AY2425S1-CS2103T-T12-4/tp/issues/258).

The UI appears empty when it should show text. Can be fixed.

> 2. For daily time preference input, overnight range is not functioning. More details are [here](https://github.com/AY2425S1-CS2103T-T12-4/tp/issues/288).
> 
> ![image](https://private-user-images.githubusercontent.com/110720082/384590617-5cfc197a-fec6-47e6-a52e-12bac2cb71e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExNDM2MjEsIm5iZiI6MTczMTE0MzMyMSwicGF0aCI6Ii8xMTA3MjAwODIvMzg0NTkwNjE3LTVjZmMxOTdhLWZlYzYtNDdlNi1hNTJlLTEyYmFjMmNiNzFlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOVQwOTA4NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MmNkOTk0Y2I3Yjk0MmY2M2YzMWI4OTI2ZmUzMWRlZjM1NzM3ZGJkNjJlYTQ2NDVjM2FjMjQwMzcxYTM4YjE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jGdxbaWd-mlNeLFKldqlq9qMkwJQOc2AwmbRiXBvoUQ) ![image](https://private-user-images.githubusercontent.com/110720082/384590625-6fcc7ae5-e435-435a-a0cd-f8857834995f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExNDM2MjEsIm5iZiI6MTczMTE0MzMyMSwicGF0aCI6Ii8xMTA3MjAwODIvMzg0NTkwNjI1LTZmY2M3YWU1LWU0MzUtNDM1YS1hMGNkLWY4ODU3ODM0OTk1Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOVQwOTA4NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YTVmNzcyMGJhNGU2YWEzMDEyYTEyNDQ0ZWUyYzQxZmIwZTBiOTk0NTYxMjViYTgyZjk4NzgzZjBlMDM2ZTk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Ox7fS0y4Vx3xFeJa-hpKnqi6uIo0xSZ1ftxQFngXJXk)
> 

Seems this behaviour is intended, as per the UG screenshot. So, changing it now would be an enhancement (or fixing a feature flaw).


> 3. Similar to point 2. More details are [here](https://github.com/AY2425S1-CS2103T-T12-4/tp/issues/272)
> 
> ![image](https://private-user-images.githubusercontent.com/110720082/384590752-3a198f73-95dd-42c1-ae8a-760eb43b609d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExNDM2MjEsIm5iZiI6MTczMTE0MzMyMSwicGF0aCI6Ii8xMTA3MjAwODIvMzg0NTkwNzUyLTNhMTk4ZjczLTk1ZGQtNDJjMS1hZThhLTc2MGViNDNiNjA5ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOVQwOTA4NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Yjk3NWE0YTgwZWIwMjVlMmNjZWMzMmJjOTZkMDdlNjU1MmNhNjlkYzBkZmYyZTUwYzUxZTIwZWIxNzUyOTg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.WxVPOfQ6FZLc8qbcEfz5gRtBprmepZsNWhZD7436i6Y) ![image](https://private-user-images.githubusercontent.com/110720082/384590760-4ec8fbaf-3e00-4458-8d99-dfd87fed4544.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExNDM2MjEsIm5iZiI6MTczMTE0MzMyMSwicGF0aCI6Ii8xMTA3MjAwODIvMzg0NTkwNzYwLTRlYzhmYmFmLTNlMDAtNDQ1OC04ZDk5LWRmZDg3ZmVkNDU0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOVQwOTA4NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xODVmMDg5Yzk3ZGM1ZTVmMWJkMTdmMmM3MmMyMmY1YWRmODMxZjgxODU0YjZjNjQ1ZGMwMzM5ZmVkYjZkOGY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.aqksq6AwH-lKkzsPyNutZIGGNUELz-dUz1GLXrCehM0)
> 
> **Not sure if it is safe to fix as it touches the displaying**

Similar to above.

**Comment by Kitty-001** [comment]
Thank you prof!
