### ISSUE TITLE
Leaving early after PE

### ISSUE THREAD

**Issue by notnotmax** [nus-cs2103-AY2425S1/forum#648]
It says in the website that I can leave early if I have an exam right after the PE (which I do, at 6pm). Do I need to inform anyone before the PE or may I just leave after part 2? I am going to attend the PE in person (f2f).

![image](https://github.com/user-attachments/assets/82df3ddb-d9c8-4637-926f-01a5610be72b)

**Comment by damithc** [comment]
@notnotmax You can inform one of the invigilators at the F2F venue before leaving.
