### ISSUE TITLE
Clarification on whether the following bugs can be fixed / does not violate feature freeze

### ISSUE THREAD

**Issue by yu-sutong** [nus-cs2103-AY2425S1/forum#649]
Hi Prof, we want to check if the following proposed actions will violate the feature freeze.
1. Taken from https://github.com/AY2425S1-CS2103T-F14a-2/tp/issues/261:
Brief description of issue: tag names in sample data might be misleading and not targeting the target audience
Proposed action: change the names of the tags in our sample data

2. Taken from https://github.com/AY2425S1-CS2103T-F14a-2/tp/issues/271:
Brief description of issue: wrong error message for invalid index
Proposed action: change the handling of index
Justification: it's a bug that causes the software to misbehave (giving incorrect results)

3. Taken from https://github.com/AY2425S1-CS2103T-F14a-2/tp/issues/292:
Brief description of issue: accepting a space before a hyphen in the name
Proposed action: change the parsing of command
Justification: it's a bug that causes the program to accept unsuitable values

Thank you!

**Comment by damithc** [comment]
@yu-sutong Please elaborate the following for each case:

1. What's the current behaviour?
2. Why is it strictly 'incorrect' (and not merely 'it can be better')?
3. What's the proposed change?

**Comment by yu-sutong** [comment]
Hi Prof,

1. Currently, when the sample data is loaded, it shows tags like "friends" and "colleagues". We would like to change the names on the tags.
<img width="805" alt="Screenshot 2024-11-09 at 7 13 47 PM" src="https://github.com/user-attachments/assets/dfd294d1-af5d-4265-a27e-14c54a6a5f54">

2. Our current error message is "invalid command format" when the user puts an invalid index in the correct command format, which is incorrect. We would like to change the error message content to "invalid index".
![image](https://github.com/user-attachments/assets/43e729d0-04cc-4379-adef-a9304a048ba4)

3. We intend to modify 2 lines in the Name.java file which handles the name regex to ensure the inclusion of accepted special symbols like - is adhered to and checked for validity. We have drafted a PR here: https://github.com/AY2425S1-CS2103T-F14a-2/tp/pull/313

**Comment by damithc** [comment]
> 1. Currently, when the sample data is loaded, it shows tags like "friends" and "colleagues". We would like to change the names on the tags.

@yu-sutong The current behaviour is not strictly incorrect, but can be better. Hence, not allowed during feature freeze.


> 2\. Our current error message is "invalid command format" when the user puts an invalid index in the correct command format, which is incorrect. We would like to change the error message content to "invalid index".

In the interest of minimising code changes (which is the purpose of the feature freeze), especially in a critical area such as command handling, I suggest you mention about this current behaviour in the UG instead. However, if you have already implemented such an error message for other commands but this command got left out due to an oversight, you can fix that.


> 3\. We intend to modify 2 lines in the Name.java file which handles the name regex to ensure the inclusion of accepted special symbols like - is adhered to and checked for validity.

What's the current behaviour, and why is it 'incorrect'?

**Comment by yu-sutong** [comment]
Hi Prof, 
<img width="821" alt="Screenshot 2024-11-09 at 8 08 39 PM" src="https://github.com/user-attachments/assets/a2bcc994-36f0-40cc-bd8d-957221357108">
For 3, currently, the user can add a person called "John -Doe" but our UG says that there must be alphanumeric character before and after the symbol.

**Comment by yu-sutong** [comment]
We intend to fix it like this:
<img width="1049" alt="Screenshot 2024-11-09 at 8 13 32 PM" src="https://github.com/user-attachments/assets/cb80a2a7-0c64-46d7-8afe-91f08ed53caf">

**Comment by damithc** [comment]
You want to allow `John-Doe` but not `John -Doe`? Yes, this specific change can be allowed, if the UG already specified that behaviour as at PE-D.

**Comment by yu-sutong** [comment]
Thanks Prof!
