### ISSUE TITLE
Outdated Java version specified in tP project constraints

### ISSUE THREAD

**Issue by uniqly** [nus-cs2103-AY2425S1/forum#65]
In [Admin Info -> tP Constraints -> Constraint-Java-Version](https://nus-cs2103-ay2425s1.github.io/website/admin/tp-constraints.html#constraint-java-version), it is mentioned that:
>The software should work on a computer that has version 11 of Java i.e., no other Java version installed.

However in [Admin Info -> Programming Languages](https://nus-cs2103-ay2425s1.github.io/website/admin/programmingLanguages.html), it states that the Java 17 is used for this semester and that:
> Any incompatibilities will be considered as bugs

This means that any Java 17 specific features not found in Java 11 that is used in tP projects will cause these 'incompatibilities' that will be considered bugs.

I assume that the constraint is intended to be:
>The software should work on a computer that has version ~~11~~17 of Java i.e., no other Java version installed.

**Comment by damithc** [comment]
Good catch @uniqly 
I've updated it to 17.
