### ISSUE TITLE
Clarification on use case

### ISSUE THREAD

**Issue by yu-sutong** [nus-cs2103-AY2425S1/forum#650]
For the actors in use cases, is it compulsory to state the target audience of the application or are we allowed to let the actor be user? (just any users of the application)

**Comment by damithc** [comment]
If the actor is the same for all use cases, you can mention that in one place, rather than repeat everywhere.

**Comment by yu-sutong** [comment]
Hi Prof, can we specify the actor as "user" since there is only one actor group, which is this app's user. Or should we be more specific? Thanks!

**Comment by damithc** [comment]
Yes, that should be fine.

**Comment by yu-sutong** [comment]
Thanks Prof!
