### ISSUE TITLE
Clarification on whether fixing Sort Command would violate feature freeze.

### ISSUE THREAD

**Issue by rahula1008** [nus-cs2103-AY2425S1/forum#651]
Currently, our Sort Command has the following bug. Say you decide to sort many people by name, it will initially do the sort. However, if you then change some non-name field of a person, the order of the list will change.

Is this a bug we are allowed to fix? Thank you.

Edit:  This bug is for clients with the same name - when we change their non-name field, the order of the list among people with the same name will change.

**Comment by damithc** [comment]
@rahula1008 Is the new order (after changing a non-name field) incorrect? Or it's just the people with the same name change positions but the list still stays sorted?

**Comment by jktang14** [comment]
Hi prof @damithc, I am from the same group as @rahula1008. The new order does stay correctly sorted among people with different names. The order only becomes randomized among people with the same names.

**Comment by damithc** [comment]
@jktang14 I see. It seems the current behaviour is correct but a bit 'odd', and very rare too. So, doesn't justify risking a code change during the feature freeze.

**Comment by jktang14** [comment]
Thanks for the clarification prof
