### ISSUE TITLE
Week 11 tP progress not recorded?

### ISSUE THREAD

**Issue by LeeZeHao** [nus-cs2103-AY2425S1/forum#652]
![image](https://github.com/user-attachments/assets/2302762b-0000-4ab0-b159-5746a093b9f2)
![image](https://github.com/user-attachments/assets/0bbc56d2-ee74-426d-bad1-8b8497483002)

Hello,

Recently I noticed that even though my Week 11 tasks are listed as completed on time, my Week 11 progress is considered incomplete. 

Does this affect performance / tP grading?

Thanks in advance.

**Comment by damithc** [comment]
@LeeZeHao That column tracks commits done in each week. It's fine if you didn't commit in one week if you have committed in other weeks.

**Comment by LeeZeHao** [comment]
> @LeeZeHao That column tracks commits done in each week. It's fine if you didn't commit in one week if you have committed in other weeks.

@damithc thank you! Everything should be fine then!
