### ISSUE TITLE
Would correcting mistakes in error messages be considered violating feature freeze?

### ISSUE THREAD

**Issue by maertan** [nus-cs2103-AY2425S1/forum#653]
Hi Prof, we would like to clarify if the following changes would violate the feature freeze:

For one command, our error message is "Person has already been added", but should be "Contact has already been added", because our app uses the word "contact" rather than "person", making "person" an incorrect word. Would this be allowed? (as the initial error message is incorrect)

For another command, our intended behaviour was for success on inputting "Y", "y", "Yes" or "yes". Our current message is incorrect as it only lists "Y/Yes". We intend to update it to include the options "y" and "yes". Could I clarify if this is allowed? (as it is widening the scope)

**Comment by damithc** [comment]
> For one command, our error message is "Person has already been added", but should be "Contact has already been added", because our app uses the word "contact" rather than "person", making "person" an incorrect word. Would this be allowed? (as the initial error message is incorrect)

@maertan The current message is not strictly incorrect, unless you already have a separate entity called 'person'. So, it will be just an enhancement (i.e., making messages more consistent) and will be considered an enhancement.


> For another command, our intended behaviour was for success on inputting "Y", "y", "Yes" or "yes". Our current message is incorrect as it only lists "Y/Yes". We intend to update it to include the options "y" and "yes". Could I clarify if this is allowed? (as it is widening the scope)

Does the code already works for al for options? If yes, you can update the message to include the two missing options. But if you are updating both the behaviour and the message, it will be an enhancement.

**Comment by maertan** [comment]
@damithc Thank you Prof for your reply! For the first one, it is in the context of when a user edits a contact to have the same phone number as an existing contact. Would it thus be okay to change "Person" to "Phone number"? Question 6 of the FAQs regarding feature freeze mentions that it is okay to change outdated AB3 terms such as "person", would this fall under that category?

**Comment by damithc** [comment]
> Question 6 of the FAQs regarding feature freeze mentions that it is okay to change outdated AB3 terms such as "person", would this fall under that category?

Yes, this should be fine @maertan
