### ISSUE TITLE
Clarification on fixing UI bug during feature freeze

### ISSUE THREAD

**Issue by oneBoz** [nus-cs2103-AY2425S1/forum#656]
<img width="460" alt="Screenshot 2024-11-09 at 10 27 38 PM" src="https://github.com/user-attachments/assets/ec9ef98f-9f9e-41a4-a1c2-66c99cc40002">

May I clarify if we are allow to widen the box in order to fix this truncate bug during feature freeze, because it might cause the layout of the UI to change, or should we replace it with a picture with a "P" instead.

**Comment by damithc** [comment]
@oneBoz Does FAQ 8 in https://nus-cs2103-ay2425s1.github.io/website/schedule/week13/project.html answer your question?

**Comment by oneBoz** [comment]
So can the fix be changing it to an image instead? because currently it is not. 
Or can I adjust the alignment of the UI to fix the truncate?

We are hesitant because of this.

<img width="759" alt="Screenshot 2024-11-09 at 11 25 44 PM" src="https://github.com/user-attachments/assets/cd09009c-5933-44de-9bce-362245e99ec9">

**Comment by damithc** [comment]
@oneBoz How does your case compare with the instructions given in **Q8** specifically? I want to know which aspect of your case is not covered in Q8 so that I can focus on filling in the missing bit (and possibly update the text of Q8 to cover the missing aspect).

**Comment by oneBoz** [comment]
So in short the user will not be able to see the text in _any way_.

Currently the truncated text occurs when ID have more than 2 digits, which is a bug that was not intended and does not respond even after resizing the window on the user side as the Column width is fixed on javafx. 

However, we are not sure if the fix will violate UI enhancement during the feature freeze as it involves changing alignments/ style change. The fix to this is by resizing the UI on javafx by making it wider/ or to change the "P" to a picture instead.

**Comment by damithc** [comment]
@oneBoz If the user can't see the truncated part in any other way, it's a bug (not an enhancement). So, fixing it is allowed.
