### ISSUE TITLE
Confirm of changing rejection of valid inputs

### ISSUE THREAD

**Issue by jktang14** [nus-cs2103-AY2425S1/forum#657]
Hi prof, as mentioned in the picture below, we are able to make changes if we are rejecting valid inputs.
![image](https://github.com/user-attachments/assets/6204f4f3-49fd-4490-97ab-7a6ad691a16d)

Just as a confirmation, given that +65 12345678 is a valid phone number, but our address book currently does not allow +, we are allowed to modify the regex to allow + to be used? There does not seem to be any workaround for country codes.

**Comment by damithc** [comment]
@jktang14 If the app is expected to receive international phone numbers in typical use cases and there is no way to indicate county code, you can update the code to allow it. There is also the alternative to declare that this version supports local numbers only and support for international numbers is coming in a future versions. Which way to go depends on the expected usage of your app.

**Comment by jktang14** [comment]
Thanks prof!
