### ISSUE TITLE
Clarification of feature freeze regarding error message

### ISSUE THREAD

**Issue by Chronoxy** [nus-cs2103-AY2425S1/forum#658]
Hi Prof, I have an error message that mentioned this field can consist of symbols like `$, #, ^`. 
However, the object will not be created if the symbols are adjacent to one another for example `Bob$#`.
Since my error message initially mentioned that the field can consist of such symbols, but this error is happening, would it be violating the feature freeze if I included a line "Symbols cannot be adjacent to one another" in the error message now?

**Comment by damithc** [comment]
@Chronoxy As the current error message is misleading, yes, it can be updated.
