### ISSUE TITLE
Question on what constitutes a feature change

### ISSUE THREAD

**Issue by ignatiusoey09** [nus-cs2103-AY2425S1/forum#659]
Hi prof for our project we have specified previously that the terms Person and Contact are interchangeable

![image](https://github.com/user-attachments/assets/f87a272f-8d50-443a-b058-d61bb9ddb808)

I would like to clarify if the change to the above string is allowed? 

With reference to Q6 on the course website:
![image](https://github.com/user-attachments/assets/ff813fc1-1bdb-49fc-9864-703bc9d7c8bb)
It could be argued that
- The term has become outdated, so we updating it to be in line with the UG is allowed
- We are merely standardizing text, so it should not be allowed

Thanks in advance :)

**Comment by damithc** [comment]
@ignatiusoey09 We allowed `person` to `something else` changes for a few other teams already. So, this can be allowed.

**Comment by ignatiusoey09** [comment]
Alright thanks for taking the time to answer Prof Damith :)
