### ISSUE TITLE
Clarification on validity checks on edits to data file

### ISSUE THREAD

**Issue by SherniceSng** [nus-cs2103-AY2425S1/forum#660]
![image](https://github.com/user-attachments/assets/5adbf414-0443-42cf-9794-38806809e6d0)

Hi Prof! I would like to clarify, based on the info given, what is the bar to know when I can add extra validity checks for the data file? More specifically, will the adding of extra checks like checks for duplicates phones and emails be allowed?

**Comment by damithc** [comment]
@SherniceSng If your UG has not promised any extra (compared to AB3) support for editing the data file, there is no need to do any validity checks. Hence, adding them during the feature freeze is not allowed.

**Comment by SherniceSng** [comment]
Okay, I see! Thank you.
