### ISSUE TITLE
Changing minimum width/height of app

### ISSUE THREAD

**Issue by Gra7ityIC3** [nus-cs2103-AY2425S1/forum#661]
Hi prof, are we allowed to change the minimum width/height of the app if it becomes unusable for smaller screen resolutions like 1280x720 (e.g., part of the UI like the result display is not shown even when full screen)?

**Comment by damithc** [comment]
@Gra7ityIC3 Yes, this should be fine.

**Comment by Gra7ityIC3** [comment]
Thank you prof!
