### ISSUE TITLE
Clarification on fixing incorrect UI text during feature freeze

### ISSUE THREAD

**Issue by prave1n** [nus-cs2103-AY2425S1/forum#662]
<img width="406" alt="UI Bug" src="https://github.com/user-attachments/assets/921a665d-bfc0-4db2-a407-1e620d2d33e8">

<br />
<br />

Currently when the user adds a person with company "CompanyA", the UI displays "companyA", which is not intended. We believe that this is a UI bug as incorrect data is being displayed and since we do not plan to change the case sensitivity of the company field, are we allowed to fix this during the feature freeze?

**Comment by damithc** [comment]
@prave1n Yes, It is incorrect to change the case of the company name. You can change it.

**Comment by prave1n** [comment]
Thank you Prof!

**Comment by prave1n** [comment]
@damithc Hi Prof, I have a follow-up question on this matter to make sure our team does not violate the feature freeze.

Currently, we are converting the company input by user to lower case even before assigning it to the instance variable

<img width="875" alt="Company" src="https://github.com/user-attachments/assets/ccc719ac-d852-4234-a1cc-c05d3c9dc1ee">

In order to ensure that we display the correct text in the UI, we will not use the `normalizeCompanyname()` function in the constructor. However to maintain the definition of a duplicate supplier, we intend to modify the `equals()` function to normalise the company name before we check for equality.

<img width="410" alt="Screenshot 2024-11-10 at 2 13 35 PM" src="https://github.com/user-attachments/assets/38fe4671-9c5e-46ae-a516-4f2ff3c6fe08">


Will this be allowed?

**Comment by damithc** [comment]
@prave1n Yes, do whatever code changes necessary to achieve the required change in behaviour.

**Comment by prave1n** [comment]
@damithc Thanks Prof!
