### ISSUE TITLE
Clarification on whether displayed parameters not matching with UG count as bugs

### ISSUE THREAD

**Issue by Quasant** [nus-cs2103-AY2425S1/forum#663]
Within the UG, the advertised parameter list was:  
`add n/NAME p/PHONE_NUMBER [s/SKILL]...`  

Within the app, the displayed parameter list was:  
`add n/NAME p/PHONE [s/SKILLS]...`

Are we allowed to change the message displayed, since from FAQ Q6, the current message is incorrect?  
Also, if we inputted a invalid skill, the error message would be that `Tag only accepts alphanumeric`, can we change `Tag` to `Skill` since this is an outdated AB3 terms?

Seeking clarification because these changes could also be argued using `the current behavior is not strictly 'incorrect' but 'can be better'`.

**Comment by damithc** [comment]
> Within the UG, the advertised parameter list was: `add n/NAME p/PHONE_NUMBER [s/SKILL]...`
> 
> Within the app, the displayed parameter list was: `add n/NAME p/PHONE [s/SKILLS]...`
> 

@Quasant Yes, this can be fixed, as these are like variable names (i.e., they need to match)

> Are we allowed to change the message displayed, since from FAQ Q6, the current message is incorrect? Also, if we inputted an invalid skill, the error message would be that `Tag only accepts alphanumeric`, can we change `Tag` to `Skill` since this is an outdated AB3 terms?

Yes, as updating AB3 terms is allowed.

**Comment by Quasant** [comment]
Thank you for the prompt reply!
