### ISSUE TITLE
Clarification on stating a `response.NotInScope`

### ISSUE THREAD

**Issue by JoanneHing** [nus-cs2103-AY2425S1/forum#665]
<img width="550" alt="Screenshot 2024-11-10 at 1 59 59 AM" src="https://github.com/user-attachments/assets/1049f58b-5015-46c8-9d10-65112501fc2f">

This is an issue raised from PE-D by one of our tester. It has been labeled severity.Medium and type.FeatureFlaw

Our team has some question
Our Product is designed for Singapore local tuition centre management for primary or secondary students.

**Main Question**
Currently our team had limit the input to `Subjects` that are usually offered in tuition centres in Singapore. It is implemented using `enum`. This is to prevent user to input some invalid subjects. We do concern that this might cause some inconvenience as the field is fixed. But we had future plan for implementing these feature for subject management.
- `newSubject`: Allow user to define their own subject that offered in tuition centre
- `delSubject`: Allow user to delete a type of subject

We do not implement this feature on the current iteration as the user input is unpredictable and we can't ensure a subject added is valid. 

Hence, if we included allowing user to define their own subject and manage it in the future, can we define this issue reported as `response.NotInScope`? Based on the criteria stated below at the course website.
<img width="693" alt="Screenshot 2024-11-10 at 2 12 49 AM" src="https://github.com/user-attachments/assets/3ac5a715-baf7-4499-959b-73779df7d8ff">

**Side Question**
Another small question we would like to ask are we allow to narrow down the scope of target user now? Like restrict it to be aiming for primary tuition centre only instead of both primary and secondary. Does this violate feature freeze?

**Comment by damithc** [comment]
@JoanneHing You may narrow down the scope of your product or target market even now, provided it doesn't require code changes.
It is also fine for a product to cater for only a subset of target market at first (e.g., leave out less common usages) and plan to expand to the rest in a future version. So, it is your decision.

**Comment by JoanneHing** [comment]
narrowing down will require code changes for narrowing down the limitation check for `yearGroup` and `subject` allowed in the app. So from my understanding this is not allowed?

If narrowing down is not allowed in this case, seems like catering subset of target market would be a better work around for us.

**Comment by damithc** [comment]
@JoanneHing Code changes for the purpose of removing features is allowed but code changes for the purpose of fine-tuning/optimizing features further is not allowed.

**Comment by JoanneHing** [comment]
Alright, thank you prof for the clarification!
