### ISSUE TITLE
A bug that cannot be replicate

### ISSUE THREAD

**Issue by JoanneHing** [nus-cs2103-AY2425S1/forum#666]
There is a bug that raised by a tester stating that one of our feature is not functioning as it intended to.

Here is the issue link: https://github.com/AY2425S1-CS2103T-W11-3/tp/issues/280

At the very beginning when `tracksubject` is implemented, I had face a similar issue also, but after I restart the application, this bug cannot be replicated so we thought it might be affected by old data files. And our members tries and the same issue did not occur anymore.

But in PE-D a tester faced a similar issue, we tried to replicate it again by following the steps the tester did but we can't replicate it anymore. May I ask prof how should we deal with this? As if we can't replicate it so it is hard for us to debug where is wrong.

Should we state it in known issue?

**Comment by kaikquah** [comment]
Hi, I have commented on your issue as I was the tester that reported this. Please check it out in your issues :).

**Comment by JoanneHing** [comment]
Thank you for your update! We see where is the issue now!
