### ISSUE TITLE
Fixing a UI display bug

### ISSUE THREAD

**Issue by JoanneHing** [nus-cs2103-AY2425S1/forum#667]
Here is the issue link: https://github.com/AY2425S1-CS2103T-W11-3/tp/issues/305

User supposed to be able to select user by navigating using up and down arrow. User should be able to navigate down and see the complete `PersonCard` when they select the user. But using the down arrow, the last student is not displayed fully as the UI doesn't go to the bottom. Can this be considered as a bug and fixed?

**Comment by damithc** [comment]
@JoanneHing This can be fixed, but only if there is no acceptable workaround to view the last student (e.g., by resizing).

**Comment by JoanneHing** [comment]
Hi prof, I just tested a few time with the -jar file, I realized this bug only occur on the first use of application, resizing will not work, but after scrolling the scroll bar manually to the bottom once to view the student, the application behaves normally, even after restarting the application. Can this be mentioned in the UG for user alert?

**Comment by damithc** [comment]
@JoanneHing Yes, this can be mentioned in the UG.

**Comment by JoanneHing** [comment]
Alright! Thank you prof for the clarification!
