### ISSUE TITLE
User input exceed limitation

### ISSUE THREAD

**Issue by JoanneHing** [nus-cs2103-AY2425S1/forum#668]
Link to issue : (https://github.com/AY2425S1-CS2103T-W11-3/tp/issues/306)

This is an issue raised by one of our tester. Our current product has an auto incrementer that assign a studentID to every student added. This is similar to the `Primary_Key` assigned to a data in a database. Hence each and every studentID is unique and won't be reused, even when user is deleted.

Our product is designed for small tuition center, where maximum could handle around hundreds of student. We set the max limit of studentID to be `99999` as a small tuition center is unlikely to exceed the studentID usage, this limitation is allowing a fairly enough safe boundary for user to manage the student contacts. If this ideation of limitation is clearly stated in UG FAQ, could we negotiate on this report? Or is there a more appropriate way to work around?

Besides that, the application will fail silently when the studentID exceed `99999`, can we fix this by displaying the appropriate error message? As this is stated in course website below.
<img width="596" alt="Screenshot 2024-11-10 at 2 37 33 AM" src="https://github.com/user-attachments/assets/c70dfb17-7218-484e-9763-74d40aecd2b3">

**Comment by damithc** [comment]
The client failure can be fixed. 
The design choice to limit to 99999 has already been made and cannot be changed during the feature freeze. If this comes up during the PE, you can try to convince the tester that this is a reasonable choice for the current version, and support for a higher number can be added in a future version.

**Comment by JoanneHing** [comment]
Thank you prof for the clarification!
