### ISSUE TITLE
Fixing error display message

### ISSUE THREAD

**Issue by JoanneHing** [nus-cs2103-AY2425S1/forum#669]
<img width="783" alt="Screenshot 2024-11-10 at 2 45 29 AM" src="https://github.com/user-attachments/assets/905999b5-08ef-4bab-a444-6bf6043ec023">

This command fail because the `studentID` is in wrong format. But the error display is the error message for incorrect format for `detail` command.

But the supposed error message should be telling user that studentID format is inaccurate, we realized that the wrong error message is displayed because we accidentally throw the wrong exception when parsing studentID, the appropriate one should be the throwing `ParseException` with error message that is already provided in the `studentID` class. Can this be considered a bug and fixed around?

**Comment by damithc** [comment]
What is the 'correct' error message?

**Comment by JoanneHing** [comment]
<img width="799" alt="Screenshot 2024-11-10 at 3 01 06 AM" src="https://github.com/user-attachments/assets/c838d8ab-2f02-406d-8d22-f6cecdf06f5a">
Here is the correct error message that should be shown that is in our `StudentID` class.

**Comment by damithc** [comment]
@JoanneHing If this error message was implemented already but wasn't used as expected in this specific case, you can update the code to use it correctly.

**Comment by JoanneHing** [comment]
Thanks you prof for the clarification!
