### ISSUE TITLE
How to change a commit message ?

### ISSUE THREAD

**Issue by blackpanther9229** [nus-cs2103-AY2425S1/forum#67]
After reading week 3 content, I try to change my commit messages to follow the git convention rules. I google for the instructions, and it told me to right click the commit and choose rebase ...However, somehow it seems to create a new branch, instead of only change the commit message. Do you guys have other ways ? 

![image](https://github.com/user-attachments/assets/559000a5-f137-4b9e-a77f-55b465a7e05d)

**Comment by Feng1231** [comment]
I believe that if the commit is already pushed to the remote repo, there is no way where you can edit the commit message without changing the commit id.

Please refer to the [github documentation](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message#) for your reference.

In short, you can use `git commit --amend` for rewriting latest commit
And as week 3 material, `git rebase -i` for rewriting past commits.

Just note that these commands is essentially creating a new commit to replace the old commit that you want to replace, so it is not exactly just an edit to the commit message

Please correct me if I'm wrong.

**Comment by damithc** [comment]
@blackpanther9229 The issue of editing past commits to fit the Git convention was also mentioned during  the briefing on last Friday.
In short, it is not required (it's enough to just follow the convention for future commits) and not recommended (as it changes the commit timestamp, and interferes with our tracking of your commit timeline).

**Comment by woke02** [comment]
Hi, I found this stackoverflow post useful regarding this topic, it details other possible ways of change commit message (though not recommended in this course). 
https://stackoverflow.com/questions/179123/how-to-modify-existing-unpushed-commit-messages

**Comment by blackpanther9229** [comment]
Thank you Prof and you guys!. Now I understand.
