### ISSUE TITLE
Clarification: Would implementing a table of content leading to multiple tables of contents be considered a bug?

### ISSUE THREAD

**Issue by SeanFoongjt** [nus-cs2103-AY2425S1/forum#671]
As mentioned above, my group has decided to implement a table of content in the User Guide so that the markdown file if ever used separately from the website would still have a table of content. However, this means that there is a duplicate table of content on the website and the pdf file when saving from the website.

Would you consider this a bug? Feel free to voice your opinions, I'm curious how everyone would think about this problem.

**Comment by damithc** [comment]
@SeanFoongjt It's good to discuss this here. Ultimately, it's your team's decision, and if a PE tester reports it as a bug later, you'll need to provide your justification and try to convince the tester to agree with your view.

**Comment by damithc** [comment]
@SeanFoongjt Are you suggesting there is value in keeping two TOC's in the PDF, which is the one that will be graded? If no, perhaps find out if there is a way to disable the auto-generated ToC in the PDF?

**Comment by SeanFoongjt** [comment]
![image](https://github.com/user-attachments/assets/0923a15e-d5dc-4f3d-a713-a9a519e5fa71)
I did a bit of research and found in the documentation that there is a way to navigate around the duplicate TOC problems such that there is still one for the actual markdown file!

Thanks for the suggestion of possibly disabling the auto-generated TOC in the PDF, I did not know that was possible.
