### ISSUE TITLE
Do I need to include lengthy parameter constraints in UG that I have mentioned in the app? 

### ISSUE THREAD

**Issue by annabellekk** [nus-cs2103-AY2425S1/forum#673]
Hello, I want to ask, if I already specified the constraints for a certain field like email in the help/invalid input message in the app, do I need to specify it again in the UG? Can I say that "the user is kept informed in other ways"? I am unsure of putting the restrictions again inside the UG because it is very lengthy especially for the email field (since it has many restrictions inherited from AB3) and can cause unnecessary clutter in the UG. For other fields that are short, I can put them again in the UG. 
<img width="815" alt="Screenshot 2024-11-10 at 9 43 48 AM" src="https://github.com/user-attachments/assets/6c20e82b-4b0f-4893-8a4c-d2f50d241341">

Alternatively, would it be better to have a section with all the parameter constraints for all parameters and for every method that uses such parameters we refer the user to this section. But would this be inconvenient to the user, since they cannot find the information in the section they are looking at and have to go back and forth between sections, and thus be considered a flaw?

**Comment by damithc** [comment]
@annabellekk It's good to discuss this here. Ultimately, it's your team's decision, and if a PE tester reports it as a bug later, you'll need to provide your justification and try to convince the tester to agree with your view.
