### ISSUE TITLE
Misbehaviour of app at unreasonably large values

### ISSUE THREAD

**Issue by RezwanAhmed123** [nus-cs2103-AY2425S1/forum#675]
Our app works until the number becomes unreasonably large and the value starts misbehaving just before the integer overflow. Can we fix this bug or do we have to put it into a proposed enhancement?

![image](https://github.com/user-attachments/assets/7525aa8f-70cf-4a41-88c6-695f7cdaba49)

**Comment by damithc** [comment]
@RezwanAhmed123 How does it measure up against the following guideline?

![image](https://github.com/user-attachments/assets/95cb45e5-b907-46a0-aef4-5671e99d0bca)

If you don't expect the number to be higher than a certain value in normal usage, you can indicate an 'acceptable' range of inputs  in the UG, even if it is not enforced it in the app. The enforcing or expanding the range can be postponed to a future version.

**Comment by RezwanAhmed123** [comment]
ok prof, understood!
