### ISSUE TITLE
Question on rejecting possible valid inputs

### ISSUE THREAD

**Issue by Feng1231** [nus-cs2103-AY2425S1/forum#676]
Our application targets Singapore users and only accepts phone number of 8 digit, starting with 6,8,9. A bug report states that the digit 3 is also possible for older phone numbers, which our application rejects.

Could this be classified as 'rejecting valid input' and hence be fixed in the feature freeze?
Changes to be done to the code:
* Accept the starting digit 3
* Update error message

**Comment by damithc** [comment]
@Feng1231 Yes, you can update the code to accept those valid inputs currently rejected.

**Comment by Feng1231** [comment]
Thank you prof

**Comment by Feng1231** [comment]
@damithc 
Prof, may I clarify for updating of code, can we add new test case that specifically tests for this updated behaviour?

**Comment by damithc** [comment]
@Feng1231 There is no restriction on changing test code.

**Comment by Feng1231** [comment]
Noted, thank you prof
