### ISSUE TITLE
Renaming of application and file

### ISSUE THREAD

**Issue by SherniceSng** [nus-cs2103-AY2425S1/forum#677]
![image](https://github.com/user-attachments/assets/3e55c5e3-96c0-48f7-a5a1-af11a22d2d58)

Hi Prof, is the renaming of application allowed during feature freeze? Because, I understand that UI enhancements are not allowed, but the name of the application is not correct. So are we allowed to change it?

Also, is the renaming of json file name to match our application allowed?

**Comment by damithc** [comment]
@SherniceSng The app name in the UI can be corrected. The data file name is not so critical (as it is an internal detail and not strictly incorrect to name it `addressbook.json`) and can be postponed to a future version.

**Comment by SherniceSng** [comment]
Thank you Prof!
