### ISSUE TITLE
Issue regarding JUnit / Gradle Build dependencies

### ISSUE THREAD

**Issue by jagdeepsh** [nus-cs2103-AY2425S1/forum#68]
# JUnit / Gradle Build Dependency issue

Hi I keep on getting this same error message when trying to run JUnit:

```
error: package org.junit.jupiter.api does not exist
import org.junit.jupiter.api.Test
                            ^
```

It pops up under Build Output, I have double check my Gradle dependencies to make sure that it is using the right JUnit dependencies, it is, but not sure where to go from here.

```java
dependencies {
    testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.10.0'
    testRuntimeOnly group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.10.0'
}
```

I searched online and one suggestion was to click the reload all Gradle projects button found in the Gradle menu. That ended up turning my `@Test` annotation red, along with the following imports turning to grey and the words "Test" and "Assertions" turning red, which I am guessing those are needed but somehow removed perhaps?

```java
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class UiTest {
    @Test
```

My development environment details are as follows:
- MacOS
- SDK: Azul zulu version 17.0.11 arch64

Here is a screenshot of what I meant:
<img width="407" alt="Screenshot 2024-08-26 at 10 38 33 AM" src="https://github.com/user-attachments/assets/58e1b7c1-ed53-467a-97d9-794ebae8cfa4">

Here is a [link](https://github.com/JagdeepSinghNUS/ip/tree/branch-A-JUnit) to the branch.

The specific file that consist the errors are `UiTest.java` and `ParserTest.java`.

**Comment by damithc** [comment]
@JagdeepSinghNUS While waiting for inputs from others, here are some things you can try:

* If using Intellij, try these 'common remedies' one-at-a-time in this order:
  * Run `./gradlew clean build`
  * Choose `File` -> `Invalidate caches`
  * Close Intellij -> Delete the `.idea` folder -> Re open the project in Intellij
* Clone the fork to a different location and open the project in Intellij again to get a fresh start without losing changes you did so far.
* Push the code to a branch and share here so that other can try to replicate the problem.

**Comment by jagdeepsh** [comment]
Hi prof, I tried the first bullet point but, it did not fix the issue.

However, I think I know where I went wrong. I attempted the second bullet point and copied and pasted my Test.java code, so if I understand correctly, I think when typing the @Test annotation, and how automatically Java asks if you would like to add JUnit. I may have selected "Add JUnit 5.8.1 to class path", which I am guessing might be the cause of the issue since I am suppose to use JUnit 5.10.

However, in my clone fork, after clicking on the @Test, the only options I am given for resolving are as follows:
- Add JUnit 4 to class path
- Add JUnit 5.8.1 to class path
- Add testing to class path
- Create another test
- Change access modifier
- Try to resolve class reference

There isn't any option specifically for JUnit 5.10.0

**Comment by damithc** [comment]
> However, I think I know where I went wrong. I attempted the second bullet point and copied and pasted my Test.java code, so if I understand correctly, I think when typing the @test annotation, and how automatically Java asks if you would like to add JUnit. I may have selected "Add JUnit 5.8.1 to class path", which I am guessing might be the cause of the issue since I am suppose to use JUnit 5.10.

@JagdeepSinghNUS You should not do any 'adding' of JUnit via the Intellij interface. Adding JUnit as a dependency is already taken care of by Gradle. After updating the build.gradle, reload the dependencies and you should be good to go. If that doesn't work, you can try the bullet points I listed earlier.

**Comment by jagdeepsh** [comment]
Hi prof, noted on not adding any JUnit from IntelJ. However, the issue still persists.

Here is my [link](https://github.com/JagdeepSinghNUS/ip/tree/branch-A-JUnit) to the branch for others to replicate if possible, I have edited into the main question above too.

**Comment by Javiery3889** [comment]
Hi @JagdeepSinghNUS, I'm from your senior batch. Looking at [these lines](https://github.com/JagdeepSinghNUS/ip/blob/2574af4e548d90b3ccb49d5a206c65dd611e1cbb/build.gradle#L30-L32) in your `build.gradle` file, it appears that the `mainClass` does not match your current package name.

It might be worth checking out to see if changing the `mainClass` to your main entrypoint of your application will resolve this issue, i.e. try setting
```java
application {
    mainClass.set("jag.Jag")
}
```

Here are some references:
- https://se-education.org/guides/tutorials/gradle.html#adding-gradle-to-the-project
- https://se-education.org/guides/tutorials/junit.html

Cheers,
Javier

**Comment by RyanNgWH** [comment]
Hello, @JagdeepSinghNUS, I am a senior from a previous batch. I noticed that your test file is located under the same directory as the class file (i.e `[project root]/src/main/java/jag/UiTest.java`) instead of of a separate `test` folder (i.e `[project root]/src/test/java/jag/UiTest.java`). Notice the difference between `src/main` & `src/test`

Not sure if that is the cause of your issues but it might be worth exploring. An example can be found here https://se-education.org/guides/tutorials/junit.html

![image](https://github.com/user-attachments/assets/ce84146d-ca06-4efc-88ad-f270d4daea43)

**Comment by Anant1902** [comment]
Hi @JagdeepSinghNUS, I am a senior from your previous batch!

Moving your test files as per convention (as stated by @RyanNgWH ) should fix the issue. I cloned your [branch](https://github.com/JagdeepSinghNUS/ip/tree/branch-A-JUnit) and tested it out. It is working fine on my side (without changing any dependencies or versions, just simply running ./gradlew clean build)!

If you're still facing issues, it is likely to do with your JUnit version. Let me know if the above doesn't resolve your issue, I'll see if I can help out!

Cheers.

**Comment by jagdeepsh** [comment]
Hi guys, thanks for the help, the issue has been resolved, no longer seeing the same error as mentioned previously when running the application. Thanks :)
