### ISSUE TITLE
Clarification on using existing implementation

### ISSUE THREAD

**Issue by AgentHagu** [nus-cs2103-AY2425S1/forum#680]
Our app has 2 classes for Student and Teacher. One of the methods were duplicated in both classes, where Student had a wrong implementation while Teacher has a correct implementation. Given that our UG specified the correct behavior and an existing correct implementation exists, can we implement a fix where Student uses the method's implementation within Teacher?

![image](https://github.com/user-attachments/assets/203bbf24-8767-4656-b533-2d3bf9ebab9d)

**Comment by damithc** [comment]
@AgentHagu Yes, you may.

**Comment by AgentHagu** [comment]
Ok, thank you!
