### ISSUE TITLE
Is changing exception message that doesn't match UserGuide requirement allowed

### ISSUE THREAD

**Issue by vicelyav** [nus-cs2103-AY2425S1/forum#681]
![e59adb19-a3af-4ace-bc4b-430a1ab163cc (1)](https://github.com/user-attachments/assets/f32665c0-c240-4cbf-9bd2-73184de0d45c)

![6160940706064088617](https://github.com/user-attachments/assets/6fd74733-a568-425f-ab9d-4114c1bb9b35)

Hi, may I ask, we realised that there was a mismatch between the UG and the error message. In this, we did not state clearly in the error message that only one of the parameters is allowed for the command, and the display in the error message is a bit misleading. To quote the bug report we received: 

> From` the status message of Delete (seen when delete is entered), there are no square brackets around parameters (INDEX, n/NAME etc.). This means that the parameters are compulsory, as seen from the Features section in the UG.  However, the Delete command only accepts 1 out of the listed parameters which conflicts with the compulsory parameters explanation.

We were thinking of simply adding "or" in between the parameters. Will this be counted as an error (and not feature enhancement) and thus be allowed in this stage?

**Comment by damithc** [comment]
@vicelyav The current error message is misleading; it can be corrected.

**Comment by vicelyav** [comment]
Okay, thank you!
