### ISSUE TITLE
Inconsistent use of <<extend>> in use case diagrams

### ISSUE THREAD

**Issue by Incogdino** [nus-cs2103-AY2425S1/forum#682]
In the textbook, use case extensions are labelled with `<<extend>> `

![image](https://github.com/user-attachments/assets/34bebb72-c950-4f8e-a0e7-3290977e5907)

However, in the UML reference sheet, it uses `<<extends>>`

![image](https://github.com/user-attachments/assets/e2473393-cfaa-4925-8760-f01208a78d3b)

What would be the accepted one here?

**Comment by damithc** [comment]
Good catch @Incogdino 
It should be `<<extend>>` but for this time, we'll accept either.
