### ISSUE TITLE
Is "Succeed silently" a fixable bug?

### ISSUE THREAD

**Issue by k-hian** [nus-cs2103-AY2425S1/forum#683]
> Can we tweak UI text (i.e., error/help messages or other text shown to the user)?
> - **If a user action fails silently**, it can be fixed to inform the user of the problem.

Regarding tweaking UI text, my team has a "type anything to cancel" function. The function correctly cancels if anything is typed, but if the user types a non-command word, an `Unknown command` error is also (correctly) shown.

Therefore, this behaviour can probably be considered to "succeed silently". Currently, the message is:
```
Unknown command! 
```
but ideally, the message shown should be:
```
You have cancelled the ___ command.
Unknown command!                                      <- not strictly necessary
```

Is this a fixable bug for feature freeze?

**Comment by damithc** [comment]
@k-hian Yes, this can be fixed, as 'succeed silently' can be misleading.

**Comment by k-hian** [comment]
Thank you. I will be closing the issue.
