### ISSUE TITLE
Fixing bug for preamble ignored for one of the command that takes in parameter

### ISSUE THREAD

**Issue by Feng1231** [nus-cs2103-AY2425S1/forum#685]
In our current UG, we have specified that extra parameters will be ignored,
for all those available commands that **do not take in additional parameters** in our application. ![image](https://github.com/user-attachments/assets/b6d76b1d-ae0d-4185-a62b-c4a868dcb269)

However, we found that one of the command that does takes into parameters actually ignores the preamble text. Could this be classified as a functionality bug and be fixed, as we have stated previously in the UG that the extra parameters should be ignored only for those commands that **do not take in additional parameters**?

**Comment by damithc** [comment]
@Feng1231 What's the command, and what's the expected and actual behaviour?

**Comment by Feng1231** [comment]
It is our find command. It should be in the format of 
`find [n/KEYWORD [MORE_KEYWORDS]] [d/DAY [MORE_DAYS]]`
eg. `find n/amy ben d/monday tuesday`

When there is extra preamble text, for example
`find randomtext n/amy ben d/monday tuesday`
Expected: it should fail with an error message
Actual: it ignores the `randomtext` and function as though 
`find n/amy ben d/monday tuesday` was entered

**Comment by damithc** [comment]
Compared to commands that don't take parameters at all, a preamble in a case like this could very well be a user mistake (i.e., intended to give a parameter but mistyped it). So, it is OK to fix it i.e., change the behaviour to give an error message or a warning.

**Comment by Feng1231** [comment]
Thank you prof.
