### ISSUE TITLE
Should we include model in this diagram?

### ISSUE THREAD

**Issue by Raghava-Chittidi** [nus-cs2103-AY2425S1/forum#687]
For this diagram, we are not interacting with the Model, but the execute function takes in m, which is a model object. So, is it okay to leave the model section in the diagram even if we are not interacting with it?

<img width="838" alt="Screenshot 2024-11-10 at 3 33 06 PM" src="https://github.com/user-attachments/assets/6b5b21d7-4f0b-483d-94ef-0d69b07b8cd3">

**Comment by damithc** [comment]
@Raghava-Chittidi OK to leave it (so that it is easy to compare with other similar diagrams in the DG, and notice that this particular command does not interact with the Model) but OK to remove it too.

**Comment by Raghava-Chittidi** [comment]
Thank you!
