### ISSUE TITLE
Dealing with invalid inputs in use case extensions

### ISSUE THREAD

**Issue by Raghava-Chittidi** [nus-cs2103-AY2425S1/forum#688]
Can we combine all these extensions into 2 saying "User provides invalid inputs" and "User is missing one or more inputs"?

<img width="484" alt="Screenshot 2024-11-10 at 3 37 07 PM" src="https://github.com/user-attachments/assets/15bfd1ab-9910-4fad-85bd-f5d0779a2fc6">

**Comment by damithc** [comment]
@Raghava-Chittidi You may use such simplifications provided it doesn't introduce ambiguity or inaccuracy.

**Comment by Raghava-Chittidi** [comment]
Thank you!
