### ISSUE TITLE
Requirement of Java packages to match folder path

### ISSUE THREAD

**Issue by vinceg4** [nus-cs2103-AY2425S1/forum#69]
In the textbook, it is stated that: "Furthermore, the package of a type should match the folder path of the source file.". I am a bit confused about the wording of this sentence. What exactly does "type" refer to? It has also been used throughout the section on Java packages. I am guessing that it is referring to a Java file?

Do correct me if my understanding is wrong. How I understand and interpret the statement is as follows:
If i have a Java class/file "Abc" that belongs to the package "example.myfile", "Abc.java" must be placed in the folder path "src/example/myfile/Abc.java".

If my understanding is correct, may I ask why must this be the case? What is the purpose of needing packages' names to follow the folder path of where the file is?

**Comment by tohhengxing** [comment]
When i use the import statement to import a package, what happens?

**Comment by damithc** [comment]
> If my understanding is correct, may I ask why must this be the case? What is the purpose of needing packages' names to follow the folder path of where the file is?

@vinceg4 The short answer is "because Java says so". Nevertheless, it is a good point to wonder about and discuss possible reasons for this requirement.

**Comment by Feng1231** [comment]
Referring to oracle's documentation on [managing files](https://docs.oracle.com/javase/tutorial/java/package/managingfiles.html):

> Many implementations of the Java platform rely on hierarchical file systems to manage source and class files, although The Java Language Specification does not require this. 

So I believe it is a common convention that is followed by most java platforms, that you should match example.myFile.Abc to the file path `./example/myFile/Abc.java`. The main point here is `Many implementations of the Java platform rely on hierarchical file systems to manage source and class files`, so I guess thats the purpose of needing packages' names to follow the folder path of where the file is.

I might be wrong, but one of the reason could be, when compiler sees
```
// Abc.java file
package example.myFile;
```
, it creates a corresponding Abc.class file at 
`{outputPath}/example/myFile/Abc.class`

Assuming this is the default behaviour of the compiler, it seems logical to me why packages name should follow the folder path, so to match the java filepaths and the class filepaths.
