### ISSUE TITLE
Are we allowed to include user stories that we did not implement?

### ISSUE THREAD

**Issue by Feng1231** [nus-cs2103-AY2425S1/forum#691]
This was in one of the section for the course website, in week 7.
![image](https://github.com/user-attachments/assets/1c5623b3-fe77-4f9f-9ac2-a31663b0c938)

Upon seeing this, my team thought it was okay to include features that we did not implement in v1.5 (and even in v1.6) in the DG  user stories. Specifically, we included these user stories, even though we did not implement it (we might not even add it in the future enhancements section for v1.6).
![image](https://github.com/user-attachments/assets/161e52d1-f913-453b-a098-596b03e8d142)

However, it was flagged out as a bug by one of the tester, stating that we are including user stories that is not supported by the current iteration of the application, so our team is a bit confused now.

May I ask whether we could keep the user stories as it is?

**Comment by damithc** [comment]
@Feng1231 In an ongoing project like this, it is expected that some requirements may not be implemented yet. So, it is not a bug to have requirements not implemented yet.

**Comment by Feng1231** [comment]
@damithc May I confirm that keeping it is fine even if we do not add the features that tackle those requirements in the future enhancements for DG?

**Comment by damithc** [comment]
> @damithc May I confirm that keeping it is fine even if we do not add the features that tackle those requirements in the future enhancements for DG?

Yes, not just fine, but that is expected. See https://nus-cs2103-ay2425s1.github.io/website/admin/tp-deliverables.html#deliverable-developer-guide-dg

<img width="822" alt="image" src="https://github.com/user-attachments/assets/b1f0ce5d-75ec-429a-8aca-09844bcae20b">

**Comment by Feng1231** [comment]
I see, thank you prof!
