### ISSUE TITLE
Clarification on UI message changes

### ISSUE THREAD

**Issue by AgentHagu** [nus-cs2103-AY2425S1/forum#692]
AB3's original email validation message did not mention that consecutive "." are not allowed in the local part, despite having a test case to check against that. Are we allowed to add onto the validation message that consecutive "." are not allowed? I think this falls under **If a user action fails  silently** and **Widening the scope of a message** but I'd just like to clarify

![image](https://github.com/user-attachments/assets/a90d4c83-e77f-4496-a473-80e61ca0477d)

**Comment by damithc** [comment]
@AgentHagu Yes, you can add that.

**Comment by AgentHagu** [comment]
Ok, thank you prof!
