### ISSUE TITLE
Clarification on whether we allowed to fix Filter command during Feature Freeze

### ISSUE THREAD

**Issue by yastsc** [nus-cs2103-AY2425S1/forum#696]
When we filter with a job no one has,
![image](https://github.com/user-attachments/assets/d5bf66b4-cfb8-479a-93ca-70c790a77845)
Then, run any command for a person that already exists in the address book, just not in the filtered list like ta n/Jeremy Ng t/terry & soon hian (ensuring Jeremy Ng is in the addressbook)
![image](https://github.com/user-attachments/assets/8a6da649-a7f4-4547-89c5-c063d1170c3f)
we run into this issue, which is incorrect as the person does exist, just not in the currently shown list.

Are we allowed to fix it?

**Comment by damithc** [comment]
Yes, as this behaviour is incorrect, you can fix it.

**Comment by yastsc** [comment]
Thank you!
