### ISSUE TITLE
Clarification on changing command usage message

### ISSUE THREAD

**Issue by IsaacPangTH** [nus-cs2103-AY2425S1/forum#697]
As our delete command allows multiple indices to be specified, there was a bug resulting from the same index being used multiple times in the command. As such, we added a check for this and changed the command usage message accordingly as shown in the image below.
![image](https://github.com/user-attachments/assets/4ef06f07-4f68-49e4-8afa-5504386093e5)
Would this be considered widening the scope of an error message, and thus be allowed, as the command usage message implicitly tells the user what the error might be caused by?

For reference, I have attached a screenshot of the full error message below.
![image](https://github.com/user-attachments/assets/ca0c607f-7bbe-4d52-bd38-6e812baf1573)

**Comment by damithc** [comment]
@IsaacPangTH What happens if the same index is used multiple times in the delete command?

**Comment by IsaacPangTH** [comment]
@damithc It fails silently without any success or error message.

**Comment by damithc** [comment]
@IsaacPangTH failing silently is considered a bug, and is allowed to fix during the feature freeze. The parameter description can be updated as well.
