### ISSUE TITLE
Are we allowed to update result messages in the event that a command was implemented incorrectly

### ISSUE THREAD

**Issue by ghos7ie** [nus-cs2103-AY2425S1/forum#698]
Similar to #632, my group's implementation of sorting is not entirely correct.

Can we update the result message to state that the sort is done by ASCII order? Since the behvaiour is not entirely incorrect so we cannot fix the code.

**Comment by damithc** [comment]
@ghos7ie You can update the UG to mention this behaviour. State it prominently so that all users get to know about it the first time they use the sort command.

**Comment by ghos7ie** [comment]
alright, thanks 👍🏻  @damithc
