### ISSUE TITLE
Is it fine if we just acknowledge a bug as known issue if fixing the bug requires would break feature freeze.

### ISSUE THREAD

**Issue by uniqly** [nus-cs2103-AY2425S1/forum#699]
For instance, a bug was spotted with clearly unintended behaviour (eg: unexpected output when command takes in unrecognized parameters when clearly the app should return an error message) but the intended behaviour is not specified in UG (eg: UG only says that the command should take xxx parameters but does not say it should not recieve extra parameters). Would fixing it break feature freeze? If not, would it be sufficient just to mention it as known issue as basis for classifying its severity as `response.notInScope`?

**Comment by damithc** [comment]
@uniqly Give more specifics: 
What does the UG say?
What is the current behaviour?
What is the ideal behaviour?

If you don't want to share here, you can send to the course email instead.

**Comment by uniqly** [comment]
@damithc 

I'm referring to these two issues brought up by one of our testers:
* https://github.com/AY2425S1-CS2103T-T09-1/tp/issues/245
* https://github.com/AY2425S1-CS2103T-T09-1/tp/issues/241

Our UG, just mentions that the command has the following parameters, but does not say anything about not including unrecognized parameters. Currently, depending on where you put the extra parameters you get different behaviours. The ideal behaviour would to be to reject these extra parameters or to ignore them.

![image](https://github.com/user-attachments/assets/c48601bc-a6af-4578-815d-9a629b7f6c52)

My team's current solution is just to add a note in our UG that users should follow the command format strictly.

**Comment by damithc** [comment]
@uniqly If the extra parameters are silently ignored, you can update the UG to inform user about it. But if the extra parameters can cause the application to misbehave, like in the case of 241, you can rectify that behaviour. Alternatively, you can also just caution users about this behaviour in the UG.
