### ISSUE TITLE
Commit Messages Checking & Does level order matter?

### ISSUE THREAD

**Issue by sheenkerr** [nus-cs2103-AY2425S1/forum#7]
Hi, 

1) Is there any way for us to know if the commit messages we have typed are sufficient and acceptable? Should we contact our TAs to check or can we only ask our TAs during tutorial.

2) Can we skip between levels, for example can I code and push `Level-5` before `A-TextUiTesting` or must we strictly code in the level order sequentially as shown in the website?

![image](https://github.com/user-attachments/assets/7407df79-883c-47d9-9433-37af08013420)

Thank you!

**Comment by RezwanAhmed123** [comment]
For number 1: I think you can refer to the website they have specified in the standards/conventions page of the website. This is the [link](https://se-education.org/guides/conventions/git.html).

For number 2, I’m not too sure but from the website they did say you can just put a few levels together so I think it should be fine if it’s not in order? However, it would be pretty weird if ur level 1 is 3 commits ahead of ur level 3, so i think as long as its not to that extent it should be fine.

**Comment by sheenkerr** [comment]
Thank you, I have seen this link, but I was just afraid that my commit messages are not sufficient.

**Comment by damithc** [comment]
Thanks for raising these questions @sheenkerr, and for the inputs @RezwanAhmed123 

> * Is there any way for us to know if the commit messages we have typed are sufficient and acceptable? Should we contact our TAs to check or can we only ask our TAs during tutorial.

At this time, you are not _required_ to follow any commit message format. So, you may write it in anyway you want. The commit message standard will become a requirement only at a later point of the iP. But you are welcome to follow it from the start too.

> * Can we skip between levels, for example can I code and push `Level-5` before `A-TextUiTesting` or must we strictly code in the level order sequentially as shown in the website?

Try to follow the given increment order, and do one increment at a time. But we don't penalize if you deviate from that a bit here and there by accident.

**Comment by sheenkerr** [comment]
Thank you for the clarification prof!
