### ISSUE TITLE
JUnit Tests

### ISSUE THREAD

**Issue by beginner-web-developer** [nus-cs2103-AY2425S1/forum#70]
In the examples in the notes, JUnit tests test usingthe "assertEquals()" function, so I am assuming this only applies to functions that return a value. How then should I go about writing JUnit tests for functions that return void?

**Comment by damithc** [comment]
Good point for discussion @beginner-web-developer 
Let's wait to see what others think

**Comment by Incogdino** [comment]
If the function call has side effects like changing the state of another component, we can check if the changed state is equal to our expected outcome.

For instance if you are testing a class and you have a function that changes one of the fields, you can check if the value of the field after calling the function matches the expected value. 

You can also refer to this answer [here](https://stackoverflow.com/a/16043927/16322247) for more.

**Comment by beginner-web-developer** [comment]
hmm this makes sense! thanks @Incogdino
