### ISSUE TITLE
Adding checks for null under feature freeze

### ISSUE THREAD

**Issue by jan-kai1** [nus-cs2103-AY2425S1/forum#700]
In the PE-D one of our user inputs which allowed an empty input caused a bug due to a nullpointer exception. Would it be allowed to add a null check to all fields including mandatory ones (which have not caused bugs yet) to improve code quality and implement defensive coding while under the feature freeze?

**Comment by damithc** [comment]
@jan-kai1 Adding assertions is allowed (as a form of code quality improvements) but adding more exceptions that can alter the user-visible behaviour is not normally allowed (as they are considered refinement to the error handling). 
But for specific cases where an input causes the application to cause a NPE and misbehave, you can treat them as bugs and fix them.
