### ISSUE TITLE
Bug in the PE-readiness quiz options

### ISSUE THREAD

**Issue by matthewyip1511** [nus-cs2103-AY2425S1/forum#701]
![image](https://github.com/user-attachments/assets/3904f40c-58e0-437e-ac9e-0a63a237a428)

Hi Prof, I'm not sure if this is a bug here but the options state to choose `confirm I am running Java 11` while also simultaneously stating that you should be running `Java 17` (which I believe is the right version to use). Thanks!

**Comment by damithc** [comment]
@matthewyip1511 Thanks for the bug report. I updated it earlier but apparently, Canvas lost it. I updated it again just now. But the updated text will not show up if you have started the quiz already.
