### ISSUE TITLE
Is refactoring code to reduce duplicate and allow reuse which is considered as code quality allowed?

### ISSUE THREAD

**Issue by SeeYangZhi** [nus-cs2103-AY2425S1/forum#702]
<img width="953" alt="Screenshot 2024-11-10 at 8 17 19 PM" src="https://github.com/user-attachments/assets/8e165852-6d9d-4885-8552-fb1a2421615d">

We intend to refactor `categories` used in transactions and `tags` used in the address book which category is based on tag and therefore has a lot of code that can be refactored to a common package for reuse. Would this be allowed? @damithc 

<img width="753" alt="Screenshot 2024-11-10 at 8 20 08 PM" src="https://github.com/user-attachments/assets/e471104e-bcb6-43e6-9d6d-c100d03bd5ee">
<img width="720" alt="Screenshot 2024-11-10 at 8 20 19 PM" src="https://github.com/user-attachments/assets/f6b54fc3-e632-44b4-9783-0e3aa205746c">

**Comment by damithc** [comment]
@SeeYangZhi While allowed, try to minimise drastic code changes as the whole point of the feature freeze is to minimise the risk from changes to the functional code. The kind of refactoring you mentioned seems like an unnecessary risk, and will mess up code authorship tracking as well (which you can still fix by using `@@author` tags -- more info [here](https://nus-cs2103-ay2425s1.github.io/website/admin/tools.html#tool-reposense-for-authorship-tracking))

**Comment by SeeYangZhi** [comment]
Okay thank you, Prof!
