### ISSUE TITLE
Clarification on rejecting valid input

### ISSUE THREAD

**Issue by rollingpencil** [nus-cs2103-AY2425S1/forum#703]
Currently, our parser for a prefix Amount rejects the input for `.01`, which can be considered as a valid input, and our constraint message "Amount should only contain digits up to 2 decimal points delimited by . and prefixed with - for negative amounts" seems to match. Would we be able to fix the validation for it?

**Comment by damithc** [comment]
@rollingpencil Yes, if this is a valid input and is currently rejected.

**Comment by rollingpencil** [comment]
Thank you prof!
