### ISSUE TITLE
Fixing Bugs that were not caught by Testers

### ISSUE THREAD

**Issue by C5hives** [nus-cs2103-AY2425S1/forum#704]
After the PE Dry Run, my team found an additional bug while addressing the bugs brought up by the other testers.

This new bug was not mentioned by any of the testers. If that's the case, are we allowed to fix this bug for `v1.6`?

**Comment by damithc** [comment]
@C5hives You may fix bugs found by PE-D testers as well as bugs found by yourselves. But all v1.6 work is subject to the feature freeze, irrespective of who found the bug.

**Comment by C5hives** [comment]
Noted with thanks prof! Will close this issue.
