### ISSUE TITLE
Clarification on whether the following bug violates feature freeze

### ISSUE THREAD

**Issue by CJianzhi** [nus-cs2103-AY2425S1/forum#705]
Our implementation of a command with the format :`upcoming aft/START_DATE bef/END_DATE` specified in the user guide submitted for PE-D allows users to enter a START_DATE that is later than an END_DATE and does not show any error message. In this case would it be considered incorrect behaviour and allowed to be fixed?

Example: the user intends to search for a delivery between 19-02-2023 08:00 and 19-02-2024 08:00. However, the user may accidentally input upcoming aft/19-02-2024 08:00 bef/19-02-2023 08:00 and get the wrong results 

[Link to bug report for reference]https://github.com/AY2425S1-CS2103T-W14-1/tp/issues/327

**Comment by damithc** [comment]
@CJianzhi What does the UG say about this feature?
If the user gives a start date later than the end date, what is the actual behaviour?

**Comment by CJianzhi** [comment]
The User guide uploaded for PE-D states that "The upcoming command is used to view pending deliveries in VendorVault. You can choose to view all pending deliveries within a specified date range or before or after a given date."

The actual behaviour would be "0 deliveries found!"

**Comment by damithc** [comment]
I see. The current behaviour is not strictly incorrect, but can be better. You can update the UG to notify users of this behaviour, and leave a better implementation to a future version, or list under planned enhancements.

**Comment by CJianzhi** [comment]
okay thank you prof for the clarification!
