### ISSUE TITLE
Clarification for violation of feature freeze

### ISSUE THREAD

**Issue by xqtann** [nus-cs2103-AY2425S1/forum#706]
Are we allowed to change the example usage in an error message shown to user, if it includes a example usage that is wrong?
Error message: 
<img width="857" alt="image" src="https://github.com/user-attachments/assets/a58f0fcf-2a07-494f-8c8d-1d0b13524762">
However, we limited the number of characters in a tag to 9 characters. The example usage shows a tag with more than 9 characters.

Also, will adding the words "with spaces" be a violation of feature freeze?
![image](https://github.com/user-attachments/assets/cdc08ec1-1f97-409a-b8e5-c7c4722e72ca)

**Comment by damithc** [comment]
@xqtann If the current example wouldn't actually work, you can change it to an example that works.

If tags already supports spaces, you can add 'with spaces' to the message.

**Comment by xqtann** [comment]
Thank you prof!
