### ISSUE TITLE
Clarification for Error Message Update during Feature Freeze

### ISSUE THREAD

**Issue by yiiilonggg** [nus-cs2103-AY2425S1/forum#707]
Our group has a command, `renameTag` with the format `renameTag ot/OLD_TAG nt/NEW_TAG`, that aims to rename all tags with `OLD_TAG` to `NEW_TAG`.

One of our PE-D testers found an [issue](https://github.com/AY2425S1-CS2103T-W12-1/tp/issues/218) with our error messages where
* If both `OLD_TAG` and `NEW_TAG` are empty strings (or just whitespaces), then a `Tags should be alphanumeric` error message is shown
* If both `OLD_TAG` is an empty string (or just whitespaces) but `NEW_TAG` is valid, then a `Tag is not found` error message is shown

We agree that the error messages should be consistent. Are we allowed to change the error message in both cases to be `Tags should be alphanumeric and not empty`? We are unsure about how to change the error message without violating the feature freeze (under tweaking UI text, widening the scope of the error message).

**Comment by damithc** [comment]
@yiiilonggg Given this is just a cosmetic issue (i.e., the error messages are not incorrect), the change is not allowed.  You can list it under _Planned Enhancements_. Alternatively, if it is reported in the PE, you can argue for `NotInScope`, given its relatively low impact.

**Comment by yiiilonggg** [comment]
thank you prof for your reply, but this does lead me to another question which I will open a new issue for.
