### ISSUE TITLE
get file contents to persist between runs

### ISSUE THREAD

**Issue by meatyturtle** [nus-cs2103-AY2425S1/forum#71]
hi everyone, im having trouble with level 7, more specifically "Load the data from the hard disk when the chatbot starts up." because whatever i write to the file doesn't persist when i run the program again. i'm using java.io.FileWriter to read and write to files:

 ```
FileWriter writer = new FileWriter("data/sigma.txt");
        try {
            File file = new File("data/sigma.txt");
            if (file.createNewFile()) {
                System.out.println("New file created: " + file.getName());
            } else {
                System.out.println("File already exists.");
                // open the file
                for (String line: Files.readAllLines(Paths.get("data/sigma.txt"))) {
                    System.out.println(line + "\n");
                }
            }
        } catch (IOException e) {
            System.out.println("error occurred creating file");
        }

// handle todo task
// ...
 items.add(task);
 try {
    writer.write(task + "\n");
    writer.flush(); 
} catch (IOException exception) {
     System.err.println("an error occurred writing to file" + exception.getMessage());
}

// close program
            if (userInput.contains("bye")) {
                System.out.println("bye");
                writer.flush();
                writer.close();
                break;
            }
```

it always prints out "File already exists" but the file will be empty on every run. anyone has any luck trying to get the contents to persist? or should i use a different class to write to files

sorry for terrible formatting

**Comment by Incogdino** [comment]
The issue most likely arose when you initialised `FileWriter` at the start with override. 

If you are not using `FileWriter(String path, boolean append)`, `FileWriter` will open the file in override mode and thus wipe out all existing data. 

In this case, I guess you have two options
1. Initialize `FileWriter` with the additional boolean argument, `FileWriter(String path, boolean append)`
2. Initialize `FileWriter` when the program is exiting with `FileWriter(String path)`

Hope this solves your issue :)

**Comment by meatyturtle** [comment]
thank you @Incogdino, this helped!!
