### ISSUE TITLE
Changing wrong error message displayed

### ISSUE THREAD

**Issue by jan-kai1** [nus-cs2103-AY2425S1/forum#711]
For our app, there is an issue where if an invalid index for a person is used e.g. greater than list size, it will just state contact was not found, instead of invalid index. The FAQ for error messages mentioned in the feature freeze that it is not allowed to change the error message to a more detailed one, but in this case the error message is not entirely accurate.

Would it violate the feature freeze to change the error message to the correct one?

**Comment by damithc** [comment]
@jan-kai1 In this case we allow expanding the scope of the error message as `Contact not found OR ..` so that it covers both possibilities.
