### ISSUE TITLE
Clarification on Incorrect Error Message

### ISSUE THREAD

**Issue by yiiilonggg** [nus-cs2103-AY2425S1/forum#712]
Our group has a `schedule` command, with the relevant parameter for this question being the schedule date, `sd/SCHEDULE_DATE`.

One of our PE-D testers found this [issue](https://github.com/AY2425S1-CS2103T-W12-1/tp/issues/224)
* When the user passes in a date of the incorrect format, it shows a `Date field must be given in the format yyyy-MM-dd.` error message.
* However, when the user passes in an invalid date in the correct format, it shows the same error message.

In this case, could I confirm we are allowed to update the error message since the error message is incorrect? And if we were to update the error message, it should follow the `widening the scope` guideline (e.g. `Date field must be given in the format yyyy-MM-dd and must be a valid date`)

**Comment by damithc** [comment]
@yiiilonggg Yes, in this case you may widen the scope of the error message.

**Comment by yiiilonggg** [comment]
thank you prof!
