### ISSUE TITLE
Can UI extending error be fixed?

### ISSUE THREAD

**Issue by Droas590** [nus-cs2103-AY2425S1/forum#714]
![image](https://github.com/user-attachments/assets/2c4fe968-93c5-43cc-862f-a0f538143732)
When extended vertically, our app will have white space below, are we allowed to fix this bug.

**Comment by damithc** [comment]
@Droas590 This seems serious enough to consider an 'error' in the UI. Allowed to fix.

**Comment by Droas590** [comment]
ok, thank you prof!
