### ISSUE TITLE
Are we supposed to cite info from Developer Guide for code reuse?

### ISSUE THREAD

**Issue by MAOXIONGKAI** [nus-cs2103-AY2425S1/forum#715]
Hi Prof! Our team has implemented undo/redo feature for our application based on the idea in the proposed feature section of the original AB3 Developer Guide, in this case are we supposed to credit this source for code reuse? Because I am somehow confused by this section of the code reuse policy.

<img src="https://github.com/user-attachments/assets/7f9d301e-460e-4da2-b53d-782772a25774" width = "60%" alt="Screenshot of code reuse policy">

As I am not sure whether our case can be considered as **Reusing from course material**.
Thank you.

**Comment by damithc** [comment]
@MAOXIONGKAI You can credit AB3 for the design of this feature.

**Comment by MAOXIONGKAI** [comment]
> @MAOXIONGKAI You can credit AB3 for the design of this feature.

Hi prof @damithc , just for a double check, is this crediting optional or compulsory? Because the course website says crediting of AB3 is welcomed but not compulsory. Thank you!

**Comment by damithc** [comment]
@MAOXIONGKAI This one is a special case as you took a proposed idea in AB3 and implemented it (not simply reused code). So, best to cite it, as the reviewers need to know that while the implementation is yours, the idea came from AB3.

**Comment by MAOXIONGKAI** [comment]
Thank you prof!
