### ISSUE TITLE
Can I fix a GUI issue like this(truncated text that makes app unusable if one of the field is given very long input)

### ISSUE THREAD

**Issue by MAOXIONGKAI** [nus-cs2103-AY2425S1/forum#716]
Hi, prof. I have seen issue like #714 but I just want to clarify in our own case.

Currently, our app can wrap text of most of the fields in our contact's person card, like below
<img src="https://github.com/user-attachments/assets/fff42013-7696-4ac6-b77c-734b6f30765b" width="50%" alt="screenshot of normal wrapped text for long inputs without tag field"/>

However, if a very long input is supplied to create a tag for a contact, the GUI becomes like this, where all the text are no longer wrapped.
<img src="https://github.com/user-attachments/assets/f8cca400-22d2-4383-862b-c7efca2c2416" width="50%" alt="screenshot of problematic person card due to presence of long tag"/>
(As you can see, the whole person card initially is expanded very long because the text are wrapped properly, but now it shrinks to normal height because the words becomes truncated after a long tag is created.)

In this case, is this considered as a serious bug and can be fixed in v1.6? Thank you prof!

**Comment by damithc** [comment]
@MAOXIONGKAI As per Q8 in https://nus-cs2103-ay2425s1.github.io/website/schedule/week13/project.html fixing this is not allowed, as this is not 'normal' usage.

**Comment by MAOXIONGKAI** [comment]
Thank you prof!
