### ISSUE TITLE
Does improving code quality and thus affect the code considered a violation of feature freeze? 

### ISSUE THREAD

**Issue by annabellekk** [nus-cs2103-AY2425S1/forum#717]
For instance, my error message contains the maximum number of characters accepted for a parameter. If I extract out the number into a variable to improve my code quality, and thus need to change the error message to use the variable instead of the typed out number in a string, does this violate the feature freeze?

**Comment by damithc** [comment]
@annabellekk Refactoring (by definition, refactoring does not affect external behaviour) is allowed. But do at your own risk, as refactoring has the risk of regressions, which is what we are trying to minimise by enforcing a feature freeze.

**Comment by annabellekk** [comment]
Ok, thank you Prof!
