### ISSUE TITLE
Can you change the command word now?

### ISSUE THREAD

**Issue by ishan-agarwal-05** [nus-cs2103-AY2425S1/forum#718]
I have a feature flaw bug in ped that says that i should reduce the length of the command word. Can i do that now after the feature freeze or is it not allowed?

Example change command word from `listattendance` to `listattn`

Another is to change the command word to be more consistent with other commands 
Eg - from `createattn` to `createevent` because the related commands are `listevents` and `deleteevent`

**Comment by damithc** [comment]
@ishan-agarwal-05 This is a feature flaw, and they are not allowed to fix during the feature freeze. See Q1 in https://nus-cs2103-ay2425s1.github.io/website/schedule/week13/project.html for more details.
