### ISSUE TITLE
Clarification on updating the UI

### ISSUE THREAD

**Issue by Ponharish** [nus-cs2103-AY2425S1/forum#720]
In our PE-D, my team received a bug in which if someone executes the `find` command and executes another command (one of those newly added commands) following the find command, the UI is not refreshed and displays the same person returned by the `find` command. Although this gets resolved when the user executes the `list` command, there is an inconsistency in our application since it works perfectly for some commands. The reason for this is due to the fact that the model was not updated upon executing those few commands. This deviates from our advertised behavior.
So would fixing this be considered a violation of the feature freeze?

**Comment by damithc** [comment]
@Ponharish you can fix this only for cases that results in the UI showing incorrect data (e.g., shows an item that doesn't exist, or shows the wrong attribute value). If that is not the case, mention this limitation in the UG and list it under _Planned Enhancements_.

**Comment by Ponharish** [comment]
Thank you Prof
