### ISSUE TITLE
Clarification on widening scope of message

### ISSUE THREAD

**Issue by AgentHagu** [nus-cs2103-AY2425S1/forum#721]
Our app currently has a bug where it gives an incorrect/inaccurate error message, such as displaying "This student already exists in the address book" when in reality it's a teacher.

Are we allowed to widen the scope of this error message by instead displaying "This _person_ already exists in the address book"?

**Comment by damithc** [comment]
@AgentHagu Yes, that can be allowed.

**Comment by AgentHagu** [comment]
Ok, thank you prof!
