### ISSUE TITLE
Clarification on what is allowed in feature freeze

### ISSUE THREAD

**Issue by AgentHagu** [nus-cs2103-AY2425S1/forum#722]
Our app's sort command is currently case-sensitive. However, in the UG we submitted for PE-D, we specified that sort is case-insensitive. Is this considered as a bug that we can fix during the feature-freeze since our tP has "incorrect behavior" according to the UG?

Also, just to confirm: Are we allowed to fix bugs due to integer overflow?

**Comment by damithc** [comment]
@AgentHagu 

> Our app's sort command is currently case-sensitive. However, in the UG we submitted for PE-D, we specified that sort is case-insensitive. Is this considered as a bug that we can fix during the feature-freeze since our tP has "incorrect behavior" according to the UG?

You can refer to Q7 in https://nus-cs2103-ay2425s1.github.io/website/schedule/week13/project.html

> Also, just to confirm: Are we allowed to fix bugs due to integer overflow?

You can refer to Q8 for this.

**Comment by AgentHagu** [comment]
Ok, thank you prof!
