### ISSUE TITLE
Can we clarify the error message?

### ISSUE THREAD

**Issue by lithops-zty** [nus-cs2103-AY2425S1/forum#723]
Hi Prof!
Our product displays `Index is not a non-zero unsigned integer!` when the actual problem is due to the presence of a stray prefix.
Can we chage the message to `Index '1 z/' is not a non-zero unsigned integer!`?

![image](https://github.com/user-attachments/assets/c987ee36-5e7b-46c0-accd-6dd698a2993b)

**Comment by damithc** [comment]
@lithops-zty Yes, go ahead.

**Comment by lithops-zty** [comment]
@damithc Thank you Prof!
