### ISSUE TITLE
Clarification on existing implementation

### ISSUE THREAD

**Issue by AgentHagu** [nus-cs2103-AY2425S1/forum#724]
Our app has a Student and Teacher command which adds the respective contact into the address book. They have their own Parser classes.

There is currently an issue with one of the Parser classes where duplicate prefixes are not accounted for but the other does check for it. Are we allowed to fix this bug? i.e. add the check for duplicate prefixes? We did not mention what is the expected behavior with duplicated prefixes in our UG

**Comment by damithc** [comment]
@AgentHagu As you have already implemented the said functionality in one place, we can allow it to be added to the other place.

**Comment by AgentHagu** [comment]
Ok, thank you prof!
