### ISSUE TITLE
Is there an error in the explaination for PE readiness quiz?

### ISSUE THREAD

**Issue by Feng1231** [nus-cs2103-AY2425S1/forum#725]
Hi, I do not understand what this explanation is trying to say.
![image](https://github.com/user-attachments/assets/53b97097-f082-45ea-9a3f-a2d288ee06d1)
Is there some phrasing error here or am I just not getting the idea? 😓 

There is also extra characters for Q25's explanation.
`&amp;nbsp;`

**Comment by damithc** [comment]
> Hi, I do not understand what this explanation is trying to say.
> ![image](https://private-user-images.githubusercontent.com/128298170/384863242-53b97097-f082-45ea-9a3f-a2d288ee06d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMjM2OTgsIm5iZiI6MTczMTMyMzM5OCwicGF0aCI6Ii8xMjgyOTgxNzAvMzg0ODYzMjQyLTUzYjk3MDk3LWYwODItNDVlYS05YTNmLWEyZDI4OGVlMDZkMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMVQxMTA5NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YWI3OTZlNDdiMjVhMDExOTFiMzJlYmMzY2NiYzhhMTEyMTNlZmQ3ZDRlYzRmODhiZGIyOGJkYmY4YzViOGZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.yc1oVofPaAbzEuOCUsynRkimY7bJmlOfBzU7FZcHi3Y)
> Is there some phrasing error here or am I just not getting the idea? 😓

Added this missing word.
![image](https://github.com/user-attachments/assets/6ec55211-bece-4dd2-a903-7af560d5928c)



> There is also extra characters for Q25's explanation.
> `&amp;nbsp;`

Thanks for reporting this. Fixed.
