### ISSUE TITLE
Are we allow to fix this feature bug?

### ISSUE THREAD

**Issue by Droas590** [nus-cs2103-AY2425S1/forum#726]
We are having this feature that can suggest user the rest of the command, and there is a bug when there the command is long. 
![image](https://github.com/user-attachments/assets/ce1880e2-1641-417f-978a-bbb33d47c984)
We think this is quite a serious issue as it disrupts users view and there is no workaround for the user.
Are we allow to fix this bug?

**Comment by damithc** [comment]
@Droas590 Yes, can be fixed.

**Comment by Droas590** [comment]
alright, thank you prof!
