### ISSUE TITLE
Developer Guide Mentions of AddressBook

### ISSUE THREAD

**Issue by arjun2598** [nus-cs2103-AY2425S1/forum#727]
For the developer guide, when underlying classes like AddressBookParser are mentioned, is it considered a bug since there is still reference to AddressBook? Or is renaming the classes only in the Developer Guide allowed? Meaning, if my team's product is called XYZ, renaming the class to XYZParser rather than leaving it as AddressBookParser in the Developer Guide but the code still uses the class AddressBookParser.

**Comment by damithc** [comment]
@arjun2598 

OK to keep AddressBook term for internal classes, as the app is supposed to be an address book variant.
But DG not matching the code can be flagged as a bug.

**Comment by arjun2598** [comment]
Ok thank you for the clarification prof!
