### ISSUE TITLE
Can this error message be fixed?

### ISSUE THREAD

**Issue by Raghava-Chittidi** [nus-cs2103-AY2425S1/forum#728]
Is it possible to fix this error message to contain >= instead of <= ? Because from the line above it can be inferred that it is >= but we made a typo in the last line.

<img width="696" alt="Screenshot 2024-11-11 at 6 10 09 PM" src="https://github.com/user-attachments/assets/378e9ddb-8d1b-4ddf-b1ff-d445832245c1">

**Comment by damithc** [comment]
@Raghava-Chittidi Yes, go ahead.

**Comment by Raghava-Chittidi** [comment]
Thank you!
