### ISSUE TITLE
Clarification on violation during feature freeze

### ISSUE THREAD

**Issue by Justin-Yeo** [nus-cs2103-AY2425S1/forum#729]
Hello! I would like to enquire if this violates against the feature freeze. I think it falls under changing grammatical errors but would like to get confirmation. 

Changing the result message from "x persons listed!" to:
- "x person listed!" if there are 0 or 1 returned
- "x persons listed!" if there 2 or more results returned

I believe that the change does not make user-facing information more specific/informative, and it falls under the approved grammar instead.

**Comment by damithc** [comment]
An option that minimizes code changes (which is the purpose of the feature freeze) is to use `person(s)`.

**Comment by Justin-Yeo** [comment]
Thank you for the suggestion prof! Will close the issue.
