### ISSUE TITLE
What to put in Acknowledgment for AI use

### ISSUE THREAD

**Issue by ishan-agarwal-05** [nus-cs2103-AY2425S1/forum#730]
I used AI such as Github Copilot and ChatGPT 4o extensively for the TP, from generating tests to help in solving some bugs.
Also whenever i typed the name of a class, Copilot understood what was to be coded and autofilled almost perfect code which i accepted. 
My teammates did not use or barely used AI, but i did a lot so how should i acknowledge this in the acknowledgement section

**Comment by damithc** [comment]
@ishan-agarwal-05 In acknowledgements section, you can mention which classes/features benefited from which AI tools.

**Comment by ishan-agarwal-05** [comment]
<img width="1017" alt="image" src="https://github.com/user-attachments/assets/bf17bb87-2577-4267-883b-7befb08aad58">
Is this good enough?

**Comment by damithc** [comment]
Yes but I suggest mentioning the features that you did so that the reader knows which parts of the code were generated with the help of AI tools.

**Comment by ishan-agarwal-05** [comment]
<img width="1153" alt="image" src="https://github.com/user-attachments/assets/211fddc7-ac31-4689-919a-a2cef201e56d">
What about this?
I mentioned attendance tracking commands in the acknowledgement. I used some form of AI tool for atleast some portion (either testing or something else) in all of my commands

**Comment by damithc** [comment]
@ishan-agarwal-05 Yes, this seems fine.

**Comment by ishan-agarwal-05** [comment]
Thanks a lot Prof
