### ISSUE TITLE
Clarification on whether we are allowed to change code such that it accepts more valid emails, as per error message

### ISSUE THREAD

**Issue by bmanara** [nus-cs2103-AY2425S1/forum#732]
Hi Profs, we have this issue that was brought up after the PE-D and I was wondering if we are allowed to change the regex so that it can fix this bug.

Specifically the issue is that there are some valid emails that our app seems to consider as invalid, despite it following the error message format: 
![image](https://github.com/user-attachments/assets/dc6ddec9-a231-4acb-affd-b4e1084cde5d)

Would it be considered as fixing a bug (allowed)? or is it considered an enhancement(not allowed)?

**Comment by damithc** [comment]
@bmanara If valid inputs are being rejected, it is considered a bug and you are allowed to fix it.

**Comment by bmanara** [comment]
Ok Prof, thank you so much for the prompt response!
