### ISSUE TITLE
Question about planned enhancements

### ISSUE THREAD

**Issue by Feng1231** [nus-cs2103-AY2425S1/forum#733]
Can our planned enhancements be a plan to integrate two commands into one, if the integration of the two commands could make command usages for our application perhaps clearer?

**Comment by damithc** [comment]
@Feng1231 Yes, that is acceptable.

**Comment by Feng1231** [comment]
Thank you prof, our plan is as such:
Each of the two commands takes in one parameter each, but they tackle rather similar use cases. For this, we will
* Use one planned enhancement to talk about the integration of the two commands. The new command will take in two parameters (which is the parameters from the l two original commands

May I then clarify that, In PED, one tester raised that there were possible improvements for the parameters in the two original commands, May we address them in another planned enhancements, where we state how we would want to improve both new parameters of the new integrated comand?
