### ISSUE TITLE
Is 'known limitation' a section in the UG? 

### ISSUE THREAD

**Issue by annabellekk** [nus-cs2103-AY2425S1/forum#734]
Hi, just to clarify, when it says we are allowed to have known limitations, are we supposed to list out the known limitations under a separate section, or as long as we make it known to the user it is acceptable? (e.g. in Q&A section)
<img width="817" alt="Screenshot 2024-11-11 at 10 21 46 PM" src="https://github.com/user-attachments/assets/f062e160-3561-48aa-be0b-bf4fab35ef68">

**Comment by damithc** [comment]
@annabellekk You can inform the user of known limitations in any way you see fit.

**Comment by annabellekk** [comment]
Ok, thank you Prof!
