### ISSUE TITLE
Clarification whether or not fix violates feature freeze

### ISSUE THREAD

**Issue by ckclion** [nus-cs2103-AY2425S1/forum#735]
Hi profs, currently my team's application has a UI error when users edit the data file manually. For a correct use case, pinned users should appear at the top of the UI. However if users manually edit the pinned parameter and starts the application, it does not appear at the top of the UI like it should. I believe my question would fall under this category however I would just like to double confirm whether fixing this would be considered violating the feature freeze.
![image](https://github.com/user-attachments/assets/cc6157d6-7776-4bc9-9444-c3588c2ec71e)

Thank you profs!

**Comment by damithc** [comment]
@ckclion Is it because the data file was edited incorrectly or even correct edits cause this issue? If the latter, is there a workaround?

**Comment by ckclion** [comment]
@damithc Correct edits will cause this issue. There is an unintuitive workaround is by calling the pin command on any contact on the list.

**Comment by damithc** [comment]
@ckclion If even the correct edits cause the application to misbehave, you can fix it. But limit your fix to this specific problem only.

**Comment by ckclion** [comment]
Ok thanks prof!
