### ISSUE TITLE
Clarification regarding equals command violating feature freeze

### ISSUE THREAD

**Issue by elliot-tang** [nus-cs2103-AY2425S1/forum#736]
In order to improve code coverage for our Parser component, we want to add an equals method in one of our Commands (to override the default Object equals method). Does this count as violating the feature freeze? 

The change does not result in any behaviour changes to the application, and is only used to improve test coverage.

Thanks in advance!

**Comment by damithc** [comment]
@elliot-tang Yes, that should be fine. 
Caution: The `equals` method is used by Java, and overriding it can have unintended consequences at other parts of the application.
