### ISSUE TITLE
PlantUML Rake SVG Reuse

### ISSUE THREAD

**Issue by Domokunx** [nus-cs2103-AY2425S1/forum#738]
Hi prof, I couldn't find proper support for the "Rake" symbol in the PlantUML documentation, and found this alternative solution from this forum: https://forum.plantuml.net/195/is-there-any-support-for-subactivity-or-the-rake-symbol from an anonymous poster.

Would it be alright to use the SVG here? Given that I credit the forum link in the .puml file as well as in the DG where it is first used.

**Comment by damithc** [comment]
@Domokunx Yes, that should be fine.

**Comment by Domokunx** [comment]
Thank you prof @damithc !
