### ISSUE TITLE
Clarification on whether we can fix invalid date input

### ISSUE THREAD

**Issue by tata32000** [nus-cs2103-AY2425S1/forum#739]
Currently, our application accepts invalid dates, such as 31-02-2024, and automatically adjusts them to the nearest valid date when scheduling. Could we fix this by displaying an error message to prompt users to enter a valid date instead?

![Screenshot 2024-11-12 at 00 16 17](https://github.com/user-attachments/assets/2f8c8f7e-0902-479d-8088-259df6e74d52)

**Comment by damithc** [comment]
@tata32000 This is not strictly incorrect. In fact this is the default behaviour of some date libraries. You can inform the user about this behaviour via the UG, and leave a more nuanced response to a future version or as a Planned Enhancement.

**Comment by tata32000** [comment]
Thank you prof!
