### ISSUE TITLE
Can I change this error message?

### ISSUE THREAD

**Issue by tanyqcollin** [nus-cs2103-AY2425S1/forum#743]
![image](https://github.com/user-attachments/assets/99ff30b2-638e-419b-afb8-828472d2b677)
This the error message in the app. Can I change the parameter’s error message because this function needs to have prefix instead of just a keyword.

**Comment by damithc** [comment]
@tanyqcollin Yes, this error in the message can be fixed.

**Comment by tanyqcollin** [comment]
Hi  prof,  can I also add an additional message to this error such that it must provide at least one optional field so that it can be a valid input?

**Comment by damithc** [comment]
@tanyqcollin Yes, if that condition is required for the command to succeed, you can add it.

**Comment by tanyqcollin** [comment]
Thank You, prof!
