### ISSUE TITLE
Github pages suddenly failing to deploy for DG due to null value error in bootstrap-utility

### ISSUE THREAD

**Issue by nuagetsu** [nus-cs2103-AY2425S1/forum#745]
Our developer guide now cannot deploy due to a null value error in bootstrap-utility, as shown in the screenshots below. We are unsure which commit caused this. Is there anyone who has encountered this issue and is able to provide some direction on how to fix this?

![image](https://github.com/user-attachments/assets/9de6a84b-b668-48a1-afcb-8683310f50ec)

![image](https://github.com/user-attachments/assets/d98ba8dd-8283-46ef-99d5-406254b70940)

**Comment by damithc** [comment]
@EdaYeo Are you able to run the site locally?

**Comment by nuagetsu** [comment]
> @EdaYeo Are you able to run the site locally?

May I ask how to run the site locally? We were under the impression that github renders the .md file to a static HTML, but is there anyway for us to do that locally?
The DeveloperGuide.md works on our devices and within the github repo preview.
Thank you!

**Comment by damithc** [comment]
I tested your site locally and did a `bit bisect` to find the problematic commit.
It seems to be https://github.com/AY2425S1-CS2103T-W09-4/tp/commit/6659f398cb30b31f1d55493277bcf5efbd05f000#diff-1a95edf069a4136e9cb71bee758b0dc86996f6051f0d438ec2c424557de7160bR783
I added a comment to indicate the likely error.

**Comment by nuagetsu** [comment]
> I tested your site locally and did a `bit bisect` to find the problematic commit. It seems to be [AY2425S1-CS2103T-W09-4/tp@6659f39#diff-1a95edf069a4136e9cb71bee758b0dc86996f6051f0d438ec2c424557de7160bR783](https://github.com/AY2425S1-CS2103T-W09-4/tp/commit/6659f398cb30b31f1d55493277bcf5efbd05f000#diff-1a95edf069a4136e9cb71bee758b0dc86996f6051f0d438ec2c424557de7160bR783) I added a comment to indicate the likely error.

It works now, thank you so much!!
