### ISSUE TITLE
Can I change incorrect example provided in the help window?

### ISSUE THREAD

**Issue by Bonzzz3** [nus-cs2103-AY2425S1/forum#746]
I have a command summary table in the help window of the app. However, one of the example provided has a parameter that was incorrect, so when user copy-paste it and run the command, an error message of wrong parameter will show. Can I change this without violating feature freeze?

**Comment by damithc** [comment]
@Bonzzz3 You can fix if the current text is incorrect, and misleading to users.

**Comment by Bonzzz3** [comment]
Thanks prof. I have another question. We have a new feature that we forgot to add to the command summary table. Is it okay if we add it now?

**Comment by damithc** [comment]
@Bonzzz3 Yes, you can add it.

**Comment by Bonzzz3** [comment]
Thank you prof!
