### ISSUE TITLE
Clarification on Allowed PE Software 

### ISSUE THREAD

**Issue by SeeYangZhi** [nus-cs2103-AY2425S1/forum#749]
What are some examples of allowed text editors? Are rich text editors like Sublime Text, VSCode, etc considered under the term - text editors?

**Comment by zaidansani** [comment]
Hmm, I think any IDEs would qualify under the distinction as a text editor. There probably could be a list of accepted editors but there are so many that people use that it would probably result in way too much amendments to the list.

Always good to clarify though!

**Comment by damithc** [comment]
Any text editor that doesn't have any online collaboration features is fine. 
The best is to stick to a simple editor -- the fancier it looks, the higher the chance of the invigilators checking with you about it, which can cost you time.

**Comment by SeeYangZhi** [comment]
> Hmm, I think any IDEs would qualify under the distinction as a text editor. There probably could be a list of accepted editors but there are so many that people use that it would probably result in way too much amendments to the list.
> 
> 
> 
> Always good to clarify though!

Agreed. Just not so sure if the use of certain such software with capabilities of AI plugins are allowed.

**Comment by SeeYangZhi** [comment]
> Any text editor that doesn't have any online collaboration features is fine. 
> 
> The best is to stick to a simple editor -- the fancier it looks, the higher the chance of the invigilators checking with you about it, which can cost you time. 

In this case VScode isnt allowed then. And even Apple's notes default notes app with icloud sharing. Actually even microsoft word allows online collaboration...

I think students definitely understand that collaboration features aren’t allowed, and invigilators should be there to ensure compliance. However, the question of whether software with AI tools or plugins is permissible remains unclear and may require additional clarification.

**Comment by SeeYangZhi** [comment]
@damithc Are there further clarifications on this topic? Else I will close the issue.

**Comment by damithc** [comment]
@SeeYangZhi We recommend using a simpler text editing tool, but we don't explicitly prohibit more sophisticated tools. And yes, using collaboration features is not allowed, even if such a feature exists in the tool.

**Comment by SeeYangZhi** [comment]
> @SeeYangZhi We recommend using a simpler text editing tool, but we don't explicitly prohibit more sophisticated tools. And yes, using collaboration features is not allowed, even if such a feature exists in the tool.

Cool, thanks prof
