### ISSUE TITLE
Git Standard Admin Task

### ISSUE THREAD

**Issue by aditig0305** [nus-cs2103-AY2425S1/forum#75]
How do we pass the Git Standard admin task as reflected in the ip progress dashboard? Is it by following the conventions for commit messages?

**Comment by damithc** [comment]
@aditig0305 You can find more details on the requirements of each item by clicking on the `details` button.

![image](https://github.com/user-attachments/assets/530c14ec-ad48-403f-9d87-58bc68931af1)

**Comment by aditig0305** [comment]
Thank you so much! Sorry that I missed that.
