### ISSUE TITLE
Clarification on duplicate bugs

### ISSUE THREAD

**Issue by jktang14** [nus-cs2103-AY2425S1/forum#750]
Hi. I would like to check the extent to which bugs are considered duplicates. For example, during the PE dry run, I encountered exceptions for 3 of a command's parameters. Eg. `sort email`, `sort address`, `sort age`

The type of bug for all 3 of them were quite similar in that the exception raised was due to clients not having values for that particular parameter. Would it be acceptable to put these cases into separate bugs?

**Comment by damithc** [comment]
@jktang14 Some relevant parts from [this page](https://nus-cs2103-ay2425s1.github.io/website/admin/tp-pe.html):

![image](https://github.com/user-attachments/assets/fded32f0-ba42-472b-8e11-8b9bc86126ee)

...

![image](https://github.com/user-attachments/assets/dbf87cb5-8da5-4e21-a675-7676682f3f4b)

**Comment by jktang14** [comment]
Hi Prof. I did read up on this portion before, specifically this portion was the one I wasn't sure about in this case as it seems possible for a dev team to phrase it such that they are considered the "exact same bug".
> The exact same bug reported multiple times

**Comment by damithc** [comment]
@jktang14 your concern is that the dev team will take different bugs and flag them as duplicates?

**Comment by jktang14** [comment]
Yes, as the same exception occurs just for many different parameters under the same command

**Comment by damithc** [comment]
@jktang14 The dev team has to 'prove' that fixing one fixes the rest. This is easy to prove or disprove, by referring the relevant code. And the tester gets a chance to object if s/he disagrees with the duplicate flag.

**Comment by jktang14** [comment]
I see, thanks for the clarification Prof.
