### ISSUE TITLE
java -version says I'm running java 22. What now?

### ISSUE THREAD

**Issue by 1st2GetThisName** [nus-cs2103-AY2425S1/forum#751]
The guide constantly mentions that I should make sure that I am not running a version of java later than version 17, but doesn't explain what to do if I am. DuckDuckGo doesn't seem to have any good answers either.

**Comment by JoanneHing** [comment]
I am not sure which OS you are using, but I followed this [guide](https://se-education.org/guides/tutorials/javaInstallationMac.html) that provided for Mac user to change the Java version, taken from the textbook.

**Comment by 1st2GetThisName** [comment]
Thanks!
