### ISSUE TITLE
Will we be expected to know the Unified Process?

### ISSUE THREAD

**Issue by ITZXITZX** [nus-cs2103-AY2425S1/forum#753]
Hi Prof, 

In the course briefing video this week, one of the questions you provided as an exam like question was:
```Is the Unified process iterative or sequential?```

However the textbook categorised the topic, "Can explain the Unified Process" as 4 stars.

May I clarify if we are expected to know the unified process?

**Comment by damithc** [comment]
@ITZXITZX 4-star topics will not be in the exam.
