### ISSUE TITLE
Able to see PE-D feedback from tested teams?

### ISSUE THREAD

**Issue by sannie-beep** [nus-cs2103-AY2425S1/forum#754]
Hi profs, is there any way for us to be able to see the feedback given to us from the teams we reported bugs for during PE-D? So that we can have a better sense of what kind of bugs to report and the associated severity levels that would be considered acceptable. To see if we are on the right track.

Sorry if this question has been answered before, because if so, I am unable to find where. :/

**Comment by damithc** [comment]
@sannie-beep We don't reveal the rating for PE-D bugs. However, you can visit their issue tracker and see which of the PE-D they fixed, what bugs you missed but were caught by other PE-D testers, what priority they gave to the bugs you reported etc. These observations can help you do a better job at the PE.

**Comment by sannie-beep** [comment]
Ah I see. Will do, thanks for replying, Prof!
