### ISSUE TITLE
Self Prepared PDF note

### ISSUE THREAD

**Issue by JoanneHing** [nus-cs2103-AY2425S1/forum#755]
<img width="791" alt="Screenshot 2024-11-15 at 1 08 27 AM" src="https://github.com/user-attachments/assets/d56bdb61-59cf-4027-8a66-d74f78d8179e">

I prepared a note using notion myself for PE preparation, but since website other than canvas, coursewebsite, MSTeams and Catcher are not allowed, can I export my note as PDF and view it with PDF viewer instead?

**Comment by damithc** [comment]
@JoanneHing Yes, you may view PDF viewer.

**Comment by JoanneHing** [comment]
Thank you prof for the clarification!
