### ISSUE TITLE
Are we allowed to read files on our computers during PE?

### ISSUE THREAD

**Issue by annabellekk** [nus-cs2103-AY2425S1/forum#756]
In the guide, it says that this is allowed - Software: PDF reader (to read the UG/DG or other references such as the textbook)
May I ask if we are allowed to use our own references, i.e. notes previously made (either pdf or in a note taking app such as MS Words)?

**Comment by damithc** [comment]
@annabellekk Yes, reading any local document is allowed.

**Comment by annabellekk** [comment]
Ok, thank you Prof
