### ISSUE TITLE
What does this mean in the bug density section in the website? The slashes are confusing?

### ISSUE THREAD

**Issue by samuelthen** [nus-cs2103-AY2425S1/forum#757]
<img width="734" alt="Screenshot 2024-11-15 at 1 30 47 PM" src="https://github.com/user-attachments/assets/5c3de838-0503-49fb-8c71-7d7b8701928d">

**Comment by damithc** [comment]
4/5 means 4 out of 5 marks

**Comment by samuelthen** [comment]
So high bug density means - 4/5 deducted, low bug density means -1/5 mark?

**Comment by damithc** [comment]
@samuelthen I revised the explanation as follows:

![image](https://github.com/user-attachments/assets/23c6e057-2447-4aa9-8741-d27cf706d1b5)

**Comment by samuelthen** [comment]
Okay thanks!
