### ISSUE TITLE
End time of PE

### ISSUE THREAD

**Issue by Wxy2003-xy** [nus-cs2103-AY2425S1/forum#759]
Hi may i ask if the we can leave immediately when the PE ends, at 1800? Asking because i have a final exam at MPSH at 1830

**Comment by damithc** [comment]
@Wxy2003-xy See below:
![image](https://github.com/user-attachments/assets/f44174b4-2d99-41c4-8968-851644a28950)

**Comment by Wxy2003-xy** [comment]
Ok i see thank you!
