### ISSUE TITLE
A-MoreOOP Difference between Ui and Parser classes.

### ISSUE THREAD

**Issue by rayray39** [nus-cs2103-AY2425S1/forum#76]
Both classes interact with the user. Parser should make sense of user commands, but since the program interacts with the user through the command line currently, isn't Ui doing the same thing?

**Comment by leslieyip02** [comment]
I think `Ui` is for receiving input while `Parser` is for processing the input. For example, `Ui` might have a `readLine` method to receive input from the user, but it will pass the raw input to `Parser` to make sense of the input.

For me, my `Parser` class has a static method to parse the description of a task, and a static method to parse the slash arguments for a task. So, I would do something like this:
```
String description = Parser.parseDescription(input);
Map<String, String> arguments = Parser.parseArguments(input);
```
This extracts the values I need from the input line, and then I can do something else with those values.

**Comment by jagdeepsh** [comment]
Yup I agree with the previous comment, you can look at Parser being solely responsible for processing the input. You can reference the example provided in `run()` under `A-MoreOOP Stretch Goal`. Notice how it is receiving a `String fullCommand` that you can get from the `ui` instance. After which it then returns an instance of `Command c` in this case. The `Ui` class for me is solely responsible for receiving inputs and printing outputs.

For me personally, I decided to use `Enums` with my `Parser` Class to match the string inputs to the range of commands that exist, though I am sure there are better ways to do this.

**Comment by RezwanAhmed123** [comment]
Hi I’m not sure if I’m doing it wrongly but I allowed my main class be the one just simply take inputs and throw it into the parser which then parsed the input into a command. Then I had another class, processor, which processed said inputs. My Ui class was named “formatted printer” and handled only the printing of outputs to user.

So my structure was like

Input from main -> turns into a recognisable command inside of parser -> the command is acted on by a processor -> the resulting feedback is then printed by the UI class

Similar to the above person I used enums for my commands as well.

**Comment by jloh02** [comment]
@RezwanAhmed123 I think your approach generally makes sense but in my opinion your UI class should still include your text input. This is because UI involves both input and output from/to users. 

Likewise, I used enums and allowed the Command class to have an `execute` method
