### ISSUE TITLE
Using the washroom during the PE (Zoom mode)?

### ISSUE THREAD

**Issue by matthewyip1511** [nus-cs2103-AY2425S1/forum#760]
Apologies for the late question, but this just came to mind and I realised that there are no instructions for this on the website.. Should we message our invigilator on Teams if we need to use the washroom?

Thank you!

**Comment by damithc** [comment]
Yes, drop a Zoom message to invigilator before leaving

**Comment by matthewyip1511** [comment]
Got it, thank you prof!
