### ISSUE TITLE
PE Severity level of bug based on consequences

### ISSUE THREAD

**Issue by OttoTan** [nus-cs2103-AY2425S1/forum#761]
Hi Prof, I had a question relating to a severity level of a bug. Say for example you discovered a bug and you reported it as `medium`. However, after the PE, you realized that the bug, if you followed the steps to reproduce, will cause the applications memory to be lost upon restart, which seems like a bug with high severity.

In this case, although you did not state the memory lost as the issue, should you still classify it as a high severity?

**Comment by damithc** [comment]
@OttoTan Tough one. You can change the severity at this stage but you can't change the description. If you think the team 'ought to' know the high severity of the problem even if you didn't mention the relevant details, you can mark it at a higher severity. You can add additional info during the 'tester response' phase, if the team doesn't agree with your severity.

**Comment by OttoTan** [comment]
Thanks for the insight Prof!
