### ISSUE TITLE
Trimmed the bugs before the announcement

### ISSUE THREAD

**Issue by Feng1231** [nus-cs2103-AY2425S1/forum#765]
My teammate and I trimmed and closed some of the bug reports before the announcment was made as we took a quick glance of part IV and misinterpreted the [~half a day] to start from 6pm today.

> We'll let you know when it is open. If you do update bugs during this period, we will automatically take the last version that was submitted/updated before the part II deadline.

Does this means that we don't have to do anything to remedy this?

**Comment by damithc** [comment]
@Feng1231 It's fine. We'll preserve the label changes and revert any changes to the title/body.

**Comment by Feng1231** [comment]
Thank you prof
