### ISSUE TITLE
Question about procedure in the event of an unclear bug title

### ISSUE THREAD

**Issue by Andrew22Teoh** [nus-cs2103-AY2425S1/forum#766]
After the PE, I realised that I had written the title of one of my bugs wrongly, writing "invalid" when I had meant to write "valid". This is likely to cause some confusion for the team when reading it, though the description of the bug will make sense in of itself.

Is there a way to rectify this or communicate this to them? Or will it simply result in a rejection of the bug?

**Comment by damithc** [comment]
@Andrew22Teoh If the description of the bug is correct, the title shouldn't matter. In any case, there is no avenue to update title or description at this point.
