### ISSUE TITLE
How to tell if its a documentation bug or a functionality bug?

### ISSUE THREAD

**Issue by kyouscrap** [nus-cs2103-AY2425S1/forum#767]
This group did not mention anywhere in their user guide that when editing an entity in their application, doing "t/  " would result in existing tags being deleted. Although this is the original functionality of AB3 and is most likely a documentation bug, as a tester unaware of this fact, is it not also right to claim that this is a feature bug since it leads to "unintended" consequences?

**Comment by damithc** [comment]
@kyouscrap It's good to discuss this here and get opinions of the other. But the final decision is yours -- as the decision if part of the deliverable (and affects your grade), the teaching team will not give a definitive answer at this stage of the PE.
