### ISSUE TITLE
Missing team size and naming convention

### ISSUE THREAD

**Issue by annabellekk** [nus-cs2103-AY2425S1/forum#769]
Hi, in the textbook, it says to state the team size under the section of planned enhancement so that the tester can know whether the count exceeds the allowed number. If the team does not state the team count, is this a documentation bug? Since it is only applicable in this course to aid testing. 
<img width="826" alt="Screenshot 2024-11-16 at 11 06 35 AM" src="https://github.com/user-attachments/assets/8b44cb08-0faf-48de-8d70-e0f5a1d88dfa">

Secondly, if the team names the sections differently, e.g. known problems / known bugs instead of known issues, or future plans / future enhancements instead of planned enhancements can I assume that they are each referring to the known issues and planned enhancement section as per the textbook, and apply the same rules? (i.e. bugs in known issues do not have immunity but bugs in planned enhancements do)

**Comment by damithc** [comment]
> Hi, in the textbook, it says to state the team size under the section of planned enhancement so that the tester can know whether the count exceeds the allowed number. If the team does not state the team count, is this a documentation bug? Since it is only applicable in this course to aid testing.

@annabellekk Yes, requirements imposed by the course on the tP are non-functional project requirements. Not meeting them is a bug.

> Secondly, if the team names the sections differently, e.g. known problems / known bugs instead of known issues, or future plans / future enhancements instead of planned enhancements can I assume that they are each referring to the known issues and planned enhancement section as per the textbook, and apply the same rules? (i.e. bugs in known issues do not have immunity but bugs in planned enhancements do)

Yes, if there is no ambiguity, you can ignore minor deviations in the section name.

**Comment by annabellekk** [comment]
Thank you prof!
