### ISSUE TITLE
Are stretch requirements required for full marks for IP?

### ISSUE THREAD

**Issue by Brendan8899** [nus-cs2103-AY2425S1/forum#77]
Hi Prof and Coursemates,

I would like to ask whether I need to complete all stretch goals to get full credit?

Thank you very much.

**Comment by damithc** [comment]
@Brendan8899 No, it's enough to reach the minimum requirements. The stretch requirements helps you gain more practice (which will help you do better in the tP) and make your iP stand out from the rest, but there is no direct impact on marks if you didn't do them.
