### ISSUE TITLE
What should the severity of a repeated issue in documentation be?

### ISSUE THREAD

**Issue by aditig0305** [nus-cs2103-AY2425S1/forum#770]
If there is an issue with the use case (a step is mentioning internal details of system) and this was repeated for many of the use cases, would the severity increase due to the number of times it was repeated? If it was just one use case, I would put it as severity low but it is in most of the use cases. Does this mean severity medium is more appropriate?

**Comment by damithc** [comment]
@aditig0305 Yes, the severity is linked to the impact on the reader, and hence, the frequency of the problem.

**Comment by aditig0305** [comment]
Thank you! I will increase the severity accordingly then.
