### ISSUE TITLE
Does A and B needing to follow same specifications indicate coupling?

### ISSUE THREAD

**Issue by yizhong187** [nus-cs2103-AY2425S1/forum#771]
Hello everyone, I was reviewing the notes on coupling, and noticed that **option f** indicates coupling. Doesn't having to "follow the same data format or communication protocol" imply that they might both be coupled to some other component (the data format or communication protocol), rather than to each other? Thanks for any help!

<img width="663" alt="image" src="https://github.com/user-attachments/assets/5ff1128d-2b18-4bc8-bb44-1c4104b2310e">

**Comment by Feng1231** [comment]
Hi, I found this on the course website:
Perhaps in this case, there is common coupling present between A and B.
![image](https://github.com/user-attachments/assets/de75fa5f-533b-4f6c-b5f4-11ba1623ab88)

**Comment by yizhong187** [comment]
Thanks Feng.
