### ISSUE TITLE
Non matching capped VARIABLES 

### ISSUE THREAD

**Issue by Feng1231** [nus-cs2103-AY2425S1/forum#772]
Referring to #663, may I check whether if not matching the variable name is solely a cosmetic issue? I personally feel that such mismatch shouldn't be just a cosmetic issue as it might cause confusion to reader / user as they will be unsure what that VARIABLE is referring to.

**Comment by damithc** [comment]
@Feng1231 It's good to discuss this here and get opinions of the other. But the final decision is yours -- as the decision if part of the deliverable (and affects your grade), the teaching team will not give a definitive answer at this stage of the PE.

**Comment by damithc** [comment]
To add, _cosmetic_ in this context means _affecting only the appearance of something rather than its substance_

**Comment by Feng1231** [comment]
Thank you prof
