### ISSUE TITLE
Bug Trimming Clarification

### ISSUE THREAD

**Issue by AgentHagu** [nus-cs2103-AY2425S1/forum#773]
Hi, in one of my bug reports, I realised that in my explanation, my examples had a typo which might cause confusion for the dev team when reading it. Will this be an issue? 

The explanations themselves are still fine I believe, but the supporting example might be confusing or misleading if they don't realise there's a typo.

**Comment by JoanneHing** [comment]
<img width="782" alt="Screenshot 2024-11-16 at 1 59 23 PM" src="https://github.com/user-attachments/assets/1aea3727-6050-4e2a-9e9a-31fc7db67749">

I think you shouldn't change your description as it will still be reverted back if you did so.

**Comment by AgentHagu** [comment]
Ye, I thought so too. I guess I'll just have to hope the dev team understands. Thx for the comment
