### ISSUE TITLE
Missing Acknowledgements section in the DG

### ISSUE THREAD

**Issue by yongkheehou** [nus-cs2103-AY2425S1/forum#774]
If a group does not credit AB3/ any other sources in the Acknowledgements section of the DG, is it considered a bug? I'm not too sure as it does not affect the functionality/ using of the app

**Comment by damithc** [comment]
@yongkheehou A project not following a project requirement (even those imposed by the course) can be considered a bug.

**Comment by yongkheehou** [comment]
thanks for clarifying!
