### ISSUE TITLE
[tP] Names cannot be the same

### ISSUE THREAD

**Issue by dominopizzaaaa** [nus-cs2103-AY2425S1/forum#778]
In the application I tested, their UG mentioned that they disallow same names and /, @, ' in names. Can I list this as a bug even though they have stated it in their UG? 

Because I feel that many people have such names and it will be a huge inconvenience for users if same names are not allowed. I was thinking also if this should be severity.LOW or severity.MEDIUM. Will be open to any opinions!

**Comment by damithc** [comment]
@dominopizzaaaa If you think the current behaviour is not optimal (even if it follows the UG), you can report it as a `type.FeatureFlaw`.
