### ISSUE TITLE
Use of outdated AB3 terms 

### ISSUE THREAD

**Issue by kngys** [nus-cs2103-AY2425S1/forum#779]
Hi, 
Could I clarify if certain instances of AB3 terms were not replaced (e.g. the json file not renamed to new product name but left as addressbook), would this be considered a bug? Or is it considered acceptable in this course (since the product was developed from AB3)? Thank you!

**Comment by damithc** [comment]
@kngys related https://github.com/nus-cs2103-AY2425S1/forum/issues/677
