### ISSUE TITLE
Criteria for a bug report to be `NotInScope`

### ISSUE THREAD

**Issue by JoanneHing** [nus-cs2103-AY2425S1/forum#781]
<img width="692" alt="Screenshot 2024-11-16 at 6 12 36 PM" src="https://github.com/user-attachments/assets/2af70e38-0071-4335-ad96-f5b59b85b2d6">

I am a bit confused how is a bug categorized as `NotInScope`, as the product I tested they allow the contact to have tags, just like AB3. But the product currently do not have a feature to easily add or remove tags, only way is to use `edit` feature, but if there is several existing tag, such as 4 tags or above, the user had to copy down the tag they want to keep and add the new tag if needed, the UG did mention that editing tag is replacing the whole existing tag but the UG doesn't mention anything planned feature that could solve this problem.

How do we categorize these issue as `NotInScope` or `FeatureFlaw` as the team may state that this feature is not important for current iteration but I think this causes some inconvenience to the user.

**Comment by damithc** [comment]
@JoanneHing You can consider points such as the below when deciding:
 
a) If you were in the dev team's shoes, would you have decided to include this feature? 
b) Which less-important current feature would you have killed off in favour of this one? 
c) If you were in the target user's shoes, is the alternative version better for you? Why?

**Comment by JoanneHing** [comment]
Thank you prof for the guidance! I had some idea now!
