### ISSUE TITLE
How are marks awarded for the tester in different cases of response and severity

### ISSUE THREAD

**Issue by psh12320** [nus-cs2103-AY2425S1/forum#782]
Can I ask which of the cases would be awarded higher marks for the tester:

1. `severity.Low + response.NotInScope`
2. `severity.VeryLow + response.Accepted`

I think this information would very helpful for trimming down bugs.

**Comment by damithc** [comment]
@psh12320 Testers earn only a small amount of credit for `NotInScope` bugs. So, 2.

**Comment by psh12320** [comment]
Alright, thank you prof!
