### ISSUE TITLE
Can you reject a response.NotInScope?

### ISSUE THREAD

**Issue by PeterHW963** [nus-cs2103-AY2425S1/forum#785]
![image](https://github.com/user-attachments/assets/dcff2147-70db-4845-b7b4-cd1f0a64ab7a)
If for instance I believe that a certain feature is vital for the application, yet the developer team decided it to be not in scope because it is a known bug that they believe isn't a priority or isn't so important, are you allowed to reject their `response.NotInScope` response?

**Comment by damithc** [comment]
@PeterHW963 Certainly. You can make your case against the `NotInScope` label, and the teaching team will decide after consideirng your justification and the team's.

**Comment by PeterHW963** [comment]
I see, thank you prof!
