### ISSUE TITLE
What to do with bug reports that are not for our team

### ISSUE THREAD

**Issue by IzN432** [nus-cs2103-AY2425S1/forum#786]
Our team has multiple bugs that seem to be for another team. For example, #3413. What should we do about these bugs?

**Comment by damithc** [comment]
@IzN432 Please send me the full list of such bugs

**Comment by damithc** [comment]
@IzN432 Ignore them for now. We'll move them to the correct team.

**Comment by IzN432** [comment]
#3411
#3413
#2972
#1825 (our app does not have emails)
#983
#982

This should be the exhaustive list.

**Comment by damithc** [comment]
@IzN432 There were 7 such cases. All moved to the correct team. Click the `Sync` button in your CATcher and they should disappear from your view.

**Comment by IzN432** [comment]
Thank you prof!
