### ISSUE TITLE
Should bugs that are classified as Rejected or Not in Scope have assignee(s)?

### ISSUE THREAD

**Issue by SeeYangZhi** [nus-cs2103-AY2425S1/forum#788]

**Comment by damithc** [comment]
@SeeYangZhi  When possible, add assignees. If the rejection is not accepted later, and if the bug has no assignees, the penalty will be devided among all team members. If you are OK with that, or if that is indeed the appropriate division of the penalty, no need to add assignees.  

<img width="769" alt="image" src="https://github.com/user-attachments/assets/8dab0628-7710-49ce-af04-bfcb056a5907">
