### ISSUE TITLE
Can Use Cases Contain Non-UI Implementation Details?

### ISSUE THREAD

**Issue by yongkheehou** [nus-cs2103-AY2425S1/forum#789]
<img width="736" alt="Screenshot 2024-11-17 at 2 11 56 PM" src="https://github.com/user-attachments/assets/ddfc1d43-cd74-40e7-9686-232a8c168771">

Hi, the course website states

>  A step gives the intention of the actor (not the mechanics). That means UI details are usually omitted. The idea is to leave as much flexibility to the UI designer as possible. That is, the use case specification should be as general as possible (less specific) about the UI.

Would it be a bug if the 3rd step of the MSS was changed to something that includes the user inputs required for the bank transfer, e.g. `User enters the amount and bank account number for the transaction`? Or would such non-UI details be acceptable in the Use Case MSS?

**Comment by damithc** [comment]
@yongkheehou You'll need to compare the two alternatives and see which one has more pros than cons. Stating a step in a more general way (without specifying the input fields) makes it future-proof but one downside is the UI designer will need to find out the exact details later. On the other hand, a use case is not the right place to give precise details of all input fields, especially if there are many such fields that need to be defined precisely, in which case it is better to specify them elsewhere and not mention them in the use case, to avoid duplication and potential inconsistency.
