### ISSUE TITLE
Submission

### ISSUE THREAD

**Issue by JellyPenguinnn** [nus-cs2103-AY2425S1/forum#79]
Does anyone know how to solve this <This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository>? Thank you so much!!

**Comment by Incogdino** [comment]
Have you pushed the branch onto github?

**Comment by JellyPenguinnn** [comment]
yes, i pushed it by using: git push origin master

**Comment by damithc** [comment]
To help you all troubleshoot this problem, here's the current state of the repo:

![image](https://github.com/user-attachments/assets/138b7f4a-f7af-4bca-9624-ecbae6ea7dfb)

**Comment by JellyPenguinnn** [comment]
should i push it to nus-cs2103-AY2425S1/ip.master to be detected by the dashboard?

**Comment by damithc** [comment]
@JellyPenguinnn It looks like your tags are on some 'stranded' commits, not reachable from the master branch. Try the following:

* delete existing tags (both locally and in the remote repo)
* create them again in the local repo
* push tags to the remote repo

**Comment by JellyPenguinnn** [comment]
Noted. I have solved it. Thank you prof!!!
