### ISSUE TITLE
Can User Stories Include Product Title?

### ISSUE THREAD

**Issue by yongkheehou** [nus-cs2103-AY2425S1/forum#790]
<img width="825" alt="Screenshot 2024-11-17 at 2 22 55 PM" src="https://github.com/user-attachments/assets/e66139a3-b5b8-407d-8d17-03cdf2ad9d8d">

Can a user story include the name of the product? E.g. if the product is called `ABC`, can I refer to `ABC` instead of `the website` or `the app` in the user story above?

**Comment by damithc** [comment]
@yongkheehou Yes, that should be fine.
