### ISSUE TITLE
What defines a harmful input

### ISSUE THREAD

**Issue by Zenkoh1** [nus-cs2103-AY2425S1/forum#792]
![image](https://github.com/user-attachments/assets/3dadbe76-a86f-48e6-ba50-9533c8e78c00)

As mentioned on course website above, what defines a harmful input? On the other hand, what kind of inputs are fine to be accepted because it is not harmful?

**Comment by damithc** [comment]
@Zenkoh1 A harmful input is something that can negatively affect the future operation of the application e.g., a person name, once saved, that causes the search feature to stop working correctly

**Comment by Zenkoh1** [comment]
Okay thank you prof!

**Comment by Zenkoh1** [comment]
Okay thank you, so is it the case where

Even if a user can input an invalid date, but there is no logic that operates on that invalid date (ie. the invalid date is only stored and displayed), it is considered **not harmful**?

**Comment by damithc** [comment]
> Even if a user can input an invalid date, but there is no logic that operates on that invalid date (ie. the invalid date is only stored and displayed), it is considered **not harmful**?

@Zenkoh1 Depends on the context. How much the app should intervene in controlling data validation depends on the field and how it is used. Once you figure out the correct level of validation for a field, doing a lot more than that, or a lot less than that, can be considered as 'flaws'. The validation for IC numbers may need to be different from the validation for address, but both depends on how those two will be used by the app, and by extension, the user. If the app is related to legal work, it is important the IC is correct. But if it is a delivery app, it is important that the address is valid.
