### ISSUE TITLE
Empty dropdown in cs2103 Practical Examination page

### ISSUE THREAD

**Issue by SeanFoongjt** [nus-cs2103-AY2425S1/forum#793]
<img width="1280" alt="image" src="https://github.com/user-attachments/assets/b198c3f5-5063-4936-bf73-154dab763cc9">

There seems to be no information when clicking on the `Can I (i.e., the tester) add more information about the bug when I object to a dev team's response?` dropdown tab as seen above.

**Comment by damithc** [comment]
Thanks for reporting this, @SeanFoongjt 
Fixed.
