### ISSUE TITLE
Multiple instances of application running at once

### ISSUE THREAD

**Issue by arjun2598** [nus-cs2103-AY2425S1/forum#795]
For my team's product, a bug was reported that when multiple instances are being run at once, modifying the data in 1 instance does not synchronise with the other instances, meaning the other instances are not updated together with the modified instance. However, supporting such behaviour seems like it would need features that violate the constraints of the project. Were we supposed to have supported this functionality? Is it okay for my team to reject this bug?

**Comment by damithc** [comment]
> Is it okay for my team to reject this bug?

This part I can't answer (but good to discuss with others here).

However, I would like to remind about the following:

![image](https://github.com/user-attachments/assets/e85b0b37-8a8b-464d-8593-0a56271f77a0)

**Comment by arjun2598** [comment]
Ok will re-evaluate using these guidelines. Thank you prof!
