### ISSUE TITLE
Duplicate bugs penalty

### ISSUE THREAD

**Issue by arjun2598** [nus-cs2103-AY2425S1/forum#797]
For bugs that are identified as duplicates, I understand that the type and labels are inherited from the original. However, what about the assignees? Meaning, if two bugs are similar and identified as duplicates, but my team only wants to assign 1 person to the duplicate bug but 2 people to the original bug. Does the penalty for the duplicate bug apply to both assignees in the original bug then?

**Comment by damithc** [comment]
Assignees are inherited as well. If you are thinking of assigning different assignees maybe you don't _really_ think they are the same bug? 🤔 😁

**Comment by arjun2598** [comment]
Ok thank you for the clarification prof!
