### ISSUE TITLE
Don't understand transitions from parts 1 to 2 to 3 for final exam

### ISSUE THREAD

**Issue by tayxuenye** [nus-cs2103-AY2425S1/forum#798]
![Screenshot 2024-11-17 153611](https://github.com/user-attachments/assets/187c8621-0ac0-4bc2-97c2-ab3bb03feb44)
For the final exam, I don't understand how we will transition from part 1 to part 2. Part 1, 2, and 3 are 3 separate exam files on Examplify?

**Comment by damithc** [comment]
@tayxuenye Yes, the are three exam files in Examplify.

**Comment by tayxuenye** [comment]
Thanks prof
