### ISSUE TITLE
Must we strictly follow the functionality on the website

### ISSUE THREAD

**Issue by df-Nic** [nus-cs2103-AY2425S1/forum#8]
Hello, I was wondering do we need to strictly follow the functionality for a particular level.

![image](https://github.com/user-attachments/assets/f1615447-8a73-47b5-9419-b520c30202f7)

For example in the image above for Level-2, any text the user has entered will be added to a list, besides the 2 keywords **bye** and **list**.

Are we allowed to change it such that the user has to type in **add <Item name>** for it to be added into the list, since the functionality is the same but the method of adding is different.

**Comment by damithc** [comment]
> Are we allowed to change it such that the user has to type in **add ** for it to be added into the list, since the functionality is the same but the method of adding is different.

@Nicholas-Cheng-De-Fei Following the exact command format is not a requirement. In fact, you are encouraged to design your own command format so that your chatbot becomes unique.

![image](https://github.com/user-attachments/assets/99fbcde0-dc06-4a48-909a-f9832eac0c81)

**Comment by df-Nic** [comment]
Thank you for the clarification!
