### ISSUE TITLE
Why do I need to create a PR on my own fork

### ISSUE THREAD

**Issue by seah-minlong** [nus-cs2103-AY2425S1/forum#80]
Hi everyone, I’m a bit confused about the point of creating a pull request (PR) on my own fork of a repository. My understanding is that PRs are typically used when contributing to a remote repository owned by someone else. So, what’s the purpose of making a PR within my own fork or is it just to learn how to create a PR?

![image](https://github.com/user-attachments/assets/29dbc440-512c-4a9d-82d5-7d0f963b4756)

I do see this but I am kinda confused about how that works. Any clarification would be appreciated. Thanks!

**Comment by Justin-Yeo** [comment]
Hello minlong, I believe the making of a PR within your own fork to the upstream repo is mainly for learning purpose :D

**Comment by Feng1231** [comment]
I assume you are referring to the task of created a PR to the upstream repo?

In this case, by creating a PR to the upstream repo, you are essentially asking the upstream repo to review your updates and merge them into the upstream repo.

So if prof approved the PR, your code will be merged into the upstream repo.

(Isn't this exactly the case of contributing to a remote repo owned by someone else?)

**Comment by seah-minlong** [comment]
Ahh i see, that makes sense. Thanks for the help! I shall close the issue.
