### ISSUE TITLE
Past tutorial recordings

### ISSUE THREAD

**Issue by NorbertLoh** [nus-cs2103-AY2425S1/forum#803]
Hi prof, where can we view the past tutorial recordings? I cant seem to find it on Canvas. Thank you!

**Comment by damithc** [comment]
@NorbertLoh In MSTeams (see below)

![image](https://github.com/user-attachments/assets/be424c1e-f2a6-41ac-b3c2-72a456b8996f)

**Comment by NorbertLoh** [comment]
Got it. Thanks prof @damithc !
