### ISSUE TITLE
Overlap of bugs that is addressed in planned enhancements

### ISSUE THREAD

**Issue by choaticman** [nus-cs2103-AY2425S1/forum#804]
Hi Prof,

In our planned enhancement, to address Bug A, we decided to have an enhancement that removes the use of pop-up windows. We then receive a Bug B, which the underlying cause is the use of pop-up windows. Since our planned enhancement already mentioned that we are not using pop-up windows, is Bug B still valid?

Thank you!

**Comment by damithc** [comment]
@choaticman If it should have been apparent to the tester that the underlying cause of the bug is the popup, and the planned enhancement was clear about removing the popup feature, the bug should not have been reported. Otherwise the tester has a case for reporting the bug.

**Comment by choaticman** [comment]
Thank you prof!
