### ISSUE TITLE
Is this a wrong notation in UML diagram

### ISSUE THREAD

**Issue by NgZiXin** [nus-cs2103-AY2425S1/forum#806]
May I check if the use of pointy braces `<<`  and `>>` valid in the case for the role of dependencies?
i.e. is the notation `<<create>>` here wrong? I can't really find much information about the correct notation from the notes.

<img width="409" alt="image" src="https://github.com/user-attachments/assets/9cba6a70-5c0f-40f0-b3ee-9033bb8bee45">
^ This is taken from AB3's Developers Guide.

**Comment by choaticman** [comment]
To add to this, the exact same diagram can be found in the course website. The exact same diagram can be found under: Week 6 Topics > w6.2c (multi-level design) > "Logic" or this following [link](https://nus-cs2103-ay2425s1.github.io/website/book/designApproaches/multilevelDesign/what/)

**Comment by damithc** [comment]
The use of UML stereotypes comes up when we cover design patterns:

<img width="718" alt="image" src="https://github.com/user-attachments/assets/70930664-ad71-433f-8409-c12bbd7a3139">

**Comment by NgZiXin** [comment]
Thank you. Understood! I will be closing the issue.
