### ISSUE TITLE
Should multiple bugs reported regarding use cases' extensions be classified as duplicates?

### ISSUE THREAD

**Issue by SeeYangZhi** [nus-cs2103-AY2425S1/forum#807]
For example, 3 different issues each reporting of UC04, UC05, UC10 that are missing extensions.

**Comment by damithc** [comment]
@SeeYangZhi This is our guideline on determining duplicate bugs:

<img width="769" alt="image" src="https://github.com/user-attachments/assets/ac9e2e6f-fdf6-46da-b25a-7f1ef3968910">
