### ISSUE TITLE
Who to assign issues to that are remnants of ab3

### ISSUE THREAD

**Issue by flyingsalsa** [nus-cs2103-AY2425S1/forum#808]
Hi, we are currently trying to assign issues in the catcher but several are just leftover functionality from ab3 such as case sensitive commands that we never touched. Who do we assign these to?

**Comment by damithc** [comment]
@flyingsalsa If you can't decide who should be responsible for a bug, you can share the responsibility equally -- which you can do by keeping the assignee field blank (if it's blank, we automatically assign all team members to it).

**Comment by flyingsalsa** [comment]
Ok thank you!

**Comment by Kitty-001** [comment]
> @flyingsalsa If you can't decide who should be responsible for a bug, you can share the responsibility equally -- which you can do by keeping the assignee field blank (if it's blank, we automatically assign all team members to it).

Sorry but how does it work exactly by leaving the assignee field blank, i.e. how does it affect the PE grade exactly? Is it something like each one of 5 of us takes 1 marks down if something is worth 5 marks down?

Thank you!

**Comment by damithc** [comment]
> Sorry but how does it work exactly by leaving the assignee field blank, i.e. how does it affect the PE grade exactly? Is it something like each one of 5 of us takes 1 marks down if something is worth 5 marks down?

Yes, it is same as assigning all of you to the bug. The penalty (if any) will be divided among all members.

**Comment by Kitty-001** [comment]
Thank you prof!

**Comment by damithc** [comment]
By the way, no bug will cost 5 marks. Historically, the total penalty for a bug is in the range of `0 .. 1.5` :-)
