### ISSUE TITLE
Pseudocode in sequence diagram

### ISSUE THREAD

**Issue by ZweZeya** [nus-cs2103-AY2425S1/forum#809]
![image](https://github.com/user-attachments/assets/5dc7efdc-0bbc-4d6f-b62a-cab70f1f878c)

Hi Prof, [previously](https://github.com/nus-cs2103-AY2425S1/forum/issues/599) you said that we are allowed to use pseudocode in our diagrams to omit the low-level implementation details so that it is easier for users to understand. May I ask if we can do so here too? We understand that conditional statements are done via the `opt` block but including this will expose additional low-level details such as exception-handling.

**Comment by damithc** [comment]
@ZweZeya While there is no rule against this type of pseudocode use, you still need to decide whether this is better than the other alternatives. For example, if you think omitting the more visual `opt` frame can mislead the reader or increase the risk of the reader missing an important information, it can still be considered as a defect.
