### ISSUE TITLE
How to handle bug from AB3 that only affects Mac OS 

### ISSUE THREAD

**Issue by zlch** [nus-cs2103-AY2425S1/forum#811]
A tester reported a bug for our product, because of the help command that has a chance to cause the addressBook to hang if the help window is opened while the addressBook is opened in fullScreen. However, based on testing on a MacBook it seems to affect all AB3 addressBooks. 

https://github.com/user-attachments/assets/ce7bf25f-b156-4ca0-8127-1ca089958adc

OpenJDK Runtime Environment Zulu17.50+19-CA (build 17.0.11+9-LTS)
OpenJDK 64-Bit Server VM Zulu17.50+19-CA (build 17.0.11+9-LTS, mixed mode, sharing)

It also seems to be a problem from previous semester: https://github.com/nus-cs2103-AY2324S2/pe-dev-response/issues/1126

Furthermore, this problem is impossible to test for if a person does not use a MacBook. We are also unsure if this is a problem with the AB3 or a problem with the MacBook OS and thus, are unsure of how to handle this.

**Comment by damithc** [comment]
@zlch Problems being specific to a certain OS can be used to lower the severity of a bug, depending on the popularity of the affected OS.

**Comment by zlch** [comment]
Would it be able to be classified as notInScope since fixing it requires a lot of effort/may not be possible if it is a problem with the OS.

**Comment by damithc** [comment]
> Would it be able to be classified as notInScope since fixing it requires a lot of effort/may not be possible if it is a problem with the OS.

You can try :-) If the tester agrees with you, no problem. But if the tester doesn't agree with you, the teaching team will have to compare your justification vs tester's justification and decide which has more merit.
