### ISSUE TITLE
Does severity of not in scope bugs matter?

### ISSUE THREAD

**Issue by SuhailLoya** [nus-cs2103-AY2425S1/forum#812]
The course website says
> Note that response.NotInScope bugs earn a small amount of credit for the tester without any penalty for the dev team, unless there is an unusually high number of such bugs for a team.

My question is from a tester's perspective, does the severity of not in scope bugs matter? For example, does a high severity not in scope bug earn more credit than a low severity not in scope bug?

**Comment by damithc** [comment]
> My question is from a tester's perspective, does the severity of not in scope bugs matter? For example, does a high severity not in scope bug earn more credit than a low severity not in scope bug?

@SuhailLoya Yes, it matters. And yes, higher severity earns more marks even for `response.NotInScope` bugs.

**Comment by SuhailLoya** [comment]
Thank you prof!
