### ISSUE TITLE
Does changing the severity of bug matter if we reject/NotInScope

### ISSUE THREAD

**Issue by zlch** [nus-cs2103-AY2425S1/forum#814]
Does changing the severity of a bug that we have rejected affect anything, for example if the tester disputes our position would us changing severity affect the choice of the teaching team? The same question for NotInScope.

**Comment by damithc** [comment]
@zlch In both cases, if your response was objected to by the tester and the teaching team agrees with the tester, the bug will be considered as `response.Accepted` and then the severity will affect the penalty for the bug. So, try to choose the correct severity (in your view) as much as possible.

**Comment by zlch** [comment]
I see so to my understanding the bugs severity is rated independently of whether it is accepted or rejected, but will changing severity affect the odds it is accepted or rejected?

**Comment by damithc** [comment]
> I see so to my understanding the bugs severity is rated independently of whether it is accepted or rejected, but will changing severity affect the odds it is accepted or rejected?

@zlch Yes, they are rated and decided independently. Testers get a separate input box for each aspect of the bug (type, severity, response, duplicate status), to submit their objections to each separately. 

In theory, they should not influence each other.
