### ISSUE TITLE
Exam resources

### ISSUE THREAD

**Issue by zaidansani** [nus-cs2103-AY2425S1/forum#816]
Hi prof, it was mentioned here #742 that the exam resources will be announced soon.

Is there an announcement out yet, and if not, when would this be? Asking so that we can plan our study schedule for the week.

Thanks!

**Comment by damithc** [comment]
@zaidansani It was announced earlier (see https://canvas.nus.edu.sg/courses/64945/discussion_topics/264501 )

**Comment by zaidansani** [comment]
Thanks prof, didn't notice this, must have blended in with the other announcements!
