### ISSUE TITLE
 Should similar bugs under planned enhancements be considered "NotInScope"?

### ISSUE THREAD

**Issue by verakohh** [nus-cs2103-AY2425S1/forum#817]
<img width="716" alt="image" src="https://github.com/user-attachments/assets/6d34bc17-c8c6-4bb8-8c7a-75198f15a131">

### **Context**:
- **Current Behavior**: Names containing substrings like `m/`, `a/`, or `e/` are misinterpreted as field prefixes, causing parsing errors.
- **Planned Enhancement**: The DG enhancement explicitly mentions fixing the issue for `m/`, but no similar mention exists for `a/` or `e/`.

### **Description**:

As shown in the screenshot above, our planned enhancements section in the DG explicitly states that the application will support names containing prefixes like `m/` as part of the name field (e.g., `n/John m/Doe`). This enhancement aims to prevent the parser from misinterpreting substrings like `m/` as the `major` prefix.

However, we have received **two related bug reports** regarding other prefixes (`a/` for address, `e/` for email) that are currently **not allowed in names**. These issues were not explicitly mentioned in the planned enhancements.

**Questions:**
1. Do these related issues qualify as part of the planned enhancement scope, given their similarity to the documented `m/` prefix enhancement since we think that they are duplicate bugs that can be fixed together at once?
2. Should we classify these issues as **"NotInScope"** or reject the bugs since they are mentioned in the planned enhancements section?

**Comment by damithc** [comment]
@verakohh As these are not specifically mentioned as planned enhancements, the tester is justified in recognising them as separate things. You should apply normal rules for determining if they are `NotInScope`. However, the reasons why you didn't implement support for `m/` in the current version can be used to justify not supporting other similar cases in the current version.

**Comment by verakohh** [comment]
@damithc okay thank you Prof Damith!
