### ISSUE TITLE
Practice exam answers

### ISSUE THREAD

**Issue by zaidansani** [nus-cs2103-AY2425S1/forum#818]
Hi prof, 

Wanted to check where do we find the practice exam answers? I can't seem to see it on Canvas -  only seeing answers for the mock exam.

![image](https://github.com/user-attachments/assets/1eb22e98-8cbf-449d-9b2b-2bd73e3b9f27)
![image](https://github.com/user-attachments/assets/2b0adf8c-1a83-403f-be06-cf559113e299)

**Comment by damithc** [comment]
@zaidansani Oops, seems like I forgot to upload them. Uploaded them just now.
