### ISSUE TITLE
Disagreeing on dev team's response (Accepted vs Not in Scope)

### ISSUE THREAD

**Issue by yxtan02** [nus-cs2103-AY2425S1/forum#819]
Let's say the dev team classified my bug report as Not in Scope but I believe that my bug report should be Accepted. If I decide to raise an objection but my objection is not accepted by the teaching team, will my accuracy marks be affected?

**Comment by Feng1231** [comment]
Yes.
![image](https://github.com/user-attachments/assets/5f884840-3ef5-49ea-a4c7-6d7b018c4329)

**Comment by damithc** [comment]
@yxtan02, as @Feng1231 said, it does.
