### ISSUE TITLE
Should ./data/[your_chat_bot_name].txt be committed?

### ISSUE THREAD

**Issue by SeeYangZhi** [nus-cs2103-AY2425S1/forum#82]
Should ./data/[your_chat_bot_name].txt be committed? or added to `.gitignore`

**Comment by damithc** [comment]
@SeeYangZhi No, it is a data file generated by your chat bot (not a source file) -- we typically don't version control _generated_ files. So, it should not be version tracked. Yes, it should be added to `.gitignore`.

**Comment by SeeYangZhi** [comment]
> @SeeYangZhi No, it is a data file generated by your chat bot (not a source file) -- we typically don't version control _generated_ files. So, it should not be version tracked. Yes, it should be added to `.gitignore`.

Thank you for the clarification, I will close this issue.
