### ISSUE TITLE
Is terminal/command prompt considered user facing

### ISSUE THREAD

**Issue by GabrielCWT** [nus-cs2103-AY2425S1/forum#820]
As the title asks, is terminal/command prompt considered user facing? Users are not expected to read through the logs for the app.

**Comment by damithc** [comment]
@GabrielCWT Here is our guideline on that:

<img width="764" alt="image" src="https://github.com/user-attachments/assets/4f1cdc5b-2d47-4d02-99e9-9e9aebc1c219">
