### ISSUE TITLE
Marks awarded for bug that is NotInScope

### ISSUE THREAD

**Issue by yxtan02** [nus-cs2103-AY2425S1/forum#822]
According to course website, a small amount of marks is awarded to bugs that is not in scope. I was wondering if the marks awarded for NotInScope bugs is lower/higher than an accepted severity VeryLow bug? This can help us to make a more informed decision if we should contest a NotInScope bug at the expense of potentially losing accuracy marks if the objection fails.

**Comment by damithc** [comment]
@yxtan02 `response.*` and `severity.*` are independent. You need to object to each separately. For example, if you submit a `severity.High` bug and the dev team chose `severity.Medium` + `response.NotInScope`, you can object to severity downgrade and the non-acceptance separately, and they will be decided (by the teaching team) independently. And each decision will affect the accuracy independently. So, I don't think you'll need to make the trade-off you alluded to in your question. 

Naturally, an `Accepted` bug of severity S earns more credit than a `NotInScope` bug of severity S.

**Comment by yxtan02** [comment]
Thanks for the quick response prof! So if a bug is considered as `NotInScope`, would its severity would still be taken into account? For example, a `severity.Medium` `NotInScopeBug` scores more marks than a `severity.Low` `NotInScopeBug`.

**Comment by damithc** [comment]
> Thanks for the quick response prof! So if a bug is considered as `NotInScope`, would its severity would still be taken into account? For example, a `severity.Medium` `NotInScopeBug` scores more marks than a `severity.Low` `NotInScopeBug`.

Yes, severity still matters.
