### ISSUE TITLE
I was given a duplicate to a bug that had high severity, but mine was medium

### ISSUE THREAD

**Issue by hooyushing** [nus-cs2103-AY2425S1/forum#824]
The team had placed mine as a duplicate. The team responded by downgrading the person's bug from severity.high to severity.medium. However, I had initially placed my bug as severity.medium. Do I raise this out during the next PE phase? I was just wondering as this would affect the accuracy score. This was the bug I was referring to: https://github.com/hooyushing/pe/issues/14

Thank you!

**Comment by damithc** [comment]
@hooyushing If you agree with the current severity rating, no action needed, and it will not lower your accuracy (because your initial severity rating is the same as the dev team's severity rating).

**Comment by hooyushing** [comment]
Thank you prof!
