### ISSUE TITLE
Clarification on planned enhancements

### ISSUE THREAD

**Issue by maertan** [nus-cs2103-AY2425S1/forum#825]
Hello Prof, may I clarify if functionality bugs would be granted immunity if listed in planned enhancements? In the course website, I could only find instructions to list feature flaws in planned enhancement. If a group listed a functionality bug (that could have been fixed in v1.6) under planned enhancements, could it still be considered a functionality bug?

<img width="677" alt="image" src="https://github.com/user-attachments/assets/5e90106c-98d0-4e8c-98ad-c56d57e5e7a4">

**Comment by damithc** [comment]
@maertan Depends on the bug. If it was considered a bug by the strict definition we used during the feature freeze, it should have been fixed (i.e., should not be listed in the _Planned Enhancements_ section).

**Comment by maertan** [comment]
Thank you Prof!
