### ISSUE TITLE
Can the dev team mark bugs that are known bugs as not in scope? 

### ISSUE THREAD

**Issue by annabellekk** [nus-cs2103-AY2425S1/forum#827]
Hi, in the textbook, it says that listing bugs as known bugs in the UG will not exempt those bugs from the final grading. That is, PE testers can still earn credit for reporting those bugs and the **dev team will still be penalized** for them. So if I have reported a bug that they mentioned under known bugs, can the dev team mark it as not in scope? Since this will contradict with what was mentioned for `response.NotInScope` - the **dev team will not be penalized**, but the bug reporter will earn a small amount of credit for reporting it. Would like to clarify on this matter, since I followed the textbook (screenshot given below) when deciding which bugs to send and which to keep, and sent this bug report with the belief that I can still receive credit for it despite it being listed as a known bug, but the team has marked it as not in scope, which will reduce the credits I receive. Therefore I want to check whether I should rebut their not in scope remark. 

<img width="1213" alt="Screenshot 2024-11-19 at 11 51 48 AM" src="https://github.com/user-attachments/assets/af297103-a981-4274-9ad3-8db75eaf4751">

**Comment by damithc** [comment]
@annabellekk Testers can still report such bugs (i.e., they are not immune from the PE) but the team can still mark them as `NotInScope` if they meets the criteria for `NotInScope` (i.e., not important enough to be done in the current version).

**Comment by annabellekk** [comment]
Hi Prof @damithc, in this case, if the response from the dev team was just something along the lines of "this issue was listed under known bugs" without justifying why they think it is not important enough to be done in the current version, can I reject the response not in scope remark? Further, I do think that this is a feature flaw that is important to implement since it is an issue on not allowing special characters in names when names are expected to match legal names that may have special characters in it.

**Comment by damithc** [comment]
> "this issue was listed under known bugs"

@annabellekk This is not a sufficient reason to categorise a bug as `NotInScope`, although it does act as circumstantial evidence i.e., they knew about the problem and chose not to fix it, possibly because they thought it is not important enough to fix it in the current version.

But yes, you can provided your own reasons for why the missing feature is important enough to be in the current version. If those reasons are convincing, it doesn't matter if it was listed as a known issue.

**Comment by annabellekk** [comment]
Noted, thank you prof
