### ISSUE TITLE
Gradle 

### ISSUE THREAD

**Issue by FYL2003** [nus-cs2103-AY2425S1/forum#83]
The current instruction for installing and add gradle in Wk3 notes seems to be in reversed order.

**Comment by damithc** [comment]
> The current instruction for installing and add gradle in Wk3 notes seems to be in reversed order.

@FYL2003 Can you give a bit more details?

**Comment by FYL2003** [comment]
I follow scenario 3 in SE-EDU then went back to follow scenario 2 then scenario 1. But now there are some unexpected behaviour. I can not run the programme normally in my duke chatbot file and have to run via gradle. (I done this before I start lvl7) Maybe the label should change to type-help.

**Comment by damithc** [comment]
While waiting for inputs from others, here are some things you can try, one-at-a-time in this order:
* Run `./gradlew clean build`
* Choose `File` -> `Invalidate caches`
* Close Intellij -> Delete the `.idea` folder -> Re open the project in Intellij
* Clone the fork to a different location and open the project in Intellij again to get a fresh start without losing changes you did so far.

**Comment by Jianwen0451** [comment]
When we try to do gradle init in a project. We receive the following message at our intellij
Select type of build to generate:
  1: Application
  2: Library
  3: Gradle plugin
  4: Basic (build structure only)
I have tried all 4 and none 1 and 4 and neither is working properly.
Can we get at least a hint how to construct proper gradle? 
Do we need to write the build.gradle by hand?

**Comment by damithc** [comment]
> When we try to do gradle init in a project. We receive the following message at our intellij
> Select type of build to generate:
> 1: Application
> 2: Library
> 3: Gradle plugin
> 4: Basic (build structure only)
> I have tried all 4 and none 1 and 4 and neither is working properly.
> Can we get at least a hint how to construct proper gradle?
> Do we need to write the build.gradle by hand?

@Jianwen0451 Did you merge the `add-gradle-support` branch and follow _scenario 2_, as stated below? 
![image](https://github.com/user-attachments/assets/ec12b348-5ea9-4013-99de-a36ee6b5c5aa)

**Comment by FYL2003** [comment]
update: after disable gradle plugin and mark ip directory as source root. My chatbot java file can run as normal(at beginning of Level7)

**Comment by damithc** [comment]
I've updated A-Gradle instructions,  to elaborate more on how to go about adding Gradle support.
