### ISSUE TITLE
Duplicate bug report flagged while severity suggestion is not relevant to my bug report

### ISSUE THREAD

**Issue by SamsonChew** [nus-cs2103-AY2425S1/forum#830]
I have a question about the tester response regarding a bug report marked as duplicate by the dev team while suggesting that they accept the bug but with severity.Low on another duplicated bug report. Given my bug report has been submitted as severity.Low during the previous phase, if I agree to mark this issue as a duplicate of another issue, will I not get awarded the accuracy point?  It seem like my original bug report is a response. Accepted from the dev team according to their response to the duplicated bug report.

**Comment by damithc** [comment]
@SamsonChew If your original severity level matches the bug's eventual severity, it increases your accuracy irrespective of whether the bug is a duplicate (provided the bug is `response.Accepted` or `response.NotInScope`)

**Comment by SamsonChew** [comment]
Thank you so much!!
