### ISSUE TITLE
How to respond to dev not able to reproduce a UI bug

### ISSUE THREAD

**Issue by Bonzzz3** [nus-cs2103-AY2425S1/forum#831]
I reported a bug of a team's app where most characters for result display and error message got cut-off. The team responded with bug cannot reproduce with reason being "This could be due to a formatting issue local to your PC" and provided some screenshots with no UI problem. However, I saw from GitHub there is another tester getting the same UI formatting issue for the same team. Should I disagree with their response since I provided valid steps and screenshots?

**Comment by damithc** [comment]
@Bonzzz3 Yes. You can also point to the other bug report as further evidence. You can try to reproduce the bug again and give screenshots as further evidence. If you think it is related to screen resolution or screen scaling setting, you can try to find which resolution/scale causes the problem -- this will increase your chances as the teaching team can use that info to reproduce the problem.

**Comment by Bonzzz3** [comment]
I see. Thanks prof!
