### ISSUE TITLE
What do I do if there is no reponse to one of my issues

### ISSUE THREAD

**Issue by FionaQY** [nus-cs2103-AY2425S1/forum#832]
For one of my bug reports, it says "Error in parsing Tester Response" and "No valid Tester Response was found. Please contact the teaching team for assistance.". Who do I contact about this?

**Comment by damithc** [comment]
@FionaQY This can happen if the bug trimming was not done fully (e.g., you kept more than 7 bugs open after bug trimming). If the bug in concern was one such bug (i.e., it was not meant to stay open after bug trimming), you can ignore it. Otherwise, email me the details of the bug.

**Comment by FionaQY** [comment]
got it thanks!
