### ISSUE TITLE
Are not in scope reports counted towards accuracy bonus marks?

### ISSUE THREAD

**Issue by annabellekk** [nus-cs2103-AY2425S1/forum#836]
Hello, can I check for the bonus marks, are bug reports marked as Response.NotInScope by the dev team considered "accepted as reported", and thus count towards the bonus marks? Or is this only referring to bugs that are explicitly accepted by the dev team?
<img width="800" alt="Screenshot 2024-11-19 at 1 35 09 PM" src="https://github.com/user-attachments/assets/33565278-79df-4f78-8726-8b5aebf6b217">

**Comment by damithc** [comment]
@annabellekk The following applies:
![image](https://github.com/user-attachments/assets/cfa8e50d-abba-4625-a150-a63cc63c490a)

**Comment by damithc** [comment]
@annabellekk An update:

![image](https://github.com/user-attachments/assets/010936f7-9317-4ba8-ba35-cd0b2363a967)

**Comment by annabellekk** [comment]
Noted, thank you prof!

**Comment by annabellekk** [comment]
Hi Prof @damithc, in this case, if I disagree with the dev team's response because I disagree that the bug is response.NotInScope or I don't think it is a duplication, but later on the teaching team decided that the response.NotInScope is valid, will this negatively affect the accuracy bonus? The severity of the issue is not affected at all (i.e. the dev team agreed with my severity chosen), just that I disagree with the response.NotInScope tag so I'm wondering if I should raise this up in case it might negatively affect the accuracy marks as opposed to just accepting it since the severity is correct.

**Comment by damithc** [comment]
@annabellekk even within one bug report, each objection and the effect on accuracy is independently judged/calculated, and is cumulative. Each objection will either increase or decrease your accuracy score, depending on whether the objection was accepted or rejected.

So, if the dev team agrees with your severity, it increases your accuracy already. If now you object to `NotInScope`, and if the teaching team agrees with you, your accuracy increases even more; but if the teaching team disagrees, the accuracy goes down. 
So, every 'hit' will increase your accuracy; every 'miss' will decrease it.

**Comment by annabellekk** [comment]
Noted, thank you for the clarification
