### ISSUE TITLE
Is the average user expected to read the developer's guide? In particular, the glossary?

### ISSUE THREAD

**Issue by shotnothing** [nus-cs2103-AY2425S1/forum#837]
Hi! If the glossary's definition (which is not the commonly understood english definition) of a word in the introduction paragraph of the user guide, is it considered a bug? Is the user expected to read the developer's guide (where the glossary is)?

**Comment by damithc** [comment]
> Is the user expected to read the developer's guide (where the glossary is)?

This part I can answer. And the answer is 'no'. :-)

**Comment by shotnothing** [comment]
Alright, thank you!
