### ISSUE TITLE
Disagree team's reject response

### ISSUE THREAD

**Issue by xqtann** [nus-cs2103-AY2425S1/forum#838]
Can I disagree with the team's decision to mark my reported bug as `response.Rejected`, when I think the more appropriate label should be `response.NotInScope`? Will that affect my accuracy in any way?

**Comment by damithc** [comment]
@xqtann Yes, you may. It is common for teams to use `response.Rejected` when they should have chosen `NotInScope` instead.
Your accuracy will improve if the teaching team agreed with your objection, but will go down if the decision goes the other way.
