### ISSUE TITLE
Severity of having typo when specifying filename for data modification

### ISSUE THREAD

**Issue by MAOXIONGKAI** [nus-cs2103-AY2425S1/forum#839]
Hi prof, I am currently reviewing the response of my evaluated team regarding an issue about data file naming typo.

Basically, the filename specified in the user guide is like this:
![image](https://github.com/user-attachments/assets/feb3b75e-2fe3-49ea-8a45-aae37aa4fe0f)

However, the actual name of the file produced is named `talent.json`, 
![3ebbba22-263c-48a4-bc62-fdcce428bcfa](https://github.com/user-attachments/assets/a1d85fba-a64c-4730-9a73-c459218bffb1)

The team has accepted my bug report but they think that this is a `severity.veryLow` bug because it is just a typo in the file name, I can understand their reason but I feel like this can be a `severity.Low` bug instead because this is a critical operation that may potential ruin the data that the app needs and cause irreversible harm to the system. Imagine if the user wants to directly modify the data but ends up getting confused because of the difference between document and the actual file name, then he/she may be hesitant about whether he/she should modify this file. Even though there's only one data file in the data folder, I think this level of confusion may still arise because user cannot assume that data folder contains only one data file and `talent.json` may be used for a different purpose as compared to `talenthub.json`, so that's why I think it should be `severity.Low`.

May I just check if the above explanation is reasonable? or I should just accept team's response and agree that this should be `severity.veryLow`? Thank you!

**Comment by damithc** [comment]
> May I just check if the above explanation is reasonable? or I should just accept team's response and agree that this should be `severity.veryLow`? Thank you!

@MAOXIONGKAI It's premature for me to comment on this, as this is a decision the teaching team will make in the next phase of the PE. For now, you'll have to exercise your own judgment and make a decision.

You can also refer to this when making the decision:

![image](https://github.com/user-attachments/assets/143a8623-8349-4944-8de5-c918511144d4)
