### ISSUE TITLE
Additional practice questions for part 2 (part (c) and (d))

### ISSUE THREAD

**Issue by dominopizzaaaa** [nus-cs2103-AY2425S1/forum#841]
Hi! This is my diagram for Additional practice questions for part 2 (part (c) and (d)):

![IMG_38C8E01ACD99-1](https://github.com/user-attachments/assets/dd6442c0-71ee-48e9-a9a6-5c95dd7cb08c)

Is there anything incorrect, or do any parts need changes or improvements?

**Comment by emmannyyy** [comment]
I got this for (c) 

![image](https://github.com/user-attachments/assets/50629672-6d47-4609-9a71-d04f28efe160)

**Comment by Dominic-Khoo** [comment]
> I got this for (c)
> 
> ![image](https://private-user-images.githubusercontent.com/122295421/388858125-50629672-6d47-4609-9a71-d04f28efe160.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNjM3NTQsIm5iZiI6MTczMjI2MzQ1NCwicGF0aCI6Ii8xMjIyOTU0MjEvMzg4ODU4MTI1LTUwNjI5NjcyLTZkNDctNDYwOS05YTcxLWQwNGYyOGVmZTE2MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMlQwODE3MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYTY1OGI2ZmI4YjhlNWM5OTAxMmRjZWI4MTRkYzBlZDY1ZWM0YjhmODY0MWYwYjE2NmQ5ODM1MjczYWIyNjNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ptzoyNI_WsCwMRZP5XIKQ2MfMWXOWcYj2Lyra_zAjzo)

I got basically the exact same answer, except that I noticed that increase(1) might've accidentally been drawn twice instead of once

**Comment by emmannyyy** [comment]
I think I got the same for (d)! 
![image](https://github.com/user-attachments/assets/fa535003-f804-4b3e-9133-bd802426eb90)

**Comment by emmannyyy** [comment]
@Dominic-Khoo oh yes. my bad! thanks for catching that!

**Comment by Incogdino** [comment]
> @Dominic-Khoo oh yes. my bad! thanks for catching that!

Hi are you referring to the extra increase() for the creater() function call? The image does not seem to be loading for me.

**Comment by juancarlovieri** [comment]
> > @Dominic-Khoo oh yes. my bad! thanks for catching that!
> 
> Hi are you referring to the extra increase() for the creater() function call? The image does not seem to be loading for me.

The problem was that they had two increase(1) function calls. It should be just one.

**Comment by damithc** [comment]
Related #878

**Comment by vinceg4** [comment]
For the sequence diagram, i was thinking if it was possible if the status does not match any of the two cases and since there is no default statement, the code just executes to f.pad() straight away.

Edit: nvm forgot alt can also mean none of it executes
