### ISSUE TITLE
Arguing for response.accepted instead of response.notinscope

### ISSUE THREAD

**Issue by jktang14** [nus-cs2103-AY2425S1/forum#851]
Just to clarify, if the team has assigned response.notinscope to a bug, are we allowed to argue that the bug is major enough to disqualify it from being notinscope and should be accepted instead?

**Comment by damithc** [comment]
@jktang14 Yes, you can. Recommended to consider costs and benefits though: if you object to `NotInScope` and the teaching team doesn't agree with your objection, it will lower your accuracy marks. But if you succeed, it will increase your marks, as an accepted bug earns more marks than a NotInScope bug.

**Comment by jktang14** [comment]
Will do. Thanks prof.
