### ISSUE TITLE
Clarification about duplicate issues

### ISSUE THREAD

**Issue by Justin-Aw46** [nus-cs2103-AY2425S1/forum#852]
<img width="674" alt="Screenshot 2024-11-19 at 4 54 37 PM" src="https://github.com/user-attachments/assets/a4d0bfd8-3866-413e-8e2e-d886cc3ea1d0">

Regarding this section where it states "Multiple buggy behaviors that are actually caused by the same defect and cannot be fixed independently (i.e., fixing one fixes the others automatically)." can I take this to mean that if the same line of code is responsible for the bug only then it would be considered duplicate issue? Otherwise if it is code in 2 separate locations then it would not be a duplicate.

An example would be like if for 2 commands they have an error with parsing a certain command. Would reporting the bug as 2 separate issues for each command be valid since I am assuming that the issue is due to errors in different parts of code?

**Comment by damithc** [comment]
> An example would be like if for 2 commands they have an error with parsing a certain command. Would reporting the bug as 2 separate issues for each command be valid since I am assuming that the issue is due to errors in different parts of code?

@Justin-Aw46 There is a chance that it's the same bug. For example, the parser could be using the same method to parse that part of the command, for both commands.

**Comment by Justin-Aw46** [comment]
Ok thanks for the clarification Prof
