### ISSUE TITLE
Clarification between the typo and inconsistent command instruction

### ISSUE THREAD

**Issue by Elinengu** [nus-cs2103-AY2425S1/forum#853]
If the command provided in the user guide is ``[n/NAME_KEYWORDS]`` ``[A/ADDRESS_KEYWORDS]``, but the meaning of ``KEYWORDS`` is not mentioned in the user guide (particularly missing in the command format section), and the error message for the command is ``[n/NAME_KEYWORD...]`` ``[a/ADDRESS_KEYWORD...]``, where the meaning of the ``...`` is clearly explained in the user guide, should this be classified as a typo? I believe that the section in the user guide may hinder the user’s understanding on the first use. However, after reading it carefully several times and trying it with the app, the behavior of the feature becomes clear to the user. Especially the examples provided in the user guide hints the behaviour of the feature. And they provided a sentence like: ``You can find students whose names, addresses, tags or lessons contain any of the given keywords.``

That being said, as a tester, I feel like it's confusing when I was testing the product before, but they did try to mention it in the user guide.

**Comment by damithc** [comment]
@Elinengu It's good to discuss this here and get opinions of the other. But the final decision is yours -- as the decision is part of the deliverable (and affects your grade), the teaching team will not be able to give a definitive answer at this stage of the PE.
