### ISSUE TITLE
[Practice Paper] Why is the constructor not shown in this partial sequence diagram? [p3.07]

### ISSUE THREAD

**Issue by anselmlong** [nus-cs2103-AY2425S1/forum#854]
![image](https://github.com/user-attachments/assets/bcb751a0-e061-4c97-b555-3b670c0f76f0)

Hi all, for those that have done the Mock Examplify Paper, I would like to ask why is option D not correct - due to the presence of the constructor bar, and A is correct instead. Does the position of the lifelines take precedence over the constructor bar?

**Comment by damithc** [comment]
@anselmlong while waiting for others' inputs, can you share your observations about Examplify search feature in [this thread](https://github.com/nus-cs2103-AY2425S1/forum/issues/815#issuecomment-2485476548)?

**Comment by anselmlong** [comment]
> @anselmlong while waiting for others' inputs, can you share your observations about Examplify search feature in [this thread](https://github.com/nus-cs2103-AY2425S1/forum/issues/815#issuecomment-2485476548)?

Sure, done! It also doesn't work for me.

**Comment by minhao23** [comment]
Hi Anselm, activation bars (the constructor is an activation bar too) can be omitted if there are no ambiguities.

**Comment by anselmlong** [comment]
Thanks @minhao23 ! Got it.

**Comment by damithc** [comment]
> Hi Anselm, activation bars (the constructor is an activation bar too) can be omitted if there are no ambiguities.

Yes, that's correct. Thanks @minhao23
