### ISSUE TITLE
Functionality Bug vs Feature Flaw

### ISSUE THREAD

**Issue by yongkheehou** [nus-cs2103-AY2425S1/forum#855]
if an invalid index e.g. `-1` is passed into a command and the error states "Invalid command format!", but the **Developer Guide** (not the User Guide) states that "an error message that the index is out of range" should be shown, should it be more of a feature flaw or functionality bug?

According to the course website, app behavior differing from the UG (in this case, the behavior differed from the specification in the DG's use case) is considered a functionality bug. Is it also then a functionality bug if the app behavior differs from what's specified in the DG?
<img width="710" alt="Screenshot 2024-11-20 at 12 21 01 AM" src="https://github.com/user-attachments/assets/357e12ff-8f13-427e-b7b6-555d05bb8506">

But, at the same time, the website also states that "Calling an invalid value a 'format error' and vice versa is a severity.Low bug" under the list of example feature flaws:
<img width="655" alt="Screenshot 2024-11-20 at 12 19 42 AM" src="https://github.com/user-attachments/assets/7780aa46-d7a3-4e30-85b5-f1b02082da8f">

The definition for wrong error message seems to overlap between feature flaw and functionality bug, so I'd like to clarify how this bug should be categorized. Thanks!

**Comment by damithc** [comment]
@yongkheehou To the tester, the bug type doesn't matter. We will not be using `type.*` label when calculating accuracy.
