### ISSUE TITLE
Unsure of how to retrieve a copy of my attempts of the practice exam

### ISSUE THREAD

**Issue by ITZXITZX** [nus-cs2103-AY2425S1/forum#857]
Hi, does anyone know how we will be able to retrieve a copy of our attempts of the practice exam? Was hoping to compare my answers with the solutions provided.

**Comment by damithc** [comment]
@ITZXITZX I think you can see the results by going to examsoft.com 
Let us know if that works.

**Comment by ITZXITZX** [comment]
Hi Prof, thanks for the info, it works and I'm able to download the results. However, I cannot see the original question, which is perhaps a limitation of examsoft
