### ISSUE TITLE
Question about the practice exam part 1 [p1.05]

### ISSUE THREAD

**Issue by ITZXITZX** [nus-cs2103-AY2425S1/forum#858]
Hi,  I have 2 questions regarding this question.

![image](https://github.com/user-attachments/assets/711d0ed8-4095-4234-b31a-07febb00b2fc)

1) In the diagram given in the question, does the diagram have an error? I thought that the process() method should be labelled as {abstract}, as seen in the text book

![image](https://github.com/user-attachments/assets/dda0d2b8-f921-4783-adb8-05252e41e62b)

2) Does anyone know why option 4 is the correct answer but not option 2? My initial reasoning for selecting option 2 is because `process()` is the only method in the abstract class `Foo`, so I assumed that `process()` is an abstract method. So if there is a solid arrow from `Bar` to `Foo`, it means that `Bar` inherits from `Foo`, and could possibly have an implementation of the abstract method `process()`. So it would cause a compile error.

On the other hand, option 4 seems to be a valid statement (incorrect answer), just like how an object can be of type List but implements and Arraylist?

**Comment by ghos7ie** [comment]
I can comment on the abstract one. I believe newer versions of Java allow for default implementations of abstract methods, iirc from CS2030S but I'm not sure if Java 17 supports that


I might be wrong tho, haven't started revising yet :')

**Comment by anselmlong** [comment]
If I recall correctly, inheriting from an abstract class means that the `Bar` class already has the default implementation of the `process()` method, so there is no need for `Bar` to have a `process()` method in the class. Having a `process()` method there means `Bar` is overriding the implementation in `Foo`, but taking it out means it uses the default implementation from `Foo`. Hence, taking it out will not cause a compile error, as stated in option 2.

Option 4 is a ~valid~ invalid statement as you said, as how `List<String> list = new ArrayList();` works.

**Comment by ITZXITZX** [comment]
@anselmlong 

Thanks for the clarification! However, option 4 is supposed to be invalid /the answer to this question

**Comment by anselmlong** [comment]
Oh my bad! Yup an invalid statement, i.e. the answer!

**Comment by ITZXITZX** [comment]
I still don't quite understand why is it an invalid statement though, since its `Bar` has overridden ~Foo` and implemented `process()`

**Comment by anselmlong** [comment]
Oh as in - the statement says that the code causes a compile error. The fact is, it does not. Hence, the statement is invalid.
`Bar` has overridden `Foo`, so `Foo foo = new Bar();` will **not** cause a compilation error.

**Comment by ITZXITZX** [comment]
I see, thank you! @anselmlong
