### ISSUE TITLE
Strictness of uml diagram

### ISSUE THREAD

**Issue by minhao23** [nus-cs2103-AY2425S1/forum#859]
Hi profs, I would like to clarify how strict is the marking for UML diagrams? If I were to identify a connection between 2 objects as merely an association, but the correct answer is composition, will I get marked down?

![image](https://github.com/user-attachments/assets/bbc8370a-8c5d-4944-a33c-5f06c81e379d)

**Comment by damithc** [comment]
@minhao23 In the exam, if composition symbol is expected in the answer, there will be a strong hint in the question e.g., `X is composed of Y`.
