### ISSUE TITLE
Practice exam ProgressWatcher in UML diagram why have no update method

### ISSUE THREAD

**Issue by tayxuenye** [nus-cs2103-AY2425S1/forum#860]
![image](https://github.com/user-attachments/assets/85b2c399-cf46-4b85-bf51-eaf46ef69dc7)
![Screenshot 2024-11-20 125336](https://github.com/user-attachments/assets/16b3af64-1c31-4b36-9da8-4e3613ae1c1d)
Why is it that the ProgressWatcher class does not have an update method in the diagram even though it implements Watcher class?

**Comment by wes-w-z-h** [comment]
The code snippet does not show the `ProgressWatcher` class having a concrete implementation for the `update` method and since it is an abstract class this is allowed and only classes which extends the abstract class need to provide a concrete implementation.

**Comment by tayxuenye** [comment]
Thank you
