### ISSUE TITLE
Is it possible to appeal for NotInScope if my bug is Rejected by the team?

### ISSUE THREAD

**Issue by kimxw** [nus-cs2103-AY2425S1/forum#862]
One of my bugs was rejected, however after reading the reasoning I wanted to suggest that it's NotInScope isntead. Is this something I can do? or can I only defend my inital PE position?

**Comment by damithc** [comment]
@kimxw Yes, you can do that. Similar to the below:

![image](https://github.com/user-attachments/assets/02ce7ca5-b499-4c4e-ab2f-2ee6e4bf7d26)

**Comment by kimxw** [comment]
Got it. Thanks prof!
