### ISSUE TITLE
Confused about this question in the textbook regarding class-level members

### ISSUE THREAD

**Issue by RezwanAhmed123** [nus-cs2103-AY2425S1/forum#863]
![image](https://github.com/user-attachments/assets/817813b7-27c4-4c10-9826-6b2abce5a09f)

Regarding this question, the only answer is (c), however, I am confused why (a) is also not considered. The totalScore should not be handled by the player object itself but im struggling to see why the Player CLASS itself cannot be modified to handle the total score for all the players. Unless this total score refers to the player only and not all players together?

**Comment by Anvita2110** [comment]
@RezwanAhmed123 , 
As per my understanding, the totalScore refers to that particular player only not for the players all together, hence it would vary from player to player. 
totalScore being the total score of an individual player(state of a specific object instance), it is better managed at instance level therefore, it cannot be a class level member.

@damithc Correct this if I am wrong.

**Comment by JoanneHing** [comment]
I think @Anvita2110 understanding is correct. Because the system is for a multiplayer Pacman game, different player will carry different score to be compared, and I think this is why `totalScore` should be a instance variable for each different `Player` instantiated.

**Comment by RezwanAhmed123** [comment]
Understood, thanks guys!

**Comment by damithc** [comment]
Yup, the reason given by @Anvita2110 and @JoanneHing is correct.
