### ISSUE TITLE
Need help with sequence diagram, if anyone has tried this question

### ISSUE THREAD

**Issue by Anvita2110** [nus-cs2103-AY2425S1/forum#864]
### Can anyone send screenshot on how the answer should look like if they have tried this before, so that I can match mine?

![Screenshot 2024-11-20 205216](https://github.com/user-attachments/assets/ff1ce757-993f-4ed4-a40b-e4055a681ce7)

---

Hint provided:

![image](https://github.com/user-attachments/assets/773d34fc-22bf-4595-beec-9dc9636dae43)

**Comment by xqtann** [comment]
![image](https://github.com/user-attachments/assets/bb6494c3-05ca-4f10-bb84-5728971fb90e)
The answer is provided in one of the exercise videos in [week 8 topics](https://nus-cs2103-ay2425s1.github.io/website/schedule/week8/topics.html)!

**Comment by JoanneHing** [comment]
<img src="https://github.com/user-attachments/assets/d3d16255-116f-4ac5-8564-8f0a572b5441" alt="alt text" width="500">

This the sequence diagram I drew, I included the `delete` after the `Quote` object is no longer used, but i think it is optional to include that

**Comment by Anvita2110** [comment]
Thank you @xqtann @JoanneHing

**Comment by damithc** [comment]
Tip: Try to match arrow entry points to start/end point of the activation bar (as shown below), as methods calls and returns coincide with the exact time a method gains control or releases control.

![image](https://github.com/user-attachments/assets/71bf8bd0-25e0-4ea1-b11b-4ca7b0bb6e2c)
