### ISSUE TITLE
Examplify PDF testing

### ISSUE THREAD

**Issue by vinceg4** [nus-cs2103-AY2425S1/forum#865]
I saw that there is an exam paper for PDF file testing, are we supposed to access that (not sure if we have the password)? Did not see the course briefing video mention this (only the mock and practice paper)

**Comment by damithc** [comment]
@vinceg4 It was created for troubleshooting purposes, as some students are facing issues using the attached PDF file in the mock exam. See #815 for more info.
If you didn't face issues accessing or searching the attached PDF file in the normal mock exam, you can ignore the `CS2103T AY2425S1 for PDF Testing` one.

**Comment by vinceg4** [comment]
@damithc okay thank you!
