### ISSUE TITLE
Revise initial bug type

### ISSUE THREAD

**Issue by yxtan02** [nus-cs2103-AY2425S1/forum#866]
Let's say I originally classified the bug as a `Functionality` bug but the team reclassified it as a `Documentation` bug. Upon review, I feel that my bug should be classified a `FeatureFlaw`. Should I respond to team's type classification? Will there be any impact on the tester's accuracy marks?

**Comment by damithc** [comment]
@yxtan02 This time, we will not consider the bug type when calculating accuracy marks. So, there is no need to object to the bug type changes.
