### ISSUE TITLE
Is hardcopy notes allowed?

### ISSUE THREAD

**Issue by Feng1231** [nus-cs2103-AY2425S1/forum#867]
I might want to print out some of the notes for easier reference. (e.g. UML reference sheet and CS2103T summary Infographics, Java coding standards)
Is that allowed?

**Comment by JoanneHing** [comment]
<img width="807" alt="Screenshot 2024-11-21 at 3 10 36 PM" src="https://github.com/user-attachments/assets/974eb118-d4d4-4d64-8977-33a21bbf91e3">

Yep it is allowed, as provided [here](https://nus-cs2103-ay2425s1.github.io/website/admin/exams.html)

**Comment by Feng1231** [comment]
@JoanneHing Thanks Joanne!
