### ISSUE TITLE
Question regarding Practice Exam Part 3 [p3.02]

### ISSUE THREAD

**Issue by Dominic-Khoo** [nus-cs2103-AY2425S1/forum#871]
<img width="800" alt="Screenshot 2024-11-22 at 3 43 26 PM" src="https://github.com/user-attachments/assets/9f67df5b-efba-4226-815f-07ef51a55c2e">

Just wanted to check, isn't option B also flawed? I understand the package private modifier, but considering that they are operations and not attributes, shouldn't there also be a blank box above it (e.g like in Option A except that option A has the wrong visibility)

**Comment by Gra7ityIC3** [comment]
> shouldn't there also be a blank box above it

The attributes compartment can be omitted as seen in Class E below:

![image](https://github.com/user-attachments/assets/02f7add8-630b-427b-88f8-d3415aa9a276)

**Comment by damithc** [comment]
Thanks @Gra7ityIC3, for the correct explanation.
@Dominic-Khoo It's OK to omit the empty attributes box as it doesn't cause any ambiguity i.e., we can see from the contents the box shown is the methods box.
