### ISSUE TITLE
Unable to access Examplify Mock Paper

### ISSUE THREAD

**Issue by Professional-Procrastinat0r** [nus-cs2103-AY2425S1/forum#874]
Hi Prof,

I keep getting shown this screen when I try to access the Mock paper on Examplify. I have already tried deleting and redownloading this exam.

Any help is appreciated. Thanks!

![image](https://github.com/user-attachments/assets/4a0af9f2-d7f6-448f-8b02-247d79b8dc7b)

**Comment by damithc** [comment]
@Professional-Procrastinat0r Is this the one named `CS2103T AY2425S1 Mock Exam (V3)` (note the `(V3)` at the end). That's the one you should try. The other versions are outdated.

**Comment by Professional-Procrastinat0r** [comment]
@damithc Hi prof, yup this is the exam I could not access on Examplify

**Comment by damithc** [comment]
@Professional-Procrastinat0r Some other students have uploaded answers to the mock exam since you posted this message, which means the problem may be specific to your account. I suggest contacting `citbox25@nus.edu.sg` for NUS CIT help.

**Comment by juancarlovieri** [comment]
I only get this error when I try to redo the exam.

**Comment by damithc** [comment]
@juancarlovieri Did you download again before attempting to redo? I think every attempt needs a fresh download of the exam file.

**Comment by juancarlovieri** [comment]
> @juancarlovieri Did you download again before attempting to redo? I think every attempt needs a fresh download of the exam file.

Yes I redownloaded the exam before re-attempting but the error message still appears. It says that I have attempted the exam before and need a resume code.

**Comment by damithc** [comment]
> Yes I redownloaded the exam before re-attempting but the error message still appears. It says that I have attempted the exam before and need a resume code.

@juancarlovieri hmm... I checked again just now. All mock and practice exam parts are set to allow up to 10 attempts. You might need to check with CIT about this.

You can also try the resume code `FA50B0` to see if that helps.

**Comment by Professional-Procrastinat0r** [comment]
This works. Thanks prof!
