### ISSUE TITLE
Is using Text Book on CS2103T website allowed in the exam?

### ISSUE THREAD

**Issue by blackpanther9229** [nus-cs2103-AY2425S1/forum#876]
I have just tried the partial lock-down mode for Examplify and it seems that we can access the online text book if we already open it before entering the exam mode. I wonder if this is allowed. Thanks.

**Comment by damithc** [comment]
@blackpanther9229 Examplify simply blocks Internet; so, web pages already loaded into a Browser will remain but you won't be able to navigate to other pages. So, that behaviour is expected.
Is it allowed? No. You are not allowed to have any other file or application open while doing the exam (except opening the Exam-reference.pdf in Acrobat Reader).

**Comment by blackpanther9229** [comment]
> @blackpanther9229 Examplify simply blocks Internet; so, web pages already loaded into a Browser will remain but you won't be able to navigate to other pages. So, that behaviour is expected. Is it allowed? No. You are not allowed to have any other file or application open while doing the exam.
Thank you Prof!
