### ISSUE TITLE
Question About Practice Exam Q2 Attachments

### ISSUE THREAD

**Issue by woke02** [nus-cs2103-AY2425S1/forum#877]
Hi Prof @damithc,

Could I check where to find the attachments for Q2 of the practice exam after finishing the exam

Thank you!

**Comment by Incogdino** [comment]
I believe it is in the handouts folder on canvas. Have attached it here for you convenience:
[Practice exam - part 2 (answers).pdf](https://github.com/user-attachments/files/17872766/Practice.exam.-.part.2.answers.pdf)

**Comment by woke02** [comment]
Thanks @Incogdino, I am looking for the question, I can't seem to find on canvas

**Comment by damithc** [comment]
@woke02 I uploaded it just now. Thanks for the alert.
