### ISSUE TITLE
Slow search result for keywords such as 'n-tier' 'client-server architectural style'

### ISSUE THREAD

**Issue by annabellekk** [nus-cs2103-AY2425S1/forum#879]
I am using Adobe acrobat reader and have downloaded the latest textbook reference from canvas. I noticed that when I'm searching for keywords such as 'n-tier' or 'client-server architectural style', it takes very long to load the results (more than 3 minutes, and I cancelled the search after so I'm not sure how long it actually takes). But this does not happen if I search for other keywords such as 'sequence diagrams'. May I ask if there are ways I can mitigate this issue so that the search is more efficient when taking the final exam?

**Comment by damithc** [comment]
@annabellekk 
1. Which OS? 
2. Do you experience the same problem when searching the textbook.pdf?

On my computer (Mac M3, Sequoia, Acrobat), I do not see any noticeable lag when searching for the key words you mentioned.

However, I noticed that it says 'no results found' unless I hit enter, after which it shows the actual search results. 

![image](https://github.com/user-attachments/assets/033f1952-75ab-4f95-b456-63f0d3bdc5f0)

So, try hitting the enter button immediately after typing the keyword to see if that helps.

**Comment by annabellekk** [comment]
Hi Prof @damithc I'm on Mac os M3, and the same thing happens when searching textbook.pdf as well. But hitting enter immediately does show the results more quickly. Thank you!
<img width="1032" alt="Screenshot 2024-11-23 at 1 18 59 PM" src="https://github.com/user-attachments/assets/d9a537fc-46b1-46bf-904a-cf04146a14a4">
