### ISSUE TITLE
On using wildcardimports

### ISSUE THREAD

**Issue by Vangmay** [nus-cs2103-AY2425S1/forum#88]
Here is a snippet of my code, from the sub-package command, I am using all the classes as they contain all the commands. I wanted to ask if this is a valid reason to use a wildcard? Or should I individually export all the classes? 

```java
package michaelscott.parser;

import michaelscott.command.*;
import michaelscott.exception.MichaelScottException;

public class Parser {
    public Command parse(String fullCommand) throws MichaelScottException {
        String[] parts = fullCommand.split(" ", 2);
        String command = parts[0];
        String args = parts.length > 1 ? parts[1] : "";

//        MichaelScott.task.Todo think enums
        return switch (command.toLowerCase()) {
            case "list" -> new ListCommand();
            case "bye" -> new ExitCommand();
            case "mark" -> new MarkCommand(args);
            case "unmark" -> new UnmarkCommand(args);
            case "delete" -> new DeleteCommand(args);
            case "todo" -> new TodoCommand(args);
            case "deadline" -> new DeadlineCommand(args);
            case "event" -> new EventCommand(args);
            case "clear" -> new ClearlistCommand();
            default -> throw new MichaelScottException("I don't understand what you mean to say!");
        };
    }
}

```

**Comment by miloaisdino** [comment]
Hey i believe this could lead to namespace pollution. Perhaps reference the package methods by typing michaelscott.xx.yy is cleaner!

**Comment by damithc** [comment]
@Vangmay Our coding standard does not say 'OK to use wildcard if there are more than N classes from the same package'. So, you need to improve each of them explicitly.
Also, having to import many classes from the same package could be a sign that the target class might be better of being moved to that package, as it seems to be interacting with many classes in the other package.

**Comment by Vangmay** [comment]
Thanks professor, I'll do that
