### ISSUE TITLE
Can we see the question of part 2 when doing part 3?

### ISSUE THREAD

**Issue by jian7490** [nus-cs2103-AY2425S1/forum#880]
Hi, profs and friends. I just tried with the practice exam. In part 3, some questions are based on the part 2 question. I wonder whether it is allowed to access the pdf attachment of part 2 when doing part 3. I forgot to try it out, so anyone who has done it and tried it can help me with this doubt? Thanks.

**Comment by damithc** [comment]
@jian7490 Yes, the part 2 question is available as a pdf attachment in part 3 exam.

**Comment by jian7490** [comment]
> @jian7490 Yes, the part 2 question is available as a pdf attachment in part 3 exam.

Thank you prof!
