### ISSUE TITLE
Order of Object Creation in Sequence Diagram

### ISSUE THREAD

**Issue by jagdeepsh** [nus-cs2103-AY2425S1/forum#883]
Referencing the attached photo, if option `c` states that `dog` object **needs** to be created first, how come option `b` was accepted, despite `dog` being created after the `Man` object?

<img width="907" alt="Screenshot 2024-11-23 at 4 58 32 PM" src="https://github.com/user-attachments/assets/411557fa-28c0-42f1-a893-e35db33702ea">

**Comment by gohsl99** [comment]
I think you misinterpret the answer. The answer is saying the Dog object needs to be created first **before passing to the set method**. It does not mean Dog object needs to be created first **before Man object**.

**Comment by jagdeepsh** [comment]
I see, I understand now, thanks for clarifying :)

**Comment by damithc** [comment]
@gohsl99 Thanks for the useful input.

To add, `b` and `c` are equivalent, given activation bars are optional, return arrows are optional, and the horizontal order of entities does not matter (i.e., it doesn't matter if`Dog` is on the left of or on the right of `Man`).
