### ISSUE TITLE
Grading of final exams Part 1

### ISSUE THREAD

**Issue by annabellekk** [nus-cs2103-AY2425S1/forum#884]
Hello Prof, can I check for the finals part 1, how are the 'answer 2' sections graded? i.e. the one where we need to elaborate on our choice. Must our answers contain certain key concepts to be considered correct? Or as long as we can explain our rationale in selecting that option then it is accepted. And are the marks counted separately from the answer 1 choice? e.g. if I chose the correct answer but for a different reason than what is on the answer scheme will I get partial marks? 

And secondly, do the multiple response questions have partial marks or we'll only get the marks if we select all the correct options. 

Thank you.

**Comment by damithc** [comment]
> Hello Prof, can I check for the finals part 1, how are the 'answer 2' sections graded? i.e. the one where we need to elaborate on our choice. Must our answers contain certain key concepts to be considered correct? Or as long as we can explain our rationale in selecting that option then it is accepted. And are the marks counted separately from the answer 1 choice? e.g. if I chose the correct answer but for a different reason than what is on the answer scheme will I get partial marks?

@annabellekk the follow up question is used to verify that you chose the MCQ answer for the correct reasons. If the answer is missing, incorrect, or is not enough to show the correct understanding, it will lower the total marks for the question.


> And secondly, do the multiple response questions have partial marks or we'll only get the marks if we select all the correct options.

There is partial marks. If the answer is only off-by-one (i.e., mismatched by only one checkbox), you get half the marks.

**Comment by annabellekk** [comment]
Thank you prof!
