### ISSUE TITLE
Path Coverage for loops

### ISSUE THREAD

**Issue by seah-minlong** [nus-cs2103-AY2425S1/forum#886]
Just to clarify, when it is said that a loop can increase path coverage greatly, it is not really due to the loop itself but the fact that `names` can be of variable length right?

![image](https://github.com/user-attachments/assets/79523753-deff-45a1-aa94-e393ee3a283d)

For instance, a fixed loop would only have 1 path. Is that correct?
``` Java
void foo (String s) {
  for (int i = 0; i < 10; i++) {
    print("Hello World");
  }
}
```

**Comment by gohsl99** [comment]
For your example, I think there is only one path because the for loop will iterate 10 times regardless.

**Comment by DennieDan** [comment]
Yes, I think you are right.

![image](https://github.com/user-attachments/assets/8c74155e-6233-490d-98ed-add564b985b7)


As per this example, I believe we need Integer.MAX_VALUE + 1 test cases:
- 1 test case for empty list of strings (length = 0)
- others are for lists of length from 1 to Integer.MAX_VALUE

**Comment by damithc** [comment]
@seah-minlong

> Just to clarify, when it is said that a loop can increase path coverage greatly, it is not really due to the loop itself but the fact that `names` can be of variable length right?

 Yes, specifically, a loop with a loop count that is not pre-determined.

> For instance, a fixed loop would only have 1 path. Is that correct?

Yes, correct.

@DennieDan The image is missing in your comment.

> For your example, I think there is only one path because the for loop will iterate 10 times regardless.

@gohsl99 Correct.

**Comment by seah-minlong** [comment]
Okay thank you prof!

**Comment by DennieDan** [comment]
@damithc I updated my image, it is actually the example given by @seah-minlong
