### ISSUE TITLE
[Practice Paper Part 3] There seems to be a mismatch between A1 and A2 in p3.15.

### ISSUE THREAD

**Issue by CYX22222003** [nus-cs2103-AY2425S1/forum#887]
<img width="350" alt="image" src="https://github.com/user-attachments/assets/7e5bc350-d177-4f39-b80a-9d365b198104">

The A2 seems to suggest the use of CCDs, but the answer in A1 is Class diagram instead. I am a bit confused by the answer key.

**Comment by gohsl99** [comment]
The original question is asking `which one will you leave out?`. Therefore, the answer is to leave out `class diagram` (A1) because `we should use CCDs instead of class diagram` (A2).

**Comment by CYX22222003** [comment]
Oh, I misread the question. Thank you for the clarification.
