### ISSUE TITLE
Practice Exam Part 2: How to make essay box disappear?

### ISSUE THREAD

**Issue by AbdulrahmanAlRammah** [nus-cs2103-AY2425S1/forum#888]
The essay box makes it very hard to read the question as it takes up the majority of the screen, but is not needed. How can I make it go away?

![image](https://github.com/user-attachments/assets/df83ced6-5d98-4439-9764-b8d9847f40ff)

**Comment by damithc** [comment]
@AbdulrahmanAlRammah hmm... is this the maximum size your Examplify Window can get to? perhaps make the Windows tool bar auto-hide? Or tweak resolution or scaling of your display?

![image](https://github.com/user-attachments/assets/c65d2e62-ad0d-4c25-944e-87b2b25563b4)

The textbox can be resized by dragging the `...` at the top of it, but there is a limit to how much smaller you can make it. Examplify UI is quite poorly designed, unfortunately :-(

**Comment by AbdulrahmanAlRammah** [comment]
@damithc Yes unfortunately this is the smallest I could make the textbox by dragging. I would suggest attaching a PDF version of the question for the 2nd part (just like it was there for the third). The pdf takes up the whole screen and is easier to read.

**Comment by damithc** [comment]
@AbdulrahmanAlRammah The exam is set passed to CIT to already. Let me see if they will allow me to change it now.

**Comment by damithc** [comment]
@AbdulrahmanAlRammah In the final exam part 2, I've added the question as a PDF file as well.

**Comment by AbdulrahmanAlRammah** [comment]
@damithc Thank you.
