### ISSUE TITLE
Practice part 3 [p3.03] UML: CD: code to CD

### ISSUE THREAD

**Issue by annabellekk** [nus-cs2103-AY2425S1/forum#889]
Can I clarify the reasons why each of these are accepted/not accepted?
A: I know multiplicity is optional, but is composition optional to draw too?
B: As shown in part 2 answers 
C: Association roles can be of different names?
D: Multiplicity, association role and navigability acceptable to omit 
E: Unacceptable because association is shown both as an attribute and as a line?

<img width="1019" alt="Screenshot 2024-11-23 at 10 51 35 PM" src="https://github.com/user-attachments/assets/062c1ab3-a29b-4e30-931a-c229b117d9ed">

**Comment by jagdeepsh** [comment]
After looking at the reasonings you gave, they are the same ones I came to as well. I think they are correct too. I could not find in the textbook if it was explicitly said that Composition is optional (for point A), however, I went back to the lecture videos to clarify, under the course website, `week 4`, `Class-Diagrams Intermediate Level`, watch the video by prof at the `4:43 min` mark, he mentions the following and I quote:
> These things (Composition and Aggregation) are what we add to an association to provide additional information
> Even without adding them, the diagram is still correct.

Hope this helps :)

**Comment by damithc** [comment]
@JagdeepSinghNUS is correct. For an association, only the line is compulsory. Everything else is optional additional information.

**Comment by annabellekk** [comment]
Got it! Thank you for the clarifications
