### ISSUE TITLE
Enhanced switch-case style

### ISSUE THREAD

**Issue by adipanda2002** [nus-cs2103-AY2425S1/forum#89]
IntelliJ often recommends this 'enhanced switch' when using switch-case - would using it breach of coding style in the course? 

![Screenshot 2024-08-28 at 1 39 57 PM](https://github.com/user-attachments/assets/43136e8a-13fc-4131-b4fd-156d74d9b542)

**Comment by adipanda2002** [comment]
This is what it looks like for reference.

![Screenshot 2024-08-28 at 1 42 18 PM](https://github.com/user-attachments/assets/8f81b8c5-5953-42cb-863b-334e8189afbe)

**Comment by SeeYangZhi** [comment]
https://github.com/nus-cs2103-AY2425S1/forum/issues/49

There has been some discussion on the switch case conventions that might be helpful.

**Comment by zaidansani** [comment]
Just to piggyback on this for anyone who happens to see this - the group of us discussing this have come up with some consensus, and I've edited the question message to reflect the preferred convention in the issue mentioned above #49.
