### ISSUE TITLE
17/18S1 Comparing answers

### ISSUE THREAD

**Issue by Virusrwj223** [nus-cs2103-AY2425S1/forum#891]
Hi, looking to verify responses for the this paper. (Paper found in NUS Library)
[1718S1.pdf](https://github.com/user-attachments/files/17880287/1718S1.pdf)

**Comment by damithc** [comment]
@Virusrwj223 You may get a better result if you post one question at a time. Same reason why it is better to send multiple small PRs and one big PR.
