### ISSUE TITLE
Drop down page not shown in Exam-reference.pdf

### ISSUE THREAD

**Issue by choaticman** [nus-cs2103-AY2425S1/forum#897]
Hi Prof,

As shown in the screenshot below, certain content that was originally hidden behind a drop down is not shown in the Exam-reference.pdf. May I check if this was intended, or are we supposed to view these contents?

<img width="1143" alt="image" src="https://github.com/user-attachments/assets/48f16096-7819-445f-926f-e489f0ee9c7a">

**Comment by damithc** [comment]
@choaticman As noted in the text at the top of your screenshot, the content of those collapsed panels are already present in another place of the PDF (i.e., in the UML chapter).
