### ISSUE TITLE
Typo in guidance above W2.6

### ISSUE THREAD

**Issue by oolongwater** [nus-cs2103-AY2425S1/forum#9]
Hi, there is a typo. Should 'not' be 'now' instead?

#As you start adding features to your project iteratively, you'll need a way to detect if the new code breaks the existing code. Next, let's learn a rather simple way to do that using a certain type of testing (we'll be learning more sophisticated methods in later weeks).

This also means we are **not** switching focus from the implementation aspect to the testing aspect of SE.

**Comment by damithc** [comment]
@oolongwater Good catch. Thanks for reporting it. Fixed.
