### ISSUE TITLE
Committing after Level-7 before starting on Level-8

### ISSUE THREAD

**Issue by vinceg4** [nus-cs2103-AY2425S1/forum#90]
Hi,  I noticed that the diagram shown on the website immediately creates branch-Level-8 after finishing Level-7 but I made a commit before doing Level-8. Can I check if this is alright and will not cause any interference (with the grading script, etc)?

**Comment by damithc** [comment]
> Hi, I noticed that the diagram shown on the website immediately creates branch-Level-8 after finishing Level-7 but I made a commit before doing Level-8. Can I check if this is alright and will not cause any interference (with the grading script, etc)?

It should be fine @vinceg4
