### ISSUE TITLE
Extra Practice Question (a) - is association roles and labels in class diagrams possibly interchangeable? 

### ISSUE THREAD

**Issue by cth06-Github** [nus-cs2103-AY2425S1/forum#901]
I was looking at the class diagrams drawn for part (a) in Additional practice questions for part 2 in issues #878 and #840 . I realised that most students drew the attributes as association labels, though some drew as association roles (and there seems to have a mix of both too). Here is my version of the answer after my attempt + viewing the comments in both issues:
<img width="537" alt="image" src="https://github.com/user-attachments/assets/58c44d58-0301-4c08-9f60-c3945c2ecde9">

I tend to use association roles to represent the attributes of a class, as highlighted in the picture. Is there any particular point in time we should use association roles, and when for association labels? Or would it always be acceptable to use either of them?<br>

(If there is anything wrong with / comments about the diagram, feel free to point it out, I will appreciate it)

**Comment by damithc** [comment]
@cth06-Github It is OK to use association role, label, or both. Use both when they are complementary but one is enough if they give the same information. The advantage of the role is that it can be the same as the variable name (easier to map to the code) while the advantage of the label is that it can be longer and hence, more informative. e.g., `referenced` vs `text refers to >`.

**Comment by nws321** [comment]
Can I check does your diagram mean Brochure is the one being referenced? And if so, shouldnt it be Handout that is being referenced based on the information given?

**Comment by cth06-Github** [comment]
I see thanks for the clarification prof.
