### ISSUE TITLE
Invalid input testing heuristics

### ISSUE THREAD

**Issue by kyouscrap** [nus-cs2103-AY2425S1/forum#902]
![image](https://github.com/user-attachments/assets/d929e78a-fe5a-4586-8322-831807eb578a)
![image](https://github.com/user-attachments/assets/3182efdb-d74a-4be5-b463-8360395bdac5)

Regarding these 2 questions, I was under the impression that it is okay to test more than one invalid input in a test case as long as you test them individually first. So then why are there two questions true?

**Comment by cth06-Github** [comment]
Good point here, I think the question assumes the context that not all invalid inputs where each of them is found in separate test cases have been tested.

**Comment by damithc** [comment]
@kyouscrap Thanks for bringing this up. I've updated the two questions as follows:

![image](https://github.com/user-attachments/assets/0a9e7d3f-4326-4ed2-b588-df96d1748034)

![image](https://github.com/user-attachments/assets/744150c9-6c30-40e5-a5f6-bd322903b11e)
