### ISSUE TITLE
Clarification on Indentation for Case Clauses in Coding Standards

### ISSUE THREAD

**Issue by chenle228** [nus-cs2103-AY2425S1/forum#903]
Hi everyone,

I would like to seek clarification regarding the coding standard for switch statements, specifically the indentation of case clauses.

The coding standard specifies that **case clauses should not be indented**, but the example provided to illustrate this seems to contradict the rule, as it shows indented case clauses. 
<img width="726" alt="626392e265b3e6c93c00706687b5d85" src="https://github.com/user-attachments/assets/804b995b-7816-41ac-94e7-791d085d6a8e">

This inconsistency was also pointed out in _Quiz 3, Question 16_, where the same example was **marked as unacceptable**. This has caused some confusion for me in understanding the expected style.
<img width="726" alt="c5589c1b884304b0c35d1a9b4dc7ce7" src="https://github.com/user-attachments/assets/0a9311a8-1298-4c8b-a9c7-425da710e8f1">

Could someone kindly confirm if the following is the correct style under the requirement?
```
switch (condition) {
case ABC:
statements;
break;

case DEF:
statements;
break;

case XYZ:
statements;
break;

default:
statements;
break;
}
```
Thank you for your time!

**Comment by gohsl99** [comment]
The answer provided for quiz 3 question 16 is true though:
![image](https://github.com/user-attachments/assets/6979ca84-f325-4acf-9ec8-e1eff6d27402)

**Comment by chenle228** [comment]
Okay thank you!
