### ISSUE TITLE
Practice Paper Part 3 Qn 13

### ISSUE THREAD

**Issue by ZweZeya** [nus-cs2103-AY2425S1/forum#905]
![telegram-cloud-photo-size-5-6204124046719827774-y](https://github.com/user-attachments/assets/a4519415-2e48-431a-b054-66741ed2a779)

Hello, may I know why `Main` uses `Observer`? It seems that `Process` is the one implementing it instead.

**Comment by gohsl99** [comment]
The `Main` component refers to the entire blue box:
![image](https://github.com/user-attachments/assets/0443c182-727d-4978-b0c6-3144dcb9b0bb)

Not referring to just the `Main` class:
![image](https://github.com/user-attachments/assets/e948ffa0-aff1-41a5-a7d7-090a05893e8e)

Therefore, it is correct to say that `Main` component (the blue box) use the Observer design.
