### ISSUE TITLE
Request for the resume code

### ISSUE THREAD

**Issue by winstonlimjy** [nus-cs2103-AY2425S1/forum#906]
When starting the part 3 exam, on the confirmation page to enter the exam, i clicked on `Return to Dashboard`.

However, I am unable to resume the exam as seen below. Could I request for the resume code?

![image](https://github.com/user-attachments/assets/19a30bd2-e27a-4fa6-9b82-5129b7b6a9e5)

**Comment by winstonlimjy** [comment]
After removing the download and re-downloading the exam.

It shows the same page with a different challenge code as seen below

![image](https://github.com/user-attachments/assets/3e87301a-e4fb-4f27-bb6c-8c5e5f090d4c)

**Comment by damithc** [comment]
@winstonlimjy Try resume code `FF731C`

**Comment by winstonlimjy** [comment]
It works now thanks!
