### ISSUE TITLE
Able to minimise the text box for part 2 of the exam?

### ISSUE THREAD

**Issue by matthewyip1511** [nus-cs2103-AY2425S1/forum#907]
![telegram-cloud-photo-size-5-6206007450008667665-y](https://github.com/user-attachments/assets/301be4d4-b5e2-4d98-b25e-94d45e799cfc)

In part 2 of the mock exam, there is a box for typing text which is not required in this section of the exam as it involves us writing on paper. However, I am not able to find a way to minimise it which makes the viewport for the question text very small. Does anyone know how to minimise it for the actual exam tomorrow? Thanks!

**Comment by damithc** [comment]
@matthewyip1511 Related: #888

**Comment by matthewyip1511** [comment]
Thanks Prof!
