### ISSUE TITLE
Overridden methods in subclasses when implementing or inheriting

### ISSUE THREAD

**Issue by LemonDrew** [nus-cs2103-AY2425S1/forum#908]
![image](https://github.com/user-attachments/assets/48dfcfba-c51d-44b2-8c16-51ab26afc85b)

Why doesn't ProgressWatcher have a update(int) under it (eg like option c). Is it because even though ProgressWatcher implements Watcher, it doesn't override the update method so it is redundant to add the method under it? If this is true, then is it safe to say that we only include the method for subclasses if they override that method, otherwise it is redundant to add such methods under the subclasses.

**Comment by niclammm** [comment]
I'm not too sure about this but from what I can gather online, an abstract class implementing an interface need not override the methods declared in the interface. However, the classes that extend from the abstract class have to implement all the methods the interface the abstract class implements.
![image](https://github.com/user-attachments/assets/67054249-7068-4cbf-beda-26049fe58524)
![image](https://github.com/user-attachments/assets/0e20663c-fd8b-46da-a376-a79e906fe86e)
I'm not super sure about this so can someone double-confirm this please? Thanks!

**Comment by MAOXIONGKAI** [comment]
I think this question can be answered by a past response by prof over [here](https://github.com/nus-cs2103-AY2425S1/forum/issues/478)
Basically, if the parent class is overridden by the subclass, then this method has to be included in this sub class, else it must not be included there
