### ISSUE TITLE
Association line branching in object diagrams

### ISSUE THREAD

**Issue by ZweZeya** [nus-cs2103-AY2425S1/forum#909]
![IMG_3416](https://github.com/user-attachments/assets/a434e2a9-d2cf-4727-bcb2-a28d1b1f7f39)
Hello, may I know if an association line could be branched out like this in object diagrams because the equivalent class diagram would have represented this with a single line?

**Comment by DennieDan** [comment]
Hi!, I think you can branch the association line in the object diagram.
This image is from the UML Reference Sheet
![image](https://github.com/user-attachments/assets/b3de93e5-4e0a-49e8-b595-0a4b6cd2f66c)

**Comment by damithc** [comment]
Yep, as @DennieDan said, it's allowed.
