### ISSUE TITLE
I haven't been using no-ff

### ISSUE THREAD

**Issue by Vangmay** [nus-cs2103-AY2425S1/forum#91]
Hello, so recently I realized that I haven't been using no-ff during merges, besides that I have properly made branches and added tags to everything along with proper messages. Will I get a penalty for this? As a result, my git tree looks something like this. 

![Screenshot from 2024-08-28 14-28-03](https://github.com/user-attachments/assets/652844c9-b66d-4ba8-a120-4d6a75ca2a93)

**Comment by damithc** [comment]
@Vangmay It's fine. Use --no-ff in future so that it is easier to see the branch merges in the revision graph.

**Comment by Vangmay** [comment]
> @Vangmay It's fine. Use --no-ff in future so that it is easier to see the branch merges in the revision graph.

Thanks professor, I will use it from now on
