### ISSUE TITLE
Sequence Diagram arrowhead

### ISSUE THREAD

**Issue by DennieDan** [nus-cs2103-AY2425S1/forum#910]
As is mentioned in the textbook, the _lined arrowhead_ is out of scope
> 
![image](https://github.com/user-attachments/assets/3dc5cf66-1d4b-445d-a017-905e8bdfe99d)

Basically, all of the sequence diagram arrowheads we encountered in this course are the first type. Does it mean that if we see a sequence diagram in the exam with the _lined arrowhead_, we can assume it is the _filled_ one?

The following is the diagram I screenshotted from one of the Week 8's videos.
![image](https://github.com/user-attachments/assets/6c4569ab-3578-4ed6-b82c-4e573b89a5df)

**Comment by damithc** [comment]
> Basically, all of the sequence diagram arrowheads we encountered in this course are the first type. Does it mean that if we see a sequence diagram in the exam with the _lined arrowhead_, we can assume it is the _filled_ one?

@DennieDan Yes, that's correct.

**Comment by DennieDan** [comment]
> > Basically, all of the sequence diagram arrowheads we encountered in this course are the first type. Does it mean that if we see a sequence diagram in the exam with the _lined arrowhead_, we can assume it is the _filled_ one?
> 
> 
> 
> @DennieDan Yes, that's correct.

Thank you, Prof!
