### ISSUE TITLE
Course Briefing video, example question 17: What's the difference between buffers and padding?

### ISSUE THREAD

**Issue by somethingfishyfishy** [nus-cs2103-AY2425S1/forum#912]
### This is my answer. Anyone else knows a better answer?

![image](https://github.com/user-attachments/assets/c2233819-841d-409f-8df4-56e25e97938b)

**Comment by cth06-Github** [comment]
https://github.com/nus-cs2103-AY2324S2/forum/issues/989

^You may wish to see this forum thread here. From that thread, my understanding is that padding refers to this particular part in the textbook: 
> inflate task estimates to create hidden buffers
<img width="768" alt="image" src="https://github.com/user-attachments/assets/c39f2583-9512-4a2e-850f-ba15ddf988bb">

**Comment by jan-kai1** [comment]
Don't think padding was discussed at all in terms of project management. Don't think the question is likely to be talking about details like cache and data storage. Maybe just old syllabus?

**Comment by damithc** [comment]
`Padding` in the question is the same thing as `inflating` mentioned in the text below.

> <img alt="image" width="768" src="https://private-user-images.githubusercontent.com/106983097/389495517-c39f2583-9512-4a2e-850f-ba15ddf988bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1Mzk1NzAsIm5iZiI6MTczMjUzOTI3MCwicGF0aCI6Ii8xMDY5ODMwOTcvMzg5NDk1NTE3LWMzOWYyNTgzLTk1MTItNGEyZS04NTBmLWJhMTVkZGY5ODhiYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNVQxMjU0MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MWQ0ZDVlMGVjZGYxZGI3OTA3NzM2MzViNjA5NzFlYjE4ZjMzYWZhZWEwNzYwMDc3YjA5ZGY2MDk5YmU3N2EzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.LUPc5I0cECtG2JHs0WYZCAe51-ASwtZiQILYimNAZuc">
