### ISSUE TITLE
Accidentally redo quiz on canvas

### ISSUE THREAD

**Issue by LemonDrew** [nus-cs2103-AY2425S1/forum#913]
I was looking through my quiz answers on canvas when I accidentally clicked on "reattempt quiz". Just to clarify, this will not affect my quiz marks since the quiz marks are already consolidated?

**Comment by damithc** [comment]
@LemonDrew No, it will not affect anything. You can freely re-attempt quizzes.

**Comment by LemonDrew** [comment]
Thanks prof!
