### ISSUE TITLE
The run() in extra activity 2 does not specify the parameters

### ISSUE THREAD

**Issue by hooyushing** [nus-cs2103-AY2425S1/forum#915]
Hi Prof! The run() method here does not specify the int status. May I ask how do we decide which case it would go into for this question? Thank you!

<img width="687" alt="Screenshot 2024-11-25 at 9 05 57 PM" src="https://github.com/user-attachments/assets/4062555a-6042-4e4b-bae1-b2de88834939">

**Comment by hooyushing** [comment]
In this case, may I ask if it will go into case 3 as it assumes it as the default case if there is no status provided? Thank you!

**Comment by cth06-Github** [comment]
I don't think there is a default case stated. There is no `default` keyword. <br>
Sequence diagram is to show how things interact with each other, for this case for `run()` -- it is possible to show **all** cases. Hint: use the alt symbol. (You may refer to issue #841 and #878 for inspiration/answers, maybe it will provide a clearer idea how showing both cases can be done)

**Comment by hooyushing** [comment]
Thank you! I realised the alt box was the issue I missed

**Comment by curtischang2510** [comment]
Additionally it is worth noting that according to the text book 

> No more than one alternative partitions be executed in an alt frame. That is, it is acceptable for none of the alternative partitions to be executed but it is not acceptable for multiple partitions to be executed.

The main point being it is possible that none of the alternate paths are executed. I did not notice this at first while answering this question and thought exactly 1 path needs to be executed which would make things a lot more complicated.

**Comment by annabellekk** [comment]
Hi Prof @damithc, in this case, an alt frame works since there is a break statement in the switch cases which means it won't fall-through to the following switch cases. But what happens if there is no break statement in the switch case? In that case alt won't work since multiple partitions may be executed.

**Comment by damithc** [comment]
> Hi Prof @damithc, in this case, an alt frame works since there is a break statement in the switch cases which means it won't fall-through to the following switch cases. But what happens if there is no break statement in the switch case? In that case alt won't work since multiple partitions may be executed.

@annabellekk Two options:

1. Use nested alt/opt frames to reflect the actual behaviour.
2. Use an alt frame but add a note to explain in this specific case multiple paths may be taken.

**Comment by annabellekk** [comment]
Noted, thank you!
