### ISSUE TITLE
Multiple end nodes in activity diagrams

### ISSUE THREAD

**Issue by ZweZeya** [nus-cs2103-AY2425S1/forum#916]
![Screenshot 2024-11-25 at 10 01 49 PM](https://github.com/user-attachments/assets/b952ea2d-1b7a-4793-9122-7756ba64877d)

Hello, prof mentioned [here](https://github.com/nus-cs2103-AY2425S1/forum/issues/878) in the comments that end nodes should be different for the additional practice question. When should we consider having different end nodes? Also, the diagram above uses a single end node to represent different outcomes.

**Comment by cth06-Github** [comment]
I think that it is acceptable to have multiple end points, and also acceptable to have a single end point as well. It is a matter of "aesthetics" / readability. Both works so long as we make the diagram not too messy to read. <br>

In the issue you linked, the "end point being different" was meant to refer that the symbol of the end point is not the same as the start point -- the end point symbol should consist of a circle circling the rounded fat dot and not merely a rounded fat dot (rounded fat dot as in a filled circle).

**Comment by damithc** [comment]
> I think that it is acceptable to have multiple end points, and also acceptable to have a single end point as well. It is a matter of "aesthetics" / readability. Both works so long as we make the diagram not too messy to read.
> 
> In the issue you linked, the "end point being different" was meant to refer that the symbol of the end point is not the same as the start point -- the end point symbol should consist of a circle circling the rounded fat dot and not merely a rounded fat dot (rounded fat dot as in a filled circle).

Yup. Thanks @cth06-Github
