### ISSUE TITLE
alt diagram in quiz

### ISSUE THREAD

**Issue by dominopizzaaaa** [nus-cs2103-AY2425S1/forum#917]
Hi all, I was wondering why is option c not correct when it gives the correct output since alt can choose not to take any path?

![WhatsApp Image 2024-11-25 at 22 23 53](https://github.com/user-attachments/assets/1e965d6e-74f7-4ce4-9637-24511b2ee144)

**Comment by cth06-Github** [comment]
Hmm I think while "alt can choose not to take any path" remains correct, perhaps alt frame can only be used when there are **2 or more** paths. If it is just 1 path, we should use opt frame.

**Comment by Incogdino** [comment]
Related to #747
