### ISSUE TITLE
Is delete object notation in a way optional in sequence diagram unless otherwise stated?

### ISSUE THREAD

**Issue by cth06-Github** [nus-cs2103-AY2425S1/forum#919]
This question came about when looking at the answers in #841 and #878 for Sequence diagrams part (c) of the Additional Practice. In #841, the delete objection notation was used to indicate that the Unit object is ready to be garbage-collected, but in #878, there was no indication for the object deletion. Is it alright to omit the delete object notation? Attach a reference image of the Sequence diagram and my question (okay to omit the X?):
![image](https://github.com/user-attachments/assets/0f747e77-45f5-4deb-b593-a7ffbea07371)

In addition, for the videos in [Week 8 Topics](https://nus-cs2103-ay2425s1.github.io/website/schedule/week8/topics.html) going through the sequence diagrams, it seems that it is okay to omit the delete object notation unless otherwise stated
![image](https://github.com/user-attachments/assets/f092b69f-d4f4-469f-ae2a-fb4f2820b4a4)

I understand that showing object "deletion" is possible only if the object is dereferenced. For the `TaskList` sequence diagram, I think the Task object can be "deleted" (as in ready to be garbage-collected) after the `generate()` finished executing as there are no attributes or any variables that are keeping a reference of the Task object. However, it seems that we don't have to show it also. Thus, I would like to clarify when we should use delete objection notation, and whether for the additional Practice part (c), the delete object notation _must_ be shown as in #841.

**Comment by damithc** [comment]
@cth06-Github Normally, the deletion can be omitted if it is not important to the purpose of the diagram. In the exam, you need to be aware of where it can appear in the diagram even if you don't show it. If you miss it altogether (i.e., you didn't even realise an object can be garbage collected after a certain point), it can affect your ability to choose the correct answer option.

**Comment by cth06-Github** [comment]
Ok got it Prof, thank you!
