### ISSUE TITLE
Wrote code on master branch instead of new branch. Any way to fix branching?

### ISSUE THREAD

**Issue by anselmlong** [nus-cs2103-AY2425S1/forum#92]
Hello! I thought I switched to a new branch (branch-level-8) before starting my code, but only after finishing and running git status, I discovered that I'm still on the master branch. Is there anyway to "bring" my code over to the branch? Last time I tried to switch over to the branch and merge, I accidentally reset my progress, so I'm hoping to get a bit more clarification on this!

Also, for some reason my Sourcetree isn't syncing with my local progress, I'm not sure if I messed it up somewhere.
![image](https://github.com/user-attachments/assets/57abf4d7-fcbd-48f3-a30a-2feda081785d)
Here's a picture for reference, but when I commit locally on my command line, it doesn't show up on Sourcetree. 

Any clarification would be much appreciated. Thank you!

**Comment by Domokunx** [comment]
Not an expert but I've also done the same a few times 

I would stash the changes, switch to the intended branch, then apply the stashed changes. [Link to forum explaining this](https://stackoverflow.com/questions/5964118/git-working-on-wrong-branch-how-to-copy-changes-to-existing-topic-branch)

Regarding sourcetree not tracking progress, you probably just have to refresh sourcetree (F5 works for me)

**Comment by damithc** [comment]
@anselmlong It's good enough if you can achieve a revision graph similar to below, irrespective of what the commits in each branch contains. For example, the commit can contain minor tweaks not related to Level-7 and Level-8, provided the branch name is as expected. What matters is you demonstrate you can use branches.
![image](https://github.com/user-attachments/assets/5bdf4753-eb2f-494c-aa46-2770fd2d015c)

**Comment by anselmlong** [comment]
> Not an expert but I've also done the same a few times
> 
> I would stash the changes, switch to the intended branch, then apply the stashed changes. [Link to forum explaining this](https://stackoverflow.com/questions/5964118/git-working-on-wrong-branch-how-to-copy-changes-to-existing-topic-branch)
> 
> Regarding sourcetree not tracking progress, you probably just have to refresh sourcetree (F5 works for me)

Thanks for the link! I realised also that my Sourcetree was somehow tracking the wrong folder. All good!
