### ISSUE TITLE
Is such notation allowed in UML class diagram (or, is this a UML class diagram in the first place)?

### ISSUE THREAD

**Issue by cth06-Github** [nus-cs2103-AY2425S1/forum#920]
<img width="460" alt="image" src="https://github.com/user-attachments/assets/bdce34af-06ea-4ae0-bbc4-f7076cd5bb8e">

^Is the above picture considered an UML class diagram, or say still correct notation? This [picture in Exercise 3 of week 11 Tutorial](https://nus-cs2103-ay2425s1.github.io/website/schedule/week11/tutorial.html) seems to suggest that it is a UML, but the dashed arrow (boxed in green) and the solid arrow (boxed in red) seems to represent input and output respectively, instead of dependency and association with navigability as what we usually do when using arrows. Thus I would like to ask if it is still considered a class diagram and if Yes, are these 2 arrows indeed allowed to be drawn in a class diagram? <br> 

Because in the event that we are asked to draw a class diagram that follows the Facade pattern, I'm wondering if it is correct to add these 2 arrows.

**Comment by damithc** [comment]
@cth06-Github The first is a dependency and the second is an association. It's just the entity at the other end is left out, as they are not relevant.
So, yes, it is a valid UML diagram. The light blue box representing the component is technically not UML but we often use them to mark component boundaries in class diagrams.

**Comment by cth06-Github** [comment]
Ok got it thanks prof.
