### ISSUE TITLE
Issue/doubt about Exam reference pdf

### ISSUE THREAD

**Issue by thisisaditya17** [nus-cs2103-AY2425S1/forum#922]
It contains these closed collapsible boxes. Before this when i tried downloading the pdf version of the textbook i faced the same issue. 
I had to manually open these boxes and then print as pdf but since i can't modify the pdf then we are stuck with this one ig.
There is a separate section of UML in the pdf but it isn't as detailed as in the earlier reference of UML under modeling section.
I know its too late, but if it can be fixed then please do. 
Otherwise just a suggestion or a mention about this issue with the printable textbook version.

<img width="686" alt="image" src="https://github.com/user-attachments/assets/b6e8c283-3984-4c1f-9606-32a402161a79">

**Comment by damithc** [comment]
Related #897
