### ISSUE TITLE
Drawing UML Class diagram for AY17/18 Sem 1 Paper Question 1

### ISSUE THREAD

**Issue by cth06-Github** [nus-cs2103-AY2425S1/forum#923]
![image](https://github.com/user-attachments/assets/3a12ad24-b441-4bee-b6db-6bf3153e148b)
^On the left of the image is the question of the paper (Q1), and on the right are the diagrams to refer to as I explained my 2 questions below. <br>

1] For drawing `Allocation` class, which is an association class as indicated by the code comments in the question, I think the one where I draw it as a concrete class -- the first UML class diagram on the right (without the red arrow) in the yellow region is valid. But if I want to represent it as an association class, would it be mandatory to remove the attributes as indicated in red? I'm wondering if it is the same reason as why we do not show associations as lines and attributes at the same time -- by keeping the attributes indicated in red, we are showing 2 times and therefore we _must_ remove `owner` and `task` from the attribute compartment of `Allocation` class. Is my reasoning correct? <br>

2] Thanks to #891 where [Virusrwj223](https://github.com/Virusrwj223) shared his/her answers. I am wondering for putting in the ProjectManager and StaffManager as per question, should these classes be shown as classes that inherited `Person` class? No where in the question explicitly said that these classes are subclass of `Person`, yet semantically ProjectManager and StaffManager is indeed a person, thus are we expected to catch that subtle hint and make `ProjectManager` and `StaffManager` classes inherit `Person` or is this considered an assumption that we should not make since the question did not explictly specify?

**Comment by ruiming97** [comment]
1. For the first question, I agree with you that the `owner` and `task` should be removed, as you explained. The association class already shows the relationship between `Person` and `Task`. However, I believe the diagram could be made clearer by labeling `allocated to` from `Task` to `Person` or the roles `owner` and `task`, as demonstrated in the example from the textbook below:

<img width="626" alt="image" src="https://github.com/user-attachments/assets/47fee91a-a662-4c62-bf68-7635fd85589a">

2. Good question. I’m also wondering whether we should strictly follow the instructions provided (the inheritance of `ProjectManager` and `StaffManager` is not explicitly specified) or rely on common sense based on how it works in the real world.

**Comment by jagdeepsh** [comment]
Hi just to supplement @ruiming97's point in regards to the first question, I also agree, but wanted to show you a question that came up in the Canvas quiz, `Week 8 Part 1`, with the following example and explanation as well. Hopes this helps :)

<img width="1568" alt="Screenshot 2024-11-26 at 11 34 37 AM" src="https://github.com/user-attachments/assets/5dc954f0-df86-4650-bbc1-62032b7b52f7">

**Comment by damithc** [comment]
To reply quickly:
1. `Person` and `Task` variables should not be mentioned inside the `Allocation` class.
2. Those two classes do not inherit from the `Person` classes. Apparently, they represent the Job/Role, rather than the individual person.

**Comment by cth06-Github** [comment]
Thank you Prof and everyone for your inputs!
