### ISSUE TITLE
What exactly is considered a "What" for code comment (with reference to AY17/18 Sem 1 Paper Q4)

### ISSUE THREAD

**Issue by cth06-Github** [nus-cs2103-AY2425S1/forum#924]
<img width="328" alt="image" src="https://github.com/user-attachments/assets/2c158790-e014-4a14-9901-a51bc5564972">

^In this question we are supposed to suggest 5 code quality improvements. In #891 the original poster shared his/her answers in which it was highlighted that the JavaDoc comment has issues as it should specify the "Why" and "What" of the code instead of writing the "How"(code implementation). I thought the JavaDoc comment is referring to the "What" of the code. From my understanding, "What" is about "the specification of what the code is supposed to do" and "How" is about the explanation how the code works. <br>

I think it is considered a "What" because the JavaDoc comment there describes what the code is expected to do. The "How" can be seen as the even more low-level and nitty-gritty details on how the numbers and spaces are removed + sorting + 10 letters replacement. However, I realised that the function name is "encode" - `encode(String original)`. So in another perspective, it could be considered a "How" because at the same time, the same JavaDoc description can be considered as explaining the step by step process of the code for encode, of how things should get encoded. The "What" is the encoding, i.e. if the Javadoc start with "encodes a string by removing space and numbers..." , it will sound more like a "What". <br>

While I think the main issue is that the first word of the JavaDoc should be "Removes" rather than "Remove", the main question of this case I have is whether the JavaDoc comment is still considered sufficiently a "What"? Because it seems that there can be 2 interpretations here, which feels very subjective.

**Comment by damithc** [comment]
@cth06-Github Yes, this can still be considered as `WHAT` as it describes the desired outcome of the function e.g., it doesn't say HOW the spaces are removed, but only that they should be removed.

**Comment by cth06-Github** [comment]
Thanks Prof!
