### ISSUE TITLE
Sequential vs iterative approach

### ISSUE THREAD

**Issue by Zenkoh1** [nus-cs2103-AY2425S1/forum#926]
<img width="472" alt="image" src="https://github.com/user-attachments/assets/d5f0b022-872f-4fda-a2f8-bd951aab7f9a">

What is the reason the circled option is true (ie. we should use iterative approach)? If I were to just base it off the advice given in the course textbook (picture below) about when to use the sequential model, it would seem that, since Facebook already exists and is a "well-understood problem", I should be going with that. I can think of some reasons why it would make sense (eg. project of cloning Facebook might be too big, so sequential might be too high of a risk), but wouldn't that go against the _main(?)_ guideline given?

<img width="542" alt="image" src="https://github.com/user-attachments/assets/aaa60e5e-a2fb-4090-86dd-64c4062c5055">

**Comment by shotnothing** [comment]
I think the path coverage option feels a lot more correct than the facebook one, which is quite ambigious

like to build a facebook competitor, the app will need to be huge and complex given how many features facebook has, so it sounds hard/unfeasible to develop in one-shot sequentially, not to mention you are developing a competitor, so it needs to be better than facebook (how? add novel features probably i.e. iterative)

path coverage in many cases is much harder to achieve than statement, and can be illustrated with even a simple example like in the textbook, so id put my money on that option

**Comment by Zenkoh1** [comment]
> I think the path coverage option feels a lot more correct than the facebook one, which is quite ambigious
> 
> like to build a facebook competitor, the app will need to be huge and complex given how many features facebook has, so it sounds hard/unfeasible to develop in one-shot sequentially, not to mention you are developing a competitor, so it needs to be better than facebook (how? add novel features probably i.e. iterative)
> 
> path coverage in many cases is much harder to achieve than statement, and can be illustrated with even a simple example like in the textbook, so id put my money on that option

Yup I agree that the path coverage option is the best answer, but what if the iterative approach option was a standalone question, would it be correct and incorrect?

Also, I do agree that it makes sense to do it iteratively, but I think my main concern has to do with whether or not to follow the guideline I mentioned, given that, that is the only explicit guideline given in the textbook (I think? correct me if I'm wrong), to decide sequential vs iterative.

**Comment by damithc** [comment]
@Zenkoh1 Combine what the textbook says, what you have experienced in the project, and imagination on what 'creating a Facebook competitor' would be like, and make a judgement call on if sequential is the right way to go.  There are subjective elements, like, is Facebook a 'well-understood' problem? If so, why does Facebook keep hiring hoards of software engineers to keep evolving it further? Very few non-trivial software are well-understood enough to be done in one-shot, or simple enough to be able to estimate effort accurately.
