### ISSUE TITLE
Can implementation triangle be filled as well? 

### ISSUE THREAD

**Issue by annabellekk** [nus-cs2103-AY2425S1/forum#927]
For inheritance, it was stated that the triangle can be either hollow or filled. Does this apply for the triangle for implementation as well or must implementation only have hollow triangles?

**Comment by jagdeepsh** [comment]
If I am not wrong I think it also applies as well, which means the only main difference is just that for implementation of interface you have a dashed line rather a single line for inheritance. The photo below is from the textbook stating only difference is just the line itself. Hope this helps :)

<img width="728" alt="Screenshot 2024-11-26 at 8 10 00 AM" src="https://github.com/user-attachments/assets/08e8fa59-f554-43e2-a2fd-7e437b606668">

**Comment by damithc** [comment]
Yup, as @JagdeepSinghNUS said, it applies to interface implementation as well. The triangle can be empty or filled.

**Comment by annabellekk** [comment]
Ok, thank you!
