### ISSUE TITLE
Default visibility for abstract classes

### ISSUE THREAD

**Issue by jagdeepsh** [nus-cs2103-AY2425S1/forum#928]
I know for Interfaces, the default visibility in Java is set to `public` for its methods, does the same rule apply for abstract methods in abstract classes as well, regards to Java's default visibility when it was not specified in the question?

**Comment by ruiming97** [comment]
I believe it's `package-private`, supported by the following reference:
<img width="693" alt="image" src="https://github.com/user-attachments/assets/c2743499-6326-4a46-909e-c6cdfb5894ff">


It would be great if Prof. @damithc could provide further clarification on this.

**Comment by damithc** [comment]
@JagdeepSinghNUS In this regard, there is no difference between regular classes and abstract classes.

**Comment by jagdeepsh** [comment]
Noted, thanks everyone :)
