### ISSUE TITLE
How does the activation bar of a method look like in an alt frame? AY18/19 Sem 1

### ISSUE THREAD

**Issue by annabellekk** [nus-cs2103-AY2425S1/forum#929]
Referring to AY18/19 sem1 Q2a (see screenshot below) 
<img width="1042" alt="Screenshot 2024-11-26 at 10 56 19 AM" src="https://github.com/user-attachments/assets/e022f2f3-d228-4e49-b18d-79fe705db402">

What would the if else block look like in a sequence diagram? I have tried drawing it (attaching my attempt below), but I'm not sure when the activation bar of the generate method should break, since there are two cases in which it can be executed. Technically, it should break when the method returns, but if I break at when getTask() returns, wouldn't the activation bar for the [else] condition be incorrect? 
![IMG_5973](https://github.com/user-attachments/assets/dbdb55bf-4bca-477b-ac61-51bbc38eba0f)

**Comment by Gra7ityIC3** [comment]
This question was answered in [Week 8's video](https://nus-cs2103-ay2425s1.github.io/website/schedule/week8/topics.html#:~:text=Drawing%20sequence%20diagrams%20(intermediate)%20%2D%20TaskList%23generateTask()) on Drawing sequence diagrams (intermediate) - `TaskList#generateTask()`:

![image](https://github.com/user-attachments/assets/9f6fc6a0-b6b2-4956-93bf-31547bf87b99)

**Comment by annabellekk** [comment]
Ohh thank you!
