### ISSUE TITLE
UML Diagram notation for Inheritance

### ISSUE THREAD

**Issue by tansanchian** [nus-cs2103-AY2425S1/forum#930]
When a class extends from an abstract class/interface, are we supposed to rewrite the methods in the parent class/interface when drawing the subclass diagram? How about the attributes? Thanks a lot!

**Comment by annabellekk** [comment]
**For abstract class:** concrete subclasses will need to implement any abstract methods in the parent class. But for non abstract methods I think it works as per normal inheritance, i.e. the subclass will inherit the methods directly from the abstract parent class
**For interfaces:** yes, subclasses need to implement all the methods in the interface 
Source: [Week 8](https://nus-cs2103-ay2425s1.github.io/website/schedule/week8/topics.html#:~:text=Drawing%20class/object%20diagrams%20(intermediate)%20%2D%20Person%2C%20Project%2C%20Task)

**Comment by tansanchian** [comment]
Noted, thanks!

**Comment by damithc** [comment]
@tansanchian To be clear, a class in a class diagram should only show methods it implements/overrides, not methods simply inherited from the parent.

**Comment by tansanchian** [comment]
Ok, thanks prof!
