### ISSUE TITLE
Practice Exam p3.04 Why there is a dependency from Activity to ProgressWatcher?

### ISSUE THREAD

**Issue by Elinengu** [nus-cs2103-AY2425S1/forum#931]
When I attempt this question, I didn't realise there is a dependency froom Activity to ProgressWatcher. Here are my (waiting-to-be-corrected) reasoning:
- watch(Watcher) depends on Watcher type of instance
- since there is an association between Activity and Watcher, no dependency is needed

Hence I am not sure why we need an explicit dependency arrow between  Activity and ProgressWatcher. Is it because ProgressWatcher is an abstract class that can be inherited?

![image](https://github.com/user-attachments/assets/f1a1c331-1a4c-40f1-b407-d5176dd5d01f)

**Comment by gabriellegtw** [comment]
I believe it is because the `Activity` class references `ProgressWatcher` class when we declare the `watchers` variable (ie. through `ProgressWatcher.MAX`)

**Comment by Elinengu** [comment]
> I believe it is because the `Activity` class references `ProgressWatcher` class when we declare the `watchers` variable (ie. through `ProgressWatcher.MAX`)

I see! Thank you so much!
