### ISSUE TITLE
How to show inheritance between two interfaces

### ISSUE THREAD

**Issue by charlesliyifeng** [nus-cs2103-AY2425S1/forum#934]
The text book states that:
<img width="546" alt="image" src="https://github.com/user-attachments/assets/be9a975b-2ff3-4e07-9140-d6e68d597a24">

But when implementing an interface:
<img width="610" alt="image" src="https://github.com/user-attachments/assets/8a93953d-9bc1-42a7-93c5-31d5f3122f53">

So should I use a solid line or a dashed line when an interface extends another interface, since extending is technically not implementing that interface?

<img width="568" alt="image" src="https://github.com/user-attachments/assets/890dcccf-3458-4a4b-a8d5-aee814366b21">

**Comment by damithc** [comment]
@charlesliyifeng Use a solid line, same as inheritance between normal classes.
