### ISSUE TITLE
Deleting the catcher smoke test repo

### ISSUE THREAD

**Issue by michaelyql** [nus-cs2103-AY2425S1/forum#938]
Are we allowed to delete the repos for the catcher smoke test? 

And after the course results and grades have been finalized, are we allowed to delete the PE repo as well?

**Comment by damithc** [comment]
@michaelyql 

> Are we allowed to delete the repos for the catcher smoke test?

Yes, you can delete that one.

> And after the course results and grades have been finalized, are we allowed to delete the PE repo as well?

This is best kept until you receive your grade.

**Comment by michaelyql** [comment]
Okay, thank you Prof!
