### ISSUE TITLE
Merge branch popup different from the one shown on the website.

### ISSUE THREAD

**Issue by WuJinhan1** [nus-cs2103-AY2425S1/forum#96]
I am merging branch 7 to the master currently but my popup when I try to do that is different from the one from the website. I want to make sure that I do not do fast forwarding, so which box should I check or uncheck?
<img width="558" alt="Screenshot 2024-08-28 at 4 57 24 PM" src="https://github.com/user-attachments/assets/dc8872e9-a1ae-469a-83a7-274ebc8e31fd">
<img width="483" alt="Screenshot 2024-08-28 at 4 57 35 PM" src="https://github.com/user-attachments/assets/da216f06-7b93-40cd-a883-d76eb0295d1e">

**Comment by damithc** [comment]
@WuJinhan1 Can you post a screenshot of the commit graph showing the two branches?

**Comment by WuJinhan1** [comment]
<img width="1039" alt="Screenshot 2024-08-28 at 8 20 56 PM" src="https://github.com/user-attachments/assets/1a28fe17-0136-4d3f-a291-b879f50648ae">
Here is the commit graph, I have a level 7 branch and a master branch.

**Comment by damithc** [comment]
Seems like a quirk in the Mac version of Sourcetree, as per https://stackoverflow.com/questions/23587750/how-can-i-commit-with-no-fast-forward-option-no-ff-in-sourcetree

Let's wait to see if other Mac users in the class has any inputs on this ...

**Comment by Dominic-Khoo** [comment]
<img width="1037" alt="Screenshot 2024-08-28 at 8 36 46 PM" src="https://github.com/user-attachments/assets/7cb0867e-f8aa-405d-a364-224e1b08dc76">

Make sure you are on the master branch, then click the merge button highlighted in red.

<img width="800" alt="Screenshot 2024-08-28 at 8 39 10 PM" src="https://github.com/user-attachments/assets/d29653bb-de0d-43d3-8025-e6b826f8b105">


Select the branch you want to merge, then ensure that the option highlighted in red 
"Create a commit even if merge resolved via fast-forward"

Hope this helps!

**Comment by WuJinhan1** [comment]
Thank you guys very much!
