### ISSUE TITLE
Git-standard not satisfied

### ISSUE THREAD

**Issue by TechRaj** [nus-cs2103-AY2425S1/forum#98]
I checked the dashboard and it says that I have not been following git standards for my commit messages. Will this result in penalisations? Do I need to rename commits/do new commits that are properly structured? Just wanted to clarify thanks!

**Comment by damithc** [comment]
@TechRaj No need. Keep following it correctly from now on. It will turn green when the latest 5 commits are compliant with the convention.

**Comment by TechRaj** [comment]
Got it. Thanks prof!
