### ISSUE TITLE
Policy on using rebase for iP/tP

### ISSUE THREAD

**Issue by zaidansani** [nus-cs2103-AY2425S1/forum#99]
Context: I want to make changes related to a previous branch that has already been merged into main, and has had other changes on top.

For my other projects outside of the module, I have been rebasing my branch to continue working on it. Since the commit tracking is used for grading - instead of this behaviour, should I be merging my master branch into my other branches that I want to continue on working?

**Comment by damithc** [comment]
> instead of this behaviour, should I be merging my master branch into my other branches that I want to continue on working?

@zaidansani Yes, in the context of this course, this approach is better, as it will not change the timestamp of any  existing commits (unlike rebasing).
